### ISSUE TITLE
Editor: export generated headers to files when compiling the game

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#1007]
Related to a task of making a stand-alone script compiler.
E.g. see #872 

There is a generated script header that is never actually saved on disk, but only passed into compiler via memory. From the top of my head, these include:
* API header; not really generated, but embedded as resource into editor exe.
* Game object symbols declaration: includes script names and/or backward compatible numeric IDs of all the game objects from the game. Also arrays of game objects and their sizes are declared there (e.g. `character[]`, `inventory[]`, and so forth).
* Variables generated by the Global Variables pane.
* Script headers created by the plugins (iirc): they contain plugin API to be used in scripts.

The problem here is that persistent script sources alone are not enough to complete the game script compilation outside of the editor. Therefore all the above should also be written to disk as a preliminary step.

This may also help analyzing any compilation problems, because above headers are not normally accessible by end users.

Questions to consider:
* where to export these to (project root dir, or special "intermediate output" directory).
* when to export...; obviously, if user changes game data, but does not recompile, the last written generated headers will become off-sync. Is this going to be an issue? If so, what could be done about this?

**Comment by rofl0r** [comment]
> API header; not really generated, but embedded as resource into editor exe.

isn't that agsdefns.sh ? i already supply that together with ascc.

> Game object symbols declaration: includes script names and/or backward compatible numeric IDs of all the game objects from the game. Also arrays of game objects and their sizes are declared there (e.g. character[], inventory[], and so forth).

i'd suggest to export these as ash file with a comment on top like "do not modify, generated by engine".

> when to export

yea, i'd vote for "whenever xml file is written"

> where to export

project dir seems like the obvious choice.

**Comment by ivan-mogilko** [comment]
Note: because #1146 is now a ticket dedicated for writing standalone tool, this ticket may be seen as a task of removing same operations within Editor and replacing with calls to standalone tool(s) instead.

**Comment by ivan-mogilko** [comment]
I shall close this, because original idea for this ticket does not seem suitable anymore, after there are tools that generate this data from game project files.

Perhaps we may return to this question when we make Editor use standalone tools instead of running operations internally.
