### ISSUE TITLE
Feature Suggestion: Engine writes Alert messages to stdout on Windows

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1019]
On the Linux Engine, whenever something goes wrong, Abort is called, or sound is not working, the Engine prints messages to the command line.

On Windows, instead we get message boxes. I would like to be possible to have the Engine output to stdout on Windows like it does on Linux, when I launch the Engine from command line on Windows (like `cmd.exe` or powershell). This could be done with an additional flag like `--no-message-box`.

This is because I would like to run windows built games on a Continuous Integration system, and right now, if something is wrong, they spawn a message box, hanging the pipeline.

**Comment by morganwillcock** [comment]
It is probably easiest to get the engine to attempt to attach to the console that it is launched from (if it exists), and set a flag to not use message boxes if this succeeds, rather than add command line arguments.

**Comment by ericoporto** [comment]
I thought about that, but searching on Google, I couldn't find any hint on how to do this on Windows. `Attach` keyword on search engine seems to bring up topics on how to debug things with an IDE.

**Comment by morganwillcock** [comment]
...although something like a CI build probably captures the output directly, rather than launch via a console/shell. So perhaps you do need an argument like `--no-message-box` regardless of whether a console gets attached or not.

**Comment by morganwillcock** [comment]
> I thought about that, but searching on Google, I couldn't find any hint on how to do this on Windows. Attach keyword on search engine seems to bring up topics on how to debug things with an IDE.

It would be this one, I think:
https://docs.microsoft.com/en-us/windows/console/attachconsole

**Comment by jduo** [comment]
I have a fix for this problem in this PR: https://github.com/adventuregamestudio/ags/pull/1088
