### ISSUE TITLE
Custom Say function in dialog script is not working as expected

### ISSUE THREAD

**Issue by ERolfi** [adventuregamestudio/ags#1021]
**Describe the bug**
When defining a custom say function for dialog scripts in General Settings, the custom function applies only to the text defined inside the dialog script. But when marking the "options text" lines with the "say" checkbox, it's still printed using the original say function.

**AGS Version**
3.5.0.22

**Expected behavior**
When marking the "options text" lines with the "say" checkbox, it's should be printed using the custom say function.

**Desktop (please complete the following information):**
Windows

**Comment by ivan-mogilko** [comment]
This is not a bug per-se, but a functionality not yet implemented. It seems I forgot to add this warning to the manual and release info.

The workaround for now is simply to not use "say" checkbox, but put option text as a first line in a corresponding section of dialog script.

The reason it was not implemented is that it requires a different approach and IIRC cannot be processed by the editor, but only by the engine at runtime. TBH I dont remember full details at the moment, this needs to be investigated again. But I think, among other things, I was also concerned that dialog option text may become mutable at some point (there was such feature request).

**Comment by ERolfi** [comment]
And would it be possible to have a keyword or command to reference the text of the dialog line from inside the dialog script? That way I would not need to replicate the text twice

**Comment by ericoporto** [comment]
Probably you are looking for: https://adventuregamestudio.github.io/ags-manual/Dialog.html#dialoggetoptiontext

**Comment by ERolfi** [comment]
Thanks, that will help

**Comment by ivan-mogilko** [comment]
@ERolfi  I don't know if this is documented anywhere, but you may also use "this" keyword in dialog script to refer to current dialog, supposedly this way you dont have to type dDialogName:

<pre>
@1
 player.Say(this.GetOptionText(1));
return
</pre>
(You will have to explicitly use the custom script function though in your case).

**Comment by ivan-mogilko** [comment]
^ The above makes me wonder, why did not I implemented automatic replacement of "say" checkbox with similar line:
<pre>player.Say(this.GetOptionText( option-number ));</pre>

I definitely had some thoughts around this idea, but maybe also had some doubts. I definitely need to write these things down somewhere as I work, for future reference...

Maybe it's worth to add this as a patch to 3.5.0, but following would need to be tested or thought through:
- will it theoretically work if dialog option text is changed;
- how to deal with translations (and how it deals with them now).

**UPDATE:** I *think* the reason of my doubts was this: the "say" checkbox is currently treated as a dialog option property, and there's always a slight theoretical chance that any property will become mutable in future. So if "say" checkbox becomes mutable (would be possible to disable at runtime), then we'd also need a way to disable that first dialog command generated from this checkbox.

Yeah I know this sounds little crazy, but I have this problem of thinking too hard about things...

Anyway, I just thought... even if that ever happens, we would be able to also get "say" checkbox state at runtime as well, and then we may instead generate following (pseudo-code):
<pre>
if (this.GetOptionSayCheck( option-number )) {
player.Say(this.GetOptionText( option-number )); }</pre>
Which would kind of fix the issue, and we'll be all good again.

So... can anyone see any other possible problem here? If not I will definitely try restoring above solution - generating first dialog line out of Say checkbox.
This spoution also has another advantage: it allows us to deprecate one special case of runtime behavior and fully rely on the compiled dialog script.

**Comment by ericoporto** [comment]
Is [this the offending line of code](https://github.com/adventuregamestudio/ags/blob/5f107eb3a24fa319d73321d72fa36ac00c685a4e/Engine/ac/dialog.cpp#L1113) (eg.: The one that could not use Custom Say function) ?

**Comment by ivan-mogilko** [comment]
> I guess the substitution of Say for "CustomSay" happens at build time and there's no property storing this at run-time?

There could be a property storing it at runtime, and this is something I was working on, but then there should be also a mechanism to call custom script function instead of engine one, and I did not and still do not have full concern everything will work smoothly.

> otherwise hitting a compile error will point to lines that don't make sense and can't be traced back

Yes that's another problem, and obviously I am not going to go into adding generated scripts and folders just for this right now. So unless there is an easy way to translate line number from generated to pre-generated when reporting errors, this will become a frustrating issue.

**Comment by ivan-mogilko** [comment]
Perhaps it would be more convenient if we add a special keyword to return dialog's option text instead.
Then user could write it more easily instead of falling back to complex script line.

**Comment by ivan-mogilko** [comment]
> otherwise hitting a compile error will point to lines that don't make sense and can't be traced back

Okay, another (last?) take on this: MAYBE it is possible to generate this say command on the same line where new section starts. In such case it will correspond to the `@option-number` line and all the user lines will stay on their original lines.
I only have a concern about AGS-script syntax not supporting everything necessary for this (there were some precedents when you could not write more than 1 command on line), so no guarantee this will work.
But if it does, sounds okay or there's something else about it that I am missing?

**Comment by ericoporto** [comment]
The engine needs to know this is built with version 3.5.0.23 or something, and in this case, not trigger the above run time function for `if (sayTheOption) DisplaySpeech(get_translation(option_name), game.playercharacter);`

**Comment by ivan-mogilko** [comment]
Yes, that's true.

**Comment by ericoporto** [comment]
I thought of that, but just above you wrote `this.GetOptionSayCheck` which apparently doesn't exist in the Script API but I was not sure.

**Comment by ivan-mogilko** [comment]
> I thought of that, but just above you wrote this.GetOptionSayCheck which apparently doesn't exist in the Script API but I was not sure.

Hmm, yes if it will be added, then extra condition would be required in this place, but maybe not obligatory right now.

**Comment by ivan-mogilko** [comment]
Okay, right, so in this case we'll need some rule to know that we no longer process that flag directly here.

**Comment by ivan-mogilko** [comment]
I think I won't do this right now. Existing feature limitation is a relatively small annoyance (and is documented afaik). But changing how dialog script is generated may lead to further issues, as it also increases connection between data in Game.agf and dialog script.

IMHO we may return to this after we have separated dialog script processing into stand-alone tools.
