### ISSUE TITLE
Editor: Updating translation for a recently translated file may result in loss of work

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#1022]
**Describe the bug**
If you have a game opened in the editor, edited translated file in your text editor, **saved it**, then updated translation from the editor with e.g. some new speech lines, your latest work in TRS file may get lost.

**AGS Version**
3.5.0.22, but the bug may be present since early AGS 3.*.

**To Reproduce**
1. Open any game in AGS Editor.
2. Create a new translation by right-clicking on "Translations" and choosing "New translation".
3. Do "Update translation", this will fill the new translation file.
4. Don't close the editor, go to game folder and open newly created TRS file in a simple text editor.
5. Add one translation under any original line. **Save TRS**.
6. Switch to the editor, and add any kind of text to the script, e.g. type `player.Say("hello");` somewhere.
7. **Don't do anything else**, like saving, compiling etc, - nothing.
8. Update translation by right-clicking on its name in the project tree and choosing "Update". Wait until process finishes.
9. Reopen/reload from disk your TRS file.
10. Observe that your last added translation has dissapeared.

**Expected behavior**
If the TRS file was properly saved prior to doing "Update" (translation) command in the editor, all the translations you added should remain, so long as original lines remain at least (tbh I dont remember rules about lines that you remove from the game).

**Additional info**
From what I found, the nature of the problem is this.
Editor keeps a dictionary of translations in memory at all times, and saves it into TRS file on Update, which seem to work correctly. But it only reloads this dictionary at certain points, such as - game compilation or individual translation compilation. However, it does not reload it just before doing Update, which means at that moment the dictionary may not contain newest translations yet (not sync with TRS).

There's definitely a operation mistake here, and it was not noticed (alot) before probably because no one usually does translation simultaneously with updating the game.

Possibly the order of updating TRS should work about like:
1) Generate lines from the game
2) Load existing TRS and intersect with new generated lines, adding translations
3) Save resulting dictionary

**Comment by AlanDrake** [comment]
This is supposedly fixed by #1779, where translations are reloaded before any operation.
