### ISSUE TITLE
GUI buttons not (completely) greyed out when interface disabled

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1025]
**Describe the bug**
GUI is shown; a "Say" command runs and so the interface is disabled (Wait cursor) and so all the buttons should be greyed out. This is indeed what happens when the game runs in 3.4.1, but is no longer the case in 3.5.

See the following screenshot. All the "round rectangles" are buttons. Only the big rectangle is greyed out, and only partially.

![BugDis1](https://user-images.githubusercontent.com/41213694/71535976-f7154700-290a-11ea-99f3-7d3c0e81dce1.png)

**AGS Version**
master, 5f107eb3 "Common: reorganized BuildAudioClipArray() operations for clarity"

**Game** / **To Reproduce**
- Use the following game (source): http://www.loquimur-online.de/ags/Cloudgame.zip
- Wait for Jake to enter the room
- Press `i` to open inventory
- use Ball lightning
- move cursor off gui to close inventory
- click on ghost head
- “intelligence test” GUI should open
- click on ghost head again
    - when in 3.4.1, observe that all the buttons in the gui are greyed out while "A slightly grumpy giant head" is displayed
    - when in 3.5, observe that only the big button of the gui is greyed out, and only partially (as shown in the screenshot above)

**Expected behavior**
All the gui buttons should grey out (as in 3.4.1)

System: Windows 10 (German)

So, I've looked at the code, and I've found some places with inconsistency that I strongly suspect to be bugs:

As far as I know, `Rect` (rectangle) objects are initialized by giving left column, top line, right column, bottom line, not as Left, Top, Width, Height. However, in the code for `AGS::DrawDisabledEffect()` at Common\gui\guimain.cpp:~686 . the outer `for` loops to `rc.GetWidth()` instead of to `rc.Left + GetWidth()` and the inner `for` loops to `rc.GetHeight()` instead of `rc.Top + GetHeight()`:

```
void DrawDisabledEffect(Bitmap *ds, const Rect &rc)
{
    color_t draw_color = ds->GetCompatibleColor(8);
    for (int at_x = rc.Left; at_x < rc.GetWidth(); ++at_x)
    {
        for (int at_y = rc.Top + at_x % 2; at_y < rc.GetHeight(); at_y += 2)
        {
            ds->PutPixel(at_x, at_y, draw_color);
        }
    }
}
```
The effect would probably be that a stripe is cut from the grey area at the right side and another slice at the bottom. 

`GUI::DrawDisabledEffect` is called, amongst others, in Common\gui\guibutton.cpp:~321:
```
// darken the button when disabled
GUI::DrawDisabledEffect(ds, Rect(X, Y,
spriteset[CurrentImage]->GetWidth(),
spriteset[CurrentImage]->GetHeight()));
```
And this also looks like the width and height are passed into the third and fourth arg of `Rect()`  instead of the right column and the bottom line. This would probably cut off another stripe off the grey area at the right and bottom side, and these effects together would explain the missing amount in the big rectangle of the screenshot above exactly.

The two effects would also explain why the other buttons aren't greyed out at all: For the bottom buttons, Top is much larger than Height and for the right buttons, Left is much larger than Width, so in both cases the `for` loops in `GUI::DrawDisabledEffect()` don't run at all.

Suspecting that this glitch could also show up elsewhere, I've then scanned all the `Rect()` invocations systematically. At first glance, in the following calls the third and fourth arguments seem also to be Width and Height instead of Right and Bottom and thus might be bugs, too:

In Engine\ac\display.cpp:~702
```
// draw the border
draw_color = ds->GetCompatibleColor(play.top_bar_bordercolor);
for (int j = 0; j < data_to_game_coord(play.top_bar_borderwidth); j++)
    ds->DrawRect(Rect(j, j, ds->GetWidth() - (j + 1), topBar.height - (j + 1)), draw_color);
```
(However, this might be correct if the "top bar" is guaranteed to start at the top left, i.e., at (0, 0))

In Engine\ac\guiinv.cpp:~88:
```
// darken the inventory when disabled
GUI::DrawDisabledEffect(ds, Rect(X, Y, Width, Height));
```

In Engine\ac\invwindow.cpp:~297
(third arg)
```
ds->FillRect(Rect(barxp,bartop, windowwid - get_fixed_pixel_size(2),buttonyp-1), draw_color);
```

**Comment by ivan-mogilko** [comment]
There's a RectWH helper function that creates a rect from x,y,w,h, this may be used where necessary in above examples.

**Comment by ivan-mogilko** [comment]
The code in "display.cpp:~702" looks okay at the first glance, because it calculates coordinates by subtracting and offset from full surface width and height.

Not sure about "invwindow.cpp:~297", need to have a closer look.

**Comment by ivan-mogilko** [comment]
@fernewelten I pushed a commit into "release-3.5.0" branch, contents mostly match things you noted: b28ad21aa01d6fc528e4335f83df4a016d387fcf

The ones in display.cpp and invwindow.cpp seem correct, because the "width/height" references there are image bounds, so used as bottom/rightmost coordinates. There were couple of cases without acual error, but where RectWH may be introduced for clarity, but I tend not to do much code refactoring for the patch.

**Comment by fernewelten** [comment]
One of the uses for UI buttons is to just display a sprite that is chosen at runtime. Those buttons don't have an associated clickaction. So they aren't really buttons, they're “GUI labels for graphics” as it were.

But when interaction is off, those “pseudo” buttons are greyed out just like the buttons proper are. That's even a bit confusing for the user because it signals to the user that they can click on an area that isn't really clickable.

So wen greying out buttons, can we only grey out those buttons that have an associated clickaction?

Something along the following lines: (in Common\gui\guibutton.cpp:~318)
```
// darken the button when disabled
// but don't darken buttons that don't have an associated action
if ((draw_disabled) && (gui_disabled_style == GUIDIS_GREYOUT) &&
    (ClickAction[kMouseLeft] != kGUIAction_None || ClickAction[kMouseRight] != kGUIAction_None))
{
    GUI::DrawDisabledEffect(ds, RectWH(X, Y, 
        spriteset[CurrentImage]->GetWidth(), 
        spriteset[CurrentImage]->GetHeight()));
}
```

**Comment by ivan-mogilko** [comment]
> So when greying out buttons, can we only grey out those buttons that have an associated clickaction?

This is open for discussion, but I'd like to separate bug fix and change in behavior. Bug fix goes in the 3.5.0 patch, behavior changes into development branch.
Unless the behavior you suggest was present before?

**Comment by fernewelten** [comment]
I agree that this should not go into a patch. 

It might even need to be postponed to the time when AGS 4 is pursued again because it's a modification that changes engine behaviour. Who is going to check that there isn't **some** game existing **somewhere** at **some time** that depended on “graphic label buttons” being greyed out?

**Comment by ivan-mogilko** [comment]
> It might even need to be postponed to the time when AGS 4 is pursued again because it's a modification that changes engine behaviour. Who is going to check that there isn't some game existing somewhere at some time that depended on “graphic label buttons” being greyed out?

Well... I doubt it's *that* essential, but even if it's, it could be possible to create a behavior property that returns different value for old games.
But your suggestion is definitely valid, I think it's how controls in regular UI behave too.

**Comment by fernewelten** [comment]
I can confirm that the bug has gone away in release-3.5.0, change b28ad21a, at least as far as my game is concerned.
