### ISSUE TITLE
Update libraries to recent versions

### ISSUE THREAD

**Issue by necros2k7** [adventuregamestudio/ags#1051]
libcda 0.5.1
freetype 2.10.1
allegro 5.2.6 
dumb 0.9.3 (fork 2.0.3?)
glad 0.1.33

**Comment by ivan-mogilko** [comment]
We cannot update allegro to 5.2.6, because Allegro 5 is a completely different library with different API, which would require us to rewrite big portions of AGS. And we already decided to replace with SDL2.
