### ISSUE TITLE
Crash when address bar overflows at both ends

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#1054]
Possible bug [reported by forum user](https://www.adventuregamestudio.co.uk/forums/index.php?topic=57814.msg636617834#msg636617834).

> Whenever I put a walk-behind area in a room, save the room, and later edit it again, it says:
>
> "Unable to read the room design-time preferences. This should not affect the actual game data, but the design time-state of all room items will be reset."
>
>Also, there is this error information, which it says to post on the AGS forum:

<pre>
"Error: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index
Version: AGS 3.5.0.24

System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index
   bei System.Collections.ArrayList.get_Item(Int32 index)
   bei System.Windows.Forms.ToolStripItemColle ction.get_Item(Int32 index)
   bei AddressBarExt.Controls.AddressBarExt.Ad dOrUpdateOverflow()
   bei AddressBarExt.Controls.AddressBarExt.Up dateBar()
   bei AddressBarExt.Controls.AddressBarExt.se t_CurrentNode(IAddressNode value)
   bei AGS.Editor.RoomSettingsEditor.SelectOld Node(IAddressNode currentNode)
   bei AGS.Editor.RoomSettingsEditor.RefreshLa yersTree()
   bei AGS.Editor.Components.RoomsComponent.Cr eateRoomSettings(DockData previousDockData)
   bei AGS.Editor.Components.RoomsComponent.Lo adDifferentRoom(UnloadedRoom newRoom)
   bei AGS.Editor.Components.RoomsComponent.Lo adRoom(String controlID)
   bei AGS.Editor.Components.RoomsComponent.It emCommandClick(String controlID)
   bei AGS.Editor.Components.BaseComponentWith Folders`2.CommandClick(String controlID)
   bei AGS.Editor.ProjectTree.ProcessClickOnNo de(String nodeID, MouseButtons button)
   bei AGS.Editor.ProjectTree.projectTree_Node MouseDoubleClick(Object sender, TreeNodeMouseClickEventArgs e)
   bei System.Windows.Forms.TreeView.OnNodeMou seDoubleClick(TreeNodeMouseClickEventArgs e)
   bei System.Windows.Forms.TreeView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNat iveWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNat iveWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callb ack(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"
</pre>

> In the room, I then can't select anything from the "Edit this room's" window. When I test the room, it still works fine though.

[room10.crm.user](https://github.com/adventuregamestudio/ags/files/4397198/room10.crm.user.txt)

**Comment by morganwillcock** [comment]
The crash is from within the address bar component, because it doesn't account for a situation where all of its control have been moved into the its own overflow menu (this gets added on the left side). There is also a built-in in overflow mode from the underlying controls (this gets a button on the right side):

![address_bar](https://user-images.githubusercontent.com/14958747/81485514-86c9eb00-9245-11ea-8726-d05c23caa212.png)

So as long as the final control is deemed to be present, it doesn't crash, although there is now mostly just empty space because the logic only considers and manages its own overflow (the menu on the left side).

The crash occurs when the final control is deemed not to fit either, which given the above example just requires a few more characters to be added to the name. This just seems to be bad logic on the control, and fixing this reveals that all buttons are now moved to the left side overflow menu:

![address_bar_2](https://user-images.githubusercontent.com/14958747/81485779-b37f0200-9247-11ea-81bb-49d6d76253d4.png)

So it nows works as intended but the vibility and lock controls for the layers and objects are missing, and these controls aren't available anywhere else. So fixing the crash is the easy part, but the logic of the control needs changing. I imagine just disabling its own overflow handling might be good enough (unless someone is using some extreme font scaling), because the first two items are of a known width and should actually always fit. The third item is of an unknown width, but the built-in  overflow will probably just deal with it. Replacing the whole bar with something better and less broken would be preferable, but that probably isn't viable in the short term.

**Comment by ivan-mogilko** [comment]
Posted the temp build on forums, now waiting for user to confirm that the issue is fixed (or not).

**Comment by ivan-mogilko** [comment]
A bit late, but two users having relevant crashes confirmed this fixed things for them.
