### ISSUE TITLE
midi: wildfire compatibility

### ISSUE THREAD

**Issue by legluondunet** [adventuregamestudio/ags#1062]
Hello,

I tried AGS on Linux and it does not play midi music?
Anyway do you think Wildfire could be a good option for AGS to play midi music on all OS platform?
--> multiplatform
--> does not need root rights on Linux (userland)

https://www.mindwerks.net/projects/wildmidi/
https://github.com/Mindwerks/wildmidi

Thank you for your help.

**Comment by morganwillcock** [comment]
For the playback to work you need to supply audio patches. It is mentioned in [the readme](https://github.com/adventuregamestudio/ags/blob/master/debian/README.md) to copy a patches file to a location where the engine can find it:

> - in the directory pointed to by the ALLEGRO environment variable; or
> - if $ALLEGRO is not defined, in $HOME; or
> - in the same folder of the AGS executable.

Do you want to give it a try?

There are ongoing discussions at the moment which will likely affect future technical changes, possibly the whole audio backend will be replaced, so thank you for the suggestion.

**Comment by legluondunet** [comment]
I put patches.dat everywhere I could store it but:

**Comment by morganwillcock** [comment]
Where did you get the ags binary from?

**Comment by legluondunet** [comment]
I tried with two different ags version:
snap version
```
$ ags --version
Adventure Game Studio v3.4 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2019 others
ACI version 3.4.3.1
```
and another version provided by Lutris
```
$ ./ags.sh --version
Adventure Game Studio v3.4 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2016 others
ACI version 3.4.1.0
```

**Comment by ivan-mogilko2** [comment]
If I remember correctly, patches.dat are used by "digmid" driver, which is, I think, a digital driver that emulates midi using these patches (?).
https://liballeg.org/digmid.html

Perhaps, try setting explicitly midiid to digmid's index in acsetup.cfg.
Unfortunately in old versions (prior to 3.5.0) midiid and digiid has to be set using a complicated integer number, composed as 
<pre>#define AL_ID(a,b,c,d)     (((a)<<24) | ((b)<<16) | ((c)<<8) | (d))</pre>
so you have to calculate this.
DIGMID's id is `AL_ID('D','I','G','I')`

**Comment by morganwillcock** [comment]
I think the Snap version has issues with the audio system, so that might be the cause of the MIDI errors. It is probably a good idea to try with the latest release and see what happens.

https://github.com/adventuregamestudio/ags/releases/download/v.3.5.0.24/ags_3.5.0.24_linux.tar.gz

**Comment by legluondunet** [comment]
Finally midi works with Maniac Manson enhanced edition, thank you! I will ask Lutris to update  his AGS runner.
