### ISSUE TITLE
show more relevant info in the ROOM tab headers in the editor

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#1066]
when you have a lot of rooms and scripts open seeing only room1.asc, room2.asc, etc makes it hard to read what you are actually doing. 
having the descriptive name I give the rooms in the tab headers would make this easier to read.
having this customizable would be best, like having the option to chose from these display methods in the preferences:
(1)room1name
room1name(1)
room1.asc

where "room1name" is the decriptive name I give the room script in the project explorer of course.

For all other tabheaders this works already, I wouldn't mind having only "I:" in front of an inventory name, but for invitems the tabs work. 
For the rooms it is complicated as there are "room scripts" and the "room room" with images and hotspots both with the same name, but a "S:" for script in front of the room script and the complete room name for the room room should work.

some small icons at the left start of the tab or different colors for different kind of tabs would also make the open tabs easier to distinguish but that is the bigger change... a simple "image"icon and a "script" icon could work...

**Comment by selmiak** [comment]
![ags roomheaders](https://user-images.githubusercontent.com/22618469/82396239-b058f280-9a4d-11ea-9d07-30cbabe5c179.jpg)

just to have an image explaining this suggestion, it's only about moving the script room name, the user gives the room, up, into the name displayed on the room tab. 
Once you have a lot of tabs open and/or have a lot of rooms in the project this change makes it easier to see which room is which when you give them good names!

**Comment by selmiak** [comment]
it should also be helpful to have the icon from the project explorer also in the tab. left side preferable. then the diagonal part of the tab could be at the right side or they collide...

**Comment by ericoporto** [comment]
Briefly looking into this, the `ContentDocument` `Name` property is the one that can do this. We pass the filename as name when we create or update it

https://github.com/adventuregamestudio/ags/blob/317e31a5c868fb6648172a583446cd7dd3badb85/Editor/AGS.Editor/Components/ScriptsComponent.cs#L291

https://github.com/adventuregamestudio/ags/blob/317e31a5c868fb6648172a583446cd7dd3badb85/Editor/AGS.Editor/Components/BaseComponentWithScripts.cs#L58

The room description though, is in the room, not in the script, so something would need to be done for this information to be available from that component.

I could come up with a hack though...

```C#
        public static int ExtractRoomNumber(string input)
        {
            Match match = Regex.Match(input, @"^room(\d+)\.asc$");
            if (match.Success)
            {
                int roomNumber;
                string roomNumberStr = match.Groups[1].Value;

                if (int.TryParse(roomNumberStr, out roomNumber))
                {
                    return roomNumber;
                }
                else
                {
                    return -1;
                }
            }
            else
            {
                return -1;
            }
        }
```

Which would be used in this way...

```C#
        protected void UpdateScriptWindowTitle(ScriptEditor editor)
        {
            int roomNumber = ExtractRoomNumber(editor.Script.FileName);
            string newTitle;
            if (roomNumber == -1)
            {
                newTitle = editor.Script.FileName + (editor.IsModified ? " *" : "");
            } 
            else
            {
                UnloadedRoom selectedRoom = Factory.AGSEditor.CurrentGame.FindRoomByID(roomNumber);
                newTitle = "(" + roomNumber.ToString() + ") " +  selectedRoom.Description;
            }
            
            ContentDocument document = GetDocument(editor);            
            if (document != null && document.Name != newTitle)
            {
                document.Name = newTitle;
                document.Control.DockingContainer.Text = newTitle;
                _guiController.DocumentTitlesChanged();
            }            
        }      
```

**Comment by ericoporto** [comment]
Maybe a pair of flavor (like room script or "regular script") and then some data where we can store the description.

**Comment by ivan-mogilko** [comment]
Sorry, I have edited the above comment, please check out the updated version. It appears that this distinction between "normal" and "room scripts" is already done.

**Comment by ericoporto** [comment]
`Factory.AGSEditor.CurrentGame.FindRoomByID` works with unloaded rooms, the room description is in Game.agf itself. So we could use that to get the description from the room number.

The only remaining thing now is it needs to update when the room description is modified or the room number needs to change when the room id is changed (this probably already happens).

The method that updates the title will also more or less be the same as I mentioned because the room script needs to show the asterisk character when it's unsaved.
