### ISSUE TITLE
Editor, mouse cursor editing pane, setting cursor hotspot via click produces wrong coordinates

### ISSUE THREAD

**Issue by khrismuc** [adventuregamestudio/ags#1068]
In the editor's mouse cursor pane, clicking the cursor image to set the hotspot produces wrong HotspotX / HotspotY coordinates

**AGS Version**
3.5.0_22

**To Reproduce**
1. Edit any cursor mode
2. Click the image to set a hotspot
3. HotspotX / HotspotY are set to wrong values (half of actual offset)

**Expected behavior**
Coordinates corresponding to click

**Comment by ivan-mogilko** [comment]
It looks like it's not coordinates that are wrong, but the sprite is drawn 2 times smaller.

**Comment by ivan-mogilko** [comment]
Should be fixed with #1070.
