### ISSUE TITLE
Wrong possition of speech/text when use the camera to make zoom

### ISSUE THREAD

**Issue by deabriel** [adventuregamestudio/ags#1069]
The speech is drawn over the character when you use the viewport/camera to make zoom.

**AGS Version**
3.5.0_24

**To Reproduce**
Create or edit the actual camera and make zoom in a room
Create a speech.

**Expected behavior**
The speech/text is drawn in the correct position.

**Comment by ivan-mogilko** [comment]
It's interesting to note that speech position do not account for character scaling whatsoever (regular scaling too), as engine uses the plain height of a sprite to calculation a point above it.

**Comment by ivan-mogilko** [comment]
While investigating this I found there's a bunch of other oversights related to new viewport/camera system, so I'll take few more days to make a group fix.

**Comment by ivan-mogilko** [comment]
@deabriel there's a temp build prepared that you may get here: https://cirrus-ci.com/task/4504037129191424

Please tell if it solves this problem for you.

**Comment by deabriel** [comment]
@ivan-mogilko I tested and now the say function works like a charm but the SayBackground still having the same position problem.

**Comment by ivan-mogilko** [comment]
> I tested and now the say function works like a charm but the SayBackground still having the same position problem.

When I test SayBackground with zoomed-in camera Y coordinate seem okay, but it is not centered horizontally over character. Do you observe same behavior or different?

**Comment by ivan-mogilko** [comment]
@deabriel : a new build: https://cirrus-ci.com/task/5700938751016960

**Comment by deabriel** [comment]
@ivan-mogilko Yes, that was the problem, the horizontal position. I did a fast test of this new build and worked like a charm.
