### ISSUE TITLE
Test/Run the game creates too many windows process

### ISSUE THREAD

**Issue by deabriel** [adventuregamestudio/ags#1081]
Every time you Test/Run the game Windows creates too many process (that don't dissapear, you need to stop them manually).

**AGS Version**
3.5.0_24

**To Reproduce**
Create a new game, test/run it and after close/open it a few tiemes. Check the Windows process.

**Expected behavior**
Don't create too many process or stop them automatically when you close the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/49668124/82854247-42457d00-9ede-11ea-8763-efde87324c11.png)

**Desktop:**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
I've never seen anything like this before.

Is it possible to clarify exact steps that lead to a second process appearing?

**Comment by deabriel** [comment]
Everytime I press the play/test button in the editor the new process appear (If I test the game 20 times, there will be 20 process)

**Comment by morganwillcock** [comment]
@deabriel do you use an antivirus software other than what comes built-in with Windows 10?

**Comment by deabriel** [comment]
I use the avast antivirus, I don't know if that's the problem.

**Comment by morganwillcock** [comment]
Could you try adding an exception for the AGS Editor directory and also your game's project directory, and see if that makes any difference?

**Comment by AlanDrake** [comment]
Maybe it's the "engine-not-closing" issue?

**Comment by ivan-mogilko** [comment]
> Maybe it's the "engine-not-closing" issue?

The engine process will be called "game.exe" while the process is "AGSEditor.exe", so I have doubts about what's going on.

**Comment by ivan-mogilko** [comment]
@deabriel have you tried @morganwillcock 's suggestion, and if yes, did that improve anything?

**Comment by ivan-mogilko** [comment]
Possibly a random system/antivirus problem, has not been reported again since, so I'd rather close this.
