### ISSUE TITLE
Game name is not validated or restricted

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#1090]
This was previously validated (although indirectly) through having to match the project directory, but now there is no validation:

Build failure because of AGS.Native string handling (trying to write Game Explorer data):
<pre>Game file name: MyGame™</pre>

Build failure because path is not enforced:
<pre>Game file name: My\Game</pre>

Build failure because valid filename characters are not checked
<pre>Game file name: MyGame?</pre>

**Comment by ericoporto** [comment]
Found an interesting note on [Stackoverflow](https://stackoverflow.com/a/62888/965638) about file names:

> From [MSDN's "Naming a File or Directory,"][1] here are the general conventions for what a legal file name is under Windows:
> 
> You may use any character in the current code page (Unicode/ANSI above 127), except:
> 
>  - `<` `>` `:` `"` `/` `\` `|` `?` `*`
>  - Characters whose integer representations are 0-31 (less than ASCII space)
>  - Any other character that the target file system does not allow (say, trailing periods or spaces)
>  - Any of the DOS names: CON, PRN, AUX, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9 (and avoid AUX.txt, etc)
>  - The file name is all periods
>
> Some optional things to check:
>
>  - File paths (including the file name) may not have more than 260 characters (that don't use the `\?\` prefix)
>  - Unicode file paths (including the file name) with more than 32,000 characters when using `\?\` (note that prefix may expand directory components and cause it to overflow the 32,000 limit)

  [1]: http://msdn.microsoft.com/en-us/library/aa365247.aspx "Naming a File or Directory"

**Comment by ivan-mogilko** [comment]
@ericoporto A function exists Path.GetInvalidFileNameChars().

**Comment by ericoporto** [comment]
@morganwillcock if I understood correctly the bug only manifests by editing the General Settings property `GameFileName` that is in `Editor/AGS.Types/Settings.cs`, and the check goes in `Editor/AGS.Editor/Panes/GeneralSettingsPane.cs` , which should be added here:
https://github.com/adventuregamestudio/ags/blob/760635024c547face5ee423d62ccbf9abc7976f8/Editor/AGS.Editor/Panes/GeneralSettingsPane.cs#L103

The actual validation code could go there directly or if desired be in `Editor/AGS.Types/Utilities.cs` if it should run in the new game wizard too.

**Comment by ivan-mogilko** [comment]
@ericoporto the above function is called after new value is already applied. Property Grid should have a way to validate its valies before assigning them.

**Comment by ericoporto** [comment]
Thanks @ivan-mogilko ! You made me notice the SaveGame extension validation, which could be used to restrict to just letters and numbers.

```C#
set
{
	// Limit what they can set it to
	if ((value.Length > 0) && (value.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0))
	{
		throw new ArgumentException("Game name has invalid filename characters");
	}
	if (value.Length > 127)
	{
		throw new ArgumentException("Game name cannot be longer than 127 letters");
	}
	if (value.Length == 0)
	{
		throw new ArgumentException("Game name can't be empty.");
	}
	_gameFileName = value;
}
```

I looked the `Editor/AGS.Editor/GUI/StartNewGameWizardPage2.cs` and the only significant other validation it does is that the combination directory and filename doesn't exists already (below), but this is not a problem since we want to override it anyway.
```
public string GetFullPath()
{
	try
	{
		return Path.Combine(txtCreateInFolder.Text, txtFileName.Text);
	}
	catch (ArgumentException)
	{
		return "[invalid path]";
	}
}
...
if (Directory.Exists(GetFullPath()))
{
	Factory.GUIController.ShowMessage("The directory '" + GetFullPath() + "', already exists. Please choose another file name.", MessageBoxIcon.Warning);
	return false;
}
```

**Comment by ericoporto** [comment]
Added a check on character values and opened a PR ( #1097  )

**Comment by ericoporto** [comment]
PR closed. It previously validated in the wizard since it had the game path information along and could check if path was valid. A proper solution would have to include that too, which I don't know how to do it. @morganwillcock will work on this now.

**Comment by ivan-mogilko** [comment]
@morganwillcock I know that you were discussing this on discord, could you post your resolution of what has to be done for this issue?
This is the last remaining ticket assigned to 3.5.0 patch3 milestone, it would be nice to resolve soon if possible.

**Comment by morganwillcock** [comment]
So far the only function I have found that is directly associated to checking the name is `CopyStringAndRemoveInvalidFilenameChars` which is in the Windows platform driver and seems to only be used in relation to Game Explorer shortcuts. So if anyone knows the location of any others that would be handy.

To summarise the previous conversation, it was about whether to:
- strip input of whitespace before validating anything, as if the user didn't type it
- throw errors directly from validation functions.

For the first point, the question is just whether " mygame", "mygame ", and " " should be treated as being intentional and valid. If the game name is editable and it doesn't break a build system then probably best to just ignore it and let all issues be handled by validation. The topic came up because one of the suggested checks for validation was whether the string was zero length, which lead me to ask whether this was assuming the input was stripped of whitespace at this point.

For the second problem this is trickier because underlying validation functions are likely checking for very specific reasons which might not actually directly relate to the game name in all situations (i.e. a character might be invalid on NTFS but that doesn't mean it is invalid in use somewhere else), and so this is then linked to whether build targets should have an influence on what is valid or not. It is likely that the game name is defined by the most restrictive use of characters on all platforms but you do not want what is valid to be changeable if build targets are added or removed. So likely there should be a static concept of what a valid name is, it should be conservative in what it approves, and it can be available for use within build targets (particularly whilst Linux builds are staged onto NTFS) and also used by the form validation. It is also likely that you don't want just the first reason why the name is invalid, especially where you need to present the result within a particular context, so I was going to look at trying it where:

- the lowest level of validation throws errors and the highest level function catches them all and rethrows as a message collection to the UI controller
- error messages are just built as a collection and the highest level parent functions throws the message collection for the UI controller. Possibly this allows easier reuse of the individual validation checks, so this seems preferable.

...this is as far as I have thought so far, but I might be able to think/do some more at the weekend. On a vaguely related note, the updated templates and/or manual could also go into the patched release if desired, although there is still a ticket open to add an item to the manual.

**Comment by ivan-mogilko** [comment]
I'd rather propose to go only with 2) for now (no stripping whitespace, but validate filename).

> It is likely that the game name is defined by the most restrictive use of characters on all platforms but you do not want what is valid to be changeable if build targets are added or removed.

This sounds like a reasonable solution. We have a similar approach in the engine where we have function FixupSharedFilename [declaration](https://github.com/adventuregamestudio/ags/blob/master/Common/util/path.h#L71), [implementation](https://github.com/adventuregamestudio/ags/blob/master/Common/util/path.cpp#L179).

Only thing I did not understand is why do you need to pass a whole collection of messages; cannot the message simply list the invalid characters met in the name?

**Comment by morganwillcock** [comment]
>Only thing I did not understand is why do you need to pass a whole collection of messages; cannot the message simply list the invalid characters met in the name?

Potentially there are multiple reasons why an item is invalid is, so just for the example of a filename the two obvious ones are mutually exclusive:
- contains invalid characters
- is zero length

...but potentially errors on other items are not. As an example, in the path `\\host\share\file?` there are two concurrent issues:
- filename is invalid because of the `?` 
- path is a not a local drive specification (unfortunately the engine cannot find the data if this isn't the case, so debug mode doesn't work)

The checks for folder path and drive are also broken, so I'm actually going to try and make some generic functions that can be used to validate arbtrary things are return more than one error message. So at the moment I am trying to fix the file/path checks and error messages, and then I will look again at the actual game name.
