### ISSUE TITLE
Textual Overlays change position if run in Sierra-speech game

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1098]
**Describe the bug**
If the game uses Sierra-with-background speech style and TextWindow gui for text background, changing Overlay's text in rep-exec function results in it changing it's position unexpectedly.

This is easiest to see if using one of the "Typewriter" modules that imitate text typed letter by letter on overlays etc.

**AGS Version**
Seems like a fairly old bug, reproduced from AGS 3.5.0 to 3.2.1 (did not test in older).

**Game**
Following test game uses TypedText module to print text on overlay.
Compiled windows version: [test_sierrasp_overlay--win.zip](https://github.com/adventuregamestudio/ags/files/4834021/test_sierrasp_overlay--win.zip)
Project source: [test_sierrasp_overlay.zip](https://github.com/adventuregamestudio/ags/files/4834023/test_sierrasp_overlay.zip)

**To Reproduce**
Unfortunately I was not able to reproduce this with minimal set of commands. I know that it happens when you have a previously created Overlay and change it's text using SetText method, but I was not able to achieve stable reproduction when doing this in a blank script for some reason (maybe I did something wrong).
It's 100% reproducing if you will use one of the two existing Typewriter modules.

1. Create a new game; it's best to use Sierra template as it already has got a TextWindow set up.
2. In General Settings change speech style to "Sierra with background".
3. In General Settings set Custom text window GUI (it should be 7 if you use Sierra template).
4. Import Typewriter module,
* either Phemar's one here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=48093.0
* or mine here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=54450.0
5. Run a simple typewriter on overlay upon some event (key press etc). E.g. if using my module:
<pre>
Overlay.Typewriter(60, 60, 0, eFontNormal, "This is a test of a typewriter text", eBlock);
</pre>
6. Observe Overlay changing position every tick, as if it's X and Y were decrementing and looping in some range.

**Expected behavior**
Overlay must retain it's position on screen unless script explicitly sets new one.

**Comment by ericoporto** [comment]
This is where the overlay position is getting changed:

https://github.com/adventuregamestudio/ags/blob/c0f2d3e5dadbca4c3c5010628c21ccb14e26d7f4/Engine/ac/display.cpp#L772

**Comment by ericoporto** [comment]
Here's [acwin.zip](https://github.com/adventuregamestudio/ags/files/4834612/acwin.zip) with the change mentioned above.

**Comment by ivan-mogilko** [comment]
Yes, this seems like logical explanation to what is happening, but I'll double-check proposed solution very carefully.

> I looked the code and don't understand in what situation it makes sense passing xx and yy in draw_text_window_and_bar by pointer instead of by value,

It's very not clear indeed, but it is used in `_display_main` function, where `draw_text_window_and_bar` is called passing xx and yy,
https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/display.cpp#L193
https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/display.cpp#L225
and later the returned values are used in call to `add_screen_overlay`
https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/display.cpp#L242

So it seems that your solution will make a difference to current logic. Some other change is required.

> I went back 8 years in commits and still could not find a commit or comment explaining.

This is original code, almost not changed since the code was opensourced. Also, this is one of the most ugly, if not ugliest, part of engine code.

**Comment by ivan-mogilko** [comment]
So, basically, the problem here is that there are two coordinates:
* overlay coords passed by user, initally
* final overlay surface coords that are a result of adjustment when there's an extra border added.

Unfortunately, the latter are saved in overlay struct, so when overlay updates itself, it reuses adjusted coords, instead of original ones. Therefore the proper solution seem to be to make sure overlay save original coords instead. That way the input coords will be kept same.

**Comment by AlanDrake** [comment]
`Overlay_SetText` is not aware that the overlay has been moved, and thus calls `CreateTextOverlay` with the current values decreasing the x/y offset each call by the image border size.
Then when the offset goes below zero, it recenters the overlay and flies off again.

I wanted to be clever and let SetText compensate for the image border, but the result was exactly the same as @ericoporto, which fails to subtract the image border size. Which means my logic was flawed.

So I guess the least painful solution would be saving the internal offset somewhere, maybe in `ScreenOverlay`, and let `draw_text_window` overwrite it instead of screwing up the original coordinates.
It may not be necessary to serialize the offset.

I'll try again after a good sleep.

**Comment by ivan-mogilko** [comment]
> So I guess the least painful solution would be saving the internal offset somewhere, maybe in ScreenOverlay, and let draw_text_window overwrite it instead of screwing up the original coordinates.
It may not be necessary to serialize the offset.

This was my thinking too. But in regards to serialization, either you add real coordinates there, or you recreate overlay on restoring a save using same rules. Latter may require minor refactoring (or maybe not). This was also a reason why I did not want to do this in 3.5.0 patch.

**Comment by AlanDrake** [comment]
You're right, serialization is required after all. I just finished testing my solution.

**Comment by ericoporto** [comment]
Is it not possible to set the variable initial value to something obviously invalid like `-9999` and if that value is read the offset is recalculated? Then it would not need to serialize the information.

**Comment by ivan-mogilko** [comment]
> Is it not possible to set the variable initial value to something obviously invalid like -9999 and if that value is read the offset is recalculated?

The main question is whether it's possible to recalculate it from properties of an overlay. From a quick glance, it's not.


Everything else is not related to this issue.
