### ISSUE TITLE
A possible implementation proposal for AGS command line tools 

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1100]
This issue proposes possible steps to build command line tools for AGS that are maintained in the AGS repository, and that can be used to build an AGS `game.ags` file from the project sources.

_these steps may be wrong and we may decide to close this and go other way, it's alright._

This ticket is a possible implementation to address partially what is described in the ticket #872 .

## The how to

We will build command line tools to bring the functions required to build a game, some of which are currently in the interface of AGS.Native, available through command line. 

All tool will also have a library with it's core functionality. 

These tools libraries are expected to work as close as possible to the source files they use, which should make their command line code as minimal as possible.

## A note on AGS Native

Removal of AGS Native is not the scope of this document since it has more places (outside of the scope of mentioned tools) where it's relevant.

As each tool is built, AGS Native should be modified as possible to link to the respective tool library instead of having any complex logic in itself.

Eventually we can replace AGS Native calls, that are the scope of mentioned tools, and used in the Editor, with either SWIG C# bindings to these tool libraries libraries or a little server that returns requests to the C# AGS Editor. We should prefer, when
possible, to replace the usage with command line calls to the tool.

## Command Line tool organization

Each tool should be on it's own directory on the top level of ags repository at first and later we can move all of them to an `AgsBuildTools/` top directory or other name.

A tool has a directory structure as follows if it's cpp:

```
ToolName/
 ├── src/
 │    ├── file1.cpp
 │    └── file1.h ..
 ├── CMakeLists.txt
 ├── Makefile
 │ 
 └── toolname.cpp
``` 

Any source file that is not relevant to core functionality and is only used for it's command line interface should be on the tool root directory. The `src/` is illustrative and we could use other names more relevant for the tool at the time, as it's possible
a tool may need more directories to organize it's code (like, it could have a `test/` directory). `vcxproj` files should be stored in the toplevel `Solutions/` directory where appropriate.

An example of CMakeLists.txt for the cpp tool is as follows:

```CMake
add_library(libtoolname)

set_target_properties(libtoolname PROPERTIES
    CXX_STANDARD 11
    CXX_EXTENSIONS NO
    C_STANDARD 11
    C_EXTENSIONS NO
)

target_include_directories(libtoolname PUBLIC .)

target_sources(libtoolname 
    PRIVATE
    src/file1.cpp
    src/file1.h
    ...
)

target_link_libraries(libtoolname PUBLIC AGS::Common)

get_target_property(COMMON_SOURCES libtoolname SOURCES)
source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} PREFIX "Source Files" FILES ${COMMON_SOURCES})

add_library(AGS::ToolName ALIAS libtoolname)

add_executable(toolname toolname.cpp cxxopts.hpp)
target_link_libraries(toolname PUBLIC AGS::ToolName)
``` 

For the tools that are written in C# I don't have ideas on how it should be organized, except that csproj files should be in the tool own directory and not under Solutions.

## The command line tools

The basic tooling to build a game we need to create will be:

- `agsorc` : a command line tool to read AGS project files and output the files needed for input in the other tools. This tool is temporary and will cease to exist once the goal is reached.

- `agssprite` : reads an index of sprites and sprites in the folders and produces the sprite blob needed for the engine. This tool can also produce the sprite cache while the editor need it but this can be removed later.

- `agspreprocessor` : this tool does the preprocessing needed for AGS Script files, different from other tools, this tool is writen in C# to easier integrate with the Editor (the others are cpp).

- `agscc` : an AGS Script compiler that takes in preprocessed AGS Script files and generates a single object file as result, representing the compiled script unit.

- `agsroombuilder` : reads XML room descriptors and output the rooms in the format compatible with the AGS Engine.

- `agspack` : reads the output of other tools and assembles a `game.ags` file.

***NOTE:*** if other tool is needed or one tool mentioned is not needed or any other wrong thing mentioned here, please comment.

### `agsorc`

Currently, a lot of information required by other tools exists in the `game.agf` file.

The `game.agf` file is a big xml file which rules are inscribed in the models existing in the AGS.Types library. The easiest way to read this file and reason on it is to use AGS.Types as a reference in the C# project and use it to generate the files we
need as input for other tools.

What `agsorc` does is simply reads `game.agf` and outputs information from it in convenient intermediate format meant to be read by each tool. It's written in C#.

- index of sprites and their paths in the filesystem for `agssprite`;
- game/project settings for `agspreprocessor`;
- Character, Views, and others (including possible project settings) that are considered by `agscc`; 
- game metadata that is relevant to `agspack`;

I believe there is some way to reorganize the game project directory so `agsorc` is rendered useless so we can kill it, this is why it doesn't matter if it's using AGS.Types as is and considered Windows only in this context.

### `agssprite`

This tool is meant to read the sprite index, get the sprites from their paths in the filesystem, convert to a format convenient to the engine and package this format in a way that is convenient for `agspack` to use later.

- this tool _may_ be easier way to address the crash in #702 .
- the place where spritecache is generated through the AGS.Native library is probably [agsnative.cpp#L2158](https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Native/agsnative.cpp#L2158).
- Rofl0r's [agsprite](https://github.com/rofl0r/agsutils/blob/master/agsprite.c) tool may be relevant here as an example similar tool, just keep in mind it does more than we currently need.

### `agspreprocessor` 

This tool can pickup AGS Script files and preprocess the macros in them. It should be used in the AGS Script files before they are passed to `agscc`.

It should be written in C# using the preprocessor code that already exists and is already currently used in the Editor. 

### `agsroombuilder`

This tool can read AGS Room files in XML format and output room intermediate files that can be later read by `agspack`. It also can generate from the room files relevant information that may be needed by `agspreprocessor` or `agscc` to build the Room script files.

### `agscc`

The AGS Script compiler, it takes preprocessed AGS Script files and generates objects that represents the built AGS Script files and other information that can be picked up bi `agspack`

### `agspack`

This tool reads files that are as close as possible to their packaged equivalent and operates them to create a `game.ags` file. If some information described before is considered too distant, example: maybe output of agscc needs to be reorganized before being packed; we then should create another tiny tool to operate the file.

**Comment by ivan-mogilko** [comment]
First of all, tbh I don't like how this is presented. Imo first come list of tasks for building a game, then tools corresponding to them, not other way around.

> Each tool should be on it's own directory on the top level of ags repository at first and later we can move all of them to an AgsBuildTools/ top directory or other name.

I'd rather have them in AgsTools from the start, whether in separate subdirs or not. The root already has got a lot of directories.

**Comment by ericoporto** [comment]
> First of all, tbh I don't like how this is presented.

It's alright!

> IMO first comes list of data, and list of tasks for building a game, then tools corresponding to them, not other way around, because it's that data and tasks that dictate necessary tools.

Right, it makes sense but I did not have clear image of this in my head.

> Right now it's not clear what data is involved and what are steps to get it all to the final form. It's also possible that as we move towards different project format some tools' concept change (or they will get added/removed). So data and build steps have to be explained first. Then each tool needs a clear definition of what goes in (files, options), what goes out (files, output to stdout?).

Yes, it's because I am not sure of all steps either! But you gave me an idea.

You or I could open new entry in this project's wiki to document the current steps and current input and output of each steps involved with building a game. 

Once this entry is sufficiently fleshed out, we create new issue to try to figure out tools that could nicely accommodate these build steps, and then we work on this new issue.

So with this I would propose closing this issue for the time being.

**Comment by morganwillcock** [comment]
I wasn't sure which branch the ideas were related to, but to summarise my own thoughts:
- ags3 changes should be the easiest path to either get better flexibility for existing workflows or get the data into a more open and accesible state (and probabaly the second change points the way to the first)
- ags4 changes should be the driven from project data (i.e. the users files and how they interact with them -> game development) and the final result (build result that runs on many platforms using desirable methods -> game).

So if this is for ags3 and ags4 is real, I would suggest to do whatever is easiest, using anything that is available and licence compatible, and do not worry about longevity of the design. If it is a difficult problem and this is adding a feature and not fixing something, then perhaps it is better left alone and just becomes a design note for ags4.

If this was for ags4 then I would consider the build tools just bridging between the project data and the final result and I don't think it would be benecfial to have either side be influenced by previous or early decisions, only by what the optimal workflow is on the user side and what the final result should be.

**Comment by ericoporto** [comment]
@morganwillcock I do not understand completely your observations.

> If it is a difficult problem and this is adding a feature and not fixing something, then perhaps it is better left alone and just becomes a design note for ags4

The difficulty is relatively. All logic is already in ags, so separating in command line tools is basically just reorganizing code and guessing input data formats for each - I know the content, but should I encapsulate in xmls, in command line options, in yaml files, ...? - and output data format convenient to agspack.

I highly doubt it will be pretty on a first try which is why I invented an ugly orc to generate these inputs however they are needed. I will highlight it:

> I believe there is some way to reorganize the game project directory so agsorc is rendered useless so we can kill it, this is why it doesn't matter if it's using AGS.Types as is and considered Windows only in this context.

In other words, we would need a tool to generate new project files for these tools from the current project files. It's possible at the end we don't need it - because by then the project has changed, becoming convenient for these tools.

Problem is, currently serializing and deserializing the project hold by the editor, although is a single complex big file, appears to offer some benefit for the editor as being a single thing to sync the representation of the objects in the panels to their models and the data on disk - at least that's why I imagine doing something like holding dialogs in separate files not being an easy task. And just noticed this is other thing that needs a tool for it, a dialog preprocessor! But anyway, for starts the complexity of changing the project file would be hidden or there's a converter. 

So maybe the answer is starting them with ags3 and pull the switch to actually using them in ags4? 

Ivan suggested to first detail the steps necessary to build a game with the inputs and outputs and figure out the tools from these steps once these are properly mapped, which I agree, I just need his ok so I can close this.

**Comment by ivan-mogilko** [comment]
@morganwillcock 's point was to make it as simple and effortless as possible for ags3.

**Comment by ivan-mogilko** [comment]
> In other words, we would need a tool to generate new project files for these tools from the current project files. It's possible at the end we don't need it - because by then the project has changed, becoming convenient for these tools.

Also, this sounds again like you are trying to bring project format to the tools, instead of opposite - first defining data and then find what would be necessary tools for that.

**Comment by ericoporto** [comment]
I will write down each current step and data needed at each and output generated and bring it up at relevant time.
