### ISSUE TITLE
Allow importing indexed png as masks

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1113]
Currently importing room masks is restricted to `.bmp` files. This has not been always like this. At some point in the past it was possible to import Room masks as indexed png files. Unfortunately I am having a hard time tracing when this was changed. I only noticed because recently I had to edit some old rooms in my game that had the walkbehind png masks and I noticed I could not import them anymore. 

I noticed the February 2019 build of 3.4.3 allows png import but it requires the png to have exactly 256 colors in it's palette. I swear there was an older version I could import a mask with less colors in the png as long as it was indexed, but I can't seem to find it anymore (I tried the latest 3.4.1 and the result was the same). But now, it needs to be not only 256 colors but also a bmp.

**Comment by ivan-mogilko** [comment]
If this was allowed but no longer works, then this should be considered a bug.

**Comment by ericoporto** [comment]
There's a very good chance it was by mistake because I noticed today in older versions it could import and throw error after `.jpeg` images. I still haven't found the version that allowed lower than 256 colors palettes, but I will keep looking.

**Comment by AlanDrake** [comment]
It wasn't by mistake #548

**Comment by ivan-mogilko** [comment]
So, the #555 only changed the filter in the file dialog, but it does not seem to change anything in regards to loading.

**Comment by ivan-mogilko** [comment]
I now remembered I changed the _filter in file dialog_ #555 , because I thought that AGS cannot import PNGs as room backgrounds (judging by user having problem with that).

**Comment by ivan-mogilko** [comment]
Anyhow, this may be a matter of correctly converting source PNG to 8-bit bitmap, if this is done the support could be restored properly.

**Comment by ericoporto** [comment]
> because I thought that AGS cannot import PNGs as room backgrounds (judging by user having problem with that)

You mean masks right? It always could import png as room backgrounds.

> Anyhow, this may be a matter of correctly converting source PNG to 8-bit bitmap, if this is done the support could be restored properly.

A png can have a palette and be indexed by it and the palette can have up to 256 colors (8-bit). A png can also have a bigger color depth and no palette. When I meant png I meant the ones that have palette.

**Comment by ericoporto** [comment]
I think currently an exported mask can't be reimported - didn't work for me at least. The exported mask has fewer colors on it's palette than 256 - it must be exactly 256 for importing, doesn't accept less colors.

**Comment by ivan-mogilko** [comment]
> I think currently an exported mask can't be reimported - didn't work for me at least. The exported mask has fewer colors on it's palette than 256 - it must be exactly 256 for importing, doesn't accept less colors.

It's supposed to be, and I was fixing this once before. If it still is not, then this is a bug that must be fixed as a patch to 3.5.0.

**Comment by ericoporto** [comment]
![mask_import](https://user-images.githubusercontent.com/2244442/93005687-b9545f00-f529-11ea-8258-b4d68feefed5.gif)

Sorry for the low quality gif, but this is the error I am facing when exporting and importing a walkable area mask.

**Comment by morganwillcock** [comment]
Are you sure that the problem isn't WINE specific? When I had looked previously I thought that WINE was forcing specific image options because handling the requested encodings wasn't implemented.

https://www.adventuregamestudio.co.uk/forums/index.php?topic=57939

**Comment by ivan-mogilko** [comment]
Guess the only option then is to finally implement PNG mask import.

> Are you sure that the problem isn't WINE specific? When I had looked previously I thought that WINE was forcing specific image options because handling the requested encodings wasn't implemented.

Is there a way to detect this problem programmatically? Then maybe editor would be able to warn user.

**Comment by rofl0r** [comment]
> Are you sure that the problem isn't WINE specific? 

is the bitmap created via winapi functions ? if so there's a good chance they have a bug there.

**Comment by ericoporto** [comment]
The craziest part for me is I use the same 3.20 Wine prefix for some years now. I think the Editor uses Allegro through AGS native to create the bitmap masks for export but not sure on it. Last time I looked Allegro code for writing bitmaps it was very straightforward, I don't remember seeing windows API calls there. Anyway, is just boring to export and import all the 4 masks when I can't do this directly - I have some rooms which were created from others as template but I use the mask export to "sync" these rooms where they are similar, basically walkable areas and regions.

**Comment by ivan-mogilko** [comment]
> I think the Editor uses Allegro through AGS native to create the bitmap masks for export but not sure on it. Last time I looked Allegro code for writing bitmaps it was very straightforward, I don't remember seeing windows API calls there. 

Creating bitmap is one thing, saving it is another. It's being saved using C# method:
https://github.com/adventuregamestudio/ags/pull/555/commits/ad8b01f48987c03235c15239f18b4d5d310bdcfa#diff-ecc1cb51bf68a4d66e8ed6096a32dc76R545

**Comment by rofl0r** [comment]
it's relatively easy to write code that writes bmp manually, but i suppose it's better to report this to wine bugtracker so they at least know that some people need this functionality.

**Comment by rofl0r** [comment]
@ericoporto has this been reported to winehq? assuming that's why you close this now.

**Comment by ericoporto** [comment]
This has been fixed by Wine 6.0 release

**Comment by ivan-mogilko** [comment]
@ericoporto I am kind of not sure if this should be closed. There are two things here: a bug in wine that did not let you import bmp for mask, and ability to import indexed pngs for masks. May the latter still be useful for some people who prefer to work with png?

**Comment by ericoporto** [comment]
I will reopen but I don't think working in it is useful since @persn has a version in the works that uses images as mask directly.

**Comment by rofl0r** [comment]
ftr, this was the mentioned post in ags forums describing the bug that according to @ericoporto has been fixed in wine 6.0:

> I did install it (not through PlayOnLinux) but I can see the same problem, the deduplicated warnings are:

```
    0009:fixme:shell:ShellItem_QueryInterface not implemented for {00000144-0000-0000-c000-000000000046} (unknown)
    0009:warn:ntdll:NtQueryFullAttributesFile L"\\??\\C:\\users\\mwillcock\\My Documents\\wine_export4.bmp" not found (c0000034)
    0009:warn:palette:GDISelectPalette invalid selected palette (nil)
    0031:fixme:ole:Context_CC_ContextCallback (0x144ce8/0x144cec)->(0xa47011, 0x35afa44, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
    0009:warn:wincodecs:BmpFrameEncode_Initialize ignoring encoder options.
    0009:warn:palette:GDISelectPalette invalid selected palette (nil)
    0009:fixme:gdiplus:GdipGetNearestColor (0x1bae90, 0x33ebac): Passing color unmodified
    0009:warn:palette:GDISelectPalette invalid selected palette (nil)
```

> The "invalid selected palette" message is being reported all the time, sometimes just by moving the mouse, so I imagine the problem is likely:

```
    0009:warn:wincodecs:BmpFrameEncode_Initialize ignoring encoder options.
```

> From a very quick look (maybe in the wrong place), it doesn't look like there is any support for 8 bit color:
> https://github.com/wine-mirror/wine/blob/ba9f3dc198dfc81bb40159077b73b797006bb73c/dlls/windowscodecs/bmpencode.c

**Comment by ericoporto** [comment]
This is weird, this is working for me since an older release candidate of 6.0 from last year and made the cut until the final release (from I think last week? It's recent) as far as I know, since I have been using this on my game. :/

I am using GIMP to work with the bmp image and the palette is correct there too for the now 8 bit bitmap exports.

**Comment by ericoporto** [comment]
@morganwillcock since you are mentioned in rofl0r message can you confirm that this is fixed for you too on Wine 6.0?

**Comment by ivan-mogilko** [comment]
> but I don't think working in it is useful since @persn has a version in the works that uses images as mask directly.

Hm, did not think about that.

But these masks would have to be converted to AGS format anyway, right? So there likely will be a need to have same code.

**Comment by rofl0r** [comment]
following the above git link and replacing the commit sha1 with `master`, then clicking on `history`, i found this commit: https://github.com/wine-mirror/wine/commit/ee6dd81e922145ca7b70cb1de01a8795119b824b#diff-c8fad0a1c95f2f3715c02b95600f5d7e8d81322ba14665ed205f195500481ead

so it seems it's indeed fixed in wine.

**Comment by morganwillcock** [comment]
@ericoporto I am struggling for free time at the moment (and I had to give that computer away) so I haven't got an easy way to directly re-test. But just based on the changes, as noted above, it does look like the encoder options were added.

**Comment by persn** [comment]
> But that does not explain when this have changed and why.

 I did some experimentation because I wanted to save/load masks as .png on disk in relation to #469. Saving a .png to disk is definitely buggy, loading it back in C# it's suddenly 32-bit with the palette gone, and the color values are all messed up (byte value 0 suddenly becoming 16 and such).

Opening up the image in gimp however I can see the palette is still physically present, but all the colors have shifted one position, palette color on index 1 is now in index 0, index 2 is now index 1, and index 0 is now index 255 so the mask end up with wrong colors so I conclude that something odd happened already when the image was exported.

Some more debugging I notice that there's something special with the first color of the image palette, it's hardcoded alpha value to 0, probably to make drawing easier. I try setting it to 255 like the rest of the colors and now I can import/export in .NET fine, and the colors doesn't shift in gimp.

I assumed .NET did something weird when saving png images with transparency so I studied the PNG specification and checked the image files in a hex editor, but it all looks fine really. I even tested if physically removing the TRNS header with the transparency data had any effect, and sure enough, the images behaved a lot nicer after taking it out.

The solution to supporting png may simply be to not hardcode the first palette color alpha value to 0 which is what I've already tried in my work when loading masks in my open room refactor. It's a little early yet so I don't know if there's other side effects

**Comment by ericoporto** [comment]
> Saving a .png to disk is definitely buggy,

You mean through wine or winapi/.NET runtime?

**Comment by persn** [comment]
Through the .NET runtime

**Comment by ivan-mogilko** [comment]
I already don't remember full story here, but I just tried in AGS 3.5.1, and found that it can actually import indexed PNGs as room masks. AGS does not show appropriate file filter in the dialog, but you may either put full file path, or `*.png` to show them.

Can anyone else test and confirm this?

**Comment by ericoporto** [comment]
- there was an error when exporting masks in old wine versions, that was fixed upstream.
- it was possible to import indexed PNG masks of arbitrary numbers of colors, but at some point it started to require exact 256 colors, I used Aseprite with a 40 color palette, so this required me to fix up manually all my masks palettes (that I imported), which was 4x100 (masks x rooms).
- I added the opinion this was not worth pursuing since ags4 with open rooms allows natural edit of the masks, without the requirement to import them.

**Comment by ivan-mogilko** [comment]
> I added the opinion this was not worth pursuing since ags4 with open rooms allows natural edit of the masks, without the requirement to import them.

But it will have to import (load) them anyway? For display in the editor, and when compiling the room.

**Comment by ericoporto** [comment]
> Can you try persn's PR (#1278 ) to see if files saved with <256 palette work?

I tried, the behavior is this:

- You can't import png, only .bmp files are allowed
- You can directly edit the file using a pixel editor (I used Aseprite), but if the png is saved with less then 256 colors it crashes the Editor.

**Comment by ivan-mogilko** [comment]
@ericoporto hmm, ok, so this is still an issue.

Could you post an example of png with smaller palette for the reference?

**Comment by ericoporto** [comment]
here is one: [mask_test.zip](https://github.com/adventuregamestudio/ags/files/7925795/mask_test.zip)

**Comment by ivan-mogilko** [comment]
So, if I understood right, the problem is related to *both* `bmp` and `png` files that have less than 256 palette size:
I tried the old bmp example you posted in [comment above](https://github.com/adventuregamestudio/ags/issues/1113#issuecomment-691557164) and it also cannot be loaded as a mask.

Note that both images are *loaded*, but they are represented as 32bpp images by .NET. Which means they may technically be used, it's just that AGS does not think they are suitable for masks.

At the same time, here's a png that works:
![8-bit-png](https://user-images.githubusercontent.com/1833754/150800482-7f192296-72e8-43a7-bc6d-26e7b1f7c18f.png)

I also tried very old AGS 3.2.1, and had exactly same results with pngs (one works, other does not).

Here I have 2 questions:
1. Would it make sense to add pngs to file filter again to let users select them? As it seems that the problem is similar among bmp and png, and theoretically users may have same exact problem with bmps.
2. Would it make sense to open a new ticket, describing the actual problem we uncovered?

**Comment by ericoporto** [comment]
This is super old, but it seems AGS now can actually import masks that have fewer colors without problem. In my tests even using alpha doesn't matter, the original palette gets discarded and we get nice traditional AGS masks colors in the room editor, which is the expect behavior I had in mind really. But only bmp files are supported in the selector.

As indexed png files are not supported, I am not sure if I close this and open a new ticket with the same exact title.

**Comment by ericoporto** [comment]
Closing this in favor of a new and right to the point issue in #1768
