### ISSUE TITLE
english.tra not working in Linux Version of Game

### ISSUE THREAD

**Issue by JPRuehmann** [adventuregamestudio/ags#1132]
**Describe the bug**
In the Linux Version off Wendy Whedon The English Translation won´t work.

**AGS Version**
Adventure Game Studio v3.4 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2018 others
ACI version 3.4.1.15

**Game**
https://shai-la.itch.io/wendy-whedon
**To Reproduce**
1. open acsetup.cfg
2. add translation=englisch
3.  Run Game
4. Runs still in French

**Expected behavior**
Should Run in English
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 
 - Version: 18.04 LTS (32Bit)

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel Something]
 - OS: [e.g. Android Q]

**Additional context**

**Comment by ivan-mogilko** [comment]
@JPRuehmann please tell, do you add the `translation=english.tra` in the default acsetup.cfg located in game directory, or user config in the save directory?

**Comment by JPRuehmann** [comment]
In the Default acsetup.cfg.
BtW where is the save Directory?
Since I have´nt configured anything for the Save Directory it should be the Game Directory.
ags --help tells nothing for translation.

**Comment by ivan-mogilko** [comment]
> Since I have´nt configured anything for the Save Directory it should be the Game Directory.

By default ags creates user config and saves in $XDG_DATA_HOME/ags/GAMENAME/

**Comment by JPRuehmann** [comment]
Thanks that was it, after deleting the Save Folder in .local/share/ags it works.

**Comment by ivan-mogilko** [comment]
On a side note, we def need to improve the situation with config/saves location, as it's been often confusing people.
