### ISSUE TITLE
OpenGL on Linux does not properly resize the game window

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1145]
**Describe the bug**
When running a game on Linux, after initializing OpenGL renderer, the created window sometimes appears much smaller than expected. The game is not stretched (shrunk) to it but only top-left corner is shown, which hints that engine "thinks" the window is a right size.

As soon as user moves the window around (holding by the title bar), it expands to correct size.

I suspect something may be wrong with our linux-specific code in OpenGL renderer, where it resizes x11 window, causing window  to not update itself properly, until its moved; like some window event is not received in time (I am fantasizing here).

**AGS Version**
3.5.0

**To Reproduce**
Not sure yet tbh, maybe it happens when the window is very close to the size of desktop, but that's a guess. Need to investigate more. Happens all the time on my Ubuntu 16.04 virtual machine, but I only recently received a user report with a main linux os.

**Expected behavior**
Window should be sized properly if that operation was successful at all.

**Comment by morganwillcock** [comment]
When I try the window is not resizable, which may explain why it goes wrong when someone manages to resize it.

**Comment by ivan-mogilko** [comment]
> When I try the window is not resizable, which may explain why it goes wrong when someone manages to resize it.

It's not about user resizing it, the window is initially created wrong size. Simply moving the whole window around (dragging by the title bar) makes it expand to the right size automatically.

**Comment by ivan-mogilko** [comment]
#1239 fixed it for me, and also Allegro 4 code does similar thing as in pushed fix. Currently only waiting for one user's confirmation to be certain.
