### ISSUE TITLE
command line option to specify which config file to use

### ISSUE THREAD

**Issue by legluondunet** [adventuregamestudio/ags#1163]
Hello AGS team,

I'm writing a game script on Lutris (games platform for Linux) which will use AGS.
I need support about an issue.
I put a config file in main game folder, acsetup.cfg.
But when AGS launch it copies this config file in /home/your-username/.local/share/ags/your_game/.
Then AGS only take care of the cfg file located in /home/your-username/.local/share/ags/your_game/.
Modifications done on acsetup.cfg in main game folder are no more taken into account.
Is there a way to tell AGS to not copy config file in user profile and just take in account the config file in main game folder?
Our installs are locale, we don't want to use user profile folder, Lutris should manage AGS option in game folder (or other place we could choose).

Thank you for your help.

**Comment by ivan-mogilko** [comment]
Hello.
There's a dedicated ticket for this problem: #961

I will copy your comment there, and close this as a duplicate.
