### ISSUE TITLE
bug: when started with --fps, CTRL-E is passed to the game

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#1176]
CTRL-e, which can toggle between max FPS and game-set default is supposed to be caught by the engine and not passed to the game. but this is not what happens. therefore in the game "Abducted - 10 Minutes" (available on AGS website, 0.9 MB), during the intro is played, the CTRL-E is ignored. one has to wait (or skip) until intro finished in order to make it work.

**Comment by ivan-mogilko** [comment]
This is a simple fix, but opened a pull request for testing just in case: #1186
