### ISSUE TITLE
Overlay.X and Y properties set/get inconsistency

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1180]
Comparing the setter and getter for Overlay.X and Y one may notice that setters apply x and y fields directly:
https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/overlay.cpp#L83

However the code of Overlay.X and Y getters retrieve calculated value from get_overlay_position which may return an offseted coordinate:
https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/overlay.cpp#L73

Note this is the original behavior from <= AGS 3.2.1.

The value returned by getters may have following meaning:

* If overlay.x is OVR_AUTOPLACE then engine _treats overlay.y as a character ID_, and calculates overlay rect relative to character's position in the room, then translates to screen coordinates through the viewport.
* Otherwise, following may happen:
    * overlay may be flagged as being "relative to room" (it has RelativeToScreen flag which is usually treated inversely), in which case its coordinates will be again translated to screen coordinates through the viewport.
    * additionally if it's an automatic overlay with text window drawn on it (created for speech etc), then coordinates are shifted by offset (which is a text window border/padding). AFAIK the offsets may only be negative (thus moving coords up-left). (For more historical context see #1098, #1104)

In short, the position returned by Overlay.X and Y may be not at all what user may have set, and even in different coordinate system.

My personal view on this is that if there's an API property X then it should return exactly same thing as was set, with only exception when engine could not apply a required value because it was out of range and thus corrected it. And definitely there must be a rule about coordinate system (if setter expects room coordinates then getter returns same, and similar with screen coords). If there's a separate calculated value then it should be returned by a different (perhaps readonly) property or not at all.

It's also interesting to note that there's no check for special OVR_AUTOPLACE in setters. I am very curious what will happen if one sets their script overlay to x = OVR_AUTOPLACE and y = some character ID. That might as well work, in which case it's another unexpected and undocumented feature.

**Comment by ivan-mogilko** [comment]
Fixing this could've been faster than writing above ticket, and frankly I just can't think of reasons not to simply return actual x/y fields just like setters assign these. But at the same time I wonder if someone has more to say about this.

I was trying to remember if there's a case when user may legitimately receive these recalculated coordinates.
* In case of custom script overlay, these are displayed using text window if you set "Custom text window GUI" in general settings. Therefore their getters will return coords with offset.
* As of now blocking speech and Display overlays are not exported to script api, hence you cannot even read their properties.
* Background speech overlay, however, is accessible, returned by Character.SayBackground. If I understand correctly, its coordinates are specified in room system, but returned in screen coords (afaik they never use text windows though hence no offsets).

Above means in theory that these "wrong" values may have already been used in older scripts, so this is something to account for.

**Comment by ericoporto** [comment]
I haven't yet made a small reproducible game (working on it), but I think if you are using the `Speech.TextOverlay`, if the room has scrolling and the camera is in a different position (I am in a very big room, far from it's origin), you can't set the overlay X or Y position - the issue I have is the overlay simply disappears, when reading it's X and Y position, it's set to a different position than the one I set, like a really negative position.

**Comment by ivan-mogilko** [comment]
> I think if you are using the `Speech.TextOverlay`, if the room has scrolling and the camera is in a different position (I am in a very big room, far from it's origin), you can't set the overlay X or Y position - the issue I have is the overlay simply disappears, when reading it's X and Y position, it's set to a different position than the one I set, like a really negative position.

Maybe you have to provide room coordinates in such case? The Overlay should have "use room coords" flag internally, unfortunately it cannot be read from script, only guessed, if that's a either an overlay returned by SayBackground or Speech.TextOverlay with Speech.Style == eStyleLucasArts.

**Comment by ericoporto** [comment]
> Speech.TextOverlay with Speech.Style == eStyleLucasArts.

Just for the record, it only doesn't happen part of this issue if not only the Speech.Style is Sierra but also if the character speaking has a Speech View.

But the returned X,Y position is still wrong, and if you read the X and Y position and set it back to the overlay the difference will make the overlay run away...

**Comment by ivan-mogilko** [comment]
I don't have a full picture in my head right now, but want to add this for the record, in case we overhaul this coordinate mess in ags 4.

In regards to OVR_AUTOPLACE mode, which makes overlay follow the selected character.
I am leaning to the idea that Overlay must not have a connection to the character, because Overlay is supposed to be very simple graphical object.
Perhaps, this connection could be reversed, and instead the Character should have a reference to Overlay, serving as a Background speech for them.

**Comment by ericoporto** [comment]
I think this was fixed by #2395 but GitHub didn't pick up for some reason.
