### ISSUE TITLE
Editor: F1 does not work correctly in various editor windows

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1181]
**Describe the bug**
Hitting F1 in the editor supposed to work as a context help, opening CHM on certain article using Index words. In AGS 3.5.0 this does no longer work for all or almost all windows. Comparing with previous versions, this worked correctly in 3.2.1, but broke for couple of panes in 3.4.*.
I don't yet know if this is problem with editor not updated to new index, or manual missing some data (or both).

**AGS Version**
3.5.0.

**To Reproduce**
Open the editor. Open General Settings, for example, and hit F1. The manual opens on the table of contents, and "Game options" will be filled in the Index.
Open any character for editing and hit F1 again. The manual will try to find "Characters" in the index, but there's no such entry in the index anymore.

**Expected behavior**
F1 should work correctly to open a page for current working window in the editor.

**UPDATE:**

List of panels where F1 still not works:
* [x] General Settings
* [x] Default Setup
* [x] Colours pane
* [x] Text Parser pane
* [x] Dialog pane
* [x] Cursor pane
* [x] Font pane
* [x] Script editor (?)
* [x] Room editor

**Comment by ericoporto** [comment]
apparently the panels that fails are loonking for sub entries here -> https://adventuregamestudio.github.io/ags-manual/Settingupthegame.html

This can be fixed by adding a page for each panel instead - there is actually an entry for most panels, but most of the text from settingupthegame has never been moved. It's possible that there are subpanels and in this case there has to be a way to jump to a sub-topic.

**Comment by ericoporto** [comment]
> Text Parser pane

This pane topic in the manual is called "The text parser" but in the Editor, it's:

https://github.com/adventuregamestudio/ags/blob/aaf16f2ddc68e96a83fd2450f699a61c8cfef580/Editor/AGS.Editor/Panes/TextParserEditor.cs#L42

**Comment by ivan-mogilko** [comment]
> This pane topic in the manual is called "The text parser"

I'd rather suggest to rename that, as using articles for index is not good, i think.

**Comment by ivan-mogilko** [comment]
> This panel topic in the manual is called "Dialog Script"

These are not same, imo, the Dialog Script article is about scripting, but the panel has other controls too. Such article should tell about how to create dialogs and options, and how all these controls work.

**Comment by ericoporto** [comment]
> I'd rather suggest to rename that, as using a/the articles for index is not good, i think, and we don't do that anywhere from what I can see.

Done.

> These are not same, imo, the Dialog Script article is about scripting, but the panel has other controls too. Such article should tell about how to create dialogs and options, and how all these controls work.

I think we need to create a new page then, and include links on this page for both Dialog Script and the Dialog from script API as a see also of sorts.

**Comment by ivan-mogilko** [comment]
> It's possible that there are subpanels and in this case there has to be a way to jump to a sub-topic.

Btw, I tried to search for this recently, but failed to find any good solution so far; the only thing I found was this:
https://stackoverflow.com/questions/20694982/msft-html-help-how-to-reach-second-level-of-keyword
this is not about CHM viewer, but MS HelpViewer (the next kind of program), and the method to call a sub-keyword involves a system-dependent hack, so not suitable anyway.

> The alternative appears to jump on a topic by using it's topic id (HelpNavigator.TopicId), but in this case it's something to solve in the generation of the chm manual - generating unique topic ids.

I guess eventually we have to do that, or even leave CHM and move to something contemporary that allows more freedom.

**Comment by ivan-mogilko** [comment]
This is resolved now (using updated help file).
