### ISSUE TITLE
potential bug in game data parsing between versions 2.60 and 2.70

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#1184]
**Describe the bug**

in GameSetupStruct::read_customprops we have code that's activated when data_ver >= kGameVersion_260, but games compiled with 2.6.2 seem to end their ac2game.dta file directly after the last view name.

while single-stepping through ags i noticed that the code here

```c
        for (int i = 0; i < numinvitems; ++i)
            invScriptNames[i] = String::FromStream(in);

        for (int i = 0; i < numdialog; ++i)
            dialogScriptNames[i] = String::FromStream(in);
```

reads actually stuff of some sprite files.

so i think above block should be inside `if(data_ver >= kGameVersion_270)`
but i'm not 100% certain whether the right value to put would be kGameVersion_270,271,or 272 as i only tested with 272 (for which the values are there as expected)

**AGS Version**
latest master

**Game**
for example larry 2 point & click, or a demo game (default template) compiled with AGS 2.6.2.

**To Reproduce**
load such a game in ags, set breakpoint on GameSetupStruct::read_customprops, see which strings are loaded into invScriptNames. it seems to be either junk values or music/sprite data from files that are appended to the ac2game.dta inside the exe pack.

**Comment by ivan-mogilko** [comment]
Curiously, I stumbled upon this line earlier today, and wondered if there's a mistake.

**Comment by rofl0r** [comment]
i just tested with 2.7.0, the default game template produces an ac2game.dta file ending with these bytes:

```
00010F60   00 56 49 45  57 31 00 56  49 45 57 32  00 00 69 4B  .VIEW1.VIEW2..iK
00010F70   65 79 00 69  50 6F 73 74  65 72 00                  ey.iPoster.
```

whereas in 2.7.2 they end with

```
00011140   00 00 56 49  45 57 31 00  56 49 45 57  32 00 00 69  ..VIEW1.VIEW2..i
00011150   4B 65 79 00  69 50 6F 73  74 65 72 00  00           Key.iPoster..
```

so after the inventory names, there's an additional zero byte.

**Comment by rofl0r** [comment]
in 2.7.1:
```
00011070   00 00 00 00  00 00 01 00  00 00 00 00  00 00 56 49  ..............VI
00011080   45 57 31 00  56 49 45 57  32 00 00 69  4B 65 79 00  EW1.VIEW2..iKey.
00011090   69 50 6F 73  74 65 72 00                            iPoster.
```
so the code should look like

```c
if(data_ver >= kGameVersion_270) {
        for (int i = 0; i < numinvitems; ++i)
            invScriptNames[i] = String::FromStream(in);

    if(data_ver >= kGameVersion_272) {
        for (int i = 0; i < numdialog; ++i)
            dialogScriptNames[i] = String::FromStream(in);
    }
}
```

**Comment by rofl0r** [comment]
i think bugs like these could be caught in the future by checking whether reads are inside the boundary of the embedded ac2game.dta.
