### ISSUE TITLE
New compiler: local variable of zero-size causes runtime interpreter error

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1193]
@fernewelten
Consider following script:

<pre>
struct EmptyStruct {
};

function game_start()
{
  EmptyStruct s;
}
</pre>

Running this script results in runtime error:

> Error: Error running function 'game_start':
> Error (line 8): stack pointer was not zero at completion of script

**Expected behavior**

I don't know if it should be allowed to create variables of zero size, but even if they are allowed they should not cause stack pointer errors.

NOTE: old compiler did not cause runtime errors, probably was not advancing stack pointer at all in this case.

**Comment by ivan-mogilko** [comment]
Note, new compiler prevents from creating zero-sized managed objects with error "Trying to emit allocation of zero dynamic memory".

**Comment by fernewelten** [comment]
Run time errors are bad; if the Engine doesn't like allocations of zero length then the compiler should avoid triggering that condition, of course.

As far as I read the error, the compiler calculates different lengths for the empty struct: one value when it is allocated and another when it is freed. So this would explain why the stack is non-empty after the function finishes. I'll have a look what's awry.

If there are two empty structs, one immediately allocated after the other, then they would both have the same address. But if the structs contain some function then that function might rely on the fact that `this` for the one struct differs from `this` of another struct. So should we perhaps force empty structs to have a length of 4 bytes?
