### ISSUE TITLE
New compiler: allows to assign dynamic array to an object pointer

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1194]
@fernewelten 

If there's a variable of Type* type, new compiler allows to assign a dynamic array of same Type to this variable:

<pre>
Character* c = new Character[10];

Character* c_arr[] = new Character[10];
Character* c = c_arr;
</pre>

Both examples compile without errors. However, I am not sure if the bytecode this produces is meaningful, and what exactly will this pointer point to. For example:
<pre>
Character* c = new Character[10];
Display("name = %s", c.Name);
</pre>
Unexpectedly this does not error, and instead displays an empty string ("name = ").

If you take following example:
<pre>
Character* c_arr[] = new Character[10];
c_arr[0] = player;
Character* c = c_arr;
Display("name = %s", c_arr[0].Name);
Display("name = %s", c.Name);
</pre>
First time it displays player's Name, but second time it again displays an empty string.

**Expected behavior**

You should not be able to assign dynamic array of T to the normal managed pointer T*.

**Comment by fernewelten** [comment]
That's a bug: The new compiler doesn't downgrade dynamic arrays to pointers to the first element.
I'm onto the case and will issue a fix soon.

**Comment by ivan-mogilko** [comment]
Fixed.
