### ISSUE TITLE
New compiler: minor mistake with forward struct declaration

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1195]
@fernewelten 

If you make a forward managed struct declaration, when doing actual declaration later you may omit "managed" keyword and compiler does not care.

<pre>
managed struct SomeType;

import void Func(SomeType* obj);

struct SomeType {
    // contents
};
</pre>
Above works well, and struct is indeed treated as a managed one.

Should this be more strict and demand indentical declaration in each case?

---

Also, in my opinion, the error message for non-managed struct forward declaration is not clear.

E.g. if you have
<pre>
struct SomeType;
</pre>
compiler reports:
`Error: Forward-declared 'struct's must be 'managed'`

I think this message may be occasionally misinterpreted by user, as if they should just add "managed" keyword to make it work.
What about saying "Only managed structs may be forward-declared" instead?

**Comment by fernewelten** [comment]
Hi Ivan,
In my opinion, for the first you've uncovered a bug, and the compiler should require the managed keyword when the forward declaration has been managed. What do you think would be better?

For the second, good point; I'll fix it.

**Comment by ivan-mogilko** [comment]
> In my opinion, for the first you've uncovered a bug, and the compiler should require the managed keyword when the forward declaration has been managed. What do you think would be better?

Yes I also agree, because otherwise this may lead to peoples' confusion when you have same struct declared differently in different places.

**Comment by fernewelten** [comment]
Turns out that the code had a similar problem with respect to 'autoptr' and 'builtin'.

Fixed in #1197
