### ISSUE TITLE
AGS 4: Add Overlay.ZOrder property

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1202]
Following might be not hard to implement, but I was curious to hear other opinions, and see if maybe I am missing anything.

### Brief recap

Overlays are primitive dynamically created game objects that contain an image, has a position, and don't have any behavior on its own (may be manipulated by the engine states though). Image may be either taken from a pre-existing sprite, or generated as a block of text (aka "textual overlays"). Position may be referring either screen or room coordinates; latter used mainly to display speech over character's heads; but overlays are always drawn on "gui layer", above the room. User-created overlays are always screen-related.

Overlays have two Z positions on screen: behind and above GUI. This choice is hard-coded:
* custom overlays (user-created, background speech) are displayed behind GUI;
* speech overlays (text & portraits) are displayed above GUI (I think this was made so there could be character speech describing inventory items, and similar purpose).
* overlays are not sorted among themselves, their drawing order is matching their order of creation (last created is drawn above all).

There are two big limitations with overlays now:
* User cannot z-order them among themselves or other game objects.
* They cannot be put inside the room (and because they have no z-order they won't be as useful there).

This ticket is about the first problem, the second is best to be dealt afterwards as its own task, because it has its own nuances.

### Proposal

1. Add integer ZOrder property with meaning similar to GUI.ZOrder.
2. GUI overlays are *sorted among the GUIs* according to [same rules](https://github.com/adventuregamestudio/ags-manual/wiki/GUI#guizorder).

The sorting is ascending, those with lower z-order are drawn behind and with higher z-order above (in accordance to existing rules).

*Special overlays and backward compatibility*

To maintain existing behavior special overlays (ones created by the game's own logic) must have z-order to either appear behind or above all GUI. This could be done either by setting very large hard-coded values (+/-), or by adjusting their z-order everytime a GUI's one is set. The first solution obviously may not work if user set even larger ZOrder for GUI, but the second probably would make sense only for backward compatible mode (if we have one in ags4), because in the new games users may want to rearrange these special overlays too.

Speaking of which, we may also add properties which define default z-order for special overlays, because it may be inconvenient or impossible for user to set one for these overlays right after their creation.
For example, Speech.DefaultZOrder property could be used to set default speech and portrait z-order, and so forth.

**Comment by AlanDrake** [comment]
You also mentioned other objects, are you planning to include a way to make overlays mingle with room object baselines?
I know there was an implementation of room overlays, though I never tried it.

**Comment by ivan-mogilko** [comment]
> You also mentioned other objects, are you planning to include a way to make overlays mingle with room object baselines?
I know there was an implementation of room overlays, though I never tried it.

There's a way to see previous editions of the ticket (by clicking on "edited" line with arrow on the header). They had paragraphs regarding overlays in room, which I later removed, because realized there will be more changes due to how software renderer works with rooms, and it may be just easier to focus on one problem at a time.
The implementation existed somewhere, but it was a very quick hack, and overlays were drawn above everything without z-order.
https://github.com/ivan-mogilko/ags-refactoring/tree/experiment--roomoverlays

But yes, I believe room overlays are also possible, and may write a separate ticket for that. In short, baselines are like z-order and they even have same sorting rule in ags (lowest behind, highest above), so reusing same ZOrder property should work.
The most trouble will be with software renderer, which does not draw walk-behinds as separate sprites like other renderers do, but has an optimization where parts of walkbehind is merged with character/object sprite, and the results are stored in a character/object image cache arrays. Perhaps this may be refactored to let include overlays too.

**Comment by ivan-mogilko** [comment]
An experiment: https://github.com/ivan-mogilko/ags-refactoring/tree/ags4--overlayzorder

I think it works, but still need to think couple of details through.

**Comment by ericoporto** [comment]
[Zorder.zip](https://github.com/adventuregamestudio/ags/files/5974757/Zorder.zip)

Played a bit with z-order, made a little "game", I like having this property and as far as I can tell it work!

**Comment by ivan-mogilko** [comment]
Resolved by #1206.
