### ISSUE TITLE
Room editor zoom slider will throw exception when dragging like a diabolical madman

### ISSUE THREAD

**Issue by persn** [adventuregamestudio/ags#1205]
**Describe the bug**
When dragging the zoom slider in the room editor, quickly and violently, it will throw ArgumentOutOfRangeException

**AGS Version**
ags4 branch, b4960813c9ae710af0b2b3b0c018d43ee61b7038
Tested on master branch also, but could not reproduce there.

**Game**
I'm guessing it works on any game

**To Reproduce**
1. Open a room in the room editor
2. Drag the zoom slider all the way to left
3. .Try dragging it right really fast and hard, so that the mouse cursor goes out of the screen
4. Throws ArgumentOutOfRangeException

**Expected behavior**
Not throw exception?

**Screenshots**
![ZoomCrash](https://user-images.githubusercontent.com/1510803/107445574-0706df00-6b3d-11eb-9e42-561573d47c08.gif)
![image](https://user-images.githubusercontent.com/1510803/107445579-0a9a6600-6b3d-11eb-8d3f-f6d97f75b62c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by ericoporto** [comment]
@persn have you tried clamping to see if it works alright - I know it will prevent the exception, but I wonder if the Room Editor could be in a invalid state.

**Comment by persn** [comment]
Nope. Tried nothing. Don't want to think about anything else than the refactor job right now

**Comment by ivan-mogilko** [comment]
This could be after my recent changes to zooming controls.

**Comment by ivan-mogilko** [comment]
I pushed one fix, there was a silly mistake where I clamped value to the size instead of size - 1.

**Comment by persn** [comment]
Fix confirmed
