### ISSUE TITLE
King's Quest III Redux freezes at specific point

### ISSUE THREAD

**Issue by HunterZ** [adventuregamestudio/ags#1213]
**Describe the bug**
Playing AGD's King's Quest III Redux using AGS 3.5. The game freezes during the scene in which you give the wizard cookie-infused porridge - by which I mean the characters stop talking and just stand there looking at each other, while the clock ticks upward and the background noises continue to play.

**AGS Version**
Running with: AGS 3.5.0.30
Compiled with: AGS 3.2.1.1115

**Game**
King's Quest III Redux from http://www.agdinteractive.com/games/kq3/download/download.html

**To Reproduce**
1. Load attached save file [agssave.027.KQ3Save.zip](https://github.com/adventuregamestudio/ags/files/6017225/agssave.027.KQ3Save.zip)
2. Open inventory
3. Select porridge
4. Use porridge on wizard
5. Wait for scene to come to a halt

**Expected behavior**
Watch from 2:29:13: https://youtu.be/mAfIhJTRuWk?t=8953
Freeze should NOT happen around 2:30:41, just after the player character finishes reciting the incantation, but does.

**Screenshots**
See video.

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Version 10

**Additional context**
Also recently reported by another user on Raspberry Pi: http://www.agdinteractive.com/forum/viewtopic.php?p=238894#p238894

Nothing appears in the log at this time, except maybe these lines:
```
WARNING: channel 2 - same clip assigned
Game.SetAudioTypeVolume: type: 1, volume: 78, change: 1680
Game.SetAudioTypeVolume: type: 3, volume: 78, change: 1680
WARNING: channel 2 - same clip assigned
```

**Comment by ivan-mogilko** [comment]
Hmm, while testing this I also noticed that portraits are not displayed in the side where they should. After loading this save during the first dialog wizard's portrait is displayed on the right, while in original it displayed on the left, according to where wizard stands.

**Comment by ivan-mogilko** [comment]
The freeze itself seem to happen because the script keeps checking for some mp3 audio position (calls GetMP3PosMillis) which was either never reached, or skipped somehow. As the music is no longer playing GetMP3PosMillis returns 0, and game is stuck in an endless waiting loop.

**Comment by ivan-mogilko** [comment]
Alright, so this was the stupidest mistake possible, and should be fixed with 57d34dda42bf69d511689e74d6fa8fcd4bfa8913 in master branch.

**Comment by ivan-mogilko** [comment]
Guess I'll close this then, this fix will become a part of 3.5.1 release, hopefully soon enough.

**Comment by michael-ts** [comment]
@HunterZ  Sorry, this may be a stupid question, but how exactly do you play KQ3 "under" a specific AGS version?  The download appears to be self contained and just runs.  Is there some way to load it into AGS and play it that way, in some kind of debug mode?   I tried, but there's no AGF file in the distributed runtime.

**Comment by ericoporto** [comment]
If you run the AGS binary and pass the path of the game it should run it will run, be it an .ags or .exe, it should figure it out. If you are on Windows it may be simpler to just copy paste acwin.exe (and the SDL dll in newer versions) on the game dir and double click acwin.

**Comment by ivan-mogilko** [comment]
@michael-ts it sounds like you tried to load the game into the editor? You need to use the engine executable (this is what @ericoporto refers to).

**Comment by michael-ts** [comment]
@ericoporto @ivan-mogilko  Thanks, that worked!  I guess that was a bit of a disappointment, I was hoping running it under AGS would give me something like debugging output or better insight into the underlying game.  (I have been trying to identify what all the GlobalInt variables are for, but so far have mostly only figured out those related to timekeeping)
