### ISSUE TITLE
AGS4 CI: run new compiler tests

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1217]
There's already "compiler_tests" job running, but it runs old compiler tests, and we have new ones in the ags4 branch.

Need to add new compiler tests, I guess preferably as a separate job to make it easier to distinguish errors.

**Comment by ericoporto** [comment]
I added the tests. I placed all the tests in separate tasks under a same job because the Windows machine in the CI is taking too much to start, so I thought it would be slightly faster in this way.

**Comment by ivan-mogilko** [comment]
Alright.
