### ISSUE TITLE
New compiler: corrupted XML messages while running from editor

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1219]
@fernewelten 
I'm experiencing random Editor exceptions from badly formatted XML messages coming from the Engine, when using the new compiler.
They look like there's some corruption happening randomly in the portion regarding script names:

Broken  examples:
```
<?xml version="1.0" encoding="Windows-1252"?><Debugger Command="EXIT">\n<EngineWindow>5445382</EngineWindow>   <ScriptState><![CDATA[in "", line 215
from "", line 330\n]]></ScriptState> </Debugger>
```
```
<?xml version="1.0" encoding="Windows-1252"?><Debugger Command="EXIT">  <EngineWindow>1314858</EngineWindow>   <ScriptState><![CDATA[in "ModalDialog.asc", line 58\nfrom "çé\nˆèé\n¸ëé\nhíé\n(îé\nàà\n"b…nøæ", line 136\n]]></ScriptState> </Debugger>
```

What the latter looks like when not sending broken XML:
```
"<?xml version=\"1.0\" encoding=\"Windows-1252\"?><Debugger Command=\"EXIT\">  <EngineWindow>1250534</EngineWindow>   <ScriptState><![CDATA[in \"ModalDialog.asc\", line 58\nfrom \"GlobalScript.asc\", line 136\n]]></ScriptState> </Debugger>"
```

It happens rarely, and it's the same kind of error I was experiencing from running upgraded projects without a full rebuild.
I suspect there's something causing memory corruption of the area containing script name tokens, but I'm not sure how to investigate further.

**Comment by ivan-mogilko** [comment]
Well, first of all we'd need to find whether names are corrupted by compiler and saved like that, or they are corrupted within engine during runtime.

**Comment by fernewelten** [comment]
On a hunch, possibly, the script name might sometimes be unset in some way for the **very first** line number metacode that is emitted after the script name changes. OTOH, the line numbers in your examples seem to be too high for that.

I'll dig around. Unfortunately, intermittent bugs are hard to hunt.

**Comment by fernewelten** [comment]
I might have found the bug. That code wasn't as easy to verify at a glance as I would have liked. So I reformulated the passage to make it clearer.  There were similar passages in the vicinity, making it likely that similar bugs could hide there, too. So I took the occasion to also re-formulate those passages that were similar to the buggy one.

**Comment by ivan-mogilko** [comment]
Forgot to close this, @AlanDrake reported that he does not have this error anymore after #1220 got merged.
