### ISSUE TITLE
32K sprite limit in kSprfVersion_Last32bit

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#1230]
according to commit message of 66bb2f7db86bf52f5533b0c44e474d9baa0ac27f kSprfVersion_Last32bit has a limit of 32K sprites. why? couldn't the value be read as unsigned short and have 64K possible values? are negative sprite numbers used somewhere ?

**Comment by ivan-mogilko** [comment]
I guess it could.

**Comment by rofl0r** [comment]
so could we change it to use unsigned short and support up to 64K sprites for spritecache version 6? that would be helpful for agsprite.

**Comment by ivan-mogilko** [comment]
I believe it might be okay to do, and if it is we may change new 32-bit index to unsigned too fwiw. Just need to check around the engine code to make sure. There may be places where index is compared to -1 to defined unassigned or invalid value, but that would work with unsigned too (if compared explicitly with -1 and not < 0).

**Comment by ivan-mogilko** [comment]
Alright, I did some research. First of all, I was bit too quick to mention unsigned 32-bit index without thinking. All the script API currently uses signed ints as sprite indices, in fact ags script itself does not support unsigned ints. Therefore changing to unsigned 32-bit index in the sprite cache will be literally useless, as no one will be able to address it from script. Ok, formally speaking, it will be possible by using negative numbers if you calculate them correctly, but this is something what we probably should not rely on.
Again, formally speaking, it might be possible to reinterpret sprite indexes in game data as unsigned, and modify them all in the Editor, but after all that hassle it will be still inconsistent with script api.

Regarding 16-bit values, I found that some object fields refering sprites were signed 16-bit (I found this problem before, but forgot about it, maybe there is even a open ticket somewhere). This is a problem on its own, even with 32-bit signed indexes. So I guess if we allow to interpret legacy indexes as unsigned 16-bit that will not make situation worse than before: those fields that could have 32-bit indexes will still be able to, and those that could not still won't.

**Comment by rofl0r** [comment]
> Regarding 16-bit values, I found that some object fields refering sprites were signed 16-bit.

huh. does that imply nobody ever even used the possibility to use spritenumbers > 32K ?

> These values were part of the old script API and plugin API too iirc, but I guess this may be still changed to unsigned, as the size is same, and all the valid old values will be still valid.

right, i think script api uses int, not short, usually. i don't think it should be an issue either as spritenumber is now saved as 32bit internally since 2 years.

**Comment by ivan-mogilko** [comment]
> huh. does that imply nobody ever even used the possibility to use spritenumbers > 32K ?

Firstly no one could before AGS 3.5.0, because sprites were limited by 30.000. But then, I'm unaware if anyone exceeded that, I only received notifications that people get "dangerously close" to 30k and were asking if it could be increased (so I did increase it to 90k).

**Comment by rofl0r** [comment]
i think this could be easily tested with the default game template after changing character sprites to have indices 32766,32767,32768,32769 and so on (i.e. range immediately before-after running out of signed 16bit range)

**Comment by ivan-mogilko** [comment]
To clarify, the "short" I found is used for room objects to define their "Graphic". Graphic property itself is int (32-bit) but internal struct stores this value in short: https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/roomobject.h#L36

(May need to search more around the code, but this is only case I remember now)

The characters use Views, which already reference sprites as ints (https://github.com/adventuregamestudio/ags/blob/master/Common/ac/view.h#L26)

**Comment by ivan-mogilko** [comment]
Well, I pushed a change that interprets old format topmost index as uint16_t (4645eec145a9c095da3f2cd6b551ea3134526cf7). I don't have means to test it now, but guess it should work (unless i missed something silly).

**Comment by rofl0r** [comment]
cool, thanks

> i think this could be easily tested with the default game template after changing character sprites to have indices 32766,32767,32768,32769 and so on (i.e. range immediately before-after running out of signed 16bit range)

if someone gets around to produce such test game as exe, i can use it to test my implemtentation too.

**Comment by ivan-mogilko** [comment]
Setting room object's Graphic to >32k causes new engine to crash, so there are two issues: a) it should not crash at least, and b) it should possibly support 32k+ sprite indices.

**Comment by rofl0r** [comment]
thanks, it seems to work as of commit 4645eec145a9c095da3f2cd6b551ea3134526cf7

i borrowed a windows pc and created a testgame where the last character (roger) move loop goes from sprite 32765-32771 (test by going upwards, so you see back of char), game works both with spritecache v11 and v6 format.

result is attached
[sprite_test_64k.zip](https://github.com/adventuregamestudio/ags/files/6093359/sprite_test_64k.zip)

(interestingly .exe produced with those changes cannot be loaded by engine "Error: Unable to load font 0, no renderer could load a matching file", but .ags file works)
