### ISSUE TITLE
Linux README: add instructions for using alleg-sdl2digi

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1233]
This optional module implements allegro audio driver and uses SDL2 as a backend. If I understand correctly, it's built from our allegro repository <https://github.com/adventuregamestudio/lib-allegro/blob/allegro-4.4.3.1-agspatch/src/unix/sdl2digi.c>
(but I keep forgetting the details).

It is not mentioned in the linux readme at all, nor how it's built nor its dependencies.

We provide it along the prebuilt engine binaries for Debian (and related systems), but there are no instructions on how to enable it (user must have SDL2 runtime installed).

This will become obsolete after we switch to SDL2 backend completely, but still essential for older branch and old version maintenance. Therefore following should be added to the readme:

* How to build alleg-sdl2digi.so (and maybe brief explanation of how allegro modules work);
* How to enable it whether you have built it yourself or downloaded prebuilt binaries.

**Comment by ericoporto** [comment]
Allegro tries to enable modules in an order and this module is the first on the list, so if the auto option in the config is set, and the person has libsdl2-2.0 installed, this module will automatically be selected and used.

**Comment by ivan-mogilko** [comment]
> Allegro tries to enable modules in an order and this module is the first on the list,

Actually, it's other way around: it uses the one that is last in the list (they seem to override each other).

**Comment by ivan-mogilko** [comment]
> Allegro tries to enable modules in an order and this module is the first on the list

IIRC it is other way around: it uses one that is last in the list (the modules seem to override each other).

But more importantly, cmake is optional, and there's still a case when a person builds everything on their own, for that reason these instructions are necessary.

**Comment by ericoporto** [comment]
CMake is optional you mean in case the person got allegro 4 from the package manager? In that case I think that code can be upstreamed to allegro4 branch.

**Comment by ivan-mogilko** [comment]
Well, I was planning to document existing situation... even if it's upstreamed and accepted there (I don't know what are their rules about such custom modules), it will take time to make into package on linux systems.

**Comment by ericoporto** [comment]
It's a single c file, imagine a single gcc command that links and include allegro4 and libsdl2 will work for building it - I don't remember how the auto will play with the module built separately but it's probably possible to manually select.

Anyway, I would like to try a PR upstream anyways, in case it's acceptable (allegro5 has a sdl2 backend and stuff) it's a plus.

**Comment by ivan-mogilko** [comment]
Ok I wrote something 4304ce48d486a4b650ff723686fa4543d3f2f75a.
Hopefully even if this is not thorough enough, it will point into write direction.
