### ISSUE TITLE
Feat.request Support pre-2.50 games (maybe in legacy branch?)

### ISSUE THREAD

**Issue by necros2k7** [adventuregamestudio/ags#1234]
subj

**Comment by ivan-mogilko** [comment]
Few important notes:
* supporting old games is no longer a priority of the current dev team;
* this would require investing significant amount of effort in reverse engineering old data formats and game logic;
* there's a scummvm ags port in works, and scummvm developers may be more interested in this task; of course if they do, they will probably do that within their port.

Would someone achieve this, we could add same support to the backward compatible branch. But I strongly doubt anyone of the current active developers will want to work on this.

**Comment by rofl0r** [comment]
i've tried many ags games, but so far encountered only one that couldnt be opened, and it was made by ags 2.20ish. do you have a list of games that don't work with current engine, @necros2k7 ?

**Comment by necros2k7** [comment]
> i've tried many ags games, but so far encountered only one that couldnt be opened, and it was made by ags 2.20ish. do you have a list of games that don't work with current engine, @necros2k7 ?

Sure, not fulll but until I tired revising my collection:

AC2/DOS based:
abstract
ace duswell
asap
bluecup
book of spells
calsoon
carver 2
captain disaster
chris quest
christmas tale
compensation
crime time
crown of gold
cup of cofee
dark sects
everything euro
floyd sb the company man
journey home
house quest
larry vales traffic division
larry vales 2
lassi quest
lassi and roger
lassi and roger 2
mr.greys great adv
night of hermit
nomedon inc.

3.11/95  based:
6 day assasin
aaron
ace
ace2
another rpg
blackjack
captain muchly
day in the future
demonslayer 4
earwig
exile
gaia fallen
gorthor
henkka mini quest
isle quest
java joes cofee
little jonny evil
lorry loader
men in brown
mom`s quest
murder
not another space quest

**Comment by rofl0r** [comment]
hmpf, i can't be bothered to register an account with $randombugtracker, otherwise i would. dont they have a github org nowadays?

**Comment by necros2k7** [comment]
You can register there with Github account ok

**Comment by ivan-mogilko** [comment]
I know they have https://github.com/scummvm/scummvm/, but the issue tracker is apparently disabled there.

@necros2k7, in regards to these games, you keep mentioning some "3.11", what is that?

**Comment by necros2k7** [comment]
> I know they have https://github.com/scummvm/scummvm/, but the issue tracker is apparently disabled there.
> 
> @necros2k7, in regards to these games, you keep mentioning some "3.11", do you mean Windows 3.11? I was not aware that previous AGS engines were meant for Windows that old.

Yeah my mistake, win95 to be correct
