### ISSUE TITLE
New compiler: access violation with a function token before an assigment

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1237]
**Describe the bug**
@fernewelten by pure chance, I found out that a function token placed right before a function assigment will crash the Editor to desktop  without alerts, due to a memory access violation during compiling.
From what I've seen only function tokens can trigger this issue, and only if the next operation is an assignment.

**To Reproduce**
```
		GetTextHeight
		player.Baseline = 1;
```

**Comment by fernewelten** [comment]
Addressed in #1240.

**Comment by ivan-mogilko** [comment]
Fixed by #1240
