### ISSUE TITLE
guidelines about branch merging

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#1241]
i'm wondering whether there are any guidelines for how the branch merging stuff works.
as an example, today a bugfix detected by scummvm folks was merged into master (which is something like ags3-development), but not into ags3--sdl2, ags-release-3.5.0 nor ags4.

the branch i'm currently most interested in is ags3--sdl2, since it is the only ags3 based branch with proper midi playback on linux, though it seems to receive a merge only every few weeks.

**Comment by ivan-mogilko** [comment]
There are no written guidelines about timing. Personally I've been just merging periodically, unless there's a critical need to have some changes in another branch.
I can merge master to ags3--sdl2 now.

release-3.5.0 did not need that particular fix, because it also does not have a commit that broken fixed logic.

**Comment by rofl0r** [comment]
> release-3.5.0 did not need that particular fix, because it also does not have a commit that broke fixed logic.

oh? the PR that broke the logic was

> ivan-mogilko merged commit c409fab into adventuregamestudio:master on Jul 19, 2020

i.e. almost one year since merge.

tbh, the difference between master and release-3.5.0 is really confusing to me...

> There are no written guidelines about timing. Personally I've been just merging periodically, unless there's a critical need to have some changes in another branch.

hmm, i personally would prefer if bugfixes were sync'd to all branches asap...

**Comment by ivan-mogilko** [comment]
> tbh, the difference between master and release-3.5.0 is really confusing to me...

What is confusing in particular?

> i.e. almost one year since merge.

AGS 3.5.0 was released 14 Dec 2019, since then "release-3.5.0" branch serves for patching, it rarely receives anything except bug fixes and cosmetic improvements.

**Comment by rofl0r** [comment]
ah, i see now. thanks for clarification!
