### ISSUE TITLE
Copyright.txt question

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1244]
Copyright.txt in our repository contains mostly names (sometimes aliases) of people who contributed to the project, but no other info. Also, it's called "Copyright" for the reason that I don't remember.

First of all, would it make more sense to rename it to Credits instead?
Secondly, perhaps we should've added other info such as github accounts along with the people names? That seems like a logical thing to do as it adds clarity to who the person is (and lets someone contact them if the need arises), but I do not know if there may be any counterarguments to this.

**Comment by morganwillcock** [comment]
> First of all, would it make more sense to rename it to Credits instead?

The (Artistic) licence makes reference to the copyright holder and involves them in certain clauses, particularly with regard to working around issues of modification where changes are not made made public. It is likely that anyone who provided a non-trivial change (or perhaps everyone who has made any change) is a copyright holder, and so I think it is fairly important to differentiate between someone listed specifically under "copyright" and where someone is thanked but didn't contribute anything that falls under the project licence.

> Secondly, perhaps we should've added other info such as github accounts along with the people names? That seems like a logical thing to do as it adds clarity to who the person is (and lets someone contact them if the need arises), but I do not know if there may be any counterarguments to this.

It might cause an issue where someone wanted to remove their contact details but didn't have direct access to do so.

**Comment by ivan-mogilko** [comment]
> so I think it is fairly important to differentiate between someone listed specifically under "copyright" and where someone is thanked but didn't contribute anything that falls under the project licence.

But does this restricts how file should be called? I.e. in the manual this goes under "Credits" article afaik.
What if the file is called "Credits" and there are sections for people who contributed and people whose work or advice was used otherwise.
But then again, guess my main question is whether "Copyright" is a proper file name for this purpose.

> It might cause an issue where someone wanted to remove their contact details but didn't have direct access to do so.

My thought mainly was that mentioning e.g. github account could be beneficial for these people, as on one hand it will clarify who is credited (and holds copyright according to our license, as you noted), and at the same time this way make it easier for these people to prove they worked on the project if they want to e.g. showcase their work in portfolio or something. TBH I do not know how this is usually done.

In regards to hiding details, each commit we have in repository contains authoring information, which usually includes github alias and email too (I don't think latter has to be real though).

**Comment by morganwillcock** [comment]
> But does this restrict how file should be called? I.e. in the manual this goes under "Credits" article afaik.
> What if the file is called "Credits" and there are sections for people who contributed and people whose work or advice was used otherwise.
> But then again, guess my main question is whether "Copyright" is a proper file name for this purpose.

I'd say that copyright and credits are separate topics, and it would probably be expected to steer someone who is looking for the information based on the filenames. Some of the current wording on the licence headers implies that the copyright file exists to avoid listed every individual in every header:

e.g.
https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/cdaudio.h#L5-L7

```
// Copyright (C) 1999-2011 Chris Jones and 2011-20xx others
// The full list of copyright holders can be found in the Copyright.txt
// file, which is part of this source code distribution.
```

I would say that anything that is a credit with no impact on copyright holders is a better fit to just go into the program documentation and not be mentioned in a separate file, if only to further distance the idea of credit vs. copyright holder.

> My thought mainly was that mentioning e.g. github account could be beneficial for these people, as on one hand it will clarify who is credited (and holds copyright according to our license, as you noted), and at the same time this way make it easier for these people to prove they worked on the project if they want to e.g. showcase their work in portfolio or something. TBH I do not know how this is usually done.

I think if there was somewhere that linked to contributor profiles that would be better in the manual or on a website. That would be the type of environment where readers would expect to find links or references to external sites, and then the copyright information doesn't have to consider how it represents/blesses/checks any links to external resources.

> In regards to hiding details, each commit we have in repository contains authoring information, which usually includes email too (I don't think latter has to be real though).

I think I'd just leave it so people maintain there own portfolios externally, and then it is their responsibility to set and maintain the commit information such as the e-mail address. It isn't trivial to maintain a provable identity in the long term. Outside of requiring signed commits I don't think there is a reliable way for someone to actually identify themselves (hopefully a GitHub user named "VisualSVN Server" doesn't appear and try to claim that the AGS source code was stolen from them). It seems safest to do the minimum amount of operations which directly relates to someone's identity, unless everyone can prove who they are.

**Comment by ivan-mogilko** [comment]
> Some of the current wording on the licence headers implies that the copyright file exists to avoid listed every individual in every header:

Ah dammit, I keep forgetting about that too.

Alright then.
