### ISSUE TITLE
AGS4: Feature proposal:  `protected:`/`public:` sections in `struct`s, retract `writeprotected`

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1254]
I'd like to propose for the new compiler to extend/change our `struct`s so that they come nearer to classes. 

1. __Keywords public, protected, (private)__

- Within the component definitions of a `struct` you can add any number of times the code `protected:` and `public:`. 
- All components that follow `protected:` will be __protected__ components, defined below, until the code `public:` or the end of the component list follows. 
- For non-protected components, nothing changes, all the current rules apply (but see below about `writeprotected`).
- Thus the default for `struct` components is that they are __not__ protected. If you don't use the new keywords, then everything will stay just as it was (but see below about `writeprotected`).
- Protected `struct` variables can only be accessed from the bodies of functions of that struct.
- Protected `struct` functions can only be called from the bodies of functions of that struct. 
- Protected `struct` attributes are not allowed.
- If a `struct` A extends a `struct` B, it will have all the components that `struct` B has, apart from its proper components. Protected components of `struct` B will become protected components of `struct` A (so they can be accessed from functions of `struct` A, too).  

.
- `private` will become a keyword. However, private components will be implemented in a future step. Until they are implemented, the keyword `private` will yield an error. (But if you want to already use private sections, you can `#define private protected` as a temporary measure. All your `private` fields will then become `protected` fields, so you must see to it yourself that your child `struct`s do not access private fields of their ancestor `struct`s).

Typical code:
```
struct Vehicle
{
protected:
     int _speed;
};

struct RaceCar extends Vehicle
{
    readonly attribute int Speed;
    import function ChangeDriver(String name);
    import function Init(String driver_name);
    import function Accelerate(int additional_speed);
protected: 
    String _driver;
};
```
----

2. __Keyword writeprotected__

`writeprotected` will lose its keyword status and trigger an error. (If you want to continue using old code, `#define` `writeprotected` to nothing.)

So what can you do instead? To achieve the effect of a struct variable that can be read but not changed from outside the `struct`, define a __protected__ variable and a `readonly` attribute that returns this variable.

**Comment by rofl0r** [comment]
instead of adding new keywords and retracting old keywords, i'd propose to make readonly and writeprotected aliases to const (could even be via `#define readonly const` in script header) and extend const to cover the usecases of these 2 other keywords.

**Comment by ivan-mogilko** [comment]
> instead of adding new keywords and retracting old keywords, i'd propose to make readonly and writeprotected aliases to const

`writeprotected` cannot be alias to const, because it means a struct member that can be only read from outside, but may be still changed from within struct member function (const would not allow to change it at all).

`readonly` has more complicated situation, it has wider range of meaning, for instance when applied to struct's `attribute` it means that the attribute has only getter, not that the returned value is "const".

**Comment by fernewelten** [comment]
Coming from a `C` background, I'm not too comfortable with `readonly` myself. But @ivan-mogilko points out that this is a very ancient Chris Jones decision, dating back at least to Version 2.8 of AGS. 

For clarification, this keyword is taken from the C# universe. I can imagine that Chris introduced it when C# was all new and shiny and all the craze, much cooler than the crusty and ugly C++.  (If the latter ugliness was his motivation, I can fully understand and feel with Chris. :-)

C# differentiates between 
- variables that can't be changed after initialization, on the one hand, 
- and constants, on the other hand. 

`readonly` is a characteristic of a variable. A variable that is `readonly` is still a variable; the only difference is that it can't be changed after initialization. It being a variable, you can't use it , e.g., in array declarations such as `int Array[kSize];`. 

To get constants in C#, you have to use `const`. No memory is allocated for a `const`, if you go `const int i = 4;`, then `i` becomes a synonym of `4`. 

So what's in the language right now?

Even now, AGS already recognizes the `const` keyword. Unfortunately, by throwing an error message and telling the user to use `readonly` instead. But as said above, you can't use `readonly` "constants" in array declarations. :-( Thats plusungood.

**Comment by rofl0r** [comment]
> To get constants in C#, you have to use const. No memory is allocated for a const, if you go const int i = 4;, then i becomes a synonym of 4. Whenever you say 'i', the compiler will immediately convert it to '4' and move on.

well, we already have that, it's called preprocessor macros.
`#define foo 4` `whatever = foo;`

**Comment by ivan-mogilko** [comment]
> well, we already have that, it's called preprocessor macros.

Macros are not full equivalent to constants, for once they do not have type. I believe that was one of the reasons they do not support them in C#.

**Comment by ivan-mogilko** [comment]
TBH, I am less in favor of this proposal, compared to other recent ones. Imho struct member protection is already fine; true that it does not have `private`, but I am not even sure if that's needed so much. In AGS scripts structs are usually simple, firstly not many people actually code larger struct hierarchies, and then there are other limitations that hinder their efficient use, such as no function overriding.

Also, I just like `writeprotected`, it's simple and saves time and 1 attribute.

**Comment by ericoporto** [comment]
I think the way it currently is with attributes is simpler and easier to use, plus it's one less thing to learn about the AGS script syntax. I don't like this proposal, having written a ton of modules I think the way it's is much clearer.

**Comment by ivan-mogilko** [comment]
Yes I've been thinking about closing this as not planned, for the reasons stated above.

The only thing that is currently missing is "private" keyword, which would make sense for struct hierarchy and controlling access in derived types, but this is not a high priority at the moment.
