### ISSUE TITLE
AGS4: Feature proposal: `const` 

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1255]
Our new compiler is currently getting compile time evaluation. So I'd like to propose additionally:

You can define compile-time constants with the keyword `const`. Typical code:
```
const float pi = 3.14;
```

This will currently only work with `int` and `float` but may be extended in future, e.g., if the compiler learns about processing strings at compile-time.

After such a declaration, `pi` will be another name for `3.14`. __No memory will be allocated.__ Instead, whenever this definition is in scope, the compiler will immediately convert any `pi` it encounters to `3.14` and carry on compiling.

The following cases are possible:
- The constant can be defined in global space. In this case, it cannot be exported nor imported (because no memory is allocated for it). If you want other modules to know about the constant, then declare it in the header file.
- The constant can be defined in a function body. In this case, it will be forgotten as soon as the `}` of the innermost `{ …}` pair is encountered in which the definition resides.
- You can declare a `const` struct component. In this case, it will by needs be a static component. (There's no way to have different compile-time constants for different struct instances since the different struct instances don't come into existence before run-time). It's possible but not mandatory to use the `static` keyword.
```
struct Foo {
    const int dozen = 12;
    static const int bakers_dozen = 13;
};
```

Note that you can calculate in the expression that defines the constant:
```
const float half_pi = pi / 2.0;
```

We can get that 'for free' because the compiler already does that whenever a literal is expected.

**Comment by ivan-mogilko** [comment]
> You can declare a const struct component, but in this case, it must be static const (There's no point in having different compile-time constants for different struct instances because the compiler doesn't have any way to keep track)

Why do you need `static` at all if consts can be only static anyway, maybe omit `static` then? iirc C# does that.

**Comment by fernewelten** [comment]
I'm fine with that. Amended the initial posting.

**Comment by ivan-mogilko** [comment]
I believe this proposal is fully resolved. Don't remember by which PR exactly, but this one seem relevant: #1250

All the proposed features are working in the current ags4 branch.

**Comment by fernewelten** [comment]
I can confirm that this is in the new compiler by now.
