### ISSUE TITLE
Primordia: Signal transmitter digits spaced too closely?

### ISSUE THREAD

**Issue by eriktorbjorn** [adventuregamestudio/ags#126]
This applies to the current git "master" branch and the version of Primordia sold on GoG.

When using the signal transmitter, the digits on it appear too closely spaced. This is noticeable when selecting a digit to change, because the highlighted digit is drawn at what I assume is the correct position. From left to right, each digit is one pixel further out of position than the previous one.

I don't know if this is a bug in AGS or a bug in the game itself.

**Comment by ivan-mogilko** [comment]
This should be retested with 3.5.0, since we are using specific alfont/freetype versions now.

**Comment by eriktorbjorn** [comment]
I tried with my old savegame and the latest ags3 branch. I've forgotten most about the game, but it looks like it works fine for me now under Linux. I'm attaching a new screenshot.

![primordia-font](https://user-images.githubusercontent.com/601765/61902569-b1e78600-af22-11e9-980b-73fdfdcf483b.png)

**Comment by ivan-mogilko** [comment]
Alright, looks fixed now.
