### ISSUE TITLE
AGS4: Rename "Sound" --> "Score" in General Settings

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1267]
There is a "Sound" category on the General Settings screen. It has just one entry: "Play sound when the player gets points". At core, this is a score related matter, not a sound related matter. In a "Sound" category you'd expect entries such as whether threaded audio or Midi sound is enabled. But those issues are all handled in the "Audio" category of "Default setup".

So I'd like to suggest renaming the "Sound" category to "Score". There's another score related field on the General Settings screen: "Maximum possible score" in "(Basic properties)". This field should be moved to this new "Score" category, too.

**Comment by ivan-mogilko** [comment]
Perhaps it would be better to remove both settings? Score and score sound may be easily implemented in script.

**Comment by ivan-mogilko** [comment]
Did this in 3.6.1: af61c8b44251b9bb93b5c1f0425ae724e0fa7d88

For 4.0 opened a PR which removes built-in score feature instead: #2201
