### ISSUE TITLE
SDL2: particular OGG clip does not play

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1275]
Following short OGG clip plays fine in AGS 3.5.1 but does not play in AGS 3.6.0: [dial1.zip](https://github.com/adventuregamestudio/ags/files/6468860/dial1.zip)

I did only brief debugging so far, and this leads down to the SDL_sound library's `Sound_Decode`, and then to `VORBIS_read`, which fails at some point.

This was tested with the AGS 3.6.0.3 built with our CI, so SDL_sound revision is fetched according to the CMake script.

Firstly may be worth trying this with the latest library revision, and if it's still not working then report to the library developers.

**Comment by ericoporto** [comment]
I verified it plays with the latest SDL_sound revision.

**Comment by ivan-mogilko** [comment]
Unfortunately it seems to not be fixed, built engine with the latest commit 14cf8dfb8a2f33051bdb6922887df7f1d25d99d2

**Comment by ivan-mogilko** [comment]
Probably not the best place to put this, but I'll post this here just in case someone would be searching for "sound not playing" issues later.

The same user sent me another clip recently, that does not play in any version of AGS, and investigating it I found that SDL_Sound does not support WAV files with 24-bit depth.
