### ISSUE TITLE
Patching AGS games

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#129]
apparently patches to AGS games on GoG are almost as large at the game itself, which apparently [causes some pain](http://www.rpgcodex.net/forums/index.php?threads/primordia-a-point-and-click-adventure-now-available.49740/page-22#post-3135923)

If whatever compression process you're using could be made to be for instance rsyncable friendly; for instance, using [parellel gzip rsyncable support](http://mail.zlib.net/pipermail/pigz-announce_zlib.net/2012-January/000003.html) the idea of which could be used for a patcher that only replaces files that changed (using rsync or not).

The first link also has some problems the author of primordia found, like weak support for localization and other annoyances.

**Comment by i30817** [comment]
Bumping this to say that i don't know what i was thinking talking about delta and compression aware patchers... for 'easy' patching you only need a VFS that allows replacing files, something like the override folder in SCI and Infinity Engine.

**Comment by ivan-mogilko** [comment]
AGS supports overriding files since the beginning. You can place file in the game's folder and it will have higher priority than the game package.

**Comment by i30817** [comment]
Well, then i was badly informed. Maybe it's actually 'making' these files that's difficult for the average game maker. Because if that works, there is [no reason for this](http://www.rpgcodex.net/forums/index.php?threads/primordia-a-point-and-click-adventure-now-available.49740/page-22#post-3135923).

**Comment by ivan-mogilko** [comment]
Well, not just difficult, rather there is no automated way to do this.

**Comment by ivan-mogilko** [comment]
I'd close this, as there are certain ways to patch the games, replacing certain files in it; there were agsutils, and now there are our own versions of few of these utils in the repository (packing/unpacking game "file libraries" etc).

It is also now possible to have compiled game scripts repacked separately from the rest of the data (both script modules and room scripts).

If further improvement is desired then there should be a task opened with more clear goals.
