### ISSUE TITLE
eEventSavedGame to go with existing eEventRestoreGame

### ISSUE THREAD

**Issue by bx83** [adventuregamestudio/ags#1295]
This is a feature request.
In the current editor, the command RestoreGameSlot() will not actually execute until the function enclosing it is finished; this makes it impossible to ever run a command *after* the game is restored, except by using a variety of true/false switches in repeatedly_execute_always(), etc. etc.
LUCKILY, there is an event trigged for this which solves the problem: eEventRestoreGame.
HOWEVER, there is no equivalent event for a SaveGameSlot() command, which has the same features and won't run until the enclosing function has finished, etc.

To Reproduce
Run RestoreGameSlot()
Set an event capture in on_event for eEventRestoreGame - this will run after the game restore is finished completely

Save a game with SaveGameSlot()
You can no longer figure out when this save function is done
hence:
  Set a switch for the savegame file name, and check for the file existing in repeatedly_execute_always()
  When the file exists, if ever, set and start a timer for something which seems reasonable to write the file completely, say 1sec
  Now you're as sure as you can be that it's saved and complete, set a 'JustSavedGame' switch to true, pick it up in repeatedly_execute_always()  
  This time, set JustSavedGame to false, do what you need to do following the SaveGameSlot() function
  You are still not 100% sure it all worked, but as long as the computer doesn't hang from some other process, or some other case, we're 99% sure we guess :/

**Comment by ivan-mogilko** [comment]
Not ready to go full depth into this right now, but something I **must** note: currently events in AGS are scheduled to run after the rest of the script finishes.

This means that if we use `on_event` for this, then it will only run after whole script callback completes, and not right away after save is written. It might even conflict with other scheduled things (like ChangeRoom).

It could be that a more explicit callback type will be useful here. Or, we would need to redesign how `on_event` works.

**Comment by ivan-mogilko** [comment]
Also, reading this:

> Set a switch for the savegame file name, and check for the file existing in repeatedly_execute_always()
When the file exists, if ever, set and start a timer for something which seems reasonable to write the file completely, say 1sec
Now you're as sure as you can be that it's saved and complete, set a 'JustSavedGame' switch to true, pick it up in repeatedly_execute_always()

The game saving is a synchronous operation currently, which means that *supposedly* the next script will be executed only after file writing was complete.
@bx83, I know it's been a while, but if you're still following this repo, could you remember and tell, why this was a problem for you in the first place?

**Comment by ericoporto** [comment]
Closed by #2012
