### ISSUE TITLE
Tool: translation compiler

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1299]
As a step of decoupling game compilation procedure from the Editor, we need a stand-alone tool that is run from the command-line, parses a translation source (TRS) file and writes a compiled translation (TRA) file in binary format.
Should be written in the similar line with the existing tools, in C++ (#1262, #1264, #1269).

Name suggestion: `trac` (TRAnslation Compiler).

_NOTE:_ this task is exclusively in writing this tool, adjusting Editor is a separate task, so no need to concern yourself with that if you are doing this. In fact it's best to assume that Editor will not be present to ensure tool's work result has no reliance on it.

**Input:**
* a TRS file (AGS translation source);
* path to output file;

**Output**
* a TRA file (AGS compiled translation)

---

### Details

The algorithm is relatively simple, most of TRS is just pairs of text lines that form a key/value map, with a few exceptions (comments, options).
Current implementation of reading and writing TRS in the Editor may be found here:
https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Types/Translation.cs
Implementation of the TRA writer in the Editor may be found here: https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Editor/Components/TranslationsComponent.cs#L92
User documentation of TRS format:
https://github.com/adventuregamestudio/ags-manual/wiki/Translations

The existing Tool code in the current master branch:
https://github.com/adventuregamestudio/ags/tree/master/Tools
MSVS solution for standalone tools:
https://github.com/adventuregamestudio/ags/blob/master/Solutions/Tools.sln

**Comment by fernewelten** [comment]
In my opinion, we should take this project as an opportunity to go standard:  If AGS uses a standard format for translatable strings then translators can profit from ready-made tools and ecosystems to handle them.

Standard formats provide annotations for strings, e.g. to say where they were pulled from so that translators get better context when deciding how they should be translated. We might make use of that.

Standard formats are more robust against involuntary breaking.

**Comment by fernewelten** [comment]
Many open-source projects use the __GNU "gettext" (PO)__ format, which has the advantage that you don't __need__ tools for translating the files: A normal text editor is entirely sufficient. 
It's common, but it isn't formally standardized, so the GNU documentation is authoritative: https://www.gnu.org/software/gettext/manual/html_node/index.html

All the professional general translating environments (SDL Trados, memoq, Wordfast, swordfish, OmegaT etc. etc.) can read from and write into a standard called __XLIFF__ . It's become a universal standard for exchanging translatable files. However, from the vantage point of end users its disadvantage is that you __need__ a tool to process the files. If you edit the files per hand, you run at least as much risk of mucking up everything as with our current .tra/.trs files.
Standardized here: http://docs.oasis-open.org/xliff/xliff-core/v2.1/xliff-core-v2.1.html

**Comment by ivan-mogilko** [comment]
@fernewelten this particular task is only to separate *existing* logic from the editor so that it could be run separately. It's also meant for ags3 branch too.

Any changes to source format should be a separate task, and considered whether it's best to add to ags3 or ags4.

**Comment by ivan-mogilko** [comment]
I think there were couple of more tickets related to translation system (unfortunately we do not have a label for these), perhaps it makes sense reviewing them and writing a summary ticket with problems & proposals.

**Comment by fernewelten** [comment]
I'd suggest:
- changing the Editor to export into PO format (exclusively)
- writing trac in such a way that accepts PO files (exclusively) and generates .TRS files
- writing a separate .TRA-to-PO converter for legacy support.

**Comment by ivan-mogilko** [comment]
I cannot do this in one task, because this is a part of parent task of decoupling compilation procedure from the editor. This does not assume any change in formats and has to maintain compatibility with 3.* projects.

Any further changes has to be separate task.

**Comment by fernewelten** [comment]
The .TRS format wouldn't (and shouldn't) change in any way.

A .PO file isn't anything spectacular at all. To quote from the docs:
> A PO file is made up of many entries, each entry holding the relation between an original untranslated string and its corresponding translation. ... One PO file entry has the following schematic structure [white space and lines starting with '#' are optional]: 
```
white-space
#  translator-comments
#. extracted-comments
#: reference…
#, flag…
#| msgid "previous-untranslated-string"
msgid "untranslated-string"
msgstr "translated-string"
```

That is, from the vantage point of the translator:
- Look for a line that leads with `msgid` and translate it on the next line leading with `msgstr`. 
- Put any notes you might have about this specific translation in front of this pair, with a leading `# `.  
- Lines starting with `#.` might give you context for the translation. 
- Ignore all other lines that lead with `#`.
- Repeat until you are done.

From the vantage point of the generating program: 
- If you have human-readable comments that show where the original is from, put them after `#.`. 
- If you have any technical references and such, put them after `#:`. 
- Generate a line `msgid "ORIGINAL"`
- Generate a line `msgstr ""` for the translator to fill in.
- Repeat until you are done.

From the vantage point of the reading program (in the simplest case):
- Ignore all white lines and all lines beginning with `#`.
- Find a line that begins with `msgid `.
- The following non-white line must begin with `msgstr ` (or else, complain about it).
- Do your thing with the pair you found.
- Repeat until you are done.

**Comment by ivan-mogilko** [comment]
@fernewelten i'm sorry, but I will make this tool as planned in any case for ags3 branch.

If you think PO format is beneficial then we may open a new task for doing what's necessary to transit there. Perhaps it will be aimed at ags4 branch, but this may be argued.

> The .TRS format wouldn't (and shouldn't) change in any way.

I'm not sure what you mean by this. Maybe you mistake TRS and TRA? TRS is the current translation source (basically a txt file), TRA is a compiled data for the engine.
