### ISSUE TITLE
A way to disable automatic save at startup

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1306]
There are games developed with the custom save system, or not meant to have saves in a common sense at all, and for these having built-in ags state saves may be unnecessary. Although for the most part these saves are instigated from script, there's still one case when the "restart point" is created at the very startup.

There might be some good way to disable it. Either provide a game setting, or even disable it completely in the future engine versions and only do when there's an explicit call to SetRestartPoint().

EDIT: Then again, maybe we may deprecate both SetRestartPoint() and RestartGame() and let users customize their restart system too as they see fit.

**Comment by ivan-mogilko** [comment]
I've been thinking about ading a simple switch in the General Settings for this. But after checking the code closely, it appears that an automatic `SetRestartPoint` call is done right after executing `game_start` function.
I tested disabling `SetRestartPoint` call in the engine and call it in `game_start` script instead, and the result seems same.

So my suggestion now is to:
1. Call `SetRestartPoint` automatically only under condition that the game was made in pre-3.6.1 AGS.
2. Since 3.6.1 recommend users to insert a manual call to `SetRestartPoint` into `game_start`.
3. Add corresponding changes to the manual.

The downside is that since this may be an unexpected effect, and users may start asking what happened to restart function.

**Comment by AlanDrake** [comment]
AGS should not need to save anything at all to restart the game from scratch.
For anything else there's already save/restore, so there's little point in creating a new SetRestartPoint(), in my opinion at least.

**Comment by ivan-mogilko** [comment]
> AGS should not need to save anything at all to restart the game from scratch.

What do you mean? That's the only way to do this from inside the game, iirc. Other than `RunAGSGame`, i guess.

**Comment by AlanDrake** [comment]
I mean that it shouldn't need a savestate to restart, the other cases should be covered by save/load functions.

**Comment by AlanDrake** [comment]
Sorry, I had overlooked this was mainly for 3.6.1.

Well, for the future it would be nice to remove agssave.999 completely in favor of cleanly restarting the game without a savestate.
I agree on deprecating SetRestartPoint as it's practically duplicate functionality.

If it were ags4 I'd say there's no problem in disabling the starting autosave, but on 3.6.1 maybe you should make it a voluntary choice from the options?
