### ISSUE TITLE
dialog_options_get_active is needed on ags4

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1311]
**Describe the bug**
Runtime error in a custom dialogue about an unimplemented `dialog_options_get_active` on script, which is true, but wasn't needed on ags 3.5.0.32.

The manual page on [_Custom dialog options rendering_](https://adventuregamestudio.github.io/ags-manual/CustomDialogOptions.html) mentions the following:

>   older versions of AGS (pre-3.4.0) supported slightly different set of functions. Thus, there was no `dialog_options_repexec`, but you had to `add dialog_options_get_active` function instead ... If you have imported older project and want to keep old dialog option scripts, then you should go to General Settings and enable **"Use old-style dialog options rendering API"**.

I can't find such option in the General Settings in AGS4, which is kinda expected.

**AGS Version**
AGS 4 branch, [a2c8f107667e8b158f1cea68b0037312b72c5de6](https://github.com/adventuregamestudio/ags/tree/a2c8f107667e8b158f1cea68b0037312b72c5de6) | Cirrus Artifacts: [task/4944673870446592](https://cirrus-ci.com/task/4944673870446592)

**Game**
I am building my own [I rented a boat](https://github.com/ericoporto/i_rented_a_boat) repository. ([Download source](https://github.com/ericoporto/i_rented_a_boat/archive/refs/heads/main.zip))

**To Reproduce**
1. Use custom dialog options with `dialog_options_repexec`, following the manual page on custom dialog options (the examples in the manual don't use `dialog_options_get_active`)
4. See error: 
   Error: The script function `dialog_options_get_active` is not implemented. It must be present to use a custom dialogue system.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2244442/121609789-facb5980-ca2a-11eb-9590-204b99bf8b51.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by ivan-mogilko** [comment]
Could you tell how was that "Use old-style dialog API" set in your project?

**Comment by ivan-mogilko** [comment]
So, I guess there are two problems here:
1. The update from the old project keeps "Use old-style dialog options rendering API" value while this option is no longer exposed in the GUI.
2. At the same time the legacy dialog API handling was not removed from ags4.

**Comment by ivan-mogilko** [comment]
BTW, while searching this in the editor, I noticed there may be more occasions where the editor still writes an obsolete property as if it were in use instead of simply using a value required by the new version.

**Comment by ivan-mogilko** [comment]
This was a typo... 7d3899b0b1a747e11054df202b184ba9f4462a7e

**Comment by ericoporto** [comment]
Yey! Thanks!
