### ISSUE TITLE
An error creating your game 

### ISSUE THREAD

**Issue by Canelmo** [adventuregamestudio/ags#1318]
Downloaded the app, didn't uncheck anything while setting it up. Therefore, right after downloading and creating a blank game this error occurs 

![image](https://user-images.githubusercontent.com/56025930/121998131-17152080-cdb4-11eb-8326-013bc3ea9f19.png)

**Comment by ivan-mogilko** [comment]
Please clarify what was the download link you used? We had a bug that caused incorrect unpacking of a game template recently.

Is the destination folder you chosen writeable?

**Comment by Canelmo** [comment]
Hello!
I used this link: https://www.adventuregamestudio.co.uk/releases/finals/AGS-3.5.1/AGS-3.5.1.7.exe
I have also tried this one: https://www.adventuregamestudio.co.uk/releases/finals/AGS-3.5.0P10/AGS-3.5.0.32-P10.exe
Both versions have this error

These are destination folders I have chosen:
C:\Program Files (x86)\Adventure Game Studio 3.5.1   For the AGS
C:\Users\canel\Documents\game  For the game

**Comment by Canelmo** [comment]
I think that it's also important to mention that Windows defender finds this application dangerous. Maybe it's somehow connected to the problem
![image](https://user-images.githubusercontent.com/56025930/122019819-dbd31b80-cdcc-11eb-9e61-86e29eddba08.png)

**Comment by Canelmo** [comment]
I found the problem. My antivirus blocked AGS's access to template files. It's all working now

**Comment by ivan-mogilko** [comment]
Ah yes, I also wondered if this is caused by some system protection. Anti-viruses don't like AGS for some reason...
