### ISSUE TITLE
Plugins may cause Editor to crash when closed from "Welcome to AGS!" popup

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1327]
**Describe the bug**
When the Editor is opened, it shows the following "Welcome to AGS!" popup:
![image](https://user-images.githubusercontent.com/41213694/122758569-3e2e8f00-d299-11eb-8ce5-dc8d371cc2cf.png)

When I click "Exit" in this window, I get an  "Unhandled Error" dump (Details below the heading "Screenshots").

When I close this message window,  I'm treated to a "A serious error occurred and the AGS Editor may now be in an unstable state" window. (Details, see below the heading "Screenshots").

When I click "OK" on this message window,  I'm in the main cockpit of the AGS Editor. In there, whenever I try to exit the Editor, I'm treated to the same two message popups as before (and as shown in "Screenshots"), and the only way to make the Editor close is by killing its task in the task manager.

**AGS Version**
AGS 3.5.0.30; also tested in 3.5.1

**To Reproduce**
See steps above.

**Expected behavior**
When I'm shown the "Welcome to AGS!" popup and click its "Exit" button, the program should exit cleanly. 

**Screenshots**
The "Unhandled Error" message when I click "Exit" in the "Welcome to AGS!" window:
(Sorry for the German; Windows insists on translating the error message. The English message might be: "Object reference not set to an instance of an object".)
```
Error: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Version: AGS 3.5.0.30

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei AGS.Plugin.DialogDesigner.EditorComponent.AGS.Types.IEditorComponent.EditorShutdown()
   bei AGS.Editor.ComponentController.ShutdownComponents()
   bei AGS.Editor.ApplicationController.GUIController_OnEditorShutdown()
   bei AGS.Editor.GUIController._mainForm_OnEditorShutdown()
   bei AGS.Editor.frmMain.frmMain_FormClosing(Object sender, FormClosingEventArgs e)
   bei System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   bei System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   bei System.Windows.Forms.Application.ExitInternal()
   bei System.Windows.Forms.Application.Exit(CancelEventArgs e)
   bei AGS.Editor.GUIController.ShowWelcomeScreen()
   bei AGS.Editor.frmMain.frmMain_Shown(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnShown(EventArgs e)
   bei System.Windows.Forms.Form.CallShownEvent()
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

The error "A serious error occurred...":
![image](https://user-images.githubusercontent.com/41213694/122759234-0247f980-d29a-11eb-9317-e35b98ccaca4.png)

**Desktop (please complete the following information):**
Windows 10, German edition

**Additional context**
Note that the error messages begin with `AGS.Plugin.DialogDesigner ...`. This might be a plugin issue or an issue of how plugins are handled.

**Comment by ivan-mogilko** [comment]
I think the exception is thrown by the DialogDesigner plugin. May be worth reporting to the plugin author.

OTOH the editor may try to catch this, especially if it's shutting down.

**Comment by ivan-mogilko** [comment]
I *think* I may have found a bug in plugin's code.

EditorShutdown method:
https://bitbucket.org/AJA/dialogdesigner/src/f14d442fc8901d89bd8e3ce06a1049eb30ac8bc1/AGS.Plugin.DialogDesigner/EditorComponent.cs#lines-230
calls _communicator.Stop:
https://bitbucket.org/AJA/dialogdesigner/src/f14d442fc8901d89bd8e3ce06a1049eb30ac8bc1/AGS.Plugin.DialogDesigner/DialogDesignerCommunication.cs#lines-34
In this method the thread is joined (`_listeningThread.Join();`)
But this thread object is created not in constructor, but in Start method above. And Start seem to be called in RefreshDataFromGame callback.
https://bitbucket.org/AJA/dialogdesigner/src/f14d442fc8901d89bd8e3ce06a1049eb30ac8bc1/AGS.Plugin.DialogDesigner/EditorComponent.cs#lines-198

Because RefreshDataFromGame is not called until game is loaded, the thread object was not created when Stop is called from the early Shutdown.

**Comment by ivan-mogilko** [comment]
The component callbacks are managed by a ComponentController class, but none of them are guarded by try/catch. We may have to devise a better way of handling this, with assumption that some of the components may throw exceptions, and decide whether editor may proceed in each case.

**Comment by ericoporto** [comment]
I think it's fine to just try/catch everything to prevent these dialogues, since the editor is shutting down anyway. But if it isn't acceptable, we could just try catch only the plugins, this is an idea here: https://github.com/ericoporto/ags/commit/cf2d8d1ca1c83c9d57fa9465a27379c551de5d0b

**Comment by ivan-mogilko** [comment]
So for now I just added a try/catch block in Shutdown method: c30138ddcbdb658dde7d513303e57efcc1ee4463

This is enough to prevent unhandled exception when quitting, but I still made it display a warning, to let users and developers know what's going on.
