### ISSUE TITLE
Script: add generic events for dialog start/end

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1328]
A suggestion is to add two new events for the `on_event` callback:
1) One run just before a dialog starts;
2) Second run just after a dialog ends;

Both events' parameter defines dialog's numeric ID.

If possible to implement, this will provide a simple and convenient opportunity to handle any changes when entering/exiting a dialog state in game.

**Comment by ericoporto** [comment]
Fixed by https://github.com/adventuregamestudio/ags/pull/2484
