### ISSUE TITLE
Website crashes browser tab

### ISSUE THREAD

**Issue by raszpl** [adventuregamestudio/ags#1329]
**Describe the bug**
Probably terrible place to report this, but there are no contact webmaster links on the site, registering on forums requires completing AGS programming quizzes, and I dont have a discord account.

https://www.adventuregamestudio.co.uk website has this gem:

`<img src="/images/facebook_logo.svg" onerror="this.src='/images/facebook_logo.png'" height="29" alt="Facebook logo">`

When one of >10 million people with uBlockOrigin and "Fanboy’s Annoyance" filter visits one of its rules filters:

`/facebook_logo.`

this triggers image load error, executes onerror and ..... you get the picture, 100% CPU utilization and constantly growing ram usage until tab crashes and is reloaded.

**Comment by fernewelten** [comment]
Passed on to the website "site report" forum; AGA says they've fixed it.

**Comment by raszpl** [comment]
Yes, its fixed, thank you.
