### ISSUE TITLE
Fix end sequence of Maniac Mansion 8 aborting part-way through

### ISSUE THREAD

**Issue by dreammaster** [adventuregamestudio/ags#1331]
As per the bug report here:  https://bugs.scummvm.org/ticket/12589
The end sequence of Maniac Mansion 8 aborted part way through when Bernard walks to a doorway and then does nothing else. This was replicated on the current master codebase on my Windows box, but the problem should be platform agnostic.

Investigating the problem, I determined that the original game script expected that the MoveCharacterBlocking method would return a non-zero value if the walk was done, and because it wasn't getting it, it aborted the sequence. Maybe this was prior behaviour of AGS 2.7, which was the version the game ships with? Since any current games expecting it to be void wouldn't be affected by it returning a non-zero value, I felt it safe to change the method return to an int with a return 1. See my commit to the ScummVM codebase below:
https://github.com/scummvm/scummvm/commit/487039489a01e8f72ddf5570429fec6598c2f8bc

Instructions for how to replicate the problem, and verify the fix can be found in the ScummVM bug report.

**Comment by ivan-mogilko** [comment]
@dreammaster

I might also mention that early on AGS script did not have `void` at all, it had `function` that was equivalent to `int`. And script interpreter safely handled even functions that don't return by presetting return value on stack to 0.

We found bugs in old games where their script would check a return value of a function that is not supposed to return anything at all (at least not likely), but that did not crash because of the above behavior, so had to restore it.

**Comment by dreammaster** [comment]
Thanks for the clarification. That makes sense.

**Comment by ivan-mogilko** [comment]
@dreammaster I ran a test on AGS 2.70, and MoveCharacter* functions return various values.

`MoveCharacterBlocking` seem to always return `-1`.
`MoveCharacter` (moves non-blocking) seem to return *the number of view loop* (basically direction) which character ends up with (0 - looking down, 1 - looking left, 2 - right, 3 - up).
`MoveCharacter` returns `-65536` when character was already standing on destination and did not move.


 returns `-1`. Idk if that matters.

**Comment by dreammaster** [comment]
Yikes. Thanks for taking the time to investigate. I'll commit in a note about it returning possible different values, and leave it as is until/unless a particular game needs it.

**Comment by ivan-mogilko** [comment]
@dreammaster to be honest, I cannot help but wonder if these all are indeed valid return values, because they may be coincidental values left on stack interpreted as return values because of how compiler acts.

**Comment by ivan-mogilko** [comment]
Anyway, pushed a suggested fix (only used -1 value): 5f65bb2edcf4138116a58393dc466fc20549ff41
