### ISSUE TITLE
Allow building game templates from the command line

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1336]
Currently creating an AGS game template requires booting up AGS and clicking through menus. If it was possible to build/export game templates from command line we could automate our own templates builds in https://github.com/adventuregamestudio/ags-template-source.

This could be a switch on AGS Editor itself though since I think it would be _us_ the users of this functionality, no need to make it too complicate. Just enough to help with fixing template issues.

**Comment by ivan-mogilko** [comment]
IIRC game templates are just same format as a compiled game, so may be packed and unpacked with the same tools.
Maybe some additions required on top of that, such as file selection, and maybe a meta data (again, don't remember all details).

I made [pack/unpack tools](https://github.com/ivan-mogilko/ags-refactoring/tree/tools--agspak) few day ago meant to be a part of the Editor tool set; was planning to make a PR after adding few options necessary for the game building.

**Comment by ericoporto** [comment]
I don't think script files are compiled in the templates - our preprocessor strips comments afaik and they are there in the script modules.

**Comment by ivan-mogilko** [comment]
> I don't think script files are compiled in the templates - our preprocessor strips comments afaik and they are there in the script modules (in the templates).

No of course they are not compiled. Perhaps I did not express myself clearly. What I meant, the package format is identical to the game package. The files are packed unchanged of course.

**Comment by ivan-mogilko** [comment]
I don't remember if scripts are additionally packed as "scm" (script modules), but if they are then we'd need an extra tool to pack/unpack SCM. Actually, such tool may come handy on its own anyway.

**Comment by ericoporto** [comment]
In my modules CI systems I use this tool from @monkey0506 for exporting, the source is 100 lines of a single C# script so it's really easy to read:

https://github.com/monkey0506/AGSModuleExporter

**Comment by ivan-mogilko** [comment]
I was able to unpack game templates using a tool #1348, but more testing may be useful.
