### ISSUE TITLE
Shake screen prevents multitasking detecting loss of input focus

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1338]
**AGS Version**
Bug happens in 3.6.X, built from current master ( https://github.com/adventuregamestudio/ags/commit/9dbdfe423c870e010a887cada725a8bbdf2de16e )

**Game**
Game: [shakeThreadTest.zip](https://github.com/adventuregamestudio/ags/files/6744521/shakeThreadTest.zip) 
Project: [shakeMultitaskProject.zip](https://github.com/adventuregamestudio/ags/files/6744540/shakeMultitaskProject.zip)

**To Reproduce**
In a new project do as following:
1. In the game_start, add `SetMultitaskingMode(1);`
2. in repexecute do something thatbehaves differently for each `System.HasInputFocus`
3. alt+tab out and back see everything works
4. do something with `ShakeScreen(40);` and try to alt+tab out, the System.HasInputFocus change will only happen after shake screen has finished.

Or using the attached game, hear that music volume is lowered when the game is out of focus, and elevated back when in focus, but if you click the Orb in the room, it will shake the screen, and now when alt+tabbing, it only changes music volume when the screen shake has finished.

**Expected behavior**
Music should lower and play with higher volume depending on focus independently if the screen is shaking or not. Game has the code below:

```AGS Script
void repeatedly_execute_always()
{
  if(System.HasInputFocus) {
    ac.Volume = 100; // audio channel volume
  } else {
    ac.Volume = 10;
  }  
}
```

**Desktop:**
 - OS: Ubuntu
 - Version: 20.04

**Additional context**
I think overall we should eventually reduce the number of internal game loops and instead manage game states in a different way, but this will be a different issue.

Possibly related to https://github.com/adventuregamestudio/ags/commit/abd03a8fbc672266da721c5281c7c9591f9b0e76 and #1292

I tried, in [`Engine/ac/global_screen.cpp`](https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/global_screen.cpp) to replace the [`platform->Delay(50)`](https://github.com/adventuregamestudio/ags/blob/9dbdfe423c870e010a887cada725a8bbdf2de16e/Engine/ac/global_screen.cpp#L68) with [`WaitForNextFrame()`](https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/timer.cpp) and added [`sys_evt_process_pending()`](https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/sys_events.cpp#L511), but it didn't work. :confused: 

This is super corner case though, I only found this because I was trying to fix a [bug in the webport](https://www.adventuregamestudio.co.uk/forums/index.php?topic=59164.msg636636350#msg636636350).

**Comment by ivan-mogilko** [comment]
ShakeScreen seem to be one of these functions (another is Display) that do not run rep-exec-always.

**Comment by ivan-mogilko** [comment]
Given the above,

1. This does not seem to be a bug.
2. To change this behavior we need to either run normal updates during shakescreen, or implement some extra script callback that runs during "super-blocking" actions such as shakescreen and display.
3. There's always a workaround: emulate shakescreen by shifting room viewport (and all gui if necessary) in script; then you will have more control over what happens.

**Comment by ericoporto** [comment]
I don't think it's expected that shake screen would block `repeatedly_execute_always`, would suggest changing this behavior on ags4. 
I also plan to write a new issue that will link to this.

**Comment by morganwillcock** [comment]
Can screenshake not be moved into a script module instead and just act on the viewport?
(Why does there need to be a special command to move something?)

**Comment by ericoporto** [comment]
> Can screenshake not be moved into a script module instea

We need a repository to start maintaining "recommended" modules then.

It's possible though, since viewport doesn't clamp to screen coordinates, very doable in script.

**Comment by ivan-mogilko** [comment]
There are few other things that we discussed for removal in the past, because they are not easy to customize when part of the engine API, but are trivial to script.

> We need a repository to start maintaining "recommended" modules then.

If it's removed in ags4, I don't think we *have* to maintain anything; not that we could not though.

**Comment by ericoporto** [comment]
I will close this since it's not a bug.
