### ISSUE TITLE
[Q] multiple section names in dialog scripts

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#1341]
i noticed that generated dialog script have, unlike all other scripts, a sections list containing multiple name/offset pairs.
ordinary scripts have only a single sections item, which contains the filename of the original script and 0 as the offset.
dialog scripts seem to have, additionally to the above, one section name per function and an offset pointing to the start of the respective function, for example:

```
.sections
"__DialogScripts.asc" = 0
"Dialog 0" = 317
"Dialog 1" = 6958
"Dialog 2" = 10437
```
etc.

are these section names (and more importantly, the offsets) used somewhere in the engine, or is it safe to omit them ?

**Comment by ivan-mogilko** [comment]
These are used to report errors relative to an individual dialog source.
Because all dialog scripts end up merged, without sections the error message will mention a line which has no correspondence to the source files, and it will be very difficult for a user to find this location.

**Comment by rofl0r** [comment]
thanks!
