### ISSUE TITLE
Cursor isn't properly erased by SDL Renderer in games with view offsets

### ISSUE THREAD

**Issue by dreammaster** [adventuregamestudio/ags#1343]
When using the SDL renderer, any game that has a black section at the top of the screen, like Maniac Mansion Mania 26, or Space Quest 4.5, doesn't properly erase the cursor when you move it around the screen. Instead, it's restoring the area of the screen without the view offset, resulting in the restored area being above the cursor rather than on it. I haven't figured out where the offset happens yet, so I can't offer any suggestions on how best to fix it.

![mmm26](https://user-images.githubusercontent.com/552828/124525046-7c0bd700-ddb2-11eb-9812-d251867d1e1d.png)

**Comment by ivan-mogilko** [comment]
This mistake was introduced earlier, present at least in 3.5.1 too.
It's related to the "legacy letterbox" mode which runs 320x200 game as 320x240, but centered on screen.

I found what has to be changed to fix the cursor sprite, but there's something else wrong, so will take bit more time.

**Comment by ivan-mogilko** [comment]
@dreammaster should be fixed with b7fdf44a70d838a0848cd5c94ffe82821323c798.

Idk if you care for this in scummvm port, but also ef78805ffc0e3702dd329401c19116a7d4737470 fixes it for the debug overlay stuff, such as fps counter.

**Comment by dreammaster** [comment]
Thanks for fixing it, and letting me know. I'll be sure to apply the upstream commits into ScummVM.
