### ISSUE TITLE
stderr debug spam of SDL2

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#1359]
since i can't comment on issue #1148 anymore (due to #1357) i'm opening a new ticket for what seems to me an annoying behaviour in SDL2 (master) branch:

when starting SDL2 based engine, i get 240 lines of spam like the below excerpt:

```
DEBUG: Failed loading XMissingExtension: Symbol not found: _XMissingExtension
DEBUG: Failed loading XextAddDisplay: Symbol not found: _XextAddDisplay
DEBUG: Failed loading XextCreateExtension: Symbol not found: _XextCreateExtension
DEBUG: Failed loading XextDestroyExtension: Symbol not found: _XextDestroyExtension
DEBUG: Failed loading XextFindDisplay: Symbol not found: _XextFindDisplay
DEBUG: Failed loading XextRemoveDisplay: Symbol not found: _XextRemoveDisplay
DEBUG: Failed loading XShmAttach: Symbol not found: _XShmAttach
DEBUG: Failed loading XShmDetach: Symbol not found: _XShmDetach
DEBUG: Failed loading XShmPutImage: Symbol not found: _XShmPutImage
DEBUG: Failed loading XShmCreateImage: Symbol not found: _XShmCreateImage
DEBUG: Failed loading XShmCreatePixmap: Symbol not found: _XShmCreatePixmap
DEBUG: Failed loading XShmQueryExtension: Symbol not found: _XShmQueryExtension
DEBUG: Failed loading XcursorImageCreate: Symbol not found: _XcursorImageCreate
```
the reason for this is that SDL2 doesn't link directly to X11, but uses dlopen() technique trying to load all sorts of libraries (like xinerama extensions and others), and if not found creates one debug message per function.
usually SDL2 doesn't display those, there must be some sort of debug output that is currently switched on in SDL2 port of ags.
my leaning would be to disable the output of those messages for regular builds, and only show them if a specific loglevel/debuglevel is activated in the engine, as they might be helpful in some cases.

**Comment by ericoporto** [comment]
https://github.com/adventuregamestudio/ags/blob/68044adc2abe11bddd7cc61e0918767dfa797f8d/Engine/platform/base/sys_main.cpp#L27

A good default here is to use `SDL_LOG_PRIORITY_WARN` instead. Alternatively, add a new debug group like `kDbgGroup_SDL` named `"sdl"`, and read from it adjusting to the corresponding `SDL_LOG_PRIORITY_`
