### ISSUE TITLE
segfault in heroine's quest during updatemp3()

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#136]
```
AGS: Loading room 80

Program received signal SIGSEGV, Segmentation fault.
[Switching to LWP 23494]
0x00007ffff7ffc8b0 in mal () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007ffff7ffc8b0 in mal () from /lib/ld-musl-x86_64.so.1
#1  0x0000000000565ad9 in update_mp3_thread () at media/audio/audio.cpp:875
#2  0x000000000056216c in engine_update_mp3_thread () at main/engine.cpp:1254
#3  0x00000000005665ae in AGS::Engine::PThreadThread::_thread_start (
    arg=0x9958e0 <audioThread>) at ../Engine/util/thread_pthread.h:96
#4  0x00007ffff7dc8093 in start () from /lib/ld-musl-x86_64.so.1
#5  0x0000000000000000 in ?? ()
(gdb) frame 1
#1  0x0000000000565ad9 in update_mp3_thread () at media/audio/audio.cpp:875
875                             channels[musicPollIterator]->poll();
(gdb) l
870             while (switching_away_from_game) { }
871             AGS::Engine::MutexLock _lock(_audio_mutex);
872             for (musicPollIterator = 0; musicPollIterator <= MAX_SOUND_CHANNELS; ++musicPollIterator)
873             {
874                     if ((channels[musicPollIterator] != NULL) && (channels[musicPollIterator]->done == 0))
875                             channels[musicPollIterator]->poll();
876             }
877     }
878
879     void update_mp3()
(gdb) p channels[musicPollIterator]
$1 = (SOUNDCLIP *) 0x0
```

a clear case: some other thread was setting channels[musicPollIterator] to 0 after the above check, despite the locks. so either locking was forgotten somewhere else, or the locking code doesn't work as it should.
this is using latest master + heroine's quest 1.1 on 64 bit linux (i updated ags after receiving the same crash a little earlier with a slightly older ags)

**Comment by ivan-mogilko** [comment]
Needs to be retested with 3.5.0 after threaded audio was rewritten.

**Comment by ivan-mogilko** [comment]
@rofl0r do you still have the game? If so, would you be able to test this again with either release-3.5.0 branch or recent master?

Otherwise I would like to close this, because it's too old and audio thread code was rewritten completely since.

**Comment by rofl0r** [comment]
> @rofl0r do you still have the game?

no, but i think this has been long fixed. i actually run threaded=1 in my default config since quite some time and never had any issues since your rewrite.
