### ISSUE TITLE
Bad interactions between room size (when changed), edges, Character.PlaceOnWalkableArea() 

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1366]
**Describe the bug**

Executing the line  `player.PlaceOnWalkableArea();` won't place player on a walkable area.

**AGS Version**
AGS Editor .NET (Build 3.5.1.8), v3.5.1, June 2021

**To Reproduce**

Install the game below; hit F5 and the code in room 222 will be executed.

Look at line 12, `player.PlaceOnWalkableArea();`. I expected that after execution of this line, the player character (the lady in white) should be on a walkable area, specifically number 1 (there aren't any others).
In reality, it isn't. The guard will say in surprise, `Ooops? I thought player would be on a walkable area?!`.

Lines 17 to 20 show that the character __can__ be put on walkable area 1. It's just that `player.PlaceOnWalkableArea();` fails to do so.  

**Game here:**
[Castle Escape.zip](https://github.com/adventuregamestudio/ags/files/6834813/Castle.Escape.zip)

**Expected behavior**
Player should end up on walkable area 1; guard character should not go `Ooops?`

**Desktop (please complete the following information):**
 - Windows 10, German version.

**Comment by ivan-mogilko** [comment]
Could be same as #163

**Comment by fernewelten** [comment]
> Could be duplicate of #163

Turns out yes, but indirectly. In this particular case the walkable area is continuous, so the root cause can't be what they were supposing back then (that the Engine only checks every 5th pixel or so).

BUT, quote from one of the __comments__ in #163 : 
> Another - __undocumented__ - exception is that `PlaceOnWalkableArea` ignores walkable areas lying beyond Room Edges. Probably that is because Edges are usually used to define exit zones.

This behaviour is still undocumented. And it accounts for part of the issue, in the following way:

When you initialize an empty room, you get a background in low resolution with preselected dimensions and edges, no matter what the General Settings screen says.  For instance, even if you declare in General Settings that your game is 1280x720, your standard new room will still be 640x400 with edges at X = 0, Y = 80, X = 634, Y = 396. 

Then, when you load your background, say a picture of 1280x720, then you are warned that "all your regions, hotspots, and walkable areas will be cleared." The __edges__ however are __not__ cleared.

So your new background is 1280x720, and the left and top edges are still fairly reasonable for the new dimensions. The __right__ and __bottom__ edges, however, end up right in the middle of the room. In particular, the bottom edge is really high so that the whole walkable area may well end up below it.

Suggestions:

1. Document that `Character.PlaceOnWalkableArea()` ignores those parts of the walkable areas that are beyond the room edges.
2. When a room of different size is loaded:
   * Either alert the user about the edges when a room of different size is loaded, similar to the warning you get when you install a walkbehind that you must now adjust the baseline.
   * Or move the right and bottom edges so that they are as far away from the new background sides as they were from the old sides.

**Comment by fernewelten** [comment]
Also, `Character.PlaceOnWalkableArea()` is two functionalities rolled into one:
* Find the nearest walkable area to a point
* Set the character there.

This made sense when AGS started out, because at that time there was no way  of returning more than one value from a function. But now there is.

So perhaps we should isolate the functionality of finding the nearest walkable area and offer it separately. Call the function, e.g., `Point *Room.NearestWalkableArea(int x, int y)`.

We could still keep `Character.PlaceOnWalkableArea()` and offer the new function as an addition.

**Comment by ivan-mogilko** [comment]
Finally, documented the PlaceOnWalkableArea's quirks in the manual.
Also, commented on how the function may be improved in the original ticket (#163).

I would like to bring two other suggestions mentioned above into separate tickets for clarity.
