### ISSUE TITLE
Strangeland crashes on startup due to DrawingSurface changes

### ISSUE THREAD

**Issue by dreammaster** [adventuregamestudio/ags#1379]
With the latest ags master, I'm now getting a startup error running Strangeland. "DrawImage: cannot draw onto itself". Doing a bisect, the problem seems to have been introduced in commit 67810b264d60f55571b1fb604ee5de833a08bfde, which did some refactoring to add extra DrawingSurface params. In the ScummVM codebase, changing the error to a one time warning allowed the game to start up without any noticeable problems.

**Comment by ivan-mogilko** [comment]
Thank you for reporting this, it was incorrect to error on this. Technically bitmap library supports this, and in theory this may be used to create a "mirror" effect, so I guess even the warning may not be necessary here.

Pushed aeb65ccbf3c94c1d4a0d73359cf93315bc0849d8.

**Comment by dreammaster** [comment]
Me either. I was happy enough that it resolved the problem. :) Confirmed that Strangeland can now startup in master with your commit.
