### ISSUE TITLE
Reported scaling and walk bugs in Space Quest 4.5 The Voyage Home

### ISSUE THREAD

**Issue by dreammaster** [adventuregamestudio/ags#1383]
There have been two bugs reported for Space Quest 4.5, and I've confirmed they happen they happen in the current AGS master, but not in the original bundled executable:
https://bugs.scummvm.org/ticket/12741
https://bugs.scummvm.org/ticket/12742

Savegames are attached to the bug reports. The first is pathfinding issues (I'm presuming). If you enter one of the rooms from the north side in the starting area, Roger can no longer walk. The second is a character zoom issue in several places; as I said, I confirmed that they were sized correctly in the original executable bundled wtih version 3.0 of the game, so maybe there was some change over time how scaling works based on character vertical position at some point

**Comment by ivan-mogilko** [comment]
I believe the scaling problem is fixed with this: 29519a0234168747750f2f3d906e463526a6c0bb

Basically, there's a special logic for hires rooms in old games, that all of their coordinates in data is saved halved down, so they have to be multiplied after load.

**Comment by ivan-mogilko** [comment]
The scaling bug is related to the coordinate system quirk of old games; the game is run as 640x400 but the rooms are 320x200, and when the engine tests for the walkable area zoom under the character's position, they get incorrect percentage. There's a missing or unnecessary coordinate conversion somewhere, but I was not able to find exactly where yet, so will keep investigating.

**Comment by ivan-mogilko** [comment]
Ok, I think I found a right fix for character scaling: 60d79d1ee26b642ef4bcc7c18dfa53540e7ae77f

**Comment by ivan-mogilko** [comment]
@dreammaster seem to have fixed the walkable area bug: f33e064cd148c6a709ccbf25a5fd4939272a7814

This one was very obscure... I had to make series of tests with the old 2.72 editor to figure out what's going on.

In short, apparently, there had been a (possibly) unintentional effect when the player character was forced snapped to a walkable area after room change, under very specific combination of conditions:
1. ChangeRoom is called not by the regular script, but by the "interaction list" (this is a form of action triggers predating AGS scripting language, you may see it [here in code](https://github.com/adventuregamestudio/ags/blob/master/Engine/script/script.cpp#L804));
2. The player character was walking when the interaction is triggered.

This is precisely what happens in that game, where this action is triggered as soon as the player crosses the "room edge".

**Comment by dreammaster** [comment]
Excellent work on both counts. Thanks for identifying and fixing them both so quickly.
