### ISSUE TITLE
android single game package question

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#1394]
since i can't comment directly in the thread #1389, here's a question that i had for a long time:
afaik android has a system that uniquely identifies an application according to its class names,
so there would need to be some mechanism to rename the starting class name depending on the game title, otherwise if 2 games where bundled (e.g. game data appended to binary build) using the same class names and installed on the same device, the names would clash and probably cause issues.
so is this adressed somewhere ?

**Comment by ivan-mogilko** [comment]
If I understand correctly (from this updated [readme](https://github.com/adventuregamestudio/ags/blob/master/Android/mygame/README.md), and from older instructions we had previously on forums), the user is supposed to use provided "single game" project as a template, and configure several things, including changing package name.

Right now this is done by hand, ideally in the future I hope there will be some script for this, and also we are planning adding Android build menu into the Editor.
