### ISSUE TITLE
Recreate Spritecache when no spritecache is found by Editor

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1404]
**Describe the problem**
Spritecache is a big binary file that is hard to store in source control systems like git, requiring all sorts of workarounds. I would like to be able to restore the spritecache from the source files (images) in the project directory and the `Game.agf` file information (which holds things like the sprite ID, sourcefile and import configs.

**Suggested change**
I have often been thinking that #702 is a requirement for this but maybe there's some other way, so I decided to open a separated issue for just that. Being frank, if it solves at least just this case, it would bring a huge quality of life improvement.

The idea is, when the Editor loads a project, if no spritecache is found, it would import all sprites on load and recreate the missing spritecache.

**Relevant forum topics**
- https://www.adventuregamestudio.co.uk/forums/index.php?topic=57647.0
- https://www.adventuregamestudio.co.uk/forums/index.php?topic=48685.0

**Comment by ivan-mogilko** [comment]
Pushed a "SpriteFileWriter" (62a87664fc9249bad2886b44d10affc4d60071c3), made from a code extracted from `SpriteFile::SaveToFile`, this allows to do step-by-step sprite writing.

**Comment by ivan-mogilko** [comment]
On a side-note. I was not was not certain where to put this, so mention here for now. It could be moved to its own ticket, but I dont want to create a new task atm.
There's a potential for writing an sprite reader/writer implementation that works with sprites saved in separate files on disk. Similar to what you've mentioned in #702, sprites could be saved already in a converted internal "ags" format. SpriteCache class itself does not care where the sprites come from, it only caches them and provides for the user (editor panes), so in-memory management and drawing sprites in the editor won't change.

The biggest problem I found in this approach (and #1281 will have the same), is how and when the sprite blob will be created. It's easy to do this only when compiling the game, but then the quick-test will either take lots of time to launch in larger projects, or it won't include recent changes.
One possible resolution of this is to actually let engine use same technique (same sprite reader) and read sprites from separate files. That will be slower, but may be okay for a test mode.

**Comment by ericoporto** [comment]
Uhm, maybe if there's no sprite cache or the specific sprite ID (say 3) isn't on the sprite cache, defer to attempt to load the specific image file like `spr00003.blob` or `spr00003.bmp` using the AssetManager? This would require something similar to Audio Cache.

**Comment by ivan-mogilko** [comment]
> if there's no sprite cache or the specific sprite ID (say 3) isn't on the sprite cache, defer to attempt to load the specific image file (like `spr00003.blob` or `spr00003.bmp`) using the AssetManager? This would require something similar to Audio Cache

Yes, that's the point of the above idea.

**Comment by ivan-mogilko** [comment]
I prepared an experimental branch which saves a sprite file by reading sprites from source:
https://github.com/ivan-mogilko/ags-refactoring/tree/360--exp-spritefilerecreate

If the Editor is run in debug configuration, there will be 2 new commands in the Help menu:
* "Test SpriteWriter read from SPRITECACHE"
* "Test SpriteWriter read from SPRITE SOURCES"

First reads sprites from active spritecache (memory + acsprset.spr), second replicates the sprite reimport using sprite's settings.

Internally, added AGS.Native.SpriteFileWriter which is a managed wrapper over the native class of same name. Its interface is limited in attempt to make it as easy to use as possible.

The sprite file generation is done in the SpriteTools C# class (prototype methods TestSpriteWriter1 and TestSpriteWriter2), where it reads sprites one by one from the given location (either native spritecache or source files).

**Comment by ivan-mogilko** [comment]
Opened a PR draft: #1594.

**Comment by ericoporto** [comment]
Amazing! Hey, this is really important for me so I want to check with some projects and different image files, but it will take me a bit to test it, I will write in the PR once I manage to do so. Thank you!

**Comment by ivan-mogilko** [comment]
Regarding the error message, according to the Microsoft docs ListView control limits its item text to 259 characters:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listviewitem.text?view=windowsdesktop-6.0#remarks

These error messages were originally written for displaying in a message box. A quick fix would be to adjust them for this restriction, but proper solution would perhaps be to use a different control for output.
