### ISSUE TITLE
Engine is not able to close the game with the "hanging" script

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1411]
**Describe the bug**
If the game features a script that "hangs", e.g. with infinite loop, the game window cannot be closed. Before 3.6.0 engine would simply not respond to a app close event, in 3.6.0 it seem to crash in this situation.

**AGS Version**
Probably any recent version, tested in 3.5.1 and 3.6.0.

**To Reproduce**
Have following script in game:
<pre>
void noloopcheck Hang()
{
   while(true) {
      int i; //arbitrary no-op
   }
}
 
void repeatedly_execute_always()
{
    Hang();
}
</pre>

**Expected behavior**
Game script should not prevent the engine from closing the game. At the minimum closing application when receiving a system event should work (for example, player closing the game window). If possible, AGS abort key (alt+x by default) should also work, but I'm not sure if it's easy to do without larger code refactor.

**Comment by ericoporto** [comment]
The large refactor looks to be something closer to https://github.com/adventuregamestudio/ags/issues/1349
