### ISSUE TITLE
Pure virtual call from update_mp3_thread

### ISSUE THREAD

**Issue by onitake** [adventuregamestudio/ags#142]
It seems this issue has already cropped up a year ago, but was never really fixed. I'm not 100% sure if it's not something else though, so I'm reporting this as a new issue.

With current AGS, I frequently get aborts due to a pure virtual call. Sometimes they happen very early after starting a game, sometimes when I exit, sometimes not at all.
I'm running a custom plugin, but that doesn't show up in the stack trace.

From gdb:

```
#0  0x00007ffff60bd3a9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff60c04c8 in __GI_abort () at abort.c:89
#2  0x00007ffff5de45e5 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5de2746 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5de2773 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5de326f in __cxa_pure_virtual () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00000000005276c8 in Release (this=<synthetic pointer>) at ../Engine/util/mutex_lock.h:36
#7  ~MutexLock (this=<synthetic pointer>, __in_chrg=<optimized out>) at ../Engine/util/mutex_lock.h:58
#8  MYSTATICOGG::poll (this=0x2d47fd0) at media/audio/clip_mystaticogg.cpp:54
#9  0x0000000000524d4f in update_mp3_thread () at media/audio/audio.cpp:875
#10 0x0000000000519839 in engine_update_mp3_thread () at main/engine.cpp:1254
#11 0x0000000000525872 in AGS::Engine::PThreadThread::_thread_start (arg=0x909200 <audioThread>) at ../Engine/util/thread_pthread.h:96
#12 0x00007ffff673c062 in start_thread (arg=0x7fffe5454700) at pthread_create.c:312
#13 0x00007ffff616da3d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

AGS reports itself as: ACI version 3.3.0.1158
OS is Debian jessie amd64. I'm running a 64bit build of AGS.

**Comment by ivan-mogilko** [comment]
Needs to be retested with 3.5.0 after threaded audio was rewritten (with threaded audio on).

**Comment by ivan-mogilko** [comment]
I'd like to close this ticket, for same reasons as #82 : it's too old and audio code changed a lot since.

If the problem resurfaces with the new version it's best to open a new ticket.
