### ISSUE TITLE
AGS4, Editor: Shift-rightclick quirks

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1427]
**Describe the bug**
When editing hotspots etc. in a room, ~~middle-click~~ Shift-rightclick doesn't call up the context menu item "Copy mouse co-ordinates to clipboard" under certain circumstances, see below.

**AGS Version**
AGS 4.0, commit 9719b05
Build https://cirrus-ci.com/build/4889336761024512

**Game**
[ShowBug.zip](https://github.com/adventuregamestudio/ags/files/7303179/ShowBug.zip)

**To Reproduce**
- Unpack game.
- Load game in Editor
- Edit room 1
- "Edit this room's: Room ... Hotspots ... hGlowingOrb"
- ~~Middle-click~~ Shift-rightclick into the floor directly under the grandfather clock (to be specific here. But AFAICS, every other room location yields the same result)
- Note that there isn't any context-menu, in particular the item "Copy mouse co-ordinates to clipboard" is missing.

![image](https://user-images.githubusercontent.com/41213694/136382598-e3bb7b91-0568-437f-b91d-db78900d1efa.png)

**Expected behavior**
Context menu provided; when menu item is selected, the current mouse co-ordinates are copied into the clipboard.

**Screenshots**
See above.

**Desktop (please complete the following information):**
Windows 10 German edition

**Smartphone (please complete the following information):**
 n/a

**Additional context**
* No Shift-Rightclick functionality with hotspot mode when straight-line or rectangle tool is selected
* In the "Edit this room's Room ... Objects", it seems as if Shift-Rightclick opens the "Place New Object Here" menu, then a fraction of a second later, the "Copy mouse co-ordinates to clipboard" menu "overlays" the other one (?).

**Comment by ivan-mogilko** [comment]
The reason why "Copy coordinates" was not set to right click originally was that right click works as a eraser when painting masks. You paint area by holding LMB and erase by holding RMB.

**Comment by ivan-mogilko** [comment]
I recently did a change to how the context menu works, merging all possible commands into one, and making it work more reliable.
As far as I can tell, there's currently a remaining issue with the "Line" tool, where it randomly would still draw a line even though the context menu was called.

**Comment by ivan-mogilko** [comment]
Fixed the problem with the line tool: 754fc299950cf55b8b5ca68dd1fbecd9c1724588

I think this may be closed now, but if there are other problems with calling a context menu, then reopen or perhaps open a new one.
