### ISSUE TITLE
AGS4/Editor: Flood fill on walkable area fills wrong area

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1431]
**Describe the bug**
On a flood fill for a walkable area, the wrong area is flooded. See screenshots below for details.

**AGS Version**
AGS 4.0, commit 9719b05
Build https://cirrus-ci.com/build/4889336761024512

**Game**
[ShowBug.zip](https://github.com/adventuregamestudio/ags/files/7337335/ShowBug.zip)

**To Reproduce**
1. Unpack and load game.
2. Edit room 1.
3. "Edit this room's: Room … Walkable area … Walkable area ID 7"
4. Select "Fill area" tool (CTRL-F).
5. Click on a spot below the grandfather clock.
6. Note that an area floodfills that doesn't contain the spot that was clicked on. Cf. screenshot below.

**Expected behavior**
The walkable area below the grandfather clock floodfills.

**Screenshots**
![image](https://user-images.githubusercontent.com/41213694/137116029-282b4a96-c86e-4f04-aa59-96ba1c15260a.png)

**Desktop (please complete the following information):**
 - Windows 10, German edition

**Smartphone (please complete the following information):**
 - n/a
 
**Additional context**
(none)

**Comment by AlanDrake** [comment]
Solved by #1435
