### ISSUE TITLE
Stable release does not compile on Debian 11

### ISSUE THREAD

**Issue by ffaf1** [adventuregamestudio/ags#1432]
**Describe the bug**
Stable release does not compile on Debian 11

**AGS Version**
ags_3.5.1.11_source

**Game**
N/A

**To Reproduce**
Download `ags_3.5.1.11_source`, untar, cd, install all the deps as README suggest, then `make --directory=Engine`.

```
/usr/bin/ld: cannot find -laldmb
/usr/bin/ld: cannot find -ldumb
```

**Expected behavior**
Program compiles.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian
 - Version 11

**Comment by ivan-mogilko** [comment]
Actually, the first commit that removed a reference to "aldumb" from the readme was 3bb17741eb48c75fbc024aa443e82c50c7c9dd71

@ffaf1 can you please confirm that it will build if you install "libaldmb1-dev"?

**Comment by ivan-mogilko** [comment]
@ffaf1 

I restored the instructions in the readme (3bdcdcd21bcb496eae3fae1f47bec50772d90fd4), and made a new formal release, although no code has changed of course: https://github.com/adventuregamestudio/ags/releases/tag/v.3.5.1.12
