### ISSUE TITLE
ags does not recognise «two-fingers-on-touchpad-tap» as rightlick

### ISSUE THREAD

**Issue by ffaf1** [adventuregamestudio/ags#1434]
**Describe the bug**
2-finger-on-touchpad right click does not work in AGS.

**AGS Version**
3.5.1.11

**Game**
7 Days a Skeptic or any game where a right click is needed.

**To Reproduce**
Have xorg configured to accept 2-fingers-on-touchpad as «right click». Check that it works on multiple applications (Firefox, wine, etc.). Now launch AGS: you will only be able to right click using the bottom right button of the touchpad.

**Expected behavior**
Recognise whatever xorg does.

**Desktop (please complete the following information):**
 - OS: Debian
 - Version 11

**Comment by ffaf1** [comment]
I would test it myself, if there is a way to compile AGS without having to install a custom sdl_sound2 library (I prefer to keep my system clean and not a frankendebian).

**Comment by ivan-mogilko** [comment]
@ffaf1 I'm sorry I could not reply earlier, i got quite distracted in the past couple of months and only focused on my priority work.

Did you make any more attempts to test our 3.6.0 version; is there's still a problem with sdl_sound library?

**Comment by ffaf1** [comment]
Hello Ivan, no worries and happy 2022! Where I am at the moment:
- I cloned the repo
- `README.md` for debian is still incorrect, (sdl_sound archive to download should end in `.tar.gz`)
- once download that file, I unpacked it and built it (in `SDL_sound-c2aeae538ab47877916b5c8569a3525ef179acef/build`), no idea on what to do now (re: please do not let me install stuff that is not in the repos)

If you tell me how to invoke `make` (i.e. to tell it “needed library is there”) I will gladly test this!

Il 01 gennaio 2022 alle 15:33 ivan-mogilko ha scritto:

**Comment by ericoporto** [comment]
@ffaf1 if you are familiar with CMake, the CMakeLists.txt is scripted to download and build the dependencies and statically link to them. You can probably `sudo apt install cmake` and just run the code below:

    mkdir build-release
    cd build-release
    cmake .. -DCMAKE_BUILD_TYPE=Release
    make

**Comment by ffaf1** [comment]
Thanks Eric, I had to sprinkle `#include <stdio.h>` in a dozen of files, after that it compiled.

I tried to play “7 Days a Skeptic” again, two-finger-tap for right click now works!

Il 02 gennaio 2022 alle 03:53 e ha scritto:

**Comment by ericoporto** [comment]
> I had to sprinkle `#include <stdio.h>` in a dozen of files

@ffaf1 hey, do you remember which files? Are them `Engine/ac/global_audio.cpp`, `Engine/main/game_start.cpp`, `Engine/main/quit.cpp`, `Engine/script/script.cpp` ? Can you tell which compiler version you used?

**Comment by ffaf1** [comment]
git status says:

        modified:   Engine/ac/dialog.cpp
        modified:   Engine/ac/display.cpp
        modified:   Engine/ac/draw.cpp
        modified:   Engine/ac/global_audio.cpp
        modified:   Engine/ac/global_game.cpp
        modified:   Engine/debug/debug.cpp
        modified:   Engine/main/game_start.cpp
        modified:   Engine/main/quit.cpp
        modified:   Engine/media/audio/audio.cpp
        modified:   Engine/platform/base/agsplatformdriver.cpp
        modified:   Engine/script/script.cpp


***@***.***:~/media/vcs/ags$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110

Il 02 gennaio 2022 alle 04:50 e ha scritto:

**Comment by ericoporto** [comment]
@ffaf1 Thank you!

About the reported issue, it's not a problem then in current master with SDL2, is this correct?

**Comment by ffaf1** [comment]
It is not a problem in current master with SDL2! This issue can be closed.

Il 02 gennaio 2022 alle 05:01 e ha scritto:

**Comment by ivan-mogilko** [comment]
Good to hear; we just need to add missing stdio includes then to make this build on your system.

**Comment by ivan-mogilko** [comment]
@ffaf1 btw you can of course open a pr with the missing stdio.h added, or a bug ticket.
