### ISSUE TITLE
Attempt to improve Font's Height handling in games

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1441]
So I've been researching problems with TTF fonts display in ags recently (https://github.com/adventuregamestudio/ags/issues/888), and think that understand the issue much better now. I've pushed some changes that may help maintain backward compatible arrangement of the texts in the old games and at the same time add potential to further improve the situation in the new games. But I'm still not fully certain of what would be expected and convenient solution from the user's perspective; and that is why I am opening this ticket.

## Problem summary

AGS historically has hacks to the TTF font library, that have two primary consequences.

### Loaded font sizes

The way TTF fonts work is that they, as vector fonts, cannot translate 1:1 to any random pixel size. There's even a note about that in, for example, FreeFont documentation ([link](https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_set_pixel_sizes)): *You should not rely on the resulting glyphs matching or being constrained to this pixel size*. I think this is because they can't scale to any random pixel size without loosing proportions.
What this means is that when the font library tries to init a TTF using "font size" as a request, the resulting size could be identical, less, or larger than requested.

Alfont library, which is a wrapper over FreeType that AGS uses, normally does following: if the font size does not match the requested one, then it will try to lower/increase the request until finding the closest possible actual size. You may observe this behavior [in the library code](https://github.com/adventuregamestudio/ags/blob/8a735b4/Common/libsrc/alfont-2.0.9/alfont.c#L431).

However, AGS contains [a hack](https://github.com/adventuregamestudio/ags/blob/8a735b4/Common/libsrc/alfont-2.0.9/alfont.c#L428) to this library that instead makes it choose the very first result and keep it. This leads to some fonts being notably larger than requested. E.g. a font imported with size 52 may in practice end up being 62 pixels high - that's about 1/5 more!

### Reported font sizes

To complicate the above, there was another hack that saved not the real font's size, but the requested font size. Which leads to the engine using this "nominal" requested height in any text or UI arrangement, and reports this height in script too (with calls to GetFontHeight, GetTextHeight, etc). This means that the fonts are not guaranteed to fit in precalculated borders, and game developers cannot programmatically learn the real height of the font either.

One known consequence is infamous issue of some fonts getting their bottom pixels "cut off", because the engine cannot correctly resize the texture it's drawing them on.

## Considering solutions

So, the question is, where do we want to go from here.

Technically it seems possible to apply any wanted changes while also keeping a "backward compatible" mode to let old games display same way.

I think first of all engine should stop pretending that the font is one size while it's in fact another, and use and report correct font heights. Note that the linespacing is by default matching font height, so it will be slightly different for the same fonts; but linespacing is today possible to customize by hand.

For this I've been thinking to add a game setting, called e.g. "Use real font height in game logic", as seen in [this prototype commit](https://github.com/ivan-mogilko/ags-refactoring/commit/853a5bcd6a669c4fbcdc3e7be6cc634d40c0da18). True by default, but if set to false it will go back to using "nominal" height as it does currently: that will keep backward compatible game looks.

But then there's another question: what are user expectations about the imported font heights? That is, when user tells AGS to import a TTF font of size 20, do they expect it to be exactly 20 pixels (or at least as close as possible), or they don't care and just use this as an arbitrary number, while relying on practical visual tests of their game?

If we think that AGS should try to match user request as close as possible, then there has to also be an engine mode where it treats this font's import height as a pixel height to which it should try to find a proper match; an additional setting perhaps, or a merged setting that would switch between "legacy" and "proper" font loading mode.

**See also:** #447, #888

**Comment by ivan-mogilko** [comment]
So, I added the setting to use real font's pixel height in the game logic (f36dc506f8d79ab27bfbd2e58d73f715a97c53bb), and also editor displays always real pixel height in "Font Height" field now, for the easier reference (2d9a71ba32dc7abfd882801ee3ceb97598f321bf)

**Comment by ivan-mogilko** [comment]
So, for an update, added two properties to the General Settings:

1. "TTF fonts height used in the game logic": can be "Nominal height" (compatible default) or "Real pixel height".
2. "TTF fonts adjustment": can be "Resize ascender to the nominal font height" (compatible default) or "Do nothing".

For now I followed @AlanDrake 's advice and set backward compatible values as defaults, mostly because noticed that some fonts used in our game template break if no fixups are made.

Also, added "Family Name" readonly field to the fonts (in the editor), for the reference, because I always wanted to see the source TTF names.

**Comment by ivan-mogilko** [comment]
> "TTF fonts adjustment"

I ended up making this property per-font instead, as some TTF fonts are actually made for AGS, taking this historical behavior into account; so I thought if someone happen to use both standard and AGS-specific TTFs in one project, they might want to have them configured separately.

**Comment by i30817** [comment]
I really appreciate you taking the time to keep all these old crusty games working with the insane engine hacks this engine accumulated over the years being reversed from the 'original' flawed editors.

**Comment by ivan-mogilko** [comment]
I opened a pr for importing TTF with the closest pixel height (#1450), that's the last thing remaining, so I will close this ticket regardless of whether the pr is merged or if considered unnecessary.

**Comment by ivan-mogilko** [comment]
I think most of changes are done now. There was another suggestion about adding a script function for getting a "nominal font's height", but I'll postpone that until there's a real use case for that.
