### ISSUE TITLE
AGS4: Setting a visible Label to `Visible = true` makes it invisible.

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1444]
**Describe the bug**
The game below has a `room_RepExec()` event that sets the action label (which already is visible) to visible. This makes the action label NOT show. 

**AGS Version**
AGS 4.0, commit 9719b05
Build https://cirrus-ci.com/build/4889336761024512
Confirmed for
AGS 4.0
Commit  7717d3f1

**Game**
[ShowBug.zip](https://github.com/adventuregamestudio/ags/files/7492554/ShowBug.zip)

**To Reproduce**
1. Unpack and run game.
2. Hover over grandfather clock. Note that the action label says "Grandfather clock", as shown in the screenshot.
3. Stop game.
4. In room1.asc, uncomment line 7 `TwoClickHandler.ActionLabel.Visible = true;`
5. Restart game.
6. Hover over grandfather clock. Note that the action label does NOT show.

**Expected behavior**
If a visible label is set to visible, as it is here, it should show.

**Screenshots**
![image](https://user-images.githubusercontent.com/41213694/140651332-4e97f5ea-2ea4-4f73-82f4-72075fa9b4fc.png)

**Desktop (please complete the following information):**
 Windows 10, German edition

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by ivan-mogilko** [comment]
Debugging the engine shows that when GUIControl::set_Visible is called, the parameter is not the integer (as expected for a boolean attribute), but of "Dynamic object" type, and its pointer address is equal to the "this". It seems that somehow the value of "this" gets duplicated into the first normal function argument.

When using old script compiler there's no such error, which make it seem like an issue is in the new script compiler.

**Comment by fernewelten** [comment]
Oops ... Thanks for the pointer.

I've decided that it's high time to start having the courage of my convictions. To find out to what extent AGS4 and the compiler is already suited for serious programming, at some point you simply have to try and actually __do__ it.

So I've started to develop a jam-sized adventure in AGS4, creating and installing the graphics and writing the code, always opting to use the new possibilites wherever I thought it would make sense from a user/coder perspective. So that's how the recent bug reports came to be. I'm mainly focused on the compiler, of course, finding and fixing bugs and snafus and annoyances whenever they come up, but whenever I happen on snags in other parts of the cockpit, I'm reporting them, too.

**Comment by fernewelten** [comment]
Can confirm. The compiler loads "true" into AX and doesn't push/pop the register afterwards to protect it from being clobbered. So when the value is needed, it's gone. 

There's a flaw in the logic that will only show up with chained __attributes__, as in `TwoClickHandler.ActionLabel.Visible`.

Righto …

**Comment by ivan-mogilko** [comment]
Fixed by #1448
