### ISSUE TITLE
Editor: Upgrading .NET for compatibility with VS 2022

### ISSUE THREAD

**Issue by persn** [adventuregamestudio/ags#1446]
VS 2022 was released this week and it seems I am no longer able to build the editor code after upgrading and the reason seems to the [following](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)

![image](https://user-images.githubusercontent.com/1510803/141541097-757bd68d-5ae1-4504-993a-ca79b62d4420.png)

Checking the [.NET system requirements](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements) it seems we can upgrade up to .NET 4.6 without breaking any OS support. Although maybe we should take the opportunity to assess if we still need to support Vista users, if not we could upgrade up to .NET 4.8, but possibly even .NET 6 depending on how much rewrite it would take. Both are supported by Windows 7 SP1

**Comment by ivan-mogilko** [comment]
@persn is it fine working with the editor's project on latest VS, does it require any tweaks or works seamlessly? I am still using VS 2015 as this was the version we upgraded to from VS 2008. Would it also make sense to upgrade the VS project version?

**Comment by persn** [comment]
I can't vouch for how it's developing on the Engine in VS2022, but I gave a quick test upgrading to .NET 4.6 on a private branch and it worked without any issues as far as I can tell. Although I've tested only for 5 minutes

I'm not sure about upgrading VS version, I didn't upgrade and I didn't notice any issues because of it

I can make a draft PR of my work and then maybe people could test it out at their leisure

**Comment by persn** [comment]
> Although maybe we should take the opportunity to assess if we still need to support Vista users, if not we could upgrade up to .NET 4.8, but possibly even .NET 6 depending on how much rewrite it would take. Both are supported by Windows 7 SP1

Actually maybe let's not do this right now, we could rather revisit the topic when ags4 is close to a release version whenever that is

**Comment by persn** [comment]
If someone merge `ags4` with `master` I can finish upgrading the remaining test project. I tried doing it myself but there's a merge conflict with a c++ file that I don't know how to resolve.

**Comment by ivan-mogilko** [comment]
Ok I merged it.

**Comment by persn** [comment]
Thanks

**Comment by persn** [comment]
This should be resolved now. The next logical upgrade of .NET would possibly be .NET 6. I'll think I'll experiment with upgrading on the side to see what is necessary to do of refactorings in preparation of an upgrade since .NET 5/6 breaks backwards compatibility with .NET 4
