### ISSUE TITLE
Consider expanding voice clip naming rules

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1456]
**Problem**

Currently voice-over clip filenames are restricted to NNNNX.ext format, where NNNN is four first letters of character's script name *except the leading small 'c'* (this is because characters were often called `cNAME`) and X is a number in the range of positive 32-bit integer. Older engines supported only 4-digit numbers 1-9999, but that restriction was since removed. I believe this name format may be a legacy of DOS support (8.3 filenames).

The name rule may cause conflicts between characters with similar script names and usually forces gamedev to edit script names to make first 4 letters unique.

Limit of 9999 clips per character is reached less often, but sometimes being ran into. In such case users usually use dummy characters to increase number of slots.

Neither of the issues above is game breaking, but may cause much annoyance and inconvenience. So this task is not ultra-critical, yet something to consider.

**Suggestion**

Instead voice clip format should be "NAMEX.ext", where NAME is full character's script name.

NOTE: @messengerbag has suggested an alternative to this: introduce new Character's property to define voice-name, which is equal to its script name stripped of small `c` prefix by default. This will help if a user does want to keep the script naming convention which suggests start names with `c` for characters, in which case all the voice clip names would have to begin with redundant "C".
Keeping a rule to strip `c` prefix may be causing confusion if characters have all lowercase script names, as their names and this prefix are not enforced neither by engine nor tools.

**Comment by ivan-mogilko** [comment]
NOTE: somehow I did not realize earlier, but speech numbers are no longer restricted to 4-digit (9999) since 3.5.0, as editor packages Speech using newer lib format that allows for longer filenames (engine seem to had never restricting that).

**Comment by ivan-mogilko** [comment]
Various discussions on forums and ags discord keep remind me of this issue.

Unless I miss anything, this might be relatively simple to implement, but two things has to be kept in mind:
- backwards compatibility (if this is also done in 3.*, and if user imports older project to ags4)
- the name forming involves implicit stripping of `c` prefix, regardless of whether user wants or not.

A reminder about the latter:
> NOTE: @messengerbag has suggested an alternative to this: introduce new Character's property to define voice-name, which is equal to its script name stripped of small c prefix by default. This will help if a user does want to keep the script naming convention which suggests start names with c for characters, in which case all the voice clip names would have to begin with redundant "C".

So, I don't think having a separate property for each use of character's script name would be nice. OTOH i doubt if that would be convenient to merge with a character's "dialog nickname" proposed elsewhere (#1274), as the syntax may be different (filename vs arbitrary name in conversation script).

So perhaps there could be a property called "AssetName", which purpose is to be used *whenever any file must be linked to a character*. Does that make sense?

Following a comment https://github.com/adventuregamestudio/ags/issues/1274#issuecomment-1493232138
the plan could be:

1. Introduce AssetName property in Character.
2. Optionally add this property in script, but make it readonly, as I doubt there's a sense to change it at runtime? (I suppose it should stay readonly at least unless we support dynamic creation of characters).
3. The *default value* in the new game projects: if we abandon the old rule, then it should be set to ScriptName when a character is created.
4. If this property is not set, then use ScriptName directly, *without any modifications* (old name conversion is NOT used).
5. On project upgrade: assign AssetNames *using old rule* (first 4 letters without small "c" prefix).
6. Similarly, when loading older games into the engine, assign AssetNames same way.
7. On game compilation check and warn about AssetName duplicates.

**Comment by ericoporto** [comment]
When you say default you mean AssetName if not set in Editor (empty), then use `Name` from from `cName` or when the project upgrade, set AssetName to `Name` from `cName`? 

The first means it can "autoconfigure" if `cName` changes but may be less clear (unless the property grid entry uses a different view that shows some hint), the second it has less "hidden" behavior, but it may be less convenient - but its easier to explain.

**Comment by ivan-mogilko** [comment]
By "default" I mean two things that are essentially same:
- a value that is assigned to AssetName when you create a *new* Character in the *new project*;
- a value that is used in case AssetName was left empty for some reason.

I suppose these should use the same rule to set a default value.

When the project upgrades then the situation is different, we cannot use the above, because that will disable all existing voice clips. On upgrade we'll have to assign a value composed of first 4 letters, as in old AGS.

**Comment by ivan-mogilko** [comment]
I'm trying to decide why is it beneficial to have a property, instead of just using a new rule (use whole name length).
It looks like possible reasons are:
- it's clearly displays for the user what engine is going to do
- allows backwards compatibility (an alternate solution would be using a global setting, but that is less clear, and may lead to confusion e.g. in case of using old templates).
- allows to define naming by hand in the edge cases.

**Comment by AlanDrake** [comment]
New rule makes more sense to me, rather than an extra proeprty users will not pay attention to until it explodes on their hands.

**Comment by ivan-mogilko** [comment]
I could actually update the rule and leave property for the future consideration, since one thing does not prevent another.

The question will be how to treat old games, especially old imported projects. Either engine tries 2 voice files (new one and old one), or judges by the game data version, or have a global option that switches between old and new naming rule.

**Comment by AlanDrake** [comment]
Trying both new and old should be fine.

**Comment by ivan-mogilko** [comment]
> Trying both new and old should be fine.

So I thought this at first, but then realized that this may result in playing a wrong clip.

**Comment by ivan-mogilko** [comment]
My last comment made me think further, and I realized that the existing naming rule makes it possible to mess up two or more characters in another way, if they have numbers in their script names.

For example: character names are cGuy1 and cGuy11.
`cGuy1.Say("&11 word");`
`cGuy11.Say("&1 word");`
Both will result in a voice clip name "guy11".

This of course is a very rare case, but it's still possible. Which means that the current rule has a loophole.
Besides, having any digits in character's name makes following clip number harder to distinguish.

The only way to avoid a situation like that completely is to separate name and number with a symbol *that cannot be in a scriptname, but can be in a filename*. Such symbol as a dot ('.') or a hyphen ('-').
I.e. make voice clips called like: `guy1.1.ogg` or `guy-1.ogg`.

**Comment by ericoporto** [comment]
The dot as separation symbol looks good.
