### ISSUE TITLE
--shared-data-dir doesn't exist in the setup menu

### ISSUE THREAD

**Issue by lwcorp** [adventuregamestudio/ags#1458]
**Describe the bug**
[The documentation](https://github.com/adventuregamestudio/ags/blob/master/OPTIONS.md#configuration-file-options) states:

> --shared-data-dir \<DIR\> - set the shared game data directory. Corresponds to "shared_data_dir" config option.

However, there's **no** such config option, at least not in the latest stable version.

**AGS Version**
3.5.1 - Patch 4

**Game**
Multiple.

**To Reproduce**
1. Enter Setup
2. Click Advanced
3. See setting for `--user-data-dir` but not for `shared-data-dir`

**Expected behavior**
There should either be a setting for it in the setup or remove the aforementioned statement from the documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/1773306/144710186-cd3e783c-957a-4a19-b4cd-55374b4d1270.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
Please note that the documentation is refering to the *config file*, not the "winsetup" dialog.

In config file you can do this:
<pre>
[misc]
shared_data_dir = [string]
</pre>

That is true that winsetup dialog does not have a corresponding setting in UI.

**Comment by lwcorp** [comment]
Interesting, I hope you'll consider adding to the setup just next to `--user-data-dir`.

But if you **manually** add values to the config file, will they still be there after you use setup to edit that config file?

**Comment by ivan-mogilko** [comment]
> But if you manually add values to the config file, will they still be there after you use setup to edit that config file?

Should be, winsetup suppose to only overwrite values that it has in the dialog and not delete anything.

**Comment by ivan-mogilko** [comment]
@lwcorp there are multiple variants how to implement this in setup dialog, but one simple thing I could do is to treat this field as both custom save dir and shared data dir, basically letting players set both using one control. I thought about this, because the common use case for these options is to save everything in the game's folder anyway (it seems).

Unless there's a practical reason to separate them for your case?

**Comment by ivan-mogilko** [comment]
Added "Custom shared data path" to winsetup (0ce6d9a61b188dc1dccbd2b3b5434a6900fff8a6). Should be included into the upcoming next 3.5.1 patch.

**Comment by lwcorp** [comment]
> Added "Custom shared data path" to winsetup ([0ce6d9a](https://github.com/adventuregamestudio/ags/commit/0ce6d9a61b188dc1dccbd2b3b5434a6900fff8a6)). Should be included into the upcoming next 3.5.1 patch.

Can you document here when it's released?

**Comment by ivan-mogilko** [comment]
Right, released as 3.5.1.13, several days ago:
 https://github.com/adventuregamestudio/ags/releases/tag/v.3.5.1.13

**Comment by lwcorp** [comment]
It works great thanks (already tried v3.5.1.14), thanks!!!
