### ISSUE TITLE
Using alternate --conf, --shared-data-dir and --user-data-dir still creates (a blank) %ProgramData%\Adventure Game Studio\

### ISSUE THREAD

**Issue by lwcorp** [adventuregamestudio/ags#1459]
**Describe the bug**
Using alternate `--conf`, `--shared-data-dir ` and `--user-data-dir` ([see documentation](https://github.com/adventuregamestudio/ags/blob/master/OPTIONS.md#configuration-file-options)) still creates (a blank) `%ProgramData%\Adventure Game Studio\` which is both futile and hurts the portability purpose of using these parameters in the first place.

**AGS Version**
3.5.1 patch 4

**Game**
All.

**To Reproduce**
1. Start any game using these parameters (make sure all of them use alternate locations)
2. Exit the game
3. See a blank folder in the aforementioned path

**Expected behavior**
Don't create this folder while using these alternate parameters, especially when it just means creating a blank folder.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
I believe fixing this in the master not long ago, will see to porting these fixes to 3.5.1.

**Comment by ivan-mogilko** [comment]
@lwcorp I got distracted for a while, but finally prepared a patch for this problem. I've been testing it myself, but perhaps you may also check it out to see if it works as expected. PR is #1460, the build may be downloaded from our build server: https://cirrus-ci.com/github/adventuregamestudio/ags/pull/1460 by selecting latest task and downloading corresponding build results.

e.g. the latest engine for the Windows is: https://cirrus-ci.com/task/5682835448135680

**Comment by lwcorp** [comment]
> e.g. the latest engine for the Windows is: https://cirrus-ci.com/task/5682835448135680

I confirm it indeed didn't create `%ProgramData%\Adventure Game Studio\`, thanks!

**Comment by ivan-mogilko** [comment]
Resolved by #1460, will release new 3.5.1 patch shortly.

**Comment by lwcorp** [comment]
> Resolved by #1460, will release new 3.5.1 patch shortly.

Can you document here when it's released?

**Comment by ivan-mogilko** [comment]
> Can you document here when it's released?

I'm sorry, it was already released: https://github.com/adventuregamestudio/ags/releases/tag/v.3.5.1.13

**Comment by lwcorp** [comment]
It works great thanks (already tried v3.5.1.14), thanks!!!
