### ISSUE TITLE
3.6.0: "Zniw Adventure" fails to read/parse some of custom data on Linux

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1464]
**Describe the bug**

The game "Zniw Adventure" has dialog translations stored in custom files (as INI format). When run on Linux the game would fail to read and/or parse some of it, causing in-game warnings and missing translation (text is displayed in original Polish language).

This does not happen when run on Windows using same 3.6.x engine.

**AGS Version**
Tested and reproduced in 3.5.0, 3.5.1, 3.6.0 (wip)

**Game**
As far as I know it's available only on Steam at the moment:
https://store.steampowered.com/app/904750/Zniw_Adventure/

**To Reproduce**
1. Run the game, select **English** language.
2. Choose "New game", pass through the intro, you will find yourself near the flower shop.
3. Speak with the flower seller (small dinosaur)
4. As soon as the conversation starts, observe the in-game message:
`WARNING - data error in file lambeo.cdf, section 022 - line number count is 0`.
Also the following speech text will be in Polish instead of English.

**Expected behavior**
No warnings appear in game, and the speech text is displayed in selected language (English).

**OS**
- Noticed only on Linux so far; works well with the Windows engine.
 
**Additional context**
The *.cdf files are basically INI files with regular text inside. They are found in the game's subdirectory "static".
We believe that the files are parsed using [IniFile script module](https://www.adventuregamestudio.co.uk/forums/index.php?topic=46631.0), so the error is either in how engine reads the file, or how IniFile parses the read contents.

**Comment by ivan-mogilko** [comment]
Actually, this happens with 3.5.0 and 3.5.1 engines too (did not test earlier), so this is an old problem.

Curiously, they have a linux version on steam, wonder how it works.

**Comment by rofl0r** [comment]
> Curiously, they have a linux version on steam, wonder how it works.

i suspect they tracked down the bug, fixed it in AGS and ship a modified engine, but didn't share the bugfix.

**Comment by ivan-mogilko** [comment]
@rofl0r I spoke with the game developer, and turns out on Linux they put these files in the game's root, and the scripts use different file path depending on the System.OS variable.

If it's so, then either moving files or using 
```[override]
os=win
```
in config should make it work.

**Comment by ivan-mogilko** [comment]
So, with override setting it works, but I found another problem: the file paths in script contain backward slashes ('\\') and the engine does not fix these for linux, as it does in many other cases.

**Comment by rofl0r** [comment]
> EDIT: I will make engine print requested file path and result of OpenFile to help diagnose similar issues...

i was kinda surprised as i used --log-file=all:all but nothing whatsoever regarding file paths ended up in log.

**Comment by ivan-mogilko** [comment]
Pushed couple of commits.
Now it works if you set the OS override setting in config.
Also prints some info about File.Open script command.

BTW, I suggest `all:info` logging, as script functions have tonn of random stuff written on the most verbose level, mostly related to GUI.

**Comment by rofl0r** [comment]
>  Now it works if you set the OS override setting in config.

wouldnt it be better to do something like `if(!windows) while(( p = strchr(filename, '\\' ))) *p = '/';` in the fileopen function called from script ?

**Comment by ivan-mogilko** [comment]
>  oh, i see, that's what you did but the os override is needed to fix the "if linux, filepaths are broken" workaround.

Yes. Also, apparently you have to start the new game, because they save OS in a variable, which gets written in a game save.

**Comment by rofl0r** [comment]
thanks, it works.
instead of adding os override, i ended up patching the game

```diff
--- O/globalscript.s.orig       2021-12-26 22:54:57.264580377 +0000
+++ O/globalscript.s    2021-12-26 23:25:39.929658071 +0000
@@ -98,7 +98,7 @@
        setfuncargs 0
        li ax, System::get_OperatingSystem
        farcall ax
-       mr bx, ax
+       li bx, 2  ; eOSWindows
        jmpi label000000000091
 label000000000021: ; inside game_start$0, ; referenced by 3 spots
        jmpi label000000000137
```
but it took me quite a while to figure that the variable "osVer" was already saved into the savegame, so i had to start from scratch.

**Comment by ivan-mogilko** [comment]
Alright, this is resolved then.

**Comment by rofl0r** [comment]
there's another issue with the game... after having fixed the OS, in all the cutscenes (like the intro video) the video suddenly stops animating, but one can hear the sound progressing. after something like 20 secs passed, the video suddenly moves on, but the audio is now out of sync, and the last 20 secs of the video then are without sound....

**Comment by ivan-mogilko** [comment]
This may be an issue of how video works in this version, as some things changed with sdl2 port, and threaded audio is now implemented differently.

**Comment by rofl0r** [comment]
alright, it's not that important.

**Comment by ivan-mogilko** [comment]
Well, I will look into this separately, bit later.
