### ISSUE TITLE
Android Launcher: Credits do not work

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1470]
**Version of AGS**
3.5.1, 3.6.0

**Problem**

1. Run the Android AGS Launcher (now called "AGS Player");
2. Open the settings menu ("..." in the top-right corner);
3. Select "Credits".
4. A completely blank page is displayed. Pressing BACK will bring you back to the games list.

**Expected**

A valid credits text is displayed.

Note that 3.5.1 does not display anything either, so this got broken a while ago. Need to research what was the original behavior, restore it or replace with something new but valid.

**Comment by ericoporto** [comment]
So, this one I thought we didn't want to manually maintain a credits screen. Maybe pulling the [text from the manual](https://github.com/adventuregamestudio/ags-manual/wiki/Credits) or the debian packaging info or the licenses in the Editor. Or maybe manually maintaining some text bit 😕
