### ISSUE TITLE
Editor: Switch Preferences UI for a property grid (like General Settings)

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1477]
Currently the Editor preferences is a nicely handmade screen like this

![image](https://user-images.githubusercontent.com/2244442/147975612-73ae5dba-5b6e-4158-abf4-92e917c0c3dc.png)

It's functional, but adding an item in the preferences requires juggling around - I am currently adding some things in the bottom left corner there and I feel the next person will have some hard time on this screen...

I would suggest redoing it similar to general settings, which uses the property grid. This would probably require some rework, like the path search needs  to be possible in the properties, but it would make it less cumbersome to add or change preferences.

I would like some opinions on this.

**Comment by persn** [comment]
I've been annoyed by the same thing in the past so I'm all for this. It would be best if changed this screen to change dynamically as we added new properties

**Comment by ericoporto** [comment]
I was totally expecting a Preferences.cs on AGS Types and was very frustrated when I found out things weren't exactly like this xD

I can do the change btw, I just want to see if there's something that I am forgetting.

**Comment by persn** [comment]
Adding an `IPreferences` to AGS.Types would be welcome at the same time. Interface can be extracted from `AppSettings` in `EditorPreferences.cs`, and any related types would also have to be moved.

**Comment by ericoporto** [comment]
> Adding an IPreferences to AGS.Types would be welcome at the same time. Interface can be extracted from AppSettings in EditorPreferences.cs

I am looking at `AppSettings` but I don't think I understand how such interface would be. 

> any related types would also have to be moved.

They all appear to be defined in the same `EditorPreferences.cs`.

Also, in my thinking Recent Games would be somewhere else... Not sure where, but it and Recent Searches look like something that should be... Elsewhere 🤔

**Comment by persn** [comment]
> I am looking at AppSettings but I don't think I understand how such interface would be.

Something like this I recon.
```csharp
public interface IPreferences
{
    TestGameWindowStyle TestGameWindowStyle { get; set; }
    StartupPane StartupPane { get; set; }
    // Etc.
    void Save();
}
```

Keep in mind that this would just be desireable, you don't actually have to do it for the sake of this issue

**Comment by ivan-mogilko** [comment]
> Also, in my thinking Recent Games would be somewhere else... Not sure where, but it and Recent Searches look like something that should be... Elsewhere

To clarify, AppSettings class is managing ALL the data that Editor saves for the current user. Its purpose is *loading and saving* that data, not displaying or using on a particular window. Also, it is bound to the internal .NET methods of serialization, that are hidden from us, in other words we *don't control* how that data is saved (unlike the game data).

When the game or workplace settings are saved, separate classes or components may request to save their data in particular xml nodes, and write/load in a custom way, as they prefer ([look for sprite import info serialization for example](https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Types/Sprite.cs#L294)).
With the way AppSettings work now, it's unlikely that you will be able to do the same. Everything goes through ApplicationSettingsBase and SettingsBase .NET classes, and is written as they prefer in their own format.

This means that you have to make a choice: if keeping existing serialization of Editor's user config, then the new Preferences class should not serialize itself, but instead something (some outside "controller" class perhaps) should take its object and pass into AppSettings using its (or its base classes) methods.

If you want to save Preferences object using same the serialization as used by the game classes in the Editor, then we will have to change how app settings are serialized, upgraded, etc, altogether (again).

**Comment by ivan-mogilko** [comment]
To summarize:

Current AppSettings is a *app settings serializer*. It does not have anything to do with Preferences *window*. All it does is saves and loads certain options in standard .NET way.

There have to be a separation between `Preferences` as an object that provides particular group of settings -- and a `Serializer` that reads/writes these. That "Serializer" may be either AppSettings, or something using our SerializeUtils, depending on how we want to save these.

Also important, right now AppSettings has all the explicit properties in it, so it not only knows *how* to save, but it knows *what* to save. This may be not a good thing, since keeping this will require us to duplicate properties from Preferences. So likely this should be changed.

**Comment by ivan-mogilko** [comment]
To summarize:

Current AppSettings is mixing the *properties object* and *serializer* behavior. So it not only knows *how* to save, but it knows *what* to save.
It does not have a direct connection with "Preferences" *window* though. It does save and load certain options in standard .NET way, and lets other to get or set these.

I believe there have to be a separation between `Preferences` as an object that provides particular group of settings -- and a `Serializer` that reads/writes these. That "Serializer" may be either AppSettings(Base), or something using our SerializeUtils, depending on how we want to save these.

Saving any property in AppSettings(Base) seems to be as simple as `this["PropertyName"] = value`, except "value" may be a complex object for lists etc. Perhaps AppSettings class could stay as a helper class that helps saving properties into .NET standard storage.

**Comment by ivan-mogilko** [comment]
@persn keeping above in mind, reading your [previous comment](https://github.com/adventuregamestudio/ags/issues/1477#issuecomment-1004729786) regarding the interface, makes me doubt  if that is really a good idea. What is this interface of? - of a set of properties, a serialization, both? What would be its use?

**Comment by ericoporto** [comment]
> the new Preferences class should not serialize itself, nor rely on the common xml serialization we use for the game classes, but instead something (some outside "controller" class perhaps) should take Preferences object and pass its properties into AppSettings

I was thinking more in the sense of having a class that it's properties magically reflect in the UI, similar to General Settings, I was not thinking about saving and other things, but say this class is a property/node on the current `AppSettings`, then everything else could be kept as is?

Anyway, I forgot about upgrade paths and all that, so I don't feel I can make this change now. I was thinking more on the UI side.

**Comment by ivan-mogilko** [comment]
> I was thinking more in the sense of having a class that it's properties magically reflect in the UI, similar to General Settings, I was not thinking about saving and other things, but say this class is a property/node on the current AppSettings, then everything else could be kept as is?

It looks like that may work. I.e.
* `Preferences` class as a part of AGS.Types, with properties organized similar to other types (decorated with attributes, etc);
* AppSettings need to somehow get or contain the Preferences object and serialize it. Tbh I did not learn fully how it saves complex objects, one might experiment and see what happens if you try to just give it a whole class as an object to save and load. If that won't work well, perhaps have a helper method that iterates over all the object's properties (using reflection) and feeds them into AppSettings serializer one by one, similar to how SerializeUtils do (property's name is the key under which it's saved, and so on).
* The new window might have a PropertyGrid, and since Preferences class is correctly decorated, then it will display all properties just like it does to other classes.

**Comment by ericoporto** [comment]
I have an idea on how the Preferences class would work [here in this **gist**](https://gist.github.com/ericoporto/d5644040f292d148bfe243ef566490d2#file-preferences-cs). I could not figure out how to actually use it, the recent games, searched stuff, and window position I don't think should be in the same place.

**Comment by ivan-mogilko** [comment]
IMHO recent games, etc, could be left right in the AppSettings for the time being.

I imagined that the simpliest way would be for AppSettings to have Preferences object in it, replacing all the relevant properties.
The question is mostly whether it's capable of correctly reading/writing whole object, or we need to write instructions where it saves property by property taking them from Preferences.

**Comment by ericoporto** [comment]
erh, perhaps we can leave everything in AppSettings but just mark all the non-preferences things that are there with `IsBrowseable(false)`, then the save and load of preferences can remain the same!
