### ISSUE TITLE
Autocomplete issue with strings with commas in the Editor

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1481]
**Describe the bug**
Sooo I'm having a weird autocomplete issue and I can't make heads or tails of it. I have a custom say function called "`GSay`", which takes two enums I declared called "`eGesture`" and "`eExpression`". It looks like this:

```AGS Script
import function GSay(this Character *, String sayThis, eExpression myExp=ex_none, eGesture myGest=eGestureNone);
```
and works like this:

```AGS Script
cJoe.GSay("Hello!",exSmile, eGestureWave);
```

It works just fine, but if I write a line a dialog that includes a comma, the autocomplete skips the "Expression" parameter and goes right to the "Gesture."

For example, the line below (which has no comma) behaves properly when autocompleting
![image](https://user-images.githubusercontent.com/2244442/148599069-9c08ee27-6006-4761-8fcb-0da1d1fbb110.png)

But this one (which includes a comma in the string) does not.
![image](https://user-images.githubusercontent.com/2244442/148599090-899874a1-b3bb-4171-8517-b818be576dbd.png)

**AGS Version**
3.5.1.14

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
[**SierraTest.zip**](https://github.com/adventuregamestudio/ags/files/7831022/SierraTest.zip)

Check the room1.asc file, from the project above, in the Editor to see the autocomplete bug manifest.

Originally reported here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=59644.0

**Comment by ivan-mogilko** [comment]
Ugh. I tried to investigate this step by step, and found several overlaying errors there.

* When editor shows function prototype hint (aka "calltip") it constructs the text in this function `ConstructFunctionCalltipText`, which calculates parameters by splitting the script by commas, disregarding any strings inside:
https://github.com/adventuregamestudio/ags/blob/0af788ef8a35580fde95eead30d48e7fbc30884e/Editor/AGS.Editor/Panes/ScintillaWrapper.cs#L1786

This means that it will show autocomplete and parameter hints if you type function name inside a comment too.

* When editor decides whether to display "calltip" for the next argument or not, after '(' or ',' symbols, it does not really check whether these symbols are inside string or comment:
https://github.com/adventuregamestudio/ags/blob/0af788ef8a35580fde95eead30d48e7fbc30884e/Editor/AGS.Editor/Panes/ScintillaWrapper.cs#L1068-L1076

**Comment by ericoporto** [comment]
Uhm... Seeing this function in the Scintilla wrapper... I have a slight feeling that this parsing of the thing being a function or not, or being in a string or comment is provided by the Scintilla lexxer we use and there's some way we could leverage it.

**Comment by ivan-mogilko** [comment]
> At minimum we can really get the style number in the position.

Yes, that's one good idea. I am currently trying both manual parsing and getting style to see which will work well. Although, getting styles would likely slow things down somewhat (but this may only be seen in practical tests).

There's some problem with the `InsideStringOrComment` function too, it does not reliably tell whether we are inside a string or not, for example if you type this: 
```player.Say("some text",```
for some reason it returns false after the comma, but if you add a whitespace
```player.Say("some text" ,```
then it works.
However, trying to fix it by taking one position step back less makes it stop working in another case. So, there's something to investigate too.
