### ISSUE TITLE
Make AGS Editor Sprite View remember folder tree area size

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1484]
> I have an issue that barely qualifies as a nitpick, but rather a small annoyance that I wonder if anything could be done about. I've been organizing all my sprites into folders and subfolders. This means I have to increase the window size to accommodate the expanded folder trees in the "select a sprite to use" window. Normally that's no big deal, but the window size resets to the original (too small) size every time I want to select a sprite. Is there any way the size of this window can be "saved" so I don't need to do that every time? See the image below to see what I mean.

![image](https://user-images.githubusercontent.com/2244442/148608509-30723e58-de2b-4a35-a77a-dbb0be4cd72f.png)

Originally from here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=59607.0

**Comment by ivan-mogilko** [comment]
This suggests that this size should be saved somewhere in memory, at least. But probably it also suggests that it should be saved between the sessions?

I guess there are two issues:
1. Investigate if this may be done uniformly for any similar windows (how many floating resiable windows to we have in the Editor though? maybe not a lot); like have some kind of a gui manager that saves this kind of information in memory.
2. investigate how to save this. This is not a project data, so should be part of either app settings, or "layout". The docking panels layout is currently read from a file (layout.xml) by the layout manager, but it's possible that it expects all file be its own. In the worst case there may be a separate file for saving additional windows.

**Comment by ericoporto** [comment]
This specific component is used in two different places, alone in it's own panel, and in this sprite selection window. I think it's own panel is usually open and kept open, but this sprite selection window is open and closed everytime a new sprite has to be selected.

**Comment by Max833** [comment]
> Sprite View remember folder tree area size

Not a big deal, but yeah... that would be handy indeed.

**Comment by ivan-mogilko** [comment]
My proposal on solution remains: have a dictionary of window settings, where keys are path-like strings.
"Color Themes" are a good example, in my opinion.
These path-keys may be formed using actual names of objects and properties (or beautified versions of them). For example:
```
"SpriteChooser/spriteSelector/splitWindow/SplitterDistance"
```
Using real property or class names could be meant to automate applying these settings through C# reflection.

As a first iteration this dictionary may be just stored in memory, in some global place, such as GUIController class, and reset every session. Then we might read/write it into its own file, similar to layout. This dictionary may be used to add more settings as necessary.

**Comment by ivan-mogilko** [comment]
An alternative to the flat list of keys could be a nested structure, basically dictionaries of objects, where some values may be strings and some are also dictionaries. In such case a child form would be passed a sub-dictionary, instead of a "parent key prefix".

**Comment by ivan-mogilko** [comment]
On another hand, looking at how ColorTheme works, it seems that the similar class may be used for configuring windows.
Maybe even some code could be picked out to a shared parent class.
ColorTheme is more or less a helper wrapper over a loaded json, which already represents a dictionary with multiple object types inside. I do not see this in ColorTheme's use, but nested parts of json likely may be returned in another wrapper instance, making it possible to use "relative keys" for child controls.

**Comment by ericoporto** [comment]
Uhm, the idea of this file that has these things serialized is to be stored in AppData in the same directory the Editor Preferences are currently stored but in a different file? Thinking about this file, when it should be written to, like right before the Editor closes (is it possible to?)?

I am trying to figure why you are suggesting a dictionary, is the idea to keep the config information (like keys and such) in the code of the pane instead of having a central settings file that has to be kept in sync with the rest?

**Comment by ivan-mogilko** [comment]
I'm suggesting a dictionary simply so that such config may be easily extended for other properties and or windows.

The idea is to have a single global dictionary of window settings somewhere in GUIController, where any window can access it and read its configuration on form load, then save back on form close.

The dictionary itself may be written to the file whenever is convenient, but at least on editor shutdown.
The location of the file depends on whether this configuration is meant for all versions of Editor, or one per-version. In the first case it may be saved along with Layout.xml, in the latter - near editor preference file.

**Comment by ericoporto** [comment]
> The location of the file depends on whether this configuration is meant for all versions of Editor, or one per-version.

Uhm, is it possible to have one per version but have it load the previous version if the current one is empty? A single one is maybe fine but maybe it isn't for people that are working with multiple versions of ags? Not sure.

I suggest to add things to this list as needed because probably there isn't a lot that has to be remembered. There also needs to be some way to delete this file to force a reset if some value there is very wrong or alternatively to use a range limit per property (a ceil and floor).

**Comment by ivan-mogilko** [comment]
I would begin with a dictionary in memory, as for the reported problem it will be enough to keep positions assigned at runtime, and restoring them after editor's relaunch seems more like an extra convenience (unlike editor preferences).

**Comment by ivan-mogilko** [comment]
This is not fully correct, but works as a first experiment:
https://github.com/ivan-mogilko/ags-refactoring/commit/40c239a69824de5e510e591775548cbac5f3e9e6
