### ISSUE TITLE
3.6.0: sending close command to the minimized game window does not close it until it's restored

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1502]
**Describe the bug**
If you minimize the game window, and then send a close command to it, using either method your OS provides: e.g. from the task bar's context menu, or task manager (*not* killing the process, but doing a regular app shutdown), the game does not close immediately. Instead it stays until you restore the focus back to its window, in which case it will close momentarily.

**NOTE:** this is a very low priority issue.

**AGS Version**
3.6.0, but I found it also happened in the earlier versions.

**Expected behavior**
The game should close normally.

**Comment by ericoporto** [comment]
I can't reproduce this on Windows 10.

**Comment by ivan-mogilko** [comment]
Hm, I cannot reproduce this on Windows 7 now. Either this got fixed somehow, or depends on certain game state. I will try to test more.

**Comment by ivan-mogilko** [comment]
This I noticed: this happens only when built in release configuration, and also for some strange reason does not happen with running a test from within the AGS Editor.

**Comment by ivan-mogilko** [comment]
Fixed by 12354d791e7ad2c358c3d99e4678fd4cda6bb75e
