### ISSUE TITLE
3.6.0: AudioChannel.Speed has no effect

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1503]
In 3.6.0 setting playback speed in script (using AudioChannel.Speed property) has no effect whatsoever.

The script channel's speed value is being set correctly, which in turn sets OpenAL's source AL_PITCH param.
But apparent problem is that mojoAL is missing pitch implementation completely. It has it applied to a data structure, but I found no code that would use this value.

**Comment by ericoporto** [comment]
Probably related issue there is https://github.com/icculus/mojoAL/issues/2

**Comment by ivan-mogilko** [comment]
For the future reference, mentioned in that issue, people in another project added their own pitch impl to their copy of mojoal:
https://github.com/supertuxkart/stk-code/commit/33459e852c354a12bac2b082c643572a77d1eb34

**Comment by ivan-mogilko** [comment]
On the other hand, it might be that OpenAL's "pitch" is not a direct equivalent to the playback speed.
In this, and any case, we may also implement resampling in the engine code, and pass altered sound data into mojoal.

**Comment by ericoporto** [comment]
MojoAL now has a pitch implementation. :)

**Comment by ivan-mogilko** [comment]
Aha. Commit for the reference: https://github.com/icculus/mojoAL/commit/47b22d002ae4d02d75817c392e9777b137f74261

**Comment by ivan-mogilko** [comment]
So, I tried it out, and mojoAL's Pitch is not what we need for Speed, it's a separate kind feature. As mentioned in the commit description, setting pitch only adjusts the sound samples, but it does not change the sound duration.

When reading [OpenAL specification](https://www.openal.org/documentation/openal-1.1-specification.pdf) though, here what it states, in a paragraph for AL_SEC_OFFSET:
> This value is based on byte position, so a pitch-shifted source will have an exaggerated
playback speed. For example, you can be 0.500 seconds into a buffer having taken only
0.250 seconds to get there if the pitch is set to 2.0. 

Unfortunately, the paragraph for AL_PITCH itself does not mention this, so one might miss and misunderstand this.

**Comment by ivan-mogilko** [comment]
So, as mentioned by @ericoporto , it's possible to trigger resampling by passing different frequency into the `alBufferData` call.
This works, although there is a remaining issue of reporting current position, and maybe something else.

**Comment by ivan-mogilko** [comment]
I made an experiment with resampler, which changes frequency before passing to OpenAl. So OpenAl thinks that the frequency is same, and sound ends up playing slower and faster; result matches the one of 3.5.1 from what I mat tell.
https://github.com/ivan-mogilko/ags-refactoring/commit/40af1c28005dc7ff0a6f0cacee6efa75f49f27c7

There are couple of issues with this, first the resampling is done per chunk, so there may be lags in speed change. Also position calculation is based on what openal returns, and so far not precise.
