### ISSUE TITLE
`File.ReadRawLine()` fails with `é` character

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1524]
**Describe the bug**
Originally reported by Baguettator in [the forums here](https://www.adventuregamestudio.co.uk/forums/index.php?topic=58976.msg636643210#msg636643210). ReadRawLineBack is not working with characters with accents in UTF-8 files.

**AGS Version**
Confirmed in 3.6.1.13 and current master.

**Game**
[TestReadLine.zip](https://github.com/adventuregamestudio/ags/files/7990718/TestReadLine.zip)

**To Reproduce**
1. create a file `my.txt` with the following string:
```
0;NomVéhicCréé0;null;null;null;0;25;25;25;25;55;35;10;10;90;10;null;0;null;0;null;0;0;
```

2. Now read it using ReadRawLine.

```AGS Script
File * F = File.Open("my.txt",eFileRead);
String st = F.ReadRawLineBack();
Display(st);
F.Close();
```

3. Resulting string st will be displayed as: `0;NomV`

**Expected behavior**
The full original text file is expected to be read.

**Screenshots**
I also tried to add the following code:
```Cpp
 if(in->EOS()) // EOL
 {
   buffer[i] = 0;
   return true;
}
```

just before ReadByte here (and removing `c < 0` comparison):
https://github.com/adventuregamestudio/ags/blob/c4f9644b38c0fbbfbbf98d6e9a28f0b309c2be04/Engine/ac/file.cpp#L114-L119

I was able to get the full string but when displaying it looks like this:
![image](https://user-images.githubusercontent.com/2244442/152256114-65527155-19cf-4e10-9965-c0a196e7d663.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
To clarify, the text file is saved as UTF-8?

What is the engine mode, ascii or unicode - enabled with the translation file option?

**Comment by ivan-mogilko** [comment]
Regarding the code:
```char c = in->ReadByte();``` 
is definitely a mistake, it should be
```int c = in->ReadByte();``` 
because ReadByte returns negative only in case of EOS, and character itself may take values from 0 to 255 (as unsigned char).

**Comment by ivan-mogilko** [comment]
Thank you for this report. I pushed a fix: 643e55f2b2b8237f27dc75e724bc87fa12339d7e
this should ensure that whole line is read.

But, as mentioned above, displaying a string from the utf-8 line correctly is only possible if the engine is switched to unicode mode. At the moment this is only possible to do with an option in translation file. We may discuss any additional methods separately, but currently you will only see original text if you create a TRS with `//#Encoding=utf-8` , provide proper unicode font and select this as an active translation.

**Comment by ericoporto** [comment]
Hey, this appears to be fixed. Can this be closed or do you want to track something else through here? (Like some toggle to turn utf8 mode on or similar)

**Comment by ivan-mogilko** [comment]
Right, this may be closed.

> Like some toggle to turn utf8 mode on or similar

I've been thinking for a moment, but then decided to not rush this and opened #1527 instead.
