### ISSUE TITLE
Editor: cannot order an item or folder among other folders in Project Tree

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1526]
**Describe the bug**
If you have subfolders in any list inside the Project Tree, you cannot drag the item in between or above these folders.
As a result:
1) all items outside of subfolders will always remain at the bottom of the list;
2) you cannot change folder's order.

This is not a very critical problem, but is a quite annoying inconvenience.

The root of the problem, it seems, is that item dragging operation expects the dragged item to be dropped over another _item_ in order to place former _above_ the latter. But if you drag something on top of a folder's name - it works as placing an item _inside_ that folder.

The solution therefore is likely to correctly handle dropping _in between_ the items. Usually in applications this is done by displaying a drop position as a line between two items.

**AGS Version**
Starting from 3.2.2 and up, 3.5.1, 3.6.0.

**To Reproduce**
1. Start the Editor and open any game.
2. In Scripts, for example, create two folders (F1,F2) and two scripts (S1,S2).
3. Try to position F2 above F1. Observe the failure.
4. Try to position script S1 in between two folders. Observe the failure.
5. Try to position script S1 above all folders. Observe the failure.

**Expected behavior**
It should be possible to drag and position items and folders between any items or folders and above them.

**Comment by ericoporto** [comment]
Found a way to detect if it's upwards or downwards in an item, in the clause below, it's possible to print it in the console as below

https://github.com/adventuregamestudio/ags/blob/be02cddec6b62f7ea1ad335370126d8328389568/Editor/AGS.Editor/GUI/ProjectTree.cs#L520-L521

```C#
int h = target.TreeNode.Bounds.Height;
int node_y = target.TreeNode.Bounds.Y;
int cur_y = locationInControl.Y;
if (cur_y > node_y  && cur_y < node_y + h / 4)
{
    System.Console.WriteLine("top of node");
}
if (cur_y > node_y + 3 * h / 4 && cur_y < node_y + h)
{
    System.Console.WriteLine("bottom of node");
}
```

**Comment by ericoporto** [comment]
OK, not very good yet but manage to make a thing.

https://github.com/adventuregamestudio/ags/assets/2244442/eeb59234-cb39-461a-920d-12bba50dfeda

I created a new control that draws this line and then just put it on the same panel and on top of everything and I hide it and resize it appropriately. I will play a bit more to make it show and hide a little better and try some graphics styles.

**Comment by ericoporto** [comment]
OK, it seems dragging folders before or after other folders requires writing your own things in BaseComponentWithFolders but it seems alright.
Same case to allow dragging items after other items.

The problem is I have zero idea how to order items anywhere else other than the after folders there? There is an Items collection for the items, and a SubFolders collection for the Folders. So doing something that allows dragging a "naked" item among the folders requires A LOT of changes, at least afaict.
