### ISSUE TITLE
Task: Write Editor AutoComplete Tests

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1543]
There are some small issues with the autocomplete. Once Tests are in place though, autocomplete logic should be easier to modify and verify correctness.

In ags4, there's a Test project in the AgsEditor solution. An autocomplete test file would probably be an `AutoCompleteTests.cs` file with a content like:

```C#
using AGS.Types;
using NUnit.Framework;

namespace AGS.Editor
{
    [TestFixture]
    public class AutoCompleteTests
    {
        private static Script CachedAutoCompletedScriptFromCode(string scriptCode)
        {
            Script script = new Script("_test", scriptCode, false);
            AutoComplete.ConstructCache(script);
            return script;
        }

        [SetUp]
        public void SetUp()
        {
        }

        [Test]
        public void CheckAutoCompleteVariables()
        {
            string scriptCode = $@"
int a;
";
            Script scriptToTest = CachedAutoCompletedScriptFromCode(scriptCode);

            Assert.That(scriptToTest.AutoCompleteData.Variables.Count, Is.EqualTo(1));            
        }
    }
}
```

The challenge mostly lies that [`ScriptAutoCompleteData`](https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Types/EditorFeatures/AutoComplete/ScriptAutoCompleteData.cs) contains lists of complex types, so whoever is writing the tests need to test if the generated data contains any element with certain specific attributes, instead of a more direct logic of `element in list`.

There's probably some magic way with LINQ I am not seeing yet that makes writing these tests easy though... 

Also probably ags4 tests in autocomplete which yield ags4 fixes in autocomplete, may have such fixes backported, using git.

**Comment by persn** [comment]
> There's probably some magic way with LINQ I am not seeing yet that makes writing these tests easy though...

Do you really need that? Maybe I'm not understanding but it seems to me that you could write a test like this

```csharp
[Test]
public ScriptShouldHaveStaticVariableFooFactory()
{
            string scriptCode = $@"
static int fooFactory;
";
    Script scriptToTest = CachedAutoCompletedScriptFromCode(scriptCode);
    ScriptVariable variable = scriptToTest.AutoCompleteData.FindVariable("fooFactory");

    Assert.That(variable.VariableName, Is.EqualTo("fooFactory"))
    Assert.That(variable.IsStatic, IsTrue);
}
```

Using LINQ it would be something like this though

```csharp
[Test]
public ScriptShouldHaveStaticVariableFooFactory()
{
            string scriptCode = $@"
static int fooFactory;
";
    Script scriptToTest = CachedAutoCompletedScriptFromCode(scriptCode);
    ScriptVariable variable = scriptToTest.AutoCompleteData.Variables.FirstOrDefault(v => v.VariableName == "fooFactory");
    
    Assert.That(variable), Is.Not.Null);
    Assert.That(scriptToTest.AutCompleteData.Variables.Any(v => v.IsStatic), Is.True);
}
```

But I'm probably misunderstanding what the complexity is. If someone gave an example of a test (ideally with code) that could benefit from being LINQified I could offer a suggestion

**Comment by ericoporto** [comment]
I just thought it was really cumbersome to write the tests and I could not figure a quick approach that I could use as a cookie cutter way of doing things there. When I wrote the preprocessor tests it was easy because it was text in and text out, so very easy to grasp what was the correct output. I just mentioned LINQ thinking there was maybe a way to make it shorter/easier - it just usually yields shorter readable code.
