### ISSUE TITLE
Unicode support: in script API String class should work with unicode chars

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1550]
As #1297 was generally complete, there's still an issue of String class API using 8-bit `char` type to return and append text characters.

The proposal is to adjust related functions and properties to work with `int` based type instead. This may be simply `int` for now, or a new type declared for "text character" as opposed to `char`=byte.

In AGS script `char` and `int` may be assigned to each other without explicit conversion (unlike int-float), therefore the existing scripts will continue to work.

The related members are:

- String.Chars[ ] (indexed attribute)
- String.AppendChar
- String.ReplaceCharAt

On a separate note, there's a question of String.Format's `%c` specifier. In C/C++ this means strictly 1byte-char, so this will work only for character codes <256 now. Need to figure out whether to add another one for printing unicode chars (int), or allow to use same specifier for unicode too. Technically, the script vm allows the latter, as `char`, `short` and `int` all are represented as 32-bit ints when passed as function arguments in ags script vm.

**Comment by AlanDrake** [comment]
We'll also need to add String.Bytes[]/AppendByte/etc variants, so the ability to manipulate raw data is not lost.
Though, won't there be annoyances with backward compat?

**Comment by AlanDrake** [comment]
For example, evil tricks like manually encoding custom data on savegame descriptions.
What about File.ReadRawChar() and File.WriteRawChar()? Would they handle characters or bytes?

**Comment by ivan-mogilko** [comment]
> manually encoding custom data on savegame descriptions.

But you likely don't need "bytes" for that, you can use regular characters.

> What about File.ReadRawChar() and File.WriteRawChar()? Would they handle characters or bytes?

I don't know, probably bytes, because otherwise there will be no way to read byte-by-byte. Perhaps there should be another function for reading or writing full characters. Or maybe reading/writing a string of given length, thus one will be able to save string of length 1 if they need 1 char.

In general, I think i disagree with letting users to access internal String contents as bytes. That breaks the idea of String as a sequence of characters, and also locks String to particular format implementation. AGS script's String is not a C-string, not a raw memory buffer, it's more like a C# String. If you look into C# their String does not give free access to its bytes; it only allows to retrieve bytes as array, or set new string from byte array.

**Comment by ivan-mogilko** [comment]
Regarding File.ReadRawChar() and File.WriteRawChar(), there's definitely is a potential problem, as now people likely use these also to form strings (using String.AppendChar which accepts 1 byte now). In theory this may even allow to read UTF-8 text this way. If AppendChar is changed to "utf-8 character" this will no longer work.

**Comment by rofl0r** [comment]
it's already in the names: AppendChar has "char" in it, which is very well defined to be 8bit.
and a C string is typically char* -> pointer to char, whereas a C++ string is the same encapsulated into a class with some metadata. it's also clear that %c works on a char, not a multibyte entity or a widechar.
rather than changing this behaviour, which will open a huge can of worms, you should consider adding instead some methods that work on utf8 multibyte encoding, for example "getnextcodepoint", iteratecodepoints, appendmultibyte, etc. this is also what other implementations do.

**Comment by ivan-mogilko** [comment]
I already answered to this before (twice). **AGS String is not a C-string, neither C++ string.** It's not a buffer of bytes.

**Comment by ericoporto** [comment]
Let's just follow C# implementation for String, Char is a character, so it's an int. It's how we are using in the Editor C# code already.

**Comment by ivan-mogilko** [comment]
Speaking of using a String to store raw values; that's not a common case, as normally people likely format values into string and parse them back. But, as String type does not expose pointer to its buffer, everything goes through AppendChar / Chars[] property, which means there's a chance that storing integers in byte range might still work. I'm going to test this out for the record.

**Comment by ivan-mogilko** [comment]
Also, a note regarding storing raw bytes. AGS script currently has `char` array and old `string` object for that. Both may be used to store strings and also work if passed into functions as `const string` parameter, or converted to String.
Old `string` has a capacity limit of 200, but `char` array may be any size. Dynamic `char` array is also supported, although I don't remember if script syntax allows to pass it as `const string` (maybe not).
In general, of course, AGS script would benefit from a proper resizable byte array type.

**Comment by rofl0r** [comment]
> Which "huge can of worms" are you speaking of, can you elaborate on this, because "can of worms" is too abstract?

the can of worms is the issues that will arise from redefining the meaning of char from 8bit to 32bit. i'm quite sure this will break lots of old games and you will spend the next 2 months after introducing this change fixing cornercases nobody thought off yet.

> ... Python script works, but if you look into their [str (string) type](https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str) - these are treated as a sequence of unicode chars,

python is the language that famously botched unicode completely, that's why they needed to introduce python3 to make breaking changes. python3 doesn't get it completely right either, so one shouldnt look at it as an example. if they had used utf8 from the start and just provided a means to iterate over unicode chars AND bytes, the disaster could've been avoided completely.

> This makes the following comparison myString.Char[0] == '🙂' possible.

your toy example is also possible by using a method as i proposed.

`myString.GetWideChar(0) == '🙂'`

or `myString.ConvertToWideChar()[0]...`

**Comment by ivan-mogilko** [comment]
> the can of worms is the issues that will arise from redefining the meaning of char from 8bit to 32bit. i'm quite sure this will break lots of old games and you will spend the next 2 months after introducing this change fixing cornercases nobody thought off yet.

I never said changing meaning of `char`. I meant changing few functions from working with `char` to `int`.

**Comment by messengerbag** [comment]
Well, in principle I'm inclined to agree with rofl0r—I'm fearful of the idea of suddenly changing the behavior of a basic API. In particular, how will this work if the project is set to ANSI mode? Will that still use the old API? Seems quite confusing.

However, if these existing APIs are kept byte-wise, then related APIs like `String.Length` may also need to be kept that way, because a lot of logic probably depends on `sizeof(String.Chars[]) == String.Length`. Which in turn creates problems with methods like `String.Substring()` and `Truncate()`. I know I have written code with statements like `myString.Truncate(myString.Length-1)`.

In other words, if we keep the APIs listed in the first post byte-wise, then we might have to keep almost *all* the existing String APIs the same, and introduce new Unicode-oriented duplicates of all these methods and properties. Or perhaps the best solution would be to introduce a whole new UnicodeString type. In either case, most existing String scripts would have to be updated in order to work with Unicode.

So what I would propose is to update the APIs as Ivan suggests, but still provide the former APIs and behaviors under new names, e.g. `String.Bytes[]`, `String.ByteLength`, `String.AppendByte(char extraByte)` and `String.ReplaceByteAt(int byteIndex, char newByte)`.

**Comment by messengerbag** [comment]
> This makes the following comparison `myString.Char[0] == '🙂'` possible.

Does this imply that `char` literals will also now be `int`s? (Or is there not actually any difference in AGS between defining something as a char or an int?)

**Comment by ivan-mogilko** [comment]
To clarify, majority of String's methods were already adjusted to work with unicode char indexes, rather than byte indexes (#1321). That should not affect older games, as obviously they all continue to work in ascii mode.

String.ReplaceChar already has "index" as a text index also, but only accepts 1-byte chars.

String.Chars[] is currently not working correctly in unicode mode at all, and return byte values using a byte index.

> But does this imply that char literals will also now be ints

That's the important question, personally i haven't tried this properly yet.

**Comment by ivan-mogilko** [comment]
> I'm fearful of the idea of suddenly changing the behavior of a basic API. In particular, how will this work if the project is set to ANSI mode? Will that still use the old API? Seems quite confusing.

Also to clarify: the initial idea was to use same API, as char and int may convert to each other, and in ANSI (ascii) mode the conversion supposedly will be lossless both ways.

If that proves to be problematic, then we may indeed link byte-based implementation at runtime for ANSI mode and/or old games.

**Comment by ivan-mogilko** [comment]
@messengerbag Alright, I made a small research, and found out that the character literal is treated as a regular numeric literal in ags script. That is - converted to a 32-bit number. Small change is required in compiler to make it process multibyte characters in quotes, but after that it may be safely assigned to an `int` and retains its decimal value.

Unfortunately at the moment there's no way to display such character directly, only to test the decimal value.

**Comment by ericoporto** [comment]
> Unfortunately at the moment there's no way to display utf-8 character directly from this variable, only to test the decimal value.

Indeed. I tried something but it did not work...
![image](https://user-images.githubusercontent.com/2244442/156864852-fc72fc38-2feb-4694-a1bb-ed40ed7394d4.png)

**Comment by ivan-mogilko** [comment]
@ericoporto there's a function in the library that you posted a while ago:
https://github.com/sheredom/utf8.h/blob/master/utf8.h#L343

AGS script:
```
String ToUTF8Char(int chr)
{
	char c[5];
  if (0 == (/*0xffffff80*/-128 & chr)) {
    /* 1-byte/7-bit ascii
     * (0b0xxxxxxx) */
    c[0] = chr & 255/*0xff*/;
  } else if (0 == (/*0xfffff800*/-2048 & chr)) {
    /* 2-byte/11-bit utf8 code point
     * (0b110xxxxx 0b10xxxxxx) */
    c[0] = (/*0xc0*/192 | (chr >> 6) & /*0xff*/255);
    c[1] = (/*0x80*/128 | (chr & /*0x3f*/63) & /*0xff*/255);
  } else if (0 == (/*0xffff0000*/-65536 & chr)) {
    /* 3-byte/16-bit utf8 code point
     * (0b1110xxxx 0b10xxxxxx 0b10xxxxxx) */
    c[0] = (/*0xe0*/224 | (chr >> 12) & /*0xff*/255);
    c[1] = (/*0x80*/128 | ((chr >> 6) & /*0x3f*/63) & /*0xff*/255);
    c[2] = (/*0x80*/128 | (chr & /*0x3f*/63) & /*0xff*/255);
  } else { /* if (0 == ((int)0xffe00000 & chr)) { */
    /* 4-byte/21-bit utf8 code point
     * (0b11110xxx 0b10xxxxxx 0b10xxxxxx 0b10xxxxxx) */
    c[0] = (/*0xf0*/240 | (chr >> 18) & /*0xff*/255);
    c[1] = (/*0x80*/128 | ((chr >> 12) & /*0x3f*/63) & /*0xff*/255);
    c[2] = (/*0x80*/128 | ((chr >> 6) & /*0x3f*/63) & /*0xff*/255);
    c[3] = (/*0x80*/128 | (chr & /*0x3f*/63) & /*0xff*/255);
  }
	return String.Format("%s", c);
}
```

**Comment by rofl0r** [comment]
here's patch for hex support: https://github.com/rofl0r/ascc/commit/0e953848fa7cc0fd7baa8d733db5e516cbd432ee

do git format-patch -1 in my repo, change path in the diff, then git am in this repo.

i can make a patch later today

**Comment by ivan-mogilko** [comment]
> here's patch for hex support: [rofl0r/ascc@0e95384](https://github.com/rofl0r/ascc/commit/0e953848fa7cc0fd7baa8d733db5e516cbd432ee)

Sorry, i did not notice this in time and already prepared a patch.

I did this, a little differently. I think using strtol to convert hex fails at values above 0x7fffffff, at least for 32-bit Win, so I had to use stroul instead. Also, passed the hex as-is until `accept_literal_or_constant_value` function, so that it would report parse errors uniformly for decimal and hex.

**Comment by ericoporto** [comment]
there is some code here that could be modified in case we think `%c` should be modified to be `%lc` or whatever (for formatting string options of a character)
https://github.com/adventuregamestudio/ags/blob/master/Engine/script/script_api.cpp#L69-L243

**Comment by ivan-mogilko** [comment]
Created an experimental branch, with a purpose to outline possible changes and test for problems/regressions:
https://github.com/ivan-mogilko/ags-refactoring/tree/experiment--utf8chars

Using following script for a test:
```
char c = 'a';
int uc = '步';

String s = "unicode test: ";
s = s.AppendChar(uc);
s = s.Append(" x <--");
s = s.ReplaceCharAt(16, uc);
Display("%s \n %c", s, s.Chars[14]);

Display("ascii format: %c\nunicode format: %c", 'a', '步');
```

**Comment by ericoporto** [comment]
Hey, in this line here: 
https://github.com/ivan-mogilko/ags-refactoring/commit/7e0c4a9586ae20167ddbfb292e86176cb7e5bc70#diff-5ddaa1fdd1f81bba191c2073cbbfc30c3be5e13b6e79a0022b3feb59e6849e18R201

Instead of `usetc(c, chr);` you can use `Utf8::SetChar(chr, c, 5);` and then you don't need allegro there! :)

**Comment by ivan-mogilko** [comment]
> Hey, in this line here: [ivan-mogilko@7e0c4a9#diff-5ddaa1fdd1f81bba191c2073cbbfc30c3be5e13b6e79a0022b3feb59e6849e18R201](https://github.com/ivan-mogilko/ags-refactoring/commit/7e0c4a9586ae20167ddbfb292e86176cb7e5bc70#diff-5ddaa1fdd1f81bba191c2073cbbfc30c3be5e13b6e79a0022b3feb59e6849e18R201)
> 
> Instead of `usetc(c, chr);` you can use `Utf8::SetChar(chr, c, 5);` and then you don't need allegro there! :)

The engine currently works in 2 modes: ascii/ansi and utf-8. `usetc` and similar functions are pointers that are switched to different implementations depending on the mode set. That is why I'm using allegro there. More information about this may be found in (#1321).

By the way, this made me realize, that my compiler change for char literal is also incorrect, as it will break extended ansi, so I'll have to use something similar.

In any case, moving utf8 functions out of allegro4 may be a way to go, as allegro4 unfortunately has too many cross-dependencies between its modules.

**Comment by ericoporto** [comment]
> By the way, this made me realize, that my compiler change for char literal is also incorrect, as it will break extended ansi in ansi mode, so I'll have to use something similar.

This means an additional compiler flag for utf8 or ansi, since the compiler can now be run through command line too.

> usetc and similar functions are pointers that are switched to different implementations depending on the mode set. That is why I'm using allegro there.

This makes the engine tests also need allegro to be built along. Also wherever else such mechanism is used.

> moving utf8 functions out of allegro4 may be a way to go, as allegro4 unfortunately has too many cross-dependencies between its modules.

I agree.

**Comment by ivan-mogilko** [comment]
Updated experimental branch, added compiler option SCOPT_UTF8.

**Comment by ericoporto** [comment]
> added compiler option SCOPT_UTF8

interesting, once this is in I can add it in the compiler frontend.

The windows test though will fail at build for the following error:

> script_api.cpp.obj : error LNK2001: unresolved external symbol `_usetc` [`Solutions\Tests.App\Engine.App.Test.vcxproj`]
