### ISSUE TITLE
Remove or properly support Non-threaded audio runtime option

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1566]
Currently AGS can only run with threaded audio. Alternatively, it can be built for non-threaded audio too - single thread build is a requirement for Emscripten port.

We can either

- remove the multithread audio flag from command line, OPTIONS.md and WinSetup 
- or reimplement some way to turn threaded audio off at runtime too

I think it's easier to just remove the config options but I also thought it was better to open an issue.

--- 

**context for emscripten**

- I already talked a bit on this in https://github.com/adventuregamestudio/ags/pull/1346 and also on the [`Emscripten/README.md`](https://github.com/adventuregamestudio/ags/tree/master/Emscripten#changes-from-other-ports)

Current pthread implementation in Emscripten comes with multiple requirements both on the browser but also on the server used to host the game:

> Browsers [that have implemented and enabled](https://webassembly.org/roadmap/) SharedArrayBuffer, are gating it behind Cross Origin Opener Policy (COOP) and Cross Origin Embedder Policy (COEP) headers. Pthreads code will not work in deployed environment unless these headers are correctly set.

see: https://emscripten.org/docs/porting/pthreads.html

**Comment by ivan-mogilko** [comment]
Resolved by #1573
