### ISSUE TITLE
Sliders are clipped incorrectly

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1581]
**Describe the bug**
Recently there has been a change that allows clipping GUI controls (#1495), but unfortunately sliders are a bit tricky regarding their sizes, and their handles are being clipped.

**AGS Version**
3.6.0.20, current master https://github.com/adventuregamestudio/ags/tree/ed971d2c5d289db6df31e2a2214771bcb162e5ca

**Game**
[SliderTest.zip](https://github.com/adventuregamestudio/ags/files/8308060/SliderTest.zip)

**To Reproduce**
1. Run the attached game and see the behavior of the sliders in the GUI that is opened
2. Close, now in general settings, visual, disable "GUI controls clip their contents"
3. Run again and noticed now the sliders are correctly presented (see screenshots below)

**Expected behavior**
Sliders should work even when clipping is turned on.

**Screenshots**
SliderTest sliders with clipping turned on
![image](https://user-images.githubusercontent.com/2244442/159095924-f29bdb5f-a288-4004-983e-16036f9ddf41.png)

SliderTest sliders with clipping turned off
![image](https://user-images.githubusercontent.com/2244442/159096029-0787a9af-89b9-419c-a55c-95ef6077f092.png)

**Desktop:**
 - OS: Windows
 - Version: 10

**Comment by ivan-mogilko** [comment]
Hmm, at first I thought it's only affecting handles, but apparently it also affects slider's body too.
Need to make research how their elements' sizes are calculated.
Probably this fix would require another "game version" logic switch.

**Comment by ericoporto** [comment]
so the Slider draw command uses a single Drawing Surface, this requires that the prepared sprite is made in this single drawing surface, and then the clipping must be on the resulting sprite. If it instead drawed in two surfaces, then the clipping would be irrelevant since the handle and the bar themselves have the correct measurement by definition.

In the way that is currently implemented, with a single drawing surface, the math for the bar and the handle needs to be adjusted so that they are contained in the determined rectangle defined by the slider size.
