### ISSUE TITLE
Custom dialog errors with DoRunScriptFuncCantBlock called with too many parameters

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1582]
**Describe the bug**
Keyboard input options with custom dialogues crashes the engine.
Reported on [forums here](https://www.adventuregamestudio.co.uk/forums/index.php?topic=58976.msg636644353#msg636644353).

**AGS Version**
AGS 3.6.0.20

**Game**
[DialogOptions.zip](https://github.com/adventuregamestudio/ags/files/8308436/DialogOptions.zip)

**To Reproduce**
Load the attached game
1. Talk with the other character
2. Once the dialog appears, try to select any option using down or up arrow on the keyboard
3. The game exits with the error "DoRunScriptFuncCantBlock called with too many parameters"

**Expected behavior**
The game should not error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
It looks like the function can only take 2 parameters here:
https://github.com/adventuregamestudio/ags/blob/59cec0c292f35404221d3f4268616921a3675e84/Engine/script/script.cpp#L335

But it takes 3 parameters here:
https://github.com/adventuregamestudio/ags/blob/59cec0c292f35404221d3f4268616921a3675e84/Engine/ac/dialog.cpp#L921

https://github.com/adventuregamestudio/ags/blob/59cec0c292f35404221d3f4268616921a3675e84/Engine/script/script.cpp#L77

So it's apparently the additional mod key in `dialog_options_key_press`.

This check was added a long time ago:

https://github.com/adventuregamestudio/ags/commit/c28274774f53bfcaa233f814c654b40ea0f4ff2a#diff-14acea2e7bc7373bc2394204ff216cac6b043f0ca339c2714b9c1bb2121a4232L356-R363

So a probable fix is just using a less or equal sign or removing the check entirely.

**Comment by ivan-mogilko** [comment]
Pushed a fix: f156586fa9d6b99249eaff54230179f784fdec09

**Comment by ericoporto** [comment]
Closing this since the commit fixed it.
