### ISSUE TITLE
Support Setting Width and Height of Overlays

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1585]
**Describe the problem**
Overlays got a readable Width and Height. That is great. But being able to actually set those values would enable actually manipulating a texture through AGS Script, which would allow a great amount of effects - plus you could distort things by making width different than height, which could be really fun!

**Suggested change**
Make Width and Height a writable property, at least in graphical overlays!

Use case: wanted to replace my scripted software renderer in [mana match](https://eri0o.itch.io/mana-match) to leverage the overlays.

**Comment by ivan-mogilko** [comment]
A question of design here is whether changing overlay's content resets width & height or not.

Overlays are not allowed to change graphic freely at the moment, but we may imagine that they are (by having e.g. Overlay.Graphic or SetGraphic) in some future. They are allowed to set text though (Overlay.SetText).

Curiously, there's no real distinction between "graphical" and "textual" overlays, such type does not exist. Both are graphical technically, as text is never saved as a field: instead a graphic is generated with text on it, and overlay contains that graphic. So it's not a type, but factory method.

**Comment by ericoporto** [comment]
If we look reaaally in the future, I kinda wish to at some point have some way to set a 4 point coordinate to do distortion in the texture. I also see overlays more like a moveable texture, if it gets a settable graphics property then this gets a performance hit to constantly read the bitmap sprite to a texture I imagine.

> A question of design here is whether changing overlay's content resets width & height or not.

Anyway, if we want to have the graphic being set, in my head this would reset the width and height. Also I have been thinking a SetSize(int w, int h) is better instead of setting each property in case there's something besides setting a value in the object property that happens when we do this in script.

An alternative method is to have a scaling property, the one can calculate the desired width and height and do that, but in this case the scaling I really would prefer if it: 
- accepts floats!
- have a different number for width and height (or even use a Vec2 object!)

**Comment by ivan-mogilko** [comment]
> I also see overlays more like a moveable texture, if it gets a settable graphics property then this gets a performance hit to constantly read the bitmap sprite to a texture I imagine.

Of course not, the engine does not update the texture unless the source bitmap has changed. This is how it works with objects and characters at the moment. In software mode it even caches transformed sprites.

> SetSize(int w, int h) is better instead of setting each property in case there's something besides setting a value in the object property that happens when we do this in script.

There's always a way to delay a more complex update. For example, for certain objects engine does not update their cached graphics and textures until the game update. Thus the accumulated changes to properties are only applied once per game frame (i personally did this to viewports and cameras).

**Comment by ericoporto** [comment]
Hum, I feel the textual overlay it's best that the width and height is always updated when the text changes. 

On the graphical I think if the person explicitly set the width and height it's expected it's maintained, but if not they probably expect the sprite width and height will be applied. 

I am tending to the design where the width and height gets reset to the sprite w/h whenever the sprite is reapplied to the Overlay.

**Comment by ivan-mogilko** [comment]
An experiment: https://github.com/ivan-mogilko/ags-refactoring/tree/360--overlaysize

**Comment by ericoporto** [comment]
I tested it and it works! (here's my test proj: https://github.com/ericoporto/mode7/tree/overlaysize ), curiously it ended up being faster than sprite drawing but not as faster as I hoped, probably due to the resolution I am working, perhaps a bigger resolution would manifest a more different performance. I built your branch here: https://cirrus-ci.com/task/5048759905157120

**Comment by ivan-mogilko** [comment]
> it ended up being faster than sprite drawing but curiously not as fast as I imagined, probably due to the resolution I am working, perhaps a bigger resolution would manifest a more different performance.

You may also try testing in the infinite fps mode:
* run with `--fps` arg
* in game press ctrl + e.

Note that this has to be merged with the recent commit e2f8b0f2357d2587016425ff6629ef37601d8e0f, which fixes these special key combinations.

**Comment by ericoporto** [comment]
ah, never mind, I actually found the issue, I had sorting done to make nicer ZOrder numbering, I scratched that and went with a pure FloatToInt from the distance to the camera and now I can handle like... Insane amounts of stuff.

**Comment by ivan-mogilko** [comment]
To keep a record, I got a internal program crash with the above game:

<pre>
---------------------------
Illegal exception
---------------------------
An exception 0xC0000005 occurred in ACWIN.EXE at EIP = 0x0040D35F; program pointer is +6, ACI version 3.6.0.22, gtags (0,64)

in "mode7.asc", line 559
from "room1.asc", line 254
</pre>

**Comment by ericoporto** [comment]
Hey, unfortunately I was toying way to much with the code above, but I pushed the code of the game here: https://github.com/ericoporto/roading/tree/overlay-render (but it's not exactly it!)

I think a good candidate for the crash may either the width/height be too big or equal or smaller than zero, I probably should be clamping to some limits in the code.

**Comment by ivan-mogilko** [comment]
> I think a good candidate for the crash may either the width/height be too big or equal or smaller than zero, I probably should be clamping to some limits in the code.

That's an access violation ( 0xC0000005), meaning there's program memory issue, not the scripting error.

**Comment by ivan-mogilko** [comment]
Another thing, one of the problems with overlays currently is that they make copies of bitmap. This makes sense for textual overlays, but is very inefficient for graphical ones. So when you create 100 overlays from same sprite - it will make 100 copies of it, and so on. With 3d renderer that is even unnecessary, as they only need a texture.
I think it's long overdue improving this.
On a side note, it's also may be a good idea to have a second cache for ready textures corresponding to certain sprite, that would seriously improve perfomance (both memory and speed) in case there are multiple objects sharing same pic.

**Comment by ericoporto** [comment]
If this cache has things unused not go immediately removed, I wonder if it could improve things for like an animation playing, where the second time it loops it all is picked from the cache.
