### ISSUE TITLE
Fade-out glitch in Blackwell Epiphany

### ISSUE THREAD

**Issue by eriktorbjorn** [adventuregamestudio/ags#159]
As far as I can tell, the recently released Blackwell Epiphany game works flawlessly in Linux with the master branch, except for one minor glitch:

(Minor spoiler warning, I guess.)

After Jocelyn has left Madeline behind, the screen fades down. Except the square where the gate used to be doesn't for some reason.

I've uploaded a saved game to http://www.update.uu.se/~d91tan/epiphany-fadeout-glitch.zip

Here is a screenshot:

![epiphany-fadeout-glitch](https://cloud.githubusercontent.com/assets/601765/3005874/223b3354-ddf8-11e3-9f2b-957fe684b001.jpg)

**Comment by ivan-mogilko** [comment]
When testing this with [3.5.0.16 beta release](https://github.com/adventuregamestudio/ags/releases/tag/v.3.5.0.16) this actually seem fixed, but I have strange crashes and errors when testing with the most recent commit in the branch, so will keep this open until I figure out what's going on...

**Comment by ivan-mogilko** [comment]
Actually, looks like this was fixed somewhere between 3.4.0 and 3.4.1. It can be still reproduced with 3.4.0 engine but goes away in 3.4.1. I wonder what that was...
