### ISSUE TITLE
New compiler: static variables inside a struct and doubt about pointer types in conditions

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1590]
## Static variable inside struct
@fernewelten I noticed a case with `static` where the compiler doesn't complain, but things don't work as one would expect:

```
struct MyStruct {
	static bool fake_static_bool;
}
```

Normally, only `static attribute` would be allowed. From what I tested, static (not attribute) variables inside structs  don't seem to be actually implemented, so it may be cause of undefined behaviors.

It wouldn't be bad to have actual static variables without all the attribute boilerplate, though.

## About pointer types

Previously it was possible to test pointer types directly like this
```
if (pointerType)
```
Without explicitly testing againt null, but now it throws the error `'if' condition: Cannot convert a pointer to 'int'`.
I don't know if this was intended, so I'm reporting it.
I personally don't mind either way, but sometimes it's nice to omit the `!= null`.

**Comment by fernewelten** [comment]
Hi @AlanDrake , sorry for the delay. My mother has died, and everything is in turmoil right now. I'll issue fixes pronto, I'm starting right now.

**Comment by AlanDrake** [comment]
I'm sorry to hear that, fernewelten. Take all the time you need, familiy should always come first.

**Comment by fernewelten** [comment]
Addressed in #1602 and #1603.

**Comment by ivan-mogilko** [comment]
@AlanDrake could you double check that the above PRs cover this issue?

**Comment by AlanDrake** [comment]
Looks good to me.
