### ISSUE TITLE
Pressing a key without modifiers doesn't invoke on_key_press

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1609]
**Describe the bug**
When pressing a key, without holding either Ctrl or Alt, no on_key_press event is invoked

**AGS Version**
Latest master from https://github.com/adventuregamestudio/ags/tree/e1745b6a613ce2f1b222bc4dca940d2d3b314a5a

**Game**
[OnKeyPressTest.zip](https://github.com/adventuregamestudio/ags/files/8457897/OnKeyPressTest.zip)

**To Reproduce**
1. Press any key without modifier and see only on_text_input event is invoked
2. Now press a key along with Ctrl or Alt

**Expected behavior**
on_text_input and on_key_press events should be invoked when a key is pressed.

**Screenshots**
From the game attached
![image](https://user-images.githubusercontent.com/2244442/162594612-51c0f714-8f32-4291-b3f1-882fa2cf0d12.png)
Both should probably indicate same keys...

**Desktop:**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
Should be fixed by ffb73a0a7488e16b26c969b7efb3ca035f7dcea4

**Comment by ericoporto** [comment]
Thanks!
