### ISSUE TITLE
QFG II Remake has broken menu colors and start menu in master.

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#1610]
**Describe the bug**
I was messing around trying to reproduce https://bugs.scummvm.org/ticket/12998 which i didn't manage, but I did immediately notice two things when i tested with standalone upstream current ags master. The parser choice menu and the inventory menu are corrupted.

**AGS Version**
```
$ ags --version
Adventure Game Studio v3.6 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2022 others
ACI version 3.6.0.22
```

**Game**
QFG II Remake at http://www.agdinteractive.com/games/qfg2/homepage/homepage.html

**To Reproduce**
1. Create a new character and you'll see the parser choice error and open the inventory and you'll see the other

**Expected behavior**
Normality.

**Screenshots**
![Screenshot from 2022-04-10 00-39-57](https://user-images.githubusercontent.com/757900/162595424-ccecbac7-28a4-4f7e-98d9-cf462836ce8a.png)
![Screenshot from 2022-04-10 00-40-58](https://user-images.githubusercontent.com/757900/162595428-07c23365-9482-49cb-bde0-e89b6849adcd.png)

**Desktop (please complete the following information):**
 - OS:  `Linux sleipnir 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
Scummvm is actually running this better and the bug i was hunting for mentioned in that bug report doesn't happen (in ags, scummvm) so that's weird.

edit: it happens on the retroarch core port using current scummvm code at https://github.com/diablodiab/libretro-scummvm-backend. ugh.

**Comment by i30817** [comment]
BTW, if you click on some (but only some) of the buttons that look normal on the dropdown top bar you'll see the broken green version in their 'pressed' state.

**Comment by ericoporto** [comment]
![image](https://user-images.githubusercontent.com/2244442/162595681-d80af31f-af58-49a6-8ad9-ce3691212fd8.png)
Just for reference, the screen @i30817 mentioned when running with the original .exe

**Comment by i30817** [comment]
About the other bug, i think it's a non-determistic thing and can happen in scummvm too and probably in ags too with the 'wrong' computer.

quoting my comment on the scummvm bug report:

> 
>  Yup, happens there for some reason. Although it happens 'once' (the main cursor doesn't appear to change - although if you move out of the bar it does - and the bar flashes once) and then if you click a second time it works 'correctly' (the main cursor changes even on top of the bar, the bar doesn't flash), then it repeats.
> 
> Note that in scummvm the bar actually disappears completely the first time. I think the 'problem' here is that the bar was supposed to disappear to show the icon, that is the top bar 'exposed' state is supposed to extend or shrink the hotspot. It extends when you touch the top of the screen and it should shrink when you click a icon, it just appears to register the mouse on a viable hotspot when it's shrinking and shows it again in the core while upstream has better timing.
> 
> It's kind of weird this is happens to me only on the libretro core - especially this version which is using upstream code instead of being thousands of commits behind.
> 
> I think this is non deterministic (i don't think the reporter is using the libretro core, it's just more easy to notice it there for me).

resuming i think inducing some kind of delay is enough to make what was supposed to be the removal of the hotspot still register the mouse there thus the 'flash' instead of the closure of the top bar when you click on a button.

**Comment by ivan-mogilko** [comment]
@i30817 please, open one issue per a bug or a group of related bugs, otherwise it's difficult to track these problems.

**Comment by i30817** [comment]
I don't, but i suspect it's just a question of timing since it (presumably) happened to someone using scummvm not the scummvm retroarch core but scummvm itself.

**Comment by ivan-mogilko** [comment]
I found which commit broke this, it's 0778031; reverting it makes these buttons look fine.
judging by the description, I've been trying to fix something else, but unfortunately do not mention a game or anything, only general issue. I'll need to investigate more.

**Comment by i30817** [comment]
I have a suspicion now that the problems are 'related'. I know it sounds farfetched, but the bug report on scummvm mentions the problem occurs 'only in the first 5 buttons of the top bar' which is what i experienced.

The corrupt buttons are divided right down the middle...

**Comment by ivan-mogilko** [comment]
I'm sorry, but i dont know what is the problem with topbar, I dont see anything wrong with it.

This visual problem is bitmaps not loaded correctly, it should not have any relation to mouse detection, or button behavior.

**Comment by i30817** [comment]
> I'm sorry, but i dont know what is the problem with topbar, I dont see anything wrong with it.
> 
> This visual problem is bitmap pixel data not loaded correctly, it should not have any relation to mouse detection, or button behavior. These buttons are "divided" basically because the pixel data lines are copied in a wrong way in memory.

Shrug. I suppose it's completely possible it's just a scummvm fork problem, since the libretro core is based on scummvm. Although from what i can see in the commits of scummvm, it's just cherry picking commits from here all the time, so it would be nice to track down which thing went wrong.

**Comment by ivan-mogilko** [comment]
I ended up reverting the older commit, pushed 36e7d53fc1da189e402d9089c580d15844c6d4b5.
Was not able to recall why i decided that the change is necessary; looking at this now the old version looks correct instead. Could be I had some confusion. Also release-3.5.1 branch has the old version of this code.

**Comment by i30817** [comment]
Fixed. BTW, there was another tell of this error in the hero's white shirt, which showed some blue artifacts (noticeable if you click on the topbar white icons to standup).
