### ISSUE TITLE
One More Fathom starts with a pink background in AGS from current master

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1612]
**Describe the bug**
Right when the game boots up, the background is pink, but it should be black

**AGS Version**
Built from master, commit https://github.com/adventuregamestudio/ags/tree/f3cd443545fc69af991713650c45ea799b624a64

**Game**
[One More Fathom](https://www.whamgames.com/downloads/OneMoreFathom.zip)

**To Reproduce**
Run One More Fathom using AGS's acwin.exe built from master branch, https://github.com/adventuregamestudio/ags/commit/f3cd443545fc69af991713650c45ea799b624a64.

**Expected behavior**
Background should be black instead of pink

**Screenshots**
This is One More Fathom when running with the build from master
![image](https://user-images.githubusercontent.com/2244442/162836205-96f979f4-bb4f-4203-8f0c-4716ab9e79a7.png)

This is running the original executable
![image](https://user-images.githubusercontent.com/2244442/162836259-46e4810f-00e3-41a6-9d15-a9548d771aa4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
So, this is probably what I was trying to fix with 077803120808a9b18a888bb24f7124844f21fa00 apparently, and now it's reverted with 36e7d53fc1da189e402d9089c580d15844c6d4b5.
Now I get to look into this more carefully.

**Comment by ivan-mogilko** [comment]
Pushed a fix b9804f5ac307e390de205b20f7c803dcf6812df2, hopefully this one is correct.

**Comment by ericoporto** [comment]
This fixes for me! Feel free to close this!

<details>we slowly understand how <a href="https://github.com/adventuregamestudio/ags/blob/master/Engine/gfx/gfx_util.cpp#L122-L127">this</a> happens... 🤣</details>
