### ISSUE TITLE
[AGS 4.0] Object image does not update until room is in focus

### ISSUE THREAD

**Issue by tarnos12** [adventuregamestudio/ags#1615]
**Describe the bug**
Changing object image in a room editor doesn't update the image until room is focused again(by clicking inside a room OR switching between 2 tabs)

**AGS Version**
4.0

**To Reproduce**
1. Create an object
2. Change Image
3. Click inside a room window so it's focused again(which will force the image to update)

**Expected behavior**
Image should update the moment we finish typing sprite ID(usually pressing Enter or clicking away from the Image text box) or choosing an image from a list(like it does in 3.5.1(Unless it doesn't?))

**Video to demonstrate the issue**
https://i.gyazo.com/3a8074da6920ab7424401125c66acbd4.mp4

**Desktop (please complete the following information):**
 - Windows 10

**Comment by ivan-mogilko** [comment]
For me it works correctly in 3.5.1, but not in most recent 3.6.0.

**Comment by ivan-mogilko** [comment]
It works alright in 3.5.1, but not in 3.6.0, so had been broken somewhere in between.

**Comment by ivan-mogilko** [comment]
So, for the reference, this was broken by this commit: 96accb49be63872035399d7880c52e2c529c9843

For some reason changing document title caused whole panel to refresh itself; this sounded too much, and also caused some errors in the updated script editor, so I removed that.

Perhaps that, and something else, lead to the lack of update in case of a property change. I guess there are too many obscure connections between editor parts that were added over the years, and these are now too twisted to understand...
