### ISSUE TITLE
AGS 4: proposal to remove software renderer

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1616]
I have a suggestion to remove software renderer from ags4 branch.

Software render is a source of duplicate work, and as we add more graphical effects into ags4, it may be becoming a burden. It requires extra bitmap handling and optimization, and has somewhat different order of operations. It's not uncommon to implement a new graphical feature in a few days, and then spend another week or two tuning software draw. It complicates the code, adding switches and extra functions. As not many people use it today, the testing is also limited.
In other words, extra effort is put in maintaining a feature that may not even be used.

I guess there's a way to improve this situation by factoring out all the drawing code in a separate module, and just feed it with sprites and parameters, so to keep the main code clear; but this will take time. + This may require a larger code revamp first anyway; changing the general approach to how the sprites from all objects are gathered and prepared.

At the moment hardware accelerated (aka 3D) renderers work well enough, and OpenGL one may be used on all ports. It may be also possible to write another renderer using SDL2 accelerated methods. IIRC there may be problems with using custom shaders with SDL2, but at least this way there will be a fallback even if one of ours won't work on some system.

The only practical purpose of a software renderer left now seem to be 8-bit palette effects. The number of 8-bit games created with AGS today is minimal, and there is a possibility to implement palette emulation (see #1376). As "AGS 4" will remain in wip state for some time, someone might create a solution in the meanwhile.

I'd even suggest to do this for ags3 branch, but it's considered backward compatible and there are at least two open issues that prevent from doing this (#745 and #1376); + safety concerns that there may be new use-cases for it at some point.

**Comment by AlanDrake** [comment]
I'm in favor for removing the software renderer.

**Comment by ericoporto** [comment]
When porting to new systems, the software renderer is very useful to see if things are working, as a stepping stone before moving to figuring how to make the opengl render work - it's useful as a debug tool. I am ok with removing it, but I would really like to make at least a little experiment on the SDL2 renderer to see how to work with it.

Currently not all the blendmodes are supported by the OpenGL ES2 renderer (used in Android and Web ports), but I have seen blendmodes work with the SDL2 Render in other games (non-ags), so I am sure it works there somehow.

**Comment by ivan-mogilko** [comment]
Cannot remove while 8-bit games with palette effects are supported, and there's no clear solution for them with texture-based modes. Would 8-bit mode be removed, or properly supported by hardware-accelerated renderers, then we may return to this question.
