### ISSUE TITLE
Installer: add version numbers to the created links

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1617]
When AGS Editor is installed on a system, it has 3 first version numbers in the title, however these are not added to the link files. As a result it may be difficult to recognize a version when running AGS from a Start menu (or desktop).

The suggestion is to also add these 3 numbers to all the links created by the installer.
In other words change:
* AGS Editor
to
* AGS Editor X.X.X

**Comment by ericoporto** [comment]
Theoretically, this is just adding the three numbers in here, at right in the "Name": 
https://github.com/adventuregamestudio/ags/blob/d3820e0fd369516008633bbc12fc3da359067798/Windows/Installer/ags.iss#L134

It should be possible to use `{#AgsFriendlyVersion}` instead to use the proper version number at the desktop shortcut directly.

<details>it does have an upper directory with version number when loading the start menu though</br>
<img src="https://user-images.githubusercontent.com/2244442/163700623-33622ee1-1176-47ea-8549-6b222bccec8d.png"></details>
