### ISSUE TITLE
Editor: Auto complete list does not appear for extended structs

### ISSUE THREAD

**Issue by tarnos12** [adventuregamestudio/ags#1623]
**Describe the bug**
Auto complete does not appear in various cases(one case that can be tested are extended structs)
As if the ags doesn't recognize the struct, yet the game compiles and struct properties can be read and used in code.
Similar issue was in 3.5.1 but I haven't tested with extended structs.

**AGS Version**
4.0

**Game**
[AutoCompleteTest.zip](https://github.com/adventuregamestudio/ags/files/8529711/AutoCompleteTest.zip)

**To Reproduce**
1) Open a script in Test > Test Auto Complete
2) In game_start function(or any other) type `dialogConfig.` to see if any properties auto complete

**Expected behavior**
Auto Complete should show all properties and functions from a base struct + extended struct, currently it doesn't show anything.

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
Scripts in Config folder are used to setup the extended structs.
The bug also happens in the config script itself in `Initialize` function which means that export/import should not be causing it.
Struct type used in script is not colored green even after restarting the editor.

**Comment by ivan-mogilko** [comment]
Reproduces in both 3.* and ags4.

**Comment by ivan-mogilko** [comment]
Apparently, the way autocomplete cache is coded does not let to know anything about base structs from other scripts, only about  the ones located in the same script.

https://github.com/adventuregamestudio/ags/blob/0af788ef8a35580fde95eead30d48e7fbc30884e/Editor/AGS.Editor/AutoComplete.cs#L142-L155

https://github.com/adventuregamestudio/ags/blob/0af788ef8a35580fde95eead30d48e7fbc30884e/Editor/AGS.Editor/AutoComplete.cs#L202-L215

**Comment by ivan-mogilko** [comment]
Hm, apparently both "Go to definition" command and keyword highlighting are also using Autocomplete cache, which means that fixing autocomplete would also fix these.

**Comment by ivan-mogilko** [comment]
@tarnos12 a test build is available here, if you want one (based on 3.6.0):
https://cirrus-ci.com/task/5416115756072960

**Comment by tarnos12** [comment]
> @tarnos12 a test build is available here, if you want one (based on 3.6.0): https://cirrus-ci.com/task/5416115756072960

@ivan-mogilko That did not fix the issue for me, still can't access properties of an extended struct, I can access it's methods only.

**Comment by ivan-mogilko** [comment]
> Also, F1 on the custom struct/function doesn't open the script file with that struct/property(it opens F1 Help window)

But that was never a feature to go to definition with F1.

**Comment by tarnos12** [comment]
> Hm, apparently both "Go to definition" command and keyword highlighting are also using Autocomplete cache, which means that fixing autocomplete would also fix these.

I meant this part, unless that is not the same thing?

**Comment by ivan-mogilko** [comment]
"Go to definition" command is located in the context menu, which is opened by right clicking on a keyword. It is supposed to work with custom extended structs now.

**Comment by tarnos12** [comment]
Alright, go to definition goes directly to the struct opening bracket `{` instead of the actual property, but it works.
We can consider this issue fixed then.
Extended struct properties are auto completed in all cases(even from different script) and go to definition works well enough.

**Comment by ivan-mogilko** [comment]
> go to definition goes directly to the struct opening bracket { instead of the actual property

This seem to be a new problem in 3.6.0, but it's a separate bug.

**Comment by ivan-mogilko** [comment]
Fixed by #1726
