### ISSUE TITLE
AGS 4: Error creating a room if roomN.asc already exists, also unnecessary warning about roomN.crm

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1624]
**Describe the bug**
If in your game's *root* folder there's a file called **roomN.asc** (room script), and you try to create a new room with the number N, the editor displays following error:

> There was an error attempting to create the new room. The error was: Unable to create a file, as it already exists*

* - translated from localized .NET exception message (probably).

This does not make much sense, as all the room files are supposed to be located inside Rooms/N/ folders.

On a side note, editor still warns about existing **roomN.crm** in the root folder when creating a room of number N. Since we have an open room format now, the crms are generated only during the compilation, therefore overwriting these should not cause a warning.

**AGS Version**
3.99.99

**To Reproduce**
1. Create a new game.
2. Maually create old-format room files, e.g. room10.asc and room10.crm, in the project's root folder.
3. In the editor try to create a room of the same number - e.g. 10.
4. Observe a warning about room10.crm already existing, accept to overwrite.
5. Observe an error saying that some file (not identified) cannot be overwritten.

**Expected behavior**
Editor should not warn about roomN.crm already existing, because with the new open room format the crms are generated at compile time only. It also should not be reacting to roomN.asc in the root folder, nor trying to do anything with it, as these are no longer in use.

**Comment by AlanDrake** [comment]
Fixed in 92bc9cc by adding a new `isNewRoom` parameter to the `ConvertRoomFromCrmToOpenFormat` function, so it doesn't attempt to copy .asc and .user from root when creating a new room.
