### ISSUE TITLE
AGS 4: using "area picker" tool selects wrong area index (index -1), may cause unhandled exception

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1625]
**Describe the bug**
Using a "picker" tool in the room editor would select not the chosen area, but the area of (index-1). If you try to pick an area 1 editor throws an unhandled exception.

EDIT: may be related, so did not open a separate ticket: using the picker outside of the room background also causes exception.

**AGS Version**
3.99.99

**To Reproduce**
1. Make a new room.
2. Paint few walkable areas, say, 1,2,3...
3. Switch to area picker tool and try to select area 3. Notice how area 2 is selected.
4. Try to select area 1. Observe the exception.

**Expected behavior**
Proper area selected, no unhandled exceptions should be caused by this.

**Comment by AlanDrake** [comment]
I was not able to reproduce the -1 index, but the picker is completely ignoring the image bounds and passing straight coordinates to the array, which can go out of bounds or select the wrong area when clicking outside the area.
