### ISSUE TITLE
3.6.0 Editor: room objects are given scriptnames automatically on load (?), may cause conflicts

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1626]
**Describe the bug**
I honestly don't remember whether this behavior was introduced on purpose or are a result of some mistake; but as of 3.6.0 the room objects are not required to have a script name, however, when room is loaded (or saved?) the ones that don't have one are given one automatically. The name generated seem to be simply `oObjectN` where N is the object's ID.

There are two problems here: 1) this name generation is a obscure feature and it's happening in unknown moment (not when the object is created); 2) editor does not check for other existing names, and it may conflict with some other symbol. This leads to errors during script compilation and simply saving the room again, and I believe may be unexpected and confusing for users.

I'm not sure if it supposed to be generated at all, and don't quite remember if that happened before (might have to check earlier versions).

**AGS Version**
3.2.1 - 3.6.0

**To Reproduce**
1. Create a new room.
2. Create a room object, assign script name "oObject1".
3. Create a second object, assign no script name.
4. Save and close the game; alternatively: create another blank room and load one.
5. Reopen the project and/or reload first room.
6. Notice that the second room object, which was previously unnamed, now has script name "oObject1" too (because second object has ID 1, it's zero-based). If you will try to save now, editor will display a "variable oObject1 is already defined" compiler's error.

**Expected behavior**
I'm not certain if editor should be generating script names for room objects, there has not been a rule about that in AGS before (unless I forgot something). But even if it does, firstly it should do that more clearly, e.g. when the object is just created, so that won't be a surprise for the user, and secondly it should check that such name does not exist at least among the other room objects.

**Comment by ivan-mogilko** [comment]
Hmm, this issue is older than I though initially, tested 3.5.1 and 3.5.0, and it also has this behavior.

**Comment by fernewelten** [comment]
Objects only __need__ to have a name when they are referenced from script. This might be the most common use case by far, but I could think of some edge cases where this is not given.

For instance, the object might cover the whole room with a room-size sprite with the intent of blending targeted areas of light and darkness onto everything (using, e.g., the blend mode "multiply").

**Comment by fernewelten** [comment]
> Why does it assign the names only after room is reloaded though, and not initially?

I assume that without this assignment, saving/room changing runs into some kind of snag. So when room saving/switching was programmed, that's when the programmer(s) found out that objects must by needs have a name. Their thinking being in that specific context at that time, they programmed the snag resolution into the room saving/switching routines: We need a name and don't have one? So then let's assign a name automatically here.

An alternative might be to issue an error message when a name hasn't been assigned and the room needs to be switched/saved.

**Comment by ivan-mogilko** [comment]
Here's where the names are given, in CreateInteractionScripts: https://github.com/adventuregamestudio/ags/blob/b482474a2d8b366d6b80dc9ccee8443d580138ba/Editor/AGS.Editor/ImportExport.cs#L227

I assume the reason is these names are necessary for creating unique event handlers for this object.
