### ISSUE TITLE
Editor asks about saving room changes even though no changes were made

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1628]
**Describe the bug**
At certain conditions, when closing current room, the editor would ask whether you like to save changes, even though none are made. The room tab also does not have a "changed" indicator (an asteriks).

I am not fully certain, but this seem to be related to having something selected on a navigation bar.

**AGS Version**
3.6.0, maybe some earlier ones too.

**To Reproduce**
1. In the editor, create a new blank room and save it.
2. Close the game or switch to another room.
3. Reopen the first room again, and immediately close the game/switch to another room once more.
4. Observe the "do you want to save changes" question.

**Expected behavior**
Editor should not suggest to save the room if there were no changes made.

**Comment by AlanDrake** [comment]
Same issue as #1630 because AdjustRoomMaskResolution was changing the Modified status at every room load.

**Comment by ericoporto** [comment]
@AlanDrake this issue is tagged as 3.6.0, but the commit you pushed in the other issue was in ags4

**Comment by AlanDrake** [comment]
Ah, you're right... same problem different places.

**Comment by AlanDrake** [comment]
This issue is caused by DesignModifed being evaluated to true ebcause the hotspot layer is marked as Modified.
I'm still investigating what is changing the value to true because for some reason I can't find where it gets set to true.

**Comment by AlanDrake** [comment]
Found it. The culprit is `control_OnVisibleChanged()` which is setting `Modified` to true, due to a chain call started from loading the room `.user` file.
Is this a mistake or there actually cases where this is correct? Isn't this just a visual change refresh, it shouldn't affect `DesignMode` and set the layer as modified, unless I'm missing something.

**Comment by ericoporto** [comment]
Visibility change needs to be stored in the room user file which requires a save, that part is alright. But loading the xml itself, should perhaps modify the visibility through a different function which would not affect Modified flag, since it's a setup of initial state of the room.

**Comment by AlanDrake** [comment]
IMO room user prefs are "non-essential" and should never cause a query to save or not.

**Comment by ericoporto** [comment]
I don't agree, they are merely there because they are not relevant for actually running the game, but they are part of the room project file, like locked GUI Controls are part of the description of the GUIs in game.agf xml.

**Comment by AlanDrake** [comment]
I would expect design-time options to be autosaved silently or not at all, and save confirm dialogs to appear only when I actually change the room data.
Imagine you open a room to take a quick peek to some element while fiddling with visibility and stuff, and later the save dialog appears making you question if you screwed up and made an unwanted change to the mask.

**Comment by ivan-mogilko** [comment]
I also think DesignModified should not cause the confirmation, this might be a mistake on my part when I introduced this flag.

**Comment by ivan-mogilko** [comment]
> The culprit is control_OnVisibleChanged() which is setting Modified to true, due to a chain call started from loading the room xml .user file.
Is this a mistake or there are actually cases where this is correct?

Hmm, I'd like to take a look, but from the sound of it, it's a mistake and should be DesignModified instead.

**Comment by AlanDrake** [comment]
It is setting DesignModified indirectly by setting the current filter layer as modified. 
Changing the DesignModified property directly would simply set all layers as modified, from what I see in the source.

**Comment by ivan-mogilko** [comment]
> > The culprit is control_OnVisibleChanged() which is setting Modified to true,
> Hmm, I'd like to take a look, but from the sound of it, it's a mistake and should be DesignModified instead.

Oh wait, I did not thought and said some nonsense there. It's not the flag which I was thinking about.
That IRoomEditorFilter.Modified flag is commented as "Gets/sets whether the design-time properties of the layer or items were modified." So .... it has a separate meaning. Need to look more into this.

**Comment by ivan-mogilko** [comment]
Well.... sigh, so I remember these things wrong. To clarify, yes, it actually displays the confirmation if the design-time settings were also changed.
https://github.com/adventuregamestudio/ags/blob/v.3.6.0.23/Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs#L868

So the primary issue is what @ericoporto said:
> But loading the xml itself, should perhaps modify the visibility through a different function which would not affect Modified flag, since it's a setup of initial state of the room.

Don't know about asking confirmation for DesignModified, since it was done so, probably it was thought to be useful.
Maybe we could change the message to say that there were "design-time changes"? In any case this seem to be a separate issue.

**Comment by ivan-mogilko** [comment]
So far it seems this is happening from the call to `TrySelectNodeUsingDesignIDPath`, in turn called from `LoadDataFromXML`. This method is *only* used from `LoadDataFromXML`. The selection itself (`_editAddressBar.CurrentNode = node`) fires `SelectionChange` event.

Relevant parts of the code:
https://github.com/adventuregamestudio/ags/blob/d3820e0fd369516008633bbc12fc3da359067798/Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs#L206
https://github.com/adventuregamestudio/ags/blob/d3820e0fd369516008633bbc12fc3da359067798/Editor/AGS.Controls/AdressBarEx/AddressBarExt.cs#L144
https://github.com/adventuregamestudio/ags/blob/d3820e0fd369516008633bbc12fc3da359067798/Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs#L703


So, one potential solution would be to not attach the event handlers until the data is loaded.

**Comment by ivan-mogilko** [comment]
Hmm, calling `RefreshLayersTree` also leads to the same result. But it has to be called after load (see the comments to the method). I am beginning to think that the simpliest way to hotfix this is to forcefully clear the "modified" flag right after loading the user data.

**Comment by ivan-mogilko** [comment]
Fixed by 0323b48d28b31543307eff7b08dec0e38593aa14.
Simply reset DesignModified flag right after loading a room and user data into the editor: this seem to be the most trivial (and maybe most rational) way to fix this at the moment.
