### ISSUE TITLE
AGS 4: when *.crm output file does not exist, on room save editor still tries to read "blank.crm" from resources

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1629]
**Describe the bug**
After the change to open room format roomN.crm files are no longer sources, but output files.
However, if the file roomN.crm is not present in the project folder, and current room is being saved, the Editor still tries to load "blank.crm" template file from the embedded resources. As this resource no longer exists, it fails, throwing unhandled exception.

**AGS Version**
3.99.99

**To Reproduce**
1. Create a new game in ags4.
2. Delete all *.crm files in the project folder.
3. Open a room in the editor and try saving it.
4. Observe the exception

**Workaround**
Copy any random crm file into the game folder and rename it to match the missing one(s).

**Expected behavior**
As *.crm files are output files now in ags4, them missing is a normal situation. They should be recreated without any error or warning, and preferably not using embedded resources. If a native object is required for saving crm, a blank one should be created in memory programmatically.

**Comment by AlanDrake** [comment]
As a temporary measure, I forced creation of a missing crm file on 67b3ea0 by using `SaveDefaultRoom()`.
How should we fix this the right way? Creating a native method to instantiate the missing `_roomStructPtr`?

**Comment by ivan-mogilko** [comment]
Recently I separated a function in native library, that converts from C# Room to RoomStruct, it's called `convert_room_to_native`. Now it accepts native object as a parameter. This means that it no longer has to work with global native object. This is utilized by `save_default_crm_file`.

I think similar solution could be taken here now. That is - don't create and load native room beforehand, but just pass a managed Room and ask to convert and save.

**Comment by ivan-mogilko** [comment]
I shall close this, as the bug is fixed by 67b3ea0aa6e017f7340a8088d5afdcb291eebf23.
The rest is a matter of refactor.
