### ISSUE TITLE
AGS 4: switching "Default mask resolution" in General Settings seem to also change any opened room afterwards

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1630]
**Describe the bug**
There are two relevant properties in AGS: "Rooms -> Default mask resolution" in General Settings that define mask resolution value for the newly created rooms; and there's "Mask resolution" individual property in each room. The "default" property suppose to only affect newly created rooms, and not change anything in existing ones.

However, in ags4 branch if you change "Rooms -> Default mask resolution" in General Settings, any room opened for editing will also get its "Mask resolution" updated to the new "default" value.

**AGS Version**
3.99.99

**To Reproduce**
1. Create new game and make sure the "Default mask resolution" is 1:1.
2. Create a new room, make sure its "Mask resolution" is 1:1. Save the room and close it.
3. Change "Default mask resolution" to 1:2.
4. Open previous room again. Notice how its "Mask resolution" is 1:2 now.

**Expected behavior**
Individual room's settings should not change after changes in General Settings.

**Comment by AlanDrake** [comment]
It looked like a simple merge mistake, fixed with 9ad7195.

**Comment by ivan-mogilko** [comment]
No, this is incorrect, the part of the code under the GameID check was still necessary, because:
- Room file may be imported (not certain how this works with open format though);
- Room may be created from another template (ags supports multiple room templates).

**Comment by AlanDrake** [comment]
@ivan-mogilko I created a PR for the room template issue  #1633
