### ISSUE TITLE
Debugger on error doesn't show proper line in callstack in some cases

### ISSUE THREAD

**Issue by tarnos12** [adventuregamestudio/ags#1631]
**Describe the bug**
When the error happens in repeatedly_execute_aways while the script is waiting for Wait/blocking command the callstack line will point towards that Wait/blocking command instead of the line where the actual error happens.

**AGS Version**
Apparently it happens since 3.2.1(tested by @ivan-mogilko)
In my case its 4.0 and 3.5.1(the game demo is in this version)

**Game**
[Test Debugger.zip](https://github.com/adventuregamestudio/ags/files/8540699/Test.Debugger.zip)

**Example script**
```
bool ready;
function repeatedly_execute_always()
{
	if(!ready) return;
	float something = 100.0 / 0.0;
}

function on_mouse_click(MouseButton button)
{
	ready = true;
	
	WaitMouseKey(10000);
}
```

**To Reproduce**
1. Left click anywhere
2. The game will crash and show you the callstack pointing at the wrong line.

**Expected behavior**
Debugger should point towards the correct line where the error happened even during blocking/Wait commands.

**Comment by ivan-mogilko** [comment]
I found what the mistake is:
when the script callback returns with the error value as seen in the code below; it does not immediately quit, but does some cleanup actions first, including resetting the script instance `currentInstance`; and returns with error only few lines later.

https://github.com/adventuregamestudio/ags/blob/v.3.6.0.23/Engine/script/cc_instance.cpp#L387-L388

The `currentInstance` is used later to get the stack information, and it is a different script instance already.

The most trivial fix is to move `if (reterr) return -6;` right under the `int reterr = Run(startat);`. This will make the stack info retrived from the script instance that had error in.

While this may work as a hotfix, it's not perfect, as it relies on how the return value is handled along the way, and whether something is done with `currentInstance` variable in the meanwhile. So it's still quite "fragile".

Also, it may be useful to also have an additional stack that led to the blocking action, during which the rep-exec-always was ran. Getting one would require to change how the error information is gathered though.

**Comment by ivan-mogilko** [comment]
Did some restructuring in the code related to script error reporting. Now it is recovers callstacks from both active and waiting script "thread", making it possible to see both location of error in rep-exec-always and location where blocking action was called. This is available both in the debugger, and when simply error message is displayed.

For example, the error message now may looks like:
<pre>
An error has occurred. Please contact the game author for support, as this is likely to be an error in game logic or script and not a bug in AGS engine.
(ACI version 3.6.0.24)

in the active script:
in "room1.asc", line 7
in the waiting script:
in "room1.asc", line 13

Error: Error running function 'repeatedly_execute_always':
Error: Floating point divide by zero
</pre>
