### ISSUE TITLE
Building the AGS editor on macOS?

### ISSUE THREAD

**Issue by eisnerguy1** [adventuregamestudio/ags#1634]
I haven't been able to find any guide on building the AGS Editor on macOS. Is this only available on Windows? I've found some guides getting the Windows version running on macOS but, I can't seem to get it to work:
https://www.adventuregamestudio.co.uk/forums/index.php?topic=59079.0

Is there a way to compile the AGS editor for macOS?

**Comment by ivan-mogilko** [comment]
No, there's no way to compile the Editor anywhere but in Windows at the moment.

It may be only run on other systems using virtual machine or other emulators like Wine.

**Comment by eisnerguy1** [comment]
Ah, gotcha. I actually got it running in Wine on my Mac 👍🏻 Can't wait to get started 😄
