### ISSUE TITLE
3.6.0: Panning does not work with stereo clips

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1637]
**Describe the bug**
Panning setting does not work with stereo clips in 3.6.0. It seems that OpenAL specification only defines sound positioning for mono clips. Might need to search for this in the standard, but so far there's a comment in mojoal.c on this:
https://github.com/adventuregamestudio/ags/blob/3dd153f7c4cff10ec0abfa42ca608306cc730316/libsrc/mojoAL/mojoal.c#L1444-L1448

EDIT: The OpenAL's [programmers guide](https://openal.org/documentation/OpenAL_Programmers_Guide.pdf) (page 21) sais this:
> Stereo data is expressed in interleaved format, left channel first. **Buffers containing more than one channel of data
will be played without 3D spatialization.**

Also see #1420 with comments from @AlanDrake. Unfortunately, although panning was fixed for mono sounds, we forgot to open a ticket about stereo panning not working earlier, so this problem was forgotten.

**AGS Version**
3.6.0

**Game**
Here's a test game made in 3.5.1, to be able to test in both 3.5.1 and 3.6.0 engine:
[test--audiopanning351.zip](https://github.com/adventuregamestudio/ags/files/8571634/test--audiopanning351.zip)

**To Reproduce**
1. Run the game in 3.5.1 engine. Controls: Space to play the sound; Left arrow to pan left, Right arrow to pan right, Up arrow to reset panning.
2. Run same game in 3.6.0. Use same controls. Notice that panning is not applied.

**Expected behavior**
The Panning setting should work with stereo clips.

**Comment by ericoporto** [comment]
There's a discussion here: https://github.com/kcat/openal-soft/issues/194

**Comment by ivan-mogilko** [comment]
> There's a discussion here: [kcat/openal-soft#194](https://github.com/kcat/openal-soft/issues/194)

From the quick glance they discuss how to emulate 2D panning with OpenAL's interface. But this is already done in our code (there's even a link to that discussion there).

**Comment by ivan-mogilko** [comment]
Looks like the solution could be to split stereo sound by channels, and play in two mono-sources. Then panning would be implemented as changing volume of these two sources, e.g. panning left would lower the "right" source's volume.
(I think this is what Alan mentioned in the closed ticket too)

I remade the test game to contain a clip which has different waveforms in channels. Testing in 3.5.1, the panning indeed works as lowering or rising volume only for particular channel, and not e.g. copying whole sound to one side. So I guess this is how it should be recreated in 3.6.0.

**Comment by ivan-mogilko** [comment]
So, i did few tests...

1. First of all, playing and balancing two sources (left & right) is possible. There's a question of synchronization, but allegedly OpenAL should handle this if they are started at the same time and feed data stably.

There's a brief example for doing this with mono wave here, I think this was written by the author of OpenAl-soft:
https://openal.org/pipermail/openal/2014-April/000105.html

For stereo wave you have to play stereo sound as 2 mono sounds and split the wave data into two buffers. I did a primitive test here: https://github.com/ivan-mogilko/ags-refactoring/tree/360--stereopanning-test2
(plays only 1 channel at a time though)

Organization-wise, there may be 2 approaches to this: either have both al sources inside a OpenAlSource class, or use two OpenAlSource objects, but then the task for synchronizing and configuring their relation is delegated to the external user (audio core code in our case).

The biggest issue I see with this is the extra code and the extra work at runtime. As the sound data will have to be continiously split, while the panning is rather a rare operation, at least based on my experience with AGS games. Maybe there's a way to "optimize" this by keeping the playback stereo until Panning is first set, after which recreate sources as 2 mono and continue from there; but this will further complicate the code of course.

---

2. Making an "extension" to mojoAl. I noticed that it already has a clear use of split "gains" values for two channels in its implementation. This is where it saves the calculated volumes from 3D positioning: https://github.com/adventuregamestudio/ags/blob/master/libsrc/mojoAL/mojoal.c#L1472

So I made a simple experiment of adding a new BALANCE property to the al source, and using that to set that gain pair for the stereo sound: https://github.com/ivan-mogilko/ags-refactoring/tree/360--stereopanning-test3

It works well, requires a minimal amount of code, plus does not add any overhead, as there's no additional sound processing.

The problem is of course that this means hacking the library. (Also, I don't know how exactly the OpenAL extensions should be organized)

**Comment by ericoporto** [comment]
> So I made a simple experiment of adding a new BALANCE property to the al source, and using that to set that gain pair for the stereo sound

This looks like few enough lines where you could make a PR in the MojoAL repository. I don't think Ryan will merge, but instead I think he will understand the idea and make his implementation of that to provide the desired feature.

**Comment by ivan-mogilko** [comment]
Reading their answers, brought me to conclusion that my solution (actually, both of them) is not really panning in the OpenAL's sense; instead that would be "channel balance" or "channel volume" (perhaps there are more correct terms).

When this was added to AGS this feature used whatever option was provided by the backend (allegro4), which happened to be implemented as a channel balance. So I guess this is what we should be aiming at if we aim at keeping things compatible with the historical feature. Otherwise, we need to separate panning as in positioning, and volume balancing as two different options.

**Comment by ericoporto** [comment]
ags4 Draconian has some type of audio positioning for sounds from characters viewframes. The request from vga256 was actually regarding HRTF OpenAL extension in MojoAL. Let's figure on MojoAL if something can be accomplished there for the panning implementation, since the panning is used as a primitive substitute for 3D audio by developers.

**Comment by ivan-mogilko** [comment]
Closing this, as the original implementation was not real panning, as mentioned in the comments above, but the channel balance change, thus it contradicted the given API's meaning. If we want to support individual channel volumes in stereo - that would be a separate feature request.

Overall, it seems, the idea of a stereo or surround-sound clip contradicts the idea of 2D panning or 3D positioning on its own.

The workaround for panning stereo sounds is to convert them to mono. This may be done either by game dev or by the engine, but if done by the game dev that would save runtime processing.
