### ISSUE TITLE
[AGS 4.0] Changing room background to a different size, breaks the room masks.

### ISSUE THREAD

**Issue by tarnos12** [adventuregamestudio/ags#1638]
**Describe the bug**
Changing room background to a larger size(perhaps works with smaller size too) breaks the mask size for walkable/region/hotspot etc.
This prevents from saving the room as it throws an error.(only tested by adding new object)

**AGS Version**
4.0

**To Reproduce**
1. Create a project in 4.0(BASS Template in my case)
2. Open room and change background to something bigger(1920x1080 in my case)
3. Close the editor which will prompt you to save which you should do.
4. Reopen the project
5. Go back to the room
6. You will notice some warnings about using 8bit palette
7. Click ok few times
8. Add a new object
9. Try to save the room
10. You will see some errors.

**Possible workaround**(Can't reproduce it anymore, perhaps you need a character to be in that room or some other conditions need to be met)
1. You need to remove the room and make a fresh one(perhaps it can be avoided idk)
2. When you add a background go to Room > Hotspots, then Room > Regions/walkable area/walk behind to "load" those masks(no idea how that works)
3. Afterwards you can save the room and I believe that masks will be saved at new size and you can avoid the problem.

**Expected behavior**
Room should save when changing a background, it should resize masks and do all that is necessary to avoid errors when loading it later.

**Desktop:**
- Win 10

**Additional context**
Original issue happened in 1920x1080 game(general settings)(and background used was 2x bigger)
Testing and reproducing happened in BASS template which is setup to lower resolution.(background used was 1920x1080)
It seems like changing resolution in general settings allows you to use background of that specific size.
Using bigger background won't work.
Also this applies only when loading a room after the background has changed.
You can edit a room correctly when its opened for the first time after the background has changed.
So you wouldn't know about the issue until the next time you opened the project and your room.

**Comment by ivan-mogilko** [comment]
There are two problems:
1. If the editor detects "invalid mask", for whatever reasons, it enters the unsafe state where some actions, such as drawing masks, lead to unhandled exceptions.
2. When the room background is resized, the masks are saved in some wrong way, that prevents editor to load them back later.

**Comment by ivan-mogilko** [comment]
Pushed a fix: 022f2c1c4c4a52143413ae13b4bfedad3988210e

**Comment by ivan-mogilko** [comment]
Seem fixed.
