### ISSUE TITLE
Error when a float parameter has a default value

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1642]
**Describe the bug**
This is bug #188 again.

#1065 added support for float as a default value. But that PR code disappeared from the master branch.

You can verify tests for float default values were supposedly added in [`Compiler/test/cs_parser_test.cpp`](https://github.com/adventuregamestudio/ags/blob/master/Compiler/test/cs_parser_test.cpp), but they are gone.

**AGS Version**
Current master: https://github.com/adventuregamestudio/ags/commit/b482474a2d8b366d6b80dc9ccee8443d580138ba

**Game**
If applicable, link or attach an example game (with optional source) to demonstrate the issue.

**To Reproduce**
- Create a new header and add the following  code
```
// new module header

import  int  importedfunc(float data1 = 0, float data2=12.5, float data3=-35654.156);
```
- It will complain `CompilerBug.ash(3): Error (line 3): Parameter default value must be literal`

**Expected behavior**
It should compile

**Comment by ericoporto** [comment]
Additionally found that the PR code has the Tests using `char * s = "a string"` instead of `const char * s = "a string"`, the omission of **const** is invalid in clang.

**Comment by ivan-mogilko** [comment]
This is a consequence of changing master to ags4 and then back to ags3.

**Comment by ivan-mogilko** [comment]
@ericoporto i noticed you made a branch in your repo, i think it looks fine for a pr.

**Comment by ericoporto** [comment]
I was going to but then I got confused why Alan's commit hash was different, but then I noticed it's probably due to being rebased.
