### ISSUE TITLE
3.6.0: solution for playing MIDI on Windows

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1649]
From what I can tell, SDL_Sound initializes MIDI decoder only if it can load up timidity.cfg. It may look into standard path, or a path taken from enviroment variable, which we could perhaps set ourselves or through config, but that's not the point. The biggest issue is that this requires users/players to have something extra installed along with the engine or game to be able to hear midi music.

What are the potential workarounds here? What kind of data does timidity.cfg contain (I have no knowledge of that, so need to research this myself first)? Does it depend on system, or there could be a universal config? May it be a clever move to provide timidity.cfg as an embedded resource along with the windows engine exe?
(BTW, it seems like SDL_Sound does not support passing a custom rwops with this config, so currently it requires a config file on disk... unless there's a way to make it read from memory which I missed.)

**Comment by ericoporto** [comment]
> his requires users/players to have something extra installed along with the engine or game to be able to hear midi music.

Windows has two MIDI APIs and has a MIDI playback device. We could use it, but this means the sound won't be played by whatever is the current SDL2 audio device on Windows. This was how allegro accomplished MIDI playback on Windows.

**Comment by ivan-mogilko** [comment]
> Also this may frustrate developers that use MIDI instead one of the tens of possible other mod audio formats when they are going to port their game to any other system and realize their music doesn't work there...

Why would not it work there?

**Comment by ivan-mogilko** [comment]
> Also this may frustrate developers that use MIDI instead one of the tens of possible other mod audio formats when they are going to port their game to any other system and realize their music doesn't work there...

Why would not it work there?

**Comment by ericoporto** [comment]
because it will require a soundfont :/

**Comment by ivan-mogilko** [comment]
How does it work on other systems now? Does it work at all?

**Comment by ericoporto** [comment]
Well, you can verify on Windows itself:

[TIMIDITY.zip](https://github.com/adventuregamestudio/ags/files/8766434/TIMIDITY.zip)

extract this zip in Windows, place it so you have the following structure `C:\TIMIDITY\instruments`, where instruments contains a bunch of `.pat` files. Now play some game with midi or just use your own midi file, here's one: [prepare_your_swords.mid.zip](https://github.com/adventuregamestudio/ags/files/8766505/prepare_your_swords.zip)

**Comment by ivan-mogilko** [comment]
> Well, you can verify on Windows itself: [TIMIDITY.zip](https://github.com/adventuregamestudio/ags/files/8766434/TIMIDITY.zip)

This technically works, although in the games I tried some instruments were not playing at all (necessary data not present?).

**Comment by ericoporto** [comment]
When RWops gets implemented in SDL_sound (https://github.com/icculus/SDL_sound/issues/69) it would be possible to a game to ship it's own "instruments" theoretically.

**Comment by ivan-mogilko** [comment]
Alright, so, after experimenting, it's established that you have to have timidity config and sound patches (instrument bank) either installed in the system (path depends on a system) or inside the current working dir (game dir normally). There's no other way currently.

This is a regression for the Windows engine, but this brings it in compliance with the rest of the ports.

I think this must be documented in the manual, after which this issue may be closed.

**Comment by ivan-mogilko** [comment]
Added a simple article to the manual: https://github.com/adventuregamestudio/ags-manual/wiki/MIDI-playback
