### ISSUE TITLE
Feature request: some way to scale GUIs

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1656]
**Describe the problem**
Rooms now have the concept of Camera and Viewport which allows it to adapt in different ways to a different Screen Size - as in the AGS in-game resolution. It would be useful if GUIs had some way to adapt too. 

One feature that would help, would be some way to modify the GUI size in a way it scales, along with all controls in it - if the GUI width and height were it's camera width and height, you can think of the scaling as the target viewport.

For my right away use, it would be to scale GUIs when I am scaling the screen so they can match, and I can have the rooms in a higher resolution - which allows me to implement a smoother game camera.

**Suggested change**
Either a game wide GUI scaling parameter or some per GUI scaling setting. Alternatively some projection width/height.

**Considerations**

- in non-pixelart games, it may be desired that the fonts are drawn at screen size if the UI is scaled up or down to avoid blurriness
- advanced scaling techniques may require a layout system for GUIs which may make their development more complex
- while there are means to provide UI scaling baked in GUI systems in more advanced game engines, they also are reportedly more complex to use, while AGS has a very easy to use UI system, we could still look into how scaling is done in these engines.
- the scaling proposed here is the simplest as possible that decouples the GUI resolution from the game screen resolution

**additional context**

- https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Cameras_And_Display/display_set_gui_size.htm

**Comment by ivan-mogilko** [comment]
In AGS 4 branch the cursor interaction (hit tests) are already taking transformations into account, because of rotation support. So adding visual scaling to GUIs alone is trivial, and is mostly a matter of API.

**Comment by ericoporto** [comment]
Yes, the scaling I am referring is the same there, a transformation. For pixel art aesthetic that is fine and works great!

I just have concerns that someone will ask a feature similar to "Render character in screen resolution", but for texts, once the GUI can be scaled and not be in screen resolution.

**Comment by ericoporto** [comment]
A PR for this issue is in #2426.

**Comment by ivan-mogilko** [comment]
#2426 is now merged, and its effect corresponds to the following paragraph from this ticket:

> One feature that would help, would be some way to modify the GUI size in a way it scales, along with all controls in it - if the GUI width and height were it's camera width and height, you can think of the scaling as the target viewport.

if that covers current ticket, then it should be closed as resolved. If not, then some clarification should be added.

**Comment by ericoporto** [comment]
It does! Thanks!
