### ISSUE TITLE
[not a bug] Incorrect button placement in Primordia

### ISSUE THREAD

**Issue by rathann** [adventuregamestudio/ags#1660]
**Describe the bug**
Fonts are rendered in the wrong place in when running Primordia (GOG build 2.0.0.2) with ags-3.6.0.25 and 3.5.0.32.

**AGS Version**
3.6.0.25/3.5.0.32

**Game**
Primordia, GOG build 2.0.0.2.

**To Reproduce**
1. ags /path/to/Primordia.exe
2. See error

**Expected behavior**
Fonts should be rendered as with the bundled ags.

**Screenshots**
Primordia with ags-3.6.0.25:
![Primordia-with-ags-3 6 0 25](https://user-images.githubusercontent.com/5873507/168068335-d30a978e-1a53-4121-a899-77df84ec8589.png)

Primordia with bundled ags-3.5.0.26:
![Primordia-with-bundled-ags-3 5 0 26](https://user-images.githubusercontent.com/5873507/168068520-7da3a1b7-d75f-42c4-b931-b9c6222c8b90.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux, MATE Desktop
 - Version 36

**Additional context**
ags built from source with the following parts unbundled:
* glm
* `<KHR/khrplatform.h>`
* libogg
* libtheora
* libvorbis
* tinyxml2

Using bundled freetype-2.1.3 or unbundling it doesn't make any difference.

**Comment by rathann** [comment]
FWIW the AGS engine in scummvm-2.5.1 has the same issue on Fedora.

**Comment by rathann** [comment]
And here's the terminal output:
```
Adventure Game Studio v3.6 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2022 others
ACI version 3.6.0.25

Initializing backend libs
Initializing game data
Opened game data file: game28.dta
Game data version: 50
Compiled with: 3.5.0.26
Startup directory: /usr/share/primordia/
Data directory: /usr/share/primordia/
Setting up game configuration
Voice pack found: speech.vox
audio.vox found and initialized.
Initializing TTF renderer
Initializing mouse: number of buttons reported is 3
Install timer
Audio driver: pulseaudio
AudioCore: opened device "Default OpenAL playback device"
Supported sound decoders:
 - Play modules through ModPlug : 669,AMF,AMS,DBM,DMF,DSM,FAR,GDM,IT,MDL,MED,MOD,MT2,MTM,OKT,PTM,PSM,S3M,STM,ULT,UMX,XM,
 - MPEG-1 Audio Layer I-III : MP3,MP2,MP1,
 - Microsoft WAVE audio format : WAV,
 - Audio Interchange File Format : AIFF,AIF,
 - Sun/NeXT audio file format : AU,
 - Ogg Vorbis audio : OGG,
 - Creative Labs Voice format : VOC,
 - Raw audio : RAW,
 - Shorten-compressed audio data : SHN,
 - Free Lossless Audio Codec : FLAC,FLA,
Install exit handler
Initialize path finder library
Game title: 'Primordia'
Game GUI version: 119
Requested script API: v3.5.0-final (7), compat level: v3.5.0-final (7)
WARNING: font 'agsfnt0.wfn' has mistakes in data format, some characters may be displayed incorrectly
WARNING: font 'agsfnt3.wfn' has mistakes in data format, some characters may be displayed incorrectly
WARNING: font 'agsfnt5.wfn' has mistakes in data format, some characters may be displayed incorrectly
WARNING: font 'agsfnt16.wfn' has mistakes in data format, some characters may be displayed incorrectly
WARNING: font 'agsfnt19.wfn' has mistakes in data format, some characters may be displayed incorrectly
WARNING: font 'agsfnt23.wfn' has mistakes in data format, some characters may be displayed incorrectly
WARNING: font 'agsfnt26.wfn' has mistakes in data format, some characters may be displayed incorrectly
Plugin 'agsteam' could not be loaded (expected 'libagsteam.so'), trying built-in plugins...
Placeholder functions for the plugin 'agsteam' found.
Checking for disk space
Game native resolution: 320 x 200 (32 bit)
Graphic settings: driver: D3D9, windowed: yes, screen size: 0 x 0, game scale: round
Requested graphics driver 'D3D9' not found, will try existing drivers instead
Running OpenGL: 3.1
Mouse speed control: enabled, unit: 1.000000, user value: 1.000000
Setting up window
Initialize sprites
Engine initialization complete
Starting game
corrupted double-linked list
Aborted (core dumped)
```

Note: the crash happens only when closing the game window.

**Comment by ivan-mogilko** [comment]
I'm not sure tbh that this is fonts positioned wrong, it looks like the whole button (or whatever that is) is relocated to the top-left corner.

**Comment by ivan-mogilko** [comment]
@rathann could you tell, does this happen only to Primordia, or other games have similar mistakes in text or gui positioning?

**Comment by rathann** [comment]
Thanks for looking at this. I don't have any other AGS games at the moment, but I'll download some free ones and test.

**Comment by ivan-mogilko** [comment]
I should perhaps note that this did not reproduce for me, but I own a Steam release which may be of different version and release date. Tested on Windows 7 and Ubuntu vm. If this problem won't reproduce in some free games, perhaps I would be able to ask developers to send me a free copy of this particular GOG release of their game for a test.

**Comment by rathann** [comment]
Thanks for looking at this. I checked with [Clotilde Soffritti 2](https://www.adventuregamestudio.co.uk/site/games/game/2608-clotilde-soffritti-in-never-double-park-your-spaceship/) and it seems fine, both with bundled freetype and with system freetype (2.12.1).

**Comment by rathann** [comment]
Same (good) results with [The Cabin](https://www.adventuregamestudio.co.uk/site/games/game/2494-the-cabin/). I guess this is something specific to the GOG build of Primordia, then.

**Comment by Dualnames1** [comment]
Rathann, this might be a diff issue, do u happen to have ENGV.TMP [from a previous version of Primordia in your savegame folder?] Regardless, i suggest you find said file, and only keep it at one location, the game's installation folder. Remove every other instance of it.

**Comment by Dualnames1** [comment]
Also, i don't believe Primordia was ever ported to 3.6 per se. I believe it's at 3.5 but i could be wrong.

**Comment by ivan-mogilko** [comment]
> Also, i don't believe Primordia was ever ported to 3.6 per se. I believe it's at 3.5 but i could be wrong.

3.6 is supposed to stay fully compatible to 3.5 (and earlier versions), it's expected that 3.5 games run fine on it.

**Comment by rathann** [comment]
> Rathann, this might be a diff issue, do u happen to have ENGV.TMP [from a previous version of Primordia in your savegame folder?] Regardless, i suggest you find said file, and only keep it at one location, the game's installation folder. Remove every other instance of it.

@Dualnames1 That was it! The file was actually missing in the copy that I was trying to run. Sorry for the misleading report, then. There's no bug here. Thank you very much!
