### ISSUE TITLE
Incorrect Blank Lines when saving Dynamic Sprite

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1681]
**Describe the bug**
When saving a dynamic sprite, a white line or area appears mysteriously in the dynamic sprite.

**AGS Version**
Current master (c7bd448dfffc197c4398a38395b444457c958d24).

**Game**
[TestSpriteSave.zip](https://github.com/adventuregamestudio/ags/files/8857205/TestSpriteSave.zip)

**To Reproduce**
1. Create a new game with the sierra template
2. Place following code in the room
```AGS Script
// room script file

Overlay* ovr;
DynamicSprite* dynspr;

function room_AfterFadeIn()
{ 
  dynspr = DynamicSprite.Create(320, 80, true);
  DrawingSurface* surf = dynspr.GetDrawingSurface();
 
  surf.DrawImage(20, 20, 2168);
  surf.DrawImage(0, 0, 2042);
  surf.DrawImage(40, 40, 2041);
  
  surf.Release();
  
  dynspr.SaveToFile("$SAVEGAMEDIR$/save_dynspr.bmp");
  
  ovr.CreateGraphical(40, 40, dynspr.Graphic, false);  
}
```
3. Now go into your saved games dir an see the bitmap is defective and has a white area in it.

Alternatively, run the attached game and look into the savegame dir.

**Expected behavior**
The dynamic sprite should be full pink with or alpha with a blue cup, a key and a blueish rounded rectangle, **but no white areas**!!

**Screenshots**
![image](https://user-images.githubusercontent.com/2244442/172502484-348ab5ed-396a-4286-b465-91a620c1166e.png)

The white line doesn't exist in script

**Desktop:**
 - OS: Windows
 - Version 10

**Additional context**
Reported in the forums here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=59842.msg636646806#msg636646806

**Comment by ivan-mogilko** [comment]
This is an old bug, supposedly since after the switch to SDL2 backend. I now suspect something was broken in allegro4 after its code got stripped.

**Comment by ivan-mogilko** [comment]
Pushed a fix: 623db88c135304bc3c462edffb742633ec50d608

There was a mistake in allegro's packfile implementation, it did not initialize or ended writing correctly.
I guess that ideally we should change allegro image saving and loading to just use our streams instead, but this is a hotfix for now.

**Comment by ericoporto** [comment]
Thanks!

> I guess that ideally we should change allegro image saving and loading to just use our streams instead

We have an AllegroBitmap class in common, my idea would be to 

- transplant the save and loading functions from allegro4 C functions to that class under SaveBmp and LoadBmp functions that could write/read to a stream
- then rewire the current SaveToFile method in that class to use these stream methods
- check if there's need to read other formats in that class, like, I remember we had pcx file format for the splash screen, so need to verify this...

**Comment by ivan-mogilko** [comment]
> We have an [AllegroBitmap](https://github.com/adventuregamestudio/ags/blob/master/Common/gfx/allegrobitmap.cpp) class in common

I believe that saving to file should be separate from the bitmap class; bitmap class is for drawing, while serialization is a separate task and deals with file formats.

**Comment by ericoporto** [comment]
@ivan-mogilko not sure on the name, but just testing the idea

https://github.com/ericoporto/ags/commit/119ed6245a75a55c8bcccb5972cb045f875f4220

**Comment by ivan-mogilko** [comment]
Well, yes; note you may just add them to the existing BitmapHelper namespace:
https://github.com/adventuregamestudio/ags/blob/0fd748eada90e1f07a8cb47430703744bc4613b1/Common/gfx/bitmap.h#L61

**Comment by ericoporto** [comment]
> Well, yes; note you may also just add them to the existing BitmapHelper namespace: 

I don't understand what you mean, like, the loading should work with that too? If it's that, I haven't yet made the loading functions.

Just to make it easier to follow the conversation, I created a draft PR in #1682
