### ISSUE TITLE
3.6.0: MP3 clips don't return a valid LengthMs

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1689]
Using `AudioChannel.LengthMs` does not return a valid length for MP3 clips.
This is because of the missing functionality in SDL_sound (see https://github.com/icculus/SDL_sound/issues/71).

**Comment by ericoporto** [comment]
Our previous mp3 implementation did a curious thing:

https://github.com/adventuregamestudio/ags/blob/14840e4f142bd7def54a3274454944f03eb08cff/Engine/libsrc/almp3/almp3.c#L1881-L1886

**Comment by ericoporto** [comment]
They updated SDL_Sound, need to check if it's actually working and update the version in AGS to that commit

**Comment by ericoporto** [comment]
@ivan-mogilko in the patch for that issue, there's a very interesting division + modulo trick, I wonder if there is any case in ags where there is an integer division where that may be necessary.
