### ISSUE TITLE
Invalid SDL_AUDIODRIVER environment variable may prevent audio to initialize

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1692]
**Describe the bug**
If you set an environment variable `SDL_AUDIODRIVER` to an invalid value, AGS may not initialize, due to SDL complaining the system does not exist.

**AGS Version**
Current master (5c3a5eabc1daf331acc2d2e9568f4f4dda4c7b0c).

**Game**
It can happen in any game. 

**To Reproduce**
1. On Windows, click on System Properties
2. Then on Environment Variables and then create a new one name `SDL_AUDIODRIVER` and set it to an invalid value (say, `dsound2`).
3. Start AGS, it will pop-up an error message

**Expected behavior**
The expected behavior is for AGS to figure a good known driver and start anyway.

**Desktop:**
 - OS: Windows
 - Version 10

**Additional context**
I am not sure if this is an AGS bug, so I opened it upstream too https://github.com/libsdl-org/SDL/issues/5818

**Comment by ericoporto** [comment]
So they only adjusted the case of `dsound`, but not being able to not fail, not sure how to approach here, but AGS used to not fail and instead figure out a valid audio driver.

I also am not fully sure, but I believe we are initializing the SDL Audio twice, once in sys_main and another time in audio_core, through MojoAL. The MojoAL initialization also pass an additional information describing what the driver must have.

The following code is wrong, but I had [this](https://github.com/ericoporto/ags/commit/30b718558dfd0274578f8de7def083201c2d4960) idea of iterating to find a working audio driver, but this would have to happen in audio_core in case my previous observation is correct.

**Comment by ivan-mogilko** [comment]
> I also am not fully sure, but I believe we are initializing the SDL Audio twice, once in sys_main and another time in audio_core, through MojoAL. The MojoAL initialization also pass an additional information describing what the driver must have.

MojoAL directly initializes *device*, not driver, these are different things. For the *device* initialization it passes its own name (optional), frequency, etc.
I don't think SDL2 will reinitialize an audio driver for the second time, but this may be double checked through code or debugging of course.

**Comment by ericoporto** [comment]
> I don't think SDL2 will reinitialize an audio driver for the second time (from documentation it seems that if subsystem is ready, then SDL2 should just increase subsystem's ref count and skip)

This is correct from the documentation, indeed. But this is what is weird, if I set an environment variable `SDL_AUDIODRIVER` with an invalid value (like `dsound2`), and set the audio driver to WASAPI in winsetup, I get the following log:
> ...
> Audio driver: wasapi
> Failed to initialize audio system: AudioCore: error opening device
> Audio is disabled
> ...

**Comment by ericoporto** [comment]
Apparently the result is just never use SDL_AudioInit. Maybe we need to override those weird environment variables of sdl2 with some value for each driver and clean it when selecting AUTO.

**Comment by ivan-mogilko** [comment]
@ericoporto tbh I'm getting confused by this issue thread. The original problem was that AGS fails to init if the requested driver id is unknown? But is the mojoAl's problem is a separate one? If so, may it be opened as a separate ticket?

Was the original problem solved though?

**Comment by ericoporto** [comment]
https://github.com/adventuregamestudio/ags/blob/f8a90c3b1c74c54f287698b76bf4ae23e92d74e9/Engine/platform/base/sys_main.cpp#L96-L102

These lines are wrong and instead it should write an empty SDL_setenv or the specific driver name selected. SDL_AudioInit should not be used since it's not ref counted.

> Was the original problem solved though?

In SDL 2.24, it will accept `dsound` as a valid spec of directsound for SDL_AUDIODRIVER environment variable which previously caused AGS to not load. This environment variable is used in SDL 1.

**Comment by ivan-mogilko** [comment]
> These lines are wrong and instead it should write an empty SDL_setenv or the specific driver name selected. SDL_AudioInit should not be used since it's not ref counted.

Please, could you elaborate why is that a problem that SDL_AudioInit is not ref counted? Is it related to what mojoAl is doing?

> In SDL 2.24, it will accept dsound as a valid spec of directsound for SDL_AUDIODRIVER environment variable which previously caused AGS to not load. This environment variable is used in SDL 1.

So, how the engine should be acting if it does not use SDL 2.24?

**Comment by ivan-mogilko** [comment]
> These lines are wrong and instead it should write an empty SDL_setenv or the specific driver name selected. SDL_AudioInit should not be used since it's not ref counted.

Re-reading all the above comments, do I understand correctly, that mojoAL cannot figure out that the audio subsystem was already initialized, and it tries to initialize something of its own once more?

> In SDL 2.24, it will accept dsound as a valid spec of directsound for SDL_AUDIODRIVER environment variable which previously caused AGS to not load. This environment variable is used in SDL 1.

I recall you wanted to provide a list of valid devices, in case the one set with enviroment variable in the system is invalid. Is that solution still feasible, or it's not because of the mojoAl's problem?

**Comment by ivan-mogilko** [comment]
So, I have got a question. If we must use SDL_InitSubSystem to let SDL2 set the ref count, then may we do this sys_main:
* set enviroment variable
* call SDL_InitSubSystem
* on failure - retry with every other known "valid" device, like you suggested some time ago.

**Comment by ivan-mogilko** [comment]
@ericoporto opened a pr: #1747

Note, I found there's no need to have your own list of drivers, as SDL2 already tries this list if the env SDL_AUDIODRIVER is null.
If we still need to do this manually, we may use SDL_GetNumAudioDrivers / SDL_GetAudioDriver(index) to get this exact list (https://wiki.libsdl.org/SDL_GetAudioDriver).

(Of course if above list is bad for some reason, in that case we could still have our own, as a last resort, but hopefully that won't be necessary)
