### ISSUE TITLE
AGS 4: New compiler: remove or change octal literals syntax

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1711]
Opened after conversation in #1675.

CC @fernewelten 

The new compiler currently supports octal literals, which syntax is `0number` (starting with `0`). There's a valid concern that such syntax may be confusing and may cause script mistakes which will be difficult to find. In overall, octal literals are rather obscure thing today, and less useful in a scripting language (personally I cannot imagine any practical use for them in AGS script); so it would be wiser to make them more explicit and less prone to typos. My suggestion is to do one of the following:

* Change octal prefix to `0o`/`0O` instead (complementing hexadecimal `0x`/`0X`), similar to javascript's strict mode, as per [ericoporto's suggestion](https://github.com/adventuregamestudio/ags/pull/1675#issuecomment-1146806667);
* Remove octal literal support altogether, to simplify the case; unless there's a real interest in having them in script.

**Comment by fernewelten** [comment]
Addressed in #1738.

I've currently removed octals for the time being, but I'm considering taking up eric0o's suggestion in a later, separate PR.

**Comment by ivan-mogilko** [comment]
Resolved by #1738 (disabled for now).
