### ISSUE TITLE
Android: AGS Player crashing when launching a game

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1712]
**Describe the bug**
On Android, launching *any* game with AGS Player will make the app stop. Menu itself works fine (Games list, preferences, credits).
At the same time a stand-alone game APK works fine.

**AGS Version**
The last working version is 3.6.0.17, the problem was introduced in 3.6.0.18.

**Additional context**
According to [the release changelog](https://github.com/adventuregamestudio/ags/releases/tag/v.3.6.0.18) that was the version when building for Android was added to the Editor. It could be that there had been a simultaneous change to the engine library that broke it for a launcher.

No log is written when it crashes, but I also was not able to make AGS Player write any log whatsoever in any version i tried (since 3.6.0.14), so not sure if this is a general issue (may require a separate investigation).

**Comment by ericoporto** [comment]
I have been only testing the apk I build myself on Android Studio, so I decided to install [the apk from cirrus itself](https://cirrus-ci.com/task/5923261534961664)... And it works fine on my phones. Can you give me a crash report or some additional information? Is this in a particular game?

**Comment by ivan-mogilko** [comment]
> Can you give me a crash report 

Where may I get this crash report on a Android device?

**Comment by ericoporto** [comment]
I reproduce this in the Emulator. It's only manifesting in Android 5.1 for me.

 The error is as follows
```
2022-06-26 20:03:02.961 7162-7189/uk.co.adventuregamestudio.agsplayer A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception 'java.lang.NoSuchMethodError' thrown in int org.libsdl.app.SDLActivity.nativeRunMain(java.lang.String, java.lang.String, java.lang.Object):-2
2022-06-26 20:03:02.961 7162-7189/uk.co.adventuregamestudio.agsplayer A/art: art/runtime/check_jni.cc:65]     in call to CallVoidMethodV
2022-06-26 20:03:02.961 7162-7189/uk.co.adventuregamestudio.agsplayer A/art: art/runtime/check_jni.cc:65]     from int org.libsdl.app.SDLActivity.nativeRunMain(java.lang.String, java.lang.String, java.lang.Object)
```

I notice that breakpoints in the native code don't trigger at all when running the agsplayer in this emulated device. In my Android 10 phone, this doesn't happen, and neither in the Android 11 one.

**Comment by ivan-mogilko** [comment]
There's a number of things which changed in agsplayer and runtime app between 3.6.0.17 and 3.6.0.18, the full list of commits is here:
https://github.com/adventuregamestudio/ags/compare/02f236155127c940f9d8dde3fcbd4b54b8a17129...25b93b6953b23c6d533b3b6c8ad2d1497807bf6a

I suspect the interesting commits could be:
57433742492bdd44e26e342ba41a72528df0a7c4
3c986c5504506d9a8cb89c493d5775d45c27c0f6

**Comment by ericoporto** [comment]
In the last commit referenced, the method `checkSelfPermission` was only introduced in [Android 6](https://developer.android.com/about/versions/marshmallow/android-6.0-changes), but by being called through AppCompat it should be correctly handled in some way. So while the error message has no relation to this commit, it may be possible something else with this causes the problem.

**Comment by ericoporto** [comment]
Found the error! I made stuff private that should be protected! lol, making a PR...
