### ISSUE TITLE
Android: improve the touch-to-mouse input control scheme

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1716]
There has been a number of suggestions to change the current control scheme in the past. I've posted one below under spoiler as an example, and more may probably be found around the issue tracker or ags forums (unfortunately they were never gathered into a dedicated ticket).

The point however is that it's desired to have configurable controls for an Android port (or generally - mobile / touch screen controls).

This may be approached from two directions:
1. Design a script API for touch controls and let game authors script their own control scheme. EDIT: there's a ticket for this: #1538.
2. Make default "touch screen - to mouse" controls configurable through a config file (and AGS Player's preferences). This will cover games that don't have a scripted touch controls. For this we'd need to _gather a list of things_ that may require an option (left mouse click, right mouse click, and so on).

This ticket is apparently dedicated to p2.

<details>
  <summary>Following was split out of the #275</summary>

_I was also wondering how I could change the controls, specifically, the two-finger double tap for right clicking. It's a little strange to pull off to be honest and sometimes the object is too small to get 2 fingers on it. Right now I'm struggling to right click these tiny objects in Resonance._

_I'd prefer every mouse control to be able to be executed with a single finger or stylus. SCUMMVM has a very good control system that AGS should consider adopting. Its:_

* _Tap + movement: Mouse movement_
* _Tap without movement: Left mouse button click_
* _Tap held for >0.5s without movement: Right mouse button click_
* _Tap held for >1s without movement: Middle mouse button click_
* _Double Tap + movement: Drag and drop_

_On devices supporting multitouch:_

* _Hold down one finger, tap with second: Right mouse button click_
* _Hold down two fingers, tap with third: Middle mouse button click_

</details>

**Comment by ericoporto** [comment]
Please, let's prioritize #1538 before going this route.

**Comment by i30817** [comment]
What about OS definitions of what is a mouse 'gesture'? For instance, i can configure in GNOME if a two finger click is right click and a 3 finger click a middle click, or setup the bottom zones of the touchpad for that (except middle click anyway).

What happens then, if you introduce highly divergent gestures apis?

**Comment by ivan-mogilko** [comment]
> What about OS definitions of what is a mouse 'gesture'? For instance, i can configure in GNOME if a two finger click is right click and a 3 finger click a middle click, or setup the bottom zones of the touchpad for that (except middle click anyway).

> What happens then, if you introduce highly divergent gestures and touch apis?

I do not fully know how that works, but if there's an OS "layer" that converts one kind of input into another, then it all depends on which system events does the game receive. If OS makes game receive mouse events instead, then the game will act according to how it's scripted to react to mouse events.

**Comment by ivan-mogilko** [comment]
For the reference, there are a number of hints that control SDL2 behavior when it comes to simulating touch and mouse through each other. Some hints are missing in the SDL2 wiki, but their brief description may be found in the source code.
(https://github.com/libsdl-org/SDL/blob/main/include/SDL_hints.h):

* SDL_HINT_TOUCH_MOUSE_EVENTS

https://github.com/libsdl-org/SDL/blob/1fc7f681187f80ccd6b9625214b47db665cd9aaf/include/SDL_hints.h#L1146-L1150

* SDL_HINT_TOUCH_MOUSE_EVENTS

https://github.com/libsdl-org/SDL/blob/1fc7f681187f80ccd6b9625214b47db665cd9aaf/include/SDL_hints.h#L1514-L1522

**Comment by ericoporto** [comment]
I think this either may be closed or can be updated. The suggested control scheme for touch to mouse is in, not sure if it includes all features mentioned.

**Comment by ivan-mogilko** [comment]
Okay, i guess one would need to make a more clear list of suggestions for something to be changed.
