### ISSUE TITLE
AGS 4: remove limits of game objects' script name lengths

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1734]
There are still length limits to the script names of certain game objects. These should be removed and script names either made unrestricted or limited by a larger length (it's desired for that restriction to be uniform among all the objects).

This is primarily a compiled data format / engine issue; after this is fixed in the engine, the editor should be adjusted to comply to the same format.

Known cases:
* AudioClips
* Characters

**Comment by messengerbag** [comment]
AGS 4 also seems like a good time to remove the special treatment of certain "Hungarian notation" initial letters in game object names, e.g. `cName` for characters. (This first letter being stripped from the name in certain contexts, for example in dialog scripts.)

**Comment by ivan-mogilko** [comment]
> AGS 4 also seems like a good time to remove the special treatment of certain "Hungarian notation" initial letters in game object names, e.g. `cName` for characters. (This first letter being stripped from the name in certain contexts, for example in dialog scripts.)

Please, this is a completely different matter, and requires work of different scale. It's best to open a dedicated ticket for this, and plan thoroughly what has to be done.

**Comment by ericoporto** [comment]
Just a note that this should be removed from ags4 milestone and added to the 3.6.1 milestone.
