### ISSUE TITLE
OSX: reimplement right/middle click emulation for 1-button mouse systems

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1740]
There have been a small hack introduced by Janet Gilbert in the past, which simulated right-click on Mac as Ctrl+Left click. The code was temporarily disabled when moving to SDL2 backend:

https://github.com/adventuregamestudio/ags/blob/bf18ba1198308f2afd41559ec9d434cbc0b92606/Engine/ac/sys_events.cpp#L409-L419

Suggestion:
1. Find out if SDL2 itself has methods to work around this Mac limitation, or configure event remap.
2. If not, find a good approach to remap key + mouse combo in the engine.
3. If above requires too much work for 3.6.0 (which is closing final release), restore the old hack under `AGS_SIMULATE_RIGHT_CLICK` and maybe add `AGS_SIMULATE_MIDDLE_CLICK` too.

**Comment by ericoporto** [comment]
SDL2 has a [hint](https://wiki.libsdl.org/SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK) for it, `"SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK"`, it [defaults to false](https://github.com/libsdl-org/SDL/blob/5e654a4bf28f30795f10727df7bec133dde8dfc0/src/video/cocoa/SDL_cocoawindow.m#L300).

Only macOS info I found on using ctrl https://support.apple.com/guide/mac-help/right-click-mh35853/mac
