### ISSUE TITLE
Regression in text display in Whispers of a Machine

### ISSUE THREAD

**Issue by criezy** [adventuregamestudio/ags#1742]
**Describe the bug**
The text in Whispers of a machine is not displayed correctly in some places. This was discussed in PR #1705.

**AGS Version**
Current code from master (commit c31e55c69db5356d6d22e80f05f2e5a9d6425f67).

**Game**
Whispers of a Machine
https://store.steampowered.com/app/631570/Whispers_of_a_Machine/

**To Reproduce**
1. Start the game
2. Watch the intro
3. See error

**Expected behavior**
Correct text display (see images below).

**Screenshots**

Correct:
![](https://user-images.githubusercontent.com/552105/180294140-0b44ff3f-5e90-4a0e-8cc8-bde21e8fbe9b.png)

![](https://user-images.githubusercontent.com/552105/180296053-f30ac62f-365c-461a-9edc-1013e5e4f78b.png)

Incorrect:
![](https://user-images.githubusercontent.com/552105/180294276-bd62bf81-73ff-467b-ad8d-e4b0701fa4d8.png)

![](https://user-images.githubusercontent.com/552105/180296095-7dfef9f8-0563-4706-a9f1-ea093d2c0d01.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.6

**Additional context**
The screenshot above are from ScummVM where the text used to be displayed correctly. A git bisect points to https://github.com/scummvm/scummvm/commit/df29806aec718c81dfbae08e664e6a47ad76d545.

This was a backport of commit d9c4a0306a6718cb03ccd6e84c1e63d093d9a64a
Engine: replaced the remaining wgettextheight() with get_font_height()

The AGSSpriteFont plugin was not working for WOAM before PR #1705 was merged, so I did not try to check in AGS if it indeed worked before that commit (it probably wasn't). But since the behaviour we get is the same in AGS and in ScummVM I am guessing the issue in AGS has the same root cause as in ScummVM and is related to the change to the font height.

**Comment by ivan-mogilko** [comment]
I just have an idea; this change in d9c4a0306a6718cb03ccd6e84c1e63d093d9a64a makes engine use a precomputed font height instead of calling Renderer each time. It *might be* that either it does not compute correctly for the Renderers provided by plugin, or it does not recompute when the plugin replaces the font's renderer following a script command.

**Comment by criezy** [comment]
I am guessing that the issue is actually due to the font height no longer depending on the text. The Clifftop Games version of AGSSpriteFont plugin does some interesting things to compute the font height, and it depends on the text 😉 
https://github.com/adventuregamestudio/ags/blob/c31e55c69db5356d6d22e80f05f2e5a9d6425f67/Plugins/AGSSpriteFont/AGSSpriteFont/VariableWidthSpriteFontClifftopGames.cpp#L16-L37

**Comment by ivan-mogilko** [comment]
Hm, I see, so the plugin was abusing a secret knowledge of which strings the older engine pass to learn the font height in very specific circumstances...

**Comment by ivan-mogilko** [comment]
Need to consider the options here, but I'd rather find a way to not rely on hacks, which might mean - carefully expanding AGSFontRenderer interface to let engine find out more about what it does: such as get custom linespacing, and so forth.

**Comment by ivan-mogilko** [comment]
@criezy opened an experimental pr: #1744
