### ISSUE TITLE
Whispers of a machine foresensic scanner and other abilities have text offset from the container box

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#1750]
**Describe the bug**
font rendering is offset for this abilitity

**AGS Version**
$ ags --version
Adventure Game Studio v3.6 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2022 others
ACI version 3.6.0.33

**Game**
Whispers of a machine, don't know if it has a non-steam demo

**To Reproduce**
1. start the game
2. go through the 3 conversation responses
3. click on the square button on the lower right
4. drag it over the blood, wait.

**Screenshots**
![image](https://user-images.githubusercontent.com/757900/183256971-d9e0bd63-9a33-4907-92c8-ae259da953d9.png)

**Desktop (please complete the following information):**
`Linux sleipnir 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by AlanDrake** [comment]
Has Whispers of a machine ever worked correctly on vanilla engine? I remember it was one of those games using the unsupported precursor to custom resolutions.
I also remember another case of misplaced text for Primordia, but in that case it seems it was due to a missing .TMP file, not sure if it applies to this case.

**Comment by i30817** [comment]
It was recently fixed with the fonts rendering problems, so i was wondering if i was missing something.

**Comment by ivan-mogilko** [comment]
> It was recently fixed with the fonts rendering problems,
To clarify, the engine you are running is with the fixed sprite fonts plugin already (so other texts look fine)?

**Comment by i30817** [comment]
first question, yes, i just built it.

second question yes, but i _believe_ the screenshot shows another defect, the words appear to be too spaced out for the area... i think.

It's not a regression - it was always like this for as long as this game worked (i had the plugin necessary as a .so in the game dir, deleted for this test of course).

**Comment by ivan-mogilko** [comment]
After some testing: 3.5.1 engine has the same horizontal offset issue, but correct linespacing.

**Comment by ivan-mogilko** [comment]
The linespacing is fixed with d94f20742284ea75abbde86905159c490a7b4d46 , I got the meaning of the special parameters wrong first time; had to look into the custom engine sources to double check how these were used.

**Comment by ivan-mogilko** [comment]
Okay, I found what's wrong. Woam's custom engine supported Label.TextAlignment property before it got supported by the official engine, but they used older constant ranges, and so the values were interpreted incorrectly by the newer engine.

Pushed a fix: 46fc9bac4fa6082561a1937861b3e567ccea2cd4

**Comment by i30817** [comment]
fixed
