### ISSUE TITLE
Internal Console past lines can be altered

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1755]
**Describe the bug**
When testing my new logger, I noticed in some cases the internal ags console had a history that was replaced.

**AGS Version**
Reproducible in 3.6.0.34 but also current master (https://github.com/adventuregamestudio/ags/tree/8bbdbd2d1e88ced0a58507d8a998cb033addcab4)

**Game**
[Log_Bug.zip](https://github.com/adventuregamestudio/ags/files/9390401/Log_Bug.zip)

**To Reproduce**
Create a new game from Sierra Template, and add an on-click function to the Orb
```AGS Script
function hGlowingOrb_AnyClick()
{
  System.Log(eLogInfo, "mouse is clicking at: %d, %d", mouse.x, mouse.y);
}
```

or load the attached project.

1. use the  \` character to show the internal console
2. Click on different places of the orb
3. See the log history be modified

**Expected behavior**
The past log be kept.

**Screenshots**
![mouse_log_hist_bug](https://user-images.githubusercontent.com/2244442/185820147-a8b69f72-9968-4614-9db4-ce5d524fb45d.gif)

**Desktop:**
 - OS: Windows
 - Version 10

**Additional context**
I found that the following change does fix the problem, but I wasn't sure if the previous way was done so for performance in some way.

```patch
diff --git a/Engine/debug/consoleoutputtarget.cpp b/Engine/debug/consoleoutputtarget.cpp
index 2442e9533..00962fead 100644
--- a/Engine/debug/consoleoutputtarget.cpp
+++ b/Engine/debug/consoleoutputtarget.cpp
@@ -31,7 +31,8 @@ void ConsoleOutputTarget::PrintMessage(const DebugMessage &msg)
 {
     // limit number of characters for console
     // TODO: is there a way to find out how many characters can fit in?
-    debug_line[last_debug_line] = msg.Text.Left(99);
+    debug_line[last_debug_line].Empty();
+    debug_line[last_debug_line].Append(msg.Text.Left(99));

     last_debug_line = (last_debug_line + 1) % DEBUG_CONSOLE_NUMLINES;
     if (last_debug_line == first_debug_line)
```

**Comment by ivan-mogilko** [comment]
This is a problem with wrapping a static char-buffer using String::Wrapper in `Sc_System_Log`. Wrapped string is shared on assignment, and when the buffer is modified, obviously it does not tell the Strings (since there's no connection), and all the strings that reference this wrapped buffer get changed as well.

**Comment by ivan-mogilko** [comment]
Pushed 588d91ab6a09877eab06bf66073239db0d28271b.

**Comment by ericoporto** [comment]
@ivan-mogilko that fixed for me!
