### ISSUE TITLE
Selecting element using properties combobox no longer changes selected element for properties panel

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1760]
**Describe the bug**
In the GUI Editor, selecting elements from a GUI in the combobox that is on top of the properties panel in the editor, doesn't change the actually selected GUI Control. This also happens in other panes - in the Room Editor, selecting an object in the combobox won't change the selected object.

**AGS Version**
in 3.6.0.31 and onwards, but 3.6.0.30 didn't have this issue. In my tests, it started in this commit: https://github.com/adventuregamestudio/ags/commit/19d54e4d9275155799c28ed590baf9ff1b767edd

**To Reproduce**
1. Create a blank game with the sierra template
2. In Explore Project -> GUIs -> click `gIconbar`
3. In the combobox in the properties pane, select `btnIconInteract`
4. See that the properties grid still points to `gIconbar`

**Expected behavior**
The newly selected `btnIconInteract` should be selected in the GUI Editor (with the red dots) and it should appear in the properties grid.

**Screenshots**
![image](https://user-images.githubusercontent.com/2244442/188236595-c4b1e612-aebc-4850-8b93-d4251fec0e29.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Originally reported here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=59842.msg636649410#msg636649410

**Comment by ivan-mogilko** [comment]
Important condition: apparently this only occurs if you have a non-default color theme enabled in the Editor.
This is also the reason why I was not able to reproduce this earlier.

**Comment by ericoporto** [comment]
Ah, I found the issue I think:

https://github.com/adventuregamestudio/ags/blob/5742cda12958e9eb4138e246d958d48bfff8b419/Editor/AGS.Editor/GUI/PropertiesPanel.cs#L80-L82

Once the control is removed and added back, all events are lost it seems.

**Comment by ivan-mogilko** [comment]
There were other problems with this custom combo box in the past.

If I remember correctly, you have to amend its constructor, where it copies all the necessary properties from the default combobox. Probably events have to be remapped as well.

**Comment by ericoporto** [comment]
> If I remember correctly, you have to amend its constructor, where it copies all the necessary properties from the default combobox. Probably events have to be remapped as well.

Tried this approach of remmaping events and it fixed!

```diff
diff --git a/Editor/AGS.Editor/ColorThemes/Controls/ComboBoxCustom.cs b/Editor/AGS.Editor/ColorThemes/Controls/ComboBoxCustom.cs
index c41dcb7fe..554fa650b 100644
--- a/Editor/AGS.Editor/ColorThemes/Controls/ComboBoxCustom.cs
+++ b/Editor/AGS.Editor/ColorThemes/Controls/ComboBoxCustom.cs
@@ -1,5 +1,6 @@
 ﻿using System.Drawing;
 using System.Drawing.Drawing2D;
+using System.Reflection;
 using System.Windows.Forms;

 namespace AGS.Editor
@@ -25,6 +26,10 @@ namespace AGS.Editor
             Size = original.Size;
             TabIndex = original.TabIndex;

+            var eventsField = typeof(System.ComponentModel.Component).GetField("events", BindingFlags.NonPublic | BindingFlags.Instance);
+            var eventHandlerList = eventsField.GetValue(original);
+            eventsField.SetValue(this, eventHandlerList);
+
             BeginUpdate();
             foreach (var i in original.Items)
             {
```

**Comment by ivan-mogilko** [comment]
> I think it's because we change the theme at load, after the events have been set (in the constructor, which happens before frmMain proceeds to the line where the event handler is added).

Yes, but I mean, if the custom combo box would be created right on form, then we would not have to clone it, and just apply a theme style to already created one.

**Comment by ericoporto** [comment]
Uhm... You mean, instead of using regular combobox, always using ComboBoxCustom, and have it be able to either be styled or not, so we don't need to switch between two combobox at runtime? I don't know how to read the non-theme color so it uses that instead.
