### ISSUE TITLE
Support importing indexed png, with fewer than 256 colors, as mask in room editor

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1768]
**Describe the problem**
When editing masks in my image editor (Aseprite), I would like to work with indexed png images since they are much smaller than bitmap. 

Problem is I really would prefer to just have as many colors as I need in my palette before importing, instead of having to hold a 256 color palette - also because by default it loads with a 32 color palette. 

**Suggested change**
I would like to 
- support importing png images as rooms masks in the editor
- allow these png images to contain less than 256 colors
  - possibly ags should replace whatever palette the png had before with it's own right after import

Allow import of png files can be done by replacing the `MASK_IMAGE_FILE_FILTER ` in `Editor\AGS.Types\Constants.cs` with the one below

```C#
public const string MASK_IMAGE_FILE_FILTER = "All supported images(*.bmp; *.png)|*.bmp;*.png|Windows bitmap files (*.bmp)|*.bmp|Portable Network Graphics (*.png)|*.png";
```

The palette change is a bit trickier and I don't know how to implement

**Comment by ivan-mogilko** [comment]
Please note that ags4 already works with mask pngs.

**Comment by ericoporto** [comment]
> Please note that ags4 already has room masks as pngs, in the open room format.

Yes, and this lowers any priority on this. But ags4 still only imports bmp files in the editor interface. I just wanted to close the old bug to lower the confusion.

**Comment by AlanDrake** [comment]
PNGs already work for import, they just need to be added back to the dropdown.
But yeah, AGS should stop trying to read the full 256 indexes, completely disregarding the actual palette size, and just process as many colors as available in the imported image.
Also it should release the handle on the imported file once its done with it, but maybe this is just an issue for AGS4, I'm not sure.

**Comment by AlanDrake** [comment]
Alright, after some investigations only ags4 needs the fix for palettes, as 3.6 is already disregarding the imported one.
Do we need to target 3.6 for png import or can I just do everything for 4?

**Comment by ericoporto** [comment]
I think it's alright to do it for ags4, 3.6.0 is too close to release.

**Comment by ericoporto** [comment]
I am closing this since it is solved by the PR, but need to write down a new one specific to the transparency/alpha/tRNS chunk stuff.
