### ISSUE TITLE
New compiler: invalid instruction when performing assignment in function parameter

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1775]
**Describe the bug**
The new compiler is not reporting invalid variable assignments when they are function parameters.

**AGS Version**
Ags4 with extended compiler

**To Reproduce**
```
	bool toggleFPS = false;
	Debug(4, toggleFPS = !toggleFPS); // Ctrl-F, fps
```
No compiler error will be thrown, but the engine will stop with the following message:
`Error (line XXX): invalid instruction 16777214 found in code stream`

**Expected behavior**
The following error should be thrown at compile:
`Error (line XXX): Invalid use of operator '!'`
Similar to what happens when performing the same with an if()

**Comment by fernewelten** [comment]
I'm on it.

**Comment by AlanDrake** [comment]
Seems to be working fine so we can close this 👍
