### ISSUE TITLE
Preprocessor: Uncaught unterminated strings

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1777]
**Describe the bug**
Unterminated strings are compiled without errors.
The fact that they aren't caught will cause unpredictable outcomes when creating or updating translations, and numbering speeches.

**AGS Version**
All versions, including new compiler.

**To Reproduce**
```
player.Say("This line should throw an error.");"
// starting from here code will be inserted into translations instead of actual string
```

**Expected behavior**
An error about an unterminated literal should be thrown instead of being swept under the rug.

**Notes**
I remember we had discussed this very issue ages ago, about translation breaking due to similar circumstances, but I can't find a ticket.

**Comment by fernewelten** [comment]
I strongly suspect that this is a problem of the Editor (!) that calls the respective compilers, not of the compilers. For instance, it might happen at program preprocessing time (where the comments are removed).

The new compiler catches a missing `"` character right at the new line that terminates the first line of the string.  I've just checked this.  So the compiler must be fed a program where the trailing `"` has already been removed.

**Comment by AlanDrake** [comment]
I'm looking into this as soon as I have time. I'll find out what the preprocessor is doing and implement some kind of alert for operations that operate on the project's string.
Whatever they're doing it shouldn't be too hard to check for a raw newline in the middle of the scripts.

**Comment by ivan-mogilko** [comment]
The making of a translation file does not use compiler at all, it has its own code afaik.
