### ISSUE TITLE
mouse.x and mouse.y can be outside the game window in Ubuntu 16.04

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1791]
**Describe the bug**
I was just testing AGS current master in Ubuntu 16.04, and my game was crashing for null pointer in a point, when using `Point* rp = Screen.ScreenToRoomPoint(mouse.x, mouse.y);` in AGS Script.

Adding a breakpoint in the line below, led me to figuring out `mouse.x' was negative, when I moved it at left at the screen.

https://github.com/adventuregamestudio/ags/blob/44e304ff65c3beaf785ab8820e5b27cf360c2437/Engine/ac/screen.cpp#L158

**AGS Version**
Current master (https://github.com/adventuregamestudio/ags/commit/44e304ff65c3beaf785ab8820e5b27cf360c2437).

**Expected behavior**
I expected mouse.x and mouse.y to always be restricted to the game window bounds.

Now, *I am **not** 100% this has always been the expected behavior* or if this is the behavior everywhere, but I was under the impression it was. It's possible also that I am hitting some upstream bug in SDL2 instead, since this is a relatively old OS, and it's currently unsupported.

If it's the expected behavior, than the fix can be something like

```C++
    scmouse.x = Math::Clamp(game_to_data_coord(mousex), 0, gfxDriver->GetNativeSize().Width);
    scmouse.y = Math::Clamp(game_to_data_coord(mousey), 0, gfxDriver->GetNativeSize().Height);
```

in 

https://github.com/adventuregamestudio/ags/blob/44e304ff65c3beaf785ab8820e5b27cf360c2437/Engine/ac/mouse.cpp#L352-L355

**Additional context**

In the manual for [Screen.ScreenToRoomPoint](https://github.com/adventuregamestudio/ags-manual/wiki/Screen#screenscreentoroompoint), it mentions

> The restrictToViewport parameter tells what to do if no viewport is found under the cursor. If it's false, then in such case the conversion will be done through the primary viewport. **If it's true, then this function returns null if no viewport is there**. The default is false.

So I expected it to never be null, unless that parameter was true, but I did not consider the case the coordinates were outside of screen bounds.

**Desktop:**
 - OS: Ubuntu
 - Version 16.04

**Comment by ivan-mogilko** [comment]
Clamping the mouse is one thing, but Screen.ScreenToRoomPoint() with restrictToViewport = false should not return null regardless of mouse coordinates. Is it possible to double check that it returns null if you pass e.g. -1, -1?

**Comment by ericoporto** [comment]
I tried the following in Windows

```AGS Script
function room_AfterFadeIn()
{
  int mx = -100; 
  int my = 1;
  Point* p = Screen.ScreenToRoomPoint(mx, my);
  if(p == null) {
    Display("Screen.ScreenToRoomPoint(%d, %d) == null", mx, my);
  } else {
   Display("Screen.ScreenToRoomPoint(%d, %d) == Point(%d, %d)", mx, my, p.x, p.y);
  }
}
```

And it worked as expected, no null. 

![image](https://user-images.githubusercontent.com/2244442/192122389-12ac9b66-3e2f-4263-88ed-c756a7c12532.png)

I then tried.

```AGS Script
void repeatedly_execute_always()
{
  int mx = -100; 
  int my = 1;
  Point* p = Screen.ScreenToRoomPoint(mx, my);
  if(p == null) {
    Display("Screen.ScreenToRoomPoint(%d, %d) == null", mx, my);
  }
}
```

And it never displayed... In the game I was playing around in Ubuntu, I had [Multitasking mode](https://github.com/adventuregamestudio/ags-manual/wiki/Globalfunctions_General#setmultitaskingmode) turned on. I tried to turn it on, in Windows, but it did not affect anything. I will test things again in Linux later.

**Comment by ericoporto** [comment]
so, weird problem, I am back at the Ubuntu 16.04 computer, I had turned it off yesterday after writing the top ticket and turned on it today. The computer is behaving a little different.

First the mouse.x and mouse.y boundary issue, it only happens if I move the mouse close to the game border, then click and old the left click with it inside the game window, then I can move it outside the window boundaries. The fix mentioned above does prevent it.

Now for the Screen.ScreenToRoomPoint issue, about the line in [`Engine/ac/screen.cpp`](https://github.com/adventuregamestudio/ags/blob/44e304ff65c3beaf785ab8820e5b27cf360c2437/Engine/ac/screen.cpp#L158). In my new test game, it doesn't ever return null.

But, when I try the old game, which is made with 3.5.0.20, I can still cause the issue. So I tried to debug again and I noticed in the old game, `restrict` is true.

![image](https://user-images.githubusercontent.com/2244442/192145564-985c2411-a193-4969-978e-5f3729253754.png)

But because the Script API reads like this
https://github.com/adventuregamestudio/ags/blob/44e304ff65c3beaf785ab8820e5b27cf360c2437/Editor/AGS.Editor/Resources/agsdefns.sh#L3069-L3073

I thought the default value in old games was also false, but from above, it's actually true. So I think I just wasn't interpreting correctly what was the default value in previous versions.

**Comment by ivan-mogilko** [comment]
For Screen.ScreenToRoomPoint expected behavior is:

* Script API v36026 and above: restrictToViewport parameter is available and default value is false;
* Script API before v36026: restrictToViewport parameter is not available and default value internally is true (always restrict);

**Comment by ericoporto** [comment]
I am thinking that there's a chance the mouse working as is, is a behavior change in SDL 2.0.22, [from it's wiki](https://wiki.libsdl.org/SDL_CaptureMouse)

> While captured, mouse events still report coordinates relative to the current (foreground) window, but those coordinates may be outside the bounds of the window (including negative values).

And then later it mentions

> Please note that as of SDL 2.0.22, SDL will attempt to "auto capture" the mouse while the user is pressing a button; this is to try and make mouse behavior more consistent between platforms, and deal with the common case of a user dragging the mouse outside of the window.

Noticeable, despite the notice, the behavior isn't consistent at all, since it's not what I am seeing on Windows. I need more experiments to check if this is an upstream regression.

It looks like this new behavior could be prevented using `SDL_HINT_MOUSE_AUTO_CAPTURE` set to 0.

**Comment by ivan-mogilko** [comment]
The original ags behavior was to disable cursor movement completely (not react to mouse updates) when it's away from the window.

**Comment by ericoporto** [comment]
I verified the following does work! It gives the following behavior, the mouse cursor can leave the window, but the in-game cursor remains inside, and follow along, if you have the mouse button down, but since it's grabbed by the window, the OS cursor doesn't show up, and the perception is the mouse is locked down in-game, as you release the left click, the OS cursor reveals itself. You don't have the mouse button down, then the follow along behavior is obvious as the os cursor is visible. I think this is a safe default behavior that won't feel weird in a future where #1686 lands.

Had to cast as int because the volatile qualifier caused a compilation error.

```diff
diff --git a/Engine/device/mousew32.cpp b/Engine/device/mousew32.cpp
index 51047c9..aeb8176 100644
--- a/Engine/device/mousew32.cpp
+++ b/Engine/device/mousew32.cpp
@@ -101,8 +101,8 @@ void mgetgraphpos()
     else
     {
         // Save real cursor coordinates provided by system
-        real_mouse_x = sys_mouse_x;
-        real_mouse_y = sys_mouse_y;
+        real_mouse_x = Math::Clamp((int) sys_mouse_x, Mouse::ControlRect.Left, Mouse::ControlRect.Right);
+        real_mouse_y = Math::Clamp((int) sys_mouse_y, Mouse::ControlRect.Top, Mouse::ControlRect.Bottom);
     }
 
     // Set new in-game cursor position
```

**Comment by ericoporto** [comment]
I can reproduce this in MacOS too. :/
