### ISSUE TITLE
Scaling of DrawingSurface.DrawImage to resolution of game

### ISSUE THREAD

**Issue by hbg11** [adventuregamestudio/ags#1795]
Currently many (all from what others have told me) AGS games seem to have the sprites scale to smaller pixels than pixel size of the resolution of the game (e.g. 320x180) as the character walks into the distance etc. This looks awkward and breaks the pixel effect.

I don't see an option in DrawingSurface.DrawImage to scale to such a resolution, and ideally align with the game's pixels. Is there some way to do it? Even just nearest neighbor would be an improvement I think for an authentic oldschool effect.

Which leads me to another question. I'm not sure if I'm mistaken, but it seems like some games have other things (lighting effects maybe) that are at too high of a resolution. Maybe there could be a user option to force scale the whole screen to the game resolution (resample it before displaying a frame)?

Sorry if I am misunderstanding the state of things, I am entirely new to AGS.

**Comment by ericoporto** [comment]
Could you clarify what are you trying to achieve? 

DrawingSurface.DrawImage is for when you are using AGS Script to create you own in game dynamic sprites or painting something in an existing Drawing Surface.

But your description is more like you have turned `render_at_screenres` off in winsetup.

**Comment by hbg11** [comment]
Ahah, that must be it. I noticed the issue is not happening on my Mac. I'm just a player/user. I did have that set on Windows, I'm not sure if the game shipped that way or if I had set that. I probably set it. Thank you.

**Comment by hbg11** [comment]
It was shipped like that by the developer. Apparently other users have seen this in other games. Not your problem, thanks for your time.
