### ISSUE TITLE
CI: Uncaught errors in uploading artifacts

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1801]
**Describe the bug**
The upload can fail as follows, but it won't be marked as a error:
"build_android" > "Upload proj artifacts"
```
Uploading 2 artifacts for /tmp/cirrus-ci-build/AGS-*-android-proj-*.zip
Uploaded /tmp/cirrus-ci-build/AGS-3.99.100.0-android-proj-debug.zip
Uploaded /tmp/cirrus-ci-build/AGS-3.99.100.0-android-proj-release.zip
Error from upload stream: rpc error: code = Unknown desc = 
```
Example from: https://cirrus-ci.com/task/4869075909214208

Is it possible to report the task as failed in such cases?

**Comment by morganwillcock** [comment]
I don't think there are any explicit options. If one of the instructions fails then I think the design is to automatically fail the task, so perhaps it is a temporary issue on the provider's side.

How large are the files? Apparently the upload limit is 1GB, but I don't know whether that is cumulative in some way.

**Comment by AlanDrake** [comment]
In this case the file was around 13mb.
I don't know how the CI works, but if that error up there is not detectable for some reason, maybe there could be another task at the end to chack that files have been actually uploaded.
It does happen rarely, but when it happens it's impossible to rerun because the failing task is a later one.

**Comment by ericoporto** [comment]
I opened a question with them about it. But that is an error in the go client used, the error message should have an error reason, but that's empty. I am taking a look at their code, but that will take a bit. Also opened a discussion question there: https://github.com/cirruslabs/cirrus-ci-docs/discussions/1075

I don't think an additional task is a good approach.

**Comment by ericoporto** [comment]
I think this can be closed as it seems it was an upstream bug that has disappeared for the time being. If/when it comes back we can reopen but it's really more a support task for the CI we are using. There's no task from us right now.

**Comment by AlanDrake** [comment]
Alright, fingers crossed.
