### ISSUE TITLE
AGS 4: Remove "has alpha channel" flag from sprites, and drawable objects

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1808]
In AGS sprites have a "has alpha channel" flag which tells whether the image's alpha channel should be used or not. Certain drawing operations depend on it; for instance a blending op or conversion from the sprite to texture may be performed in one or another way depending on the combination of source and destination surfaces' alpha flags.

My proposal is to remove this flag and those checks altogether, and imply that 32-bit images always have a valid alpha channel. This should somewhat simplify all the drawing operations.

If necessary, the flag may remain in sprite import settings; in such case removal of an alpha channel from a 32-bit source image would correspond to filling alpha bytes with 0xff (fully opaque).

**Comment by ericoporto** [comment]
Hey, does this need some form of project upgrade to work, when loading an existing project, or nothing is necessary to change in the project part?

**Comment by ivan-mogilko** [comment]
The consequences of this would be that the 32-bit images with "magic pink" color would have to be converted on import or load from file (right now this is done when converting to texture).

**Comment by ivan-mogilko** [comment]
Resolved by #1813
