### ISSUE TITLE
AGS 4: missing dynamic library in the editor's installer

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1817]
Recent builds of AGS 4 (editor) seem to require an extra file called `WeifenLuo.WinFormsUI.Docking.ThemeVS2015.dll`. But they are missing in the installer; present in the zip archive though.

Is this file substituting WeifenLuo.WinFormsUI.Docking.dll or Editor has to have both?

In any case it has to be added to installer.

**Comment by AlanDrake** [comment]
Both, and in future versions of DockPanel there might even be one more because they split the default vs2005 theme into a separate dll, IIRC.
