### ISSUE TITLE
Editor: Android config is not fully represented in game project, file is overwritten with defaults

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1819]
**Problem**

When making an Android build from within the editor, the most of the `android.cfg` contents are always reset to defaults, without any means to change these values. Editor does not have them present anywhere in settings, and because it's overwritten each time when the game builds, user cannot even edit the file manually (all changes will be lost). This makes it practically impossible to edit all options in this file.

On an extra note, the new "mouse emulation" settings are not represented in Default Setup at all, and because acsetup.cfg is recreated from scratch each time, it's also not possible to edit it and add wanted setting.

NOTE: the latter, imo, is a sign of another potential issue: the user cannot have any custom settings in config. I think this was changed only in 3.6.0 (but I could be wrong).

**Expected behavior**

Each config option should have a corresponding property in the game project. If it's more convenient to take existing settings from Default Setup (also duplicated in acsetup.cfg), then this may be done. If not, then new properties should be added specifically for Android.

In regards to the config file being reset each time, I suppose we could also have a setting that tells whether to reset it or not, because otherwise users won't be able to add anything there if they like or need to (e.g. if the game wants to read custom options from the config). In theory this could also be solved by adding special field for adding config contents, but that's more work, and may be left for the future updates.

**Comment by AlanDrake** [comment]
I think we made it reset some time ago because changes to default settings were not ending up being written in the cfg.
The real problem here are the missing defaults options, and maybe a comment added inside the cfg to warn that the file will be overwritten on compile.

**Comment by ericoporto** [comment]
At least the touch options are relevant for the Web Build too, so I think I want everything that can be set in Android be possible to set in Default Setup too.

If representing everything from Android in Default Setup is an ok resolution of this, I can probably implement a PR for this soon - and this can be assigned to me.

**Comment by ericoporto** [comment]
I think in the future we may want to have it be possible to configure either a global DefaultSetup, and then per platform either inherit whatever is the global or customize particular settings per platform. I am not sure how to do this UI wise in a way that is natural with the WindowsForms property grid we use.

**Comment by ivan-mogilko** [comment]
> At least the touch options are relevant for the Web Build too, so I think I want everything that can be set in Android be possible to set in Default Setup too.

Could you clarify, which options are used in web build?

**Comment by ivan-mogilko** [comment]
> I think we made it reset some time ago because changes to default settings were not ending up being written in the cfg.
The real problem here are the missing defaults options, and maybe a comment added inside the cfg to warn that the file will be overwritten on compile.

Hm, I found I was the one who made that change, but unfortunately I haven't noted the reason in the commit description: b070c8998d39037dafe716a22ab58bb22ad96e18

Maybe this was to remove deprecated options when the project is upgraded.

**Comment by ivan-mogilko** [comment]
In regards to this ticket, following are recent changes:
197e1b2b6dc614043be521f18747ebf71ee4a2b1
9f50b653d5984f7d52b31a1dc570abf6360a0919
fb6a124d7b11ddc1512a3e983d179eee628b87f3

So now there are some options related to the touch controls. And also the default values for options that are not in the editor are not getting overwritten if some values were already present (this is achieved by reading values from config first).

**Comment by ericoporto** [comment]
> Hm, I found I was the one who made that change, but unfortunately I haven't noted the reason in the commit description: https://github.com/adventuregamestudio/ags/commit/b070c8998d39037dafe716a22ab58bb22ad96e18

Looking at the change above, before the config that was set in Default setup would still overwrite the lines from acsetup.cfg it just would not remove the lines that were not set there

**Comment by ivan-mogilko** [comment]
I think this may be closed in the context of 3.6.0. Later it's best to investigate the existing situation again and write down a new task if something has to be done.
