### ISSUE TITLE
Access to number of views from Plugin / Scripts

### ISSUE THREAD

**Issue by WallucePinkham** [adventuregamestudio/ags#1829]
**Describe the problem**
I would like to be able to tell the number of loops a view has from a c++ plugin.

**Comment by ericoporto** [comment]
You can use `GetScriptFunctionAddress` to call things from the script API, this is a commit, but should give some idea how to use it: https://github.com/adventuregamestudio/ags/commit/db0561e5e839ecd70504b24dd1e27d456e676f78.

I think you should be able to just use [`Game.GetLoopCountForView(int view)`](https://adventuregamestudio.github.io/ags-manual/Game.html#gamegetloopcountforview), by leveraging GetScriptFunctionAddress.

**Comment by WallucePinkham** [comment]
Thanks!

This is exactly what I needed. The only question I have is: How do I 
know that the name of the function I should be looking for is 
"Game::GetLoopCountForView^1"?

If I hadn't looked at the source code, I would never have guessed that:
* I had to use :: instead of . and
* I had to append ^1 to the end.

Did I miss somewhere where this is documented?

**Comment by ivan-mogilko** [comment]
I don't remember if how the function names are called is exactly documented somewhere; if not, then we may add this information to plugin article in the manual.

In regards to "^1" part, iirc that is necessary only if there are multiple variants of the same script function with different number of arguments. In other cases the "^N" may be omited.

**Comment by ivan-mogilko** [comment]
@WallucePinkham I added an explanation on how the function names are formed here:
https://github.com/adventuregamestudio/ags-manual/wiki/EnginePluginRun-timeAPI#iagsenginegetscriptfunctionaddress
(this is our manual's source text)

**Comment by WallucePinkham** [comment]
Thanks so much! That’s really helpful!Regards,Walluce PinkhamOn 25 Nov 2022, at 14:41, ivan-mogilko ***@***.***> wrote:﻿
@WallucePinkham I added an explanation on how the function names are formed here:
https://github.com/adventuregamestudio/ags-manual/wiki/EnginePluginRun-timeAPI#iagsenginegetscriptfunctionaddress
(this is our manual's source text)

**Comment by ivan-mogilko** [comment]
I guess this may be closed as resolved.
