### ISSUE TITLE
New compiler: Check the `LINENUM` pseudo-directives, too

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1836]
**Describe the problem**
The new compiler features around 120 googletests that check exactly what bytes are generated for specific short example programs. But line number generation is switched off in these tests, so they __don't__ check what `LINENUM` pseudo-directives are generated. 

We've already encountered a situation where such directives were missing in real code, and the existing googletests hadn't flagged that (#1832).

**Suggested change**
Turn on line numbers for the bytecode googletests. Check whether all the `LINENUM` directives are generated in the tests we already have.

**Comment by ivan-mogilko** [comment]
Resolved by #1886
