### ISSUE TITLE
Grandma Badass savegame crash

### ISSUE THREAD

**Issue by arrowgent** [adventuregamestudio/ags#1841]
**Describe the bug**

loading savegame crashes AGS

**AGS Version**
Include version of AGS used. If compiled from source, please include a changeset.
3.6.0.35 beta 15
https://github.com/adventuregamestudio/ags/releases/tag/v.3.6.0.35

**Game**
If applicable, link or attach an example game (with optional source) to demonstrate the issue.
https://store.steampowered.com/app/1606640/GrandMa_Badass__a_crazy_point_and_click_adventure/

**To Reproduce**
1. load save game

**Expected behavior**
save games loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/57545549/205452988-02215e50-799d-4018-a4e1-7a56429956a6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS] windows
 - Version [e.g. 10]

**Additional context**

this was reported for another user/owner of the game. (not myself)

**Comment by morganwillcock** [comment]
I don't think saved games are guaranteed to be compatible when the Engine is switched for a newer one.

Presumably this works?
1. Create a new saved game
2. Load the saved game that was just created

**Comment by AlanDrake** [comment]
Is it really an Engine issue and not because the game was updated and the script count is now different?

**Comment by ivan-mogilko** [comment]
> I don't think saved games are guaranteed to be compatible when the Engine is switched for a newer one.

3.6.0 engine supports saves made by older engines starting from at least AGS 3.2.1.

But here the problem is likely that the game was changed and the save is no longer compatible with the game. This is a typical issue with AGS games, and not something that we may fix easily in the engine, and rather something that game developers should address on their own for the time being.

For the reference see: #1400

**Comment by arrowgent** [comment]
there might have been a game change (update patch), the engine is unlikely changed version (3.6.0.35)

**Comment by ivan-mogilko** [comment]
It's best to discuss this with the game author, although I doubt that they will be able to do anything if they did not prepare for this kind of situation beforehand.
