### ISSUE TITLE
GlobalMessages are no longer accessible but remain in the game data

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1854]
Global Messages were an array of 1000 strings, indexed from 0 to 999, that could be edited in the pre-3.* editors, and compiled into the game data. In the game script they may be displayed as a speech or text overlays using functions like DisplayMessage and DisplayMessageAtY.

The manual mentions about them in "Upgrade to AGS 3.0 article":
https://adventuregamestudio.github.io/ags-manual/UpgradeTo30.html

> Global Messages are no longer supported and should be considered obsolete -- there's really no need for them now that the interaction editor has gone. Any global messages that you had will be retained and will still work, however the AGS 3 editor provides no way to edit them.

When upgrading an older (pre-3.*) game these messages stay in data (in Game.agf), and are still compiled into the game if present. They may be completely removed using "File -> Remove Global messages" command. Unfortunately, Editor does not provide any means for copying or otherwise converting these messages into some supported form, like an array in script, or Global Variables, which is clearly an oversight in the upgrade process. This leaves users with either having to leave them as-is forever after upgrade, or manually recreating them in a script.

There may be few potential solutions to this, such as:
* Enable editing Global Messages again in the contemporary editor (at least in ags3 branch). For instance, Room Messages are still editable, even though they are considered to be deprecated. This would likely require a simple list view with editable indexed entries (see Room Messages dialog for example).
* Provide an option (e.g. a menu command) for moving these options into a script. For example, create a String array of 1000 elements in the global script and assign in "game_start". After they are converted to script, the messages are removed from Game.agf.

PS. For the reference, there's a somewhat similar game upgrade issue: #946

**Comment by messengerbag** [comment]
AGS 3.0 came out in 2008, almost 15 years ago. Upgrading a game project from before that era (and not just to upgrade to the latest engine, but to continue editing it) seems like such a niche use case that I would question whether it is worth adding any support for in the editor. In the last ten years, we've had a total of **two** people asking about it.

To me, the appropriate solution would be to provide a short guide to where to look for Global Messages in the game.agf file, so that people with this very peculiar need can extract them and recreate them in some other format.

**Comment by ivan-mogilko** [comment]
I agree that this is a low priority for us, but at the same time the second solution which I mention above ("moving these options into a script") might take around 30 minutes to implement, for instance:
1. Add a "GlobalMessages" script module.
2. Generate String array in the module.
3. Clear GlobalMessages array in the game data.

After that the user will at least have these texts in an open form, and may do whatever they want.

**Comment by ivan-mogilko** [comment]
Of course, one may also write a standalone tool or script which extracts these texts...
