### ISSUE TITLE
Isometric support

### ISSUE THREAD

**Issue by jumpjack** [adventuregamestudio/ags#1861]
It would be useful to introduce isometric support; currently AGS only supports 16 "walkbehinds", which would allow only 4x4 tiles rooms; bringing this value at least to 256 would allow 16x16 rooms, which could be created in Tiled (www.mapeditor.org) and imported (somehow...) in AGS (manually creating 256 walkbehinds would not be an alternative...)

**Comment by ivan-mogilko** [comment]
Could you please be more specific, what does "isometric support" imply? You probably have some experience with this, but others not necessarily understand this:
> currently AGS only supports 16 "walkbehinds", which would allow only 4x4 tiles rooms; bringing this value at least to 256 would allow 16x16 rooms

**Comment by jumpjack** [comment]
Yes, I mean "constructing a room of some elements", where "elements" are called "tiles": they are drawn top-down, each one occludes the previous one, and the player is visible or occluded depending on its position when drawing the room.

![image](https://user-images.githubusercontent.com/1620953/208429181-d35dd799-1e0e-4b6e-ab58-a697a4a4753b.png)

I also had a quick look at overlays, but I think only 20 of them are available, right?

Anyway it's not just a matter of occlusions: also collisions have to be implemented.

**Comment by ivan-mogilko** [comment]
> I also had a quick look at overlays, but I think only 20 of them are available, right?

Since 3.6.0 they are unlimited.

> Anyway it's not just a matter of occlusions: also collisions have to be implemented (i.e. walkable areas, i.e. the "footprints" of the tiles).

Since 3.6.0 walkable areas may be modified at runtime as well. I cannot tell how convenient that might be, because never tried to make a fully functional room generator like this, but in theory one could read a "level" from a file, create elements with room objects (256 max in 3.6.0) or room overlays (unlimited in 3.6.0), and draw the walkable areas accordingly around these elements.

**Comment by ivan-mogilko** [comment]
If I recall right, judging by reading the related posts on AGS forums in the past, the biggest issue with isometric room is the objects' baselines (or sprite sorting in general). In AGS they are implemented having a side-view in mind. I don't know how this is usually dealt with in isometric engines, and whether it's possible to work around in AGS.

**Comment by jumpjack** [comment]
"Tiled" tool I mentioned above ( www.mapeditor.org ) is the de-facto standard for tile-based games "maps" (which you call "levels"): a TMJ file (a JSON file with different extension) contains both tiles map and collisions map).

The draw order of tiles is the biggest issue in isometric engines; that's why I asked for an "enhancement request" rather than "help about how to implement it by myself". :-)  I experimented with MelonJS, JSiso, Wright!, Phaser3, but I always had to implement everything by myself.

**Comment by ivan-mogilko** [comment]
Well, I can tell that this will be a very low priority for us. AGS is intended for other kind of games, and there are far more serious tasks planned ahead. Unless someone wants to dedicate themselves for implementing this in the engine, or write a plugin that would do this job, I don't think this will be considered soon.

**Comment by jumpjack** [comment]
Given that a tiles and collision editor already exists, and an "import" featur already exists in AGS editor, the editor will "just" need a TMJ importer/converter.
Unfortunately I cannot help  with plugins, I am a javascript coder, not a C++ coder. Maybe I could help with the converter: where could I find the formats for walkbehinds files, overlays files and  walkable areas files?

**Comment by ivan-mogilko** [comment]
First thing you would need to decide, what are you going to convert *into*. For historical reasons in AGS there are types of objects that are created at design-time, and objects that are only created at runtime, using script commands.

For example, Overlays may only be created in script. So if you're planning to use overlays, then it makes little sense to import and convert anything within the editor.

Secondly, in AGS 3.* room contents are all packed in a single binary file, which has a rather complicated format. I don't think we have a proper specification around, so this has to be read in code.

In an experimental ags4 branch the rooms are saved in open format within the game project (design-time data): there walkable areas and walk-behinds are stored as separate PNG files, and generic data as xml. Perhaps this branch will be easier for these experiments.

**Comment by jumpjack** [comment]
If I undesrstood correctly how Overlays work (but I can't find their maximum number), I could import a TMJ/JSON file and use it to draw tiles/overlays one by one, assigning to them the "right" Z-order (see image below) before displaying the room, then AGS should automagically draw the sprites with proper occlusions.

![image](https://user-images.githubusercontent.com/1620953/208455158-15ec4b45-eb67-40ba-9406-1062d9f58411.png)


But I didn't understand if I also can create at runtime the walkable areas, which would be easier (for me), because exporting a JSON file in javascript is much easier than exporting images.

Note: "Walkable areas" are referred to as "collisions management" in isometric games.

Or maybe I should use [Regions](https://adventuregamestudio.github.io/ags-manual/Region.html#region-functions-and-properties)?  I see that I can edit them after game starts using [Drawimage](https://adventuregamestudio.github.io/ags-manual/DrawingSurface.html#drawingsurfacedrawimage); as all tiles have the same shape, to create my non-walkable region I should just draw one image per each tile onto the DrawingSurface.

If I build a 100% transparent region on the background in this way, then could I use `Region.GetAtRoomXY(int x, int y)` to detect if the sprite is over it?
And is it possible to test for an area of the sprite rather than just one pixel?

**Comment by jumpjack** [comment]
This is what I need to draw as nonwalkable area:

![image](https://user-images.githubusercontent.com/1620953/208459879-43871c85-85dc-4241-8664-cfe6f4528008.png)

**Comment by jumpjack** [comment]
To summarize:

Isometric --> AGS:

- Tiles --> Regions ([static DrawingSurface* Region.GetDrawingSurface()](https://adventuregamestudio.github.io/ags-manual/Region.html?case_sensitive=0#regiongetdrawingsurface))
- Occlusions --> Walkbehinds [(DrawingSurface* GetDrawingSurfaceForWalkbehind()](https://adventuregamestudio.github.io/ags-manual/Globalfunctions_Room.html?case_sensitive=0#getdrawingsurfaceforwalkbehind))
- Collisions --> Walkable area (inverted)  ([DrawingSurface* GetDrawingSurfaceForWalkableArea()](https://adventuregamestudio.github.io/ags-manual/Globalfunctions_Room.htmlcase_sensitive=0#getdrawingsurfaceforwalkablearea))


![image](https://user-images.githubusercontent.com/1620953/209130628-60a2f0df-24fe-4c77-9370-f03f63787bcc.png)

I think I should refer to these functions:

For tiles/regions:
```
DrawingSurface.DrawImage(int x, int y, int slot, optional int transparency,
                            optional int width, optional int height,
                            optional int cut_x, optional  int cut_y, 
                            optional int cut_width, optional int cut_height)
```
For collisions /nonwalkable:

`DrawingSurface.DrawTriangle(int x1, int y1, int x2, int y2, int x3, int y3)`


But I don't understand one thing: how do I set transparent color when drawing an image onto a drawing surface? I mean the color which will be totally replaced by background, not transparency level of whole image. 
Or, in other words, how do I turn the first image (a chair) into the third (chair silhouette, one color for background, one transparent color), to paste it into a walkbehind drawing surface?

**Comment by ivan-mogilko** [comment]
> Probably this happens because walkability check is performed on single pixel; can it be done on aforementioned "player base area"?

No, I'm afraid AGS does not support this option at the moment.

The "base area" you mention, it's the player's own "collider", called "Blocking area" in AGS. But it is not tested against the walkable area, it's used to create a non-walkable region where other characters and objects cannot move into.

**Comment by jumpjack** [comment]
Ok, I added this in repeteadly_execute():

```
  int leftX = cEgo.DestinationX - tilewidth/2 + XMARGIN; int leftY = cEgo.DestinationY;
  int topX = cEgo.DestinationX; int topY = cEgo.DestinationY - tileheight/2 + YMARGIN;
  int rightX = cEgo.DestinationX + tilewidth/2 - XMARGIN; int rightY = cEgo.DestinationY;
  int downX = cEgo.DestinationX; int downY = cEgo.DestinationY + tileheight/2 - YMARGIN;
  lblDebug.Text = String.Format("Now: %1d,%1d", cEgo.x,  cEgo.y);
  lblDebug2.Text = String.Format("Going to: K: %1d,%1d (%1d), M %1d,%1d (%1d)", leftX, rightX,  GetWalkableAreaAtRoom(leftX, rightX) ,  mouse.x,  mouse.y,  GetWalkableAreaAtRoom(mouse.x, mouse.y));
  if ( 
  ( GetWalkableAreaAtRoom(leftX, leftY) > 0 )  &&
  ( GetWalkableAreaAtRoom(topX, topY) > 0 )  &&
  ( GetWalkableAreaAtRoom(rightX, rightY) > 0 )  &&
  ( GetWalkableAreaAtRoom(downX, downY) > 0 )) {
    //
  } else {
    lblDebug.Text = String.Format("%s - Should stop!", lblDebug.Text ) ;
    cEgo.StopMoving();
  }
```

Unfortunately it works only with mouse; upon pressing arrow keys on keyboard, I get weird values for DestinationX and DestinationY, but I could just disable keyboard.

-----

Anyway, what about the other question? "how do I turn the first image (a chair) into the third (chair silhouette, one color for background, one transparent color), to paste it into a walkbehind drawing surface?"

Thanks.

**Comment by ivan-mogilko** [comment]
@jumpjack , I am sorry, but this becomes a scripting help conversation, and I usually don't do this here in the repository; and also frankly don't have much of a spare time now.

I may recommend visiting AGS forums and discuss this problem there:
https://www.adventuregamestudio.co.uk/forums/index.php

In regards to this ticket, and a question of "Isometric support"  I think it comes down to this:
1. Specify what is required for isometric support, which "elements", so to speak;
2. Find out whether engine provides means or workarounds to achieve what is required;
3. Find out what is impossible, or way too inconvenient to do in the engine.

When we have established p3, we may look at the picture and decide what kind of additional functionality should be added. Or whether it will require more significant redesign to allow different game "modes".

**Comment by jumpjack** [comment]
this is exactly what I am doing: trying to implement isometric support using only available features, and at the same time explainig to readers of this thread how isometric games work (tiles,collisions occlusions).
As of now I figured out how to implement tiles and collisions, now only occlusions remain to complete the job.

I have two kinds of resources available:
- png images with  transparent color
- bmp couples (image + transparency mask)

Probably I should prepare a drawingsurface entirely filled with one color and "drill" it by "pasting" on it where needed the .bmp images containing the masks.
I'll give it a try.

So the final process would be:
- load TMJ file (now: **simulated**)
- add one walkable area wherever there are NO tiles **(done)**
- draw each tile as per their "isometric Z order" (z=x+y) (**to do** with drawingsurface.drawimage using png images)
- draw per each tile its transparency mask onto overall walkbehind drawingsurface (**to do** with drawingsurface.drawimage using BMP image masks)

**Comment by messengerbag** [comment]
With isometric maps, is it not usual to have character movement be square-by-square rather than pixel-by-pixel, so that the character will always be standing at (or moving between) the centers of the squares? In that case, you wouldn't even need walkable areas.

**Comment by jumpjack** [comment]
No, the character can move freely all around its tile, but the tile as one single object is used to check for "collisions", i.e. walkable areas: if next move will bring character out of its tile, you must check in advance if adiacent tile is walkable.
At least, this happens in isometric games I've seen around.

**Comment by ivan-mogilko** [comment]
> Unfortunately it works only with mouse; upon pressing arrow keys on keyboard, I get weird values for DestinationX and DestinationY, but I could just disable keyboard.

Could you tell more about this?, I'd like to check if that's a error in the engine.

Also, in regards to testing DestinationX/Y, that's only the final point, but I suspect that the character may walk on an undesired place if it has a multi-segment route, for example, around the corner.

**Comment by ivan-mogilko** [comment]
> Anyway, what about the other question? "how do I turn the first image (a chair) into the third (chair silhouette, one color for background, one transparent color), to paste it into a walkbehind drawing surface?"

Oh, I apologize, for not realizing what you're asking about earlier, my head was busy with other things...

There's a `DynamicSprite.CopyTransparencyMask` function. I guess you could do this: have a sprite filled with certain color, and then copy transparency mask from a real chair sprite on it. The you will have a "silhouette" kind of image.

**Comment by jumpjack** [comment]
> > Unfortunately it works only with mouse; upon pressing arrow keys on keyboard, I get weird values for DestinationX and DestinationY, but I could just disable keyboard.
> 
> Could you tell more about this?, I'd like to check if that's a error in the engine. Are you using keyboard controls script that comes with the "Sierra" game template?

> 
> Also, in regards to testing DestinationX/Y, that's only the final point, but I suspect that the character may walk on an undesired place if it has a multi-segment route, for example, around the corner.

Yes I started with Sierra template.
I would expect that using keyboard I would get as DestinationX and DestinationY a position very close to current one, but I get numbers which I don't understand.
For example:
player stand still in (x,y)=93,93. DestinationX and DestinationY = 85, 101. Shouldn't they instead be the same of current position?
Upon pressing RIGHT arrow: DestinationX and DestinationY = 107, 123. Why these numbers?

I also changed from **eKeyboardMovementModeTapping** to **eKeyboardMovementModePressing** to get the player stop in clicked position rather than continue walking.

But it could depend on me, I'm quite new at AGS scripting and not experienced at all in C.

**Comment by jumpjack** [comment]
Current status of my attempt to implement isometric game in AGS:

- Occlusions: use overlays, assigning to Zorder properties the sum of X and Y isometric coordinates
- Collisions: 
    - rather than drawing walkable areas, it's better to make whole room walkable and "drill" nonwalkable areas for each tile;
    - it's better to extend downwards by some pixels the nonwalkable areas, to prevent the effect of "walking over furniture".

**Comment by ivan-mogilko** [comment]
I would rather close this, as apparently this was successfully (at least relatively?) implemented in script.

If there are actual things not possible (or too difficult) to implement in script, then please open a new issue about them.
