### ISSUE TITLE
On Linux engine does not load plugin dependencies if they are NOT found in system's rpath

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1865]
Another related issue, may be addressed together: #1707
Recent related bug, for the reference: #1864

When trying to load a plugin, the engine currently coded to look into these locations:
* system rpath;
* cwd;
* engine's binary location (if different from cwd).

However, if the plugin has dependencies, the engine does not search for them itself, but relies on `dlopen` do the job. And dlopen searches only the rpath.

The problem is, that some plugins may depend on another custom (user-made) library, or simply a library that's not commonly installed on player's system, but distributed along with the game. In such case the dlopen will simply won't be able to find it, and thus the plugin will fail to load.

One good example is the AGSSteam plugin `libagssteam.so` which relies on a `libsteam-api.so` (a part of the Steam SDK).

A dummy test game:
https://github.com/adventuregamestudio/ags/files/10289620/test--350steamplugin--flat.zip

Some solution has to be invented for this case, to let such plugins and their dependencies load from any directory where engine may look for plugins.
Please also see #1707 for a related suggestion, that may have an impact on the final solution.

**Comment by ericoporto** [comment]
This is not exactly right, the dlopen mechanism works like this (in Linux, not sure about MacOS and others):

> - (ELF only) If the executable file for the calling program contains a DT_RPATH tag, and does not contain a DT_RUNPATH tag, then the directories listed in the DT_RPATH tag are searched.
> - If, at the time that the program was started, the environment variable LD_LIBRARY_PATH was defined to contain a colon-separated list of directories, then these are searched. (As a security measure this variable is ignored for set-user-ID and set-group-ID programs.)
> - (ELF only) If the executable file for the calling program contains a DT_RUNPATH tag, then the directories listed in that tag are searched.
> - The cache file /etc/ld.so.cache (maintained by ldconfig(8)) is checked to see whether it contains an entry for filename.
> - The directories /lib and /usr/lib are searched (in that order).
> 
> If the library has dependencies on other shared libraries, then these are also automatically loaded by the dynamic linker using the same rules. (This process may occur recursively, if those libraries in turn have dependencies, and so on.)

So we first try dlopen call with the name of the library alone, later we try it with `./libagsname.so` and finally we use the `appDirectory/libagsname.so`.

Now, note the last line of how dlopen will propagate the loading for the libraries dynamic dependencies. There's probably things that matter here like, "are we passing absolute or relative paths?" (I think this is something that changed between AGS versions), "are we using rpath or runpath?", and so on. These are only ideas of things to investigate.

**Comment by ivan-mogilko** [comment]
> Now, note the last line of how dlopen will propagate the loading for the libraries dynamic dependencies. There's probably things that matter here like, "are we passing absolute or relative paths?"

I'm not sure if I understand, are you saying that if we try to load a plugin using certain relative path, like 'appDirectory/libagsname.so', then this plugin's dependencies will also be searched in the same relative path `appDirectory`? Or this is not what you meant?

**Comment by ivan-mogilko** [comment]
> We can also check with ldd ags64 if $ORIGIN is being set in rpath

@ericoporto , you are probably mistaking 2 tickets, what you say refer to the "bundled" engine binary, which is a separate issue (#1864).

This ticket is about a commonly built engine, which is not built with hardcoded rpaths.

**Comment by ericoporto** [comment]
> I had all the libraries

What libraries? Without rpath or LD_LIBRARY_PATH direct dependencies (vorbis, sdl2, ...) are linked to what is available on system paths (/usr/lib, /lib, ...)

> Could you clarify, when you speak of absolute/relative paths, do you refer to paths passed into dlopen as an argument

What we pass to dlopen.

---

Let's go back, engine is supposed to output dlerror on dlopen failures. Could you add the log messages of the engine in this specific case?

If these log messages are not enough, we can use `strace` to look into what's going on, but that is for later. Ah, and is there any plugin that isn't agsteam where this happens?

**Comment by morganwillcock** [comment]
I think that the change of build environment is now setting RUNPATH instead of RPATH, and that won't work with libraries like the Steam support which look to open a library themselves.

So for this ticket there probably needs to be a convenient way to set RPATH, RUNPATH, or do nothing, when building because the build method shouldn't need to be different to accommodate the use of the binary.

For the linked ticket, to get the original behaviour back I think `--disable-new-dtags` needs to be passed to the linker.

^ this is just based on what I think is going on, I haven't actually confirmed this yet, and something that is a stand-alone library would need to checked too. Using just the Steam support for testing is probably generating a lot of confusion about where the problem is.

**Comment by ivan-mogilko** [comment]
Before answering, I must clarify again, that in the context of *this ticket* I am speaking about a commonly built engine (using a common Makefile), and *not* a "bundled" binary built with debian scripts (for that I opened another ticket #1864).

Here I will link a dummy game which may be used for a test: 
[test--350steamplugin--flat.zip](https://github.com/adventuregamestudio/ags/files/10289620/test--350steamplugin--flat.zip)
It's a "flat" version of the build linked to the second ticket, without an engine, only game data + steam plugin so files (64-bit).

> > I had all the libraries

> What libraries? 

Plugin and its dependency (`libagsteam.so` and `libsteam-api.so`). I had them in the same dir as the engine, and ran the engine from terminal, while being in the same dir.

> Let's go back, engine is supposed to output dlerror on dlopen failures. Could you add the log messages of the engine in this specific case?



> Ah, and is there any plugin that isn't agsteam where this happens?

I tried few other plugins, but they did not have "custom" dependencies (except for system libs, perhaps), and they loaded fine. This made me think that the reason is dlopen not being able to find a dependency (`libsteam-api.so`) if it's located simply in cwd.
I guess it may be possible to create a test plugin that requires a dummy library as dependency and try that.

**Comment by ivan-mogilko** [comment]
Before answering, I must clarify again, that in the context of *this ticket* I am speaking about a commonly built engine (using a common Makefile), and *not* a "bundled" binary built with debian scripts (for that I opened another ticket #1864).

Here I will link a dummy game which may be used for a test: 
[test--350steamplugin--flat.zip](https://github.com/adventuregamestudio/ags/files/10289620/test--350steamplugin--flat.zip)
It's a "flat" version of the build linked to the second ticket, without an engine, only game data + steam plugin so files (64-bit).

> > I had all the libraries

> What libraries? 

Plugin and its dependency (`libagsteam.so` and `libsteam-api.so`). I had them in the same dir as the engine, and ran the engine from terminal, while being in the same dir.

> Let's go back, engine is supposed to output dlerror on dlopen failures. Could you add the log messages of the engine in this specific case?

```
Built library path: libagsteam.so
dlopen returned: libagsteam.so: cannot open shared object file: No such file or directory
Built library path: ./libagsteam.so
dlopen returned: libsteam_api.so: cannot open shared object file: No such file or directory
Built library path: /home/ikm/games/test--350steampluginflat/libagsteam.so
dlopen returned: libsteam_api.so: cannot open shared object file: No such file or directory
Plugin 'agsteam' could not be loaded (expected 'libagsteam.so'), trying built-in plugins...
Placeholder functions for the plugin 'agsteam' found.
```

> Ah, and is there any plugin that isn't agsteam where this happens?

I tried few other plugins, but they did not have "custom" dependencies (except for system libs, perhaps), and they loaded fine. This made me think that the reason is dlopen not being able to find a dependency (`libsteam-api.so`) if it's located simply in cwd.
I guess it may be possible to create a test plugin that requires a dummy library as dependency and try that.

**Comment by ericoporto** [comment]
First, I think @morganwillcock  is probably correct on the RPATH, here' s is 3.5.0.31:
```
$ objdump -x ags64 |grep 'R.*PATH'
  RPATH                $ORIGIN/lib64
```

> Using just the Steam support for testing is probably generating a lot of confusion about where the problem is.

Probably better would be a dumb plugin with a dumb dependency just for testing.

@ivan-mogilko , Uhm, that is a curious output of dlerror, here is the same but for agsblend:

```
Built library path: libagsblend.so
dlopen returned: libagsblend.so: cannot open shared object file: No such file or directory
Built library path: ./libagsblend.so
dlopen returned: ./libagsblend.so: cannot open shared object file: No such file or directory
Built library path: /home/user/git/ags/cmake-build-release/libagsblend.so
dlopen returned: /home/user/git/ags/cmake-build-release/libagsblend.so: cannot open shared object file: No such file or directory
```

I noticed the error output on the shared libraries in the error message for `libsteam_api.so` don't have the directories mentioned.

Ah, if there is a way to "know" the dependencies of a plugin (say the editor writes this information), we could dlopen the dependencies before the plugin.

**Comment by ivan-mogilko** [comment]
I've read a few things about this, and apparently this cannot be resolved easily on the engine's side.

The existing options are:
- Set LD_LIBRARY_PATH before execution. This is what our generated launch scripts do, but this also may be done by user (write script or do from terminal each time).
- Using `-rpath` linker option. This might work in case someone builds the engine for particular game, but won't work in a general case, as the engine may be located not in the game dir, so we cannot predict the necessary rpath.
- Explicitly load (custom, non-system) plugin dependencies before the plugin itself. I'm afraid this is going to be a convoluted solution, as we'll have to either
    * Store the list of these dependencies in game data; while the game data may be generated on a system where dependencies may differ; and somehow we will have to distinguish system deps from custom ones.
    * Analyze dependencies at runtime, basically do what `ldd` utility does on Linux (idk if there are even standard functions for doing this); and again we will have to somehow distinguish system and custom deps.

Overall the "generic" solution seems like a lot of work for something thay may be resolved using `LD_LIBRARY_PATH`:
```
LD_LIBRARY_PATH=path_to_game_dir/ ags path_to_game_dir
```

And so far there is only 1 plugin that ever needed this (at least among the popular ones).

So I am leaning to close this with "wont fix" now, and provide users with instructions.

**Comment by morganwillcock** [comment]
> Set LD_LIBRARY_PATH before execution. This is what our generated launch scripts do, but this also may be done by user (write script or do from terminal each time).

I don't think the launch script ever did this. It has appeared in launch scripts written by other people, who built the engine themselves, didn't have the rpath value set, and then found that libraries wouldn't load.
