### ISSUE TITLE
Walkable areas management

### ISSUE THREAD

**Issue by jumpjack** [adventuregamestudio/ags#1873]
![image](https://user-images.githubusercontent.com/1620953/209861232-e5aea13b-5989-45dd-95c9-2d65bf6340f1.png)

Looking at how character moves with debug mode enabled to show walkable area (image above), apparently it seems that check is performed on single pixel on foot of the character versus edges of nonwalkable area. In other words, the "nonwalkable hole" around character's feet can overlap the nonwalkable area, as long as the single pixel at (playerwidth/2 , playerheight) is out of the area.

Is this intended or is this a bug?

**Comment by ivan-mogilko** [comment]
This is an intended behavior. The "nonwalkable hole" is affecting the same character it belongs to, but rather prevents *other* characters from walking too close to this character.

**Comment by jumpjack** [comment]
I think it's counter-intuitive. Maybe in a future version it could be useful an user-selectable option to use single point or  character  nonwalkable area to determine allowed positions for a character.

**Comment by ivan-mogilko** [comment]
> Maybe in a future version it could be useful an user-selectable option to use single point or character nonwalkable area to determine allowed positions for a character.

Maybe. There have been a feature request to also allow to customize the character's blocking area further (right now it's strictly a rectangle positioned at a hardcoded place relative to char).
