### ISSUE TITLE
Remove long usage from CSCISendControlMessage in debug GUIs 

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1875]
Right now we have a `long lPar` at right in CSCISendControlMessage

https://github.com/adventuregamestudio/ags/blob/566ea29fee0e1d3b3ca88b309e02de5f25879f15/Engine/gui/cscidialog.h#L29
 
The way this works later is in most cases is it gets casted to char*

https://github.com/adventuregamestudio/ags/blob/566ea29fee0e1d3b3ca88b309e02de5f25879f15/Engine/gui/mylistbox.cpp#L156

The `long` size in bytes varies per system, this table in AGS explains well

https://github.com/adventuregamestudio/ags/blob/566ea29fee0e1d3b3ca88b309e02de5f25879f15/Common/core/platform.h#L99-L111

**The problem**

The problem is void* and long size differs in Windows 64-bit systems, so in these systems this convertion will fail. It would be nice to refactor these, to avoid the long <-> char pointer conversions.

---

Despite the "Send" in the name of the function, that lParam is also used to retrieve/read values, so it would be nice to break it in two methods, so sending and getting is different? I gave a shot at replacing the buffers with Strings and using them instead, but not sure if it's too much for the change necessary here.

<https://github.com/ericoporto/ags/commit/7a03fc183b607ef20092b27c43b4c9ba9aba26c7>

**Comment by ivan-mogilko** [comment]
In regards to this function, it's worth noting that it's exclusively a part of built-in gui dialogs handling (built-in Quit, Restore, Load and Save), and has no relation to API.

I think there may be 2 separate tasks here:
1. A hotfix, to make the code more reliable.
2. Complete rewrite of this part, for example, into a number of virtual methods instead of generic "message" function.

> Despite the "Send" in the name of the function, that lParam is also used to retrieve/read values, so it would be nice to break it in two methods, so sending and getting is different?

The "Send message" term may be used for both setting and retrieving values, you may compare with WinAPI, or Scintilla API, for instance.

**Comment by ericoporto** [comment]
> A hotfix, to make the code more reliable

A hot fix would be fine as a fix of this issue - I just wanted it to work in LLP64 systems.

The rewrite (2.) could have it's own ticket later if necessary, as this part of the engine code is something we don't touch as much as the other parts, and may have different considerations.

**Comment by ericoporto** [comment]
I tried a different [hotfix way of switching to `char*`](https://github.com/ericoporto/ags/commit/571f4c930ff2b191125b32bb6b91738e670ef910), but I don't know exactly what to do here in this case, where I think it's meant to be unicode aware.

https://github.com/adventuregamestudio/ags/blob/b1611316632ae4193634d05d59444f273d0c4bb8/Engine/gui/mytextbox.cpp#L68

Overall I am having a hard time figuring out what is the minimal way to change this and get me into a proper win64 compatible way.

**Comment by ivan-mogilko** [comment]
I think you misunderstand what it does. This `lParam` there may contain *either* a pointer, or an integer, depending on "message".
So if you replace with `char*`, the proper conversion would be: `int uchar = (int)lParam`

But `intptr_t` may be the best way to do this, as it is afaik guaranteed to be a size of a pointer.

**Comment by ericoporto** [comment]
I tested intptr_t and it worked in win64 builds, and it apparently works the same in x86 builds too, so I made a PR.
