### ISSUE TITLE
GUI Buttons Text Offsets

### ISSUE THREAD

**Issue by WallucePinkham** [adventuregamestudio/ags#1876]
**Describe the problem**
I would like to be able to set the offset, in pixels, for text on GUI Buttons. I find the current options of TopCenter, MiddleCenter, etc. too limiting. The button style that I would like to use just does not look good with the current settings.
This is incovenient and ugly. I could do an image for each button, but then I can't use the same in-game font for my dialogs, since the graphics applications don't understand AGS fonts.

**Suggested change**
I would like to be able to set the offset, in pixels, for text on GUI Buttons. E.g. 10 pixels from the left and 3 pixels from the top.

**Comment by ivan-mogilko** [comment]
>  I could do an image for each button, but then I can't use the same in-game font for my dialogs, since the graphics applications don't understand AGS fonts.

I'd like to mention an existing workaround for now: you may create Dynamic Sprites in game script, and draw text with any game font on a sprite, then assign it to button.

**Comment by ericoporto** [comment]
A second workaround is laying a label on top :)

**Comment by WallucePinkham** [comment]
Hi,

Thanks for the workarounds, but it looks like I have to make an image 
for every button anyway, because the text doesn't move with the button 
when I change images (e.g. clicked).

**Comment by ivan-mogilko** [comment]
Well, the dynamic sprite solution solves that too (as you may create them for all buttons states); but in the end this is a choice of making a graphic at design-time versus runtime (programmatically).

**Comment by ericoporto** [comment]
I don't think we are doing this now, but in case it happens, it's probably better to use names like margin or padding, picking up a logic from how things work in html/css instead of plainly offset - offset with doesn't work conceptually with something like alignment.
