### ISSUE TITLE
Documentation for ZOrder and baseline of overlays, objects and characters

### ISSUE THREAD

**Issue by jumpjack** [adventuregamestudio/ags#1881]
I think the [documentation about this new ZOrder feature ](https://adventuregamestudio.github.io/ags-manual/Overlay.html#overlayzorder)introduced with 3.6.0 could be more clear by adding a reference to characters and objects baseline.

Current description:

> [Overlay.ZOrder](https://adventuregamestudio.github.io/ags-manual/Overlay.html#overlayzorder)
> int Overlay.ZOrder;
> Gets/sets the overlay's z-order relative to other overlays and on-screen objects.
> 
> The Z-order setting is an arbitrary integer number that can be positive or negative. AGS draws the Overlays and GUIs in order, from the lowest numbered at the back to the highest numbered at the front.
> 
> Compatibility: Supported by AGS 3.6.0 and later versions.
> 
> See also: [GUI.ZOrder](https://adventuregamestudio.github.io/ags-manual/GUI.html#guizorder)

Suggested changes (in bold):
> [Overlay.ZOrder](https://adventuregamestudio.github.io/ags-manual/Overlay.html#overlayzorder)
> int Overlay.ZOrder;
> Gets/sets the overlay's z-order relative to other overlays and on-screen objects.
> 
> The Z-order setting is an arbitrary integer number that can be positive or negative. AGS draws Overlays, **Characters** and GUIs in order, from the lowest numbered at the back to the highest numbered at the front. **Overlays support transparency, so they can also be used to define [walkbehind](https://adventuregamestudio.github.io/ags-manual/Globalfunctions_Room.html?highlight=walkbehind&case_sensitive=0#getdrawingsurfaceforwalkbehind)-like areas starting from sprites:**

> `myOverlay[overlayIndex] = Overlay.CreateRoomGraphical(x,y,  spriteSlotNumber,  0,  true);`

> **The player or object will be drawn behind the overlay if  condition**

>**[player.Baseline](https://adventuregamestudio.github.io/ags-manual/Character.html) < overlay.ZOrder**

>or

>**[object.Baseline](https://adventuregamestudio.github.io/ags-manual/Object.html) < overlay.ZOrder**

>**is true.
> Normally player baseline value is automatically set by AGS engine to same value of player.y (lowest edge of sprite), but it can be set to any value; if set to 0, it switches back to auto-handling by AGS.**
> 
> Compatibility: Supported by AGS 3.6.0 and later versions.
> 
> See also: [GUI.ZOrder](https://adventuregamestudio.github.io/ags-manual/GUI.html#guizorder)

**Comment by ivan-mogilko** [comment]
@jumpjack , we have a separate repository for the manual, could you please repost this suggestion there?

> Overlays support transparency, so they can also be used to define walkbehind-like areas starting from sprites

I did not quite understand, how is transparency related to making walkbehinds?

**Comment by ivan-mogilko** [comment]
Reopened here: https://github.com/adventuregamestudio/ags-manual/issues/210
