### ISSUE TITLE
3.6.0: on Windows, window placement disregards the task bar

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1895]
**Problem**

In the previous versions, at least on Windows, AGS took taskbar into account, and clamped the maximal window size to the remaining space. 3.6.0 no longer seem to do this. With the "stretch to fit screen" the window is created too large, so it may partially hide behind a taskbar. Even if window's size is enough to fit the free space on desktop (e.g. with "max round multiplier" scaling), it's positioned without accounting for a taskbar, so I have to move it aside if I want to see the whole game screen.

**Expected behavior**

The game window should account task bar into account, clamp the maximal size, and position itself so that it is not covered by taskbar on start.

**Comment by ericoporto** [comment]
[GetMonitorInfo](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfoa) returns rcWork, with as far as I can understand is the work area rectangle. From the description [here](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfoa?redirectedfrom=MSDN):

> The work area is the portion of the screen not obscured by the system taskbar or by application desktop toolbars. 

From: [https://github.com/libsdl-org/SDL/src/video/windows/SDL_windowsmodes.c#L555-L577](https://github.com/libsdl-org/SDL/blob/a47a045128f74ae66b67668ceb346343554eb452/src/video/windows/SDL_windowsmodes.c#L555-L577)

I think you can then get this area by using [SDL_GetDisplayBounds](https://wiki.libsdl.org/SDL2/SDL_GetDisplayUsableBounds).

**Comment by ericoporto** [comment]
OK, turns out we have platform specific code for this in use instead of SDL2, it's platform->ValidateWindowSize.

https://github.com/adventuregamestudio/ags/blob/d6f02bf8523c9833dd5f9d38c5cb1e80c60e2891/Engine/platform/base/sys_main.cpp#L66

It already returns the correct size for the client rect area so it also takes into account window decorations, at least on Windows, and it looks like it _should_ be working even though it doesn't.

**Comment by ivan-mogilko** [comment]
> apparently for some reason accounting for shadows requires the window to be created and then adjusted

This is curious, but with "stretch to fit whole screen" the window may be created little to big (so partially hiding behind the task bar), but if you only move it a little, or just grab and release, it resizes itself to lower size.

**Comment by ericoporto** [comment]
I think it's this [SDL_GetDisplayUsableBounds](https://wiki.libsdl.org/SDL2/SDL_GetDisplayUsableBounds).

**Comment by ivan-mogilko** [comment]
Hmm, apparently 3.5.1 also has a problem, but it's different: the window's size is the same but the window is positioned away from the task bar, which results in caption being behind the desktop's upper bound.

**Comment by ivan-mogilko** [comment]
One thing to keep in mind, the way ValidateWindowSize is used currently (or rather `get_max_display_size`): it is not refered to as the max window size, but as the max client size (or the max possible game frame). The window with borders will be larger.

Need to double check how does SDL interpret width and height in `SDL_CreateWindow`, because there might be a logical mismatch.

**Comment by ericoporto** [comment]
I think SDL_CreateWindow uses the internal width and height of the window, the client area.

**Comment by ericoporto** [comment]
I think because platform->ValidateWindowSize does work, a first fix may be done by only using it, and later perhaps a new version may be done by making the base version of this method be done using SDL methods. But as I mentioned before, if one wants to consider shadows they need to do so after window creation with a readjustment.

I also found this issue with `SDL_WINDOWPOS_CENTERED` https://github.com/libsdl-org/SDL/issues/6875

**Comment by ivan-mogilko** [comment]
> I also found this issue with SDL_WINDOWPOS_CENTERED https://github.com/libsdl-org/SDL/issues/6875

Oh so that's why it's not adjusted vertically as in 3.5.1.

If the size may be fixed, we may either leave the centering as it is, or add a temporary hack until SDL2 fixes this.

**Comment by ericoporto** [comment]
![image](https://user-images.githubusercontent.com/2244442/224518880-8ba4d850-4de6-45e8-9f81-394d52a055ac.png)

From the issue text

> With the "stretch to fit screen" the window is created too large

Just to counterpoint, in my computer the size of the window is correct, the position is the thing that is wrong.

**Comment by ericoporto** [comment]
> But I'm concerned this may cause the window to "blink".

I tested this on Windows by setting the position and size right after the window is created inside `sys_window_create` and it didn't blink.  One thing that I don't know about using `SDL_SetWindowPosition` instead is we normally use `SDL_WINDOWPOS_CENTERED_DISPLAY(DEFAULT_DISPLAY_INDEX)`, so do we need to do something to specify which display we are talking about before setting the position? (my guess is we don't, but thought to ask)

**Comment by ivan-mogilko** [comment]
> One thing that I don't know about using SDL_SetWindowPosition instead is we normally use SDL_WINDOWPOS_CENTERED_DISPLAY(DEFAULT_DISPLAY_INDEX), so do we need to do something to specify which display we are talking about before setting the position?

That's a good point, I used SDL_GetWindowDisplayIndex(window) when centering.

**Comment by ericoporto** [comment]
The PR works correctly and I don't perceive any blinking issue (this is something that was mentioned as a possibility at some point).

But, in case someone has a problem at some point with blinking in the future, I noticed this [comment](https://github.com/libsdl-org/SDL/issues/7506#issuecomment-1475015431)

> The recommended way to create windows with a position is to create the window hidden, set the window position, then show the window.

So if the need arises in the future, we can do this.
