### ISSUE TITLE
Allegro MIDI patches working no more

### ISSUE THREAD

**Issue by ffaf1** [adventuregamestudio/ags#1898]
**Describe the bug**
Using Allegro MIDI patches (needed to precisely render midi tracks as they played on, say, WinXP) works no more. 

**AGS Version**
ACI version 3.6.0.37, Debian stable.

**Game**
Trilby's notes

**To Reproduce**
Have `export ALLEGRO=~/cfg/data/audio/ags-midi/` (and a `patches.dat` in the folder). Start game, you will notice a line like `- MIDI decoder, using a subset of TiMidity : MIDI,MID,`.

**Expected behavior**
Get tracks to play as they did on Win.

**Desktop (please complete the following information):**
- Debian stable

**Additional context**
Is there a way to have AGS tell timidity to use that specific file? Or a workaround?

**Comment by ericoporto** [comment]
https://adventuregamestudio.github.io/ags-manual/MIDI-playback.html

Hey, we switched from Allegro to SDL2_Sound, it uses an embedded Timidity with some differences, so instead it needs a timidity cfg. The above topic in the manual should help, please reply if this works for you.

**Comment by ffaf1** [comment]
Thanks, sad that I have to edit a file in `/etc/` and no dotfile instead.

**Comment by morganwillcock** [comment]
> Thanks, sad that I have to edit a file in `/etc/` and no dotfile instead.

Just to clarify, you shouldn't have to do modify the system configuration if you just want MIDI music to work again. The Timidity configuration and/or the patches can still be local to the game, it is just a default configuration for the current user which doesn't seem to be possible now.

I'll update the documentation because it seems a little confused.

**Comment by ericoporto** [comment]
@ffaf1 you should also be able to set an environment variable TIMIDITY_CFG and pass the location of the timidity.cfg there

I am only now noticing it's not mentioned in the manual.

**Comment by ffaf1** [comment]
That is most welcome, my mum does not want me to run `sudo`.

Do we know if DOSBox runs timidity? and if so, which patch? I feel older games take advantage of some idiosyncrasies that get lost using contemporary patches.

**Comment by morganwillcock** [comment]
I've updated the page to try and be clearer on what is needed and where the files can be located:
https://github.com/adventuregamestudio/ags-manual/wiki/MIDI-playback/b9b8e6ac9ec65d74c209f4ad51ddf0241920f8ea

These changes are not in the manual yet, but the next build of the manual will use them unless I've made the page worse and someone notices.

I don't think it is correct to add a complete example of using patches on that page unless there is a set of patches that is definitely legal to redistribute and use. If someone can find such a set of patches it would be a good idea to add a complete example.

**Comment by i30817** [comment]
Heads up, if you're in linux you can 'simply' use a hardlink to patches.dat and place the 'copy' on the game directory.

**Comment by morganwillcock** [comment]
> Heads up, if you're in linux you can 'simply' use a hardlink to patches.dat and place the 'copy' on the game directory.

AGS 3.6 doesn't use patches.dat.

**Comment by i30817** [comment]
That's actually quite terrible. I didn't notice my soundfonts were broken now and timidity configuration requires creating the config file and i don't even have timidity installed. It's a bit strange that's the way this worked out.

**Comment by ivan-mogilko** [comment]
> That's actually quite terrible. I didn't notice my soundfonts were broken now and timidity configuration requires creating the config file and i don't even have timidity installed. It's a bit strange that's the way this worked out, since requiring user intervention is worse than not requiring it.

If there's some problem with MIDI in 3.6.0, or you have a suggestion to change something, please open a new ticket. This ticket was discussing why allegro midi patches do not work.

**Comment by i30817** [comment]
What's happening is that a self built ags is not picking up the timity.cfg, (and yes, there is a soundfont.cfg in a 'source' with a absolute path that exists inside that file, and the first line of that soundfont.cfg is a pointer to a directory that exists with the samples).

With Allegro previously, i just dumped the patches.dat and i had sound. Supposedly i could do the same now by dumping a timidity.cfg pointing to a existing soundfont on my system, but that's not working.
