### ISSUE TITLE
Dist. Ubuntu 22.04LTS: AGS Engine in Scummvm ACI version 3.6.0.31 had a Bug

### ISSUE THREAD

**Issue by SaschaVasarrhelyi** [adventuregamestudio/ags#1899]
**Describe the bug**
If i start "Captain Disaster in : Death has a million stomping boots" and the first Video starts in "Prolog" than this Error come up and the Game Exits.

"
ACI version 3.6.0.31
Error:SetTextOverlay Internal error: Inconsistent type ids
"

**AGS Version**
ACI version 3.6.0.31.
I use the Scummvm snap 2.7.0git-5625-gd930a30338a . Don't know exactly wich version of AGS they use in this Port.

**Game**
If applicable, link or attach an example game (with optional source) to demonstrate the issue.
"Captain Disaster in : Death has a million stomping boots"

https://store.steampowered.com/app/1298280/Captain_Disaster_in_Death_Has_A_Million_Stomping_Boots/

**To Reproduce**
1. Start the Game via Steam and Roberta Scummvm engine with Scummvm latest/edge from snap
2. See the Startsequence and wait till on screen comes the "Prolog...", after that you can see the Spaceship 1 sec than the error massage came up and than the game quti.
3. See error:  ACI version 3.6.0.31
Error:SetTextOverlay Internal error: Inconsistent type ids

**Expected behavior**
Just start and wait to the point

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS] Linux; Ubuntu-Mate 
 - Version 
 - 22.04.1 LTS (Jammy Jellyfish) 64-bit
 - MATE 1.26.0
 - Kernel Linux 5.15.0-58-generic x86_64

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel Something]
 - OS: [e.g. Android Q]

**Additional context**

**Comment by ivan-mogilko** [comment]
Hello.

The error sounds like a bug which had been already fixed in the past: #1797
and it's been fixed in [3.6.0.36](https://github.com/adventuregamestudio/ags/releases/tag/v.3.6.0.36).

The latest 3.6.0 build is 3.6.0.40. Could you please try that at tell if the problem persists?

**Comment by SaschaVasarrhelyi** [comment]
Hello,

i'am try to test the Game with the Stable brunch of snap ags.

You right, it's fixed the problen. No need to do something.

Thank You verry mutch

Greetings
