### ISSUE TITLE
Wrong text in Empty Template intro

### ISSUE THREAD

**Issue by jumpjack** [adventuregamestudio/ags#1900]
When creating a new game, a warning is shown to the user about empty template being used, suggesting to use "Default Game" template, but this template has been renamed to "Sierra-style".

V 3.6.0.41-RC6.

![image](https://user-images.githubusercontent.com/1620953/213380834-85078f77-25a9-4ce6-bc78-3825f0144165.png)

![image](https://user-images.githubusercontent.com/1620953/213381091-4f2ee18e-4524-47be-90cb-3601ae7fb419.png)

As a side note, a short description shown upon clicking on each template would help selecting the "right" one.

**Comment by ivan-mogilko** [comment]
Adjusted the template's intro in repository:
https://github.com/adventuregamestudio/ags-template-source/commit/8da20eec9ed07257f239914f52b69df15f390ae5
and repacked template. This will be included with the next 3.6.0 update.

> As a side note, a short description shown upon clicking on each template would help selecting the "right" one.

We have a feature request for that too: #564
