### ISSUE TITLE
crash when showing preload.pcx on build from master

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1906]
**Describe the bug**
The game crashes when loading when it has a `preload.pcx` image.

**AGS Version**
Build from current master https://github.com/adventuregamestudio/ags/commit/d103c55676db0078c7d006443662aa57b5858dff

**Game**
[preload_pcx_test.zip](https://github.com/adventuregamestudio/ags/files/10514282/preload_pcx_test.zip)

**To Reproduce**
1. Build from current master and run the attached game above
2. The crash should happen instantly

**Expected behavior**
The game should run

**Screenshots**
![image](https://user-images.githubusercontent.com/2244442/214975051-7560a1a7-7b0b-4baa-b430-59b8fef07448.png)

**Desktop :**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
Pushed a fix : 8e38f612d8b8fe834bdc8a55bb5ef543e6b45cb8

**Comment by ericoporto** [comment]
I don't get the crashing anymore, so the fix worked for me.

**Comment by ivan-mogilko** [comment]
Pushed a fix for not displaying a preload.pcx: 84730a4bbfb971855c667241a9a47745f283f12e
