### ISSUE TITLE
crash on fadeout in software render with 8-bit game built from master

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1907]
**Describe the bug**
Crash when running 8-bit game on software render in a fadeout

**AGS Version**
https://github.com/adventuregamestudio/ags/commit/d103c55676db0078c7d006443662aa57b5858dff

**Game**
[TestFade_8bit.zip](https://github.com/adventuregamestudio/ags/files/10514592/TestFade_8bit.zip)

**To Reproduce**
1. Create an empty 8-bit game and make sure it has fadeout, and load it on current master
2. Alternatively, use the attached project above or the binary in it
3. Run it with engine built from master

**Expected behavior**
The game is an empty black room, it should just load

**Screenshots**
![image](https://user-images.githubusercontent.com/2244442/214983994-2820dd25-633b-4efb-8437-f735de4d25ba.png)

**Desktop:**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
Pushed a fix: 7ad4f424f473f480c830faf3f7a2aca4388aa8fe

**Comment by ericoporto** [comment]
Fix worked! Thanks!
