### ISSUE TITLE
"Black Morph" text glitches

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1909]
This ticket is a recreation of #835. Unfortunately, in the original ticket the problem was not explained well from the start, and diagnosing did not progress at first. For that reason it contains a number of unrelated information and screenshots. This may cause misunderstanding for anyone who reads it. Another thing, the eventually posted screenshot which was displaying the actual problem is not longer available, but fortunately I found a copy saved on my disk.

---

**The problem**

@rofl0r reported text glitches in the game "Black Morph". The game may be found in AGS game database ([link](https://www.adventuregamestudio.co.uk/site/games/game/2123-black-morph/))

Following is a screenshot of the problem, made in the very first room after starting a new game, when you interact with the "Reeds" hotspot:
![blackmorph-rofl0r](https://user-images.githubusercontent.com/1833754/215852861-f7678e77-79bf-4c51-b3d7-da22bfa264c6.png)
Following is how the text is supposed to look like:
![blackmorph2-ags360-linux](https://user-images.githubusercontent.com/1833754/215852972-2dea57cf-b15d-4f39-9f70-39874e59b214.png)

In other words, a text is drawn with some parts cut off. Also note that parts of the textbox's frame is also either not drawn, or painted over with black color.

According to the initial report, the issue appeared starting with AGS 3.5.0; and game looked fine in 3.4.x engine. The issue was noticed on a Linux system (my guess, it's "Sabotage Linux", specifically). It persists regardless of a graphics driver: both Software and OpenGL renderers were tested with the same result.

The engine was built using common makefile, found in the Engine dir (**not** using cmake).

As a guess, this may be related to a change to alfont and/or freetype library: before 3.5.0 AGS was linking to a system freefont library on linux, but starting with 3.5.0 we have a particular version of freefont embedded into the engine.

Similar problem was not reported by anyone else since, which makes it seem a niche case. @rofl0r suggested trying a linux distro that uses **musl** libc, such as "alpine linux". The suggestion is that the problem is caused by an undefined behavior in either alfont or freefont, and musl may be more sensitive to those.

Unfortunately, at that time, I failed to build all necessary libraries for 3.6.0 engine (e.g. SDL_Sound) on alpine linux, and because this was such a strange report, left it for later, and forgot about it eventually. In retrospect I could try building and testing a 3.5.0 engine instead too.

---

May be related (or not): #1438, #1939

**Comment by messengerbag** [comment]
Notice that it is not just the text that is distorted: the whole screen is wrong. This can be readily seen in the dithering patterns of the background (e.g. on the cliffs above the text box).

**Comment by ivan-mogilko** [comment]
Speaking of potential bugs in ttf renderer (alfont), see description to #1939.

**Comment by ericoporto** [comment]
@ivan-mogilko , I think this error in particular is just downscaling.

**Comment by ivan-mogilko** [comment]
> @ivan-mogilko , I think this error in particular is just downscaling.

Thist *might* be a (uneven) scaling issue, but it's difficult for me to imagine how downscaling occured for this game. The game's native size is 240x135! The user who reported this mentioned he was playing both fullscreen and in window, in two different renderers. This was reported for 3.5.0 and 3.6.0 engines, and apparently in both cases they used default game's config. I wish I've asked for a log back then to see how gfx mode initializes.

**Comment by ericoporto** [comment]
It could. I am also thinking if maybe there is a case where `find_nearest_supported_mode` in the graphics mode code, fails.

**Comment by rofl0r** [comment]
indeed, the problem seems gone in current engine version. for code archeology purposes, it would be interesting to see which exact commit fixed it via bisecting, but even compiling ags once takes almost too much time for my taste.
