### ISSUE TITLE
AGS 4: New compiler fails to report member function without import properly

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1921]
CC @fernewelten 

**Describe the bug**
The new compiler fails to report a struct's member function without `import` keyword, and instead reports a use of this function, but does not name the function correctly.

Consider following script (may be placed completely in a script's body):
```
struct Test
{
    static int F();
};

function game_start()
{
    Test.F();
}
```

The **old compiler** fails with error:
> NewScript.asc(3): Error (line 3): function in a struct requires the import keyword

The **new compiler** ignores the declaration in struct, but fails at the function call:
> NewScript.asc(9): Function 'short' has been referenced in this file but never defined

Notice how
1. It does not pay attention to a wrong member declaration;
2. It reports function name incorrectly (`short`??). Looks like it's using a random item from a table of names.

**AGS Version**
4.0

**Expected behavior**
New compiler should report a member-function declaration without `import` as an error.
In any case, if it's necessary to report a function name, it should give a proper name, and not a random type name.

**Comment by fernewelten** [comment]
Oops. I'm only seeing this right now for some reason. I'll see to it.

**Comment by ivan-mogilko** [comment]
Fixed.
