### ISSUE TITLE
Leisure Suit Larry 2: script error upon entering a TV studio

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1943]
**Describe the bug**
In "Leisure Suit Larry 2" (AGS remake) upon entering a TV studio you receive a scripting error that implies that a string function received a null-pointer instead of a real string.

**AGS Version**
Reproduced in 3.6.0, 3.5.1, 3.5.0 so far.

**Game**
In AGS database:
https://www.adventuregamestudio.co.uk/site/games/game/356-leisure-suit-larry-2-point-and-click-final-version-/
Just in case, attached to github:
https://github.com/adventuregamestudio/ags/files/10915492/larry_test.ags.zip

**To Reproduce**

Option 1:
1. Use a save made in 3.6.0.44 just before the TV studio:
[agssave.zip](https://github.com/adventuregamestudio/ags/files/10920600/agssave.zip)
2. Enter the TV studio (through the auto-sliding doors).

Option 2:
1. Launch the game, skip the intro.
2. Walk "north" through the multiple screens (to be precise: "north" means towards the up-right corner), until you reach a TV studio - that should be the last screen.
3. Enter the TV studio (through the auto-sliding doors).

Observe the error.

**Expected behavior**
No script error should happen.

**Comment by ivan-mogilko** [comment]
Alright, this looks like a false alert. I downloaded the game from the [AGS database](https://www.adventuregamestudio.co.uk/site/games/game/356-leisure-suit-larry-2-point-and-click-final-version-/), and it does not give same error.

@ericoporto could you tell, where/how did you get the larry_test.ags that you linked in #1941?

**Comment by ericoporto** [comment]
@ivan-mogilko I got it from one of the several midi threads here: https://github.com/adventuregamestudio/ags/issues/367#issuecomment-761814457

Now, the game was indeed repacked by rofl0r, and I don't remember where it was shared with me.
