### ISSUE TITLE
Going from Windowed to Fullscreen hangs in OpenGL driver with VSync

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#1949]
**Describe the bug**
If the game is using OpenGL video driver, when going from Windowed to Fullscreen, if VSync is set, it hangs.

I have only tested on Linux, haven't tried on Windows or different linuxes.

**AGS Version**
3.6.0.44 and since this https://github.com/adventuregamestudio/ags/commit/bcf90697ac93080d0edac3e99727041a4e2b461a

**Game**
The game I tried had vsync set.

**To Reproduce**
1. Start the game in Windowed mode
2. Press Alt+Enter to go into Fullscreen
3. The game should hang

**Expected behavior**
It should just go into fullscreen and the game should proceed

**Desktop:**
 - OS: Ubuntu
 - Version 16.04 (it's old, I know)

**Additional context**
If I make the support check return false, the game no longer hangs

https://github.com/adventuregamestudio/ags/blob/f19043d902ff9a7e7d6478f51093ef3c807dd258/Engine/gfx/ali3dogl.h#L230

I tried to redo SetVsync like this 

```Cpp
bool OGLGraphicsDriver::SetVsync(bool enabled)
{
    if (_mode.Vsync == enabled)
    {
        return _mode.Vsync;
    }

    if (SDL_GL_SetSwapInterval(enabled) == 0)
    {
        _mode.Vsync = enabled;
    }

    return _mode.Vsync;
}
```

But the game still hanged.

I saw some weird comments on `SDL_GL_SetSwapInterval` from icculus, so now I am a bit suspicious of it - and I think we call it on everyframe, which not sure is a good idea.

- https://github.com/libsdl-org/SDL/issues/4471#issuecomment-886069233
- https://github.com/libsdl-org/SDL/issues/5122#issuecomment-1010569143

<details>
<summary>$ glxinfo | grep version</summary>
server glx version string: 1.4 <br>
client glx version string: 1.4 <br>
GLX version: 1.4 <br>
    Max core profile version: 4.5 <br>
    Max compat profile version: 3.0 <br>
    Max GLES1 profile version: 1.1 <br>
    Max GLES[23] profile version: 3.2 <br>
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.5 <br>
OpenGL core profile shading language version string: 4.50 <br>
OpenGL version string: 3.0 Mesa 18.0.5 <br>
OpenGL shading language version string: 1.30 <br>
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.5 <br>
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20 <br>
</details>

<details>
<summary>$ glxgears -info</summary>
GL_RENDERER   = Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)  </br>
GL_VERSION    = 3.0 Mesa 18.0.5  </br>
GL_VENDOR     = Intel Open Source Technology Center  </br>
GL_EXTENSIONS = GL_3DFX_texture_compression_FXT1 GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_window_pos GL_ATI_blend_equation_separate GL_ATI_draw_buffers GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_texture GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_gpu_program_parameters GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texture GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_IBM_multimode_draw_arrays GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_INGR_blend_func_separate GL_INTEL_performance_query GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_MESA_window_pos GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_light_max_exponent GL_NV_packed_depth_stencil GL_NV_primitive_restart GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_env_combine4 GL_NV_texture_rectangle GL_OES_EGL_image GL_OES_read_format GL_S3_s3tc GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays 
VisualID 312, 0x138
</details>

**Comment by ivan-mogilko** [comment]
> and I think we call it on everyframe, which not sure is a good idea.

That's a must, but there's also something else that was not accounted for before: if it fails, then the new value is not saved, and it will keep trying repeatedly again. Possibly the solution would be to remember the first fail, and not try again, at least until a display mode changes (windowed/fullscreen).

TBH I cannot remember why is it set repeatedly anyway, maybe we need to stop doing that and set only once the setting changes. There is some other setting that is also set repeatedly afaik (render sprites at screen resolution). In case of D3D that simply changes a variable, but in case of OpenGL it also does some "test", which may spend some time...
...now when I said that, I wonder if it has something to do with abnormal cpu load that I noticed running OpenGL some time ago. Maybe not, but it's still not a good thing.

> I saw some weird comments on SDL_GL_SetSwapInterval from icculus, so now I am a bit suspicious of it

Hmm, both cases seem to be different from what we have: first is about setting >1 interval, and second is about using "adaptive" mode (-1 arg).

**Comment by ericoporto** [comment]
> why is it set repeatedly anyway

I still don't understand exactly if a window is destroyed and recreated after the game is running in some case, but perhaps if this happens it also needs to reapply the `SDL_GL_SetSwapInterval` config.

**Comment by ivan-mogilko** [comment]
Does this happen when vsync is not set? Because we need to know which exactly problem we need to fix, and it's not clear from the ticket's description.

**Comment by ericoporto** [comment]
> Does this happen when vsync is **not** set?

No, it only happens when vsync is set!

**Comment by ericoporto** [comment]
I wonder if I am screwing with how I have vsync set. I used `System.VSync = true` at game_start.

**Comment by ivan-mogilko** [comment]
> I wonder if I am screwing with how I have vsync set. I used System.VSync = true at game_start.

Well, that is supposed to be handled by recent changes where runtime change is allowed for d3d/ogl.
Before that change this command will only work for software renderer.

Hmm, by the way, what if you run software renderer, theoretically it should use OpenGL on linux too?

**Comment by ericoporto** [comment]
> Hmm, by the way, what if you run software renderer, theoretically it should use OpenGL on linux too?

Good call, let me try that.

I tried your PR, and it did not work, I added a bit of log and it looks like the SDL_GL_SetSwapInterval returns success, but after it, I can only run 1 game frame when I try to enter in fullscreen, going back to windowed is possible by hittin alt+tab (but not alt+enter!), and attempting to go back to fullscreen only runs 1 game frame.

https://gist.github.com/ericoporto/73e4942d9e19cebb1e2aa63d7675e4ae

My computer reports `Running OpenGL: 3.0` on log, and not something newer like 4 or above.

**Comment by ivan-mogilko** [comment]
> I added a bit of log and it looks like the SDL_GL_SetSwapInterval returns success, but after it, I can only run 1 game frame

Could be it is stuck waiting for the interval response for some reason?... just a blind guess.

**Comment by ivan-mogilko** [comment]
What if you set vsync in config to enable on startup, instead of using a script command, will it work, or same thing happens?

**Comment by ericoporto** [comment]
> What if you set vsync in config to enable on startup, instead of using a script command, will it work, or same thing happens?

I added [some logging commands](https://gist.github.com/ericoporto/02189d626968f19514d2a40f797bc319) and got the log below

https://gist.github.com/ericoporto/2cb4e544dad752e91dd0c7922d32e6c2

**Comment by ivan-mogilko** [comment]
> Curiously I don't see any SetVsyncImpl call in the log. It still hangs.

Assuming you set vsync in config, then SetVsyncImpl is not called, because the vsync was already set at the display mode init.

The fact that it still hangs probably means that the OpenGL just does not handle vsync, in these particular circumstances.

I should test this on linux too...

**Comment by ericoporto** [comment]
Hey, so... Apparently it only happens with Future Flashback, I tried to create a small game that causes it, but so far, can't quite figure it out what makes this bug trigger. :/ If you have an old version of Future Flashback, it should trigger it.

**Comment by ivan-mogilko** [comment]
Hmm, apparently I cannot test this on my Ubuntu vm, because OpenGL does not work properly in fullscreen on my system, at all. Instead I always see a black screen, and can only alt-tab out of the game, but usually cannot go back. This refers to both our own OpenGL renderer, and the SDL2-based software renderer (when the underlying output is opengl), and also regardless of vsync.  Maybe this is an issue with virtual box's driver, or something is not configured correctly. I may try again using a different vm, or try tracing back to older versions of AGS to see if it works with them later.

---

I tried your "Future Flashback" game on Windows, but do not experience this problem.

In regards to this issue, we need to keep narrowing it down, because it started with thinking that switching vsync at runtime is causing this, now it turns out that having it preset causing this, and only in one game (so far).

My questions are then:
1. when did this start? does this only happen with the latest 3.6.0, or did it happen with earlier ones too? The runtime vsync setting was ported only very recently, by commit 08d0552643fdc309420fbc81243cc1071869a06a.
Could you build from earlier tags and see if this problem was present back then, **with vsync enabled in config** (as enabling it in script won't work)?

2. Another question, to double check, does this happen with software renderer when it has opengl as an output (created by SDL2), or no?

Looking at what happens in the video, makes me wonder if vsync somehow breaks our game frame timer...

**Comment by ivan-mogilko** [comment]
As a small update, I finally managed to resolve the fullscreen issues on my Ubuntu VM, by manually upgrading SDL2 from 2.0.4 to 2.24.2. Now I can have a working fullscreen mode (so it's been some SDL2 window error).

However, I met another weird problem, as our OpenGL renderer fails setting vsync, reporting error.
Weirdly enough, I was able to have vsync enabled if using software renderer with SDL's own opengl output.

Using the latter, I don't have any problems running your game with vsync. FWIW the vsync is set at startup, as the version I've been testing does not seem to change vsync in script.

**Comment by ericoporto** [comment]
> Could you build from earlier tags and see if this problem was present back then, with vsync enabled in config 

I built 3.6.0.42 from source, and set vsync in acsetup.cfg and manage to reproduce the issue. I am trying to figure it out when it started to happen.

**Comment by ericoporto** [comment]
I am tending to close this issue as the only thing I can think of is something installed in this computer broke something OpenGL related and this is why my computer now exhibits this curious weird behavior.
