### ISSUE TITLE
AGS4: New compiler inconsistency on import of managed struct type function

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1951]
@fernewelten I encountered an issue with asterisk omission and custom managed structs imports, outside structs.
Imports declared inside `struct` do not trigger this bug.

**Describe the bug**
ash
```ags
import Point[] foo(); // error, recognized as Point[] instead of Point*[] from asc declaration
import String[] bar(); // works (maybe builtin types are handled differently?)

struct MyTest {
   import Point[] foo();  // works
}
```
asc
```ags
Point[] foo() { ... }
String[] bar() { ... }
```

**Expected behavior**
The import clause should allow omitting the asterisk without causing errors, just like it already does when the import is declared within a struct.

**Comment by ivan-mogilko** [comment]
This is a subtask / duplicate to #1729, where the reasons for this behavior are also explained in detail.

**Comment by AlanDrake** [comment]
Alright, if it's already known and this is a dupe, feel free to close the ticket.
I had overlooked that issue and didn't make the connection.
