### ISSUE TITLE
Move game objects logic update out of the game draw pass

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1956]
There's a number of things done inside the "draw game" function (and sub-functions) that rather relate to updating the game and object states. Besides inconvenience, the problem with that is that if drawing is skipped for any reason, then the game will not be fully updated, resulting in an inconsistent state.

There's at least one obscure bug known that may be caused by this, related to the character zoom level not getting updated if the room is fully fade-out. But there may be more.

Known cases:
1. Character and object updates in `prepare_characters_for_drawing()` and `prepare_objects_for_drawing()`. Include zoom and visual sprite position update, affected by the room areas and view offsets.
2. GUIMain::Poll is called from `draw_gui_and_overlays`.
3. Mouse cursor update in `update_mouse_cursor()`, which is currently called only when the game screen is drawn. Includes cursor position and cursor animation updates.~
4. Mouse move over hotspot check in `game_loop_do_render_and_check_mouse` is done only after the render, possibly because the mouse update is done inside render function. In fact whole `game_loop_do_render_and_check_mouse` would like be not necessary after this (the mouse update code may be moved elsewhere).

The object state update needs to be moved out to the general game update function. This has to be done carefully, as the state update is entangled with the draw cache update in these functions. Only necessary parts should be moved.

IMPORTANT: if this is done we also likely need to make sure a mouse is updated during "special" states, such as shakescreen, etc. These places are possibly found where `construct_game_scene` or `render_graphics` are called explicitly in a loop.
For that reason this issue may perhaps be easier to do after #1349, but 1349 likely will take more effort in comparison.

This is required for detaching game update from render, if we want to have separate update rate and render rate.
See also: #1349.

This will be beneficial for 3.* branch too, as may help avoiding occasional regressions in older games.

**Comment by AlanDrake** [comment]
Are you sure it won't cause regressions on 3.x?

**Comment by ivan-mogilko** [comment]
> Are you sure it won't cause regressions on 3.x?

No, i'm not sure; this has to be investigated logically for possible effects.
But I know that there's already a small potential regression in 3.6.0 because of slightly optimized draw call (which i mentioned in the issues's description).

**Comment by ivan-mogilko** [comment]
Partially resolved by #1957, but some things still remain (see the updated ticket description).

**Comment by ivan-mogilko** [comment]
Remaining issues resolved by c5e20301a490d22631975ada3e4fba91d650039d and f41eb86f25d425f4c8c040089131897d20419559
