### ISSUE TITLE
3.6.0: Perfect Tides crashes in 3.6.0 (Mac)

### ISSUE THREAD

**Issue by messengerbag** [adventuregamestudio/ags#1973]
**Describe the bug**
Running the game [_Perfect Tides_](https://www.adventuregamestudio.co.uk/site/games/game/2605-perfect-tides/) (released in an AGS 3.5.1 Mac version for Steam) with a v3.6.0 engine build on MacOS, it crashes at a certain point with the error message: 

> Assert failed at line 289 of <...>/ags_3.6.0.47_source/libsrc/allegro/src/graphics.c

The line in question is `ASSERT(width >= 0);` in `create_bitmap_ex()`

The point at which is crashes is a sort of cutscene where the main character goes on her computer and an in-game AIM chat window pops up. The game [uses Khris's ChatDisplay module](https://www.adventuregamestudio.co.uk/forums/modules-plugins-tools/module-chatdisplay-show-a-whatsapp-like-dialogue-on-gui-button/msg636638438/#msg636638438) to display the chat window.

**AGS Version**
It crashes on Mac in both v3.6.0.44 and v3.6.0.47, built by me from source according to the instructions [here](https://anthonyirwin.com/adventure-game-studio-ags-macos-build/).  I've also tried running it both in OpenGL and with software driver, fullscreen and windowed, and it does not make a difference.

It does not crash in the official Mac build that Steam distributes (running ACI version 3.5.1.16, compiled with 3.5.1.11).

I have not been able to test on Windows to see whether the problem is limited to Mac or applies to 3.6.0 generally.

**Game**
_Perfect Tides_ v1.0.1, official Mac version as shipped on Steam

Savegame before crash: [agssave.029](https://drive.google.com/file/d/1e8CWg5lZji5CAPam6qvdKQ8DbLZzAR5G/view?usp=share_link)

My latest home-built AGS app bundle (into which I drop the game files): [ags_3.6.0.47.app](https://drive.google.com/drive/folders/1ZU1L-L-21Jnm9g_zmNjJjQrauphmsfQ4?usp=share_link)

**To Reproduce**
1. Click Hand cursor on computer to begin cutscene
2. Click through a few dialog boxes
3. Game crashes at point where chat window is supposed to appear

**Expected behavior**
Game should not crash. An in-game chat window should pop up.

**Additional context**
The reason I want to run it in 3.6.0 is that because of the awkward resolution (640x480), the game cannot be cleanly scaled to full-screen, and ends up with uneven pixel scaling using the software driver. In 3.6.0 I can use OpenGL and supersampling to get even pixel scaling (with anti-aliased edges).

**Comment by ivan-mogilko** [comment]
> The reason I want to run it in 3.6.0 is that because of the awkward resolution (640x480), the game cannot be cleanly scaled to full-screen, and ends up with uneven pixel scaling using the software driver. In 3.6.0 I can use OpenGL and supersampling to get even pixel scaling (with anti-aliased edges).

Unrelated to the bug, but does not OpenGL work in 3.5.0 / 3.5.1?

**Comment by messengerbag** [comment]
> Unrelated to the bug, but does not OpenGL work in 3.5.1?

No:

> Graphic settings: driver: OGL, windowed: no, screen def: scaling, screen size: 0 x 0, match device ratio: yes, game scale: proportional
> Requested graphics driver 'OGL' not found, will try existing drivers instead

And I don't think it's expected to work. The 3.6.0 release notes mention:

> **OSX:**
> - OpenGL renderer is now supported on MacOS.

**Comment by ivan-mogilko** [comment]
Oh, I had bad memory, this is how OSX port used opengl prior to 3.6.0 (quoting a comment from a different ticket):

> This may be important to mention that in 3.5.* mac port works somewhat similar to mobile ports: the engine only draws game in native size using software renderer, then this image is passed into the patched Allegro library, where its own graphic or system driver uses OpenGL to display a scaled texture.

**Comment by ivan-mogilko** [comment]
So, this is interesting. I did not have this crash on Windows, but then I found out that the ASSERT that you reference is disabled by default in our builds. I only get this when rebuilding the engine with Allegro ASSERTs enabled (by declaring `DEBUGMODE` compile flag). If it's disabled, then the execution simply continues, and creates an invalid bitmap.

This originates from the call to `DynamicSprite.Create(/*width*/ 210, /*height*/ 0);`

**Comment by ivan-mogilko** [comment]
After more testing in AGS 3.2.1 and 3.5.1, apparently DynamicSprite.Create never really cared about the arguments.

Here's my test run:
`DynamicSprite.Create(0, 0); // success`
`DynamicSprite.Create(100, 0); // success`
`DynamicSprite.Create(0, 100); // success`
`DynamicSprite.Create(-1, -1); // success?!`
`DynamicSprite.Create(-1, 10); // crashes, failed to allocate -40 bytes, lol`

**Comment by ericoporto** [comment]
> I only get this when rebuilding the engine with Allegro ASSERTs enabled (by declaring DEBUGMODE compile flag).

https://github.com/adventuregamestudio/ags/blob/38d0dd3d7f0d6a4624d1f908f2e8d3c1abfee52a/libsrc/allegro/CMakeLists.txt#L194

Uhm it looks like it's there on the CMake, so this flag is enabled in debug builds on macOS that are done through CMake (I need to update the stream api moved around in the Xcode project, so that may not be working for a different reason) and also and also in Android debug builds. I think we never officially build Emscripten for debug, so web builds are not affected.

**Comment by ivan-mogilko** [comment]
Pushed 82194b261b4649281742c45498a4c34f452fd350, which will enforce minimal size of 1 x 1 and proceed. Not the perfect solution, but this is just to keep old games working.

**Comment by ivan-mogilko** [comment]
Also, while testing, I noticed that the computer chat is made *horribly* slow. It drops game fps from 40 to 15-16.
Upon further debugging, it **fully recreates dynamic sprite** on each game frame(!), and probably redraws it over and over. Maybe there's more.

**Comment by messengerbag** [comment]
> > I only get this when rebuilding the engine with Allegro ASSERTs enabled (by declaring DEBUGMODE compile flag).
> 
> https://github.com/adventuregamestudio/ags/blob/38d0dd3d7f0d6a4624d1f908f2e8d3c1abfee52a/libsrc/allegro/CMakeLists.txt#L194
> Uhm it looks like it's there on the CMake, so this flag is enabled in debug builds on macOS that are done through CMake

It makes sense to me that debug mode is enabled in debug builds. I did notice that building it in XCode placed the binaries in /Debug, but I don't know XCode well enough (/at all) to figure out any other way to build it, and it never caused problems up till now.

> Why not following the instructions from our README?

Because I never knew there was a readme with instructions for building on Mac. It's a pretty natural progression: the link has good explanation of how to get Windows AGS games to run on Mac, with a pre-built app bundle for two engine versions. Then if you want some other engine version, it also has step-by-step instructions on how to build it yourself right below.

Now looking at the readme, yeah, I think it could be improved. I mean, it starts out talking about icons. That's just about the LAST think you need to worry about if you want to get an AGS game to run on Mac. And the way it presents alternative processes is just confusing.

(And couldn't we distribute an official pre-built app bundle for each version of the engine, rather than ask every Mac user to build their own?)

**Comment by ivan-mogilko** [comment]
> And couldn't we distribute an official pre-built app bundle for each version of the engine, rather than ask every Mac user to build their own?

There have been an issue open for this: #1333.
I don't know what the current state is.

**Comment by messengerbag** [comment]
> well, the problem is clear, the question now is which behavior to implement while also keeping compatible with existing games...

My knee-jerk answer is that either throwing a script exception or returning NULL would be the right behavior if the bitmap dimensions are illegal. Then you'd need a backwards-compatible script option for running older games, of course.

The assertion failure in Debug mode is probably OK? There just needs to be a well-documented way to make non-debug builds for Mac.

> I wonder if it's a game's or original module's problem.

We could ask in the module thread. (Or first examine the module code to see how it's meant to run, I suppose.)

**Comment by ivan-mogilko** [comment]
@messengerbag could you check if building from commit 82194b261b4649281742c45498a4c34f452fd350 fixes the issue? It's a compatible hack, will create a bitmap of minimal valid size instead.

We may change it to return null in case of bad parameters in the future major versions (like ags4).

**Comment by ericoporto** [comment]
Just a thing, using cmake by telling it is a release, there shouldn't be that assert.

**Comment by messengerbag** [comment]
> @messengerbag could you check if building from commit [82194b2](https://github.com/adventuregamestudio/ags/commit/82194b261b4649281742c45498a4c34f452fd350) fixes the issue? It's a compatible hack, will create a bitmap of minimal valid size instead.

Hmm...
First, I didn't want to download the whole repo, so I just applied the change in my local copy of the 3.6.0.47 code.

And yes, it no longer crashes, but the scene is now extremely laggy. As you said:

> Also, while testing, I noticed that the computer chat is made horribly slow. It drops game fps from 40 to 15-16.

This is _not_ the case for me with 3.5.1. The difference is very noticeable in this build.

**Comment by ivan-mogilko** [comment]
I tested once more with both 3.5.1 and 3.6.0.

3.5.1 gives around 24 fps for me with 1 chat window, and 14 with 2 chat windows.
3.6.0 gives around 15 fps with 1 chat window, and 8 with 2 chat windows.

So, obviously there's a curious regression in 3.6.0. On another hand, it's been already quite slow in 3.5.1, which is an issue on its own.

I will try to figure out what is making it slower in 3.6.0 though.

**Comment by ivan-mogilko** [comment]
Found the commit that caused the slowdown: c34f0c96596f1a7814c15e7a06c2c498cb95ebfc
This was an experiment, which was partially disabled later: e0edb28b6606c360a1ea3fdcc487c2b05929ed02

**Comment by ericoporto** [comment]
`sys_evt_process_pending()` should not be that costly, if there are no events we go there, the event list is empty, it backs out. We already call it once per frame normally, how many times is it being called per frame to cause this slowdown?

**Comment by ivan-mogilko** [comment]
> `sys_evt_process_pending()` should not be that costly, if there are no events we go there, the event list is empty, it backs out. We already call it once per frame normally, how many times is it being called per frame to cause this slowdown?

It's not `sys_evt_process_pending` that is causing this, but `AGS_Clock::now()` alone.

> How are you getting your numbers?

Running with `--fps` command and looking at fps numbers at the bottom of the window.

**Comment by ivan-mogilko** [comment]
Okay, I removed the whole check added by c34f0c96596f1a7814c15e7a06c2c498cb95ebfc.
It's sad to do this, but on the second thought, it's totally not correct to add extras like this inside a script execution, which is quite time sensitive, and may be already slower than wanted...

**Comment by ericoporto** [comment]
I read a bit about `now` and apparently there are faster ways to get time. There's even a single magical assembly instruction - perhaps there's some abstraction to select the correct assembly per processor. Are we using now multiple times per frame in different places?

**Comment by ivan-mogilko** [comment]
Apparently the event pending was also done incorrectly, because it did not reset the `_lastAliveTs` when running pending. Which means that pending would keep running every turn after reaching a time limit.

> Are we using now multiple times per frame in different places?

It's in several places around the code, in frame delay calculation, input handling. It's easy to see if you search for `AGSClock::now()`.

I made a simple test, counting how many times the time test is called per game frame, and it shows numbers in the range of 16000 to 30000.

**Comment by ericoporto** [comment]
There is some interesting discussion here: https://github.com/microsoft/STL/issues/624

Apparently if we know the duration range  (do we need to go up to seconds or at most milliseconds?) and precision, there are ways to do it a bit faster.

**Comment by ivan-mogilko** [comment]
Hmm, I replaced the AGSClock declaration with `using AGS_Clock = std::chrono::system_clock;`
and can confirm that it runs at least almost as fast as in 3.5.1 for me.

**Comment by ivan-mogilko** [comment]
I've been testing 3.5.1 and 3.6.0 with fixes (fixed event poll timing and using system_clock), and 3.6.0 without this timeout check at all.

EDIT: it still slightly slower, like 0.5-1.5 fps slower , randomly.

**Comment by ericoporto** [comment]
There is also [`__rdtsc()`](https://learn.microsoft.com/en-us/cpp/intrinsics/rdtsc?view=msvc-170), I used it at some point in a benchmark variant AGS engine I had, where I needed to profile something - [around this time here](https://www.adventuregamestudio.co.uk/forums/general-discussion/interesting-article-on-using-chrometracing/msg636632672/#msg636632672). I think it wasn't able to go much longer than 1 second without overflowing.

**Comment by ivan-mogilko** [comment]
Well, I'd prefer to keep this time check removed. Even with system_clock there's a noticeable decrease, not a big one, but there is.
Overall, I believe it was a mistake to add extra code to the script interpreter which is already not fast.

**Comment by ericoporto** [comment]
@ivan-mogilko unrelated, but does running in unlimited frame mode (fps on + ctrl+e) gives you even more fps gains there?

**Comment by messengerbag** [comment]
> Running with --fps command and looking at fps numbers at the bottom of the window.

Thanks!

Though I can't seem to get it to work with the original 3.5.1 Steam app bundle. Calling it with that command line option displays framerate info in the 3.6.0 builds, but running it the exact same way (and the same cfg options) with the officially distributed version shows nothing. It doesn't require a debug build of the engine, does it?

In any case, in my 3.6.0 build the framerate drops from 40 fps (60 fps when set to unlimited) to 1 fps with one chat window, and to 0.5 fps with two.

**Comment by ivan-mogilko** [comment]
> to 1 fps with one chat window, and to 0.5 fps with two.

This clearly indicates you are building a debug build of the engine, it contains too much extra check and assertion code.

**Comment by ivan-mogilko** [comment]
I believe this should be closed, as the original reported bug has been fixed.

In regards to the slowdown, @messengerbag, I propose to test with the latest release-3.6.0 branch (and use the "release" engine build), but if the problem persists I think it's best to open a separate issue.
