### ISSUE TITLE
Editor: delete/rename old compiled binaries when the "Game Filename" is changed in project

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1976]
Since the Editor allows to change the game's "filename" by editing a property in General Settings, following problem may occur: an old *.ags and possibly *.exe file would be left in Compiled/... folders. During further game compilations the extra *.ags files may get copied along from the Compiled/Data folder. Also this may cause problems when running a game using a standalone engine.

The proposal is to either **delete** or **rename** old compiled binaries found in Compiled folder and respective subfolders when "Game Filename" is modified.

---

Did a test of all builds to see the current situation:

* Data folder does not keep an old .ags file, so it's probably **fine**;
* Linux build does not keep old .ags, but it keeps old **startup script**;
* Web build keeps **old .ags**;
* Windows keeps an **old .ags** in case you have "Attach game data to exe" disabled in general settings, but not the old .exe;
* Android does not keep old .ags, so it's probably **fine**;

**Comment by ericoporto** [comment]
Delete sounds like the correct approach, probably checking if the file is really there before deleting, in case it's a second rename before building the game again.

**Comment by ivan-mogilko** [comment]
I did a little test, and the current situation is a little inconsistent:

* Data folder does not keep an old *.ags file.
* Linux build does not keep old *.ags, but it keeps old startup script;
* Web build keeps old *.ags;
* Windows keeps old .ags, but not the old .exe (that's in case you have "Attach game data to exe" disabled in general settings);
Haven't tested Android yet, because it takes a long time installing stuff.

**Comment by ericoporto** [comment]
Uhm, found an issue here that is the following: when you build the game (Build EXE) it saves the built name in some in ram variable. Then, if you rename the game file, in the next build, it first checks the previous built from this saved name and then asks for deletion of the previous build.

OK, the issue here is if you load a project, and then before building it once after the project is opened, you rename the game file. When you build after this "cold" renaming, AGS Editor won't know the name of the build it did before - since it's not serialized anywhere - so it won't trigger the delete of old builds.

I don't know what is the approach here - to serialize the build name somewhere or to delete on file renaming.

**Comment by ivan-mogilko** [comment]
> OK, the issue here is if you load a project, and then before building it once after the project is opened, you rename the game file. When you build after this "cold" renaming, AGS Editor won't know the name of the build it did before - since it's not serialized anywhere - so it won't trigger the delete of old builds.

If this is the only problem, then the filename could be saved at loading the project?

**Comment by ericoporto** [comment]
> If this is the only problem, then the filename could be remembered at loading the project?

Good point. Trying to think this through, I think if you rename, close and save the project without rebuilding and then load the project again it won't delete it when it build the exe. So, for this edge case then it would be necessary to serialize I think.

**Comment by ericoporto** [comment]
If you serialize on build, even if you rename twice or more times without building, the next time you actually build it will be able to pickup the builds in the old name, so serializing on build rather than on rename is also the correct time.

**Comment by ivan-mogilko** [comment]
> The question is more than where to serialize this to.

I added this to my previous comment: there's Workspace settings (`AGS.Types.WorkspaceState`), which seems suitable for this.

But looking into this now, turns out it already has something called LastBuildGameFileName!
https://github.com/adventuregamestudio/ags/blob/415dca744c913db7c8527b387e431c07d789fd76/Editor/AGS.Types/WorkspaceState.cs#L28

It's just that its use is non-trivial, I could not understand what it does yet.

**Comment by ericoporto** [comment]
This is curious, it looks like everything is in place then, it seems it's about figuring out when the workspace gets serialized (it seems it should be everytime a property change or at least some specific properties are changed?)

**Comment by ivan-mogilko** [comment]
@ericoporto 
> OK, the issue here is if you load a project, and then before building it once after the project is opened, you rename the game file. When you build after this "cold" renaming, AGS Editor won't know the name of the build it did before - since it's not serialized anywhere - so it won't trigger the delete of old builds.

Could you please give step by step instructions for this? I am not certain how this should be reproduced.

**Comment by ericoporto** [comment]
> Could you please give step by step instructions for this? I am not certain how this should be reproduced.

I can edit this tomorrow in a computer with specifics, but the summary is:

- load an AGS project in AGS Editor
- Go into general settings and rename the game file (I forgot the actual name of the property there)
- Now close AGS Editor.
- Open AGS Editor again, now click Build EXE
- Go to the game compiled folders and notice that the old game is still there along with the new one

**Comment by ivan-mogilko** [comment]
> I think the last game build name needs to be serialized on build and not on save.

The project is saved right before compilation, and workspace settings are serialized along.
