### ISSUE TITLE
Character.Animate errors in Gobliiins5 game/demo

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2001]
**Describe the bug**
The recently released Gobliiins5 games (including the demo which is chapter 1) are affected by multiple Character.Animate fatal errors.
The game is built using AGS 3.5.1.17.
Although this is an issue with the game and not the interpreter itself, it seems to affect also other (old) games
(i found one, [Prototypical](https://www.adventuregamestudio.co.uk/site/games/game/796-prototypical/) but there are likely others) so maybe the error check should be changed or downgraded.

**AGS Version**
3.6.0.48

**Game**
https://pierre-gilhodes.itch.io/gobliiins5

**To Reproduce**
1. Pick tin can
2. Move right
3. Use can with frog trashcan

**Desktop (please complete the following information):**
 - OS: [Any]

**Comment by ivan-mogilko** [comment]
Yes, you are right, pushed a change ecb4ae13031c32c2793d1d6a2b2af9f2af7bd911

**Comment by ivan-mogilko** [comment]
@tag2015 i did some more cleanups in the code, and fixed the "Prototypical" error with db71d928a6f290172975209d36ba7b7e22881f57.

**Comment by tag2015** [comment]
Great work! I can confirm that both games work fine now.
