### ISSUE TITLE
Editor: in Sprite Manager allow to modify properties of multiple selected sprites

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2008]
Before the new sprite import was implemented in AGS 3.5.0, the sprite manager's property grid let users to select multiple sprites and the property grid would display only matching values for all of these sprites, and show others as a blank space. If a property's value was changed, it would apply the new value to all the selected sprites.

After the sprite import and import dialog were reimplemented in AGS 3.5.0, this is no longer supported.

As user proposed, this ability should be restored.

When multiple sprites selected:
* Property grid displays only matching values, and displays blank space in other fields where values don't match.
* Changing a value of a property would affect all the selected sprites at once.

SIDE NOTE: I recall similar thing was requested for the View Frames, but I could not find any open ticket here.
(also selecting multiple frames is not possible as of 3.6.0)

**Comment by morganwillcock** [comment]
Do you know exactly why it doesn't work?

I don't think how the panel works was changed when the new sprite import window was added, although the panel contents will change depending on whether the 'ImportAsTile' option is True or False.

**Comment by ivan-mogilko** [comment]
> Do you know exactly why it doesn't work?

No, I haven't investigated that.

Actually, maybe this should be tagged as a bug, if this was not intended to change.

**Comment by ivan-mogilko** [comment]
So, there's a event callback `SpriteManager.spriteSelector_OnSelectionChanged`, called from `SpriteSelector.spriteList_ItemSelectionChanged`, and somehow it fails to be called if there's more than 1 sprite is selected. Probably some condition is wrong, or similar.

**Comment by ericoporto** [comment]
> ah, this was the commit that supposedly broke it

Specifically, only one item can have focus, but multiple items can be selected.

**Comment by ivan-mogilko** [comment]
Reverting the `e.Item.Focused` check fixes this, but the commit ff02202d26f11e988dd037b4909098e37b678583 was trying to deal with some slowdown, thus it would be proper to first investigate whether that problem may be solved in a different way.

**Comment by ivan-mogilko** [comment]
Found a very curious way to improve performance, opened pr: #2014
