### ISSUE TITLE
AGS on Linux captures keyboard in fullscreen mode preventing switching out of the application

### ISSUE THREAD

**Issue by shmerl** [adventuregamestudio/ags#202]
At present, in fullscreen mode on Linux AGS captures practically all keyboard shortcuts (with the few exceptions like switching to virtual terminals), so one can't switch out of the application with Alt+Tab or with shortcuts for switching virtual desktops. That's the common property of fullscreen X.org window by default, but it can be avoided if for example AGS would explicitly not trap certain combinations (like the mentioned Alt+Tab).

What to exclude can be left up to user to configure in AGS ini files for example (since users might have different combinations set for those actions in their desktop environments).

**Comment by shmerl** [comment]
Just tested it with Order of the Thorne release, and this bug is still present.

**Comment by ivan-mogilko** [comment]
I can confirm this is an issue with engine built from develop-3.3.5 branch (tested on Ubuntu).

A Linux savvy person should investigate whether this is something in AGS code that causes this, or caused by Allegro.

**Comment by rofl0r** [comment]
is this with system allegro or using the allegro sources in the ags source tree ?
i use the standard allegro libs in my distro and dont remember experiencing this problem.

**Comment by ivan-mogilko** [comment]
AGS has only few "patches" to Allegro in its source tree (and most of these are related to Windows build).

**Comment by ivan-mogilko** [comment]
Actually, I just re-checked, and these patches are not even used under Linux, at all.

**Comment by shmerl** [comment]
@rofl0r: Order of the Thorne is using Allegro that comes with AGS, so no the system one.

**Comment by ivan-mogilko** [comment]
@shmerl , are you playing the game with Linux port, or Windows version of the game with Wine?

**Comment by shmerl** [comment]
I'm playing the native Linux release.

**Comment by ivan-mogilko** [comment]
You mean, they have a precompiled game binaries for Linux?

**Comment by shmerl** [comment]
Yes, they provide precompiled binaries for Linux.

**Comment by ivan-mogilko** [comment]
Just to clarify, I was testing a random game, which I ran using the engine I compiled myself.

**Comment by shmerl** [comment]
Yep, I understood. I'll do such test as well with Order of the Thorne (a bit later) just to be sure.

**Comment by shmerl** [comment]
OK, I just built AGS from source using the default Makefile (on current Debian testing) and run the game with it. It has the same issue (Alt+Tab and other keyboard combinations don't work).

**Comment by shmerl** [comment]
After some digging I found this: https://github.com/liballeg/allegro5/issues/392

**Comment by shmerl** [comment]
@rofl0r: To clarify. Looked more closely at AGS source, and it's indeed using system installed liballegro when building the game. Sorry for previous confusion.

**Comment by shmerl** [comment]
Some overview of this issue: https://forum.kde.org/viewtopic.php?f=111&t=121907

**Comment by shmerl** [comment]
The best workaround for this is to use windowed mode, and set window size to your screen resolution if possible. I managed to do it for Order of the Thorne with ags-setup setting 6x nearest-neighbor filter (which game me 1920x1200). Then in KDE you can make window full screen which will hide all decorations. And Alt+Tab works! But this method doesn't seem universal, since ags-setup provides only a few such sizes, and if your screen doesn't match - it probably won't work.

**Comment by ivan-mogilko** [comment]
@shmerl , you can set "gfxfilter=max" in the config to make it choose maximal supported scaling automatically.

As for scaling restrictions, they are caused by how rendering was implemented in AGS. We changed it in develop-3.4.0 branch (currently WIP).

**Comment by stqn1** [comment]
Using SDL2 instead of Allegro would help. All AGS games are broken in fullscreen on Linux (no alt-tab or any other kb shortcut + partially transparent window for some reason when I use Compton configured to render unfocussed windows as partially transparent).

**Comment by ivan-mogilko** [comment]
We have a SDL2-based version now, this problem has to be retested in it.

**Comment by ericoporto** [comment]
I confirm this is not a problem in Ubuntu 20.04 with engine built from master, but I don't remember if this was a problem for me before (with allegro 4.4.3.1).

**Comment by ivan-mogilko** [comment]
Looks like working in the latest 3.6.0; although i should not that i've been using system SDL2, which may be of a different version that the one we distribute with the Editor's linux package.

If there's still any issue with this, a new report should be open as we now have SDL2 backend.
