### ISSUE TITLE
Possibility to _down_-zoom characters in Editor

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#2020]
**Describe the problem**
When you preview a character in the Editor, there is a zoom field to blow up visuals that are small. However, I've got the opposite problem: My characters are too large to fit the screen; I'd need the possibility to shrink them down to, e.g., 25 %. The zoom field doesn't offer any possibility to enter values smaller than 100 %. Thus there's no way to see all of the character with my monitor.

![image](https://github.com/adventuregamestudio/ags/assets/41213694/a6ce0de0-6dbe-4143-9556-011fcaffee9f)

Similar problem in the View editor preview:

![image](https://github.com/adventuregamestudio/ags/assets/41213694/43abb6e9-e50c-483d-994f-b8b0b06abb9d)

**Suggested change**
Make the zoom range start at 25 % or even at 10 % instead of 100 %.

AGS 3.6.0

**Comment by ivan-mogilko** [comment]
> In the view, originally I meant the left pane to have no relationship to the zoom slider at right, and instead just fill the panel as well as possible. I still think this works best for the animation preview, as it's more a quick preview of an animation that will be only properly viewed in-game, later, in a context. I think the slider should only affect the right pane there.

This is not a view, but a character preview.
Right pane on this preview displays a Speech view frame.

**Comment by ivan-mogilko** [comment]
> In the view, originally I meant the left pane to have no relationship to the zoom slider at right, and instead just fill the panel as well as possible. I still think this works best for the animation preview, as it's more a quick preview of an animation that will be only properly viewed in-game, later, in a context. I think the slider should only affect the right pane there.

This may be changed, although need to be careful, as the "preview" panel is shared between Character and View panes.
