### ISSUE TITLE
Allow importing masks of any number of colors actually used

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2025]
**Describe the problem**
When trying to import a hotspot mask, you have to use a 256 bit indexed image. That is alright. But if the number of colors in the actual drawing is bigger than 16, it will remove those colors. I don't understand why, because we can have 49 hotspots with events, names and all associated.

**Suggested change**
I would suggest removing any sort of limit, even the 49 hotspot colors, more colors (until the top 256) would simply not be associated to any event/name/... but they could still be retrieved through regular mask drawing functions.

**Comment by ivan-mogilko** [comment]
Limit by 16 for hotspots is probably a typo somewhere, because all other area types are limited to 16.

I would agree with the suggestion, but I wonder how remaining colors will look like in the editor. Because they may be "seen", but not selectable, if there are no higher area items.

**Comment by ericoporto** [comment]
just to explain a bit more, I had was experimenting with something in AGS where I encoded the information using a 0-255 palette, with 0-255 entries, but I want to use in a regular non-8-bit game, and then I am reminded AGS is 16-bit so I can at most get a 0-63 range through regular naive sprite import, so I tried to add as a mask since it's room-sized, but then I could not also do that.

So currently I need to use a python script to push the first 5 bits in the red channel and the remaining bits in the green channel.

(#1997 would solve my issue in a weird way because them I could get the pure information and in theory the red channel in a pure import would be equivalent to 0-255 in the indexed information because I currently am using a grayscale palette)

**Comment by ivan-mogilko** [comment]
Would it work for you if there were a support for importing sprites as 8-bit in AGS editor and/or loading 8-bit images from file and keeping them 8-bit instead of converting?

**Comment by ericoporto** [comment]
Yes but my feeling is this change would be way bigger.

**Comment by ivan-mogilko** [comment]
Is this urgent? Could you use a simple binary file instead?
I'm asking because it's not known how many nuances will appear when someone starts changing these things.

If you were making games in ags4, I would suggest completing #1980 too.

**Comment by ericoporto** [comment]
> Is this urgent?

Not at all, I have python script that I use to pack things in AGS colors, so I am using that. I just briefly forgot about it and was trying to find a workaround and then found that it was blocked through the editor.

**Comment by ivan-mogilko** [comment]
> Limit by 16 for hotspots is probably a typo somewhere, because all other area types are limited to 16. This probably may be fixed quickly on its own.

Regarding this, according to the code it's limited correctly depending on the mask type, but the warning message contains a hardcoded "16".

**Comment by ericoporto** [comment]
The too many colors message is fixed by https://github.com/adventuregamestudio/ags/commit/0180e6a3fa8218d3b4d6ede0316a7131ce49b256

The actual need of the request I think now is better served by some of the other approaches in the other tickets (#1997, #1980), so I am closing this.
