### ISSUE TITLE
Make all file-related script API case-insensitive

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2026]
As same AGS games may be run on both case-sensitive and insensitive filesystems, their asset loading at runtime is made case-insensitive. However, the File script commands were not, at least when they point to actual directories (paths with `$DATA$` token happen to be case-insensitive because they are resolved using AssetManager).

In order to make things consistent between various ways to load game resources, and also between systems, all these script commands should also be made case-insensitive.

This includes:
* File.Open;
* File.Exists;
* File.Delete;
* ListBox.FillDirList - treat subdirs in ci way; also should join multiple items which differ only by the letter case;
* DynamicSprite.CreateFromFile
* DynamicSprite.SaveToFile
* and corresponding legacy API which is not remapped to new funcs:
    * SaveScreenShot

In addition there's a potential problem with ResolveWritePathAndCreateDirs(), which is meant to support subdirs for files created by script. Right now it uses simply Directory::CreateAllDirectories() which ignores case sensitivity differences. Either we need to add a parameter that would instruct it to do CI tests for existing dirs while creating them, or run a test prior to calling this and find out which dirs already exist in CI way.
EDIT: i guess we could utilize FindFileCI for this as well, if we add an optional output parameter that would store the longest matching path found.

**Implementation issues**

We have a File::FindCI() function that helps finding a file in a case-insensitive way on cs-filesystems. But it misses one important bit: it does not process subdirectories, which is essential, as above script commands support relative subdirs in paths.

**Test game**

https://github.com/adventuregamestudio/ags/files/11992261/test--361fileci.zip
https://github.com/adventuregamestudio/ags/files/11992262/test--361fileci-proj.zip

Does a number of manipulations with files in script, using case mismatching filenames, and prints results to log.

**Comment by ericoporto** [comment]
I remember there was an idea to reverse the priority (filesystem vs game package) for some platforms in case it's useful for performance (look in the game package first, case sensitive there), these platforms would be like the web port and perhaps consoles/mobile. I imagine this reversal would be at compile time.

Just noting here for comments as I am not sure this is indeed required, I didn't want to create an issue only for it yet.

**Comment by ivan-mogilko** [comment]
> I remember there was an idea to reverse the priority (filesystem vs game package) for some platforms in case it's useful for performance (look in the game package first, case sensitive there), 

To clarify, files in game package are also case insensitive, it's been like that for over a decade.

**Comment by ericoporto** [comment]
Ah ok, that is fine then. How does this work, do we just lowercase files in directory and lowercase the file that we want and then search for a match? Or is there some kernel call or something that can get me the file already being case insensitive?

**Comment by ivan-mogilko** [comment]
> Ah ok, that is fine then. How does this work, do we just lowercase files in directory and lowercase the file that we want and then search for a match? Edit: I think that's the way. I was trying to look into wine code to see how things are done there as wine is case insensitive in case sensitive drives as far as I remember, but I couldn't figure out where it actually does this.

I am not sure if I understand the question; are you asking how two names are compared case-insensitive way? system returns file names as they are written in its filesystem, whatever we do to them is our own task.

**Comment by ivan-mogilko** [comment]
> Ah ok, that is fine then. How does this work, do we just lowercase files in directory and lowercase the file that we want and then search for a match?

If you are asking how names are compared technically? Either lowercasing beforehand, or using case insensitive string comparison, or calculating case-insensitive hash if it's a hashmap search. I don't think there's a big difference overall, but one method may have a benefit over another depending on the circumstances. I don't have actual numbers, but speculating, for example, if you iterate over a dir, then lowercasing each item may probably be slower than running ci compare, as lowercasing would imply copying a name to buffer and modifying it. But if you cache the dir contents somewhere, then bringing everything to same case could make comparison faster, I guess.
