### ISSUE TITLE
Puzzle in Chronicle of Innsmouth can't be solved,

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2030]
**Describe the bug**
At the end of Chronicle of Innsmouth, there is a puzzle that involves turning some rollers with glyphs,
When played using AGS 3.6 (latest stable or 3.6.1 beta) or ScummVM, the glyphs on the first roller don't seem
to appear normally, and there's also a weird misalignment.
This is how the puzzle should behave:
https://youtu.be/aAww8kmx4b0?t=6570

This is my playthrough (using my steam version on windows)
https://www.youtube.com/watch?v=zNvAIcSkxOo

**AGS Version**
3.6.0.48, 3.6.1.1

**Game**
https://store.steampowered.com/app/420180/Chronicle_of_Innsmouth/

**To Reproduce**
1. Load save [agssave.111.savegame.zip](https://github.com/adventuregamestudio/ags/files/11696779/agssave.111.savegame.zip)
2. Look at panel
4. Click first roller

**Desktop (please complete the following information):**
 - Win10

**Comment by ivan-mogilko** [comment]
For the reference, the game is made in AGS 3.4.0.16.

The puzzle seems working in 3.5.1.27 (release-3.5.1 branch).
Here's a save written by 3.5.1, in case that makes it easier to find what broken the game's behavior:
[agssave.112.savegame.zip](https://github.com/adventuregamestudio/ags/files/11713422/agssave.112.savegame.zip)

(i had to backport reading 3.6.0 saves into 3.5.1 to make this, wish we had a proper saves conversion tool)

**Comment by ivan-mogilko** [comment]
Pushed a fix: 38f65da028838c742dd184a75e33da4bffc38a90

**Comment by ivan-mogilko** [comment]
I will close this, if something is wrong this issue may be reopened, or a new one made.
