### ISSUE TITLE
GUI with alpha channel displays incorrectly

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2037]
**Describe the bug**
When a GUI background has an alpha channel, the buttons are drawn first and then the alpha is overlaid. This means that (e.g.) where alpha is 50% transparent, the buttons appear 50% transparent; and where alpha is fully transparent, the buttons are invisible.

**AGS Version**
Build 3.6.0.47, but it also applies in every earlier AGS version I have tried.

**To Reproduce**
Create a GUI.
Set backgroundcolor and bordercolor to 0.
Set a background picture that has an alpha channel.
Add one button that overlaps an area with alpha transparency (where the button itself does not have alpha channel).

**Expected behavior**
The alpha channel should be drawn first, then the buttons. The goal of the transparent background is to darken the room (over which the GUI is shown), not the buttons of the GUI.
If the backgrond picture does not have an alpha channel, the GUI is shown as expected.

**Screenshots**
![alpha_gui](https://github.com/adventuregamestudio/ags/assets/107799718/bd90b61b-60f3-4cf7-aa50-4e7efb0cb597)
The left side of the screenshot is from the AGS editor; the black area is 50% transparent; the pink area is 100% transparent.
Note how in the right side of the screenshot, the slider buttons (e.g. the one with the music note) are shown 50% transparent where they are on top of the alpha channel; and the buttons are clipped/hidden (e.g. the one with the loudspeaker) where they are on top of the fully transparent area.

**Desktop (please complete the following information):**
Windows 11.

**Comment by ivan-mogilko** [comment]
> Build 3.6.0.47, but it also applies in every earlier AGS version I have tried.

3.6.0 had a significant change to how the GUIs are rendered. Please tell which older versions have you tried that also have this bug?

Another thing, could you tell what is the value of option "GUI alpha rendering style" in General Settings?

Does this happen with all graphics renderers?

**Comment by Crystal-Shard** [comment]
Aha, I had missed that that option exists. GUI Alpha Rending Style "classic" has the bug. "Additive opacity" and "Proper alpha blending" do not have the bug. Thanks, I suppose that means it's fixed with these new(ish) two options.

**Comment by ivan-mogilko** [comment]
"Classic" mode is pre-3.*, I think. "Additive opacity" was the blending mode used in early 3.*, and proper alpha blending was introduced around 3.3 to fix these issues.

There's a similar separate setting for "sprites blending" nearby; this is mostly left for backwards compatibility with old games.
