### ISSUE TITLE
Plugins yet to be open sourced / ported

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#205]
Following plugins need to be open-sourced or stubbed (if sensible) to allow playing games on other platforms
(with related reported issues)

agsCredits
- #180

agsjoy (missing stubs)
there's a reimplementation: https://github.com/ericoporto/agsjoy but it's not built with the engine, nor referenced anywhere in readmes etc.
- #111

OtherRoom
- #26

(the list will be updated over time)

**Comment by Mailaender** [comment]
See also http://www.adventuregamestudio.co.uk/forums/index.php?topic=47388.msg636479467#msg636479467

I found some Open Source replacements for the ones used in @WadjetEyeGames:
* https://bitbucket.org/monkey0506/ags_shell
* https://github.com/onitake/agsteamstub

**Comment by ivan-mogilko** [comment]
> See also http://www.adventuregamestudio.co.uk/forums/index.php?topic=47388.msg636479467#msg636479467

Yes, this is my post :).

**Comment by Mailaender** [comment]
@monkey0506 can you help submitting a stub of agsteam with a Makefile to https://github.com/adventuregamestudio/ags/tree/master/Plugins?

**Comment by monkey0506** [comment]
I have limited experience using makefiles directly. IIRC the AGS2Client
project and AGSteamStub projects should both have Linux Code::Blocks
project files. I'll see if I can sort out a makefile from there.

**Comment by ivan-mogilko** [comment]
Currently feature-incomplete, but there is this open-source rewrite of agsjoy based on SDL2:
https://github.com/ericoporto/agsjoy

**Comment by ericoporto** [comment]
Not really that the previous version was not open sourced, but it wasn't possible to run in non-Windows systems:
https://github.com/ivan-mogilko/ags-spritevideo

**Comment by ivan-mogilko** [comment]
Hmm, this task turned out to be forgotten. Opened tickets per each respective plugin, with links to where to find info and source (if available):
agsCreditz: #1962
OtherRoom: #1963
