### ISSUE TITLE
Editor: allow to change the audioclip's source filename

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2051]
Per user's request: it's possible to change the sprite's source either importing a new sprite over the existing sprite, keeping the same ID, or modifying the Source Filename property directly. But it's not possible to do the same for the Audio clips.
The use case is when you have a number of placeholder clips in your projects, and want to replace them with real sounds without losing their IDs, so not deleting existing item and creating a new one.

The proposal is then to make AudioClip's SourceFilename property editable, with custom editor type that opens a file dialog upon clicking a "..." button, in a similar way to how it's done with sprites.

Note, modifying property type is trivial, but the actual issue would be in forcing a audio file's recache.
Also see #778.

**Comment by ericoporto** [comment]
I am working in a PR for this.

**Comment by ivan-mogilko** [comment]
> need help on how to make the property grid use ... instead of a down arrow. 

This is done by providing a property editor interface in attributes to property. You may see existing examples, such as Game Resolution.

**Comment by ericoporto** [comment]
Thanks! Made it work, added as a new commit in #2074
