### ISSUE TITLE
Backslash character in translation (TRS) file

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2060]
**Describe the bug**
In earlier versions of the editor, in TRS files, the backslash was treated as a regular character. In the current version, it is taken as an escape sequence.
For instance, in Heroine's Quest, the word "art\stico" appears in the Spanish translation, and the font file is used to display the "\" as an accented "í", so the string "artístico" is shown on-screen. This works in earlier AGS versions; in the current it gives the error  "Translation 'Spanish.trs' compiled with errors: " and "Unrecognized escape sequence \s."

**AGS Version**
Editor build 3.6.0.47

**Game**
Heroine's Quest

**To Reproduce**
1. Have a TRS file that includes the lines:
```
Lead Artist[and Animator
Jefe de dise~o art\stico[y animaci^n
```
2. Build the game.
3. The error message appears.

**Expected behavior**
Compatibility with earlier versions of AGS, i.e. that backslash followed by any letter (in TRS files specifically) is treated by the compiler as two distinct characters and not as an escape sequence.

**Desktop (please complete the following information):**
Windows 11

**Comment by ericoporto** [comment]
Does using `\\` results in the character you want?

> In earlier versions of the editor

Any idea on the version?

**Comment by AlanDrake** [comment]
Crimson backported the unescaping of text properties by 432ae84.
I wouldn't call it a bug, but a change in behavior for 3.6.1.

**Comment by ivan-mogilko** [comment]
The reported version is 3.6.0.47

**Comment by Crystal-Shard** [comment]
Yes, a straightforward fix for me would be to alter the TRS files. Thanks for your response!
