### ISSUE TITLE
New compiler: incorrect error report for missing function definition

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2066]
CC @fernewelten 

As of latest ags4, the new script compiler has a mistake when reporting missing function definition. Instead of telling the function's name, it seems to report a random type name (e.g. `int`), or even "(end of input)".

To reproduce use following script:
```
void Test();

function game_start()
{
    Test();
}
```

Resulting error message:
> Test.asc(8): Function '(end of input)' has been referenced in this file but never defined

**Comment by fernewelten** [comment]
I'm looking into it.

**Comment by ivan-mogilko** [comment]
Fixed by #2090
