### ISSUE TITLE
New compiler: incorrect parsing of multidimensional array inside a function arg list

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2068]
CC @fernewelten 

With a new compiler, using a multidimensional access syntax with commas conflicts with the function's argument list syntax.

Consider following script:
```
int arr[10, 10, 10];

void Test(int x) {}

function game_start()
{
	Test(arr[1, 2, 3]); // error
	Test(arr[1][2][3]);
	int value = arr[1, 2, 3];
	Test(value);
}
```

Compiler throws following error at the first Test() call:
> Test.asc(7): Expected just 1 parameters but found 3

remaining script works correctly.

PS. I started writing a proper test game in ags4, so probably will keep finding mistakes :).

**Comment by fernewelten** [comment]
I'll look into it. Compiler reads the function arguments from the end. It shouldn't blindly stop at commas, but skip when encountering a `]` until the matching `[` is found.
