### ISSUE TITLE
AGS 4: room's data.xml is saved without linebreaks

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2070]
**Problem**

I haven't noticed when this started, but the recent version of ags4 saves room's data.xml without any linebreaks, in a single line.
This makes reading it very difficult, and also complicates working with source control.

**Expected behavior**

The xml should be saved with each element on its own line, similar to how Game.agf is saved.

**Comment by AlanDrake** [comment]
It's just missing a `writer.Formatting = Formatting.Indented;` I'll push a commit quickly.

**Comment by AlanDrake** [comment]
Fixed by [a6193b7](https://github.com/adventuregamestudio/ags/commit/a6193b77a2e45ce59504b798fc90c1149b90dff4)

**Comment by ivan-mogilko** [comment]
[Seeing](https://github.com/adventuregamestudio/ags/commit/a6193b77a2e45ce59504b798fc90c1149b90dff4) how many repetitive assignment of same parameters is there, I think it's worth adding our own descendant/wrapper of XmlWriter which assigns all these in constructor.
