### ISSUE TITLE
AGS 4: saving a room sometimes changes their background and mask file binary contents because of pHYs chunk

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2071]
**Problem**

Testing recent ags4, I noticed that git sometimes detects changes to room image files, such background and mask pngs after I save the room, or rebuild whole game, although neither of these were changed in the editor.

~The changes seem to occur always in IHDR section of PNG.~
~The changes occur in one of the leading sections, prior to IDAT. There are sRGB, gAMA and pHYs sections present, but maybe something else.~
As [explained in the comment](https://github.com/adventuregamestudio/ags/issues/2071#issuecomment-1671813956), this is caused by pHYs chunk.

At first I was suspecting recent change to loading PNGs (#1772), but reverting to a previous version did not fix this.

**Steps to reproduce**
1. Open a project in latest ags4.
2. Make sure there's at least 1 room.
3. Make a backup copy of room N files.
4. Do Build -> rebuild all files.
5. Run a diff tool (like kdiff or similar) on old and new room image files, and notice that there are small changes.
Also if you use git, it will detect differences.

You may repeat Rebuild all. The results can be strange. Sometimes it changes the same file 1-2 more times in a row. Sometimes it stops. But restarting the Editor, and running Rebuild all again will create new differences.

**Expected behavior**

Ideally, if nothing was changed, then files should remain identical. Right now this will make working with source control annoying.

**Comment by ericoporto** [comment]
> The changes seem to occur always in IHDR section of PNG.

From [libpng website](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html).
> The IHDR chunk must appear FIRST. It contains:
>- Width:              4 bytes
>- Height:             4 bytes
>- Bit depth:          1 byte
>- Color type:         1 byte
>- Compression method: 1 byte
>- Filter method:      1 byte
>- Interlace method:   1 byte

It's weird these would change, did you use a hex diff tool to find this out?

**Comment by ivan-mogilko** [comment]
I did not look too close. It may not be IHDR, but anything else preceding IDATA. There are also sRGB, gAMA chunks visible, maybe others. An investigation is required.

**Comment by AlanDrake** [comment]
There's an extra sRGB chunk compared to before

**Comment by AlanDrake** [comment]
I've been trying , but I can't seem to generate new differences by rebuilding and restarting the editor.
Everything has consistently the srgb chunk now, with no other discernible difference.

All pngs are always being rewritten though, which could be avoided.

**Comment by ivan-mogilko** [comment]
So, I did a research, and found that this is caused by the pHYs chunk. According to [PNG specs](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html) pHYs chunk contains "pixels per unit" data, which does not relate to the pixel data itself, but rather to its representation on screen.

I used a [ExifTool utility](https://exiftool.org/) to compare two room masks saved in different times by AGS Editor, and they show a very slight difference in these parameters, for example:
1. 3777 pixels per meter (yes, meter lol)
2. 3778 pixels per meter.

So I assume this is likely some kind of a rounding mistake occuring each time a PNG is saved or loaded.

This is annoying as this changes the file from the source control's pov, and may both confuse users and may lead them to commit room images unnecessarily, thus causing repository bloat (something we wanted to solve with the open room format).

What are existing solutions here? I guess we may investigate following:
1. Why the room files are resaved every time? as @AlanDrake mentioned, this should be avoided. But besides that...
2. Is there a way to make it not write pHYs chunk at all?
3. If not, is there a way to write it in units that don't cause, or less likely to cause rounding errors?

**Comment by ericoporto** [comment]
About the PNG issue

> would it be acceptable for us to first save the PNG to a temp file / memory array using standard .NET functionality, and then cut particular chunk out before resaving into the final file

Yeah, this should work

> The better alternative seem to be getting some kind of a specialized image library, but this seem to be a too big change for such small fix.

If we do this through agsnative, may be an opportunity to experiment with some PNG library to add reading and writing to the engine - it wouldn't require to write compatible with many png options but reading it would possibly require some versatility.

**Comment by ivan-mogilko** [comment]
I decided to cover the major issue of redundant image re-saving first (see #2082), believing it will cover the most cases on its own. Basically, if the images will be only saved when they are changed by user, then a differences in 1 chunk will become no longer important, since there are changes to the image itself.

**Comment by ivan-mogilko** [comment]
Closed, hopefully will no longer be a problem after #2082.
