### ISSUE TITLE
Reduce CirrusCI usage for new policy, possibly offloading some tasks to GitHub Actions

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2076]
as of 1st of Setember, Cirrus CI will be limiting FOSS repositories in 50 compute credits per month, according to [their blogpost](https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/). Unfortunately, we use a tad more per month, around 140 compute credits.

I think we can move things that aren't use in a release to GitHub Actions - so macOS builds and the Linux CMake builds. This should lower the compute credit amount of Cirrus CI a bit so we can have some breathing time. Right now, I think the harder to migrate are the Windows stuff as we use VS with Platform Toolset v140, I don't know if this is available in the VS in GitHub Actions.

My fear with GitHub Actions is it seems its a bit harder to keep using older things there, and also overall Docker usage in GitHub Actions is a bit more work - you need to push Docker images to GitHub Package Registry and deal with it more manually.

## Proposed plan

- [x] Reduce use of macOS and non-releaseable tasks (#2079 and  #2083 )
- [x] Leverage [`changesInclude` and `changesIncludeOnly` functions](https://cirrus-ci.org/guide/writing-tasks/#supported-functions) to avoid builds when changes don't ask for - say the commit only updated a README for example. (#2083 )
- [x] For macOS CMake builds we can also look into leveraging ccache (it requires a C++17 capable compiler for building, so we can't use it in other places right now...)
- [x] Look into offloading to GitHub Actions
  -  #2077 has a version of this, but we can explore alternatives here too
  - made a new branch with a possible suggestion here https://github.com/ericoporto/ags/tree/ci-add-gh-actions
  - added in #2091 

## Additional context

There are probably other projects with similar problem, we could take a look into them

- https://github.com/scikit-learn/scikit-learn/issues/26879
- https://github.com/bitcoin/bitcoin/issues/28098
- https://github.com/numpy/numpy/issues/24280
- https://github.com/scipy/scipy/issues/19006
- https://github.com/MDAnalysis/mdanalysis/issues/4216
- https://github.com/opencontainers/runc/issues/3964

## Our previous monthly usage

<img src="https://github.com/adventuregamestudio/ags/assets/2244442/12301650-3f2d-4c4c-9124-94dbced2e8e9)" width=600>

**Comment by ivan-mogilko** [comment]
What is "compute credits", and how are these spent? Is it tasks per a rebuild, or tasks per day, etc?

Today the whole set of artifacts is rebuilt automatically any time the commit is pushed to repository.
Is it possible to make it configure it to build automatically only once per day, for instance, or even once per couple of days, while keeping an ability to run by hand?
Is it possible to configure to not rebuild something that was not touched by a change?

**Comment by ericoporto** [comment]
These compute credits vary per platform, in Linux, 3 compute credits gives 1000 minutes of 1 CPU. Windows is a bit more expensive at 4 compute credits for the same, and macOS is 15 compute credits - this is [detailed here](https://cirrus-ci.org/pricing/#compute-credits).

In July, which was an average month we used 24 compute credits in Windows builds, 61 compute credits in Linux builds and 79 compute credits in macOS builds. So it's my belief that simply moving the build tasks that aren't used for release to GitHub Actions we are already really close to the amount of freely available compute credits.

I would like to look into moving everything at some point though, because Cirrus has lots of weird outages, specially in the Windows builds that are really really slow. Other than this, building release and debug builds in the same container, would reduce usage too, and make things faster too.

**Comment by ericoporto** [comment]
I am looking into general strategies to reduce our usage in compute credits and it's possible to also scope a bit the tasks if they should run or not by what the change in the commit is

https://cirrus-ci.org/guide/writing-tasks/#supported-functions

We can for instance make changes in only markdown files to not run and other things similarly, which I can implement. I will edit the title to move to this approach

**Comment by ericoporto** [comment]
Had an idea, for the CirrusCI, to have a label and have so that PRs only run CirrusCI once you add this label.

**Comment by ericoporto** [comment]
I am closing this as the things I mainly had in mind are done, lets see how September will fare, since it will have the new policies in place.
