### ISSUE TITLE
AGS4: Trying to Create DynSprite from Save Game without Screenshot causes Crash

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2093]
**Describe the bug**
If you create a game and in general settings do not enable the "Save screenshots in save games" option, attempting to create a dynamic sprite from a save screenshot will cause the game to crash.

**AGS Version**
Used AGS 4, built from my Joystick PR https://github.com/adventuregamestudio/ags/pull/1759/commits/3901bba2373e0c49361257c10f188783fc0c5897, but should reproduce in regular ags4 branch too.

**Game**
Here is a 3.6.0 game, it DOESN'T crash, but it will crash in ags4!
[CrashScreenShot.zip](https://github.com/adventuregamestudio/ags/files/12344989/CrashScreenShot.zip)

Here is a three save files, one doesn't have any screenshot, the other two does have (saved from different general settings configs)
[CrashScreenShotSaveFiles.zip](https://github.com/adventuregamestudio/ags/files/12345003/CrashScreenShotSaveFiles.zip)

**To Reproduce**
1. Click the save menu and save the game
2. Click the menu to open load menu, and it should crash

**Expected behavior**
It should not crash, it could either create a placeholder bluecup or give a null pointer in the script. In 3.6.0, it gives a null pointer in script.

**Desktop:**
 - OS: Windows
 - Version 10

**Additional context**
The error is possibly in `Engine/ac/game.cpp`, in `read_savedgame_screenshot` function where there is this line

https://github.com/adventuregamestudio/ags/blob/aa0383dd577b14ba54d04453f0e9e9347ba94eee/Engine/ac/game.cpp#L973

It assumes `desc.UserImage` contains a valid bitmap and doesn't deal with the case where that pointer is null.

**Comment by ivan-mogilko** [comment]
Fixed in master a1032d1018a86d611f8cfe1b82320d54d3553f11 and ags4 971cd932113f8a30ad9caf46b238150060263087

**Comment by ericoporto** [comment]
Thanks! Found the commit that introduced the issue, just noting here for reference (https://github.com/adventuregamestudio/ags/commit/aca47b9f466fe41d73d99a15b9f0ae41e65c6926)
