### ISSUE TITLE
Allow cancelling GUI/button clicks when you hold and move the mouse away

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2100]
**Describe the problem**
There is an entry on the [Xbox Accessibility Guidelines](https://learn.microsoft.com/en-us/gaming/accessibility/xbox-accessibility-guidelines/107#implementation-guidelines) that is very informative

> The down click or down press (the down event) on an item doesn't automatically activate that item. Activation occurs on the up event, which is when the button or press is being released. (For example, when a player hovers their mouse over a button and clicks, the button’s function is not immediately activated as the player presses their mouse button “down.” The button is only activated on the up event, or as the player is releasing the mouse button. This also applies to touch-screen experiences.)
>
> A mechanism is available to cancel the action before completion. (For example, if a player touches down on the wrong location or item, they can move their cursor or finger away from that location before the up event or click release. This cancels the unintended action.)
>
> If a mechanism to cancel the action isn't available, a simple mechanism to undo the action is provided.

I noticed this is true for Windows and Windows Forms (AGS Editor behaves like this!)

**Suggested change**
By leveraging the mouse up button on GUI and button clicks, it's possible to check that the mouse position is not in the GUI/button area anymore and don't emit the event, this would allow canceling the mouse click action if you suddenly change your mind.

**additional context**
This may break previous behavior - it was possible to post pone the click by holding, but it would still execute on releasing when mouse is not in the control area, at least in AGS 3.4.3.

**Comment by ivan-mogilko** [comment]
But this is already working like this, testing the 3.6.0.

**Comment by ivan-mogilko** [comment]
> A mechanism is available to cancel the action before completion. (For example, if a player touches down on the wrong location or item, they can move their cursor or finger away from that location before the up event or click release. This cancels the unintended action.)

If we would have to follow these guidelines for real, then clicks on any objects in game must also act the same. Currently they are all triggered by the mouse down event, which sends on_mouse_click.

If it's required to support the aforementioned rule, then it should be applied to **ALL** the interactive elements in the engine. To help users achieve similar behavior in script we would also need to implement separate "mouse down" and "mouse up" callbacks in script (currently it may only be done by testing for mouse button states in re-exec).

**Comment by ericoporto** [comment]
I think that the things that don't have a "pushed state" (with visual feedback) are fair to be on mouse down, like the objects you mention and well, speech skipping. I was thinking only GUIs would behave like this - similar to the Windows OS, the native stuff behaves like this, but everything else doesn't.

**Comment by ericoporto** [comment]
I will close this to think this more thoroughly and rewrite, re-analyzing now it looks like it would have to be in a case by case basis.

**Comment by ivan-mogilko** [comment]
I suppose it's better to open a ticket regarding these accessibility guidelines, and investigate if AGS has all features and options to let configure the game for these.
