### ISSUE TITLE
Android native static libraries for Lua need rebuilding

### ISSUE THREAD

**Issue by monkey0506** [adventuregamestudio/ags#211]
The Android NDK Revision 10c removed several symbols which the currently compiled Lua libraries (Android/nativelibs/*/lib/liblua.a) depend on:

`Removed the following symbols from all architectures: get_malloc_leak_info, free_malloc_leak_info, __srget, __swbuf, __srefill, __swsetup, __sdidinit, __sflags, __sfp, __sinit, __smakebuf, __sflush, __sread, __swrite, __sseek, __sclose, _fwalk, __sglue, __get_thread, __wait4, __futex_wake, __open, __get_tls, __getdents64, and dlmalloc.`

Rebuilding the Lua library directly from the 5.1 source code (http://www.lua.org/source/5.1/) as part of the build process for the AGSLua plugin works with one exception requiring source modification (Android NDK does not apparently fully define struct lconv as returned by localeconv() -- this is only used here to convert decimal separator to current locale, but can be defaulted instead).

To prevent introducing the entire Lua library source code into the repository, the static libraries should be rebuilt for Android architectures. Note that the Lua libraries should not normally need to change, so pushing changed binaries in this case seemingly makes sense, though we might consider removing them from the repository and hosting them elsewhere.

**Comment by ivan-mogilko** [comment]
Well, @monkey0506 never updated the thread.

Not sure if this is applicable anymore. The building process of Android port has since changed to not using precompiled libraries and we now have lua library sources as an optional submodule.

So, closing this now.
