### ISSUE TITLE
Guard Duty Illegal Exception (immediate crash)

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2110]
**Describe the bug**
On latest 3.6.0 stable or 3.6.1 beta, Guard Duty is no longer playable and crashes immediately with a
Illegal Exception error:
An exception 0xC0000005 occurred in ACWIN.EXE at EIP = 0x00494C80; program pointer is +1004, engine version 3.6.0.51, gtags (4538,48)
An exception 0xC0000005 occurred in ACWIN.EXE at EIP = 0x00488C4D; program pointer is +1004, engine version 3.6.1.6, gtags (4538,48)

Attached crash dumps
[crashinfo.zip](https://github.com/adventuregamestudio/ags/files/12432574/crashinfo.zip)

**AGS Version**
3.6.0.51, 3.6.1.6 downloaded for github

**Game**
Guard Duty (GOG)

**To Reproduce**
Just start the game

**Desktop (please complete the following information):**
 - Windows 10

**Comment by ivan-mogilko** [comment]
This is caused by a call to Object.SetProperty, with an incorrect object ID.

The object properties are stored in a vector since commit 5f3b8eb509c9535c75b401f9b7257f7c7acd0e6d, prior to that they were stored in a array of a fixed size MAX_ROOM_OBJECTS.

**Comment by ivan-mogilko** [comment]
Yes, it appears the script is running a loop over `object[]` array from 0 to "max objects", setting some properties, disregarding the fact that there may be less actual objects in the room. This is another case of AGS being too permissive in some cases and not warning a developer that something is wrong.

**Comment by ivan-mogilko** [comment]
Pushed commit ed26772ef8bc3f9a11713da6d68028bfbe1a3431 to release-3.6.0 branch, and 6ad4b220d75a32ea8df959e9a7b7f1ecb21d0c26 to master branch (where 3.6.1 is being developed atm)

**Comment by tag2015** [comment]
Excellent, thanks for the quick fix! I can confirm that the game now works properly.
