### ISSUE TITLE
Ordering Character to walk while it is already walking will make it halt for 1+ frames

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2125]
**Describe the bug**
If a Character is walking, and is ordered to walk again (e.g. by calling Character.Walk), then the character will visibly halt on a current position for 1 or more frames (this is unclear) before starting to move towards the new destination.

This behavior may be quite irritating for players, who may have a habit to click around multiple times while character is walking. Similarly this is annoying to see when you change your mind in the middle of the walk, and order to walk elsewhere. Generally, this seems like a mistake in the engine.

I noticed that this behavior is best observed with "movement linked to animation" and slow movement speed, but it also actually happens if that setting is off too, only may be harder to notice.

A curious thing is that although movement stutters, the walking animation does not have same problem.

**AGS Version**
As far as I know, this happens for a very long time. At least in every version in 3.* generation, but maybe in earlier ones too.

**To Reproduce**
1. Configure player character to have MovementLinkedToAnimation enabled, and MovementSpeed 1. This is not required for the error to happen, but will make it easier to notice and thus test it.
2. Start the game, order character to walk. Then start clicking repeatedly on the same spot.
3. Notice how character "stutters" whenever there's another walking order. If you click fast enough, it will never change position at all (this is because movement speed is low). On another hand, notice that animation runs without extra delays.

**Expected behavior**
If a new movement order is issued while Character is walking, there has to be a smooth transition onto the new path. That is - a character does not halt and starts walking on a new path same game frame. In other words, this should look as if it keeps walking same path as before.

**Additional context**
There's a number of timers related to walking. I counted 3 that may be relevant: `wait`, `walkwait` and `walkwaitcounter`.
This may also be related to how pathwalking works in AGS, where the path is split into a number of "steps", and the rules of how these steps are performed. Or not, I could not figure out yet whether that has anything to do with this.

**Comment by morganwillcock** [comment]
> If a new movement order is issued while Character is walking, there has to be a smooth transition onto the new path.

Some people may prefer to have the delay as an indication that the instruction to move was registered, otherwise something like a mouse click may not have any feedback to indicate that it was successfully received.

If the delay gets removed entirely it is probably worth checking that it would be  possible to recreate the original behaviour with some scripting.

**Comment by ivan-mogilko** [comment]
I possibly found a culprit. It appears to be a part of the MoveList logic.

From what I understand, it breaks whole path into tiny segments, and tells how many pixels to move "per step" (this is members `xpermove` and `ypermove`). But besides that there's a variable called `onpart`. This variable is incremented once per game frame, and the actual move is calculated like `xpermove * onpart`. The thing is that xpermove may be <1 (a fraction of pixel), so it takes more than 1 game frame to start moving visibly.

If this is the primary issue here, then I wonder how this may be dealt with. Theoretically, if a seamless move is desired, then a remaining fraction of a move time from the previous movelist should be converted into a starting fraction of a new movelist.

**Comment by ericoporto** [comment]
> it breaks whole path into tiny segments, and tells how many pixels to move "per step" 

This is what I tried to explain you the other day on why it's not possible to change the walkspeed while walking, as speed is pixels per step in the non-glide mode. 

Note that in ags4 there are some changes in the other parts of the logic as there the fixed stuff has been rewritten to use floats. Overall, if x and y were floats more of this logic could be simplified - the delay to move stuff would simply move in floats.

**Comment by ivan-mogilko** [comment]
> This is what I tried to explain you the other day on why it's not possible to change the walkspeed while walking, as speed is pixels per step in the non-glide mode.

This is not directly related to glide or non-glide mode, the glide mode only affects how animation and move time is synced.
In other words, it affects when and how often the movelist's counters are incremented.

**Comment by ivan-mogilko** [comment]
By the way, I now genuinely wonder if it would be hard to recalculate these xypermoves when changing move speed.
If we know the previous move speed, then possibly this will be a matter of dividing each "move" on old speed and multiplying on a new speed.... unless i miss anything.
