### ISSUE TITLE
5 Days a Stranger Multilanguage - special characters don't display properly

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2134]
**Describe the bug**
This could be a bug with the game, so feel free to close.
There is a multilanguage version of 5 days a stranger (not the "special version"), that includes multiple translations.
Many language-specific letters (e.g. german umlauts, cyrillic, etc) display improperly or are replaced with something else.
Setting the game to lowres or hires makes no difference.

**AGS Version**
latest 3.6.0 / 3.6.1

**Game**
[link](http://www.fullyramblomatic.com/5days/5daystran.zip)

**Screenshots**
![de](https://github.com/adventuregamestudio/ags/assets/1673892/961d0bdb-638c-456d-8c60-046d656c89dd)
![fi](https://github.com/adventuregamestudio/ags/assets/1673892/59df7e9e-0df4-47b9-8fab-f903900c819e)

**Desktop
- Windows 10

**Comment by ivan-mogilko** [comment]
I ran the original game exe, and it does exact same thing, so this is a problem with translation data mismatching fonts, or fonts not containing proper glyphs.
