### ISSUE TITLE
Support acsetup.cfg in utf-8 encoding (and maybe in ansi too)

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2137]
**Describe the problem**
acsetup.cfg is the last file that only supports ansi encoding, but unfortunately there are some free strings in the file that can have utf-8 names in them.

**Suggested change**
It would be nice if acsetup.cfg could support utf-8. It would be even nicer if utf-8 and ansi could be supported, somehow. Supposing it can only support one encoding, then we just always assume things are utf-8 in acsetup.cfg from now on.

The editor has to be modified so that the acsetup.cfg files it creates are utf-8 too.

**Additional context**

- See forums here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=61002.0

**Comment by ivan-mogilko** [comment]
I think this is really a bug, because this makes winsetup display the title text wrong in unicode formatted games.

**Comment by ivan-mogilko** [comment]
Hrm, reading microsoft articles on WritePrivateProfileString, it seems like there's no way to explicitly control the output format:
https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-writeprivateprofilestringa
https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-writeprivateprofilestringw

The only supported formats are ANSI and "Unicode", but these articles never explain what "unicode" format means. I suspect it may even be a two-byte chars, which we do not want. Also, the docs say that:
> If the file was created using Unicode characters, the function writes Unicode characters to the file. Otherwise, the function writes ANSI characters.
All this sounds quite unreliable.

This might mean that we cannot use WritePrivateProfileString for this, and will have to reimplement our own ini file writing and reading. There's one implementation done in C++ that engine uses. It may be rewritten in C# perhaps, optionally, for a quicker solution, we could reuse a C++ one by, say, passing a prepared map of key/values into a AGS.Native library.
