### ISSUE TITLE
Editor: Import GIF transparency lost when transparent palette index is not zero

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#2156]
**Describe the bug**
Importing a transparent gif  with "Leave as-is" will lose transparency if the transparent color is not index 0.

**AGS Version**
Tested on 3.6.1 and 4

**To Reproduce**
1. Import attached gif and check "Leave as-is"
2. Note that the preview is correct in import window
3. Click import
4. From Sprites pane it can be seen that the sprite has lost transparency

**Expected behavior**
Transparency should be applied no matter at which palette index is set at.

Example gif with transparency at palette index 5:
![options_chkbox_sel](https://github.com/adventuregamestudio/ags/assets/1430815/f0856d29-7b92-4f59-af04-a283b26a46bc)

**Comment by ivan-mogilko** [comment]
This reproduces in 3.6.1 editor too, perhaps this has been always like this?

**Comment by ivan-mogilko** [comment]
First need to find out whether it is the Editor itself, or its dependency (Magick.NET) responsible for this.

**Comment by AlanDrake** [comment]
So, from my first look into it, it appears that this problem has always been there from the very beginning.
`sort_out_transparency` has a `if` that forces the assumption that palette 0 is the transparent one when "Leave as-is" (SIMP_LEAVEALONE) is chosen, but even when commenting it, it apparentl fails to determine the correct transparent index color through `GetMaskColor()` call.

For some reason that part of the code isn't available to the debugger so I ended up pausing my investigation for now.

**Comment by ivan-mogilko** [comment]
> For some reason that part of the code isn't available to the debugger so I ended up pausing my investigation for now.

You might need to configure debugger type for AGS.Native as "Mixed" (on "Debugging" page), and check "Enable native code debugging" option in the Editor's project settings too.

As for GetMaskColor, it is allegro's internal thing, completely unrelated and independent to the imported source image. It always returns same value depending on the bitmap's bitness.

**Comment by AlanDrake** [comment]
Great, in the meanwhile I just found out that 8bit palettes are being mangled to 16bit colors inside `CreateBlockFromBitmap()`, it was striking me odd, how some colors from gifs were a bit off compared to pngs... but I thought this behavior had been removed a long time ago.

**Comment by AlanDrake** [comment]
Alright, I determined that `bmpPalette[i].A` does correctly track the transparency for 8bit gifs.
It's just not being used under the assumption that palette index 0 is always the transparent color.
