### ISSUE TITLE
Framerate caps at 60

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2158]
**Describe the bug**
Heroine's Quest has a speed slider, that goes from 30 to 100 and then calls SetGameSpeed with that value. A player reports that with AGS 3.6, framerate goes no higher than 60, whereas in the earlier build using AGS 3.3, the game managed a higher framerate. Another player reports that the framerate caps at 50 for him.
The VSync checkbox (in winsetup) is off. It seems that either the game plays noticeably slower in the new engine, or the game speed caps at the VSync rate even when VSync is disabled.

I'd say this is not urgent to fix (who plays at 100 fps anyway?) but I'd like to be able to answer to these players what causes this.

**AGS Version**
3.6.0.52

**Game**
Heroine's Quest 1.2.9

**To Reproduce**
1. Skip all the title and intro screens
2. Press escape to open the control panel
3. Set speed slider to maximum
4. Check framerate

**Expected behavior**
Framerate should be 100, if the system permits.

**Comment by ivan-mogilko** [comment]
Hmm, that is a strange issue. I confirm that it happens. But this does not look like a engine running slower, because the fps is fixed at a round value. This seems rather a mistake at setting and/or maintaining game update rate.

**Comment by ivan-mogilko** [comment]
@Crystal-Shard I found that the game is setting vsync in script (using System.VSync property).

**Comment by ericoporto** [comment]
According to #675 , VSync at runtime only worked with the software renderer in the past.

**Comment by Crystal-Shard** [comment]
Ah, that explains it. Thanks. Are there any renderers in 3.6.0 that do not support vsync?

**Comment by ericoporto** [comment]
According to that same issue no, VSync is working correctly in all renderers.

**Comment by ivan-mogilko** [comment]
Unfortunately there's no way to check from script. There's System.SupportsGammaControl but no System.SupporsVSync.

**Comment by Crystal-Shard** [comment]
Ok, I'll fix this in code. Thanks for the feedback!
