### ISSUE TITLE
Text window corner pieces

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2161]
**Describe the bug**
![overrun](https://github.com/adventuregamestudio/ags/assets/107799718/e1d86490-2612-4fc0-becb-b62b6a433ead)
This is a text GUI. Note that the three righthand parts end in a bit of transparency.
The center part cuts off before the center-right part starts. This is correct.
The top-center part extends to the full right of the GUI, so it is shown underneath the top-right part.

**AGS Version**
3.6.0.52
(but I'm pretty sure AGS has always worked that way and I'm either overlooking something or using GUIs in new and exciting ways)

**To Reproduce**
1. Import this GUI into a game: https://crystalshard.net/test/textbox.guf
2. Show text with that GUI.
3. See error

**Expected behavior**
The top-center (and bottom-center) parts should cut off where the top-right (and bottom-right) parts start.

**Screenshots**
See above

**Desktop (please complete the following information):**
Windows 11

**Comment by ivan-mogilko** [comment]
Yes, it appears that ags historically only clipped central part, but never top and bottom edges. That's probably an oversight, that was never fixed.
https://github.com/adventuregamestudio/ags/blob/e3ad2aad411ecc6ed08bdb6b6c52880e2ab0937b/Engine/ac/display.cpp#L672

**Comment by Crystal-Shard** [comment]
Thanks. You wrote "added this to the [3.6.0 maintenance]" -- does that mean it will be part of AGS 3.6.0 patch 6 eventually?

**Comment by ivan-mogilko** [comment]
> Thanks. You wrote "added this to the [3.6.0 maintenance]" -- does that mean it will be part of AGS 3.6.0 patch 6 eventually?

From a first glance this is really an old bug, and *likely* fixing this should not break anything, as I doubt that such behavior was ever intended; so I thought it should be fixed in 3.6.0 too.

**Comment by Crystal-Shard** [comment]
That would be great!
Because it's for [https://www.adventuregamestudio.co.uk/forums/ags-games-in-production/sir-bob-squire-for-hire/](this game in progress) and it would be nice to have that textbox fix soon-ish (by which I mean, no need to hurry but I much prefer having it in 3.6.0 instead of waiting for the next stable).
Thanks!

**Comment by ivan-mogilko** [comment]
I had a change in mind after reading the code more, and thinking about this. It's hard to tell how likely or not, but in theory some of the older games could account this behavior or could maybe even use it for artistic purpose.
If such game is found, then for backwards compatibility we would have to make a version switch based on compiled game version. But the current convention is to not add new version tags after the version was already released, so this better go into the next version (3.6.1).

I pushed a commit there now: 11fecdaaf125cf94018af5a9c2ff63748bee49ae

**Comment by Crystal-Shard** [comment]
Ok, I see where you're coming from, but graphically speaking I'd find it highly unlikely that anyone would do that.
Perhaps a better approach would be to ask on the forums whether anyone can remember any game doing that, instead of adding a backwards-compatibility version switch that nobody would actually use? Forum users tend to have a good memory for such things.

**Comment by ivan-mogilko** [comment]
> Ok, I see where you're coming from, but graphically speaking I'd find it highly unlikely that anyone would do that.

In the past years we encountered numerous cases where old games had an "unlikely" script or setup, or when their performance dependent on coincidental behavior in the engine.

**Comment by ivan-mogilko** [comment]
Very well, I will add this to 3.6.0 too, without any checks, for now.

If it will turn out to be necessary in old games, i will have to use the 3.6.0 data version tag to make a condition, and hope that this was never utilized in 3.6.0.

**Comment by ivan-mogilko** [comment]
Pushed to release-3.6.0 branch too: a77393abc2353a7d8309b7edf1f0ff582c34778c

**Comment by ivan-mogilko** [comment]
The fixed 3.6.0 build may be tested using this download:
https://cirrus-ci.com/task/5479288426725376

**Comment by Crystal-Shard** [comment]
Thank you. I can confirm that it works now.
