### ISSUE TITLE
Font height not detected properly

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2169]
**Describe the bug**
If I take the attached font and import it at 28 points, then have a GUI label with two lines, the lines will overlap. In other words, the engine does not properly detect this font's height, because in (e.g.) MS Word it shows normally. As a workaround, I can set the font's LineSpacing property manually, but it still feels like a bug that should be logged.
[agsfnt2.zip](https://github.com/adventuregamestudio/ags/files/12843978/agsfnt2.zip)

**AGS Version**
3.6.0.52

**To Reproduce**
1. Import the font
2. Make a GUI label using that font and with at least two lines of text
3. See error

**Expected behavior**
The lines don't overlap.

**Desktop (please complete the following information):**
Windows 11

**Additional context**
Not urgent since a workaround is available.

**Comment by ivan-mogilko** [comment]
AGS historically did certain "fixups" for the font's height and its vertical position (ascender).
Since 3.6.0 there are 2 switches that let disable these fixups.

1. General Settings: "TTF fonts height used in the game logic".
2. Per font setting "TTF font adjustment" (also exists in general settings as a default value).

Please tell which values do these properties have currently in your game, and will other options improve the situation?

**Comment by Crystal-Shard** [comment]
Let's see. With height=nominal and adjustment=nothing, I get a big overlap.
With height=nominal and adjustment=resize, I get the same overlap except all letters move about 20 pixels up.
With height=full and adjustment=resize, I get much less overlap but still enough overlap to make it a bit hard to read.
With height=full and adjustment=nothing, there's no overlap but I'd say the line spacing becomes too big.

I'd say using the LineSpacing parameter is still my best approach here.

**Comment by ivan-mogilko** [comment]
So, having height "full graphical height" still does not work well... This might mean that our font rendering library is still doing something wrong. I will check out what happens, but chances are this is simply an old library's fault, in which case we cannot do anything until the library gets upgraded or replaced.

**Comment by ericoporto** [comment]
> cannot do anything until the library gets upgraded or replaced

See #1528

**Comment by ivan-mogilko** [comment]
Need to retest this font to see if this is related to the issue of font's reported ascender/descender not matching individual glyph sizes, see #2388.

**Comment by ivan-mogilko** [comment]
Apparently I was not reading comments very well...

> Let's see. With height=nominal and adjustment=nothing, I get a big overlap.
With height=nominal and adjustment=resize, I get the same overlap except all letters move about 20 pixels up.
With height=full and adjustment=resize, I get much less overlap but still enough overlap to make it a bit hard to read.
With height=full and adjustment=nothing, there's no overlap but I'd say the line spacing becomes too big.
> 
> I'd say using the LineSpacing parameter is still my best approach here.

So, "With height=full and adjustment=nothing" - that is a "true" settings combination, without adjusting for backwards compatibility. This seems to give the useful effect. Default linespacing being too big may be an issue, but it's just how font is configured by its creator.

Applying custom linespacing is definitely a way to go in this case, but I'd say there's no real engine bug here.
