### ISSUE TITLE
Display() in eEventEnterRoomBeforeFadein

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2179]
**Describe the bug**
Assuming screen transition is set to eTransitionFade, then calling Display() during the Enter Room Before Fadein event will show a black screen. This does not apply to the very first room shown (presumably because the engine fades between rooms, not before the first one).
This makes it seem like the game hangs. Earlier AGS versions would show the message box (and the screen).
This can happen because earlier versions didn't have the After Fadein event, and certain events can be checked globally at the entry of each room (e.g. "you are being followed" or "you are getting hungry").

**AGS Version**
3.6.0.52

**To Reproduce**
1. Make an on_event function with: if (event == eEventEnterRoomBeforeFadein) Display ("Hello");
2. SetScreenTransition (eTransitionFade);
3. Have at least two rooms
4. Enter the second room to see the error.

**Expected behavior**
Either show the message box anyway, or print to the warning.log file that the game displayed a message box while the screen was blanked out.

**Desktop (please complete the following information):**
Windows 11.

**Comment by Crystal-Shard** [comment]
(Not actually a big deal since I'm using eEventEnterRoomAfterFadein now, but may affect compatibility for older games)

**Comment by ivan-mogilko** [comment]
Hmm, so you are saying that they were displaying in older games? In such case this should classify as a regression.
Could you point to an example?

We had a number of drawing optimizations in the past years, this change could be caused by one of them.

Besides compatibility, it's a question of design. First we need to decide whether these message boxes are supposed to be shown in between room load and room transition effect, while the room itself is not drawn yet. I may see both for and against arguments. For instance, this message box is often used for debugging purposes, as it is fully blocking whole game.

**Comment by Crystal-Shard** [comment]
Right. I use it for debugging, e.g. when entering a room check if all the hotspots are on a walkable area. I've checked my own games and can't find any examples outside of debugging. That also means it's unlikely to show up in the release version of these games.

According to release notes, eEventEnterRoomAfterFadein exists since 3.6.0.

**Comment by ivan-mogilko** [comment]
> According to release notes, eEventEnterRoomAfterFadein exists since 3.6.0.

That's event arg for a global "on_event" function, but individual Room's "after fade-in" event exists for over a decade at least.

**Comment by ivan-mogilko** [comment]
So, I tried old versions of AGS, down to 2.52, and in none of them Display's message is shown in "Before fade in" event.

**Comment by Crystal-Shard** [comment]
FWIW I'm using the on_event() function with parameter eEventEnterRoomBeforeFadein, maybe that makes a difference.

Anyway, it's not that important to have the ability to show message boxes at that exact point, but I do feel this should print a message in the log file.

**Comment by ivan-mogilko** [comment]
Added warnings: d7235fcef3c3ff042f9a4f9eed6ac0a250296927
