### ISSUE TITLE
MAGICNUMBER not found before Audio Clips.

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2182]
**Describe the bug**
I'm in the process of upgrading A Tale of Two Kingdoms from AGS 3.3 to 3.6. In the new build, I get the following error when restoring a saved game. I'm not sure what this even means.
Error: Unable to restore the saved game. Inconsistent format, or file is corrupted. MAGICNUMBER not found before Audio Clips.

**AGS Version**
3.6.0.52
legacysave_assume_dataver=43 and legacysave_let_gui_diff=1 are set.

**Game**
A Tale of Two Kingdoms
(I'll send you my current build over PM)

**To Reproduce**
1. Restore this saved game: [agssave.043.atotk.zip](https://github.com/adventuregamestudio/ags/files/12906636/agssave.043.atotk.zip)
2. See error

**Expected behavior**
The saved game is restored.

**Desktop (please complete the following information):**
Windows 11

**Comment by ivan-mogilko** [comment]
The last check before the GUI's "magic number" is the number of Views. This check passes, which means that number of views in saves and game matches, but also that format mismatch happens somewhere in between.

This could only be during reading views. Unfortunately the save does not make any checks for loop and frame counts. Have you by any chance change a number of loops or frames in this game?

I think i had the old version of this game somewhere, I might test same save in it too.

**Comment by Crystal-Shard** [comment]
The old version is on Steam, I'm pretty sure I've given you a key years ago.

Let me check what I did with views.

**Comment by Crystal-Shard** [comment]
Yes that's actually it. There was a rarely-used walk view used for goblin disguise, and the standard walk view has a few animations (e.g. pick up item) in it. So picking up things while disguised would crash, and I fixed that by adding a few loops with existing sprites.

...I can undo that easily, and add code to play animation unless in goblin view.

**Comment by ivan-mogilko** [comment]
I will adjust the error message to something easier to understand.

**Comment by Crystal-Shard** [comment]
Ok, here's a weird one...

It turns out that the AGS3.3 version had a reference to Music42.ogg which did not exist, and wasn't played anywhere either.
Importing this to AGS3.6 will quietly remove this reference from the list of audio clips (this probably shouldn't happen).
Loading a saved game will fail if the number of audio clips doesn't match (I'm not sure why this check is imporant).
So after fixing the above issue, I ran into this one.
I have fixed this by creating a Music42.ogg file and manually re-inserting it in game.agf and that seems to work.

**Comment by ivan-mogilko** [comment]
> Loading a saved game will fail if the number of audio clips doesn't match (I'm not sure why this check is imporant).

This is a mistake on engine's side. I just noticed and fixed it too. The temp build is available here:
<https://cirrus-ci.com/task/5304763974156288>

**Comment by Crystal-Shard** [comment]
> > This is a mistake on engine's side. I just noticed and fixed it too. The temp build is available here: https://cirrus-ci.com/task/5304763974156288

That doesn't help; I now get
```
Error: Unable to restore the saved game.
Game object initialization failed after save restoration.
Invalid audio clip index.
```

**Comment by ivan-mogilko** [comment]
Sigh, I should add a clip index information to let diagnose this.

**Comment by Crystal-Shard** [comment]
It's weird. With the previous build (which is the one from #2161 ) restoring does work if I manually put the audio clip in game.agf. With the build you just posted here, it appears to work _neither_ with nor without the audio clip in game.agf.

**Comment by ivan-mogilko** [comment]
I made a mistake and broken the save format.

**Comment by Crystal-Shard** [comment]
Sure, check your inbox. This build has the audio clip added and it seems to work fine.

**Comment by ivan-mogilko** [comment]
The new build is here:
<https://cirrus-ci.com/task/5949274081460224>

**Comment by Crystal-Shard** [comment]
Yes, that works (with the music file NOT added to game.agf)
