### ISSUE TITLE
Disabled language option in winsetup

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2192]
**Describe the problem**
All of our games that have translations start with a language selection screen at startup; for instance, Heroine's Quest. We have adopted this practice to give greater prominence to the translations (and frankly, some of our games have a lot!)
This means that these games will ignore the language setting in acsetup.cfg.

**Suggested change**
In winsetup, it should be possible to disable the Game Language pulldown (graying it out and defaulting it to "game default"); for instance by taking the following to acsetup.cfg,
```
[disabled]
language=1
```

**Comment by ivan-mogilko** [comment]
I added this
```
[disabled]
translation=1
```
because the option is called `translation` elsewhere.
