### ISSUE TITLE
Evaluate porting ScummVm blitting optimizations

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2194]
ScummVm port of AGS engine uses a different allegro library, apparently rewritten from ground up using C++. They recently had through GSoC a very interesting optimization to their allegro library blitting and blending operations using SIMD instructions.

- https://blogs.scummvm.org/eklipsed/
- https://github.com/scummvm/scummvm/pull/5144
- https://github.com/scummvm/scummvm/pull/5303
- https://github.com/scummvm/scummvm/pull/5304

I think the results are interesting. In my experience when profiling higher resolution games (mostly Dave's and test games), of the part of the code that renders stuff, only at most 20% of the time of those is spent in blitting/blending things (at least when using the Directx renderer). Still, maybe, with the existing sprite-to-texture pipeline it could be relevant to port those? I don't know the details of how the ScummVm rendering works and if maybe these functions are more relevant there. If some ScummVm dev passes by, it would be interesting to get their view here.

Also possibly time is better spent by coming up with a "texture-file" since we have a texture cache already, and then skipping all the sprite-to-texture pipeline for "sprite-file" things that have a "texture-file" pair, but I don't have yet a good enough idea of how that would work to write a ticket.

**Comment by sev-** [comment]
We do not use Allegro, and we had to replace it. Our backend works with plain squares of pixels aka Graphics::Surface, thus, theoretically it is possible to take our routines as is. The project licenses are compatible.

**Comment by ericoporto** [comment]
I opened this with an expectation of better understanding why this is necessary and if it's needed for us - it seems ScummVm uses something more similar to a software drawing, so I think this is not necessary to us.

**Comment by ivan-mogilko** [comment]
I missed this sentence:

> Still, maybe, with the existing sprite-to-texture pipeline it could be relevant to port those?

Of course, since these are related to software blitting, they are not applicable to rendering textures.
These optimizations would be useful to Software renderer, and possibly to DrawingSurface operations.

**Comment by criezy** [comment]
It could indeed possibly be useful for the software renderer, and for the blending function implementations (which I think are used by all the renderers?). But the way we handle the blending modes in the ScummVM AGS engine is very different from the way it is handled in the standalone AGS, and our code is probably more complicated that what you need (as we have different constrains on what color format is available depending on the platform). So the mapping to your code  would not be straightforward.

**Comment by ivan-mogilko** [comment]
Blending functions are used primarily by software renderer, but others use this route only in backwards compatible mode, when they need to simulate old-style imagery. In "normal" mode they are using shaders.
