### ISSUE TITLE
Disable "smooth scaled sprites" in winsetup

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2198]
**Describe the problem**
I can add options in acsetup.cfg to disable a few buttons in winsetup (notably "scaling method" and "render sprites at screen resolution") that, for certain specific games and art styles, the artist believes will not look good on-screen.

**Suggested change**
In winsetup, it should be possible to disable "Smooth scaled sprites" checkbox, by adding the following to acsetup.cfg,
```
[disabled]
smooth_sprites=1
```

**Comment by ivan-mogilko** [comment]
I guess this is also small change enough to add to the next 3.6.0 patch.

**Comment by ivan-mogilko** [comment]
Pushed 5f3f342 to master branch and be38eca to release-3.6.0.

The option in "disabled" is called "antialias" to match the existing option's name in config.

**Comment by Crystal-Shard** [comment]
Great, thank you!
