### ISSUE TITLE
Linux cfg file lists Windows driver

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2206]
**Describe the bug**
Compiling a game for Linux, by default the Linux/data/acsetup.cfg file will contain the following line which is not valid for Linux,
`driver=D3D9`.
This produces a warning in the logs shown to stdout when the game starts up. I'm not sure _which_ driver is loaded instead, but the game does work (so this is not particularly urgent).

**AGS Version**
3.6.0.52

**To Reproduce**
1. Compile a game for Linux, with graphics driver set to D3D9
2. Open acsetup.cfg in a text editor
3. See error

**Expected behavior**
When compiling a game for any system, its acsetup should contain values valid for that system, or be blank (I'm assuming that writing "driver=" will use the system's default graphics driver, just like with audio).

**Desktop (please complete the following information):**
Ubuntu 22; I haven't checked if this also applies to Android or Mac builds.

**Comment by ivan-mogilko** [comment]
We do not have separate settings for Linux config.

**Comment by ivan-mogilko** [comment]
Another patch to release for 3.6.0.

**Comment by Crystal-Shard** [comment]
Actually, which driver *does* it load in Linux if it tries and fails to use D3D9? As far as I can tell, this is not specified on stdout.

**Comment by ivan-mogilko** [comment]
> Actually, which driver does it load in Linux if it tries and fails to use D3D9?

It should try supported drivers in an order, starting with OpenGL, iirc.

> As far as I can tell, this is not specified on stdout.

I think engine must print this to the log, but maybe it uses too low log level which is not shown in stdout by default.
Another way to find out is to press Ctrl+Alt+V in game.

**Comment by Crystal-Shard** [comment]
I've tested, and it's OpenGL.

**Comment by ivan-mogilko** [comment]
To summarize, the solution, i think, is to add another small step in each BuildTarget: right where it calls `GenerateConfigFile`, add another method which:
- loads final generated config to Dictionary;
- checks certain options, fixes them if necessary;
- writes Dictionary back into this final config file.

The helpers for reading/writing config using Dictionary are already there in 3.6.1.
Imho this is the simplest path for 3.6.1. For future major versions it's best to have separate setup panes per a build target, that's something that we discussed in past, but that also would require a bigger change in the building system.

**Comment by Crystal-Shard** [comment]
> For future major versions it's best to have separate setup panes per a build target, that's something that we discussed in past, but that also would require a bigger change in the building system.

I'm not convinced it's necessary to have separate panes; most likely the only thing that would be different between build targets is the graphics and audio drivers.

**Comment by ivan-mogilko** [comment]
> I'm not convinced it's necessary to have separate panes; most likely the only thing that would be different between build targets is the graphics and audio drivers.

It is necessary, there are more options that may require different values than drivers, there may be a need to have target exclusive options. It's a generally a common thing to be able to override config options per port.
