### ISSUE TITLE
EngineConfigFile.html

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2207]
**Describe the bug**
For the sake of completeness, I'd like to mention this documentation oversight that I noticed when checking setup file parameters for 3.6.0.52. In https://adventuregamestudio.github.io/ags-manual/EngineConfigFile.html, the following lines from acsetup.cfg are not explained,
```
[graphics]
fullscreen=full_window
window=desktop
[misc]
game_width=640
game_height=400
gamecolordepth=32
titletext=default setup
```

In addition, the following lines are generated in the default acsetup.cfg but do not appear in the Default Setup panel in the AGS editor:
```
[sound]
enabled=1
[graphics]
window=desktop
```

**Comment by ivan-mogilko** [comment]
> the following lines from acsetup.cfg are not explained,

Looks like the manual was not still properly updated after changes in 3.6.0.
This should be posted to the manual's issues:
https://github.com/adventuregamestudio/ags-manual/issues

> In addition, the following lines are generated in the default acsetup.cfg but do not appear in the Default Setup panel in the AGS editor:

"[sound] enabled" is not in winsetup either. This may be a general problem. But I don't know if we need this if we have a "driver" selection which may be "none". Perhaps this option could be removed completely.

"[graphics] window" is corresponding to "Windowed scaling style". That options generates 2 values: "[graphics] window" and ""game_scale_win".

**Comment by ivan-mogilko** [comment]
These values seem redundant, they are no longer used by winsetup, as it reads these parameters from the game data now:
```
[misc]
game_width=640
game_height=400
gamecolordepth=32
```

So these has to be removed from config file generation.

**Comment by ericoporto** [comment]
in OPTIONS.md there is a `background` under misc, but I think this got slashed in the sdl transition.

**Comment by ivan-mogilko** [comment]
> in OPTIONS.md there is a `background` under misc, but I think this got slashed in the sdl transition.

"background" was added recently, it forces keep running the game while player switched out, same as "--background" command.

**Comment by ivan-mogilko** [comment]
This is bad, I forgot to add new 3.6.0 options there, I will have to re-release the recent patch.

**Comment by ericoporto** [comment]
Right, I think I confused that with `multitasking`

**Comment by ivan-mogilko** [comment]
Removed unnecessary config options: 86034c2326a71174d2387a3e25a6527f6c4d0aa0

**Comment by ivan-mogilko** [comment]
Alright, I see, the "[audio] enabled" is generated from "Audio driver" property in Default Setup. I forgot about this.

If "Audio driver" is "Default", the enabled is set as 1, if it's "Disabled" then it is set as 0.

**Comment by ericoporto** [comment]
I noticed in [GitHub status](https://www.githubstatus.com/history) had some incidents until recently, not sure if related but even though an ❌ is shown  in the commit, the CirrusCI build seems alright.

**Comment by ivan-mogilko** [comment]
> Manual did not mention couple of options, and turned out it mentioned few old ones which are no longer used.
> Editor kept generating few options into acsetup.cfg that were no longer used.

This should be fixed now.
