### ISSUE TITLE
Editor won't load if TRS missing

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2208]
**Describe the bug**
Opening a game in the editor with a .trs file missing causes the editor to refuse to open the entire game. This has an obvious workaround so it's not urgent.

**AGS Version**
3.6.0.53

**To Reproduce**
1. Create a game with a translation file
2. Quit the AGS editor
3. Delete the .TRS file from disk
4. Open the AGS editor
5. See error

**Expected behavior**
Opening the game with basically any other file missing works fine and throws an error when you build; this allows the user to fix it in the editor. A missing .TRS file should also throw a build error.

**Desktop (please complete the following information):**
Windows 11.

**Comment by ivan-mogilko** [comment]
This should be fixed in 3.6.1.

**Comment by Crystal-Shard** [comment]
Well it has an easy workaround by manually creating the TRS file, so if this is in 3.6.1 I think this can be closed.
