### ISSUE TITLE
General Settings when importing from old engine

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2209]
**Describe the bug**
When I import a game from an older AGS version, the General Settings and Default Setup show incorrect values. Saving, quitting, and reopening AGS Editor fixes this. Not an urgent deal since it has an easy workaround.

**AGS Version**
3.6.0.52

**To Reproduce**
1. Create a game in an older AGS version with some changes to general settings, e.g. set a game name
2. Import this game into AGS 3.6
3. Check the General Settings, note the changes from pt.1 are not there
4. Quit and reopen AGS
5. Check the General Settings, note the changes from pt.1 are now visible

**Expected behavior**
The General Settings and Default Setup work correctly in the first time.

**Desktop (please complete the following information):**
Windows 11.

**Comment by ericoporto** [comment]
How old? Can you check if this is #1005 ?

**Comment by Crystal-Shard** [comment]
> How old? Can you check if this is #1005 ?

Yes, that appears to be the same issue.

**Comment by ivan-mogilko** [comment]
I'll close as duplicate as #1005 then.
