### ISSUE TITLE
Default values in General Settings / Default Setup

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2210]
**Describe the bug**
In a large properties panel (in particular, General Settings and Default Setup in the AGS editor) I find it practical to see which values are in their default setting and which have been changed. The latter stand out because Windows prints them in boldface, and this makes it easy to change them back to their default.
However, I find that a number of settings either don't have a default (meaning they're always boldface) ~~or don't start at their default value when creating a new game.~~ For instance, "Sprite File Compression" doesn't have a default value, ~~and "Characters Turn To Face Direction" is initialized to false where the default is true.~~
This has a clear workaround so it's not urgent, but it some cases I would really like to know what the default (recommended) values _are_.

**AGS Version**
3.6.0.52

**To Reproduce**
1. Create a new game using the Empty Game template
2. Click on 'General Settings' or 'Default Setup'.
3. Note how a number of values are boldfaced. All of these either don't have a default, ~~or are not initialized to their default.~~

**Expected behavior**
All settings should have a default (which should probably be the most recent / most recommended setting), ~~and when starting a new game all settings should be initialized to their default value.~~

**Desktop (please complete the following information):**
Windows 11

**Comment by ivan-mogilko** [comment]
The starting values come from **templates**. This responsibility also lies on a template author or maintainer.

**Comment by Crystal-Shard** [comment]
That's a good point, I didn't know the templates had a separate repo and ownership. I'll make a ticket for Empty Game; the other templates presumably have good reason for using different values.

**Comment by ivan-mogilko** [comment]
Here's the list of the properties that don't have default values (judging by 3.6.1 state):

General Settings:
- "Color depth"
- "Resolution"
- "Text format"
- "Sprite file compression"
- "Inventory item cursor hotspot marker"
- "Inventory item cursor hotspot marker sprite" (? or maybe it's treated as 0)
- "Inventory item cursor hotspot marker dot colour"
- "Inventory item cursor hotspot marker crosshair colour"
- "Maximum possible score"
- "Build target platforms"

There may be also some properties which default values are questionable, like "Debug Mode" is true by default. While that's a reasonable starting value, idk if it's logically default in game.

**Comment by Crystal-Shard** [comment]
It makes sense to me for Debug to default to false; this makes it stand out if it's still true when you're trying to release.

**Comment by ivan-mogilko** [comment]
Fixed by f8e3d3a953456ec0319850626d52bc52f4556499 and 8d9fc8c904791c2576f08e4323b44804cecd6918
