### ISSUE TITLE
AGS4: Editor doesn't rebuild backgrounds in CRM after external changes in the room's background png

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#2216]
**Describe the bug**
Updating a room background via filesystem won't trigger an update to the crm file.

**AGS Version**
AGS4

**To Reproduce**
1. Open a room
2. Update the room png image with an external editor
3. Editor recognizes an external change and asks if to load it
4. Click reload
5. Background is displayed fine in the preview
6. Run the game
7. Ingame room uses the old image
8. Rebuild all
9. Ingame room still uses old image

**Expected behavior**
If the Editor has recognized an external changed and it has loaded the change, then it should also rebuild the crm properly.

**Additional context**
We're probably just missing to set a dirty flag somewhere.
Editing any mask will finally get the background to be properly saved.

**Comment by ivan-mogilko** [comment]
I added a "was modified" flag per room component some time ago to prevent unnecessary saving, but I cannot remember if that also affected crm compilation.
