### ISSUE TITLE
Build from command line

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2222]
**Describe the problem**
For the purpose of scripting and automation, I would like to be able to to build a game from the command line.

**Suggested change**
From the windows command prompt or a batch file, if I run
`AGSEditor.exe --build C:\Games\test\test.agf`
I suggest that this opens the AGF file, invokes the "rebuild all files" command from the Build menu, and quits. If any error occurs, print the error to stdout and quit. It would be practical if, in case of error, Compiled\Windows\test.exe is deleted.

**Comment by ericoporto** [comment]
You can, it's `AGSEditor /compile c:\Games\test\Game.agf`

**Comment by ivan-mogilko** [comment]
This is still not documented in the manual though, this information should be added there.

**Comment by ericoporto** [comment]
> If any error occurs, print the error to stdout and quit.

The only issue is https://github.com/adventuregamestudio/ags/issues/666

AGD already had this in 2017 when I started using it, my guess is it was probably added by CJ before our time - which would mean there may be things before our time that are still undocumented too.

**Comment by ivan-mogilko** [comment]
Besides #666, if there are any immediate problems with `/compile`, please report here, if not then we should close this as "not planned".

**Comment by Crystal-Shard** [comment]
Technically it can be closed as complete because the functionality already exists :) I just didn't know about it.
Anyway, if there are more undocumented command line switches then I'd like to hear about them somehow.
