### ISSUE TITLE
All The Way Down fails on Linux with version error which seems wrong

### ISSUE THREAD

**Issue by stuartlangridge** [adventuregamestudio/ags#223]
Running a just-compiled HEAD on Ubuntu 14.04:

    $ ./Engine/ags --help
    AGS: Adventure Game Studio v3.3 Interpreter
    Copyright (c) 1999-2011 Chris Jones and 2011-2014 others
    ACI version 3.3.3.0
    (snip)

and trying to run [All The Way Down](http://www.adventuregamestudio.co.uk/site/games/game/1872/), AGS complains that the game requires a newer version of AGS, and then quotes a lower version number (I am running 3.3.3.0, the game requires 3.3.0.1167?)

    $ ./Engine/ags ../allthewaydown/
    AGS: Adventure Game Studio v3.3 Interpreter
    Copyright (c) 1999-2011 Chris Jones and 2011-2014 others
    ACI version 3.3.3.0
    
    AGS: *** ENGINE STARTUP ***
    AGS: Reading config file
    AGS: Initializing allegro
    AGS: Setting up window
    AGS: Initializing game data
    AGS: Game data file: /home/aquarius/Programs/Others/ags/allthewaydown/deepuns3.exe
    
    AGS: Initializing TTF renderer
    AGS: Initializing mouse
    AGS: Checking memory
    AGS: Initializing speech vox
    Speech sample file found and initialized.
    AGS: Initializing audio vox
    Audio vox found and initialized.
    AGS: Initializing keyboard
    AGS: Install timer
    Checking sound inits.
    AGS: Initialize sound drivers
    ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
    AGS: Install exit handler
    AGS: Initialize path finder library
    AGS: Load game data
    AGS: Game data version: 44
    AGS: Requested engine version: 3.3.0.1167
    This game requires a newer version of AGS (3.3.0.1167). It cannot be run.Invalid file format. The file may be corrupt, or from a different
    version of AGS.
    This engine can only run games made with AGS 2.5 or later.

**Comment by ivan-mogilko** [comment]
As far as I know, "All the Way" down was compiled with an experimental side-branch version of AGS which is no longer supported.

I'd ask game author to recompile it using nearest compatible version 3.4.0.

**Comment by stuartlangridge** [comment]
Oh! OK, then it's not your fault, no worries :-)
