### ISSUE TITLE
Editor: Pasting into the Dialog's option text will paste into the dialog script instead

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2231]
**Problem**

If you have a Dialog open, and paste a text from clipboard into the option's text, it will instead paste into the dialog script, as if it had a focus or a command precedence.

**AGS Version**
3.6.1, does not reproduce in earlier version.

I have suspicion that this might be related to picking out ScriptEditor's base class.

**To reproduce**
1. Open a dialog for editing, create few options.
2. First click onto the script to set a cursor there.
3. Copy any text to clipboard.
4. Set cursor into one of the option fields and paste (ctrl + v).
5. Notice how the text pastes into the script instead, at the position where the latest cursor position was.

**Expected behavior**
Nothing is pasted into script unless it has a focus.

**Comment by ericoporto** [comment]
Now that you mentioned, indeed in the previous dialog editor there wasn't a `PASTE_COMMAND`, by looking into the diff in the PR #1743

**Comment by ivan-mogilko** [comment]
> Now that you mentioned, indeed in the previous dialog editor there wasn't a PASTE_COMMAND, by looking into the diff in the PR https://github.com/adventuregamestudio/ags/pull/1743

I'm not sure what is the deal with the old code, but I tested a number of older versions (starting with 3.2.1) and they have Copy/Cut/Paste in context menu, and Ctrl+C/Ctrl+V combinations work.

**Comment by ericoporto** [comment]
OK, the issue is the edit menu that we add has commands with shortcut keys that match the default ones (e.g. Ctrl+C for copy) and so on. The menus are changed through a weird way by the `MainMenuManager.cs` under `ShowPane` method. They are define in the ScriptControlBase and then they are passed to the matching component.

So, when you do the shortcut it will call `OnClickCommand` passing the specific string, not sure how that works, and unfortunately when it does so, it doesn't pass what object the command was done, as there isn't one, as this is just calling the method on top of the edit.

Given this, I had the following not bright idea to add on top of `OnClickComman` call...
```C#
            if(!_scintilla.Focused)
            {
                Control c = Utilities.GetControlThatHasFocus();
                if (command == CUT_COMMAND) (c as TextBox)?.Cut();
                else if (command == COPY_COMMAND) (c as TextBox)?.Copy();
                else if (command == PASTE_COMMAND) (c as TextBox)?.Paste();
                else if (command == UNDO_COMMAND) (c as TextBox)?.Undo();

                return;
            }
```

It sounded dumb, but it also didn't work - somehow you can see that text is still pasted to the ScriptEditor, even if you click on a textbox, so not sure why the focus is not being grabbed.

**Comment by ericoporto** [comment]
Given this, I had the following not bright idea to add on top of `OnClickCommand` call

https://github.com/adventuregamestudio/ags/blob/abd7bfa537dd2535bb101a7644707d6662cf9264/Editor/AGS.Editor/Panes/ScriptEditorBase.cs#L190-L191

```C#
            Control c = Utilities.GetControlThatHasFocus();
            TextBox tbox = c as TextBox;
            if (tbox != null)
            {
                if (command == CUT_COMMAND) tbox.Cut();
                else if (command == COPY_COMMAND) tbox.Copy();
                else if (command == PASTE_COMMAND) tbox.Paste();
                else if (command == UNDO_COMMAND) tbox.Undo();

                return;
            }
```

This actually works without any visible issue - for some reason testing for `_scintilla.Focused` doesn't work, this is why I test for a textbox.

My second attempt was deleting all copy, paste, cut, redo and undo from the ScriptEditorBase. This works, but the menu entries are missing in the Edit menu - it doesn't look nice.

**Comment by ivan-mogilko** [comment]
Right, so the problem is clear now. I think in such case the solution normally should be in changing particular menu commands state (enabled/disabled) depending on a context. ScriptEditorBase has a function called `UpdateToolbarButtonsIfNecessary`, (mention of "toolbar" is misleading), but it's being called from a strange place and seemingly not when it should.

**Comment by ericoporto** [comment]
I found a weird approach

> set their shortcutkeys to none, then set their shortcutkeydisplaystring's to Ctrl+C, Ctrl+X, Ctrl+V

https://www.vbforums.com/showthread.php?598714-RESOLVED-Keyboard-short-cuts-for-Cut-Copy-Paste-Not-working

Essentially create the menu entries but do not actually capture the shortcut keys but pretend as such.

**Comment by ivan-mogilko** [comment]
> Essentially create the menu entries but do not actually capture the shortcut keys but pretend as such.

That does seem as valid workaround, although the menu commands will still be seen as enabled regardless of where the cursor is.

The cursor may be even in Properties Grid, and selecting Paste from main menu will paste into the script. This may be fine for time being...

**Comment by ericoporto** [comment]
Here is a weird thing that I have currently, for me the visual studio solution in Release mode doesn't rebuild the c# projects, I had to manually mark those to build - I don't know if this is something specific to my PC or if we committed something wrong in the solution, so check if it's actually getting built.

**Comment by ivan-mogilko** [comment]
>  I think the solution platform "Mixed Platforms" is correct but the "Win32" is configured incorrectly.

I've been using "Mixed Platforms" config for as long as I recall.

**Comment by AlanDrake** [comment]
I too always used Mixed Platforms, but now that you mention it I did notice once yars ago I couldn't compile on Win32 but I just assumed it was a joke config never menat to work.

**Comment by ivan-mogilko** [comment]
@ericoporto I went with your latest suggestion about replacing shortcuts with "displayed shortcuts". It's simple enough and seems working: d50affeff323a422094f938b0055798d6f797eca

Please test too.

**Comment by ericoporto** [comment]
It worked fine as far as I could test! By directly clicking the actions in the Edit menu, they instead affect scintilla, which is fine and expected, I think if I would add something, I would just make sure that things get focus when such commands are issued, like below:

```diff
diff --git a/Editor/AGS.Editor/Panes/ScriptEditorBase.cs b/Editor/AGS.Editor/Panes/ScriptEditorBase.cs
index f01f36183..2c2fc5f43 100644
--- a/Editor/AGS.Editor/Panes/ScriptEditorBase.cs
+++ b/Editor/AGS.Editor/Panes/ScriptEditorBase.cs
@@ -198,20 +198,24 @@ namespace AGS.Editor
         {
             if (command == CUT_COMMAND)
             {
+                _scintilla.Focus();
                 _scintilla.Cut();
             }
             else if (command == COPY_COMMAND)
             {
+                _scintilla.Focus();
                 _scintilla.Copy();
             }
             else if (command == PASTE_COMMAND)
             {
+                _scintilla.Focus();
                 _scintilla.Paste();
             }
             else if (command == UNDO_COMMAND)
             {
                 if (_scintilla.CanUndo())
                 {
+                    _scintilla.Focus();
                     _scintilla.Undo();
                 }
             }
@@ -219,6 +223,7 @@ namespace AGS.Editor
             {
                 if (_scintilla.CanRedo())
                 {
+                    _scintilla.Focus();
                     _scintilla.Redo();
                 }
             }
```

**Comment by ericoporto** [comment]
> I too always used Mixed Platforms, but now that you mention it I did notice once yars ago I couldn't compile on Win32

@AlanDrake , I have been playing with it because of my test of building the Editor for x64, and my idea was going there, to remove the Mixed Platforms - as it isn't mixed at all, the native parts are built for x86.

**Comment by ivan-mogilko** [comment]
> By directly clicking the actions in the Edit menu, they instead affect scintilla, which is fine and expected

In my opinion these actions should change their state and/or reaction depending on focused control instead. But this is an original problem, so may be addressed separately.

**Comment by AlanDrake** [comment]
@ericoporto According to internet lore, Mixed platforms is created when adding projects into the solution that have different build platforms, or upgrading from older solutions.
