### ISSUE TITLE
AGS 4: implement Character's direction ratio property

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2243]
### Problem

AGS has a hardcoded factor for switching directional character view loops depending on the direction they are facing. There were numerous requests to let user configure these in the past, when they like to emulate different perspectives, such as isometric movement and whatnot. Yet it's not possible to do in AGS without scripting switching loops yourself.

---

### Potential solution

The basic suggestion is explained on ags forums here by @messengerbag, with illustrations:
https://www.adventuregamestudio.co.uk/forums/editor-development/feature-request-ability-to-create-16-character-facing-directions/msg636657477/#msg636657477

![](https://i.imgur.com/XsGxJ7j.png)

Quote:
> As you can see, as the circle and cross get more and more flattened by **foreshortening**, the front and back view angles get wider, while the side view angles get narrower.
> We can represent this perspective distortion as **a single number**: the height/width ratio of the circle or ellipse.

Coincidentally, there have been already a feature made by @AlanDrake in his experimental "draconian" version, I think it's been around for many years, but never made it to main ags version. It's called "DirectionRatio", and is represented by a script function `Game.SetDirectionRatio(float ratio)`.

Example commit: https://github.com/AlanDrake/ags-draconian/commit/bdf8cffe4922b98df06933985f0b43dd4401e07e

From the comment's description:
> Allows to change the way the direction view is calculated. Can be useful for better matching the room perspective.
What it does is change the importance of the X axis in the original calculations.
Default is 1.0, from 2.0 to 3.0 could be good values for a room in perspective.

---

### Suggestion

1. Decide on the API terminology; would that be a "foreshortening" or "direction ratio", or else. It should be clear enough for users to understand its purpose: it is for choosing the facing/moving angles at which to switch from one directional view loop to another.
2. Implement a number of properties that let user configure this factor for various scenarios. For the most basic effect a global `Game.DirectionRatio` would be enough (I am using example name here). But I'd suggest to consider having several overriding properties: `Game.DirectionRatio` -> `Room.DirectionRatio` -> `WalkableArea.DirectionRatio` -> `Character.DirectionRatio`, where each property has a default value meaning "use parent", and character's individual property (when set) overrides all the above. EDIT: I suppose that value 0.0 may be "use parent" / "undefined", unless there may be scenarios where it's valid? If so, then we may add a constant with a -1.0 value to be used here.
3. It's more essential to have this in script API, to let change dynamically on need, but of course would be nice to have in Editor properties too.

**Comment by AlanDrake** [comment]
Beware, sometimes my hacks only look like they work. I never went and actually made a test to make sure what I did was formally correct...

As for naming, maybe Perspective, DirectionPerspective, DirectionScale... hmm I can't think of a clear winner.

**Comment by ericoporto** [comment]
While we can certainly test more it appears this indeed work, [according to the user](https://www.adventuregamestudio.co.uk/forums/beginners-technical-questions/switching-angles-of-diagonal-character-loops/msg636659286/#msg636659286)

![image](https://github.com/adventuregamestudio/ags/assets/2244442/99e17f31-d291-45e1-ba9e-5804dd9c2d16)

_(plus I thought it looked cute and wanted an excuse to have it here...)_

**Comment by ivan-mogilko** [comment]
Resolved by #2304
