### ISSUE TITLE
Script Editor: Deleting collapsed text breaks the editor

### ISSUE THREAD

**Issue by edmundito** [adventuregamestudio/ags#2254]
**Describe the bug**
Something is wrong when deleting

**AGS Version**
3.6.0.54

**To Reproduce**
1. Open the script editor
2. Add this comment:
```
/*
Comment block to be deleted.
*/
```
4. Collapse the comment
5. Select and delete the collapsed comment

**Expected behavior**
Collapsed text should be removed correctly.

**Actual behavior**
If you look at the code, you'll see that the line numbers still skip as if there was something still collapsed. When building the game, there may be some pieces of the old code that are still there.

The workaround is to close the script editor and re-open it to remove partially un-deleted code.

**Comment by ivan-mogilko** [comment]
> Select and delete the collapsed comment

I have to clarify: you must select and delete only the line with the "expand" marker. Selecting and deleting larger region with lines before and after the collapsed block does not cause any issues, it seems.
Another way is to place cursor on the collapsed line and delete the text by holding down backspace or delete key.

**Comment by ericoporto** [comment]
Hey, I found an issue that reads similar to this one here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11246

I tried to apply the mentioned fix in the linked commit to that issue in AGS

```diff
diff --git a/Editor/AGS.Editor/Panes/ScintillaWrapper.cs b/Editor/AGS.Editor/Panes/ScintillaWrapper.cs
index 1dae762ac..374cb075a 100644
--- a/Editor/AGS.Editor/Panes/ScintillaWrapper.cs
+++ b/Editor/AGS.Editor/Panes/ScintillaWrapper.cs
@@ -420,6 +420,8 @@ namespace AGS.Editor

             scintillaControl1.SetFoldFlags(FoldFlags.LineAfterContracted); // Draw line below if collapsed
             scintillaControl1.Margins[2].Sensitive = true;
+
+            scintillaControl1.AutomaticFold = ScintillaNET.AutomaticFold.Show | ScintillaNET.AutomaticFold.Change;
         }

         void scintillaControl1_MarginClick(object sender, MarginClickEventArgs e)
```

The result is as follows:

https://github.com/adventuregamestudio/ags/assets/2244442/3f7dcb6c-8c9d-458e-882b-2e7971a1cea4

As a comparison, without the change, the original error is:

https://github.com/adventuregamestudio/ags/assets/2244442/fd2e3a18-63c4-4cac-9c7f-058aa2acb8c2

**Comment by ericoporto** [comment]
I think the issue is that the fold change event necessary to trigger modifications can only be emitted if `foldAutomatic` has the `SC_AUTOMATICFOLD_CHANGE` bit here

https://github.com/adventuregamestudio/ags/blob/107e40ae1a740470b38290f3a989027d87276982/Editor/scintilla/src/Editor.cxx#L2708-L2710

So I think the proposed PR #2257 makes sense.
