### ISSUE TITLE
Editor: Exception in Script Editor "Value x not valid for index" at `ComboBox.ObjectCollection.get_Item(Int32 index)` 

### ISSUE THREAD

**Issue by edmundito** [adventuregamestudio/ags#2268]
**Describe the bug**
I've been seeing this exception in the script editor quite a bit. My Windows is in Spanish so `El valor de '19' no es válido para 'index'.` Means `Value 19 is not valid for index`.

```
Error: InvalidArgument=El valor de '19' no es válido para 'index'.
Nombre del parámetro: index
Version: AGS 3.6.0.54

System.ArgumentOutOfRangeException: InvalidArgument=El valor de '19' no es válido para 'index'.
Nombre del parámetro: index
   en System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   en AGS.Editor.ComboBoxCustom.<OnCreateControl>b__4_2(Object s, DrawItemEventArgs a)
   en System.Windows.Forms.DrawItemEventHandler.Invoke(Object sender, DrawItemEventArgs e)
   en System.Windows.Forms.ComboBox.OnDrawItem(DrawItemEventArgs e)
   en System.Windows.Forms.ComboBox.WmReflectDrawItem(Message& m)
   en System.Windows.Forms.ComboBox.WndProc(Message& m)
   en AGS.Editor.ComboBoxCustom.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**AGS Version**
3.6.0

**To Reproduce**
Unknown. Some things I'm doing:
* Typing partial OOP code and switching between ash and asc file to copy and paste the heading
* Using `#region` areas

After the error appears. When I save, the editor switches tabs from the asc file to the ash file automatically. The workaround is to close and re-open the editor.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by ivan-mogilko** [comment]
I suspect this refers to the "location" combo box on the top of the script editor.
There are vague memories of this combobox being fixed, but that could be a different problem too.

**Comment by ericoporto** [comment]
Perhaps this is similar to #1919 ? 

I had a vague memory of things being fixed but I think I am mistaking for the theme related things that were fixed for that combobox in ags4 by @AlanDrake . I browsed by commits with `Editor:` tag on master and couldn't find anything there.

**Comment by ivan-mogilko** [comment]
Right, the callstack matches precisely, so this looks like a duplicate.
Also there's a ticket about tab switching on save: #1920

I will close this one.
