### ISSUE TITLE
Incorrect doc in `GUI.ProcessClick`:  `MouseButton` instead of `CursorMode`

### ISSUE THREAD

**Issue by edmundito** [adventuregamestudio/ags#2270]
**Describe the bug**
I noticed that the doc for the GUI in the script editor says the third parameter is `MouseButton`:
https://github.com/adventuregamestudio/ags/blob/0b6d178bdb61ae50719ee73409876eb74cb423ab/Editor/AGS.Editor/Resources/agsdefns.sh#L1964C3-L1964C3

However, the docs mention that it is `CursorMode` instead.

**AGS Version**
3.6.0 (December 2023)

**To Reproduce**
1. Open a script and type `GUI.ProcessClick`
2. Look at the tooltip doc
3. Righ click on `GUI.ProcessClick` and read the docs

**Expected behavior**
The tooltip should read `CursorMode`.

**Comment by edmundito** [comment]
Hang on, maybe it's the other way around? Maybe the doc should be `MouseButton` instead of `CursorMode`?

**Comment by ivan-mogilko** [comment]
GUI.ProcessClick accepts MouseButton, because GUIs work with buttons, not cursor modes.

**Comment by ivan-mogilko** [comment]
This is a mistake in the manual, possibly because of a copy-pasted text from Room.ProcessClick.
https://github.com/adventuregamestudio/ags-manual/wiki/GUI#guiprocessclick
should be fixed there.

**Comment by edmundito** [comment]
Yes that is what I realized after a few tries. The documentation is incorrect because it refers to CursorMode:

https://adventuregamestudio.github.io/ags-manual/GUI.html?highlight=processclick&case_sensitive=0

**Comment by ivan-mogilko** [comment]
Okay, I rewrote the article, it was quite strange:
https://github.com/adventuregamestudio/ags-manual/wiki/GUI/_compare/ebd89dbc8a9c6f99fa9e403480d98ae96c68db2c...ebf29ac3bd73071bc38e21ff8b1068ad375fc574
