### ISSUE TITLE
macOS engine: Show error message as as a dialog window

### ISSUE THREAD

**Issue by edmundito** [adventuregamestudio/ags#2279]
**Describe the problem**
Currently, error messages displayed by the macOS (OSX) engine are only shown in the log, which means that when the game crashes for a Mac user, there is no visible error message. The only way a mac user can see the error is by running the app directly from the Terminal, so that the engine logs display on the terminal console.

Here's a reference to the OSX `DisplayAlert` implementation, as you can see there it only prints the console
https://github.com/adventuregamestudio/ags/blob/9cc72e49301120fc2e1a8bd672cc1328f7e5a600/Engine/platform/osx/acplmac.cpp#L71-L81

**Suggested change**
Leverage [`SDL_ShowSimpleMessageBox`](https://wiki.libsdl.org/SDL2/SDL_ShowSimpleMessageBox) to show the error message using the native dialog window. This was done recently for iOS and works great:

https://github.com/adventuregamestudio/ags/blob/9cc72e49301120fc2e1a8bd672cc1328f7e5a600/Engine/platform/ios/acplios.cpp#L325-L334

**Comment by edmundito** [comment]
I can make some time to implement this, but not right away, so I decided to track it as an issue first. Feel free to assign this to me.

**Comment by ivan-mogilko** [comment]
Yes, elsewhere I suggested to implement whole set of options in the base platform class, and only provide additional implementations for narrow actions, like message box. This way all platforms will act mostly same way.

There's a minor issue with Debug::Printf call, which may lead to duplicate logging into stdout, if you also have an explicit action of printing into stdout in a DisplayAlert (like it's done in Windows or AGSPlatformXDGUnix). I was not sure how to deal with this, unless you implement a way to disable certain log output just for this call, or pass this as a "ignore outputs" parameter into Debug::Printf.

**Comment by ericoporto** [comment]
> There's a minor issue with Debug::Printf call, which may lead to duplicate logging into stdout

The windows platform solves this by directly calling the method that prints to stdout afaict.

https://github.com/adventuregamestudio/ags/blob/9cc72e49301120fc2e1a8bd672cc1328f7e5a600/Engine/platform/windows/acplwin.cpp#L310-L314

**Comment by ivan-mogilko** [comment]
> The windows platform solves this by directly calling the method that prints to stdout afaict.

The point is to log the alert message through the log system, so that file etc also gets it.
