### ISSUE TITLE
Several games fail on boot with Script link error in 3.6.0

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2286]
**Describe the bug**
It seems commit 973845a15ed9726956895161c8847bc668c3e787 is not properly implemented or a bit too restrictive.
At least The Cat Lady (GOG); Quest for Glory 2 (AGDI remake); Maniac Mansion Mania ep. 1 (latest release) and probably
others are affected by this issue.

**AGS Version**
3.6.0.55

**To Reproduce**
Just start the game

**Desktop (please complete the following information):**
Win10

**Comment by ivan-mogilko** [comment]
Yes, I did it wrong, this condition should not apply to all fixup types, but only to particular one(s).

**Comment by ivan-mogilko** [comment]
Pushed 9d86d5ab1a6e84115c33ffbfc8a96185e6b9fd63
