### ISSUE TITLE
Numpad keys are not treated correctly by the engine

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2294]
**Problem**
Numpad keys are not treated correctly by the engine:
1. The on_key_press receives keycodes corresponding to non-numeric keys, disregarding NumLock state. This means that even if NumLock is on, the on_key_press would receive PgUp, PgDown etc codes.
2. If there's an active TextBox control, and NumLock is on, then pressing numpad keys would both print numbers into Textbox and call on_key_press with non-numeric key codes.

**AGS Version**
3.6.0, 3.6.1

**Expected behavior**
1. on_key_press should receive a keycode depending on NumLock state.
2. Alternatively, there has to be distinct NumPad keycodes, so that user could at least know that these are "keypad" keys.
3. If TextBox uses a key, then on_key_press should not be called.

**Comment by ivan-mogilko** [comment]
This is happening because since SDL port engine separates keycodes and printable chars created by a key combination.

When NumLock is on, pressing a numpad key produces 2 events: key event and a text event. TextBox only accepts text event, and ignores key event.

**Comment by ivan-mogilko** [comment]
Ah, ... this is bit unexpected (maybe I forgot details about how engine treats alphanumeric keys), but following experimental fix actually fixes both problems at once:

```
    // NumPad
    if ((sym >= SDLK_KP_1 && sym <= SDLK_KP_0) && (mod & KMOD_NUM) != 0)
    {
        return static_cast<eAGSKeyCode>(sym - SDLK_KP_1 + SDLK_1);
    }
```

**Comment by ivan-mogilko** [comment]
Also fixed IsKeyPressed for few numpad keys, but only those that do not depend on NumLock state. This is because this function is not supposed to depend on modifiers (e.g. it ignores shift). This is also matching the pre-3.6.0 behavior.

Related commits: c6ed7f8c37b4a0ae694c3224de6ed4efcb968c78, 6c498ec18d6e1e63920c886d7949f2447b9b5191

OTOH, there is a distinct AGS KeyCode for NumPad5, but not others. Perhaps, it would be desired to add other NumPad* keycodes to let user combine them with System.NumLock mod to know the correct key state.

**Comment by ericoporto** [comment]
Probably not relevant, but just to note, there is an issue in web port due to a limitation in information from the browser for SDL (https://github.com/libsdl-org/SDL/issues/5447), it can't pick num lock state changes when the tab is not in focus.
