### ISSUE TITLE
when ENGINE is shut down, screen resolution should be restored

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#23]
ENGINE HAS SHUTDOWN -> seriously broken X11 resolution

since you cant even reach the taskbar anymore, you basically have to restart X and lose all your unsaved data.

**Comment by ivan-mogilko** [comment]
Can someone tell if this is still an issue with the recent release?

**Comment by ericoporto** [comment]
I don't get this issue on either Ubuntu 18.04 + Gnome 3 or Ubuntu 16.04 + Unity.

**Comment by rofl0r** [comment]
yeah, this seems to have been fixed. i still get the occasional segfault from the engine though, which has the same effect. thus i don't run ags in fullscreen anymore. that particular issue could potentially be fixed though by using a signal handler for SIGSEGV that calls the "restore_original_resolution" code.
