### ISSUE TITLE
I can't install ags-git from aur 

### ISSUE THREAD

**Issue by EsamLasheen** [adventuregamestudio/ags#2309]
**Describe the bug**
I can't install ags-git from aur 

**AGS Version**
 ags-git-3.4.1.6.r56.g234c69ef-1

**Game**
i use it on hyprland 

**To Reproduce**
1Steps to reproduce the behavior:

```paru -S ags-git``` 

**Expected behavior**
installed
**Screenshots**

![Screenshot_2024-01-21_15-26-46](https://github.com/adventuregamestudio/ags/assets/55217611/37d423ee-5e11-4487-b4cb-468a5c6e0534)

**Comment by ericoporto** [comment]
We don't package for aur, you should reach the maintainer instead. Still, this is a really old and unmaintained package. You should use the `ags` package.

https://aur.archlinux.org/packages/ags

**Comment by ivan-mogilko** [comment]
@EsamLasheen Hello, our team develops the engine itself here, but we do not maintain its packages. As @ericoporto said, you should address this to the maintainer(s) of this package or respective system distro.
