### ISSUE TITLE
Is it possible to add Korean fonts for AGS and ScummVM 

### ISSUE THREAD

**Issue by Leemann07** [adventuregamestudio/ags#2310]
Is it possible to add Korean fonts?

A Korean language patch has been created for If on a Winter's Night Four Travelers. 

The link of the Korean patch is https://downapi.cafe.naver.com/v1.0/cafes/article/file/805fafa2-d2c8-11ed-a9bc-0050568dec42/download.   

The link of the Korean patch is https://github.com/scummvm/scummvm/pull/559

This Korean patch was created as a Korean font for AGS, and I want to make it work on ScummVM as well. 

I would like to ask for advice on this.  :) 

**Describe the problem**
Please explain what is currently lacking in AGS or does not work how you'd wished it did.
Were you trying to accomplish something and found it's impossible or too hard to do?
Is there something that is simply inconvenient?

**Suggested change**
What do you propose to add or change?
If you have got a fully fledged idea about how things might work, please explain in all details so that we could clearly see your point.
If not, then simply leave any thoughts you have got on this issue.

**Comment by ericoporto** [comment]
ScummVm is a different project and the link sent is for a different feature - apparently something about Theora library. Features for ScummVm should be solved in ScummVm bug tracker.

AGS itself can display texts in Korean if you are making a game using 3.6.0 and later versions, they are utf-8 by default so it's just a matter of having a font with mentioned characters. Korean input in IME keyboard is not yet supported.

**Comment by ivan-mogilko** [comment]
@Leemann07 please clarify what are you trying to do.

If you want to add something to the game, then you should contact the game author, because the game is their own business. Here we develop the engine, but we do not patch games.

If you are trying to run the game with your own custom data, then please explain how you do that, and which version of the engine do you use, because that also matters.

I might note that "If on a Winter's Night" game was originally made with AGS 3.5.1. That version did not support Unicode mode yet. So either it has to be run with a 3.6.0+ engine, or the fonts must be ANSI-compatible (I do not know if it's possible for Korean font).

I could not check your patch, because the link does not work for me (it returns "access denied").

**Comment by Leemann07** [comment]
> 기부자
> ###

https://github.com/scummvm/scummvm/pull/5597 sorry this link is real

**Comment by Leemann07** [comment]
> @Leemann07무엇을 하려는지 명확히 해주세요.
> 
> 게임에 무언가를 추가하려면 게임 제작자에게 문의해야 합니다. 게임은 자체 사업이기 때문입니다. 여기서 우리는 엔진을 개발하지만 게임을 패치하지는 않습니다.
> 
> 자신만의 사용자 정의 데이터로 게임을 실행하려는 경우 어떻게 수행하는지, 그리고 어떤 버전의 엔진을 사용하는지 설명해주세요. 왜냐하면 그것도 중요하기 때문입니다.
> 
> "If on a Winter's Night" 게임은 원래 AGS 3.5.1로 제작되었다는 점을 기억해 두겠습니다. 해당 버전은 아직 유니코드 모드를 지원하지 않았습니다. 따라서 유니코드 글꼴을 사용하는 3.6.0+ 엔진으로 실행해야 할 가능성이 높으며 번역 파일은 [매뉴얼에](https://adventuregamestudio.github.io/ags-manual/Translations.html#additional-options) 설명된 대로 "utf-8 인코딩"을 정의해야 합니다 .
> 
> 링크가 작동하지 않기 때문에 패치를 확인할 수 없습니다("액세스 거부"가 반환됨).

https://github.com/scummvm/scummvm/pull/5597 sorry this link is real

**Comment by ericoporto** [comment]
If you read the manual page above it explains how to use translation in 3.6.0+ including setting the encoding and font. You should also contact the game author instead.

**Comment by ivan-mogilko** [comment]
@ericoporto have you tried checking out the link? It suggests to add certain code to the AGS.

**Comment by ivan-mogilko** [comment]
@Leemann07 I can see that your code adds support for reading WFN fonts with Unicode support. But I could have missed some details. Is there any explanation of what this code does exactly? Have you wrote it, or someone else?

The potential support for Unicode WFN fonts was added in the latest 3.6.1 engine version. I might suggest to try the 3.6.1 engine from the latest "master" branch in this repository, or from latest releases here:
https://github.com/adventuregamestudio/ags/releases

If you could give me your font and translation, I could also test if these work with 3.6.1.

**Comment by ericoporto** [comment]
There's nothing special about Korean that needs an isKorean, there's proper ways to switch to utf-8 that doesn't require hardcoding, there's no clear explanation on the wfn patching, there's some special case for one game that I doubt is needed. It's best to understand what is the actual problem. If necessary make the translation format better.

Other issue I see is text rendering through bitmap and packing the glyphs should be possible with something easier then wfn. Like a dictionary of character to a pair rectangle and sprite. That bitmap font plugin, there's probably some feature from it that could be internalized in the engine.

About ScummVm it would make more sense for me if they would take the patch or modify or whatever, figure things there for backwards compat and then someone of their team contributes back what they think is needed. In ScummVm it's fine to special case a game but here we try not to.

**Comment by ericoporto** [comment]
Well, it looks like you read the code. Yeah, ScummVm will only support our stable releases.

The big issue I see is text rendering through bitmap and packing the glyphs should be possible with something easier then wfn. Like a dictionary of character to a pair rectangle and sprite. That bitmap font plugin, there's probably some feature from it that could be internalized in the engine. Yeah, it's inventing a font format, but I think it would be much more flexible than wfn.

**Comment by ivan-mogilko** [comment]
I'd like to focus on the matter at hand, and not discuss better formats etc here, that's completely irrelevant.

I'm currently trying to understand what the user is doing, and help them understand the existing situation.

**Comment by ericoporto** [comment]
Afaict they don't know about the comments that I mentioned that are in the manual to switch the text mode - or this isn't the final trs that gets transformed to tra.

https://github.com/british-choi/ScummVM-Kor-Trs/blob/master/Blackwell%20Unbound%20(GOG.com)/korean.trs

**Comment by tag2015** [comment]
> 
> If you are using ScummVM, then it's possible that they are at AGS 3.6.0 still. In such case you must either use TTF fonts with ScummVM, or wait until they update to 3.6.1 AGS version. (@tag2015, could you clarify this please?)
> 
That is correct. We included some bugfixes from the 3.6.1 branch, but the ScummVM AGS engine is basically 3.6.0

> Tbh I am not sure if OP is the same as @british-choi.
They are not the same person. @Leemann07 asked recently on Discord for advice on how to run this patched/modded version of IOAWN4T

**Comment by tag2015** [comment]
By the way this is the [link ](https://m.cafe.naver.com/ca-fe/web/cafes/16259867/articles/29391?art=aW50ZXJuYWwtY2FmZS13ZWItc2VjdGlvbi1zZWFyY2gtbGlzdA.eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYWZlVHlwZSI6IkNBRkVfVVJMIiwiYXJ0aWNsZUlkIjoyOTM5MSwiY2FmZVVybCI6ImhhbnNpY2d1IiwiaXNzdWVkQXQiOjE3MDYwMjM4Njg4NjN9.w8WgWtQhOhkkJbUZO_Q27eZ4Boifm9p30lQn5YbRatE&q=If%20on%20a%20Winter%E2%80%99s%20Nigh&tc=section_search_result_articles), but it seems you need an account  on that social to download

**Comment by Leemann07** [comment]
Thank you very much for your kind reply. And I'm sorry for the late reply. I read and re-read your post to understand it. I will download the Korean patches for AGS 3.6 and share the link with you.

**Comment by Leemann07** [comment]
> @ericoporto , @tag2015 Alright, thank you for this extra information, I can see the situation better now.
> 
> @tag2015 , only for the reference, the unicode support for WFN renderer is this small commit: [49561d4](https://github.com/adventuregamestudio/ags/commit/49561d40b7335f8b02070dbf1272e063ee2ac099) I just have to note that I tested it with a single font made with an [adjusted WFN editor](https://github.com/ivan-mogilko/fontedit); I don't think there are real games that use this feature. The WFN file format itself **remained unchanged**, because it's theoretically enough to contain at least few languages in unicode. I did not investigate the posted code for Korean support thoroughly enough (yet), but I'm curious if they keep existing WFN format or expanded it with a custom data.

http://naver.me/GNvNuPCx this is Korean patch for blackwell_unbound, blackwell_legacy to AGS 3.6 and If on a Winter's Night Four Travelers.

**Comment by ivan-mogilko** [comment]
> http://naver.me/GNvNuPCx this is Korean patch for blackwell_unbound, blackwell_legacy to AGS 3.6 and If on a Winter's Night Four Travelers.

This is a custom engine, based on AGS 3.5.0.31, which did not support unicode properly.

You should be using AGS 3.6.0 or 3.6.1 with a proper unicode support instead.

**Comment by ivan-mogilko** [comment]
Regarding to the use of *.font files, if this is the standard SCI font, then it may be converted to WFN. AGS Editor does this on font import, but I do not know if there's a standalone converter somewhere. It may be written though. To be fair, loading SCI fonts may be supported in the AGS engine too, as it's a sort of a simplified version of WFN.

**Comment by ivan-mogilko** [comment]
Darn, I've been testing this, and found that our translation compiler (trac) got broken somewhere in the midst of 3.6.0 development. It's been writing incorrect data. I guess nobody really tried it since (or tried but never reported a problem).

**Comment by ivan-mogilko** [comment]
@Leemann07 
So, here's the *example* of a working Korean language that I prepared, using your translation file, and following instructions that I posed above:
https://www.dropbox.com/scl/fi/idmwpt2cw7c7qpg8o38u9/IOAWN4T-3.6.0-KoreanTest.zip?rlkey=91pbnta71fmeddstlhatl123u&dl=1

This is based on a 3.6.0 engine. The package contains 3.6.0 acwin.exe, fixed TRS file, compiled TRA file and few TTF fonts.
I used GNU Unifont for the game fonts: https://www.unifoundry.com/unifont/ , but you may replace it with anything you like.

**Comment by Leemann07** [comment]
> > http://naver.me/GNvNuPCx this is Korean patch for blackwell_unbound, blackwell_legacy to AGS 3.6 and If on a Winter's Night Four Travelers.
> 
> This seems to be either a 3.5.0.31 engine, or a custom engine based on AGS 3.5.0.31, which did not support unicode properly. For unicode it uses a plugin called AGSBMFontRenderer (https://github.com/bggd/AGSBMFontRenderer). This plugin seems to require a ~slightly different font format (*.font, which may be a classic SCI font format), but I am not completely sure.~ EDIT: alright, my mistake, it requires completely different bitmap font format, incompatible with WFN.
> 
> @Leemann07, you should be using AGS 3.6.0 or 3.6.1 engine with a proper unicode support. They may be able to display Korean language without any extra plugins.
> 
> For this to work, the translation file (korean.trs) should have a proper header with encoding, as explained in the manual: https://adventuregamestudio.github.io/ags-manual/Translations.html#additional-options
> 
> TRS file should also be saved as UTF-8 (without BOM).
> 
> Translation should be compiled by a translation compiler that can understand the encoding setting. We have a newer translation compiler program in our repository, its code may be found here: https://github.com/adventuregamestudio/ags/tree/master/Tools/trac But the ready program for Windows may also be downloaded here: https://www.dropbox.com/s/6wfl3foo3jb9iyu/agstools-360.zip?dl=1 compiler is called "trac.exe".
> 
> This will result in "korean.tra" file, usable with the AGS games.
> 
> If you're using AGS 3.6.0, then you may only use TTF fonts for Korean language. If you are using 3.6.1, then you might as well use WFN fonts.






> > http://naver.me/GNvNuPCx this is Korean patch for blackwell_unbound, blackwell_legacy to AGS 3.6 and If on a Winter's Night Four Travelers.
> 
> This is a custom engine, based on AGS 3.5.0.31, which did not support unicode properly. For unicode it uses a plugin called AGSBMFontRenderer (https://github.com/bggd/AGSBMFontRenderer). This plugin seems to require a slightly different font format (*.font, which may be a classic SCI font format), but I am not completely sure.
> 
> @Leemann07, you should be using AGS 3.6.0 or 3.6.1 engine with a proper unicode support. They may be able to display Korean language without any extra plugins.
> 
> For this to work, the translation file (korean.trs) should have a proper header with encoding, as explained in the manual: https://adventuregamestudio.github.io/ags-manual/Translations.html#additional-options
> 
> Translation should be compiled by a translation compiler that can understand the encoding setting. We have a newer translation compiler program in our repository, its code may be found here: https://github.com/adventuregamestudio/ags/tree/master/Tools/trac But the ready program for Windows may also be downloaded here: https://www.dropbox.com/s/6wfl3foo3jb9iyu/agstools-360.zip?dl=1 compiler is called "trac.exe".
> 
> This will result in "korean.tra" file, usable with the AGS games.
> 
> If you're using AGS 3.6.0, then you may only use TTF fonts for Korean language. If you are using 3.6.1, then you might as well use WFN fonts.

Thank you so much again for your help. I will study by reading and re-reading the article and everything in the link. I wish people who like adventure games could play the games in Korean. :)
Thank you and Best Regards Leemann

**Comment by ivan-mogilko** [comment]
By the way, while investigating this, I found some function in Allegro code for unicode "space" detection:
https://github.com/adventuregamestudio/ags/blob/59e1a5a4a5908e6aa0cbbe344b522da064be3e56/libsrc/allegro/src/unicode.c#L1716-L1725

We are not using this anywhere, but maybe we should use this in a line-wrapping function. May be worth investigating what these special character codes refer to.

**Comment by ericoporto** [comment]
@ivan-mogilko I think from the upload that your trs solved the issue.

About word-wrapping note that Hangul nowadays is mostly written left to right with spaces, so our current approach works.

**Comment by ivan-mogilko** [comment]
Hmm, okay, I will close this as resolved. If there are any specific problems with Korean or other languages in 3.6.0/3.6.1, please open new tickets for these.
