### ISSUE TITLE
Plugin API: add a CreateScriptArray method

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2313]
When a plugin registers a script function that returns a `String`, it must use `IAGSEngine::CreateScriptString` in order to create an internal engine's ScriptString object, that engine knows how to deal with.

But there's no such function for creating a dynamic array object. This means that plugins cannot register script functions that return dynamic arrays.

Optionally same could be done for "user struct" object. The use case for this is when plugin wants to return a managed struct, but not manage that struct type itself: don't provide a type's manager, and have struct's data stored in engine's mem.

**Comment by ericoporto** [comment]
The closest thing for this we already have is the `DynamicArrayHelpers` function to create string arrays - we use for retrieving keys from the dictionary and the set.

https://github.com/adventuregamestudio/ags/blob/ced74c55e6b24a6c64e6e8a76f75f925d7915cdc/Engine/ac/dynobj/cc_dynamicarray.cpp#L100-L117

**Comment by ivan-mogilko** [comment]
> Don't know how to make this generic for any object as plugin interface. Take both void* and handle of each element?

If a plugin returns dynamic array, then it knows the type and size of elements. The engine only need to know the size of element, and its count, in order to create a buffer of necessary length. Plugin will be supposed to write the memory itself.

Since we support RTTI in ags4, then perhaps "type" could be another argument, but it's not clear to me how plugin may know which value to pass.

> We never in script take an array as input! So the reverse of receiving an array as input in a plugin would take more effort.

Plugin can receive arrays just like it can receive strings: a pointer to a buffer of memory.
