### ISSUE TITLE
Speech.DisplayPostTimeMs and "..." causes endless loop

### ISSUE THREAD

**Issue by codengine** [adventuregamestudio/ags#2327]
**Describe the bug**
So while I was playing around and trying to learn AGS I noticed a very strange behavior.
I downloaded a testgame from https://github.com/ManiacMansionMania/Michael-SP and played around with the source. The following code will provoke an endless loop:

```
      Speech.DisplayPostTimeMs = 1000;
      player.Say("&2 Fast alles Bücher über Emuzucht ...");
      player.Say("...");
      player.Say("&3 Jetzt bin ich ein bisschen verwirrt.");
```

After player.Say("...") the game does not continue as shown in this video:
https://streamable.com/d4943e

It seems to interfere with the setting of DisplayPostTimeMs because the issue is solved when I remove the Speech.DisplayPostTimeMs.

**AGS Version**
3.6.0.50 as well as latest dev build.

**Game**
Based on Maniac Mansion Mania.
[Michael-SP-bug.zip](https://github.com/adventuregamestudio/ags/files/14154729/Michael-SP-bug.zip)

**To Reproduce**

1. Start the game
2. Click on "Start"
3. Click on "Schau" (look) and the books

The code can be found at Room 20, starting at line 254.

**Expected behavior**
The dialog should continue after the pause (caused by "...")

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2

**Additional context**
It also happens with ScummVM. The reason seems to be that this code

```
        if (_GP(play).messagetime < 1 && _GP(play).speech_display_post_time_ms > 0 &&
                _GP(play).fast_forward == 0) {
            if (!_GP(play).speech_in_post_state) {
                _GP(play).messagetime = ::lround(_GP(play).speech_display_post_time_ms * get_current_fps() / 1000.0f);
            }
            _GP(play).speech_in_post_state = !_GP(play).speech_in_post_state; // <-----
        }
```
...toggles _GP(play).speech_in_post_state on and off.

**Comment by ivan-mogilko** [comment]
Hmm, the situation is even more silly than that. This endless "post state" loop also happens if the speech is set to be skipped only by player's input (not by time). In such case when the "post state" flag is repeatedly set on and off and on again, and more messagetime assigned. It's just that this is not causing any troubles with the regular speech, as player may click it off anytime. But internal logic is wrong nevertheless.

**Comment by codengine** [comment]
While debugging through ScummVM (because I was not sure if it was a Scumm or AGS issue) and given they adopted a lot of this code, I could observe the same.

In ScummVMs case, it seems that it is enough to just set the value for "isInPostState" to true instead of toggling it (value!=value) but I haven't checked all other code paths there.

Maybe that helps?

**Comment by ivan-mogilko** [comment]
That is almost the fix that I am preparing, but I need to test several speech cases to make sure that there's nothing tied to this post state being toggled off in the end.

**Comment by ivan-mogilko** [comment]
Pushed 37360990b22a79380f2a5b34e686a2d2fbcf7de1,
I suppose it should be trivial to port to ScummVM.

**Comment by ivan-mogilko** [comment]
I guess this is resolved then.

**Comment by codengine** [comment]
Once the next RC is available, I'll test it :) Thanks again for the quick fix.

**Comment by ericoporto** [comment]
@codengine just mentioning in case it helps, we have a CI that builds the artifacts. When a tag is created, a new build is triggered, but the difference then is the matching GitHub release gets some specifics of the artifacts packaged and uploaded 

So all pushes that generates a build appears here
https://cirrus-ci.com/github/adventuregamestudio/ags

I believe that specific commit the full Editor package that includes the engine (`acwin.exe` and the `SDL2.dll`) is this one, the download is labeled "archive"

https://cirrus-ci.com/task/6692138243588096

**Comment by codengine** [comment]
@ericoporto Thanks for the information. I only saw the build action at github (which failed for windows for some reason), I didn't know that there is a separate CI system.

**Comment by ivan-mogilko** [comment]
I made a mistake, for some reason I thought that you had a chance to test these changes.

Since the bug report was regarding 3.6.0 version, I might mention the list of builds for 3.6.0 may be found here:
https://cirrus-ci.com/github/adventuregamestudio/ags/release-3.6.0
for example, the latest one is this:
https://cirrus-ci.com/build/4896757256028160
I am releasing patches to the existing "stable" version about once per 1-2 months, usually when a number of fixes are accumulated.

**Comment by tag2015** [comment]
I haven't pushed the fix to the ScummVM repo yet, but I can confirm that the issue is solved.

**Comment by codengine** [comment]
Can confirm that it is fixed, thanks!
