### ISSUE TITLE
Creating a sprite from surface may give sprite of wrong depth if it's size is invalid

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2345]
**Describe the bug**
When running the code below

```AGS Script
DynamicSprite* spr2 = DynamicSprite.CreateFromDrawingSurface(surf1, 50, 50, 0, 100); // note width is zero
surf1.DrawImage(51, 51, spr2.Graphic);
```

It will warn the following: `(room:1)[R 16] DrawImage: Sprite 2 colour depth 8-bit not same as background depth 32-bit`

But the actual issue is the created sprite is invalid, because it's size is 0.

**AGS Version**
3.6.1.20 but it can also be reproduced in current master (https://github.com/adventuregamestudio/ags/commit/2e5ac6dbf2ccb623a712541c68a18d5c28123efe)

**Game**
[DrawingInvalid.zip](https://github.com/adventuregamestudio/ags/files/14470857/DrawingInvalid.zip)

**To Reproduce**
You can just run the attached game and it will produce the warning mentioned in the log.

Alternatively do these steps to reproduce the behavior:
1. Create a new game from the Sierra Template and add an After Fade-in event to the room script
2. Add this code to the room script

```AGS Script
Overlay* rovr;
function room_AfterFadeIn()
{
  DynamicSprite* spr1 = DynamicSprite.CreateFromBackground();
  DrawingSurface* surf1 = spr1.GetDrawingSurface();
  
  DynamicSprite* spr2 = DynamicSprite.CreateFromDrawingSurface(surf1, 50, 50, 0, 100); // note width is zero
  surf1.DrawImage(51, 51, spr2.Graphic);
  
  surf1.Release();
  spr2.Delete();
  rovr = Overlay.CreateRoomGraphical(0, 0, spr1.Graphic, true, true);
  rovr.ZOrder = -1;
}
```

4. Run the game in the Editor and make sure the log has level 5 - Warn available
5. It will print in the log
```
[Main][Info]: Starting game
[Game][Warn]: (room:1)[R 15] DrawImage: Sprite 2 colour depth 8-bit not same as background depth 32-bit
```

**Expected behavior**
Because AGS has apparently allowed invalid zero size sprites to exist, I guess adding a warning in the log that the sprite is size zero would work, when it's created. It would be good to print the line it's happening so someone can track and fix.

Alternatively detect this is over a certain version and maybe quit in a way that the editor could point to that line so the user can fix?

**Desktop:**
 - OS: Windows
 - Version 10

**Additional context**

There are actually asserts for width or height being zero in allegro code when a bitmap is created but neither of them are triggered when running in debug for me.

**Comment by ivan-mogilko** [comment]
Not long ago I added following safety check for DynamicSprite.Create:
```
    if (width <= 0 || height <= 0)
    {
        debug_script_warn("WARNING: DynamicSprite.Create: invalid size %d x %d, will adjust", width, height);
        width = std::max(1, width);
        height = std::max(1, height);
    }
```
IIRC this was done for backwards compatibility.

I believe then same should be added to CreateFromDrawingSurface for consistency.

**Comment by ivan-mogilko** [comment]
Alright, so what happens here actually is that the bitmap is created with correct color depth, but when trying to put it into a SpriteCache, SpriteCache rejects it as being "size = 0", and the slot remains empty. Next time this sprite is requested, SpriteCache returns a placeholder, which is a 1x1 8-bit image. It looks like it's 8-bit by coincidence.

What needs to be done here is to check the result of setting a sprite into a SpriteCache, and also check whether bitmap is valid earlier when adding a dynamic sprite, and make sure that DynamicSprite.Create... functions return null if something like this happens.

**Comment by ivan-mogilko** [comment]
Okay, I pushed 3 small commits in regards to this:
9c54262d973114110952b8794d737e6e45a532fb
83e78fb1341b6852fb13366bae5aaed340571651
9d12250e5756f406eb1cfe2d7062d5d8bd931b0c

**Comment by ericoporto** [comment]
Thank you! This fixes. Tried in my actual game and also in my test game. Got the `[Game][Warn]: (room:1)[R 14] WARNING: DynamicSprite.CreateFromDrawingSurface: invalid size 0 x 100, will adjust` message in the test game.
