### ISSUE TITLE
Illegal Exception in No-Action Jackson

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2366]
**Describe the bug**
No-Action Jackson crashes with an Illegal exception right after the intro (intro can be skipped pressing ESC)

An exception 0xC0000005 occurred in ACWIN.EXE at EIP = 0x004951DA; program pointer is +6, engine version 3.6.0.57, gtags (0,12)
[CrashInfo.3.6.0.57.dmp](https://github.com/adventuregamestudio/ags/files/14761249/CrashInfo.3.6.0.57.dmp)

**AGS Version**
Latest 3.6.0/3.6.1

**Game**
https://archive.org/details/No-Action_Jackson

**To Reproduce**
1. Start game
2. Wait (or skip) intro

**Desktop**
Win10

**Comment by ivan-mogilko** [comment]
This seems to happen when hovering a cursor over certain areas on the game screen. For some reason the "GetHotspotProperty" is called with -1 index.

**Comment by ivan-mogilko** [comment]
Pushed a fix: 99f94c469636522bd2d89923901659476d816577

**Comment by tag2015** [comment]
Thanks for the quick fix! Confirmed working
