### ISSUE TITLE
Function in Engine/ac contains unreachable code

### ISSUE THREAD

**Issue by MoreMoschops** [adventuregamestudio/ags#237]
The function  "int IsKeyPressed (int keycode)" in file "engine/ac/global_game.cpp" contains unreachable code at lines 623, 625, 627 and 629.

Clearly at some point someone wanted those lines to be reachable and that code to execute, but instead each of them has a forerunner that does something slightly different. I don't know enough about those lines to have the confidence to either delete them or change them, although I'm happy to poke at it and see what I can deduce if nobody stops me...

**Comment by MoreMoschops** [comment]
Having had a poke round, though, I can't actually see anywhere that the function is called from, unless it's done magically through function pointers or that huge RegisterGlobalAPI() function or some such. Sure are a lot of globals hanging around!

**Comment by monkey0506** [comment]
This function is only called by game scripts, it is never called directly by the engine. Still, best not to have unreachable code.

**Comment by monkey0506** [comment]
It seems like the entire IsKeyPressed function really seems rather naive in its implementation. It reuses the keycode argument to ultimately be forwarded to the rec_iskeypressed function, but yet it is intermingled with other calls to that same function. This makes the function far less readable than if it simply called rec_iskeypressed with the appropriate parameters as needed.

In particular, if keycode is 380, then what would make sense would be to check rec_iskeypressed(85) (actual down arrow key) or that Num Lock is not activated and rec_iskeypressed(39) (Numpad Key 2). The way the function is right now I would expect it to yield incorrect results for Numpad Key 2 as a down arrow -- unless Allegro 4 makes an exception for this. From what I can see though, it really looks like Allegro 4's keyboard handling was kind of a mess in the first place...

My recommendation would really be to rewrite the entire method.

**Comment by MoreMoschops** [comment]
I freely confess I just happened to notice the unreachable code in passing; exactly what this function is up to is a bit of a mystery to me. Looks like it really should be kicking back a bool rather than an int (given that the possible return values are 1 or 0, and the function name is a question), but for such a function it seems to have a lot of side effects going on; is it not just checking is a key is pressed, but also updating global state in the event that a key is being pressed? 

Plus, of course, it's heaving with magic numbers! I did stick a breakpoint in here, run up a game and see what I had to do to provoke this function call, but nothing doing. Presumably the test game I used simply doesn't call this? 

I don't know nearly enough about this; thanks for your patience. I just saw something odd and started digging.

**Comment by monkey0506** [comment]
You would have to actually have an AGS script call "IsKeyPressed(KEYCODE);" or this function would never be invoked. A typical place to do this would be in the repeatedly_execute function in the GlobalScript.asc.

The fact that the return type is int is an artifact of the compiler I believe. IIRC the (game script) compiler won't work correctly with the native bool type and will result in some junk value being returned. I think it expects all return types to be exactly 4 bytes. The simplest way of dealing with this for boolean results is just to have the native methods return an int and check it against 0 or 1.

**Comment by MoreMoschops** [comment]
Okey dokey. I've been having a look at how to do this, and there's a fair chance I'll get round to creating enough of a game to get the script going and call IsKeyPressed, so I can watch it go round.

It occurs to me that other people who work on this almost certainly have such things themselves; test games that are the worst games ever made, but just exercise calls accordingly for testing purposes.

All return types needing to be four bytes exactly has made a siren go off inside my head. Would I be right in surmising that there is some significant difficultly existing in creating a 64-bit version?

**Comment by ivan-mogilko** [comment]
> All return types needing to be four bytes exactly has made a siren go off inside my head. Would I be right in surmising that there is some significant difficultly existing in creating a 64-bit version?

The script values are limited to 32-bit, indeed. We were rewriting a lot in the engine to remove 64-bit incompatibilities, and it may run on 64-bit system in general case, however there's still one big problem: the plugins are allowed to pass *pointers* to script interpreter as 32-bit integer values, which is obviously incompatible with 64-bit system.
The solution we were discussing for some time is simply to rewrite plugin interface from scratch.

**Comment by ivan-mogilko** [comment]
Function IsKeyPressed was since refactored, so this is not relevant anymore.

**Comment by ivan-mogilko** [comment]
I made a mistake, it was a different function that was refactored. Looking closer (and comparing to older version from 2015), the unreachable code is still there, only line numbers have shifted a little.

It is not obvious at the first glance, but in this big if/else switch there are *duplicating conditions*, which lead to *different actions*:

<pre>
        // left arrow
        else if (keycode==375) keycode=382; // <-------------------- 1
        // right arrow
        else if (keycode==377) keycode=383; // <-------------------- 2
        // up arrow
        else if (keycode==372) keycode=384; // <-------------------- 3
        // down arrow
        else if (keycode==380) keycode=385; // <-------------------- 4
        // numeric keypad
        else if (keycode==379) keycode=338;
        else if (keycode==380) keycode=339; // <-------------------- 4
        else if (keycode==381) keycode=340;
        else if (keycode==375) keycode=341; // <-------------------- 1
        else if (keycode==376) keycode=342;
        else if (keycode==377) keycode=343; // <-------------------- 2
        else if (keycode==371) keycode=344;
        else if (keycode==372) keycode=345; // <-------------------- 3
        else if (keycode==373) keycode=346;
</pre>

No idea how that was supposed to work.

**Comment by sonneveld** [comment]
Closing as this has been refactored.
