### ISSUE TITLE
whispers of a machine notebook invisible

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#2386]
**Describe the bug**
in whispers of a machine, after collecting few hints, when starting a conversation a notebook is supposed to be displayed that let's one click on certain topics. currently, the notebook is invisible, when enough hints are collected that multiple pages should be displayed, one can only see the arrows to move left and right and see an animation moving the pages, but then the screen is empty again.

**AGS Version**
git master as of 4 days ago

**Game**
woam 1.06

**Screenshots**
https://0x0.st/X-tB.png

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
there's also some warning output which seems related to savegames:
Restoring saved game './saves/agssave.101'
WARNING: global variable refers to data beyond allocated buffer (1564, 1564)
WARNING: global variable refers to data beyond allocated buffer (1564, 1564)
WARNING: looking up for global variable beyond allocated buffer (1564, 1564)
WARNING: looking up for global variable beyond allocated buffer (1564, 1564)
WARNING: looking up for global variable beyond allocated buffer (1564, 1564)

**Comment by rofl0r** [comment]
note: i extracted the windows installer using innoextract. there's 2 ttf fonts in tmp/ that may be supposed to be installed in the system - i didn't do that. maybe that explains the missing text (failure to use a fallback font), but not the invisible book pages.

**Comment by rofl0r** [comment]
hmm, i started the game accidentally with an older engine version - f7b90bbaaa242e4dc79d26fdddaf7e269e7ce600 , then continued with latest. starting from scratch with the latest engine makes the book visible. then i guess the bug is only the savegame processing from earlier revision.

**Comment by ivan-mogilko** [comment]
> WARNING: global variable refers to data beyond allocated buffer (1564, 1564)

So, this was usually caused by an empty struct as a global variable, compiler allowed this by mistake, and couple of older games have this.

**Comment by rofl0r** [comment]
hmm, the issue with asking every question twice still exists. reopen ?

**Comment by ivan-mogilko** [comment]
> edit: i forgot to mention that when clicking on an invisible entry in the book, the question is always asked twice. maybe another bug.

Could you elaborate more on what is happening?

I tested both original win exe, and running with the latest master, and I noticed that if you keep clicking through the dialog without moving the mouse away, then eventually you may trigger the same topic by mistake before the notebook visually appears on screen.

When I moved cursor away, I just clicked through whole dialog and it did not repeat on its own.

In regards to fonts, IIRC this game used SpriteFont plugin for them.

**Comment by rofl0r** [comment]
in first scenario, talk with the worker with bloody hands, and click on name of victim in the book (2nd page - persons), even if you carefully only clicked once Q is asked twice - and you cant seem to abort listening to the dialogue a second time.

**Comment by rofl0r** [comment]
yes, you're right. when moving the cursor away after clicking, the Q is only asked once. if you leave it on the same spot you clicked, it's as if you clicked again after the dialogue is finished. that sounds like a bug to me.

**Comment by ivan-mogilko** [comment]
I retested again, and I cannot reproduce this problem in the original game; maybe I did a mistake earlier.
In which case there's something incorrect with the newer engine behavior. I will write a new issue for this.
