### ISSUE TITLE
Editor: improve Preprocessor error reporting for Dialog scripts

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2389]
There's this problem that Dialogs are compiled like a one huge script module. Compiler can handle error reporting there, because it uses "sections" that let name certain regions in the code and reset line number counting. But preprocessor does not do that.

As a result, any preprocessor's error in dialogs mentions `_DialogScripts.asc` and a linenumber inside a combined mix of dialog scripts, rather than a linenumber in an individual dialog script, making searching for the source of error a tough task for the user.

An example of a preprocessor error is non-closed string literal, for instance.

What could be done is to either teach preprocessor to parse the same "section" info that compiler does, or invent an alternative method of storing this information (where individual dialogs start and end in the combined file).

This information may be generated while gathering or converting dialog scripts, then stored, and used when reporting preprocessor's errors. I.e. if preprocessor errors at line X, that number would be converted to a matching dialog N and line M in that dialog script.

**Comment by fernewelten** [comment]
As far as I can see, there are _two_ preprocessors in play: The one in the Editor, file Preprocessor.cs; and the one in the "classic" compiler, file preprocessor.cpp. 

Are they both in use? Do we have to develop modifications in tandem, see to it that both preprocessors react in the same way to the same inputs?

**Comment by ivan-mogilko** [comment]
> Are they both in use? Do we have to develop modifications in tandem, see to it that both preprocessors react in the same way to the same inputs?

Yes, one in the Editor is used by the Editor, and another is written for the standalone compiler executable in C++.
They share functionality.
I suppose that eventually we will stop using one in the Editor and use only standalone one.

**Comment by ericoporto** [comment]
> What could be done is to either teach preprocessor to parse the same "section" info that compiler does

The preprocessor is who currently writes this line.

https://github.com/adventuregamestudio/ags/blob/e0854823da9ce01215858db7ecc3e0e32b3293c3/Editor/AGS.CScript.Compiler/Preprocessor.cs#L48

**Comment by fernewelten** [comment]
I've now done a PR with @ericoporto 's idea, cf. #2615.

The preprocessor.cs now emits error messages that you can click on in the editor. 

I couldn't test the preprocessor.cpp of the "classic" compiler project.

**Comment by ericoporto** [comment]
I don’t get it, I never said that, I suggested to first improve the dialog parser, the issue I mentioned is that the preprocessor currently is the one responsible for putting the section markers in place.

**Comment by ivan-mogilko** [comment]
> The preprocessor is who currently writes this line.
>
https://github.com/adventuregamestudio/ags/blob/e0854823da9ce01215858db7ecc3e0e32b3293c3/Editor/AGS.CScript.Compiler/Preprocessor.cs#L48


Preprocessor only adds the first marker in the beginning of the script.
The markers between dialogs are added by the DialogScriptConverter:

https://github.com/adventuregamestudio/ags/blob/2e3cfaadc040a03d3ab5cadc907c0dbf0bb89c10/Editor/AGS.Editor/Utils/DialogScriptConverter.cs#L35

**Comment by ivan-mogilko** [comment]
#2615 was merged to ags4, I will apply any compatible changes to ags3 and then close this.

**Comment by ivan-mogilko** [comment]
Okay, fixed in 3.6.2 too.
