### ISSUE TITLE
[QUESTION] Why does the engine script compiler generate a new function?

### ISSUE THREAD

**Issue by Antonin-Carette-RedArtGames** [adventuregamestudio/ags#2392]
Hi,
We have a question about the AGS Script compiler and how the compiler generates code for an extended function.

We have written this extended function for `Character`:

```ags
function SayExtended(this Character*,  String line)
{
  ...
  this.SayAt(posX, posY, width, line);
  return;
}
```

As you can see here, we use the default `SayAt` function from `Character`, with the same number of arguments.
Also, we use the same type for each argument.

However, when we look at the btree in the engine side, we have two different `SayAt` functions:
* `SayAt^4`, the default one
* `SayAt^104`, a new generated function.

If we comment the `SayAt` call in `SayExtended` we don't have any `SayAt^104` in our btree, so we know that this function has been generated from `SayExtended`.

Looking at [the official documentation](https://github.com/adventuregamestudio/ags/wiki/A-quick-guide-to-Script-API#script-functions-registration) it says:
> There's a rule on the name under which the function has to be registered. First of all, this name must match the function declaration in built-in header. Optionally, the name may include a postfix ^X where X is a number of function arguments.

So I expect that `^104` is set for **extended function (10) with 4 arguments (4)**, right?

I don't really understand why the compiler generates  a new function for `SayAt`, especially as we use the default one.

Also, if I try to use another function like `Move` in another extended function, like this below, I don't have another `Move` function that has been generated:

```ags
function MoveExtended(this Character*) {
  this.Move(0,  0,  0,  0); // This uses the `Move^4` of the std lib
}
```

Is there something we missed in the documentation about this behaviour?
Thanks a lot.

**Comment by Antonin-Carette-RedArtGames** [comment]
I forgot to add this information: we are using the AGS 3.6.1.11 (BETA VERSION).

**Comment by ericoporto** [comment]
> btree in the engine side

How are you doing this?

Anyway, in 3.6.1 we added support for format string directly in SayAt.

**Comment by Antonin-Carette-RedArtGames** [comment]
>How are you doing this?

In the engine side, on Visual Studio, I have put a breakpoint in line
```c++
 resolved_imports[import_idx] = simp.get_index_of(scri->imports[import_idx]);
```,
in the function `bool ccInstance::ResolveScriptImports(const ccScript *scri)`.

If I enter the function I get a `btree` variable and I can see the two `SayAt` functions (please check the screenshot attached).
![sayAt_VS](https://github.com/adventuregamestudio/ags/assets/105704991/730784a8-4d6f-4ece-a3ac-62eb3c4d367a)

Is there any reason the compiler generates a new `SayAt` function please?

**Comment by ivan-mogilko** [comment]
"100" in a internal function name stands for "variable number of parameters", and is assigned for variadic functions.
"104" means a variadic function with 4 explicit parameters preceding variable list.

SayAt was made a variadic function since 3.6.1.

Engine registers both functions for backwards compatibility, so that old games were also able to run old function variant.

**Comment by Antonin-Carette-RedArtGames** [comment]
Thank you @ivan-mogilko, I understand now.
