### ISSUE TITLE
Script API: remove 2048 length limit for the variadic text functions

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2398]
Historically, all the text printing script functions have a limit of resulting string. It was an arbitrary 3000 bytes around 3.6.0, in current master it's 2048, but that's not the point. Because AGS Strings may contain up to INT32_MAX bytes, there should not be any restriction on a length of a string that a user may create using e.g. String.Format.

Printing script args is done using ScriptSprintf function. I propose to fix this function to make it act in compliance with standard snprintf: that is let pass a null buffer in which case it would only calculate and return necessary size. Formatting will be done in two steps: first calculate the necessary buffer length, then allocate a StringBuffer, print text, and create ScriptString, or use this text elsewhere as necessary.

**Comment by ericoporto** [comment]
I was playing with this by looking into the function before I realized I don't know where the call to this is 

https://github.com/ericoporto/ags/commit/5f485b16ac0f9692919e41c605818e11bcf50a6d

Beyond the tests, I can't figure how this actually get called in `String.Format`, and don't know how to modify to take the null buffer, but maybe my initial sketch is useful?

**Comment by ericoporto** [comment]
Hey, I fixed remaining issues with getting it to actually work and I can pass tests that doesn't limit the buffer length, but I don't know how to actually make this function be used by the Engine because my IDE can only find reference to it in tests...

https://github.com/ericoporto/ags/commit/fd8e95ca5d6ca2ae8be9075969dc2e8f191ad555

**Comment by ivan-mogilko** [comment]
The ScriptSprintf function is called from within several macros:
https://github.com/adventuregamestudio/ags/blob/525b1aa8b3b314c4f1b05ea528fd62e84f6f9d6f/Engine/script/script_api.h#L71-L107


I've been planning to look into this when i get more spare time, and possibly investigate how `sprintf` is dealing with this in some of the standard library sources. Because it would be good to not slow things down unnecessarily. I wrote this function many years ago, maybe it's not as optimal on its own, and especially with length calculation mode it may be worth to revise its process.

Not ready to make any exact proposals, but for instance, it may be that instead of doing a check char-by-char this function could instead search for the next placeholder, and only then check "if we count length or write" once and either add a pointer diff to calculate length or memcpy the range of bytes. That's just an example.

Of course, it's difficult to tell what's better without a proper speed test (not fps test, but measuring time while this function is called many times in a loop).

**Comment by ericoporto** [comment]
ok, I think I understand these macros, but I think I am missing some C++ compatible solution that would allow the dynamically sized buffer to be deallocated when the function that runs it exits.

I guess the way to go with less changes would be to modify `ScriptSprintf` to return the type `std::unique_ptr<char[]>` and move the resulting buffer. Using this we will lose the information of the size of the buffer, but looking into ags code we currently don't use this information. The alternative would be using a vector.

**Comment by ivan-mogilko** [comment]
> , but I think I am missing some C++ compatible solution that would allow the dynamically sized buffer to be deallocated when the function that runs it exits.

std::vector<char>?

std::unique_ptr<char[]> might also work. But vector has an advantage that you may reserve a global one to reduce memory allocations each time a Sprintf is called; in which case you keep same vector, and only increase it if capacity is not enough.
