### ISSUE TITLE
AGS incompatible Version

### ISSUE THREAD

**Issue by JPRuehmann** [adventuregamestudio/ags#240]
Since a Week or so I get more and more messages that Ags is outdated.

AGS: Adventure Game Studio v3.3 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2014 others
ACI version 3.3.3.0

AGS: *** ENGINE STARTUP ***
AGS: Reading config file
AGS: Initializing allegro
AGS: Setting up window
AGS: Initializing game data
AGS: Game data file: /home/ruehmann/Data/.wine/drive_c/Foundations/Foundations.exe

AGS: Initializing TTF renderer
AGS: Initializing mouse
AGS: Checking memory
ci_find_file: cannot change to directory: Compiled
AGS: Initializing audio vox
Audio vox found and initialized.
AGS: Initializing keyboard
AGS: Install timer
Checking sound inits.
AGS: Initialize sound drivers
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: Datei oder Verzeichnis nicht gefunden
AGS: Install exit handler
AGS: Initialize path finder library
AGS: Load game data
AGS: Game data version: 46
AGS: Requested engine version: 3.4.0.3
This game requires a newer version of AGS (3.4.0.3). It cannot be run.Invalid file format. The file may be corrupt, or from a different
version of AGS.
This engine can only run games made with AGS 2.5 or later.

How can I get a compatible Version.
The Games won´t work under wine to.

I am using Kubuntu 14.04 LTS

**Comment by tobihan** [comment]
That happens when people create their games with the development version
of AGS. You need to use the develop-3.4.0 git branch to run such games.

**Comment by JPRuehmann** [comment]
How can I get this?
    I had not found any Link other than the normal github Link.
    
    Am 22.04.2015 um 10:45 schrieb BigMc:
    
    That happens when people create their games with the
      development version
      of AGS. You need to use the develop-3.4.0 git branch to run such
      games.
      
      
      On 04/22/2015 10:40 AM, Jan-Peter Rühmann wrote:
      > Since a Week or so I get more and more messages that Ags is
      outdated.
      > 
      > AGS: Adventure Game Studio v3.3 Interpreter
      > Copyright (c) 1999-2011 Chris Jones and 2011-2014 others
      > ACI version 3.3.3.0
      > 
      > AGS: *** ENGINE STARTUP ***
      > AGS: Reading config file
      > AGS: Initializing allegro
      > AGS: Setting up window
      > AGS: Initializing game data
      > AGS: Game data file:
      > /home/ruehmann/Data/.wine/drive_c/Foundations/Foundations.exe
      > 
      > AGS: Initializing TTF renderer
      > AGS: Initializing mouse
      > AGS: Checking memory
      > ci_find_file: cannot change to directory: Compiled
      > AGS: Initializing audio vox
      > Audio vox found and initialized.
      > AGS: Initializing keyboard
      > AGS: Install timer
      > Checking sound inits.
      > AGS: Initialize sound drivers
      > ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open
      /dev/snd/midiC0D0
      > failed: Datei oder Verzeichnis nicht gefunden
      > AGS: Install exit handler
      > AGS: Initialize path finder library
      > AGS: Load game data
      > AGS: Game data version: 46
      > AGS: Requested engine version: 3.4.0.3
      > This game requires a newer version of AGS (3.4.0.3). It
      cannot be
      > run.Invalid file format. The file may be corrupt, or from a
      different
      > version of AGS.
      > This engine can only run games made with AGS 2.5 or later.
      > 
      > How can I get a compatible Version.
      > The Games won´t work under wine to.
      > 
      > I am using Kubuntu 14.04 LTS
      > 
      > —
      > Reply to this email directly or view it on GitHub
      >
      <https://github.com/adventuregamestudio/ags/issues/240>.
      > 
      
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    Thanks,
    -- 
      -==================================== Jan-Peter Rühmann  ===========================-
 Gubkower Str.7             [ Tel.:  +49 (38205) 65484  ]     jan-Peter@ruehmann.name
 18195 Prangendorf          [ FAX:   +49 (38205) 65212  ]    http://www.ruehmann.name
                            [ Tel.:  +49 (38205) 65215  ]
                            [ Mobil: +49 (162) 1316054  ]         IT-Servicetechniker
Skype: jan-peter_ruehmann / ICQ: 288192920 / Yahoo: jpruehmann / Twitter: @JPRuehmann
-===================================================================================-
                Die Verwendung der Daten zu Werbezwecken ist verboten.

**Comment by tobihan** [comment]
In your ags folder you cloned with git you do

git checkout develop-3.4.0

Everything else should work the same as on the master branch.

**Comment by JPRuehmann** [comment]
Thanks that worked.
    
    Am 22.04.2015 um 11:29 schrieb BigMc:
    
    In your ags folder you cloned with git you do
      
      git checkout develop-3.4.0
      
      Everything else should work the same as on the master branch.
      
      On 04/22/2015 11:27 AM, Jan-Peter Rühmann wrote:
      > 
      > 
      > 
      > 
      > 
      > 
      > 
      > How can I get this?
      > I had not found any Link other than the normal github Link.
      > 
      > Am 22.04.2015 um 10:45 schrieb BigMc:
      > 
      > That happens when people create their games with the
      > development version
      > of AGS. You need to use the develop-3.4.0 git branch to run
      such
      > games.
      > 
      > 
      > On 04/22/2015 10:40 AM, Jan-Peter Rühmann wrote:
      >> Since a Week or so I get more and more messages that Ags
      is
      > outdated.
      >>
      >> AGS: Adventure Game Studio v3.3 Interpreter
      >> Copyright (c) 1999-2011 Chris Jones and 2011-2014 others
      >> ACI version 3.3.3.0
      >>
      >> AGS: *** ENGINE STARTUP ***
      >> AGS: Reading config file
      >> AGS: Initializing allegro
      >> AGS: Setting up window
      >> AGS: Initializing game data
      >> AGS: Game data file:
      >>
      /home/ruehmann/Data/.wine/drive_c/Foundations/Foundations.exe
      >>
      >> AGS: Initializing TTF renderer
      >> AGS: Initializing mouse
      >> AGS: Checking memory
      >> ci_find_file: cannot change to directory: Compiled
      >> AGS: Initializing audio vox
      >> Audio vox found and initialized.
      >> AGS: Initializing keyboard
      >> AGS: Install timer
      >> Checking sound inits.
      >> AGS: Initialize sound drivers
      >> ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open
      > /dev/snd/midiC0D0
      >> failed: Datei oder Verzeichnis nicht gefunden
      >> AGS: Install exit handler
      >> AGS: Initialize path finder library
      >> AGS: Load game data
      >> AGS: Game data version: 46
      >> AGS: Requested engine version: 3.4.0.3
      >> This game requires a newer version of AGS (3.4.0.3). It
      > cannot be
      >> run.Invalid file format. The file may be corrupt, or from
      a
      > different
      >> version of AGS.
      >> This engine can only run games made with AGS 2.5 or
      later.
      >>
      >> How can I get a compatible Version.
      >> The Games won´t work under wine to.
      >>
      >> I am using Kubuntu 14.04 LTS
      >>
      >> —
      >> Reply to this email directly or view it on GitHub
      >>
      >
      <https://github.com/adventuregamestudio/ags/issues/240>.
      >>
      > 
      > —
      > Reply to this email directly or view
      > it on GitHub.
      > 
      > 
      > 
      > 
      > 
      > 
      > 
      > 
      > Thanks,
      > -- 
      > -==================================== Jan-Peter Rühmann
      > ===========================-
      > Gubkower Str.7 [ Tel.: +49 (38205) 65484 ]
      jan-Peter@ruehmann.name
      > 18195 Prangendorf [ FAX: +49 (38205) 65212 ]
      http://www.ruehmann.name
      > [ Tel.: +49 (38205) 65215 ]
      > [ Mobil: +49 (162) 1316054 ] IT-Servicetechniker
      > Skype: jan-peter_ruehmann / ICQ: 288192920 / Yahoo:
      jpruehmann /
      > Twitter: @JPRuehmann
      >
-===================================================================================-
      > Die Verwendung der Daten zu Werbezwecken ist verboten.
      > 
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/adventuregamestudio/ags/issues/240#issuecomment-95091263>.
      > 
      
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    ca.
    -- 
      -==================================== Jan-Peter Rühmann  ===========================-
 Gubkower Str.7             [ Tel.:  +49 (38205) 65484  ]     jan-Peter@ruehmann.name
 18195 Prangendorf          [ FAX:   +49 (38205) 65212  ]    http://www.ruehmann.name
                            [ Tel.:  +49 (38205) 65215  ]
                            [ Mobil: +49 (162) 1316054  ]         IT-Servicetechniker
Skype: jan-peter_ruehmann / ICQ: 288192920 / Yahoo: jpruehmann / Twitter: @JPRuehmann
-===================================================================================-
                Die Verwendung der Daten zu Werbezwecken ist verboten.
