### ISSUE TITLE
Cannot import 16-color BMP file

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2416]
**Describe the bug**
When importing a room Walkbehind mask, selecting a 16-color BMP image doesn't work. The editor expects a 256-color BMP image using only the first 16 colors, which is a somewhat odd choice of file formats considering common bitmap editors (e.g. MS Paint) by default support 16-color bitmaps.
Opening a 16-color bitmap in MS Paint, saving it as 256-color BMP, and importing that doesn't help (it imports succesfully but doesn't get the full mask, presumably because MS Paint does not save the 16 colors as the _first_ 16 in a 256-color BMP).

**AGS Version**
3.6.0

**Game**
n/a

**To Reproduce**
1. Import this bitmap as a walkbehind mask: [parkmine-wb.zip](https://github.com/adventuregamestudio/ags/files/15241137/parkmine-wb.zip)

**Expected behavior**
Importing the 16-color bitmap works.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by ivan-mogilko** [comment]
It's not 16-bit specifically that is denied for masks, it's anything beyond 256 color bitmaps.

In AGS 4 the rooms already save masks strictly as indexed PNGs. This is the chosen way to go.

**Comment by ivan-mogilko** [comment]
Sorry, I misread this as 16-bit bitmap.

I think in AGS 4.0 we support indexed PNGs of any palette size, but cannot remember if we added or tried adding support for BMPs of any palette size at any point. I have vague memories of trying to make 4-bit bitmaps work.

**Comment by Crystal-Shard** [comment]
I've checked, and it appears that older versions of AGS do support 16-color BMPs. Maybe it was dropped when the engine switched to Allegro because that library doesn't support it? But of course it has since switched to SDL.

**Comment by Crystal-Shard** [comment]
Thank you, I'll check it out over the weekend.

**Comment by Crystal-Shard** [comment]
> @Crystal-Shard there's a build with this support, if you'd like to test: https://cirrus-ci.com/task/6457604614914048

I confirm that this works.
