### ISSUE TITLE
Unable to set EXE name/description: LoadLibrary failed

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2420]
**Describe the bug**
Often, when I compile a game in AGS, it gives the error: "Unable to set EXE name/description: LoadLibrary failed".
Nevertheless, the game appears to have been built successfully. But maybe the description is now missing? I'm not sure how to check that.

**AGS Version**
3.6.0

**Game**
all

**To Reproduce**
1. Click 'build'

**Expected behavior**
No error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by ericoporto** [comment]
We fixed that in 3.6.1 too... See #2376

**Comment by ivan-mogilko** [comment]
#2376 case has very specific conditions, and it never reproduced for me in 3.6.0.

There may be various reasons why this is failing, not necessarily related to #2376.

**Comment by Crystal-Shard** [comment]
> * Antivirus preventing Editor to modify a exe file;

It's probably this one. I notice that if I run the game within about five seconds after creating it, I get an error message from my antivirus (presumably, that it's still scanning). I should note that this does not happen with older versions of AGS.

> This may be checked by opening file's properties in windows explorer, and checking "Details" tab.

If you mean the .EXE file, then it says e.g. Product Name = "Made with AGS" and it doesn't contain anything that I placed in General Settings.

**Comment by ericoporto** [comment]
If you try 3.6.1 there's also a fix for Windows Defender case - if it's other antivirus idnk, but at least we get better error reporting in 3.6.1...

**Comment by ivan-mogilko** [comment]
@Crystal-Shard how easy it is to reproduce this problem? If that's like 5 times out of 10 when you rebuild the game, could you also try latest 3.6.1 release and see if it same keeps happening there?

**Comment by Crystal-Shard** [comment]
It reliably happens about 10 times out of 10 with 3.6.0.

Using 3.6.1.24, I've tried a couple times and the error doesn't seem to occur.

**Comment by ivan-mogilko** [comment]
Alright, I suppose some of the things we did there in 3.6.1 improved this situation.
