### ISSUE TITLE
XCode 11 support for AGS iOS project

### ISSUE THREAD

**Issue by Ishitori** [adventuregamestudio/ags#2421]
**Describe the problem**
I am trying to compile AGS for iOS, but unfortunately I have an old mac version with XCode 11.3.1 installed on MacOS Mojave 11.3.1 (the last one that supported 32-bit apps.) The ags/iOS/xcode/ags/AGS.xcodeproj is stored in XCode 14 and it cannot be opened in an earlier version of XCode.

As far as I understand, there is no particular requirement for this project to be compatible only with XCode 14 and higher.

**Suggested change**
The error message suggests to "Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode." 

Could someone please re-save the project file with a support of an XCode 11? Here how it supposed to look: https://forums.developer.apple.com/forums/thread/689451

@edmundito, please? :)

**Comment by edmundito** [comment]
Hello, it looks like from my Xcode, I can only downgrade it as low as Xcode 12. You could try re-creating the project for that version, but I'd have to write up how to set it up.

**Comment by Ishitori** [comment]
If you could write up how to set it up, that would be much appreciated!

**Comment by Ishitori** [comment]
I have manually changed the project version from 56 to 52 and then opened it in XCode 11 :) Then I resolved the dependencies and it worked just fine on iPhone emulator!

Thank you!
