### ISSUE TITLE
NewRoom error in old Downfall (2009) release

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2424]
**Describe the bug**
When accessing the "waxworks" room, Downfall (freeware version, released in 2009, AGS 2.72) fails with:
NewRoom: Cannot run this command, since there was a NewRoom command already queued to run in "Global script", line 379!

Seems similar to bug #2365

**AGS Version**
Latest 3.61 / 3.6.0

**Game**
[download](https://archive.org/details/downfall-2009)

**To Reproduce**
1. Load save [agssave.zip](https://github.com/adventuregamestudio/ags/files/15277566/agssave.zip)
2. Click "waxworks" hotspot (top-left street)

**Comment by ivan-mogilko** [comment]
This is strange, I specifically tried double sequential NewRoom() calls in older AGS (2.72 or earlier), and it appeared to be forbidden there as well.

**Comment by ivan-mogilko** [comment]
@tag2015, I tested this, and there's something curious. It looks like the error does not happen if you enter the security room (a small building with a "lever" on its corner) before going into "waxworks".

For a moment I thought that this is a game bug, but this error does not happen with the original executable even if you skip the security room.

**Comment by ivan-mogilko** [comment]
More details.

Apparently, in this room (this is room 48) there are two exit triggers:
1. A hotspot with "Waxworks" hint.
2. A region on ground.

Both of them call NewRoom.
So what happens is that player reaches the hotspot by walking on the region in the process. Region calls NewRoom first, and then Hotspot calls it as a part of "click" interaction (which is run after player reaches the hotspot, apparently).

In the successful case region does not work for some reason, and only hotspot runs NewRoom.

**Comment by ivan-mogilko** [comment]
@tag2015, I am fairly certain that this is a combination of the actual game bug and certain difference in the engine behavior, either pathfinding or something related to how interactions handled.

The mistake in the game is described above: there are 2 exit triggers, one attached to the region, another to hotspot. Region is activated by walking, and hotspot is activated by clicking on it.
When you activate hotspot:
1. Character tries to walk towards coordinates hardcoded as "walkto" hotspot's property.
2. If she steps onto the region anytime during this walk, the region activates and calls NewRoom.
3. This call occurs nested during walking INSIDE hotspot handling.
4. So, after this NewRoom call chacter stops, execution returns up to the hotspot processing, hotspot runs its own interaction script, and another NewRoom call is made.


What could possibly be a fix to this?
In theory, the engine could test if the room change was requested after character walked towards the hotspot; and if it's so, then don't run hotspot's own interaction.
But I am concerned if that may change behavior for other existing games.


The workaround in this game, as noted above, is to not click on "waxworks" hotspot, but on any unlabeled spot around it, thus making character to walk onto the exit region.

**Comment by tag2015** [comment]
Wow, that's some in-depth debugging, thanks!

Unfortunately I don't have better ideas on how to tackle the issue, I'll think about it

By the way the game is indeed quite buggy, e.g. if you click Agnes (in the same room) it'll fail with another script error

**Comment by ivan-mogilko** [comment]
@tag2015, I'm sorry for this delay, I don't know if you did any fix for this problem in the ScummVM ags port yet.

While I forgot about this particular bug, I made a change for unrelated reasons, where if there are multiple "change room" commands scheduled within the same script, the engine will not quit with error, but simply log a warning:
78aa1f920769edc074573c1545ec92af53ffbe0b

As an effect this also fixes current issue.
I will close this as fixed now.
