### ISSUE TITLE
Engine: Log file location hould consider platform app output directory as base path

### ISSUE THREAD

**Issue by edmundito** [adventuregamestudio/ags#2437]
**Describe the problem**
When debug mode is enabled and the engine outputs log files (such as `warnings.log`), it writes the file in the same directory as the application. This works fine for Windows games but on other platforms like macOS, iOS (and perhaps others - e.g., consoles) may not be allowed, or it may corrupt the validity of the application. For example, in Mac builds, it will create the file inside the app bundle (`/Applications/<AGS Game Name>.app/Contents/MacOS/`) instead of  where the app-generated files are located (`~/Library/Application Support/<AGS Game Name>/`)

One problem is that the implementation of outputting to warnings.log (or maybe the `create_log_output` function does not consider a path from the platform driver:

https://github.com/adventuregamestudio/ags/blob/be87b0c035763e0857a21b35c5fe48fe90da0319/Engine/debug/debug.cpp#L339

https://github.com/adventuregamestudio/ags/blob/be87b0c035763e0857a21b35c5fe48fe90da0319/Engine/debug/debug.cpp#L166

**Suggested change**
A simple solution would be to update the `create_log_output` function to ensure that the base path is always the app output directory from the driver so that each platform can provide the best path for the log files. However, this needs to be discussed first to ensure it does not impact other areas.

**Comment by ivan-mogilko** [comment]
This is not correct to decide this file's presence and path by the platform alone. On Windows the game may also be installed onto location where writing is forbidden. There has to be another factor.

So far this factor was "Debug" mode. This file "warnings.log" is written to the same folder not because it *must* be there, but because it's easy for the user to find it so when they are running the game test.

Is there a reason or a use case to package "Debug" game build into the Mac bundles, let alone Android or iOS etc app bundles?
I supposed that this should be avoided, so maybe just don't do that?

**Comment by ivan-mogilko** [comment]
Erh, of course if this file is not required on these platforms, and/or it causes other problems, then it may be moved to the same path which is used for a regular file log. This may be done by e.g. adding a function to platform driver that tells whether engine is allowed to write to the game dir at all. If it's denied, then it will use AppOutputDir from platform driver instead.

This might work as a hotfix.

For a better long-term solution, in my opinion, we should rather make a step back and reconsider existance of this "warnings.log". Because its use may not be necessary anymore, now when there's a normal configurable log file + a log panel in the editor.

**Comment by ivan-mogilko** [comment]
Nothing is logged exclusively to "warnings.log", everything is sent to all outputs, according to message filters.

**Comment by edmundito** [comment]
@ivan-mogilko

> Is there a reason or a use case to package "Debug" game build into the Mac bundles, let alone Android or iOS etc app bundles?
I supposed that this should be avoided, so maybe just don't do that?

This is a common scenario when alpha or beta testing games. Game authors provide game builds with the Debug mode enabled to access menus to jump to chapters, skip puzzles, etc.

I have personally run into this issue while running a game on a game console and recently saw the same thing for one upcoming title. 

> For a better long-term solution, in my opinion, we should rather make a step back and reconsider existance of this "warnings.log". Because its use may not be necessary anymore, now when there's a normal configurable log file + a log panel in the editor.

Testers often look at warnings.log and report back to the game author with whatever they see there.

**Comment by ivan-mogilko** [comment]
> Testers often look at warnings.log and report back to the game author with whatever they see there.

They may similarly order a normal file log to the custom path, and with wanted message filters, as explained in the readme:
https://github.com/adventuregamestudio/ags/blob/master/OPTIONS.md

**Comment by ivan-mogilko** [comment]
OTOH, the engine could support multiple log files, each with its own name and filter config.
Then the Editor could add the config for "warnings.log" into the game debug builds.
This may be planned for the next version.

Anyway, the hotfix seems to be for all non-Windows (non-Linux?) builds to write "warnings.log" to the same dir as the regular file log.

**Comment by ivan-mogilko** [comment]
@edmundito I like to clarify, in the situation where writing to the local dir is restricted, where this "warnings.log" will be expected?
In this ticket you suggest "app output directory from the driver", but that's always same directory (e.g. "C:\Users\<user>\Saved Games\Adventure Game Studio" on Windows). Which means that all games will overwrite same "warnings.log" file.

**Comment by edenwaith** [comment]
Thank you @edmundito for reporting this and to @ivan-mogilko for fixing it so quickly!

A little further context about what I've seen with this particular issue:
I saw the `warnings.log` file get written inside the Mac app bundle's `Resources` folder (`My Great Game.app/Contents/Resources/`), which is a little confusing when the code says it writes to the current working directory, which I'd assume would be in the `MacOS` folder where the executable file (generally named `AGS`) resides.

An additional thought:
At least on the Mac, would it be feasible to write any log files to the `~/Library/Logs/<Name of AGS Game>/` folder?  But relocating at least the `warnings.log` file to another location outside of the app bundle is a great improvement and won't invalidate the code signing.

**Comment by edmundito** [comment]
> At least on the Mac, would it be feasible to write any log files to the `~/Library/Logs/<Name of AGS Game>/` folder? But relocating at least the `warnings.log` file to another location outside of the app bundle is a great improvement and won't invalidate the code signing.

I was unaware of the log's location on macOS, but it may be something that can be considered. The problem is that the AGS platform driver does not provide a specific area for logs, so this would need a more long-term solution.

**Comment by ivan-mogilko** [comment]
> The problem is that the AGS platform driver does not provide a specific area for logs

It certainly does, that is what GetAppOutputDirectory() method is for.

**Comment by edmundito** [comment]
> > The problem is that the AGS platform driver does not provide a specific area for logs
> 
> In the platform interface that is what GetAppOutputDirectory() method is for. The return value may be implemented as necessary for each platform.

Oh! So the name of the fn is ambiguous. I had to read the comment in the header file to understand that this was explicitly for logs, the name of the function is not very clear. Then, it would not be too much of an issue to update the location of the Mac log to output to the proper location.

**Comment by ivan-mogilko** [comment]
Function may be renamed too.

**Comment by ericoporto** [comment]
> for any "service" files that engine has to write

Do you mean like the "room cache" idea? Does anyone knows if there's actually a log dir in any other platform? Is there actually a log dir in macOS - I can't find this in the documentation.

**Comment by edmundito** [comment]
I see logs in my `~/Library/Logs` folder. However, it's not always the case. Some apps do stick the logs in application support, sometimes in a `logs/` subfolder.

From our end, SDL provides us with only one directory which for macOS is `Application Support`: https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_filesystem.h

**Comment by ivan-mogilko** [comment]
I forgot to close this; problem was hotfixed by #2439

If changing log file location is desired, please open a separate ticket.
