### ISSUE TITLE
Help window stretches across multiple monitors if created with negative coordinates

### ISSUE THREAD

**Issue by cellproductions** [adventuregamestudio/ags#244]
The HTML Help API's HtmlHelp function forces the help window to stretch across multiple monitors if it opens at a negative location (-x, -y), which can be quite inconvenient.
E.g. if a user has two monitors (one set to the left of the main desktop monitor) and the help window is opened, it may be created on the monitor with the negative coordinates (e.g. -1920, 0) and set the size of the window to span across both monitors.

As I understand it, this is an issue within Windows' HTML Help API itself.

**Comment by ivan-mogilko** [comment]
@cellproductions , we have merged your related pull request (https://github.com/adventuregamestudio/ags/pull/243). Can you confirm this problem is fixed for you now?

**Comment by cellproductions** [comment]
Yep, it's fixed. Cheers.
