### ISSUE TITLE
"Adventure in the Galaxy of Fantabulous Wonderment" quits in SetDialogOption()

### ISSUE THREAD

**Issue by eriktorbjorn** [adventuregamestudio/ags#245]
Adventure in the Galaxy of Fantabulous Wonderment [1] crashes/quits fairly late in the game. I've placed a gzipped savegame at http://www.update.uu.se/~d91tan/agssave.017.gz

To reproduce the problem:

* * Click on Hole, the creature to the right.
* Select "Open communication."
* Select "Grimbace University."
* Select "Do you have a mathematics department?"
* Select "Do you have a symbology department?"

When he asks "Anything else?" the game immediately quits with the following message:

```
An error has occurred. Please contact the game author for support, as this is likely to be a scripting error and not a bug in AGS.
(ACI version 3.3.3.0)


Error: SetDialogOption: Invalid option number specified
AGS: ***** ENGINE HAS SHUTDOWN
```

I'm guessing that this probably *is* a scripting error rather than a bug in AGS and that, since it's a fairly old game, AGS used to be more forgiving about that sort of things. I don't know what your policy for this sort of things are, but it would be a shame if the game was broken because it works flawlessly up to that point.

[1] http://www.clawofcat.com/yahtzee/galaxyof.zip

**Comment by ivan-mogilko** [comment]
> AGS used to be more forgiving about that sort of things. I don't know what your policy for this sort of things are

The policy (at least for current development branch) is to implement backwards compatibility whenever possible. There were few case already when new versions of AGS appeared to be more restrictive; in such cases we do a game version check and let older games pass through.

There's also the general question, whether AGS should just quit on such minor script mistake, but its another topic.

**Comment by ivan-mogilko** [comment]
NOTE: game made using 2.62.772

**Comment by ivan-mogilko** [comment]
Made a patch: 82ef1b1d49a149456a79d28ecc81d8da6481987b

**Comment by eriktorbjorn** [comment]
Seems to work fine. Thanks!
