### ISSUE TITLE
Engine: Rendering graphical glitch

### ISSUE THREAD

**Issue by edmundito** [adventuregamestudio/ags#2456]
**Describe the bug**
While playing An English Haunting, I noticed a graphical glitch in one of the rooms—a black bar with a blue pixel. I notified the creator (Postmodern Adventures), and they couldn't see it. They reviewed the sprites used for the room, and nothing unusual was found. Note that animation is playing in this part of the room, so this area is part of an object that animates:

![image](https://github.com/adventuregamestudio/ags/assets/168664/3ae75e4e-1f4d-4b36-bfaa-b98bdcbba9b0)

I am running the game with an ATI (Now AMD?) Radeon 560; I wonder if that's the issue, as I've encountered some problems with this before.

**AGS Version**
3.6.0.54

**Game**
An English Haunting (I can provide a save game)

**To Reproduce**
Just stand in the room and watch.

**Expected behavior**

**Screenshots**
Game setup:
![image](https://github.com/adventuregamestudio/ags/assets/168664/88830454-d9dc-4062-9480-4c296c7df1bc)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by ivan-mogilko** [comment]
> An English Haunting (I can provide a save game)

Yes please, provide a save. I have asked developers for a game copy a while ago, but I haven't played it through.

**Comment by edmundito** [comment]
@ivan-mogilko Here's a saved game that puts you right in the cave:

[an-english-haunting_cave-glitch-save.zip](https://github.com/user-attachments/files/16015334/an-english-haunting_cave-glitch-save.zip)

**Comment by ivan-mogilko** [comment]
I'm afraid I don't see this glitch either.

I have a nvidia card, but idk if it's related.

**Comment by edmundito** [comment]
This is why I suspect it is video card-related. I don't know anyone with an ATI card yet, But I will ask around... In any case, hopefully, a minor bug then.

**Comment by ivan-mogilko** [comment]
Could you also tell, does this happen in any display mode or in particular one (fullscreen, exclusive fullscreen, windowed)?

**Comment by ericoporto** [comment]
> I just tried all modes and all rendered (d3d9, ogl, software) and it's still there.

If it happens in the software renderer I don't think it can be related to the video card.

I don't know if you are familiar with [RenderDoc](https://renderdoc.org/), but it can be used to inspect the textures by themselves, it works with the AGS OpenGL driver, you need to run the game from RenderDoc to be able to inspect it.

But anyway, if it happens in the Software Renderer my guess is it isn't that. If you can run the game on a build from the master and see if it reproduces the error it would be useful, also perhaps running it on your mac computer, and seeing if it reproduces there or not.

**Comment by ivan-mogilko** [comment]
Actually, yes, if it happens in software mode, then either this is actually a game bug, engine bug, or something else overlaying the game.

Does it happen in windowed mode?

**Comment by ivan-mogilko** [comment]
@edmundito can you clarify, do you see this glitch immediately after loading the save that you attached, or do you have to do something to make it appear?

Another thing, there are few test options in the engine. Try running the game with `--nospr` command, that will disable rendering of characters and objects. See if the glitch persists.

**Comment by ivan-mogilko** [comment]
After speaking with @edmundito on Discord, we compared couple of different builds of this game, and it turned out to be a glitch in the game itself.
