### ISSUE TITLE
Editor: having multiple project folders which names are different only in letter case breaks the item drag-n-drop

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2473]
**Describe the bug**
If there are 2+ folders in the project tree, which have names different only by letter case (e.g. "Test" and "test"), the Editor gets confused when dragging and dropping an item into one of them: the item will be dropped into the first folder of such name instead of a chosen one.

**AGS Version**
3.6.1 and eariler (seems like an old bug).

**To Reproduce**
1. Open a game project.
2. Open, for instance, Characters node.
3. Create two folders: "Test" and "test".
4. Drag existing character to the folder "test".
5. Notice Character appears in the upper folder "Test" instead.

**Expected behavior**
Dragged and dropped items should end up where user have dropped them.

On a side note, I noticed that folder names are not required to be unique on a given level. Perhaps that may be considered another issue.

**Comment by ericoporto** [comment]
> On a side note, I noticed that folder names are not required to be unique on a given level

I think they should be unique and should probably be case insensitive too.

**Comment by ericoporto** [comment]
I believe the right thing is

- do not let folders that differ only in case be created at the same level
- do not let folders that differ only in case from others at a level be dropped in such level

**Comment by ivan-mogilko** [comment]
I doubt that the folders should be case insensitive. Uniquely named - maybe, but no other item names are case-insensitive.

**Comment by ericoporto** [comment]
I thought that the items were case insensitive honestly, since things like views generate all caps names as macro.

**Comment by ivan-mogilko** [comment]
I found at least *why* this happens. The culprit is this function StartFromNode, which is called when repopulating project tree:
https://github.com/adventuregamestudio/ags/blob/2482502f69b124ea94d244b12a368b4df191c25c/Editor/AGS.Editor/GUI/ProjectTree.cs#L180-L186

Here it looks for anything resembling the node id, and returns an array, which may contain even subnodes. Then it selects the first found node in results. *By coincidence* the results are sorted alphabetically, so ones with capital letter will appear first.

This behavior is firstly quite unreliable, and secondly is even more buggy than I thought initially. Judging by tests, the dropped item is only *visually* attached to the wrong Tree Node. But in data it is still considered a child of the *correct* folder.

So, this mechanism is currently working badly, regardless of what we decide about folder names,

**Comment by ivan-mogilko** [comment]
> I thought that the items were case insensitive (in uniqueness) honestly, since things like views generate all caps names as macro. If you have a view named view1 and other VIEW1, then idnk what happens if that is the case.

That makes sense.
So I double checked this, and it appears inconsistent among types. If you look for uses of "IsScriptNameAlreadyUsed", some items have their names uppercased before passing there (Characters, Views), and others not.
