### ISSUE TITLE
Infamous Adventures' Space Quest II crashes in full-screen.

### ISSUE THREAD

**Issue by duganchen** [adventuregamestudio/ags#248]
Infamous Adventures' Space Quest II remake works great in window, but in full-screen it crashes when you skip or get past the intro. Here is the console output:

http://pastebin.com/iBTi2tBX

**Comment by ivan-mogilko** [comment]
I found and fixed a mistake in code just today; I think it may be the same problem as you experienced.
Please building engine with the recent commit 4cf5006 .

**Comment by duganchen** [comment]
Yep, that fixed it.
