### ISSUE TITLE
Typos in DistanceBetween routine cause wrong calculation

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2485]
**Describe the bug**
As reported here https://bugs.scummvm.org/ticket/15292 , the DistanceBetween routine uses the ^ operator in an attempt to calculate the power of 2, instead of doing a simple mulltiplication or using pow. Clearly the result of a copy-paste from stackexchange.

Note that I haven't done any additional tests so I don't know if fixing the issue may actually cause problems in games expecting the "broken" calculation.

**Comment by ericoporto** [comment]
https://github.com/adventuregamestudio/ags/blob/7d912dae10dd20a8cd8ab3e0676b1304dc925b21/Common/util/geometry.cpp#L46

Leaving a permalink to make it easier to find it.

**Comment by ivan-mogilko** [comment]
Thank you, pushed a fix
release-3.6.1 branch: 445dd910c97ee08a6acf3dc7f624fd63c81951b1
master branch: c5f8c5374024b71493d276a27daa38d1aac84a89

This function was only used when searching for a nearest room viewport to display a character speech over a character,
but so far there have been only couple of games made which made use of multiple viewports, so this was never noticed.

**Comment by tag2015** [comment]
Thank you for the quick fix 😃
