### ISSUE TITLE
Support rasterizing the Room viewport to a dynamic sprite

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2509]
**Describe the problem**
Sometimes one needs to screenshot the screen without layers like a GUI or the mouse cursor. An example is when creating a save with screenshot but the menu to save the game is open

**Suggested change**
If you could screenshot a viewport to a dynamic sprite and then pass a graphic to the save function to use instead of the screenshot it normally takes, you could just save the game without having to hide the GUI and cursor for a single frame.

This is only an idea, perhaps some other approach is to pass a list of flags to the screenshot function telling what to either exclude or include. 

**additional context**
See forum https://www.adventuregamestudio.co.uk/forums/beginners-technical-questions/how-to-customize-the-default-load-save/msg636665150/#msg636665150

**Comment by ericoporto** [comment]
Btw, if one could just pass a sprite to the save function, they could just pass a pre-made asset to the save function instead for that specific game area. In theory one could even pass the room background but I don't think it is accessible currently as a sprite directly - one needs to get it as a drawing surface and then draw it in another drawing surface of a dynamic sprite to be able to then get that sprite.

**Comment by ivan-mogilko** [comment]
> Btw, if one could just pass a sprite to the save function,

Hm, that's actually a very good idea, might be done on its own, regardless of the screenshot.

**Comment by ericoporto** [comment]
Ah things that sounds easy in my head and become hell to implement... 

I may try the second approach, and use a sprite slot and some static bitmap object that holds a copy of whatever it was in the slot and frees it after writing.

But not sure how do deal with existing behavior, maybe it's better to give a new function name like SaveGameSlotWithGraphic?

**Comment by ivan-mogilko** [comment]
So, apparently, there are following new features involved here:
1. Creating a screenshot with only selected layers (with DynamicSprite.CreateFromScreenShot);
2. Passing an arbitrary sprite to SaveGameSlot.
3. Telling how to make a automatic screenshot for the save (same settings are in p1).

I suppose that being able to pass any sprite to SaveGameSlot is a more suitable for individual function parameter than a screenshot layer selection, which is better set as a game option once (i.e. using SetGameOption).

Screenshot layers may be a combination of flags. For starters these could be only "cursor", "gui layer" and "room layer". More may be added later if there will be a need to filter specific sublayers (like make a screenshot of room background without objects), but these seem less useful (?).

In regards to implementation, graphic renderers already support tagging batches with a "layer" constant, and then filtering them out when redrawing last frame. Currently this is done for the purpose of fade-in and out effects, where mouse cursor should not be present.
As seen here, for example:
https://github.com/adventuregamestudio/ags/blob/203a76d1fe99d76b0b2bfb1156f135c3fe362328/Engine/ac/draw.cpp#L2806-L2807

**Comment by ivan-mogilko** [comment]
Opened #2526 as a draft with these proposed changes implemented.

**Comment by ivan-mogilko** [comment]
Probably resolved by #2526.

There's still a curious idea of copying a selected room viewport to a sprite or drawing surface, but I suppose that's a separate task for a completely separate use-case. Similarly, there could be a function to draw a GUI over a drawing surface, for instance.
