### ISSUE TITLE
New compiler: AccessStructAsPointer are failing

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2518]
CC @fernewelten 

In regards to the test failures that are noticed only recently. I suspect they may be failing after #2513, but not sure how we did not notice them in that pr. This could be a result of several recent changes.

Failing tests are:
* Bytecode1.AccessStructAsPointer02
* Bytecode1.AccessStructAsPointer03

@ericoporto changed the logging setting, and now we can see what exactly is failing in these tests. Here's from the CI logs:

```
[ RUN      ] Bytecode1.AccessStructAsPointer02
/Users/runner/work/ags/ags/Compiler/test2/cc_bytecode_test_1.cpp:717: Failure
Expected equality of these values:
  codesize
    Which is: 64
  scrip.code.size()
    Which is: 63
/Users/runner/work/ags/ags/Compiler/test2/cc_bytecode_test_lib.cpp:93: Failure
Expected equality of these values:
  should_be_val.c_str()
    Which is: "code[9] == 3"
  is_val.c_str()
    Which is: "code[9] == 48"
/Users/runner/work/ags/ags/Compiler/test2/cc_bytecode_test_lib.cpp:136: Failure
Expected equality of these values:
  should_be_val.c_str()
    Which is: "fixups[1] == 23"
  is_val.c_str()
    Which is: "fixups[1] == 22"
[  FAILED  ] Bytecode1.AccessStructAsPointer02 (0 ms)
```

```
[ RUN      ] Bytecode1.AccessStructAsPointer03
/Users/runner/work/ags/ags/Compiler/test2/cc_bytecode_test_1.cpp:786: Failure
Expected equality of these values:
  codesize
    Which is: 34
  scrip.code.size()
    Which is: 33
/Users/runner/work/ags/ags/Compiler/test2/cc_bytecode_test_lib.cpp:93: Failure
Expected equality of these values:
  should_be_val.c_str()
    Which is: "code[12] == 3"
  is_val.c_str()
    Which is: "code[12] == 48"
[  FAILED  ] Bytecode1.AccessStructAsPointer03 (0 ms)
```

For some reason I could not reproduce this in my working environment, which makes me think that these depend on certain settings: build setup, compilation flags, C++ compilers. etc.

**Comment by ericoporto** [comment]
In that PR these tests were not run in GitHub Actions at all yet. They were just ran in GitHub Actions later, after the other PR that added these tests to CMake builds too.

**Comment by ivan-mogilko** [comment]
Alright, I found out what is happening.

This indeed is related to SCOPT_NOAUTOPTRIMPORT flag. It is set to certain values in some of the tests, but not others.

But there's a apparent difference between running these tests as Compiler2.Lib.Test executable, built from MSVS, and how they are run when built with CMake by github actions:
When run as Compiler2.Lib.Test.exe this flag is assigned to a global variable, and naturally remains in memory unless unset.
When run in automatic tests, it *seems* like this flag is reset.

**Comment by ivan-mogilko** [comment]
Closed by #2519.

**Comment by fernewelten** [comment]
> I think it would be nice to avoid globals in general in the new compiler and leave those only for the native glue / c# interface.

Actually, the compiler proper does. But googletests use a version of `cc_compile`  in combination with `ccSetOption`, where `ccOption` sets some global/static variables. This seems to have been  a **bad** idea because these static variables seem to remain in effect from one test to another. So suddenly the order matters in which the tests are run. 

Okay, I see, the solution is to rewrite the tests to avoid `ccSetOption`. That's more or less a mechanical change. I'll make one PR out of that that changes all the affected tests in one fell swoop.

**Comment by ericoporto** [comment]
Actually the way it's done is still using ccSetOption. I don't know if something like this exists... Pseudocode below

```
Compiler c;
c.SetOption(opt);
auto err = c.Compile(script);
```
