### ISSUE TITLE
Editor: focusing Menu with Alt key is broken since the first open-source release

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2566]
This is probably one of those things that are rarely used, that's my explanation why it was never reported in all those years.

**Problem**
Pressing Alt key is supposed to set a keyboard input focus on the Main Menu strip.
Instead it seems to set a keyboard focus on "system menu" (the one which is also called by clicking on a window icon in top-left corner). Pressing up/down arrow keys will open it instead of main menu's first submenu.
OTOH if you have any pane undocked and in floating mode, then Alt sets focus to *that floating pane's* window menu instead.
I do not think any of that was intended.

**Steps to reproduce**
1. Open the AGS Editor
2. Press Alt. Notice the Main Menu changes the look by underlining the first letters in its options. But the first menu item is not selected.
3. Press up or down arrow keys on keyboard. Notice that system menu opened instead of the main menu's submenu.
4. Make sure some pane is open, e.g. even if a "Welcome" pane. Make that pane floating by dragging it by the tab.
5. Now press Alt and then up or down keys. Notice how a this floating pane's window menu opens.

**AGS Versions**
Any version past 3.2.1 (3.2.2 and onwards).
You can check v3.2.1 to see how it was supposed to work.

**Expected behavior**
Pressing Alt should set a keyboard focus to the Main Menu.

**Comment by ericoporto** [comment]
It appears it's just that the frmMain doesn't have it's MainMenuStrip property set. For some reason setting it through the Designer crashes my Visual Studio, but in `frmMain()`, just after `InitializeComponent()`, I added the following

```C#
MainMenuStrip = mainMenu;
```

It works.
