### ISSUE TITLE
Different signedness comparison warning in update.cpp

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2568]
**Describe the bug**
Sorry for the hassle, another warning is in 
https://github.com/adventuregamestudio/ags/blob/f8f47f233fbddf622d62850bb6d1fc08139c1b98/Engine/main/update.cpp#L95

 warning: comparison of integer expressions of different signedness: 'const AGS3::fixed' {aka 'const int'} and 'unsigned int' [-Wsign-compare]

Possible solutions:
- doing an AND before the comparison
`else if ((ypermove & 0xffffffff) == 0xffff0000)`
- using XOR
`else if (!(ypermove ^ 0xffff0000))`
- cast (not sure it's recommended)
`else if ((uint32_t) ypermove == 0xffff0000)`

**Comment by ivan-mogilko** [comment]
I am fairly certain there may be a lot of warnings in this code, is this causing actual mistakes?
Are particular warnings wanted to be fixed?

Perhaps it may be better to open a single issue which lists types of warnings to be checked for particular compiler?

**Comment by tag2015** [comment]
> I am fairly certain there may be a number of warnings in this code; are particular warnings wanted to be fixed?
> 
> Perhaps it may be better to open a single issue which lists types of warnings to be checked for particular compiler.

Using gcc, this is the only warning reported in this part of the code

**Comment by tag2015** [comment]
> Anyway, I used the first proposed fix, because similar AND operation is used everywhere else in the surrounding code: [9cf99a3](https://github.com/adventuregamestudio/ags/commit/9cf99a3583fcb05dd983d9ce06a513851e47dd57)

Thanks! Issue can be closed I think
