### ISSUE TITLE
Show AGS version in "Welcome to AGS!" screen

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2576]
**Describe the problem**
I am running multiple AGS Editors all the time and when it's open editing a game I can easily check the version in the About menu. But when I have multiple AGS Editors in the "Welcome to AGS!" screen, I have no way to figure the version I am in.

**Suggested change**
It would be nice to have the version of AGS somewhere in this screen. It could be anywhere. Here's an example

<img width="392" alt="image" src="https://github.com/user-attachments/assets/3ee8587d-9747-4bea-8eeb-55a5b82d7fbc">

**Comment by ericoporto** [comment]
Had a different idea of design, I pulled the same string from the splash

![image](https://github.com/user-attachments/assets/15515638-dccf-414e-8023-319819616f1f)

**Comment by ivan-mogilko** [comment]
Hmm, maybe have a full version string, but place it right below the "Adventure Game Studio" words, on the blue background?

**Comment by ericoporto** [comment]
Uhm, perhaps like this?

![image](https://github.com/user-attachments/assets/725177c4-1d24-4ac9-99b9-9ddf3d5205cf)
