### ISSUE TITLE
Blackwell legacy fails with Character.Animate error

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2594]
**Describe the bug**
If you ask Joey about his powers, AGS closes with a CharacterAnimate error:
Error: Character.Animate: invalid loop number 10 for view 17 (range is 0..7)

I suppose this is a problem with the game itself, but since it's quite well known maybe the
issue should be avoided or worked around 

**AGS Version**
3.6.1.29, 3.6.1.30, 3.6.2 latest beta

**Game**
The Blackwell Legacy / Blackwell 1

**To Reproduce**
1. Load save [agssave.zip](https://github.com/user-attachments/files/17927251/agssave.zip)
2. Click on Joey
3. Ask about his powers

**Additional context**
Bug originally reported on the ScummVM bugtracker https://bugs.scummvm.org/ticket/15523

**Comment by ivan-mogilko** [comment]
Here's the save made by original game exe (made with 3.6.0.50):
[blackwelllegacy-36050-agssave.zip](https://github.com/user-attachments/files/17929850/blackwelllegacy-36050-agssave.zip)
this is to ease comparisons between builds.

**Comment by ivan-mogilko** [comment]
I see what's going on. The view 17 is the "idle view", which is constantly on for Joe (it's a floating ghost moves up and down).

Animate command used to unlock from the idle view prior to running assertions, but after some of my changes, it does assertions earlier. Normally this should not be a problem, as users are required to call LockView to a view which contains animation. But they quite often neglect this, which may lead to random results.

This will be easy to fix, just move the "unlock from idle view" to an earlier step.

**Comment by ivan-mogilko** [comment]
Pushed a fix,
master branch: b63ae88ee064ca14dfd0a50cb5e7be6d40a391ad
release-3.6.1: 946fa71c9332cae98f31d8b7672a1fe7b76d46c5

**Comment by tag2015** [comment]
Thanks! Confirmed fixed
