### ISSUE TITLE
Add Length to Autocomplete

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2599]
Length read-only property is now supported for Dynamic Arrays by the AGS Script compiler in v.3.6.2. It needs to be added strictly to dynamic arrays in autocomplete.

When a Script Variable is added to the Autocomplete it contains information if it is or isn't array, but not if it's dynamic

https://github.com/adventuregamestudio/ags/blob/583ff7a0f485de3db8deae689eaee335af1edcdc/Editor/AGS.Editor/AutoComplete.cs#L615

During parsing this information is found and set in the Autocomplete state as DynamicArrayDefinition. It's just that such information isn't stored in the variable after.

The other issue is figuring where/who should add Length as a property to dynamic arrays. If it's in some AutoCompleteFixUps that runs over at the end, with Length hardcoded, it would relatively easier to add any new similar things that may appear. A description text may optionally be added too.

**Comment by ericoporto** [comment]
When you type something like

```
   arrayname.
```

The dot is when we want the autocomplete to trigger. It will run `ShowAutoCompleteIfAppropriate`, which calls `ShowStructMemberAutoComplete()` when it sees a dot, and then it goes to call the `ParsePreviousExpression`, all of this in the ScinttillaWrapper.

You can see in it a few parts like

https://github.com/adventuregamestudio/ags/blob/22f98876d50cff9d666fbd25398770c2bb870f11/Editor/AGS.Editor/Panes/ScintillaWrapper.cs#L1682

and 

https://github.com/adventuregamestudio/ags/blob/22f98876d50cff9d666fbd25398770c2bb870f11/Editor/AGS.Editor/Panes/ScintillaWrapper.cs#L1693

where it does retrieve a ScriptVar, but then it will try to find its type. The thing is, if it is an array, is when we want to somehow get Length as an autocomplete.

But the way this function works, is under the assumption it has to return a `ScriptStruct` and `ConstructScintillaAutocompleteList` can only take a list of `ScriptStruct` (because of extensions), so this would also have to be adjusted somehow. Either by injecting a fake `ScriptStruct` that has only `Length` or creating some proper early exit that has a smaller function dedicated to work with dynamic arrays.

**Comment by ericoporto** [comment]
OK, I tried partially the second approach, I shoved an additional out parameter in `ParsePreviousExpression` where I retrieve the script var and then if it's a dynamic array, I forcefully add Length to autocomplete

https://github.com/ericoporto/ags/commit/46af4e545df0cae8db6734ff4de173d3c1f64386

It works. The remaining issue is that mouse over the typed `.Length` property shows no tooltip with a description of what it is. Ideally it would be nice to know it is "a read only property that the size of the dynamic array", I know it is obvious but it is weird it doesn't show.

**Comment by ivan-mogilko** [comment]
I thought making fake struct with an attribute would be more convenient. I've changed compilers to do that recently, and the advantage of that is that this makes all aspects work consistently.

**Comment by ivan-mogilko** [comment]
I thought that adding a fake struct with an attribute would be better, if that could be done. I did a similar change to compilers recently, and the advantage is that it does not require a special handling in place; once the fake type member is generated, the compiler proceeds as normal.

I don't remember how calltips work in scintilla, but maybe that fake struct could also help with that.

**Comment by ericoporto** [comment]
The thing of the fake struct is it is not something you can have “prepared”, you need to inject it when appropriate similar to the way I ended up doing by returning the ScriptVariable, like at those points you would need to produce the specific fake struct and return it.

This fake struct is not available later for the calltip, the calltip has two paths, one for functions and other for variables. So for the length property we would have to make something that fits the variable path. I couldn’t come up with something that wasn’t disruptive there, but the variable has a struct owner, so the length variable could have the fake struct as owner in this place.

**Comment by ivan-mogilko** [comment]
> The thing of the fake struct is it is not something you can have “prepared”, you need to inject it when appropriate similar to the way I ended up doing by returning the ScriptVariable, like at those points you would need to produce the specific fake struct and return it.

My meaning was to inject" a fake struct at the time when the variable is found.
Like, you've added a `isDynamicArray` boolean to the variable definition. I wonder if it is possible to generate this struct & attribute data around the place when the variable is added, as opposed to "injecting" a list of members when autocomplete is shown.

I.e. there's a AddVariableDeclaration call. Suppose, you receive a result from this call, test if the variable is a "dynamic array", check if this array type is already added to "structs", if not then generate a fake "struct" and an attribute for it. Then, supposedly, this attribute will be automatically shown by autocomplete whenever user types a dot after such variable.
This is just an idea, I have not tried myself yet.

**Comment by ericoporto** [comment]
This was my first idea, but the problem is that the variable can be added from three different places:

- global context
- local context
- local context from the function parameters

And in each of these cases the list of structs is not directly accessible, as the struct is more like a type declaration, so they happen in a different context. To do that, I would need to either pass them as parameters around, or reprocess at a later state, iterating through all declarations and picking which ones are dynamic arrays, but they all feel like a lot more changes.

**Comment by ivan-mogilko** [comment]
Maybe it's a bigger work (not necessarily too big), but it feels like a more correct change which, if working, will cover all cases where editor accesses this variable.
