### ISSUE TITLE
Demo game does not compile

### ISSUE THREAD

**Issue by sonneveld** [adventuregamestudio/ags#260]
Using commit b9c2fac13b1a26e2143b7c6e75a299fee7997872 from develop-3.4.0 , the editor cannot rebuild the demo game.  Have tested with 3.3.4 and the compile error does not appear.

error:
GlobalScript.asc(690): Error (line 690): Undefined token 'ProcessClick' 

steps to reproduce:
1) rebuild AGS.Editor.Full.sln
2) Execute editor
3) Load demo game 
4) Build menu / Rebuild all files.

**Comment by sonneveld** [comment]
When I have time I'll attempt to find which changeset introduced the error.

**Comment by gurok** [comment]
While it's true that there's a compilation error, it's the result of an intentional change in the click handling model between 3.3.x and 3.4.0. ProcessClick was made a static member of Room (Room.ProcessClick). I don't have the specific commit, but it occurred around the time of this announcement: http://www.adventuregamestudio.co.uk/forums/index.php?topic=51290.msg636500494#msg636500494

Something should be done about the error, but I believe it's the demo game that should be corrected.

**Comment by sonneveld** [comment]
Ah that's good to know. I thought maybe it was a defect that wasn't picked up. 

Thank you for the link, I'm still catching up with all the changes done. Adding "Room." did fix the issue. I suspect it's time for people to make pull requests to https://github.com/sonneveld/ags-demo-quest :)

**Comment by ivan-mogilko** [comment]
I was thinking on updating Demo Game and templates (if that is required) right before the 3.4.0 release, to fix all the incompatibilities that would be know at that point.

**Comment by sonneveld** [comment]
Should we have a deprecation process before removing functions altogether?

**Comment by ivan-mogilko** [comment]
Well, there is a compiler switch that adds obsoleted function back. Is it what you mean?

**Comment by ivan-mogilko** [comment]
A note regarding Demo Game: we are considering to replace it with different open sourced game, because "Demo Game" is a very old and incomplete project, which become target of criticism recently.
It was mostly a case of tradition to keep it in Editor distributive.

**Comment by ivan-mogilko** [comment]
With the addition of Script Compatibility Level switch (which automatically enables obsolete functions when loading an old project) into 3.4.0 branch this may be a non-issue now. Need to retest.

**Comment by ivan-mogilko** [comment]
This was fixed by adding compatibility switch in 3.4.0, which is automatically set on project import.
