### ISSUE TITLE
Editor uses Magick.Net-Q8-AnyCPU, Ver. 7.10.0 – which has a high severity vulnerability

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#2613]
**Describe the bug**
My Visual Studio alerts me when compiling the Editor:
> Package 'Magick.NET-Q8-AnyCPU' 7.10.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-j7hp-h8jx-5ppr

This is probably not a good thing.

**AGS Version**
AGS 4, Commit dfc68e28

**Comment by ivan-mogilko** [comment]
master branch has the same library, 
Magick.NET 7.10.0 version has been used since db8224a8a9d178c2a234c98251791058067dc3b7 which is more than 6 years ago.
AnyCPU version specifically was set in 23689843df7bf5acb5cd6ebbc3df4faca04c2c6b, about a year ago.

**Comment by ericoporto** [comment]
Upgrading requires upgrading everything else - VS, C#, .NET, Windows.

**Comment by ivan-mogilko** [comment]
So, I did a small investigation in the NuGet Gallery here:
https://www.nuget.org/packages/Magick.NET-Q8-AnyCPU/

and according to their notes, the first version that does *not* have a vulnerability is [13.3.0](https://www.nuget.org/packages/Magick.NET-Q8-AnyCPU/13.3.0)

It's dependency is ".NET Standard 2.0", and apparently [Magick.NET.Core](https://www.nuget.org/packages/Magick.NET.Core/), which requires .NET 8.0 (if i'm not mistaken).
