### ISSUE TITLE
AGS 4: Type.GetByName is broken after declaring game objects as pointers in script

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#2616]
Type.GetByName kind of functions no longer work after #2453 

This issue applies only to AGS 4.0 version.

The reason is simple: when implementing GetByName I used SystemImports table, where each game object was registered as a raw pointer to itself, along with the corresponding Manager, being able to report its type.
After #2453 SystemImports stores not object pointers, but handles instead, and they use a dummy "staticobject" manager.
The function `ccGetScriptObjectAddress` no longer works:
https://github.com/adventuregamestudio/ags/blob/c21eecebf105b026a5928534b89a0009f133b4ef/Engine/script/script_runtime.cpp#L104-L114

Need to either fix it to work, or invent another way.

---

Also should add "GetByName" tests to the game tests here:
https://github.com/adventuregamestudio/ags-test-games

**Comment by ericoporto** [comment]
I think https://github.com/adventuregamestudio/ags/pull/2588 will be broken when merged in ags4 for similar reason.

**Comment by ivan-mogilko** [comment]
> I think #2588 will be broken when merged in ags4 for similar reason.

No, it won't because it returns a direct pointer stored in character array. I already mentioned that: it works same way as GetAtScreenXY.

GetByName worked differently: instead of returning an element of object array it retrieved a item stored in "symbol imports" table.
