### ISSUE TITLE
source code release tarballs

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#274]
would be nice to haver proper source release tarballs on the official website (similar how it's done for windows binary downloads). github downloads from tags are not nice for a number of reasons ( https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck ), and git checkouts even less so for usage in a source code linux distribution.

**Comment by sonneveld** [comment]
Of all those listed, I think the integrity, naming and archive layout arguments are good points. Not entirely sure about the others. I quite like the idea of having https everywhere.

I think we should probably have source release tarballs and sha1sums over https, maybe for 3.3.5?

**Comment by ivan-mogilko** [comment]
On AGS website a person nicknamed AGA is a first administrator, and Peder Johnsen, an owner of agsarchives, helps him sometimes. They are the people to discuss this with.

**Comment by rofl0r** [comment]
@ivan-mogilko whats your stance on this ?
could we at least attach manually created release tarballs to the release tags ?

**Comment by ivan-mogilko** [comment]
I made one for the latest release: https://github.com/adventuregamestudio/ags/releases/tag/v.3.3.4.2

Please tell if this is what you had in mind. At this moment I selected only directories that has any relevance to Linux port.
Although it still is uses HTTPS for download, so I guess it solves the issue only partially.

**Comment by tobihan** [comment]
If you want a tarball with the things relevant for the Linux build you
can just run

debian/rules get-orig-source

That creates a tarball in .. (the directory above). That's the one that
is used when a Debian package is built.

**Comment by ivan-mogilko** [comment]
Well, I guess I will learn Linux by small steps like these.

Here's the bash script I wrote based on your debian rules:

<pre>
#!/bin/bash

cd $1
echo Source directory: $1
VERSION=$2
echo Source revision: $VERSION
ORIG_CONTENT="$(git ls-tree --name-only $VERSION | grep -Ev '^(Android|Editor|Compiler|iOS|OSX|PSP|Solutions|Windows|debian|\.git.*)')"
echo Files: $ORIG_CONTENT
echo Running git archive...
git archive --prefix=ags_linux_$VERSION/ --format=tar $VERSION $ORIG_CONTENT | xz > ../ags_linux_$VERSION.tar.xz
echo Done
cd ..
</pre>

**Comment by rofl0r** [comment]
@ivan-mogilko that's fantastic, thanks. works well and it may be that now sabotage linux is the first linux distribution with an ags package included... https://github.com/sabotage-linux/sabotage/commit/2bf6502eb6bbbd358b45ec52c848709614b5fad4
would be nice if you could keep doing that for upcoming release.

**Comment by ivan-mogilko** [comment]
I will do this manually for now, but later I will see if it is possible to utilize the build server @sonneveld set for AGS project and automate the process.
(http://ec2-54-66-209-118.ap-southeast-2.compute.amazonaws.com:8111/project.html?projectId=AdventureGameStudio)

**Comment by ivan-mogilko** [comment]
Added tarball for the new release: https://github.com/adventuregamestudio/ags/releases/tag/v.3.3.5.4

**Comment by rofl0r** [comment]
thanks! updated.
