### ISSUE TITLE
bug/question: many games ship with a windows installer...

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#276]
(for example http://www.adventuregamestudio.co.uk/site/games/game/401/ )
which precludes usage with the multiplatform ags engine on non-windows platforms.
are there plans to offer a (or already existing) mirror project that only ships the game executable/files without the windows installer ?

**Comment by ivan-mogilko** [comment]
I think I should've closed this, as we are developing the engine/editor, but the website or games hosting is outside of this project's responsibility.
