### ISSUE TITLE
idea: add engine version prerequisites info to ags download site

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#277]
it would be useful if the download site on ags...co.uk displayed the engine version number that's required and if the game uses DLL plugins that are not supported in the opensource version.

**Comment by ivan-mogilko** [comment]
I am afraid we (contributors/maintainers) do not have a control over that website; it is the site admins that need to be talked about this.

**Comment by ivan-mogilko** [comment]
Same as with #277, I think it would be possible to suggest this to Peder Johnsenn, the owner of AGS Archives (https://www.agsarchives.com/). He is planning on uploading every AGS game he may find there, and also provide additional features. I believe he may add separate download with raw game data too.

**Comment by ivan-mogilko** [comment]
So, I am not sure if this ticket should remain here, because this does not look like this project members responsibility (same as #277).

I'd rather close them both, but idea itself makes sense. Perhaps this could be posted on forums instead, try to bring attention of someone who might be interested?

**Comment by rofl0r** [comment]
> this could be posted on forums instead

yep, but i can't do it since new registrations aren't accepted.
also, if i was you, i'd try to convince someone of the website admin to give you or someone else from the team at least r/w access.

**Comment by ivan-mogilko** [comment]
> yep, but i can't do it since new registrations aren't accepted.

I heard they did several fixes recently, maybe you could try again?

> also, if i was you, i'd try to convince someone of the website admin to give you or someone else from the team at least r/w access.

well, I actually have r/w access to their file server for uploading releases, and also limited mod rights because I maintain "release" threads on forums, but working with game database is not something I am ready to do...

**Comment by ivan-mogilko** [comment]
I heard there's a new site/database redesign, so might pass this suggestion to them. Plus there are definitely lots of new members on forums leately, so it should be possible to get there and discuss this on forums.
I'll close the ticket as it does nothing good hanging here.
