### ISSUE TITLE
Using one config file for many games

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#287]
This was requested by user in the [comment to another issue](https://github.com/adventuregamestudio/ags/issues/104#issuecomment-41592817):

@JPRuehmann

> Hello
> Me to I thing at least the possibility of an central config  such as an ~/.acsetup or /etc/acsetup file would be great.
> I´ve got fifty or so AGS games and all of them should run with the same Configuration.
> Thanks,
> JPR

Judging by the comments in code, AGS should actually first try to find a config in the "current directory". Need to check how that actually works (because it may change current directory to game dir early).
OTOH, it is perhaps viable to pass path to config as a new command line argument.

**Comment by rofl0r** [comment]
how about a global/user-specific "override config":
engine first reads config from game dir, then overrides its values with the users one
so user can set for example all games to fullscreen, but leave the default resolution to the game's config.

**Comment by ivan-mogilko** [comment]
*bump*

With the configuration map implemented in the recent releases, this should be easier to do. In fact we already potentially read two config files (at least on Windows), where one in the game-related "user's directory" overrides one in the installation directory.

Adding one extra source in all-games shared path that overrides map again should not be a problem. Only problem is to decide where this should be located (on every supported system).

**Comment by ivan-mogilko** [comment]
This may also be a chance to decide whether Linux needs a separate path for a game-specific config.

Since AGS 3.3.5 there are couple of config options that may be altered during the game, and engine writes them back into config file.
On Windows there was an issue that game may be installed into "C:/Program Files", and program is not allowed to write back there unless it is run with administrator's privileges.
This is why AGS now reads config from the game installation directory first, and then overrides it with config read from users directory (and saves config into latter when quitting the game).

No one has reported similar issue on Linux yet (probably everyone is putting games into user's home dir?), but in may that be a theoretical possibility?

**Comment by rofl0r** [comment]
how about this:
game first reads config from game dir, then overwrites it with values from $HOME/ags/gamename/config, and finally with values from $HOME/ags/global.conf
for saving, game always tries to save into $HOME/ags/gamename/config.

**Comment by ivan-mogilko** [comment]
I opened pull request: #378, but I am suggesting different order for global and game config: "$HOME/ags/global" first and "$HOME/ags/gamename/config" second, because otherwise global config may override options that were written by game itself (which could be chosen by player from some game menu).

**Comment by JPRuehmann** [comment]
That is exactly what is intended by that.

**Comment by ivan-mogilko** [comment]
Forgot to close this in time.
Was implemented with #378.
