### ISSUE TITLE
Is it time to do a legacy branch only for "classic" AGS games?

### ISSUE THREAD

**Issue by timofonic** [adventuregamestudio/ags#290]
Hello.

I see backwards impossibility is usually a problem. Is it time to make a really maintained legacy version for those older games and clean the new branch?

Kind regards.

**Comment by sonneveld** [comment]
I believe that's what ScummVM is trying to do with their AGS branch

**Comment by ivan-mogilko** [comment]
Well, I guess we may have to do this eventually; some breaking changes are needed anyway.

**Comment by ivan-mogilko** [comment]
To elaborate, first JJS and me were adding all kinds of conditional branches in code to support very old games, but these add code bloat, and usually make it more difficult from updating engine, because you have to keep various backwards compatible hacks in mind.

**Comment by rofl0r** [comment]
my stripped ags binary is 2.3 MB, which is not that much.
it would be much more bloated if i'd need to keep around separate binaries for every ags engine version :/

**Comment by timofonic** [comment]
About ScummVM:

I'm not sure, but I think the main author (fuzzie) is quite busy and the
progress got stagnated. For verified information, you should contact the
ScummVM Team.

Are there actual interest in it in both the AGS and ScummVM projects? Any
possible contributors to make it happen?

I'm still just a gamer. To me, it would be very positible to be able to
play these legacy games on a common GUI/framework that is very portable. I
have no idea about the technical details and the complexity to make it
happen, of course.

**Comment by ivan-mogilko** [comment]
> Are there actual interest in it in both the AGS and ScummVM projects? Any
possible contributors to make it happen?

To make *what* happen?

**Comment by i30817** [comment]
People who want this probably don't compile ags themselves and are used to 'only' using scummvm so want to stuff everything there (probably for their gui). I for one am satisfied about ags, command line invoking and all.

**Comment by ivan-mogilko** [comment]
Please, let not bring all kinds of problems into one issue.

The original post was about splitting branches. Last comments are about ScummVM and launching games from GUI framework.

@timofonic , could you elaborate on the reasons you opened this issue? What confuses me most is that you position yourself as "just a gamer", but your suggestion is a technical one, and has importance mainly from developer's perspective.

**Comment by ivan-mogilko** [comment]
Well, @timofonic did not answer, and the discussion derailed, leaning towards collaborating with ScummVM team and launching games from GUI framework.

The original question does make sense, of course, but we do not have plans to overhaul engine beyond the point where supporting old games would become impossible. Even with bigger changes it is capable to emulate old behavior.

In fact, the most restricting part of AGS is the engine's plugin interface, but ports cannot use original plugins anyway, and most of old plugin sources are lost, so they have to be recreated to be able to run those games; and newer games use these old plugins quite rarely. That's why we shall most probably remake plugin interface from scratch.

I am inclined to close this issue now.

**Comment by timofonic** [comment]
@ivan-mogilko

Hello.

I'm so sorry, I didn't read this before. I agree, I didn't explain my ideas and derailed the conversation. 

Now with a ScummVM fork adding AGS support: Can I write an "issue" related to this? The ScummVM fork mostly done by @morganwillcock (that features the "ags" branch) lacks an issue tracker, unfortunately.

Best regards.

**Comment by ivan-mogilko** [comment]
> Current list of eligible (but not definitive, I think) tasks is available here. The ScummVM fork mostly done by @morganwillcock (that features the "ags" branch) lacks an issue tracker, unfortunately. Where should I put it?

Looks like I forgot to enable issue tracker there. I added one now.

We've already a word with ScummVM team. here: http://forums.scummvm.org/viewtopic.php?t=14463

> What's the status of having older source code available? Can someone politely contact Chris Jones (the original developer, right) about this? Maybe he has older backups somewhere or even used a VCS to develop.

I can try mailing him, or asking around his old friends on AGS forums, but I haven't heard from him in years, so cannot guarantee anything.

**Comment by morganwillcock** [comment]
> The ScummVM fork mostly done by @morganwillcock

Just to clarify, the work was mostly done before I started looking at it.

In terms of tracking issues, the majority of non-functional bits are marked as such in the code. Because a lot of the scripting functions are not implemented, loading in an actual game will usually result in the game not being playable. At the moment I'm just testing the scripting functions independently, so any issues at a higher level (e.g. Game X gets stuck on the title screen) would likely be invalidated by future changes and have to be re-tested anyway.

**Comment by ivan-mogilko** [comment]
>> The ScummVM fork mostly done by @morganwillcock

> Just to clarify, the work was mostly done before I started looking at it.

Yes, just in case anyone is wondering, we just forked the WIP work by @fuzzie that was frozen somewhere in 2013.

**Comment by rofl0r** [comment]
i did some work on that branch, and i tried to get "Duty and Beyond" working.
it actually worked very good already. there's an issue with pathfinding in the medieval level (screenshot of scummvm here  https://github.com/adventuregamestudio/ags/pull/160#issuecomment-47511917 ) and the one were you can drive around with a submarine (mentioned here #163).
i think a good approach would be to start backporting the fixes that have been made to the pathfinding algorithm in this repo here.
there are also some math functions missing (this is really low-hanging fruit), one basically just needs to write a wrapper for libc functions. if you look for commits authored by me, you should find several of them which could serve as an example.
one of the major points that's missing, is that one cannot save and restore a game. this requires "serializing" the game state, which imo is a rather hard task and require some in-depth knowledge.

another task that needs to be done and that was demanded in the scummvm forum thread, is rebasing all of the AGS related commits into a new branch based on current scummvm master. this requires good knowledge of git (stuff like `git am` and `git commit --author="foo <foo@bar.com>"`), and tools like diff and patch (i usually do stuff like this by exporting commits as patches, then try to `git am` then, if there are merge conflicts i undo `git am --abort` and remove the hunks that failed to merge, then apply them by hand to the source, etc)

**Comment by ivan-mogilko** [comment]
@rofl0r 
>  there's an issue with pathfinding in the medieval level (screenshot of scummvm here #160 (comment) )

As I noted in the referred thread, I think that particular case was not issue with pathfinding, but something different. The two walkable areas were not connected there, which means that character moves between them only by explicit command that ignores walkable areas.

Anyway, now when issue tracker is working in https://github.com/adventuregamestudio/scummvm, I suggest posting known issues there.

**Comment by rofl0r** [comment]
all right, i was just trying to raise some points you or @morganwillcock may want to look into to get started.
