### ISSUE TITLE
Incorrect parsing of INT_MIN value in script

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#295]
In develop-3.3.5 branch we had fixes related to parsing large integer values, however script compiler still cannot parse INT_MIN value (-2147483648) properly.

Example of script:
<pre>
int a = -2147483648;
</pre>

Instead it reports following error:

<pre>
Error while parsing integer symbol '2147483648'.
</pre>

Notice: it also does not include sign when reporting a symbol it cannot parse.

Values higher than INT_MIN are parsed properly. For example following script produces correct expected result:
<pre>
int a = -2147483647;
a--;
Display("a = %d", a); // this displays "a = -2147483648"
</pre>

**Comment by sonneveld** [comment]
That is weird.. must be an edge case that unit test isn't picking up

**Comment by ivan-mogilko** [comment]
I finally had a time to look into this; I do not know how compiler works in detail, but apparently when it constructs a list of symbols, it looses negative sign from literal integer constants.

For instance, when sym.get_name() returns literal "name" (value) of the constant, it is already positive. This happens with *any* negative constant.

**Comment by ivan-mogilko** [comment]
Okay, basically is_part_of_symbol() function fails to recognize following digits as a part of '-', and causes tokenizer to treat '-' and number separately.

**Comment by sonneveld** [comment]
I haven't got a chance to look at it until around Jan 5 but a failing unit
test would be a good start I think

**Comment by ivan-mogilko** [comment]
Another thing I noticed, there are two functions which do similar thing:
* accept_literal_value()
* accept_literal_or_constant_value()

The first function is completely duplicated in the second function, but the latter supports handling of negative values.

**Comment by ivan-mogilko** [comment]
Resolved by https://github.com/adventuregamestudio/ags/pull/311
