### ISSUE TITLE
[BUG] duty and beyond misbehaviour

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#31]
when entering room 49 (3rd level), in the .exe version shipped with duty and beyond, a pig appears - that one is missing in both scummvm and AGS version hosted here.

**Comment by ivan-mogilko** [comment]
Hmm, alright, this was here way too long :).

It was not clear whether this was a bug in the first place. And there were numerous compatibility fixes made to the engine in the past years. I'd like to close this now. If the bug is found with the latest release please open a new issue.
