### ISSUE TITLE
"Duplicated" mouse cursor movement in fullscreen, Linux under VMWare only

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#313]
I somehow made an oversight and did not test the develop-3.3.5 branch in fullscreen mode on Linux before.
This branch contains rewritten mouse routine, that applies custom speed setting to the cursor movement. When doing so, it repositions the system cursor. (This is only done when running in fullscreen mode).

Related pull request (merged): https://github.com/adventuregamestudio/ags/pull/291

Anyway, I was trying out the patch that was supposed to reduce mouse lag (https://github.com/adventuregamestudio/ags/issues/162) when I observed a weird, but clearly noticeable issue; I will note in advance, that the lag-reducing patch did not affect the issue at all (it was present with and without patch likewise).
The issue can be described as following:

_When I move the mouse to direction A for some time, then stop, and start moving it to direction B, the mouse continues moving to direction A for some more time, before changing to B.
The mouse moves only when I move the mouse (!), it does not move when I stop. But when I start moving mouse again, the cursor "continues" moving into previous direction before changing to new one._

I have little knowledge about how XWindows work, but I would intuitively say that it looks like the event queue is being filled with duplicated "mouse move" notifications, which are only processed when mouse actually moved by user. Again, this is just a guess, based on observation.

I made a quick search, and [found following information](http://linux.die.net/man/3/xwarppointer) about XWarpPointer function, that Allegro uses to reposition cursor:

> If you do use this function, however, it generates events just as if the user had instantaneously moved the pointer from one position to another.

So, I thought that maybe by "correcting" cursor position I cause extra "delta" events that loop back to Allegro, and AGS (presuming Allegro does not know that it should ignore these)? I made an experiment by removing calls to position_mouse completely, and only reading mouse moves. To my surprise, it did not fix anything.
After more experimentation, I found out that this effect is being caused by calling _get_mouse_mickeys_ function as well (in fact, it is caused by calling **either** _get_mouse_mickeys_ or _position_mouse_). Not only that, but even simply calling that function without actually using returned values (and calculating mouse movement by difference between old and new cursor position) already cause same issue.

This is where I got dumbfounded, because get_mouse_mickeys is a function that should supposedly only return you some values. By examining Allegro's implementation for XWindows, I noticed that it actually not only returns values, but also sets some internal flag (call to __xwin_set_warped_mouse_mode_).

I realize the continuation will require making a larger research, so I need to clarify first: can someone reproduce this problem on their system? I am running Linux on virtual machine, so that may have some effects too.
Secondly, may this has any relevance to the previously reported "lag" issue (https://github.com/adventuregamestudio/ags/issues/162)? I must underline, that applying the patch for AGS did not make any noticeable change for me.

**Comment by ivan-mogilko** [comment]
According to recent @morganwillcock 's tests this behavior only found when running Linux on VMWare Player.

**Comment by ivan-mogilko** [comment]
Need to retest in AGS 3.6.0 (sdl2 based version).

Also I might check this in a different virtual machine player (like Oracle's VirtualBox).

**Comment by ivan-mogilko** [comment]
Not a problem with 3.6.0 and VirtualBox (which seemed to generally behave better than VMWare in my experience, but then again maybe this was improved in vmware since).
