### ISSUE TITLE
Engine build documentation for Debian is missing two required packages

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#318]
Required packages to build the engine on Debian are currently listed as:
- git
- debhelper
- build-essential
- pkg-config
- libaldmb1-dev
- libfreetype6-dev
- libtheora-dev
- libvorbis-dev
- libogg-dev

I believe that these two are also required:
- libsm-dev
- libice-dev

**Comment by ivan-mogilko** [comment]
Yes I can confirm that after upgrading to Ubuntu 14.04 AGS requires these two extra libraries to build.

**Comment by ivan-mogilko** [comment]
Both seem to relate to x11 library (at least on Debian/Ubuntu systems), which AGS is statically linking since latest 3.3.5 release.

This makes me think that I might have made a mistake adding static x11 linking to AGS itself. Allegro already links x11. We could probably use the "weak" references, similar to the [mouse patch example](https://github.com/adventuregamestudio/ags/commit/df953ff183ee5ecc456880c5ba2c5659dcd26641), or even dynamic linking if the latter won't work for any reason?

**Comment by rofl0r** [comment]
yes; dynamic linking should definitely be preferred, in the worst case it's harmful to have two sets of the functions in the address space, in the best case it just wastes ram since the functions are already mapped.

**Comment by morganwillcock** [comment]
Does it depend on how you are delivering the executable? I think SteamOS runtime is still a collection of Ubuntu 12.04 libraries; If you sign-up as a developer do you have to agree to building against or using those libraries?

**Comment by ivan-mogilko** [comment]
Alright, I found where those two extra libraries come from.

This commit: d644bbbe54f1bef74ebc09299ac4b6ec3d830ad0 changed the way allegro library list is defined from
> shell allegro-config --libs
to
> pkg-config --libs --static allegro

On Ubuntu 14 the resulting string from the first gives:
> -L/usr/lib/x86_64-linux-gnu -lalleg
and the second:
> -lalleg -lm -lpthread -lrt -lSM -lICE -lX11 -lXext -lXcursor -lXpm -lXxf86vm -ldl
(notice -lSM and -lICE)

**Comment by tobihan** [comment]
If the packages libsm-dev and libice-dev are required now, please add them to the Debian package list in debian/README.md (sudo apt-get install ...) and the Build-Depends field in debian/control.

The latter will also fix building with make_ags+libraries.sh, because this field is how the libraries to be installed are determined.

**Comment by tobihan** [comment]
So why did you add static linking to x11? The other libraries are also dynamically linked and I think the libX11 ABI should be pretty stable, no?

**Comment by ivan-mogilko** [comment]
> So why did you add static linking to x11? The other libraries are also dynamically linked and I think the libX11 ABI should be pretty stable, no?

The honest answer is that I do not have much experience with Linux, and make mistakes.

**Comment by tobihan** [comment]
I just asked because was also not totally sure what to suggest. If there was no reason, I would change to linking X11 dynamically.

And why the --static in the pkg-config command?

**Comment by ivan-mogilko** [comment]
You are right, I realized I was not clear enough about the situation.
All this started with this small addition: 3c8c913a8b53fcb84e0f637740ae26236f8dc835
This alone resulted with "undefined reference to XGrabPointer.

> And why the --static in the pkg-config command?
The script changes for commit d644bbb were given to me by @sonneveld .

**Comment by ivan-mogilko** [comment]
Can it be that me mentioning the x11 static linking is in fact a stupid misunderstanding?

I've been reading on gcc linking options, and it seems to me that the way LIBS string is constructed in in the latest makefile does not assume static linking.

**Comment by tobihan** [comment]
Yes, I think you just have to remove the --static flag from the pkg-config allegro command. If then something is missing, manually link to that.

**Comment by ivan-mogilko** [comment]
Well, I have to apologize for making everyone here misleaded.

After changing to "pkg-config --libs allegro" I had to add:
* -ldl
* -lpthread
* -lX11

I have a question though. Some of the libraries are added just directly (-lxxx), others are added using pk-config now. Would it be preferred to use pk-config where possible (i.e. "pk-config --libs x11")?

**Comment by tobihan** [comment]
Where pkg-config files are available it's good to use them. However it's normally more important for the --cflags flag, to get the include directories for a library.

**Comment by ivan-mogilko** [comment]
I created pull request: #326.

**Comment by ivan-mogilko** [comment]
I get it that this issue is solved, because AGS won't require SM and ICE packages now.
