### ISSUE TITLE
Room change debug messages printed to stdout

### ISSUE THREAD

**Issue by salty-horse** [adventuregamestudio/ags#319]
The following messages in `Engine/ac/room.cpp` are printed using `Out::FPrint`. They seem relevant for development, and are of no interest to people using the engine to play games.

They should probably be printed with `DEBUG_CONSOLE`.
```cpp
Out::FPrint("Unloading room %d", displayed_room);
Out::FPrint("Loading room %d", newnum);
Out::FPrint("Room change requested to room %d", newnum);
```

Sorry for not submitting this as a pull request. I'm not sure which branch to target.

**Comment by ivan-mogilko** [comment]
We need a switch to toggle logging to stdout similar to how the log file creation is toggled.

**Comment by ivan-mogilko** [comment]
Sorry, I mean, not just the general on/off switch, but verbosity switch.

**Comment by ivan-mogilko** [comment]
On the other thought we may change it to DEBUG_CONSOLE for now, since implementing proper switch will require more work than worth for this case.

**Comment by ivan-mogilko** [comment]
Done with e34921b.
