### ISSUE TITLE
3.3.5.5 Needs '-lm'

### ISSUE THREAD

**Issue by ainola** [adventuregamestudio/ags#327]
The Archlinux pkgbuild requires this line to build properly since the 3.3.5.5 update that replaced the older 3.3.5.5:

`sed -i 's/-ldumb/-ldumb -lm/' Engine/Makefile-defs.linux`

Otherwise I was getting The following errors:

/usr/bin/ld: ac/math.o: undefined reference to symbol
Unable to build: DSO missing from command line

**Comment by ivan-mogilko** [comment]
Sorry, I added it back now: f031ce4793f651329c2bb02b75ea0345182a498d

I am referring to the previous makefile we had before release 3.3.5, and I think all the libs mentioned there are now back.

**Comment by ainola** [comment]
Yay, this fixes it! Thanks so much for maintaining!

**Comment by ivan-mogilko** [comment]
I would be very glad if someone helped me to understand why it worked on my test system (e.g. Ubuntu) before.

**Comment by ainola** [comment]
I believe this is due to glibc 2.22. As Debian/Ubuntu trails behind a release or two, this bug was probably just discovered sooner rather than later. :)

From 2.22's release notes (http://abi-laboratory.pro/tracker/changelog/glibc/2.22/log.html)

> The math code has been replaced with a math library based on fdlibm from
> Sun, and modified by JT Conklin and Ulrich Drepper with i387 support, by
> Ian Taylor with `float' functions and by Ulrich Drepper with `long double'
> functions.  The math functions now reside in a separate library,  so
> programs using them will need to use `-lm' their linking commands.

**Comment by ivan-mogilko** [comment]
Oh, I think I found another reason myself. Since we are now using "pkg-config", the "pkg-config --libs" returns a string that contain -lm for some of other libraries.
For example "pkg-config --libs vorbis" return
> -lvorbis -lm -logg
on my system.

**Comment by rofl0r** [comment]
@ainola: the text you cite is from the entry for GLIBC 2.0, not GLIBC 2.22

**Comment by ainola** [comment]
A similar problem occured with Csound when glibc 2.22 came out (see https://github.com/csound/csound/issues/526).

pkg-config --libs vorbis returns only -lvorbis for me.
