### ISSUE TITLE
Barn Runner 1 Eclair 1: pure virtual method called

### ISSUE THREAD

**Issue by tobihan** [adventuregamestudio/ags#34]
At the start of the opening movie, I get this error. Using the master branch This does not happen with the main branch.

AGS: Loading room 20
pure virtual method called
terminate called without an active exception
**\* glibc detected **\* ags: double free or corruption (!prev): 0x00007f2a81049a30 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x75b76)[0x7f2a7e709b76]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x6c)[0x7f2a7e70e8ac]
/usr/lib/x86_64-linux-gnu/liballeg.so.4.4(destroy_sample+0x1c)[0x7f2a800a9a3c]
/usr/lib/x86_64-linux-gnu/liballeg.so.4.4(+0x424d4)[0x7f2a800644d4]
/usr/lib/x86_64-linux-gnu/liballeg.so.4.4(remove_sound+0x7e)[0x7f2a800aa12e]
/usr/lib/x86_64-linux-gnu/liballeg.so.4.4(allegro_exit+0x1d)[0x7f2a8004b7ed]
/usr/lib/x86_64-linux-gnu/liballeg.so.4.4(+0xbb137)[0x7f2a800dd137]
/lib/x86_64-linux-gnu/libc.so.6(+0x324f0)[0x7f2a7e6c64f0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x35)[0x7f2a7e6c6475]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x180)[0x7f2a7e6c96f0]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x11d)[0x7f2a7e3f289d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x63996)[0x7f2a7e3f0996]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x639c3)[0x7f2a7e3f09c3]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x644df)[0x7f2a7e3f14df]
ags(_Z17update_mp3_threadv+0x5c)[0x7f2a8065c6dc]
ags(_ZN3AGS6Engine13PThreadThread13_thread_startEPv+0x12)[0x7f2a80667ea2]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x6b50)[0x7f2a7eca3b50]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f2a7e76c70d]
======= Memory map: ========
7f2a675e6000-7f2a6b5e7000 rw-s 00000000 00:11 56660                      /run/shm/pulse-shm-3418340510
7f2a6b5e7000-7f2a6f5e8000 rw-s 00000000 00:11 56655                      /run/shm/pulse-shm-594289429
7f2a6f5e8000-7f2a6f5e9000 ---p 00000000 00:00 0 
7f2a6f5e9000-7f2a6fde9000 rw-p 00000000 00:00 0 
7f2a72bc3000-7f2a72bc4000 ---p 00000000 00:00 0 
7f2a72bc4000-7f2a733c4000 rw-p 00000000 00:00 0 
7f2a733c4000-7f2a733c5000 ---p 00000000 00:00 0 
7f2a733c5000-7f2a73bc5000 rw-p 00000000 00:00 0 
7f2a73bc5000-7f2a73bca000 r-xp 00000000 fe:01 1316717                    /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
7f2a73bca000-7f2a73dc9000 ---p 00005000 fe:01 1316717                    /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
7f2a73dc9000-7f2a73dca000 r--p 00004000 fe:01 1316717                    /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
7f2a73dca000-7f2a73dcb000 rw-p 00005000 fe:01 1316717                    /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
7f2a73dcb000-7f2a73dea000 r--p 00000000 fe:01 1186081                    /usr/share/locale/de/LC_MESSAGES/libc.mo
7f2a73dea000-7f2a73dfd000 r-xp 00000000 fe:01 3670021                    /lib/x86_64-linux-gnu/libresolv-2.13.so
7f2a73dfd000-7f2a73ffc000 ---p 00013000 fe:01 3670021                    /lib/x86_64-linux-gnu/libresolv-2.13.so
7f2a73ffc000-7f2a73ffd000 r--p 00012000 fe:01 3670021                    /lib/x86_64-linux-gnu/libresolv-2.13.so
7f2a73ffd000-7f2a73ffe000 rw-p 00013000 fe:01 3670021                    /lib/x86_64-linux-gnu/libresolv-2.13.so
7f2a73ffe000-7f2a74000000 rw-p 00000000 00:00 0 
7f2a74000000-7f2a74033000 rw-p 00000000 00:00 0 
7f2a74033000-7f2a78000000 ---p 00000000 00:00 0 
7f2a78036000-7f2a78037000 rw-p 00000000 00:00 0 
7f2a7819f000-7f2a78452000 r-xp 00000000 fe:01 1190525                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.8
7f2a78452000-7f2a78651000 ---p 002b3000 fe:01 1190525                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.8
7f2a78651000-7f2a7866d000 r--p 002b2000 fe:01 1190525                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.8
7f2a7866d000-7f2a7866e000 rw-p 002ce000 fe:01 1190525                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.8
7f2a7866e000-7f2a786b9000 r-xp 00000000 fe:01 1190523                    /usr/lib/x86_64-linux-gnu/libFLAC.so.8.2.0
7f2a786b9000-7f2a788b8000 ---p 0004b000 fe:01 1190523                    /usr/lib/x86_64-linux-gnu/libFLAC.so.8.2.0
7f2a788b8000-7f2a788b9000 r--p 0004a000 fe:01 1190523                    /usr/lib/x86_64-linux-gnu/libFLAC.so.8.2.0
7f2a788b9000-7f2a788ba000 rw-p 0004b000 fe:01 1190523                    /usr/lib/x86_64-linux-gnu/libFLAC.so.8.2.0
7f2a788ba000-7f2a788cf000 r-xp 00000000 fe:01 3670030                    /lib/x86_64-linux-gnu/libnsl-2.13.so
7f2a788cf000-7f2a78ace000 ---p 00015000 fe:01 3670030                    /lib/x86_64-linux-gnu/libnsl-2.13.so
7f2a78ace000-7f2a78acf000 r--p 00014000 fe:01 3670030                    /lib/x86_64-linux-gnu/libnsl-2.13.so
7f2a78acf000-7f2a78ad0000 rw-p 00015000 fe:01 3670030                    /lib/x86_64-linux-gnu/libnsl-2.13.so
7f2a78ad0000-7f2a78ad2000 rw-p 00000000 00:00 0 
7f2a78ad2000-7f2a78ae0000 r-xp 00000000 fe:01 1187925                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f2a78ae0000-7f2a78ce0000 ---p 0000e000 fe:01 1187925                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f2a78ce0000-7f2a78ce1000 rw-p 0000e000 fe:01 1187925                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f2a78ce1000-7f2a78ce5000 r-xp 00000000 fe:01 3670089                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f2a78ce5000-7f2a78ee4000 ---p 00004000 fe:01 3670089                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f2a78ee4000-7f2a78ee5000 r--p 00003000 fe:01 3670089                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f2a78ee5000-7f2a78ee6000 rw-p 00004000 fe:01 3670089                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f2a78ee6000-7f2a78eea000 r-xp 00000000 fe:01 3670063                    /lib/x86_64-linux-gnu/libattr.so.1.1.0
7f2a78eea000-7f2a790e9000 ---p 00004000 fe:01 3670063                    /lib/x86_64-linux-gnu/libattr.so.1.1.0
7f2a790e9000-7f2a790ea000 r--p 00003000 fe:01 3670063                    /lib/x86_64-linux-gnu/libattr.so.1.1.0
7f2a790ea000-7f2a790eb000 rw-p 00004000 fe:01 3670063                    /lib/x86_64-linux-gnu/libattr.so.1.1.0
7f2a790eb000-7f2a790f0000 r-xp 00000000 fe:01 1190519                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f2a790f0000-7f2a792ef000 ---p 00005000 fe:01 1190519                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f2a792ef000-7f2a792f0000 rw-p 00004000 fe:01 1190519                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f2a792f0000-7f2a79351000 r-xp 00000000 fe:01 1190527                    /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f2a79351000-7f2a79550000 ---p 00061000 fe:01 1190527                    /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f2a79550000-7f2a79552000 r--p 00060000 fe:01 1190527                    /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f2a79552000-7f2a79553000 rw-p 00062000 fe:01 1190527                    /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f2a79553000-7f2a79557000 rw-p 00000000 00:00 0 
7f2a79557000-7f2a79560000 r-xp 00000000 fe:01 3673477                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f2a79560000-7f2a7975f000 ---p 00009000 fe:01 3673477                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f2a7975f000-7f2a79760000 r--p 00008000 fe:01 3673477                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f2a79760000-7f2a79761000 rw-p 00009000 fe:01 3673477                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f2a79761000-7f2a79762000 rw-p 00000000 00:00 0 
7f2a79762000-7f2a79767000 r-xp 00000000 fe:01 1190407                    /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7f2a79767000-7f2a79966000 ---p 00005000 fe:01 1190407                    /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7f2a79966000-7f2a79967000 rw-p 00004000 fe:01 1190407                    /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7f2a79967000-7f2a7996e000 r-xp 00000000 fe:01 1189372                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f2a7996e000-7f2a79b6d000 ---p 00007000 fe:01 1189372                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f2a79b6d000-7f2a79b6e000 rw-p 00006000 fe:01 1189372                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f2a79b6e000-7f2a79b85000 r-xp 00000000 fe:01 1189370                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f2a79b85000-7f2a79d84000 ---p 00017000 fe:01 1189370                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f2a79d84000-7f2a79d86000 rw-p 00016000 fe:01 1189370                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f2a79d86000-7f2a79d89000 rw-p 00000000 00:00 0 
7f2a79d89000-7f2a79d8a000 r-xp 00000000 fe:01 1186482                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f2a79d8a000-7f2a79f89000 ---p 00001000 fe:01 1186482                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f2a79f89000-7f2a79f8a000 rw-p 00000000 fe:01 1186482                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f2a79f8a000-7f2a79f8e000 r-xp 00000000 fe:01 3673459                    /lib/x86_64-linux-gnu/libcap.so.2.22
7f2a79f8e000-7f2a7a18d000 ---p 00004000 fe:01 3673459                    /lib/x86_64-linux-gnu/libcap.so.2.22
7f2a7a18d000-7f2a7a18e000 rw-p 00003000 fe:01 3673459                    /lib/x86_64-linux-gnu/libcap.so.2.22
7f2a7a18e000-7f2a7a1d2000 r-xp 00000000 fe:01 3673481                    /lib/x86_64-linux-gnu/libdbus-1.so.3.7.2
7f2a7a1d2000-7f2a7a3d2000 ---p 00044000 fe:01 3673481                    /lib/x86_64-linux-gnu/libdbus-1.so.3.7.2
7f2a7a3d2000-7f2a7a3d3000 r--p 00044000 fe:01 3673481                    /lib/x86_64-linux-gnu/libdbus-1.so.3.7.2
7f2a7a3d3000-7f2a7a3d4000 rw-p 00045000 fe:01 3673481                    /lib/x86_64-linux-gnu/libdbus-1.so.3.7.2
7f2a7a3d4000-7f2a7a435000 r-xp 00000000 fe:01 1190531                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-2.0.so
7f2a7a435000-7f2a7a634000 ---p 00061000 fe:01 1190531                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-2.0.so
7f2a7a634000-7f2a7a635000 r--p 00060000 fe:01 1190531                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-2.0.so
7f2a7a635000-7f2a7a637000 rw-p 00061000 fe:01 1190531                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-2.0.so
7f2a7a637000-7f2a7a63e000 r-xp 00000000 fe:01 1190521                    /usr/lib/x86_64-linux-gnu/libjson.so.0.0.1
7f2a7a63e000-7f2a7a83d000 ---p 00007000 fe:01 1190521                    /usr/lib/x86_64-linux-gnu/libjson.so.0.0.1
7f2a7a83d000-7f2a7a83e000 r--p 00006000 fe:01 1190521                    /usr/lib/x86_64-linux-gnu/libjson.so.0.0.1
7f2a7a83e000-7f2a7a83f000 rw-p 00007000 fe:01 1190521                    /usr/lib/x86_64-linux-gnu/libjson.so.0.0.1
7f2a7a83f000-7f2a7a888000 r-xp 00000000 fe:01 1190529                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.14.2
7f2a7a888000-7f2a7aa87000 ---p 00049000 fe:01 1190529                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.14.2
7f2a7aa87000-7f2a7aa88000 r--p 00048000 fe:01 1190529                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.14.2
7f2a7aa88000-7f2a7aa89000 rw-p 00049000 fe:01 1190529                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.14.2
7f2a7aaa0000-7f2a7aaa6000 r-xp 00000000 fe:01 1316708                    /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
7f2a7aaa6000-7f2a7aca5000 ---p 00006000 fe:01 1316708                    /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
7f2a7aca5000-7f2a7aca6000 r--p 00005000 fe:01 1316708                    /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
7f2a7aca6000-7f2a7aca7000 rw-p 00006000 fe:01 1316708                    /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
7f2a7aca7000-7f2a7aca8000 ---p 00000000 00:00 0 
7f2a7aca8000-7f2a7b4a8000 rw-p 00000000 00:00 0 
7f2a7b4a8000-7f2a7b4a9000 ---p 00000000 00:00 0 
7f2a7b4a9000-7f2a7bca9000 rw-p 00000000 00:00 0 
7f2a7bca9000-7f2a7bcab000 r-xp 00000000 fe:01 4732096                    /usr/lib/x86_64-linux-gnu/allegro/4.4.2/alleg-alsamidi.so
7f2a7bcab000-7f2a7beaa000 ---p 00002000 fe:01 4732096                    /usr/lib/x86_64-linux-gnu/allegro/4.4.2/alleg-alsamidi.so
7f2a7beaa000-7f2a7beab000 rw-p 00001000 fe:01 4732096                    /usr/lib/x86_64-linux-gnu/allegro/4.4.2/alleg-alsamidi.so
7f2a7beab000-7f2a7beb2000 r-xp 00000000 fe:01 3670040                    /lib/x86_64-linux-gnu/librt-2.13.so
7f2a7beb2000-7f2a7c0b1000 ---p 00007000 fe:01 3670040                    /lib/x86_64-linux-gnu/librt-2.13.so
7f2a7c0b1000-7f2a7c0b2000 r--p 00006000 fe:01 3670040                    /lib/x86_64-linux-gnu/librt-2.13.so
7f2a7c0b2000-7f2a7c0b3000 rw-p 00007000 fe:01 3670040                    /lib/x86_64-linux-gnu/librt-2.13.so
7f2a7c0b3000-7f2a7c19f000 r-xp 00000000 fe:01 1188821                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7f2a7c19f000-7f2a7c39f000 ---p 000ec000 fe:01 1188821                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7f2a7c39f000-7f2a7c3a5000 r--p 000ec000 fe:01 1188821                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7f2a7c3a5000-7f2a7c3a7000 rw-p 000f2000 fe:01 1188821                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7f2a7c3a7000-7f2a7c3ab000 r-xp 00000000 fe:01 4732095                    /usr/lib/x86_64-linux-gnu/allegro/4.4.2/alleg-alsadigi.so
7f2a7c3ab000-7f2a7c5ab000 ---p 00004000 fe:01 4732095                    /usr/lib/x86_64-linux-gnu/allegro/4.4.2/alleg-alsadigi.so
7f2a7c5ab000-7f2a7c5ac000 rw-p 00004000 fe:01 4732095                    /usr/lib/x86_64-linux-gnu/allegro/4.4.2/alleg-alsadigi.so
7f2a7c5ac000-7f2a7c5b1000 r-xp 00000000 fe:01 1193403                    /usr/lib/x86_64-linux-gnu/libXxf86dga.so.1.0.0
7f2a7c5b1000-7f2a7c7b1000 ---p 00005000 fe:01 1193403                    /usr/lib/x86_64-linux-gnu/libXxf86dga.so.1.0.0
7f2a7c7b1000-7f2a7c7b2000 rw-p 00005000 fe:01 1193403                    /usr/lib/x86_64-linux-gnu/libXxf86dga.so.1.0.0
7f2a7c7b2000-7f2a7c7b7000 r-xp 00000000 fe:01 4732080                    /usr/lib/x86_64-linux-gnu/allegro/4.4.2/alleg-dga2.so
7f2a7c7b7000-7f2a7c9b7000 ---p 00005000 fe:01 4732080                    /usr/lib/x86_64-linux-gnu/allegro/4.4.2/alleg-dga2.so
7f2a7c9b7000-7f2a7c9b8000 rw-p 00005000 fe:01 4732080                    /usr/lib/x86_64-linux-gnu/allegro/4.4.2/alleg-dga2.so
7f2a7c9b8000-7f2a7c9b9000 rw-p 00000000 00:00 0 
7f2a7c9b9000-7f2a7c9be000 r-xp 00000000 fe:01 1183116                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f2a7c9be000-7f2a7cbbd000 ---p 00005000 fe:01 1183116                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f2a7cbbd000-7f2a7cbbe000 rw-p 00004000 fe:01 1183116                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f2a7cbbe000-7f2a7cbc0000 r-xp 00000000 fe:01 1183113                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f2a7cbc0000-7f2a7cdc0000 ---p 00002000 fe:01 1183113                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f2a7cdc0000-7f2a7cdc1000 rw-p 00002000 fe:01 1183113                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f2a7cdc1000-7f2a7cdc6000 r-xp 00000000 fe:01 1186460                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0Abgebrochen

**Comment by ivan-mogilko** [comment]
It was never clear what was this issue caused by really. Engine has changed significantly since, and I run the game now on Ubuntu without any crashes. I'd like to close this now. If the bug is experienced again with the latest release please open a new issue.
