### ISSUE TITLE
[Linux] Allegro DIGMID no longer functional in 3.3.5.7

### ISSUE THREAD

**Issue by jspatz** [adventuregamestudio/ags#341]
I'm running AGS under Arch Linux x64.  I recently updated to 3.3.5.7, the current version of AGS supplied by the AGS package in the Arch User Repository.  I've got the following options set in /etc/allegro.cfg:

`midi_card = DIGI`
`patches = /usr/share/soundfonts/SGM-V2.01.dat`

Under the previous version of AGS that I had installed, 3.3.4.2, these settings would be observed when AGS initializes Allegro:

`AGS: Installed digital driver ID: 'ALSA' (0x414c5341), MIDI driver ID: 'DIGI' (0x44494749)`

and MIDI music would play as expected via the DIGMID synthesizer.

With AGS 3.3.5.7, the result is:

`Installed digital driver ID: 'ALSA' (0x414c5341), MIDI driver ID: 'None' (0x0)`

and, as expected, no music is being synthesized.  Attempting to manually define the MIDI device via an entry in an acsetup.cfg, i.e. `midiid=44494749` does not work, and the MIDI device defaults back to 'none'.

**Comment by jspatz** [comment]
Correction of above: I'd accidentally pasted the hex ID of the DIGI synth into acsetup.cfg.  When I replace it with the decimal ID it expects, `midiid=1145653065`, I get the following:

> `Trying digital driver ID: 'Auto' (0xffffffff), MIDI driver ID: 'DIGI' (0x44494749)`
`Failed to init one of the drivers; Error: DIGMID patch set not found`
`Trying to start without MIDI`

When I create a ./patches.dat as a symlink to my actual patch file, it works correctly.  So it seems that the current version of AGS is no longer respecting the 'patches' entry in allegro.cfg.  Can the behavior be adjusted to look for the patches configured with allegro prior to defaulting to no MIDI device if a patches.dat is not found in the usual search path?

**Comment by ivan-mogilko** [comment]
>  So it seems that the current version of AGS is no longer respecting the 'patches' entry in allegro.cfg

I think I know why this is happening. There was a change between 3.3.4 and 3.3.5 that overrides allegro.cfg to fix certain issue. I did not realize people may be using their own allegro.cfg. I will be looking into fixing this.

**Comment by ivan-mogilko** [comment]
Okay, it is possible that it is simply a case of using wrong allegro function.

In file Engine/main/engine.cpp there is a function "engine_setup_allegro". Inside that function allegro's set_config_data() is being called. I think that changing it to "override_config_data" instead may fix this problem.

**Comment by jspatz** [comment]
I tested 3.3.5.7 rebuilt with the "set_config_data" function changed to "override_config_data" as you specified, and it does indeed solve the issue on my end.

**Comment by ivan-mogilko** [comment]
@jspatz, could you confirm that latest **release-3.3.5** branch (particulary commit dae74739461ee8dc4c75b49382e0a148ce7903a4) works for you?

**Comment by jspatz** [comment]
I can confirm that AGS built from this branch solves the issue on my end.
