### ISSUE TITLE
Build pack location

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#347]
If you are using the Linux build pack (current instructions say to copy the folder to the installation directory) the Inno Setup uninstaller doesn't remove it when the uninstall process is run, so the installation folder cannot be deleted.

The build pack probably shouldn't be in this directory to start with, since at worst the user trying to install a build pack might not be an administrator, and at best they'll have to use an elevated shell or approve a UAC prompt to copy the folder. Also, I would imagine that there might be multiple build packs at some point in the future, and they won't neccessarily be in sync with editor releases.

In the short term maybe it's best to get the installer to clean-up the build pack as well, I guess something like this:

<pre>[UninstallDelete]
Type: filesandordirs; Name: "{pf}\{#AgsName} {#AgsFriendlyVersion}\Linux”</pre>

...but I think the build packs should be treated more like plug-ins, so in %PROGRAMDATA% (installed for all users) or in %APPDATA% (installed for the current user) would seem the appropriate places. The editor should probably check them both and offer the build check box for any build pack that it finds, plus give you an import option for build packs (copy to one of the above locations).

**Comment by ivan-mogilko** [comment]
I do not think it is correct to make installer clean something that it does not install. I would rather have Linux build pack inside distributive too, installed if user checked an option in the components list. This way we will also ensure that user can install compatible package.

**Comment by morganwillcock** [comment]
Yes, if they are included with the installer that solves the uninstall problem. I was more worried that the official instructions would remain as "extact the build pack into the installation folder".

**Comment by ivan-mogilko** [comment]
We now include "Linux" component in the Editor's installer program.
