### ISSUE TITLE
‘shared_ptr’ in namespace ‘stdtr1compat’ does not name a template type

### ISSUE THREAD

**Issue by ainola** [adventuregamestudio/ags#356]
Compiling 3.4.0.12 with gcc 6.2.1 on Archlinux produces the following error:

```
ac/math.o
In file included from ../Engine/script/script_runtime.h:31:0,
                 from ac/math.cpp:227:
../Engine/script/cc_instance.h:121:27: error: ‘shared_ptr’ in namespace ‘stdtr1compat’ does not name a template type
     typedef stdtr1compat::shared_ptr<ScVarMap>                   PScVarMap;
                           ^~~~~~~~~~
../Engine/script/cc_instance.h:124:5: error: ‘PScVarMap’ does not name a type
     PScVarMap globalvars;
     ^~~~~~~~~
make: *** [Makefile:46: ac/math.o] Error 1
make: Leaving directory '/home/ainola/AUR/ags/src/ags-v.3.4.0.12/Engine'
```

**Comment by ivan-mogilko** [comment]
Should be fixed with 5a8dc7a37b312ea8d308db03bd14a6f5d6583a1f

**Comment by ivan-mogilko** [comment]
BTW, I was testing this out with gcc6 on Antergos system, and compilation log was swarming with the warning about auto_ptr being deprecated. Since we perfectly aware of that, I am just wondering if that may make sense to add an option to gcc to supress warnings like that.

**Comment by ainola** [comment]
Thanks for that! I've included a patch with the release in the meantime.

As for the errors: I'm afraid I'm not the most qualified individual for this advice.
