### ISSUE TITLE
Hardcoded framerate logic

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#360]
I found a a place where the engine assumes 40 frames per second while handling the **loopcounter** variable
void CharacterInfo::update_character_idle(CharacterExtras *chex, int &doing_nothing) @characterinfo.cpp

Maybe even "void ShakeScreen(int severe)", I see a "hh < 40", but I'm not quite sure what's going  on there.

**Comment by AlanDrake** [comment]
It's also worth mentioning that the way the loopcounter is used has a side effect: adding from zero to almost a second delay. This is unfavorable if the idle view is meant to start immediately (delay=0).

`    else if ((loopcounter%40==0) || (chex->process_idle_this_time == 1)) {
      idleleft--;
      if (idleleft == -1) {`

**Comment by rocifier** [comment]
I just had a quick look at the code. These things also look wrong to me.

**Comment by AlanDrake** [comment]
Heh, it's not just that. At the moment there's no way to properly set a target framerate without throwing off seconds/frames calculations.
SetGameSpeed was originally meant to speed up or slow down, I think we'll have to introduce a reference framerate variable, replace all the hardcoded instances and then see how to make it work properly.
Might add a new method and call it SetFrameRate or something.

**Comment by ivan-mogilko** [comment]
> Maybe even "void ShakeScreen(int severe)", I see a "hh < 40", but I'm not quite sure what's going on there.

To clarify, in ShakeScreen 40 is a hardcoded number of shakes, the actual delay per shake is hardcoded as 50 for some reason.

**Comment by ivan-mogilko** [comment]
@AlanDrake CharacterInfo::update_character_idle is now fixed to not use hardcoded logic (2e0d5116bce07a098166d6f6311fc87b27352e47)

**Comment by ivan-mogilko** [comment]
I did a change regarding ShakeScreen: 1f079403cb29f93bbb3d066ab72e1e42420ee802
Now it uses proper frame mechanic, waits and renders using game's fps. The duration and shake delays still use hardcoded numbers, but are not applied directly and used as factors to calculate generic shake params instead.

**Comment by ivan-mogilko** [comment]
@AlanDrake  I'd close this, but I did not quite understand your statement in one comment above:

> At the moment there's no way to properly set a target framerate without throwing off seconds/frames calculations.
SetGameSpeed was originally meant to speed up or slow down, I think we'll have to introduce a reference framerate variable, replace all the hardcoded instances and then see how to make it work properly.
Might add a new method and call it SetFrameRate or something.

Could you elaborate on this?
