### ISSUE TITLE
macOS Sierra cannot build AGS Mac's libs

### ISSUE THREAD

**Issue by edmundito** [adventuregamestudio/ags#373]
With macOS Sierra and Xcode 8, there is an issue to build the third party libraries via:

```
cd OSX/buildlibs
make install
```

The following error occurs:
```
OSX/buildlibs/build/allegro-4.4.2/include/allegro/platform/alosx.h:45:15: fatal error:
      'QuickTime/QuickTime.h' file not found
      #import <QuickTime/QuickTime.h>
              ^
1 error generated.

...

** BUILD FAILED **


The following build commands failed:
	CompileC OSX/buildlibs/build/allegro-4.4.2/build/ALLEGRO.build/RelWithDebInfo/allegro.build/Objects-normal/x86_64/cadigi.o src/macosx/cadigi.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [allegro] Error 65
```

The root cause is that QuickTime is gone, and apparently the solution may be to remove the import from that file. I wanted to provide a fix, but was not too sure how to update the allegro patch properly.

Here are some references to the fix in Allegro 5:
https://github.com/liballeg/allegro5/commit/fc2c2c18473242d326c04e0b405075d3f8db2117

https://www.allegro.cc/forums/thread/616534

**Comment by sonneveld** [comment]
This is actually fixed in my osx branch.

**Comment by ivan-mogilko** [comment]
@edmundito , @sonneveld was this actually fixed? Also, I am unaware of the macOsx port's state for 3.5.0.

**Comment by sonneveld** [comment]
The port works quite well, albeit I've only been testing via cmake so there might be some issues with the legacy makefile and buildlibs scripts

**Comment by ivan-mogilko** [comment]
@edmundito

We are using Allegro 4.4.3 now, but it looks like they still got this `#import` in the official version:
https://github.com/liballeg/allegro5/blob/4.4/include/allegro/platform/alosx.h#L45

It was removed in our own repository though, which may explain why our Cmake script builds fine on macos (as it pulls allegro from our repository).

If this is still a problem for you, maybe we could ask allegro team to investigate the options of resolving this in their repository too.

**Comment by ivan-mogilko** [comment]
@vga-256 Hello, I heard you are working on 3.5.1 ports for the AGS Awards client. Would you be able to check out this issue, and also couple of more mac related that are still assigned to 3.5.1: 
https://github.com/adventuregamestudio/ags/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.5.1+label%3A%22system%3A+macOS%22

I'm insterested to know at least if these are still valid problems; if yes if these can be fixed somehow.

**Comment by ivan-mogilko** [comment]
As this is a) mostly a problem with allegro4 upstream version, b) we have moved to SDL2 in the upcoming version, and c) that there seem to be no interest to try this further from OP, I'll close this.
