### ISSUE TITLE
Android Launcher: game search logic is incorrect

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#379]
AGS launcher app for Android uses an incorrect method for detecting AGS game files: it looks for files named "ac2game.dat" which have Windows executable properties inside of them. (I think this was made for simplicity, at the times when proper method was not well known).

Correct way to find AGS game data files should be copied from the native engine; see [FindGameData](https://github.com/adventuregamestudio/ags/blob/master/Common/game/main_game_file.cpp#L134) for the reference.

**Comment by ivan-mogilko** [comment]
Done for 3.5.1 by #1289, but now need to reimplement separately for 3.6.0, as launcher changed too much to copy the commit.
