### ISSUE TITLE
AGS Script: variable of zero size is permitted to be used in variadic function call

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#385]
**TEST CASE 1**
<pre>
struct MyStruct {};

// more global variables may be declared PRIOR to MyStruct's one
MyStruct a;

function game_start()
{
  Display("%d", a);
}
</pre>

I currently cannot see any other means to force the reference to such variable in script, except for using it in the variadic function parameter list (by mistake).

If there are no variables declared after empty one, what happens is that compiler registers global variable at offset N, but since that variable has zero size, and declared in the end of the global variables list, offset N appears to be equal to global data array's size (points beyond array).

In response to this engine issues a warning:
"WARNING: global variable refers to data beyond allocated buffer"
and later
"WARNING: looking up for global variable beyond allocated buffer"

NOTE: these are warnings, not strict errors, because one game has this issue: ["Metal Dead"](https://www.adventuregamestudio.co.uk/site/games/game/1539/).

If there ARE valid variables declared after empty one, then referencing empty variable will actually refer to the next valid variable's data instead.

---

**TEST CASE 2**
<pre>
struct MyStruct {};

function game_start()
{
  MyStruct a;
  Display("%d", a);
}
</pre>

This is a similar case, but variable is referenced on virtual stack memory. Interestingly, engine does not correctly detect this problem, probably due to stack having fixed preallocated buffer. But this may be dangerous nevertheless.

---

**SOLUTION**

We need to find a way to prevent empty variable referencing in compiler, and some safety workarounds in the engine.

**Comment by ivan-mogilko** [comment]
Updated issue title and description; this problem actually refers to both global and local variables (although outcome is slightly different).

**Comment by ivan-mogilko** [comment]
@fernewelten could you check this problem out?

I tested with your compiler, and above examples simply do not work anymore because new compiler does not allow to pass regular struct as parameter anywhere.

Still, how does it handle variables of zero size as in above examples?

**Comment by ivan-mogilko** [comment]
UPDATE: the new compiler causes a bigger problem:

<pre>
struct EmptyStruct {
};

function game_start()
{
  EmptyStruct s;
}
</pre>

Running this script results in runtime error:

> Error: Error running function 'game_start':
> Error (line 8): stack pointer was not zero at completion of script

**Comment by fernewelten** [comment]
As far as I understand the current calling convention, it is very much dependent on each parameter occupying exactly four bytes. Anything larger can't be passed unless through a pointer (which is exactly four bytes long). Anything smaller is enlarged to four bytes, by moving it into a register and then using a standard push command. This also goes for variadic functions. 

As Ivan noted above, the new compiler doesn't handle whole structs as parts of expressions, in particular it won't pass them to functions. But if it did, the issued code would move them into a register and push them, in effect enlarging them to exactly four bytes on the stack.

AFAIK, the Engine really doesn't like zero-length dynamic memory, there was a time where this would even trigger a division-by-zero error at runtime. So in particular, pointers to zero-length memory can't end up on the call stack.

**Comment by ivan-mogilko** [comment]
So, I think this is covered by the new compiler:

1. Zero sized global variables are not mentioned in the compiled script's table;
2. You no more may pass an instance of a struct into the function (see below).
3. Compiler issues a warning on instances of zero size.

<pre>
struct MyStruct {};
MyStruct a;

function game_start()
{
  Display("%d", a);
}
</pre>

`Cannot access non-managed struct as a whole`
