### ISSUE TITLE
AGS Script: local variables do not work in "case" statements of a switch

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#387]
Basic test:

<pre>
    Character *pc;
    pc = player;
    switch (player)
    {
      case pc:
        Display("pc matches");
        break;
    }
</pre>

If "Character *pc" is a global variable, this test properly displays "pc matches" string, but if it is a local variable, then it does not.

This behavior was broken by 8407af2cb10aca37eda762e7a98f05b7bd4ecccb

**Comment by gurok** [comment]
This *should* be fixed in #391

**Comment by ivan-mogilko** [comment]
Fixed by 657e672a6708b8635533662c7d6d1363514f2818
