### ISSUE TITLE
Notification: ceasing my work on the project

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#393]
I decided to cease my work on this project. This is long due, but I kept maintaining it despite of wanting to stop couple of years ago.

The biggest problem and mistake was that we chose wrong approach on its development. We should have  reach stable execution of existing games on chosen ports, and then probably create new versions based on completely new codebase (contemporary libraries, and so on).

Because we did not do it, most time and effort was spent on backwards compatibility.

I personally do not see any point in developing this tool further, because it is already so much outdated, that it would make more sense to write one anew. Let alone the fact that we do not have any consistent project team.

The source is still open and free, so if anyone would like to take it from here, there is no problem in that.

**Comment by rofl0r** [comment]
that's bad news. you will be missed...
anyway, good luck, and thanks for the great work you've done for this project.

**Comment by JanetGilbert** [comment]
Sad to hear that! I don't think the project took any wrong turns. Great progress was made! It's much better now than when you started. Thanks for all the work.

Janet

**Comment by ivan-mogilko** [comment]
Well, "leaving the project" did not work very well eventually, although I am still not sure neither of the project or my future here.
