### ISSUE TITLE
Problem with play_fli and apparent need to patch Allegro

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#407]
This was explained before, but in short, AGS had its own version of "pack_fopen" function to override Allegro4's, that created PACKFILE stream from AGS own data package. This was made so because not all of the Allegro4 media API provided means to use custom PACKFILE to create an object.

After getting rid of pack_file in AGS, I had to only write new function for creating MIDI clip from provided PACKFILE, which Allegro 4 library lacked. I even sent the patch to Allegro repository, which they accepted (for latest A4 WIP branch). But for us a function inside AGS engine was enough (it was possible to make one), since we still link against latest stable release of Allegro 4.4.2.

The reason I did not want to actually use Allegro's development version at that time was that I did not know how to deal with Linux port. I got an impression that Linux users usually prefer to get maintained packages of libraries when a new version comes out, not arbitrary WIP branches.

Anyway, this time the problem is more serious. I found out that I missed FLIC functionality, which also lacks function to pass PACKFILE to, only functions to pass filename and memory buffer. I was about to use the latter, but I have doubts about that: this method requires to keep whole file in memory, meaning it will take time to load it all before playing, and increased memory requirements for playing it.
Okay, I may sound bit paranoid there, but who knows what game developers may put into their game, what if that will be 500 MB video file?

So, I tried to write analogue for play_fli which takes PACKFILE as parameter, similarily to how I made load_midi_pf, but to my desperation I found out that in Allegro 4 FLIC implementation is heavily based on the use of internal global variables... which have to be set properly, and to which I do not have access from external program anyway. Which means I'd actually have to patch Allegro this time.

So right now I am at crossroads, not knowing which path to choose. I could pass another patch to Allegro team; actually I could simply patch our own Allegro branch. Either way would be OK for Windows version, where we statically link to Allegro anyway. That won't seem to be a big problem for mobile ports too, because they require patching Allegro already. But what about Linux users? Will they be able (and willing) to build special Allegro build from either WIP branch of official repository, or our own patched branch?

What are alternatives... linking to some separate FLIC playing library, if one exists, hoping that won't take too much time.... copying whole FLIC implementation into AGS (uhhhh)?

**Comment by rofl0r** [comment]
do you have some numbers how many games actually use FLI video ? afaik that's a stone-old format, and i would guess nobody uses it today.
if it's only a handful, then maybe the easiest thing would be to just not support playing it on linux (i.e. skip playing the video). or launch some external fli player software ?

**Comment by ivan-mogilko** [comment]
I could propose a patch to Allegro4 in hope they will release a new version at some point; Windows version will use our custom patched version, and Linux users either deal with missing video, or build Allegro from  particular Allegro branch if they want to.

**Comment by ivan-mogilko** [comment]
BTW, my patch was accepted by Allegro 4: https://github.com/liballeg/allegro5/pull/761

**Comment by ivan-mogilko** [comment]
> I could propose a patch to Allegro4 in hope they will release a new version at some point; Windows version will use our custom patched version, and Linux users either deal with missing video, or build Allegro from particular branch if they want to.

Well, we are there for the time being, so I am closing this issue.
