### ISSUE TITLE
[ANN] ags disassembler and assembler available!

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#41]
https://github.com/rofl0r/agsutils

i was able to extract all 139 scripts contained in "Duty And Beyond" into disassembly, recompile them with the assembler, and inject the modified scripts again into the game - and it works.

this should be a milestone in debuggability of AGS games.

see README for usage instructions.

**Comment by ivan-mogilko** [comment]
TBH I am not sure how to deal with announcement kind of tickets. I'd rather close it now but may add a link to the agsutils in our repository's wiki or even Readme.
