### ISSUE TITLE
speech not working anymore in Linux

### ISSUE THREAD

**Issue by cedricbu** [adventuregamestudio/ags#412]
Speech does not seem to work anymore (music and sound still fine). There's no more errors to be seen.

Workaround : getting back to v.3.4.0.16

**Comment by ivan-mogilko** [comment]
What branch/tag this bug is present in?

**Comment by ivan-mogilko** [comment]
Fixed with ac5b8df in "release-3.4.1" branch. Will merge to master in a short while.

**Comment by vdeG123** [comment]
Hi!!

  I would like to know when this is going to be merged into the master? ;)

Thanks a lot!!

**Comment by ivan-mogilko** [comment]
Sorry, it looks like I already did and forgot to mention this here.

If you open commit I linked above, you may see that it is included in both master and release-3.4.1 branch.

Please tell if the speech works in master branch for you now.

**Comment by vdeG123** [comment]
Hi!!

  I am using the emulator with a Retropie setup on a Raspberry Pi, and now it is working like a charm!! ;)
  Theora videos and speech were not working, and now they are!!

Thanks a lot!!

**Comment by ivan-mogilko** [comment]
Good to know, I am closing this issue then.
