### ISSUE TITLE
'glCreateShader' was not declared in this scope

### ISSUE THREAD

**Issue by monkey0506** [adventuregamestudio/ags#420]
In Engine/gfx/ali3dogl.cpp, line 585 references `glCreateShader`, which apparently only exists if `WINDOWS_VERSION` is defined. The entire file seems to be omitted (via the preprocessor) except for `WINDOWS_VERSION`, `ANDROID_VERSION`, and `IOS_VERSION`, but as I said, the `glCreateShader` symbol is only defined for `WINDOWS_VERSION`.

This was tested on the current master branch, I have not yet inspected if 3.4.1 branch has the same issue, though I presume it does. This makes building for Android and IOS impossible on the current master.

**Edit:** A summary glance at the 3.4.1 branch shows the same issue, as suspected.

**Comment by ivan-mogilko** [comment]
Yes, Android and iOS cannot built 3.4.1 yet. When I found that OpenGL renderer does not support tinting and lighting yet, I had to implement these using shaders, introducing a bunch of new functions to the code. glCreateShader may not be the only function that won't be found.

If you look around the code you may notice that for every port there are different set of headers included, and some function names are macros redefined as actual function names, related to that port's openGL library.

We need to find out what headers to include for Android and iOS and how corresponding functions are called in their SDKs.

The full list of newly used functions to check:

<pre>
glCreateShader
glShaderSource
glCompileShader
glGetShaderiv
glGetShaderInfoLog
glAttachShader
glDetachShader
glDeleteShader
glCreateProgram
glLinkProgram
glGetProgramiv
glGetProgramInfoLog
glUseProgram
glDeleteProgram
glGetUniformLocation
glUniform1i
glUniform1f
glUniform3f
</pre>

I hope this is not the case, but if these devices do not support something of here, then the only workaround is to provide dummy stubs (and disable this part of functionality).

**Comment by ivan-mogilko** [comment]
**Update:** Android port compilation was fixed in both release-3.4.1 and master branches.

iOS was not, but I do not have means to compile it myself right now.
