### ISSUE TITLE
Laggy audio

### ISSUE THREAD

**Issue by DuendeInexistente** [adventuregamestudio/ags#436]
After testing with the precompiled binaries and not liking the results (The main game I want to play gives me a null pointer error) I compiled from git, and midi playback is being laggy. *Very* laggy. I don't have an incredibly powerful rig, but it surprised me when I can play midi files well in any other program.
I tested with another game and the result was the same, laggy music.
For the curious, the log is this:

> ▶ /home/cammera/Downloads/ags/Engine/ags --windowed --gfxfilter stdscale 2 
>Adventure Game Studio v3.4 Interpreter
>Copyright (c) 1999-2011 Chris Jones and 2011-2018 others
>ACI version 3.4.2.0
>
>Initializing allegro
>Reading configuration
>Located game data file: /media/cammera/Datos/Juegos/FullyRamblomatic-SpecialEditions/5daysse/5days.exe
>
>Opened game data file: ac2game.dta
>Game data version: 27
>Compiled with: 2.62
>Setting up window
>Initializing TTF renderer
>Initializing mouse: number of buttons reported is 3
>Checking memory
>Data directory: /media/cammera/Datos/Juegos/FullyRamblomatic-SpecialEditions/5daysse
>Initializing keyboard
>Install timer
>Sound settings: digital driver ID: 'Auto' (0xffffffff), MIDI driver ID: 'Auto' (0xffffffff)
>ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
>Installed digital driver ID: 'ALSA' (0x414c5341), MIDI driver ID: 'DIGI' (0x44494749)
>Install exit handler
>Initialize path finder library
>Game GUI version: 105
>Game title: '5 Days A Stranger'
>Checking for disk space
>Game native resolution: 320 x 240 (16 bit) letterbox-by-design
>Game settings: windowed = yes, screen def: scaling, screen size: 0 x 0, match device ratio: ignore, >game scale: 2
>Mouse control: off, base: 1.000000, speed: 1.000000
>Initialize sprites
>Audio is processed on the main thread
>Engine initialization complete
>Starting game
>***** ENGINE HAS SHUTDOWN

Is there anything I could to do to improve audio playback? I was a bit surpsied at seeing that there weren't any options related to it in the executable.

**EDIT**: I tried to mute it directly from pulse's audio control since it allows per-application volume, but the thing is appearing and dissapearing from it constantly and when I manage to click mute fast enough it just forgets the setting next time it appears. Makes me wonder if this is just starting a bunch of processes that crash for some reason.

**Comment by ivan-mogilko** [comment]
What you describe seem to be a know issue. Personally I won't be able to help, but must mention this: the project was lacking a proper Linux maintainer for years. I tried to keep Linux engine runnable and being able to execute games, but that's it. Program is still based on a very old library (allegro 4), so the root of this issue may actually lie inside one.
Unless someone Linux-savvy takes this in their own hands, I doubt there will be any fix.
Moving to another library (e.g. SDL) may be a solution to many of similar problems, but that would take a serious effort.

Alternatively, there is a work to finish ScummVM port: https://github.com/adventuregamestudio/scummvm
Perhaps you will be able to run at least old games using that.

**Comment by rofl0r** [comment]
is the CPU usage at 100% ? if so you could try with linux' `perf` command to find the function that sucks up your CPU. if not, there's probably some stupid timing issues somewhere.

**Comment by DuendeInexistente** [comment]
No, it doesn't affect my performance significantly.

**Comment by DuendeInexistente** [comment]
It uses in average a 5%. I should've mentioned this before, but I have a CPU usagfe counter on screen at all times so I would've noticed if it was suddenly topping all the time.

I would appreciate it if there was simply an option to mute the music or audio in general, as a compromise until someone can solve the issue. It should be easier to simply set the volume to 0%, right?

**Comment by DuendeInexistente** [comment]
Btw, [here](https://files.catbox.moe/CX16es.txt) is the result of using perf. It's nearly 3 MBs of text.

**Comment by ivan-mogilko** [comment]
> I would appreciate it if there was simply an option to mute the music or audio in general, as a compromise until someone can solve the issue. It should be easier to simply set the volume to 0%, right?

There is a way to disable audio: open acsetup.cfg and put following:
<pre>
[sound]
digiid = 0
midiid = 0
</pre>

That supposed to init allegro with "none" audio drivers.

**Comment by DuendeInexistente** [comment]
```
Adventure Game Studio v3.4 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2018 others
ACI version 3.4.2.0

Initializing allegro
Reading configuration
Located game data file: /media/cammera/Datos/Mis Documentos/Downloads/Vinyl Demo/Octavia in The Underworld's Cello.exe

Opened game data file: game28.dta
Game data version: 42
Compiled with: 3.2.0
Logging scipt to "warnings.log"
Setting up window
Initializing TTF renderer
Initializing mouse: number of buttons reported is 3
Checking memory
Data directory: /media/cammera/Datos/Mis Documentos/Downloads/Vinyl Demo
Voice pack found and initialized.
Audio vox found and initialized.
Initializing keyboard
Install timer
Sound settings: digital driver ID: 'None' (0x0), MIDI driver ID: 'Auto' (0xffffffff)
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
Failed to init one of the drivers; Error: 'Insufficient digital voices available'.
Will try to start without MIDI
Failed to init sound drivers. Error: Insufficient digital voices available
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
Failed to init one of the drivers; Error: 'Insufficient digital voices available'.
Will try to start without MIDI

Unable to initialize your audio hardware.
[Problem: ]
Installed digital driver ID: 'None' (0x0), MIDI driver ID: 'None' (0x0)
Install exit handler
Initialize path finder library
Game GUI version: 115
Game title: 'Octavia in The Underworld's Cello'
Checking for disk space
Game native resolution: 320 x 200 (32 bit)
Game settings: windowed = yes, screen def: scaling, screen size: 0 x 0, match device ratio: ignore, game scale: 2
Mouse control: off, base: 1.000000, speed: 1.000000
Initialize sprites
Audio is processed on the main thread
Engine initialization complete
Starting game
Shutting down Allegro due to signal #11
[1]    6515 segmentation fault (core dumped)  ../ags/Engine/ags --windowed --gfxfilter stdscale 2
```
The midi driver being set to 0 is fine, but starts with broken audio anyway, but the digital driver does this.

**Comment by ivan-mogilko** [comment]
Hmm, I will check out how it behaves on my machine, could you tell, which commit did you use to build the engine?

**Comment by DuendeInexistente** [comment]
77294fb3

**Comment by ivan-mogilko** [comment]
Ok, I gave it a quick test, disabling both midi and digital sound, and had no crash.

Does it occur with any game for you, or only with particular one(s)?

**Comment by DuendeInexistente** [comment]
Not for sound-related reasons, no. Only pattern is some windows software under wine -never found why exactly- and most recent unity games for GPU reasons.

**Comment by ivan-mogilko** [comment]
Sorry, what I meant, if you try any other AGS game, will it crash similarily if you disable digital sounds?

**Comment by ivan-mogilko** [comment]
> And no- to my knowledge warnings.log isn't actually being saved anywhere.

Oh, I just realized why you mentioned "warnings.log". This means the game was compiled in "Debug" mode. Is it your own game project, or you have downloaded it from somewhere?

On Linux AGS logs are written into $XDG_DATA_HOME/ags/GAMENAME/, which is $HOME/.local/.share/ags/GAMENAME/ by default.

There is more information on options and some paths here: https://github.com/adventuregamestudio/ags/blob/master/OPTIONS.md

**Comment by DuendeInexistente** [comment]
Huh, I tried with 7 days a skeptic and it works like a charm, even past the intro. [This](https://www.mediafire.com/file/2bc8yvrja1qox9a/Vinyl+Demo.rar) is the game that gives me issues, and which didn't run in the deb available.

Warnings.log isn't saved there either, only a single savefile (I assume it's created on first run as a dummy file) and acsetup.cfg

**Comment by ivan-mogilko** [comment]
This is very interesting, I'll try to test this out.

As for "warnings.log" it is created only when there are script warnings, which may not be your case at the moment. That is special log mainly to bring game developer's attention to something; and the main log is created if you run the game with --log parameter.

**Comment by ivan-mogilko** [comment]
Well, I can see that the game is closed because of the game script error: that's the problem I was speaking about above.

Since AGS 3.2 the sound API requires you to test whether AudioClip.Play function returns null pointer, which actually happens if the sounds are disabled in setup. This is one of those uncomfortable design quirks that many AGS users are not aware of. You may even find errors like that in commercial releases, such as Resonance for instance.

**Comment by DuendeInexistente** [comment]
What comes to mind is that what happens is the crash reporter causing the segfault, but I got no idea if it's possible to check that.

**Comment by ivan-mogilko** [comment]
Similarily, will close this after moving to SDL2 backend and sdl_sound library. The 3.6.0.* engine seem playing sounds better, even on linux virtual machine where i had various problems with it in the past.

If there are similar problems with the new version, please open a new report.
