### ISSUE TITLE
Text Window GUI crashes engine when border images are deleted

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#443]
When a text windows is displayed (e.g. `Display("Hello")`), if any of the border images have been deleted, the game will crash. I think this makes it impossible to create a text window GUI that does not have borders, although the editor also appears to incorrectly crop the editing controls, so perhaps I am missing something. 

Also, once deleted, I can't see any way to put the border images back.

**Comment by ivan-mogilko** [comment]
> Also, once deleted, I can't see any way to put the border images back.

You mean in the editor? Borders are buttons, and may be selected in the object list of the property grid.
Also, I think you may select them by clicking on exactly small spot on the GUI (could be few pixels wide).

**Comment by morganwillcock** [comment]
When you delete them they are removed from the property list. I'm deleting them by clicking the tiny selectors (the ones which are only a few pixels wide) and pressing delete on the keyboard.

Having fiddled with it a little more, I can choose sprite 0 to make them invisible in the editor, but then any which are not invisible (have a sprite) don't show up in the game.

**Comment by ivan-mogilko** [comment]
Oh, I though you were speaking about deleting the sprite (removing from property). Did not know they could be deleted like that. That's definitely it's own bug then.
