### ISSUE TITLE
Scripting: AGS compiler ignores unsupported constructor-like syntax

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#449]
Right now (3.4.1) AGS script supports creating objects of managed custom types, but does not support constructors.
Object creation normally looks like this:
<pre>
MyStruct *obj = new MyStruct;
</pre>

However, following syntax is ignored by compiler and not treated as error:
<pre>
MyStruct *obj = new MyStruct();
MyStruct *obj = new MyStruct( some parameters );
</pre>

In reality this does nothing, and creates a clear object (where every member is initialized to 0).

This may be an issue if you are porting a code from somewhere else, since there is no signal from compiler that such construct is not valid that may be quite difficult to pinpoint the problem.

**Comment by ericoporto** [comment]
In this case, is the desired solution to output an error, or to support constructors?

**Comment by ivan-mogilko** [comment]
> In this case, is the desired solution to output an error, or to support constructors?

Compiler must fail at anything it does not support, so this is desired solution short-term.

Whether to support constructors or not is entirely separate thing.

**Comment by ivan-mogilko** [comment]
With the new compiler in ags4 branch this is no longer permitted, but the result is unexpected: instead of telling that such function does not exist, for example, it instead tells:

> Error: Expected '[', found '(' instead

In other words it for some reason thinks that I was supposed to create a dynamic array.

**Comment by fernewelten** [comment]
> In other words it for some reason thinks that I was supposed to create a dynamic array.

It does: Whenever any character other than `;` follows after the keyword `new` and a struct name, then the only possible case is that a dynarray is being declared. So when the compiler doesn't find a `[` then it becomes unhappy about not finding an array size in brackets.

Just what would be a better error message?

**Comment by ivan-mogilko** [comment]
Hmm, my concern was that this may sound like an advice to replace '(' with '[', which will mislead a person who tried to use a constructor like syntax. So perhaps "Unexpected '('" could sound better, not implying what should be done instead.
But then, everyone has their own perception, so maybe I'll close this as fixed, and leave this to you if you want to change the message.
