### ISSUE TITLE
AGS 4: GetWalkableAreaAt is broken

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#457]
GetWalkableAreaAt is broken in master branch, compared to "ags3", it returns incorrect area index.
I confirmed that this error was introduced by merging "ags4" branch, but did not find what causes it yet.

Possible suspects are coordinate conversion and incorrectly loaded mask.

PS. I was testing this game: http://www.adventuregamestudio.co.uk/site/games/game/2216/
It features a huge scrollable room, if that matters. Calls GetWalkableAreaAt to find out the area cars are located on.

**Comment by ivan-mogilko** [comment]
Ok, if I understood @AlanDrake 's explanations correctly, in the past all games with "high-res" native resolution (which means "over 320x240" in AGS terms) had some of the room masks reduced in size compared to the room size (something like 1:2 or 2:3, don't remember that by heart). Probably this was done to save memory and disk space.

@AlanDrake has removed the game resolution-based coordinate conversion from the engine and made it so that the Editor always creates 1:1 maks. Which probably makes sense on its own, but unfortunately this breaks all 3.4.1 hi-res games and reduces the number of games we may use for a test without importing and upgrading them in the new Editor.

So, on one hand we indeed decided to drop legacy stuff for now, on another hand there is this consideration that sometimes it may be convenient to test a game compiled by 3.4.1 (in case wip Editor is suspected to have bugs).

The proposal I'd like to make is to introduce the "room mask precision" property as a rightful feature in the AGS 4. I am honestly not sure whether memory or disk space may be an issue today, but perhaps this still may find uses in extreme and special cases.

If we presume such feature, then the engine could be allowed to do coordinate conversion between room and masks. Since currently mask bitmap is supposed to cover whole room, and there is one of type per room, then it is as simple as comparing room size and mask size. So, mathematically that would no issue. The only problem is to do this in a clean way, ideally there should be 1 function that does that, e.g. something like GetRoomMaskPixel(room_x, room_y).

In the future we could think about how to implement this "mask precision" choice in the editor (it stays 1:1 for now for all the compiled games).

What do you think about this?

**Comment by AlanDrake** [comment]
With #458 I did the quick fix I mentioned on discord.
Speaking of a "mask precision" property, I don't know. The only mask type that would actually benefit from that, are walkable areas due to pathfinding calculations.
All the other masks are best left 1:1.

How heavy is the pathfinder impact on high resolution games ?

**Comment by ivan-mogilko** [comment]
> How heavy is the pathfinder impact on high resolution games ?

I do not know in what terms to calculate such impact. Masks are 8-bit, hence 1 byte per (room) pixel. New A* pathfinder has its own grid, which adds memory usage, but probably not directly connected to mask's precision.

My primary intention was to add such concept to the engine, which would also give an easy compatibility support. Provided code is done well, it should not have any complexity added to the program overall.

**Comment by ivan-mogilko** [comment]
Anyway, with #458 the issue is temporarily solved, maybe we could return to the coordinate conversion idea after some refactoring is made in the room code?

**Comment by AlanDrake** [comment]
Yes, it's probably best to leave it until later.

**Comment by morganwillcock** [comment]
I think that character speed must be being scaled somewhere too, as building the master branch now has my character moving, but at (roughly) half speed.

**Comment by ivan-mogilko** [comment]
Only a guess, but if mask resolution has changed it also could have changed pathfinding or number of room pixels character walks each step.

If that's true, this means that when making the new games users would have to set different range of speeds for their characters from now on.

**Comment by AlanDrake** [comment]
It makes sense, the pathfinder has twice the pixels to travel now for high resolution games.
Movement speeds will need to be doubled to match the previous behaviour.
This was bound to happen since old AGS was built to allow the developer to switch from 320<->640, while having everything running mostly the same way.

Perhaps we could introduce a setRelativeMovementSpeed that scales according to resolution. Might come handy for game templates.

**Comment by morganwillcock** [comment]
If it is expected and the speed property is writable from a script, I'd be happy to just leave it as-is. I think scaling for higher resolutions already introduces various inconsistencies in the templates, and it will always be subjective as to whether what was changed was correct (potentially someone can argue that, if a character's speed has doubled, its sprites should now be twice the size).

**Comment by ivan-mogilko** [comment]
Hmm, 3.4.1 areas are still broken, and not only in Walkable areas but also in Walk-behinds.

The problem is that besides the mask size there are also few properties which coordinates are also given in lower coordinates it seems. This is probably Baseline for Walk-behind, and Top/Bottom line for Walkable areas. So these have to be multiplied also for 3.4.1 games to run correctly.
