### ISSUE TITLE
In 256-color games black color on GUI is sometimes rendered as transparent

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#461]
There is some bug in latest versions of AGS, causing black color on GUI elements become transparent.
This affects *Software renderer*. (Running with Direct3D/OpenGL renderers since 3.4.1 is rather a side-effect than an official feature, so we should not care about these for now.)

For example:
- Run ["Trilby's Notes"](http://www.adventuregamestudio.co.uk/site/games/game/736/), in the main menu choose "Quit". The confirmation dialog will have its font transparent instead of black (you may see background through).
- Run ["Heatwave"](http://www.adventuregamestudio.co.uk/site/games/game/1737/). Also, in the main menu click on "Quit". The confirmation dialog will have its font transparent instead of black.

Note, that "Heatwave" was made using AGS 3.3.0, and original Windows version does not have such bug. This means the mistake was introduced somewhere between 3.3.0 and 3.4.1.

**Comment by rofl0r** [comment]
> There is some bug in latest versions of AGS, causing black color on GUI elements become transparent

if you know this didn't happen in recent versions, `git bisect` can help you finding the bad commit that introduced the bug very quickly.

**Comment by ivan-mogilko** [comment]
This commit: aac4dfe7bc72eedd4626dc0e6ff86e018fcc7352

**Comment by ivan-mogilko** [comment]
Fixed with 1ac496c1de027f4a852a1c442128a7bb45aff967.

(one parameter was lost in between function calls)
