### ISSUE TITLE
Editor: saving script flushes Undo buffer

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#462]
Steps to reproduce (from user):
- Open an script (any script)
- change anything in it
- Do Ctrl+S
- As soon as the file gets saved, you cannot "Undo". All the undo steps get flushed.

I noticed that Undo tool button is active, but pressing it does nothing and it gets disabled afterwards.

**Comment by ivan-mogilko** [comment]
Following code might be related to the issue:

https://github.com/adventuregamestudio/ags/blob/master/Editor/scintilla/src/CellBuffer.h#L129
<pre>
/// The save point is a marker in the undo stack where the container has stated that
/// the buffer was saved. Undo and redo can move over the save point.
void SetSavePoint();
</pre>

**Comment by ivan-mogilko** [comment]
Nevermind above. I think I found what may be the cause of this problem

This is how Scintilla control determines whether Undo is allowed:
<pre>
case SCI_CANUNDO:
		return (pdoc->CanUndo() && !pdoc->IsReadOnly()) ? 1 : 0;
</pre>

Note the IsReadOnly() check.

Apparently Editor sets Scintilla in Read-only mode when it makes a save:
https://github.com/adventuregamestudio/ags/blob/ags3/Editor/AGS.Editor/Panes/ScintillaWrapper.cs#L468
<pre>
public void SetSavePoint()
{
    this.scintillaControl1.SetSavePoint();
    this.scintillaControl1.IsReadOnly = true;
}
</pre>
But does not unset it until certain actions (like typing).

**Comment by jeancallisti** [comment]
Hurray for your god-like efficiency!

**Comment by ivan-mogilko** [comment]
Well, there is still a question of how to fix this. Why does Editor put text control in the readonly mode anyway? Is it to protect it during game compilation process? If so, perhaps the proper solution is to put it back to writeable mode after all operations are completed.

**Comment by ivan-mogilko** [comment]
Hmm, "resolves" keyword failed for some reason. Anyway, this was fixed by #467.
