### ISSUE TITLE
Add Pre-Increment to AGS Script

### ISSUE THREAD

**Issue by CisBetter** [adventuregamestudio/ags#464]
I recently tried to use my standard for-loop design in AGS and discovered that
```c
for (int i; i < a; ++i)
{
  foo(bar);
}
```
produces the following error message:

 > GlobalScript.asc(3893): Error (line 3893): variable required on left of assignment ++ 

I am sure [pre-increment](https://en.wikipedia.org/wiki/Increment_and_decrement_operators) is not yet implemented in AGS.
As I use this increment as my standard increment (mainly because everyone else uses `a++`), I'd be very happy if this feature made its way into the AGS Engine :grinning:.

**Comment by fernewelten** [comment]
For an explanation of this phenomenon (in both the old and new compiler): 

Currently, `++` and `--` aren't implemented as possible expression operators. Instead, surprisingly, they are implemented as __assignment__ operators. For instance, take the source code `i++;`: The expression already ends with the `i`. The following `++` is treated as a shorthand for `+= 1`. 

So in your example, when you have `++i`, as the third component of a `for` loop, then the compilers will look for an expression in front of the `++`, not find anything at all and become unhappy. 

The new compiler will complain `Unexpected symbol '++'`, and I'm not really happy with that message. The old compiler's message is more understandable.

Nearer to programmer's expectations would be to re-define `++` and `--` as expression operators, in C or C++ or C# style. AFAICR, this is hard to do in the old compiler for technical reasons. The new one can probably do it without heavy changes. I'll have a look and report back.

**Comment by ivan-mogilko** [comment]
Was resolved by #1250
