### ISSUE TITLE
Support custom room viewport's location on screen

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#473]
There is a number of room-related tasks and issues in AGS that may be resolved if AGS supported distinct logical separation betwen room's and GUI's rendering.

For example, right now in AGS room background is supposed to be at least the size of game resolution. This means that if you want to have smaller rooms, you'd need to keep superflous strips on room background bitmap. One of the solutions seem to be drawing backgrounds with defined offset. While such ability might also come useful in some case, this does not automatically resolve other potential issues: this offset must be taken into account when scripting commands, characters and objects probably wanted to be clipped behind room borders, etc.

Another example is supporting scaling and rotating of whole room visually (without changing anything in room's coordinates). While it is task on its own, the first step it requires is internal separation of room's rendering, to be able to apply additional effects only to its content.

### The proposal:

1) Introduce separation between implicit game's viewport, which contains both room and GUI, and room viewport, which may have a different size and position on screen.
2) In Script API: add Viewport or RoomViewport struct and move viewport-related functions and properties there.
Viewport.X and Y tell where viewport is positioned *on screen*.
Viewport.RoomX and Viewport.RoomY tell the offset at which room is drawn inside the viewport.
**NOTE:** because we have Get/SetViewportX functions that get/set room's offset, we may instead make Viewport.X/Y do same, and invent another name for viewport's screen position.
Viewport.Width and Height become settable properties.
3) Add room properties, that allow to automatically adjust Viewport upon loading this room (set in the Editor).

### Possible complications:

The screen-room coordinate conversions, both in internal engine functions, and script functions, has to be adjusted and take viewport position into account.

Rendering system needs to correctly adjust position of the room contents and clip them. This may not be very difficult to code, but we have two separate types of renderers - software and texture-based - which handle sprite stack somewhat differently, so need to think of a good way to structure this.

We need to define what entities actually belong to the room and which not. For instance, where does Character speech go? May speech lines render outside the room viewport? (Note: personally I think yes)

Right now System.ViewportWidth/Height mean all the game's size and room's screen size at the same time (there is no separation between these two). Should it stay that way, or new properties introduced to tell full game's size?

**Comment by morganwillcock** [comment]
Would it be easier / just-as-good to:
 - make the background entirely optional (if you draw transparency onto an existing one, it already shows as black anyway)
- just use an object for the background, if you want it to be anywhere except the origin (I think traditionally the background was handled separately for performance reasons, but is there any situation where a sprite on an object wouldn't do the same thing?)
- masks are still applied directly to the room, so you don't have to clip anything or offset anything (maybe just have extra properties to offset all masks to match where the object is, i.e. Room.MaskX, Room.MaskY, but even without this, you will get the option to have the character walk outside of the 'room' for free)

**Comment by ivan-mogilko** [comment]
@morganwillcock all what you've mentioned may have its uses, but it won't have same effect as having a custom room viewport.

Viewport sets and limits the position of a room image on screen. With changeable viewport you could, for example, have a large scrollable room while only small portion of it is visible at once.

**Comment by ivan-mogilko** [comment]
@morganwillcock all what you've mentioned may have its uses, but it won't have same effect as having a custom room viewport.

Viewport sets and limits the position of a room image on screen. With changeable viewport you could, for example, have a large scrollable room while only small portion of it is visible at once in the center of the screen.

If only the room background is restricted, by allowing smaller background image, or object as a background, you still would have to clip characters and objects somehow, if you want them to be able to cross background's borders.

**Comment by ivan-mogilko** [comment]
Hmm, maybe I should elaborate a little more.
I would not like to say that having custom viewport is always the best solution for the aforementioned problem, neither that it is meant _only_ for that problem. It is one of the options, which also has extra uses.

This may be bit far-fetched, but in perspective, if AGS will ever be able to load and run multiple rooms at the same time, having distinct room viewport thing will allow to show multiple rooms on screen in separate "windows".

**Comment by morganwillcock** [comment]
From the perspective of multiple rooms, that does sound very useful. Perhaps it would be better to rebrand the feature as a 'camera', so people would understand that a camera can be in a different room, or you can have multiple cameras within a single room. Then each camera updates a 'camera sprite', which you can just assign to an object (so you make your own viewing window). If you wanted to apply custom shaders or scaling effects, you may also want to do that per camera, or have a different cameras follow different objects/characters. Viewport could remain as the entire display, if you wanted to apply something to all camera displays in a single pass, or just assign a single camera directly.

I guess to sum up, I'd rather go for the most far fetched result if the end result is closer to an ideal design (so ignoring how the existing Viewport operates, for design purposes). I think in general most 2D engines are dropping software rendering because of the performance issues when scaling for HiDPI displays, so it wouldn't be out of the question to just assume the use of a GPU and design it with that in mind.

**Comment by AleWin32** [comment]
Hi @ivan-mogilko, take a look at my post please, i reported this 4 years ago:
[](http://www.adventuregamestudio.co.uk/forums/index.php?issue=631.0)

So, are we talking about exactly the same desired functionality? Thanks

**Comment by ivan-mogilko** [comment]
@AleWin32 , yes, I was refering to your post. Actually, we were just talking on forums about this today.

**Comment by messengerbag** [comment]
While I admire the initiative, to me the whole thing seems like a lot of work and added complexity to fix something that is not really an issue in the first place.

(1) Black frames add very little to the size of the backgrounds because of run-length encoding. 
(2) If your GUI takes up fixed screenspace, and you redesign it to some other dimensions, it will usually not only affect the playable room area's _offset_ on the screen, but the _size_ as well. So in most cases you'll have to edit each room anyway.
(3) Multiple viewports on screen simultaneously is a cool idea, but not relevant for 99.9% of AGS games. Someone who wanted that could probably fake it or implement it themselves.

For the third point, I think a more generally useful solution would be an API to draw walkable areas, regions and hotspots via game script. You could then script your own scrolling viewports in sections of the screen, as well as achieve a ton of other cool effects.

**Comment by ivan-mogilko** [comment]
@messengerbag , like I said, this feature is not meant solely to solve the mentioned problem.

If room viewport is separated, other things that could be done with are, for example, scaling and rotating of whole room image.

**Comment by ivan-mogilko** [comment]
@AleWin32 I was planning to look into this after I finish with couple of other tasks. My hopes were to add this to the next version. But since this project is not the only thing I am working on, it's hard to predict the time.

**Comment by ivan-mogilko** [comment]
@morganwillcock 
> From the perspective of multiple rooms, that does sound very useful. Perhaps it would be better to rebrand the feature as a 'camera', so people would understand that a camera can be in a different room, or you can have multiple cameras within a single room. Then each camera updates a 'camera sprite', which you can just assign to an object (so you make your own viewing window). If you wanted to apply custom shaders or scaling effects, you may also want to do that per camera, or have a different cameras follow different objects/characters. Viewport could remain as the entire display, if you wanted to apply something to all camera displays in a single pass, or just assign a single camera directly.

So, if we are going to split into Camera and Viewport, I may propose following *minimal* script interfaces for the start:

Camera interface:
<pre>
builtin managed struct Camera
{
	import attribute int X;
	import attribute int Y;
}

Camera *RoomCamera;
</pre>
This defines camera position inside the room. For the sake of theorising, in the future this may be extended with Room reference, Zoom, Rotation, Pivot (determines how the camera's view rectangle is aligned to X/Y), and so on.

Viewport interface:
<pre>
builtin managed struct Viewport
{
	import attribute int X;
	import attribute int Y;
	import attribute int Width;
	import attribute int Height;
	import attribute Camera *Camera;
}

Viewport *RoomViewport;
</pre>
This defines a screen rectangle where the selected camera is rendered.

**Comment by ivan-mogilko** [comment]
I usually don't do teasers, but this is just way too much fun:

![](https://i.imgur.com/Kum2M2b.gif)


Made using a *very crude prototype* with some hardcoded stuff, based on [this branch](https://github.com/ivan-mogilko/ags-refactoring/tree/ags3--spritebatchtransform).

Frankly that may take a while to optimize and make it work with all renderers (especially software one will definitely cause some pain).

**Comment by AleWin32** [comment]
Oh, that's great! Keep on that, thanks!

Can you explain the concept of camera and viewport? I will try to explain what i understand, correct me if i am wrong please.

Supposing a room of 1920x1080 in size, we can use a camera of 320x200 in size moving from upper left corner of it (x:0, y:0) to the end of the right side (x:1600, y:0), so if our game has a total resolution of 960x480 we will see in the upper left corner (if the viewport is x:0, y:0) an image of 320x200 showing a panning in the room from left to right.

**Comment by ivan-mogilko** [comment]
> Supposing a room of 1920x1080 in size, we can use a camera of 320x200 in size moving from upper left corner of it (x:0, y:0) to the end of the right side (x:1600, y:0), so if our game has a total resolution of 960x480 we will see in the upper left corner (if the viewport is x:0, y:0) an image of 320x200 showing a panning in the room from left to right.

Yes, and this is how it already works in AGS, only viewport and camera concepts are currently merged and viewport always takes whole screen.

**Comment by ivan-mogilko** [comment]
I got it practically working, sans some optimisation may still be needed for software renderer.
Soon will be cleaning my wip branch and preparing proper pull request.

Wip branch is still: https://github.com/ivan-mogilko/ags-refactoring/tree/ags3--roomviewport
The windows build of the editor and engine may be downloaded here:
https://www.dropbox.com/s/ecc5ldzi1dqvc5k/ags-3.5.0--roomviewport-wip4.zip?dl=0
(it has to be copied over real installation of AGS)

Latest script API looks like this:
<pre>
builtin managed struct Camera
{
  /// Gets/sets the X position of this camera in the room.
  import attribute int X;
  /// Gets/sets the Y position of this camera in the room.
  import attribute int Y;
  /// Gets/sets the camera's capture width in room coordinates.
  import attribute int Width;
  /// Gets/sets the camera's capture height in room coordinates.
  import attribute int Height;
  /// Gets/sets this camera's room horizontal scaling relative to the viewport it is displayed in.
  import attribute float ScaleX;
  /// Gets/sets this camera's room vertical scaling relative to the viewport it is displayed in.
  import attribute float ScaleY;

  /// Gets/sets whether this camera will follow the player character automatically.
  import attribute bool Auto;
};

builtin managed struct Viewport
{
  /// Gets/sets the X position on the screen where this viewport is located.
  import attribute int X;
  /// Gets/sets the Y position on the screen where this viewport is located.
  import attribute int Y;
  /// Gets/sets the viewport's width in screen coordinates.
  import attribute int Width;
  /// Gets/sets the viewport's height in screen coordinates.
  import attribute int Height;
  /// Gets the room camera displayed in this viewport.
  import readonly attribute Camera *Camera;
};
</pre>

Viewport is accessible as Game.RoomViewport, and Camera as Room.Camera.
Camera size may be determined either by explicitly setting Width and Height or setting ScaleX and ScaleY properties to automatically adjust displayed room relative to the viewport's size.

I am open for the suggestions to improve anything in the above.

**Comment by ivan-mogilko** [comment]
> Do you think it would be possible to get the engine to implement smooth scrolling, so that as well as saying Room.Camera.Auto = true you could also set a camera tracking speed and a dead zone?

Perhaps as a separate task, right now the camera behavior is kept the same, only code refactored and new API added.

> especially since any existing script modules aren't going to be aware of the camera feature

Old functions like SetViewport and GetViewportX/Y are still working, editor allows to use them if backwards compatible switch is turned on, and engine is translating these calls to use new camera feature accordingly.

**Comment by ivan-mogilko** [comment]
Alright, so it's done in ags3 branch, the custom room viewport is supported, and AGS now allows to have rooms of any size starting with 1x1, which should close the original issue (having to add extra black borders to backgrounds of part of screen is constantly covered with GUI) as well.

There are few things that may be good to amend to this feature, but they may be dealt with as separate tasks.

**Comment by ivan-mogilko** [comment]
@morganwillcock , something reminded me of this old question of yours again:

> Do you think it would be possible to get the engine to implement smooth scrolling, so that as well as saying Room.Camera.Auto = true you could also set a camera tracking speed and a dead zone? I think this would be a pretty big deal if the engine could do this itself, rather than rely on script modules (especially since any existing script modules aren't going to be aware of the camera feature).

Recenly @eri0o posted this educational video on 2d game cameras, and there was this "camera trap box" feature explained: https://youtu.be/l9G6MNhfV7M?t=200

This made me think that it may be a more flexible approach to instead let camera target any character in the room, and then you could have script modules for "camera target" motion (relative to player for example) instead of having this in the camera itself.

**Comment by ericoporto** [comment]
This is how it works in the SmoothScroll module, you can select a target character, I know it sounds weird, but it really works well. After all, characters are prepared to exist accross Rooms. :)

I think about it and the problem in my mind is that the target character, if it's not the player, either he must be teleported on the room change, or the target character must become the player.
