### ISSUE TITLE
No way to access game menu and keyboard on the AGS Android App without menu button

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#474]
In some games a keyboard is required to play. In the AGS Android App, there is no way to access the keyboard in [tablets without home button as reported here](http://www.adventuregamestudio.co.uk/forums/index.php?topic=44768.msg636588597#msg636588597) .

The [suggested change](http://www.adventuregamestudio.co.uk/forums/index.php?topic=44768.msg636589972#msg636589972) is to alter the [AgsEngine.java](https://github.com/adventuregamestudio/ags/blob/master/Android/library/src/com/bigbluecup/android/AgsEngine.java) to use `engine.showInGameMenu();` on `onBackKeyPressed`. This opens openOptionsMenu. I think there is a confusion and the actual suggestion is to the Keyboard Toggle. 

note: Originally, long pressing home should `toggleKeyboard`. Unfortunately, on my phone home goes back to Android Home and long press of Home get's Google Assistant. I couldn't figure out what is the function `openOptionsMenu`.

**Comment by mim2011** [comment]
I think is about Menu button not Home button. 
For example my Samsung phone has (in the right order):

Menu (soft)button  - Home button - Back (soft)button

My Asus tablet has:

Back (soft)button - Home (soft)button - Tasks (soft)button

With soft I mean that there are no physical buttons but touch ones. The Home button is always for Android, as well the Tasks one. I don't think that you can use it from an App.

AGS works only with the Back and Menu buttons (AgsEngine.java).
My suggested change is to reassign the action engine.showInGameMenu() to the Back button because not all tablets have a Menu button
Thank you.

**Comment by ivan-mogilko** [comment]
Only wanted to add that it's possible to have an option in launcher/engine's preferences that switches the action (in case other devices need to keep original one).

**Comment by mortonharley** [comment]
Can soemone build me an apk with the following changes in AgsEngine.java ? I can't do it, since I am not on a linux system.

`public void onMenuKeyPressed(AgsEngine engine, boolean longPress)
		{
			if (longPress) engine.toggleKeyboard();
			else engine.showExitConfirmation();
		}
		
		public void onBackKeyPressed(AgsEngine engine, boolean longPress)
		{
			if (longPress) engine.showInGameMenu();
			else engine.keyboardEvent(KeyCode.KeyBackHardKey);
}`

**Comment by ivan-mogilko** [comment]
Since I am preparing an unplanned patch to v3.4.1 now I may as well look into implementing this suggestion (unless someone else makes a working pull request before that).

**Comment by ivan-mogilko** [comment]
Test build: https://www.dropbox.com/s/hq3a5ibzhos4x48/AGS-3.5.0-menu-on-backbtn.apk?dl=0
Built from branch: https://github.com/ivan-mogilko/ags-refactoring/tree/test--android-buttons

**Comment by mim2011** [comment]
thank you ivan,

i tried it and it is ok now, after long pressing the back button i got a menu with the option to activate the keyboard and to exit.

**Comment by ivan-mogilko** [comment]
Added in v.3.4.3.0 (and ags3 branch).
