### ISSUE TITLE
Resolve "feature-editor-drac" branch

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#479]
There is a very old "feature-editor-drac" branch in this repository, which contains some changes from @AlanDrake 's custom editor version. Should find out if there is anything that still need to be copied to the main (ags3 or ags4), then delete the branch.

**Comment by AlanDrake** [comment]
You can delete that old branch, if there's any feature missing we can use, it can be cherry picked from my draconian branch.

**Comment by sonneveld** [comment]
Deleted as requested by @AlanDrake , thank you!
