### ISSUE TITLE
API for drawing room masks

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#480]
Ability to edit room masks at runtime was asked for number of times in the past, and [mentioned again recently](https://github.com/adventuregamestudio/ags/issues/473#issuecomment-405184815).

Code-wise this should not be too hard to implement. We already have DrawingSurface API, and same could be used to draw on room mask, including painting a ready sprite.

Thinking of potential problems, I guess most important is to provide a function for getting proper drawing color corresponding to a mask. And restrict drawing to these colors regardless of game's color depth.
Worst case we'd have to check for every pixel of a painted sprite to make sure it stays in the range (or maybe we should not bother? wrong pixels will simply get ignored by the engine anyway).

Also, question is whether these modifications should be written into savegame. Right now modification of the room background is not saved, and script must redo it every time player enters the room. Maybe same could be done for masks, in the sake of consistency.
(Then again, it is possible to have these changes in savegame too, as a bonus feature)

Probably this won't require any critical change to the code, and thus is possible to do in AGS 3 branch as well.

**Comment by messengerbag** [comment]
Brilliant!

Yeah, a function to get a DrawingSurface for each mask would be sufficient, along with – as you say – a way to find the correct drawing color. I sort of assumed that it would simply be the AGS color number.

I don't think including it in the savegame (or even when you leave a room) is necessary, if it would complicate the task. It's easy enough to handle in script.

**Comment by ivan-mogilko** [comment]
@messengerbag First experiment was successful.

https://github.com/ivan-mogilko/ags-refactoring/commits/dev--drawroommasks

Compiled test game: https://www.dropbox.com/s/tktylmrqri4a6ez/RoomMaskDrawing.zip?dl=0

**Comment by ivan-mogilko** [comment]
Done, #1031
