### ISSUE TITLE
[Linux] Fails to build against glibc 2.28 due to conflicting function definitions in Allegro headers.

### ISSUE THREAD

**Issue by jspatz** [adventuregamestudio/ags#487]
Allegro 4 includes a number of math functions that conflict with functions defined in certain implementations of libc.  The [Allegro developers were aware of the problem](https://liballeg.org/stabledocs/en/alleg042.html), and renamed the functions in order to avoid the problem, but also implemented aliases for backward compatibility that still conflict, and need to be manually disabled by defining ALLEGRO_NO_FIX_ALIASES in your own source.

This hasn't been an issue with gcc/glibc on Linux until now -- the alias definitions are now conflicting with math functions defined in glibc 2.28 (which was pushed out to the Arch repos about a week ago).  I was able to get AGS 3.4.1.14 to build properly by defining ALLEGRO_NO_FIX_ALIASES and correspondingly renaming the function calls in a couple of source files (`Common/libsrc/aastr-0.1.1/AAROT.c` and `Engine/ac/route_finder.cpp`).  Everything seems to be working fine -- I've been playing Wadjet Eye's _Unavowed_ with this build of the engine with no noticeable issues.

Since I was trying to build the release version, I created a manual diff against the source in the tarball (in order to apply it as a patch in the PKGBUILD script for Arch) instead of creating a patch with Git, but if would be helpful, I can do the same thing against the Git master and submit a pull request within a couple of days.

**Comment by ivan-mogilko** [comment]
> Since I was trying to build the release version, I created a manual diff against the source in the tarball (in order to apply it as a patch in the PKGBUILD script for Arch) instead of creating a patch with Git, but if would be helpful, I can do the same thing against the Git master and submit a pull request within a couple of days.

Could you do a PR against "ags3" branch instead? We broke backwards compatibility in master, but ags3 branch still retains all functionality to run whole range of versions, so having this fix there would be useful (ags3 may then in turn be merged to master, we do this regularly).

**Comment by jspatz** [comment]
No problem.  Pull request #488 submitted.

**Comment by ivan-mogilko** [comment]
Was fixed by 44d9544 and ammended with 575db9426239d37e3e6692c7e1848554cb9902f9 and 837add19c533c2bb3e384d9e6551a97942e55d7b.
