### ISSUE TITLE
Possible problem with data format version in AGS 4

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#491]
Once in the past I've mentioned a possible problem that may happen if we have two or more versions developed or maintained at the same time. Back then this was related to 3.3.* branch and newer 3.4.0.
Since all of the data formats in AGS are defined as numbers which usually go in one sequence it becomes actual issue if we modify this format in older version during some update.

In the past this led to numerous frustrating moments when I had to delay adding new feature until next major version because did not want to break the format number sequence.
Then we made a decision to keep development cycles short to avoid such problems, and that kind of worked for some time.

Now we seem to have this issue back, since there is development of AGS 3 that still continues and perhaps will continue for some time (maybe until one final major version is released), and we have split AGS 4 of, which may have its own (and big) format changes.

For the reference there was this forum thread I started few years ago: http://www.adventuregamestudio.co.uk/forums/index.php?topic=52555.0
In that thread I was discussing an idea of replacing simple numeric sequence with a set of string IDs that define features or group of features.

But that could be an overkill in our case. The simpliest solution that comes to mind is to rise all format indexes in AGS 4 by a very big number, like 1000. This will ensure proper order of versions: if we add new format index in AGS 3 it will always be smaller than the one in AGS 4.

**Comment by AlanDrake** [comment]
Or change the savegame signature

**Comment by ivan-mogilko** [comment]
> Or change the savegame signature

But this will make it harder to keep track of all the formats. If someone wants to write unified data parser, instead of only testing for a version they would have to test pairs of signatures and versions, while differences in format may be smallish.

**Comment by ivan-mogilko** [comment]
EDIT: hmm, actually I will think about that...

**Comment by ivan-mogilko** [comment]
> Or change the savegame signature

Are you replying to #494?
Imho not the signature but the main savegame version perhaps. The signature is meant to determine the general format structure, which did not change.

**Comment by AlanDrake** [comment]
I was just considering that the format was likely to change so I didn't know if it made sense attempting to read the saves with the current signature. Upping all the component versions is the same, except you need to change more places.

**Comment by ivan-mogilko** [comment]
Oh, I see what you mean now.

**Comment by ivan-mogilko** [comment]
This is a useless ticket now, so closing it.

As a final thought on topic, regarding format version itself, there is always an issue with parallel development in two or more versions. Perhaps the proper and simple solution is to have format number consisting of several components matching program version number. It may even have an arbitrary string component meaning "program name" to distinct our formats from versions made by other teams or custom versions.
But this is something that have to be implemented systematically, and for all format numbers in program.
