### ISSUE TITLE
AGS3 doesn't build in Linux. Missing include in spritecache.cpp?

### ISSUE THREAD

**Issue by eriktorbjorn** [adventuregamestudio/ags#504]
I'm trying to build the latest git version of AGS3 under Linux, and I get the following error:

```
../Common/ac/spritecache.o
../Common/ac/spritecache.cpp: In member function ‘void SpriteCache::RemoveOldest()’:
../Common/ac/spritecache.cpp:271:13: error: ‘sprintf’ was not declared in this scope
             sprintf(msgg, "SpriteCache::removeOldest: Attempted to remove sprite %d that does not exist", sprnum);
             ^~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:46: ../Common/ac/spritecache.o] Error 1
```

I'm guessing the solution is to simply add #include <stdio.h> to spritecache.cpp?

**Comment by ivan-mogilko** [comment]
> I'm guessing the solution is to simply add #include <stdio.h> to spritecache.cpp?
Right, I was cleaning some code lately and probably thought its not needed.
But I'd rather replace sprintf with our String class there.

**Comment by ivan-mogilko** [comment]
I think this should do: e48ee06e4e88f906b552905a525570d0361107b9

**Comment by eriktorbjorn** [comment]
Yup, it compiles again. Thanks for the very quick reply!
