### ISSUE TITLE
AGS 3/4 question: is separate format index for each savegame component good?

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#506]
Some time ago I did a new savegame format. There I have broken the data into "components" sections. Which was good on its own for organizing data, but I also added separate "format version" index for each component.

Now recently it began to bug me that I could have done a big mistake. First of all, what is the benefit of having separate versions for components? This would be advantageous if we expect files to have different combinations of versions of components in them. With the AGS savegames this does not seem to be the case: for each version of the engine there is only one combination of data in the savegame. This makes the necessity of these multiple versions questionable.

*(On contrary, in theory the game data may be present in different versions, like some rooms may be of different versions if they were added into package without recompiling)*

On the other hand having multiple format indexes - one for each part of savegame - has disadvantages. These are not critical, but may become annoying:

1. Technical issue: even though engine is capable to test whether it can read a component of given version, it cannot do this beforehand (to prevent game quit/restart) since component version is found in the middle of the file. This may be solved by adding some kind of quick reference or table of contents in the file header. Such TOC may also be helpful on its own if someone writes a parser to extract only particular data (something I was considering to do at first but haven't for some reason), but of course it does not justify component versions.

2. Psychological/usability issue: if there is only one data version for all the savegame, then developers/contributors would know to simply raise it whenever they change something in savegame (which may already be an issue; I remember couple of custom engines where authors did not even consider changing data version at all). When there are separate versions for every component one needs to find out what component they are changing and raise that particular component's version.

I would like to know other developers opinion on this, because I feel that sometimes overthink a problem of overcomplicate the solution (in the past I was working on a complex software with lots of data formats we had to maintain, so that may have an effect on me now).

The latest WIP engine was already tested and used a bit, but there were no "final" releases yet, so this save format has not "cemented". In theory I could leave the component version field as reserved for the time being and use and rely on the main save version everywhere.

**Comment by tzachshabtay** [comment]
I think different versions per components have more advantages:
1. If Developer on branch A and developer on branch B both change a different component format they don't have to sync with one another. Each can work on her/his own component, and meanwhile people can use the branches and their savegames will work eventually when merged to master.
2. This allows the potential future feature of delegating saving specific components to plugins.

**Comment by ivan-mogilko** [comment]
> 1. If Developer on branch A and developer on branch B both change a different component format they don't have to sync with one another. Each can work on her/his own component, and meanwhile people can use the branches and their savegames will work eventually when merged to master.

Feature branches are not supposed to be used in actual games, only merged release. Described approach would mean we'd have to keep support of temporary data format variant found in feature branches and custom experimental branches. Also, imho the described situation is a "fortunate" subset of bigger problem of version conflicts, which I described [here](http://www.adventuregamestudio.co.uk/forums/index.php?topic=52555.0).

> 2. This allows the potential future feature of delegating saving specific components to plugins.

But does it really matter whether plugin will receive a component version or "overall" version? If engine can handle this, plugin should be able to also.

**Comment by ivan-mogilko** [comment]
I delayed this for too long, but some decision has to be made in regards to this.

Right now my main concern is this:
> Technical issue: even though engine is capable to test whether it can read a component of given version, it cannot do this beforehand (to prevent game quit/restart) since component version is found in the middle of the file.

Why is this a problem: the default implementation of restore game dialog in AGS checks save files for compatibility and displays "invalid slot" instead of incompatible file. AGS also provides means for user to make similar test if they are scripting their own save/restore dialogs (e.g. using GetSaveSlotDescription, which returns null if save slot is either missing or erroneous/incompatible).
With the current system unsupported saves cannot be detected beforehand anymore and may cause annoyance for players who would occasionally try to load such save and crash the game.

Yes, well, this is a rare occasion because it assumes that game was updated using next version of AGS (major or minor) where saves have an updated format as well, but this still irritates me.

So, since the save format was kept anyway since I first asked this question, I currently see two possible solutions:
* increase global format version also when component versions are increased;
* introduce TOC at the format header which lists data partitions, their offsets, and their respective versions; but in such case engine would have to run through this TOC each time when testing a save file, which could be relatively much slower compared to e.g. description extraction right now (may have some impact if there's a tonn of save files in directory).

**Comment by rofl0r** [comment]
> In theory I could leave the component version field as reserved for the time being and use and rely on the main save version everywhere.

that sounds like a wise choice

**Comment by ivan-mogilko** [comment]
> > In theory I could leave the component version field as reserved for the time being and use and rely on the main save version everywhere.

> that sounds like a wise choice

Unfortunately, it may be a bit late for that, because when reading saved data functions check their own component versions, and these changed few times in the past year.

**Comment by ivan-mogilko** [comment]
On the other hand I could just do what I wrote in the more recent comment:
> increase global format version also when component versions are increased;

This will keep save system using component versions internally, but for external "viewer" there will be global format version; thus sort of a mixed solution.

**Comment by ivan-mogilko** [comment]
I went ahead with the above decision (increased global format index), so I will remove the ticket from 3.5.0 milestone, but still keep it open for now because the issue still will require attention in the future IMHO.

**Comment by ivan-mogilko** [comment]
Ok, maybe not... if there's an issue with this in future, new ticket may be opened.
