### ISSUE TITLE
Malformed patch when building libraries

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#508]
When running `make install` in buildlibs.

```
cd /Users/mwillcock/Build/ags/OSX/buildlibs/build/allegro-4.4.2 && \
		patch -p1 < /Users/mwillcock/Build/ags/OSX/buildlibs/../patches/allegro-4.4.2.patch && \
		mkdir -p build && \
		pushd build && \
		cmake \
		'-DCMAKE_OSX_ARCHITECTURES=x86_64;i386' \
		-D CMAKE_OSX_DEPLOYMENT_TARGET=10.7 \
		-D SHARED=off \
		-D WANT_ALLEGROGL=off -D WANT_LOADPNG=off -D WANT_LOGG=off -D WANT_JPGALLEG=off -D WANT_EXAMPLES=off -D WANT_TOOLS=off -D WANT_TESTS=off \
		-D WANT_DOCS=off \
		-D CMAKE_INSTALL_PREFIX=/Users/mwillcock/Build/ags/OSX/buildlibs/opt \
		-G Xcode .. && \
		xcodebuild -project ALLEGRO.xcodeproj -target ALL_BUILD -configuration Release && \
		xcodebuild -project ALLEGRO.xcodeproj -target install -configuration Release
patching file CMakeLists.txt
patching file addons/allegrogl/src/fontconv.c
patching file addons/jpgalleg/include/jpgalleg.h
patching file addons/loadpng/CHANGES.txt
patching file addons/loadpng/LICENSE.txt
patching file addons/loadpng/README.txt
patching file addons/loadpng/loadpng.c
patching file addons/loadpng/loadpng.h
patching file addons/loadpng/regpng.c
patching file addons/loadpng/savepng.c
patching file addons/logg/logg.c
patching file addons/logg/logg.h
patching file addons/logg/loggint.h
patching file addons/logg/play_ogg.c
patching file cmake/FileList.cmake
patching file cmake/FindTslib.cmake
patching file docs/src/allegro._tx
patching file docs/src/readme._tx
patching file examples/exkeys.c
patching file examples/extrans2.c
patching file include/allegro/base.h
patching file include/allegro/internal/alconfig.h
patching file include/allegro/platform/aintios.h
patching file include/allegro/platform/aintosx.h
patching file include/allegro/platform/alios.h
patching file include/allegro/platform/alioscfg.h
patching file include/allegro/platform/alosx.h
patching file include/allegro/platform/alunix.h
patching file include/allegro/platform/alunixac.h.cmake
patching file include/allegro/system.h
patching file misc/allegro-config.in
patching file misc/pkgreadme._tx
patching file setup/setup.c
patching file src/config.c
patching file src/digmid.c
patch: **** malformed patch at line 1874: diff --git a/src/ios/idrivers.c b/src/ios/idrivers.c
```

**Comment by colejd** [comment]
Did you ever figure this out?

**Comment by sonneveld** [comment]
My recent pull request should have fixed this: https://github.com/adventuregamestudio/ags/pull/667 Please try again if you have the time.

**Comment by colejd** [comment]
Ah! I just was picking apart another one of your repos. I'll give this a shot!

**Comment by colejd** [comment]
@sonneveld it seems that I cannot build from the latest master on the ags3 branch. It seems to be because the latest version of Xcode doesn't support compiling for i386; it fails when compiling Lua (`symbol(s) not found for architecture i386`). If you remove the i386 target from the buildlibs makefile and rebuild, Lua will build, but then you'll get the above error.

**Comment by sonneveld** [comment]
You could try commenting out lua from the makefile. I'm pretty sure it's not used in the mac builds.  I'm still rocking xcode 9.3.. I don't want to break my setup just yet :)

**Comment by colejd** [comment]
Hmm. I'm getting further, but still failing. Now when Allegro is built, I get this (among other output): 
```
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]

...

clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
```
From that and other output, it looks like we need to use libc++ in Allegro?

And I totally get not wanting to break your existing setup. I'm an iOS developer, so I typically have multiple installations of Xcode, which is something you can do if you download the .dmg directly from https://developer.apple.com/download/more/.

**Comment by sonneveld** [comment]
Sounds like I'll have to bite the bullet and install a newer xcode to debug this. Allegro does have some cpp code but it's platform specific (beos and ppc) so it shouldn't affect macos builds.

**Comment by 256colour** [comment]
Sorry to necro this - but the solution is to add two blank lines with a single whitespace in front, in your text editor above line 1874:

`
 
 
diff -Naur src/ios/idrivers.c src/ios/idrivers.c`

**Comment by ivan-mogilko** [comment]
What is the state of this problem?

**Comment by morganwillcock** [comment]
I don't think this is actually a supported way to build any more, it uses the wrong Allegro version. But I tried re-running it anyway and the script encounters a different error.

```cd /Users/mwillcock/Build/ags/OSX/buildlibs/../../libsrc && ./download.sh
allegro-4.4.2.tar.gz: OK
dumb-0.9.3.tar.gz: OK
libogg-1.3.2.tar.gz: OK
libtheora-20150828-gfbb2758.tar.bz2: OK
libtheora-20160525-g50df933.tar.bz2: OK
libtremor-20150108-r19427.tar.bz2: OK
libvorbis-1.3.5.tar.gz: OK
lua-5.1.5.tar.gz: OK
./checkenv.sh
mkdir -p /Users/mwillcock/Build/ags/OSX/buildlibs/opt
mkdir -p /Users/mwillcock/Build/ags/OSX/buildlibs/build
tar xf /Users/mwillcock/Build/ags/OSX/buildlibs/../../libsrc/lua-5.1.5.tar.gz -C /Users/mwillcock/Build/ags/OSX/buildlibs/build
cd /Users/mwillcock/Build/ags/OSX/buildlibs/build/lua-5.1.5 && \
                patch -p1 < /Users/mwillcock/Build/ags/OSX/buildlibs/../patches/lua-5.1.5.patch && \
                make macosx INSTALL_TOP="/Users/mwillcock/Build/ags/OSX/buildlibs/opt" PLAT_LDFLAGS="-mmacosx-version-min=10.7 -arch i386 -arch x86_64" PLAT_CFLAGS="-mmacosx-version-min=10.7 -arch i386 -arch x86_64" && \
                make install INSTALL_TOP="/Users/mwillcock/Build/ags/OSX/buildlibs/opt"
patching file src/Makefile
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make macosx
/Applications/Xcode.app/Contents/Developer/usr/bin/make all MYCFLAGS=-DLUA_USE_LINUX MYLIBS="-lreadline"
make[3]: Nothing to be done for `all'.
cd src && mkdir -p /Users/mwillcock/Build/ags/OSX/buildlibs/opt/bin /Users/mwillcock/Build/ags/OSX/buildlibs/opt/include /Users/mwillcock/Build/ags/OSX/buildlibs/opt/lib /Users/mwillcock/Build/ags/OSX/buildlibs/opt/man/man1 /Users/mwillcock/Build/ags/OSX/buildlibs/opt/share/lua/5.1 /Users/mwillcock/Build/ags/OSX/buildlibs/opt/lib/lua/5.1
cd src && install -p -m 0755 lua luac /Users/mwillcock/Build/ags/OSX/buildlibs/opt/bin
cd src && install -p -m 0644 lua.h luaconf.h lualib.h lauxlib.h ../etc/lua.hpp /Users/mwillcock/Build/ags/OSX/buildlibs/opt/include
cd src && install -p -m 0644 liblua.a /Users/mwillcock/Build/ags/OSX/buildlibs/opt/lib
cd doc && install -p -m 0644 lua.1 luac.1 /Users/mwillcock/Build/ags/OSX/buildlibs/opt/man/man1
tar xf /Users/mwillcock/Build/ags/OSX/buildlibs/../../libsrc/freetype-2.4.12.tar.bz2 -C /Users/mwillcock/Build/ags/OSX/buildlibs/build
tar: Error opening archive: Failed to open '/Users/mwillcock/Build/ags/OSX/buildlibs/../../libsrc/freetype-2.4.12.tar.bz2'
make: *** [freetype] Error 1
```

Maybe someone else will know if this script this library build process is still needed for anything, or would be fixable for building without CMake (but this script is already requiring CMake so that also seems a little redundant).

**Comment by rofl0r** [comment]
freetype is now included in the source tree (Common/libsrc), so this at least could be easily fixed.

**Comment by ivan-mogilko** [comment]
@morganwillcock , @vga-256 i'm sorry to nudge you, but I have couple of questions in regards to this ticket:

1) was this issue resolved at some point at all, or still no?
2) is this still applicable to the recent version (sdl2-based); and if not
3) is there still interest in ensuring this works in release-3.5.1 branch? as I theoretically would like to still support 3.5.1 branch for some time, while 3.6.0 is in tryout (and numerous game developers are likely still using 3.5.* versions to make games).

Unfortunately I rarely try osx port, so keep forgetting, if this "buildlibs" folder and scripts in it are still in use?

On a side note, I noticed that OSX readme was not updated for 3.6.0 yet, as it still mentions that the engine is based on a *"modified Allegro 4 library"*

**Comment by morganwillcock** [comment]
For 3.5 on macOS I think I've only ever built it with CMake. I don't think there was another way to build it that worked and I don't know of anyone testing any other type of build. So if you wanted to document how to build the 3.5 branch on macOS I think it would have to be how to build using CMake.

(and if I trust my previous comment, the script requires CMake so avoiding CMake isn't an option)

**Comment by ivan-mogilko** [comment]
After [3.6.0](https://github.com/adventuregamestudio/ags/releases/tag/v.3.6.0.47) is released with SDL2 backend, I believe this is no longer significant.
