### ISSUE TITLE
trilby art of theft crashes/shuts down with 3.4.1.15

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#512]
after unlocking level 4, in the level where you have to hit Z and X real fast, sometimes this happens:
```
Game GUI version: 115
An error has occurred. Please contact the game author for support, as this is likely to be a scripting error and not a bug in AGS.
(ACI version 3.4.1.15)

in "Room script", line 453

Error: Object.SetPosition: cannot set position while object is moving
```

and in the mission select screen, sometimes this happens when scrolling rapidly upwards through the missions:
```
Game GUI version: 115
An error has occurred. Please contact the game author for support, as this is likely to be a scripting error and not a bug in AGS.
(ACI version 3.4.1.15)

in "Room script", line 22
from "Room script", line 613

Error: Object.SetPosition: cannot set position while object is moving
```
even though the engine suggests it's a bug in the game, it looks more like an engine bug to me.

**Comment by ivan-mogilko** [comment]
Might be that engine logic changed since too, we had number of similar issues in the past.
Do you have any savegame close to that location?

**Comment by rofl0r** [comment]
yes, https://0x0.st/s3hc.xz . i think the 2nd one is the right one, but the issue can easily be reproduced by going rapidly through the mission selection with the up key.

**Comment by rofl0r** [comment]
re: the error message `Object.SetPosition: cannot set position while object is moving`:

after making sure that there's not another bug/regression in the engine leading to this, i would recommend to make this "error" non-fatal, and only not execute Object.Setposition for the requested object in that situation.

**Comment by ivan-mogilko** [comment]
> after making sure that there's not another bug/regression in the engine leading to this, i would recommend to make this "error" non-fatal, and only not execute Object.Setposition for the requested object in that situation.

Making it non-fatal in any case might be a right thing. I had a guess these fatal errors were introduced mainly as a way to bring developers attention to an unexpected behavior, but practice shows that this rather annoys them. Recently we replaced couple of similar errors with warnings to log.
