### ISSUE TITLE
Replace "fatal errors" in script functions to warnings

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#517]
There is a number of cases when AGS throws fatal error and closes the game in case the script function cannot perform expected action. I have a guess that this was the way to bring developer's attention to logical errors in their scripts, but this may be undesired to have in a released game.

I suggest to examine all fatal error throws ( **quit** and **quitprintf** calls ) in script functions and replace them with **debug_script_warn** calls. That function prints a warning text indicating current script location into the special log that is created only in "debug" mode. After that the potential future addition could be a signal sent to the connected Editor that breaks execution at that point to let developer examine error with callstack etc.

Of course in particular cases the error/warning may be completely removed if it seems unreasonable and there are no actual consequences, e.g.  error in GUI.SetSize when user sets size larger than the screen.

**Comment by ivan-mogilko** [comment]
Closed in favor of #1488 (extended task)
