### ISSUE TITLE
Segfault when launching in a window, with gfxfilter scale set to 0

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#519]
<pre>./102jam --windowed --gfxfilter none 0
Adventure Game Studio v3.4 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2018 others
ACI version 3.4.1.15

Initializing allegro
Initializing game data
Located game data file: /home/mwillcock/.config/itch/apps/in-bloom/data/102jam.ags
Opened game data file: game28.dta
Game data version: 49
Compiled with: 3.4.1.14
Setting up game configuration
Logging scipt to "warnings.log"
Setting up window
Initializing TTF renderer
Initializing mouse: number of buttons reported is 3
Checking memory
Data directory: /home/mwillcock/.config/itch/apps/in-bloom/data
Audio vox found and initialized.
Initializing keyboard
Install timer
Sound settings: digital driver ID: 'Auto' (0xffffffff), MIDI driver ID: 'Auto' (0xffffffff)

Unable to initialize your audio hardware.
[Problem: /dev/sequencer: No such file or directory]
Installed digital driver ID: 'ALSA' (0x414c5341), MIDI driver ID: 'None' (0x0)
Install exit handler
Initialize path finder library
Game GUI version: 118
Requested script API: v3.4.1 (5), compat level: v3.4.1 (5)
Game title: 'In Bloom'
Checking for disk space
Initializing MOD/XM player
Game native resolution: 320 x 240 (32 bit)
Game settings: windowed = yes, screen def: scaling, screen size: 0 x 0, match device ratio: ignore, game scale: 0
Shutting down Allegro due to signal #11
Segmentation fault</pre>

**Comment by ivan-mogilko** [comment]
The crash should be fixed with 192cc842e85d59152b0ea51d709fe81cf1eff7ad.
(The error appeared to be completely irrelevant to the setup option)

Also, 7c51f499a9e97ff73338d25718a80e98a368ff51 fallbacks to default scaling if it has invalid configuration.
