### ISSUE TITLE
Editor: exception when trying to create a room template

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#540]
For some reason this error only occurs when you are trying to create a room template in a freshly created new game.

1. Launch AGS and select "Start new game". Choose any template that _already has rooms_ (not Empty template), and proceed setting up game name and so forth.
2. As soon as the game is open, open "Rooms" node in the project tree, *do not double click on the room* but instead right-click on existing room to bring up context menu and choose "Create template from room..."
3. Observe exception.

The NullReference exception is thrown at the following line:
https://github.com/adventuregamestudio/ags/blob/ags3/Editor/AGS.Editor/Components/RoomsComponent.cs#L241
because _roomSettings reference is null.

**Comment by ivan-mogilko** [comment]
> It seems to be related to the user data for the room not being there, so for an existing project you can get the problem back by deleting 'room1.crm.user'.

This did not reproduce for me, was there anything else besides deleting *.user file and was the error stack the same?

The error is simply related to the incorrect conditions around the place, it first tests whether room is loaded and then assumes that the document pane should be existing as well without checking. But when the new game is created the room is loaded without opening a pane, probably for compilation.

For that reason you can also reproduce this error if you do following:
1. Open existing project, dont touch anything yet.
2. Do Build -> Rebuild all files (all rooms will be recompiled).
3. Now try to create a room template before actually opening a room in the editor.

**Comment by morganwillcock** [comment]
I think I must have changed something else as well, you are right, checking again deleting that file doesn't make a difference.

**Comment by morganwillcock** [comment]
Would it just be changing
<pre>if (!SaveRoomAlwaysAndShowErrors(_loadedRoom, _roomSettings.Control as RoomSettingsEditor))
{
    return;
}</pre>
to
<pre>if (!SaveRoomOnlyGameDataAndShowErrors(_loadedRoom))
{
    return;
}</pre>
?

**Comment by ivan-mogilko** [comment]
@morganwillcock ,
> Would it just be changing
something like that, perhaps just passing null if roomSettings is not allocated. The SaveRoomOnlyGameDataAndShowErrors function itself makes null checks so that should be safe.

**Comment by ivan-mogilko** [comment]
Should be fixed with 0339e605937f2a6daca7a5a1f702520f56701eb2
