### ISSUE TITLE
Store Native.dll in git

### ISSUE THREAD

**Issue by alkhimey** [adventuregamestudio/ags#546]
If I want to build AGS.Editor.NoNative, I must find Native.dll and put it into References folder. The suggested way is to get it from the installed game.

This will probably not work well if the version in the installed game is not compatible. And even without any problems this step adds complexity and additional thing to do before I can build the Editor for the first time.

So why not store a "tested to be working with the code in this commit" Native.dll file along with the sources inside this repository?

This suggestion is relevant for any external dependency that the licensing cat permit this. When I read that I need to build and patch lib-alfont and friends, it was really a turnoff for wanting to try to contribute something for this project :(

**Comment by alkhimey** [comment]
@ivan-mogilko I don't want to use it because of the dependencies that it requires. The file size is a fair point though.

**Comment by ivan-mogilko** [comment]
Hopefully this will be solved with automatic building (#531)

For now I uploaded AGS.Native.dll built for three recent branches (release-3.4.1, ags3 and master):
https://www.dropbox.com/s/67wxgtyvkj1eek7/AGS.Native.zip?dl=0

**Comment by ivan-mogilko** [comment]
We have automatic building now, which artifacts may be found here:
https://cirrus-ci.com/github/adventuregamestudio/ags
