### ISSUE TITLE
Get/Set Delay of an animation while animating

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#561]
No idea how possible it is to change the delay of an animation of an object/character/button/etc at runtime but reading it out should easily be possible.

**Comment by ivan-mogilko** [comment]
As one random idea to consider, we could make Animate functions return "animation" object which would contain control properties.

**Comment by selmiak** [comment]
if these can be manipulated while animating this could be really helpful.

**Comment by ivan-mogilko** [comment]
As a random idea to consider, we could make Animate function return a kind of "animation" object that would contain all necessary control properties. Additionally, have "CurrentAnimation" property in a character/object.

**Comment by ivan-mogilko** [comment]
Closing this in favor of #2010.
