### ISSUE TITLE
cChar.Say autocompletes to cChar.Say("");

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#562]
would ease this up a lot! :)

bonus points when the cursor then is already inside the ("") for easy typing and no navigating.

**Comment by ivan-mogilko** [comment]
I will close this as not planned. As I commented previously, in my opinion, there should not be a task to add such behavior to a particular script function, but instead a autocomplete/autoformatting feature in the script editor which may be configured to user's needs.

Also see #2016.
