### ISSUE TITLE
Sprites: show SourceFile name aligned to the right, so you can instantly see the name of the file and the extension

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#563]
hovering over the SourceFileName shows the complete path, but mostly I'm interested in the file name and the bigger the project gets chances are the file is deep in some folder structure where the name is pushed very far to the right an invisible when quickly looking there. IT IS VISIBLE when hovering over the SourceFileName field, but when the displayed text (path) is aligned to the right inside that field the filename is always visible at once.
also aligning the hovering display to the right end of the field too should/would not display outside of the editor window when using it in windowed (and not fullscreen)

Same for audio files. Though not as relevant as the name is mostly the same as the ingame name.

**Comment by ivan-mogilko** [comment]
I wish this was discussed back when this was opened.
I don't think the Properties grid control that we used would allow something like this easily. I also doubt that it's good to change the default behavior of these fields, as different users may have different intent about them (and they may change depending on a situation).

@selmiak do you recall why did you need this? What was the use case (the purpose) of seeing the rightmost part of a sprite's filename?

**Comment by selmiak** [comment]
it is not a problem but a feature to make using AGS easier. 
I need this to instantly see the filename in a long and nested folder structure. For animations that have 01.png 02.png and so on this is useful, and they all look alike as it is an animation.
My take is, that this is mostly useless when it only displays the start of the filepath, that is always the same for all files, so aligning the name to the right makes it useful. Quicker for the user. I have no idea when you'd need the drive letter and some folders in a field for the actual filename. as the name implies it should indeed show the filename and make it easy for the user.

**Comment by ivan-mogilko** [comment]
> I need this to instantly see the filename in a long and nested folder structure. For animations that have 01.png 02.png and so on this is useful, and they all look alike as it is an animation.

I was asking, why do you need to see that, what is the exact use for knowing the filenames?

**Comment by ivan-mogilko** [comment]
@selmiak , for instance, will it work, if the filenames were displayed under the sprites themselves?

![sprites-with-names](https://github.com/adventuregamestudio/ags/assets/1833754/13570274-0bc1-4353-b4d1-9156649fadd7)

**Comment by selmiak** [comment]
You mean only the filename is displayed without the whole path? Yes, that would be very much what I mean.
But the filenamepath of course is important to know as well, but the name of the file is more important. So when the display on the right in the properties still has the path on display while the files are displayed like this, this is a great solution.

**Comment by ivan-mogilko** [comment]
> please make sure, that when scaling DOWN the preview the whole(!) name is still there and not "btn_poin..." is displayed instead of "btn_pointer_normal.png" as of course the _normal or _pressed or so it what the game author wants to see instantly by just a quick look. I'd rather have weird linebreaks to fit the smaller width of the element while still displaying the complete long filename over cutting off the filename with "..." when scaling down the display!

I don't think that is possible, we don't have that kind of control over how ListView displays text. We'd probably need to rewrite how it draws items, which I am not going to do right now.
Seeing full name is still possible if you select the item.

**Comment by selmiak** [comment]
okay, thanks for letting me know. This issue can be marked as solved for now...
It probably works very well this way. If not I can open another issue later on. Thank you!

**Comment by ericoporto** [comment]
There is an alternative of renaming SourceFileName  to SourceFilePath and have SourceFileName in the properties display only the filename - if no change on the list view is desired.

**Comment by selmiak** [comment]
> 

having the filepath somewhere is also useful and having all the filenames visible at once is also useful, the change Crimson suggested is a pretty good fit.

**Comment by ivan-mogilko** [comment]
> There is an alternative of renaming SourceFileName to SourceFilePath and have SourceFileName in the properties display only the filename - if no change on the list view is desired.

I had this thought at first, but then I thought that the whole point of extracting a filename is to make it easily visible in connection to the sprite, and the easiest way to do this, it seems, is to place it right at the sprite.

Similarly, if this is necessary for AudioClips, the filename may be displayed somewhere on a label on the preview panel.

**Comment by ericoporto** [comment]
> I had this thought at first, but then I thought that the whole point of extracting a filename is to make it easily visible in connection to the sprite, and the easiest way to do this, it seems, is to place it right at the sprite.

I agree, just didn't had any idea of what to do when the sprite zoom is lower, because I like that on lower zoom, more sprites are visible (specially in folder with lots of sprites), so I didn't want to change anything in size there to show the full name.

**Comment by ivan-mogilko** [comment]
Sorry, I don't understand your point, are you saying that this should not be added to the item text? Or that it should not be added in the lower zoom?

**Comment by ericoporto** [comment]
Made an experiment that reduces slightly the font in the smaller zoom, not sure if it is a good idea. I am also fine with the way it currently is in the PR as it's possible to select the sprite to see the full name.

https://github.com/ericoporto/ags/commit/4eb8b3537306f31c56cd28b8eeefff1c7fac59d0

![image](https://github.com/adventuregamestudio/ags/assets/2244442/4541a79a-d6b0-40f6-8491-c261313afcf6)

**Comment by morganwillcock** [comment]
If this is a ListView, can it not be switched into a mode which lists the sprites in a vertical list? I think that would allow the full path to be displayed, one per line, with a smaller thumbnail.

**Comment by selmiak** [comment]
list view would be a very small sprite preview, not that I'd use that much, but maybe someone else needs exactly that.
that list view is what I would expect to happen when drawing the zoom slider to the smallest amount. or rather with a gap between smallest square view (and name below it) and then the list view. Where the slider first snaps to the smallest zoom level and you have to consciously move the mouse and slider a tad bit more to make it jump to list view. if that control is even possible with the framework stuff use for ags.

**Comment by ivan-mogilko** [comment]
I'd like to understand, there's still more changes wanted for this? In such case I will close my PR and let others do this, because I did not expect to spend more time on this.

**Comment by ivan-mogilko** [comment]
I'd like to know if the current PR is fine, or more changes are required. This started as a request to make sprite's filename easier to see, now there's conversation about how to change the list view looks. To be clear: I am not ready to work on larger changes, I meant only to provide a minimal solution for the original request.
If my PR is not enough, then I will close it and let other people work on this, whoever have spare time and wish.

**Comment by ivan-mogilko** [comment]
Alright, I merged and closed this, if other changes wanted please open a new feature request.

Something I like to recommend, is to always clearly mention **intent** of a propose change, because there may be other better ways to implement what you ask for.

**Comment by selmiak** [comment]
sure close this. The intent totally is part of the issue title though, sometimes it is not easy to tell but the discussion distilled that out and I'm looking forwards to this change :)
