### ISSUE TITLE
move template description to template selection

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#564]
and not after selecting the template.

**Comment by ivan-mogilko** [comment]
IIRC this means: display the description in the "select game template" window e.g. in a scrolling textbox, instead of displaying it after game is already created as a popup dialog.

This would require to preload template data, but I believe it's worth it because it's more convenient to get info about template's contents beforehand.

**Comment by jumpjack** [comment]
> IIRC this means: display the description in the "select game template" window e.g. in a scrolling textbox

I think a 2-3 lines description  inside a static label would be enough.

> This would require to preload template data

Probably it would be easier and faster to just hardcode the descriptions inside the editor and associate them to templates names.

**Comment by jumpjack** [comment]
I was talking only about templates distributed with AGS releases, I didn't even know it was possible to add custom templates.

**Comment by ivan-mogilko** [comment]
The template file in AGS is simply an archive containing game files. When the game is created the Editor unpacks the archive into the destination folder.

The template's description is at the moment supplied as a `template.txt` file. Right now, Editor will load text from that file after whole template is unpacked into the new game, and display on popup.

For implementing a preview, Editor would need to unpack just that one file from each found template instead, and "give" these texts to the template selection dialog.

**Comment by ericoporto** [comment]
This was fixed in ags4 by #1903, can be labeled as ags4 and closed.

**Comment by ivan-mogilko** [comment]
Weird, "Resolves" line did not work in pr.

**Comment by ericoporto** [comment]
Descriptions have been adjusted in https://github.com/adventuregamestudio/ags-template-source/pull/69 and the UI has been backported to AGS 3.6.2 too.
