### ISSUE TITLE
Audiofiles: Always Show Length in Player

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#567]
at the moment the length is only displayed when play is clicked.

ALSO: when clicking stop the position/ length is back to 0 / 0 and not 0 / length!

**Comment by selmiak** [comment]
I dare to say this one is a bug and not a suggestion, that's why I posted two different issues. position in the audio file in the player should be 0/length when not playing and not 0/0.

The suggestion is about showing the length in the properties of the audiofile too.

**Comment by morganwillcock** [comment]
For some reason the play / pause behaviour is different for MIDI files (the play/pause buttons work differently, although functionality seems the same), which I think is probably another bug in the same area.

**Comment by ivan-mogilko** [comment]
This was done in 3.5.0.
