### ISSUE TITLE
Android Menu Button Issue

### ISSUE THREAD

**Issue by mortonharley** [adventuregamestudio/ags#586]
Can soemone build me an apk with the following changes in AgsEngine.java ? I can't do it, since I am not on a linux system.

```
public void onMenuKeyPressed(AgsEngine engine, boolean longPress)
		{
			if (longPress) engine.toggleKeyboard();
			else engine.showExitConfirmation();
		}
		
		public void onBackKeyPressed(AgsEngine engine, boolean longPress)
		{
			if (longPress) engine.showInGameMenu();
			else engine.keyboardEvent(KeyCode.KeyBackHardKey);
}
```

**Comment by ericoporto** [comment]
You don't need to be in a Linux System to build Android AGS, just get [Android Studio](https://developer.android.com/studio/) and follow the instructions on it's [`README.md`](https://github.com/adventuregamestudio/ags/blob/master/Android/README.md).

You can get [the prebuilt engine on the forums](https://www.adventuregamestudio.co.uk/forums/index.php?topic=56452.0) if you have any trouble using NDK, so that you only need to edit the Java code on the Android Studio IDE.

**Comment by mortonharley** [comment]
After 5 hours of trying to build the apk, I am giving up for today. I am going from error to error in the build process. Will try from scratch tomorrow, if noone might help with a setup already established.

**Comment by ericoporto** [comment]
@mortonharley please show your errors, we can use that to improve the readme!

**Comment by ivan-mogilko** [comment]
The readme does not describe how to build with Android Studio.

**Comment by ericoporto** [comment]
damn, ok, I have a new computer now and downloading things is slow as hell, so it will take a while for me to build anything @mortonharley

**Comment by mortonharley** [comment]
The ndk-build process with precompiled libraries always fails. It seems, that it is due to unresolved imports regarding the assets.h. I will try again later and let you know the exact errors I am getting. Also tried building the app withount compiling the engine, using cmake to compile, but got no luck with that either, neither through ant or gradle directly.
Before trying to build the engine, I had to replace the used c++-compiler in android.mk because gnu seems to be no longer supported by ndk.

**Comment by ivan-mogilko** [comment]
@mortonharley please tell which branch you are building too.

**Comment by mortonharley** [comment]
I was trying the master branch.

This is the error ndk-build gives me

```
Android NDK: Found platform level in jni/../project.properties. Setting APP_PLATFORM to android-16.
Android NDK: WARNING:jni/../jni/Android.mk:agsengine: non-system libraries in linker flags: -lalleg -lfreetype -lvorbisidec -ltheora -logg -laldmb -ldumb
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
Android NDK: WARNING:jni/../jni/Android.mk:agslua: non-system libraries in linker flags: -llua
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
Android NDK: WARNING:jni/../jni/Android.mk:agsengine: non-system libraries in linker flags: -lalleg -lfreetype -lvorbisidec -ltheora -logg -laldmb -ldumb
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
Android NDK: WARNING:jni/../jni/Android.mk:agslua: non-system libraries in linker flags: -llua
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
[armeabi-v7a] Compile++ arm  : agsengine <= audiochannel.cpp
In file included from jni/../jni/../../../Engine/ac/audiochannel.cpp:16:
In file included from jni/../jni/../../../Engine\ac/gamestate.h:20:
In file included from jni/../jni/../../../Common\game/roomstruct.h:42:
In file included from jni/../jni/../../../Common\game/interactions.h:42:
In file included from jni/../jni/../../../Common\util/string_types.h:23:
In file included from jni/../jni/../../../Common\util/string.h:43:
jni/../jni/../../../Common\debug/assert.h:44:20: fatal error: expected unqualified-id
inline void assert(bool expr) {
                   ^
1 error generated.
make: *** [obj/local/armeabi-v7a/objs-debug/agsengine/ac/audiochannel.o] Error 1
```

I tried to fix that by defining debug in the code, which initself leads to the following error.

```
Android NDK: Found platform level in jni/../project.properties. Setting APP_PLATFORM to android-16.
Android NDK: WARNING:jni/../jni/Android.mk:agsengine: non-system libraries in linker flags: -lalleg -lfreetype -lvorbisidec -ltheora -logg -laldmb -ldumb
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
Android NDK: WARNING:jni/../jni/Android.mk:agslua: non-system libraries in linker flags: -llua
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
Android NDK: WARNING:jni/../jni/Android.mk:agsengine: non-system libraries in linker flags: -lalleg -lfreetype -lvorbisidec -ltheora -logg -laldmb -ldumb
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
Android NDK: WARNING:jni/../jni/Android.mk:agslua: non-system libraries in linker flags: -llua
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
[armeabi-v7a] Compile++ arm  : agsengine <= audiochannel.cpp
In file included from jni/../jni/../../../Engine/ac/audiochannel.cpp:16:
In file included from jni/../jni/../../../Engine\ac/gamestate.h:20:
In file included from jni/../jni/../../../Common\game/roomstruct.h:46:
jni/../jni/../../../Common\util/wgt2allg.h:30:10: fatal error: 'allegro.h' file not found
#include "allegro.h"
         ^~~~~~~~~~~
1 error generated.
make: *** [obj/local/armeabi-v7a/objs-debug/agsengine/ac/audiochannel.o] Error 1
```

If I go through the imports with intellisense, I see that there are some files, that can't be found

**Comment by mortonharley** [comment]
My suggestion would be that fututre bulds implement my change since there is a lack of menubuttons on modern devices and hence no way to use f-keys.

**Comment by mortonharley** [comment]
I give up, as this turns out to be more complicated than I thought, and I simply don't have the time to mess with all the issues I am facing. Again, I would really appreciate, if someone, who might already have setup all the library requirements, would provide me with a debug apk with said changes. Thank you for your help so far.

**Comment by ivan-mogilko** [comment]
@mortonharley , alright, it took some time because I had a complete reinstall of linux system recently, but I've set up everything required for Android build again (found few unobvious nuances are missing from our readme along the way). I may try building an APK with your variant of button code now.

**Comment by ivan-mogilko** [comment]
@mortonharley , here you go:
https://www.dropbox.com/s/hq3a5ibzhos4x48/AGS-3.5.0-menu-on-backbtn.apk?dl=0

I can see better how this all works now. I'd like to investigate how AGS java app works a bit more before making the code into the official engine though.

**Comment by mortonharley** [comment]
Thank you very much for the build. Sadly the longclick does not seem to work at all on modern phones. At least not on my 2 devices I have here. I will try to setup the dev environment again later this day and maybe have a look myself and try to debug. I have some experience in Android development but I fail to build the engine due to it's 3rd Party library requirements.

**Comment by mortonharley** [comment]
Following this So question edited in 2014: [here](https://stackoverflow.com/questions/3403465/android-long-key-press)

You should implement the longpress on buttons by overriding the standard:

```
@Override
public boolean onKeyLongPress(int keyCode, KeyEvent event) {
    if (keyCode == KeyEvent.KEYCODE_BACK) 
    {
        // do your stuff here
        return true;
    }
    return super.onKeyLongPress(keyCode, event);
}
```

**Comment by ivan-mogilko** [comment]
>  I have some experience in Android development but I fail to build the engine due to it's 3rd Party library requirements.

I have noted some missing info about building here: https://github.com/adventuregamestudio/ags/issues/587#issuecomment-457781099
(will add them to our README later)

I will also try to add these proposed longclick changes.

**Comment by ivan-mogilko** [comment]
I also found this, idk if related, but I will leave it here just in case: https://bugzilla.mozilla.org/show_bug.cgi?id=1304688

@mortonharley could you tell what kind of devices you have (android version / api version)?

**Comment by ivan-mogilko** [comment]
Well, I built this APK with your change: https://www.dropbox.com/s/l5neszivh5m77r1/AGS-3.5.0-buttonstest4.apk?dl=0

But I cannot test it myself, because KEYCODE_BACK does not come into onKeyLongPress on my device, or so it seems.

**Comment by ivan-mogilko** [comment]
Alright, I think I finally made it working through onKeyLongPress function; I commented old long press handling out and it works on my side too (fingers crossed).
https://www.dropbox.com/s/rq5ys1iqg9m1dt5/AGS-3.5.0-buttonstest7.apk?dl=0

The problem apparently was in overridden dispatchKeyEvent() function, it intercepts all the key events regardless of whether they are useful for application or not. I think it's a mistake (perhaps oversight). For this test I made it let keydown events for KEYCODE_BACK and MENU through, but later we need to review the whole code there.

**Comment by ivan-mogilko** [comment]
@mortonharley , @mim2011 , could you also try the APK I linked one post above? I redid how long presses are handled and wonder if that work for you (I know that old way did not work for @mortonharley).

(Also anyone else is welcome to try it out)

If that works I will be preparing a proper pull request.

**Comment by ericoporto** [comment]
@ivan-mogilko , do you know if it would be possible to have a configuration in android.cfg to handle left click as finger, so a tap is a click, a down and hold of the finger is perceived as a click but the m isButtonDown for eMouseLeftButton is read as true, and after the finger is released, left button is read as false? This would enable trully porting games to Android to translate mouse gestures (like click hold for drag and drop, using your module) to finger gestures.

**Comment by mim2011** [comment]
> 
> 
> @mortonharley , @mim2011 , could you also try the APK I linked one post above? I redid how long presses are handled and wonder if that work for you (I know that old way did not work for @mortonharley).
> 
> (Also anyone else is welcome to try it out)
> 
> If that works I will be preparing a proper pull request.

@ivan-mogilko 

it is ok, on my tablet i see no difference between the two apks. thank you

**Comment by ericoporto** [comment]
@ivan-mogilko I will open a new issue then, I believe this one can be closed though.

**Comment by ivan-mogilko** [comment]
I still haven't got reply from the original poster.

**Comment by ivan-mogilko** [comment]
Alright, I guess, I will close it now. If there are still issues with android buttons then please open new reports.
