### ISSUE TITLE
Editor: allow to import scripts as ash/asc pair

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#589]
Right now editor only lets you import scripts in the exported module format (scm), but that's inconvenient because you cannot even import your own scripts from another game without packaging them first or doing some workaround.

I suggest to let user choose ash or asc file as well.
* if scripts are in another folder, they get copied to the current project folder first;
* if the second of the pair does not exist it will be created as empty file.
* if the script with same name already exists in the project, then share behavior with scm import (right now it creates a duplicate appending a number to to the module's name; idk if that's a good thing in general but better keep things consistent imo).

**Comment by ericoporto** [comment]
I accidentally stumbled to the first time you said that
https://www.adventuregamestudio.co.uk/forums/index.php?topic=33578.msg518926#msg518926

**Comment by ericoporto** [comment]
The pr #2364 should fix this. :)
