### ISSUE TITLE
Fedora: Unable to find XShm.h

### ISSUE THREAD

**Issue by scottchiefbaker** [adventuregamestudio/ags#591]
I'm trying to build on Fedora and getting an error about `XShm.h` being missing. 

    In file included from platform/linux/acpllnx.cpp:23:
    /usr/include/xalleg.h:38:10: fatal error: X11/extensions/XShm.h: No such file or directory
    #include <X11/extensions/XShm.h>
            ^~~~~~~~~~~~~~~~~~~~~~~

I'm not sure what package I should be installing on Fedora to get this library. Any ideas?

**Comment by scottchiefbaker** [comment]
I had to install both `libXext-devel` and `libXxf86vm-devel`. I'll update the Fedora compile docs as soon as I get this working.

Now I'm getting:

    /usr/bin/ld: ../Common/libsrc/aastr-0.1.1/AAROT.o: in function `_aa_rotate_bitmap':
    /home/bakers/github/ags/Engine/../Common/libsrc/aastr-0.1.1/AAROT.c:88: undefined reference to `fsin'
    /usr/bin/ld: /home/bakers/github/ags/Engine/../Common/libsrc/aastr-0.1.1/AAROT.c:89: undefined reference to `fcos'
    collect2: error: ld returned 1 exit status

**Comment by ivan-mogilko** [comment]
fsin and fcos are part of Allegro API.

UPD: they WERE part of Allegro API, until this: https://github.com/liballeg/allegro5/commit/4848f1583c3dbe41f5f056869ff2c796d33d8121

What version of Allegro are you using?

**Comment by scottchiefbaker** [comment]
`allegro-devel-4.4.2-21.fc29.x86_64`

**Comment by ivan-mogilko** [comment]
No, Allegro 5 is totally different and not compatible.

Can you check that the code shown in the commit linked above still exists in allegro header?

**Comment by scottchiefbaker** [comment]
`/usr/include/allegro/alcompat.h` does indeed contain that entire `#ifdef ALLEGRO_FIX_ALIASES` block.

**Comment by ivan-mogilko** [comment]
Hmm, well, then either ALLEGRO_FIX_ALIASES is not defined, or the header does not get included into the given *.c file for some reason.

**Comment by ivan-mogilko** [comment]
Alright, we actually have these aliases disabled in the latest ags3 and master branches: 44d954493bb5f3e95a11a4eddbb62bd6110b1b63
Not the best way to disable them right in code like that though, should be probably moved to makefile.
fcos and fsin in AAROT.c should be changed to fixcos and fixsin as suggested.

Note, that AAROT.c is actually not used by the engine, and is only included in non-Windows ports by mistake.

**Comment by scottchiefbaker** [comment]
Aha... that makes sense now. If you land a fix for this let me know. I'll `git pull` and try the build again. 

I'll update the Fedora compile instructions with a PR when this is all done.

**Comment by scottchiefbaker** [comment]
It's been a while since I've messed around with AGS. Should I be using `master` or the `ags3` branch. Can you explain the diff to me?

**Comment by ivan-mogilko** [comment]
>  If you land a fix for this let me know.

I will make a PR soon.

> It's been a while since I've messed around with AGS. Should I be using master or the ags3 branch. Can you explain the diff to me?

The difference is explained in the readme here: https://github.com/adventuregamestudio/ags#ags-game-compatibility
In more detail: #448, #450

Right now the "master" branch contains future version which is called "ags4" (working title). It does not have any actual release plan or date.
"ags3" is developed more actively at the moment and we will be releasing v3.5.0 in a while.
All changes from "ags3" are being merged to master (ags4).

**Comment by scottchiefbaker** [comment]
I enable XXX and it gets a lot closer to compiling, but I'm getting a new error about a duplicate function definition now:

    In file included from /usr/include/allegro/base.h:41,
                    from /usr/include/allegro.h:25,
                    from ../Common/util/wgt2allg.h:30,
                    from ../Engine/ac/draw.h:26,
                    from ac/dynamicsprite.cpp:19:
    /usr/include/allegro/alcompat.h:44:7: error: conflicting declaration of C function ‘fixed fadd(fixed, fixed)’
        AL_ALIAS(fixed fadd(fixed x, fixed y), fixadd(x, y))

**Comment by ivan-mogilko** [comment]
This is why these functions were disabled in the first place: iirc same function names are also declared in standard library.

**Comment by ivan-mogilko** [comment]
I opened pull request, could you try it out? #594

**Comment by scottchiefbaker** [comment]
This should be fixed once the doc update in #595 is landed
