### ISSUE TITLE
Splitting Engine and Editor source by separate repositories

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#61]
When I started refactoring attempt I had an impression that Editor code should be kept close to Engine's, for they share part of the codebase. Back then there was, perhaps, a sense in this, because there were files divided on engine & editor "parts" by macros, and before those were separated it was more convenient to have both projects together so that every change could be quickly tested on both.

Now I do not see any serious reason to keep them in the same repository, since they are two separate programs, only sharing number of data structures and serialization formats.

In retrospect, keeping AGS.Native library up to date with changes to shared code was redundant, because there was nothing there that would affect editor's logic nor game compilation (but that's other issue).
Besides, ideally, AGS.Native should be rewritten to be a seamless part of the Editor anyway (aside from other reasons, that is required to make Editor compatible with Mono), and have all ties with engine code cut.

What are problems that may arise if we split those two projects?

I assume that most people have forked this repository to get the engine. So far we had never received any pull requests nor patches for the Editor, and I don't suppose someone is preparing one right now.

Cleaning history is more serious issue. If it is possible to erase individual files from the Git history, we could make both repositories have only related files down to the original state.
Information on cleaning may be found here: https://help.github.com/articles/remove-sensitive-data
and here: http://git-scm.com/book/en/Git-Tools-Rewriting-History
If we do that, we should be aware that _all_ collaborators should do "rebase" when getting changes, not "merge".

In the end, we could have, e.g., ags-engine repository, ags-editor, and maybe some ags-utils for any tools, editor installation script, etc.

This is not something that may be done any moment, we should plan this carefully, make some tests first.

**Comment by ivan-mogilko** [comment]
A little bump, this did not happen, but I'd like to know what active contributors think about this old idea today. I may close this if no one is interested (or if people are generally against this).

**Comment by tzachshabtay** [comment]
The recent trend from I can tell is using monorepos: https://en.m.wikipedia.org/wiki/Monorepo

Google for example has one repo for all their software. So I don't see the harm in keeping them in the same repo.
Splitting them otoh will make history searches harder.

**Comment by rofl0r** [comment]
it was also partially resolved when you started to throw out binaries and upstream source code (like allegro). probably the repo is slim enough now.

**Comment by ivan-mogilko** [comment]
Okay, I will close this then.
