### ISSUE TITLE
License files for newer DLLs shipped with the editor

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#615]
From all the 3rd party libraries shipped with the Editor, only Scintilla dll has an explicit license present in Docs folder. While some of the libs may be covered by LGPL (which is also present). but it's better double check to be sure.

**UPD**: Also need to add this info to About dialog.

Libs used by the engine:
* irrKlang.NET4.0.dll and ikpMP3.dll - a part of irrKlang 1.6 (https://www.ambiera.com/irrklang/)
* Magick.NET;
* Newtonsoft.Json.dll;
* WeifenLuo.WinFormsUI.Docking.dll - a part of DockPanel Suite (http://dockpanelsuite.com/)

**Comment by ivan-mogilko** [comment]
@morganwillcock since you were updating installer recently, could you take a look at this?

**Comment by morganwillcock** [comment]
Sure.
