### ISSUE TITLE
Properties panel shows wrong details when setting StartingRoom

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#617]
Someone sent me a screenshot of the properties panel for a Character showing the properties for an Object.

![properties](https://user-images.githubusercontent.com/14958747/52524332-bfba8f00-2c93-11e9-90d5-6d96a73378c3.png)

It seems easy to recreate this problem, With the room editor open and an object defined, just set the starting room for a character. Internal state seems to get broken at this point, so re-opening the Character properties continues to show the wrong information. To recover you have to restart the Editor.

![wrong_properties](https://user-images.githubusercontent.com/14958747/52524364-11631980-2c94-11e9-9b41-1ab30faadfd5.gif)

**Comment by ivan-mogilko** [comment]
> Internal state seems to get broken at this point, so re-opening the Character properties continues to show the wrong information. To recover you have to restart the Editor.

I wanted to note that you do not have to restart the Editor, simply dropping down the list at the top of Properties pane and selecting character will fix it.

**Comment by ivan-mogilko** [comment]
Should be fixed with #619.
