### ISSUE TITLE
Room editor: strange toolbar button state behavior

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#625]
There is a toolbar button in the mask mode named "Copy walkable area mask to regions".
This supposed to be a simple push button which does some action on click.
I noticed that under certain conditions it may become "checked" (displayed with selection fill). One of the ways to reproduce this is to click on nearby "Show non-selected masks grey-out" button (which has toggleable state).

**Comment by ericoporto** [comment]
Please add a message box with proceed and cancel, with the text "are you sure you really want to copy all walkable area masks on your regions masks? You won't be able to undo this action." And make the cancel pre-selected. I think I misclicked this button some times and needed to use git reset :/

**Comment by ivan-mogilko** [comment]
I removed this command now:
56c2028116e51586bf09fcf6d974bb76c6e0b142


This has been obsolete and redundant for over a decade.

If wanted, we might add proper "copy/paste full mask" command. For the time being one could use export/import via a temporary image file.
