### ISSUE TITLE
Room editor: when multiple layers are visible they also can override mouse actions

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#626]
When multiple layers are made visible in the room editor, the editor acts as if all of them are also active at the same time, at least in respect to mouse actions.

For example, if both Characters and Walkable Areas are visible, and Characters layers is selected in the navigation bar, you may still perform last selected area action (e.g. area selection or paint) unless mouse hovers a character.
If Objects are visible, then you may always right-click to bring up a context menu that lets you to create new object under mouse cursor.

What's expected is that only actions related to the currently selected layer must be enabled.
Alternatively, selection may be allowed, but not other operations (like painting).

**Comment by ivan-mogilko** [comment]
> What's expected is that only actions related to the currently selected layer must be enabled.
Alternatively, selection may be allowed, but not other operations (like painting).

Can anyone comment on this suggestion? Being able to select stuff even when it's on the different layer may be convenient. For instance, when you open a room nothing is selected, yet you may click on characters or objects to select them.

At the same time, in the area/region mask mode you should not be able to click on other items, because all the space between areas is "area 0" which is a valid area which may also be edited.

**Comment by morganwillcock** [comment]
I can see there are issues with the picker, when there is something clickable (like an object) in the way. I think the solution might be to add an extra cursor mode which is just for selection and default to this, and then let the all other tools (such as the picker) click through objects and characters, and work on any "area 0"s.

**Comment by ivan-mogilko** [comment]
Resolved with #912.
