### ISSUE TITLE
How to turn Travis CI on

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#628]
Travis-CI provides environments for doing things on the cloud.

***please read this guide through before following it's steps***

## setting up Travis-CI

The description of everything that needs to happen lives on the .travis.yml file in the root of the repository.

For it to be active, someone with owner permission on GitHub has to:

1 - Go to [GitHub Marketplace](https://github.com/marketplace) and install [Travis-CI](https://github.com/marketplace/travis-ci). AGS is Open Source, so follow the Open Source $0 plan.

2 - Go to [Travis-ci.com](https://travis-ci.com/) and [Sign up with GitHub](https://travis-ci.com/signin). 

3 - If the repository is not owned by the account, but by an organization, request access to it for the organization. Click sync.

4 - Roll to the repo that has a `.travis.yml` file and click activate.

5 - You can manually run a build in the interface to check if it's working

## deploying builds to GitHub 

When a build passes, in some cases, you may want to put your artifacts in a convenient place. You may have each commit submit the artifacts to [Bintray](https://bintray.com/) or attach the results to GitHub Releases.

We are going to use GitHub Releases here. 

[It's important to know security best practices on Travis](https://docs.travis-ci.com/user/best-practices-security/).

Travis [has good docs already on how to deploy releases](https://docs.travis-ci.com/user/deployment/releases/), we are going to cover the minimum.

For uploading something on GitHub Releases, one needs a GitHub account and permission to attach files to releases, which comes with the commit access to the repository.

You can do this either through Travis CLI installed on your computer through ruby gems or the web interface. Since the Travis docs only explain the cli way, I am going to explain the UI way, and we will use an environment variable instead of an encrypted key in the `.travis.yml` itself.

The way Travis-CI does this is by using someone's GitHub Token. Login on GitHub on the user you want to do this and click on the [user settings and then tokens](https://github.com/settings/tokens).

Create a new token and give it a name you won't forget. Copy the token, after the token screen is gone, you won't ever be able to recover it, so you will need to delete and create another. It's alright.

On Travis-CI, in the project you are setting the deploy to GH Releases, create an environment variable, give it an easy name like `GITHUB_TOKEN` and paste the token on it's value. Travis will never give you access to that variable again through it's interface. Please don't note down the token anywhere, if it's value is needed for some reason, create another.

Your `.travis.yml` should look like something below:

```
...
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
...
```

Now, by default, on Travis, only people actually commiting to the repo can access this variable, so someone pushing a PR can't PR a malicious code to see the environment value on the logs.

I like to use an specific account for CI things so if that token ever gets shown in some security failure the damage is easily recovered from.

**Comment by ivan-mogilko** [comment]
@ericoporto , can you actually set this all up same way we did for manual if I give you necessary access permissions?
If you can't maybe someone else (@morganwillcock, @sonneveld)?

This is something good to have, and I feel that I am slowing things down.

**Comment by ericoporto** [comment]
Yes I can. We can reuse the ci-user I had made to allegro. The only difference is that on the manual side I had access to repository settings in the actual repo, so I could like, actually check the [webhooks](https://github.com/adventuregamestudio/ags-manual/settings/hooks). I don't need that access though, if the [ags-ci-user](https://github.com/ags-ci-user) has it, it's fine too.

**Comment by morganwillcock** [comment]
I don't think I've got access to any settings.

**Comment by morganwillcock** [comment]
There are no webhooks defined at the moment. If I'm following correctly, it is setup to run with ags-ci-user and it is just missing the hook to run it?

**Comment by ericoporto** [comment]
If anyone is following here @morganwillcock figured that we need a `.travis.yml` in every pushed branch we want to build.

Looking around, this appears to be true for other ci systems, where the pushed branch will then have it's config file applied. So here the problem was there was no `.travis.yml` in the ags3 branch.

**Comment by morganwillcock** [comment]
> About lib-allegro , I think it's missing webhooks for appveyor - again, neither I or @morganwillcock have access to that repository settings to check.

I do have access to that too, so I can add it.

**Comment by morganwillcock** [comment]
This is turned on and building, so I'll close this now.
