### ISSUE TITLE
Allow to setup game binary name in General Settings

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#629]
Currently the only way to change compiled game's binary name is to rename the project folder (and this is not documented anywhere afaik). It does not look like there's any technical reason to keep this restriction.

I propose to add a "binary name" property to General Settings along with the Game Title, and use it when compiling the game.

**Comment by selmiak** [comment]
milestone worthy!

**Comment by ivan-mogilko** [comment]
Done #765.
