### ISSUE TITLE
Issue loading some v3.3 games in ags3 branch: "GUIMain (0): unknown control type 0 in ref #1."

### ISSUE THREAD

**Issue by sonneveld** [adventuregamestudio/ags#633]
Tested with these games:
https://archive.org/details/a-landlords-dream-v1.1
https://archive.org/details/bruce-quest-secrets-of-the-outback
https://archive.org/details/ntgtfoi

Error message:
Game GUI version: 116
Loading game failed with error:
Failed to load one or more game entities.
GUIMain (0): unknown control type 0 in ref #1.

**Comment by sonneveld** [comment]
Possibly related to this commit: a2247b8db74b3464718a8a7773d3f76028e0c856

**Comment by sonneveld** [comment]
I did a reverse diff: `git diff 87cc10c5e13e015db404d557b71458479cf406c3...014ced380e5bab992169cf1542bd1c426bdb1911 -R `, applied the patch and tidied it up if you wish to test without the changes.


[revert-gui-control-changes.patch.zip](https://github.com/adventuregamestudio/ags/files/2872027/revert-gui-control-changes.patch.zip)

**Comment by ivan-mogilko** [comment]
Oh, I think I know what's wrong... I will try to fix it now.

**Comment by sonneveld** [comment]
I believe you're right. With landlord's dream, if I print out "ControlCount" in the old code I get numbers like this: 
```
rebuild array controlcount: 1
rebuild array controlcount: 4
rebuild array controlcount: 0
rebuild array controlcount: 8
rebuild array controlcount: 4
rebuild array controlcount: 3
rebuild array controlcount: 4
rebuild array controlcount: 0
rebuild array controlcount: 4
rebuild array controlcount: 1
rebuild array controlcount: 4
rebuild array controlcount: 0
rebuild array controlcount: 8
rebuild array controlcount: 4
rebuild array controlcount: 3
rebuild array controlcount: 4
rebuild array controlcount: 0
rebuild array controlcount: 4
```
But with the new code, when I print out _controls.size(), I get `30` and then crashes.

**Comment by ivan-mogilko** [comment]
I made pull request: #634

**Comment by ivan-mogilko** [comment]
I think this should be fixed now.

**Comment by sonneveld** [comment]
It is indeed fixed. Thank you.
