### ISSUE TITLE
Unable to play Quest for Glory II VGA with AGS-3.4.3.1-debug.apk

### ISSUE THREAD

**Issue by lotus-minh** [adventuregamestudio/ags#635]
I try to play Quest for Glory II VGA on my Android with AGS-3.4.3.1-debug.apk but unfortunately the Android application which is AGS-3.4.3.1-debug.apk says : 
 
WARNING: Please run the setup program and check the "use digital music pack" option before playing. This file must be available in order for the game to run. 
 
Individual music and speech settings may be adjusted, enable, or disable from within the game. 

References : 
 
A.) Quest for Glory II VGA 
 
https://www.adventuregamestudio.co.uk/site/games/game/1072 
 
B.) Android.3.4.3.1.APK.zip 
 
https://github.com/adventuregamestudio/ags/releases 
 
Please fix this issue.

**Comment by ivan-mogilko** [comment]
Do you have audio.vox present in the game folder?

**Comment by lotus-minh** [comment]
I don't have it.

**Comment by lotus-minh** [comment]
Only music.vox is present at the game folder.

**Comment by ivan-mogilko** [comment]
Hmm, maybe I was testing with different version of the game, I will check your link.

**Comment by ivan-mogilko** [comment]
Hmm, ok let me check exactly the link you posted, maybe I was testing with different version of the game.

**Comment by ivan-mogilko** [comment]
The download link currently leads to the following page:
http://www.agdinteractive.com/games/qfg2/downloads/thegame/downloads_snd.html

This is QFG2 v2.0, it has audio.vox in the package, and is built with AGS 3.2.0, which may be seen in setup dialog.

Where did you download you game? What desktop system do you have (Windows, Linux etc)? If it's Windows you may try running winsetup.exe and check the version of AGS it was built with. On Linux you may do so under wine probably.

**Comment by lotus-minh** [comment]
I thank you very much for your help.

**Comment by ivan-mogilko** [comment]
The thing is, games made with AGS 3.2.0 and later are hardcoded to find digital audio in "audio.vox", and games made before 3.2.0 look into "music.vox". So the question really is, whether it was simply an incorrect file in the game folder, or this is an older version of QFG2 that does not work for some reason. In the latter case I'd like to test it (if only I knew where to get older version).

**Comment by lotus-minh** [comment]
I play this game in version 1.1 
 
Please forgive me, I did not know this game version is changing fast from time to time, and this thing make this game is different in version from time to time at the download page on the AGD Interactive Studio Website from the last time I download this game in the past time at : 
 
http://www.agdinteractive.com/games/qfg2/downloads/thegame/downloads_snd.html 

However, I found another link to download this game in version 1.1 at : 
 
https://archive.org/details/quest-for-glory-ii-trial-by-fire 
 
And because this game in version 1.1 is did not have audio.vox at the game folder, because only have music.vox is present, so I renaming the file music.vox with audio.vox and this make me able to play this game on my Android. 
 
However, I still have the problem to play this game in version 1.1 on my Android because there is not have a mouse double-click, only mouse single-click is present. 
 
I did not know if the game in version 2.0 is have a mouse double-click is present, yes or no. 
 
http://www.agdinteractive.com/games/qfg2/downloads/thegame/downloads_snd.html 

Because in fact, this game in version 2.0 is a single file which is just Qfg2vga20.exe only, without having audio.vox or another files is not present. 
 
And the important thing is this Qfg2vga20.exe is cannot be open with AGS-3.4.3.1-debug.apk 
 
The problem is this Qfg2vga20.exe is a file installation or the installer for the computer only and the thing is I AM NOT HAVE A COMPUTER. 
 
So that is the reason I play this game on my Android with playing this game in older version only, i.e. version 1.1 

https://archive.org/details/quest-for-glory-ii-trial-by-fire 

And in fact, this game in version 1.1 is have so many files, including music.vox and to playing this game on Android, so renaming the file music.vox with audio.vox is the way to playing this game on Android.

**Comment by lotus-minh** [comment]
I playing this game in version 1.1 on my Android with AGS-3.4.3.1-debug.apk  
 
I am sorry, I did not know this game version is changing fast from time to time, and this thing make this game is different in version from time to time at the download page on the AGD Interactive Studio Website from the last time I download this game in the past time at : 
 
http://www.agdinteractive.com/games/qfg2/downloads/thegame/downloads_snd.html 

However, I found another link to download this game in version 1.1 at : 
 
https://archive.org/details/quest-for-glory-ii-trial-by-fire 
 
And because this game in version 1.1 is did not have audio.vox at the game folder, because only have music.vox is present, so I renaming the file music.vox with audio.vox and this make me able to playing this game on my Android. 
 
However, I still have a problem to playing this game in version 1.1 on my Android because there is not have a mouse double-click, only mouse single-click is present. 
 
I did not know if this game in version 2.0 is have a mouse double-click is present, yes or no. 
 
http://www.agdinteractive.com/games/qfg2/downloads/thegame/downloads_snd.html 

Because in fact, this game in version 2.0 is a single file which is just Qfg2vga20.exe only, without having audio.vox or another files is not present. 
 
And the important thing is this Qfg2vga20.exe is cannot be open with AGS-3.4.3.1-debug.apk 
 
The problem is this Qfg2vga20.exe is a file installation or the installer for the computer only, and the thing is I AM NOT HAVE A COMPUTER. 
 
So that is the reason I playing this game on my Android with playing this game in older version only, i.e. version 1.1 

https://archive.org/details/quest-for-glory-ii-trial-by-fire 

And in fact, this game in version 1.1 is have so many files, including music.vox and to playing this game on Android, so renaming the file music.vox with audio.vox is the way to playing this game on Android.

**Comment by ivan-mogilko** [comment]
> Because in fact, this game in version 2.0 is a single file which is just Qfg2vga20.exe only, without having audio.vox or another files is not present.

It's a Windows installer, you need to install/unpack it first.

> However, I found another link to download this game in version 1.1 at :
https://archive.org/details/quest-for-glory-ii-trial-by-fire

Alright, I am going to check that out too, because normally AGS should find and utilise music.vox when necessary.

> However, I still have the problem to play this game in version 1.1 on my Android because there is not have a mouse double-click, only mouse single-click is present.
> I did not know if the game in version 2.0 is have a mouse double-click is present, yes or no.

AGS does not have a support for double-click event on its own so it's something scripted in game. Probably they are testing for delay between two mouse clicks. On other hand I think Android port has a hardcoded delay time since last tap during which additional taps are ignored, which may be a problem for this game.

Maybe it's worth opening a new suggestion for better double tap support on Android.

But I have to just warn that if you're able to run some game with AGS APK, it does not automatically mean the game will be fully playable on mobile device with touch screen. Not every game controls are designed in compatible way. For example, Wadjet Eye releases special versions of their games with remade controls for iOS.

**Comment by ivan-mogilko** [comment]
Alright, regarding the "music.vox", this seem to be a compatibility problem of the current engine, not only Android port. I will open a separate task for this.

**Comment by lotus-minh** [comment]
I thank you very much for your attention on this issue.

**Comment by lotus-minh** [comment]
About mouse double-click is actually the right mouse button feature function or the mouse right-click feature function in any game that opened with AGS-3.4.3.1-debug.apk 
 
And recently I found out that AGS-3.4.3.1-debug.apk is actually have the right mouse button feature function or the mouse right-click feature function in any game that opened with AGS-3.4.3.1-debug.apk 
 
The way to have the right mouse button feature function or the mouse right-click feature function in any game that opened with AGS-3.4.3.1-debug.apk is by pressing two point tap together at the same time on Android screen while playing any game with AGS-3.4.3.1-debug.apk 
 
However, it will be much better if AGS-3.4.3.1-debug.apk is use double tap or tapping twice with fast on Android screen while playing any game to have the right mouse button feature function or the mouse right-click feature function in any game that opened with AGS-3.4.3.1-debug.apk

**Comment by lotus-minh** [comment]
I want to say thank you very much to ivan-mogilko that is helping me a lot. 
 
Since I now is able to playing this game which is Quest for Glory II VGA in version 1.1 on my Android with the help from AGS-3.4.3.1-debug.apk 
 
So I decide to close this issue. 
 
If there is any inconvenience regarding this issue, so I am so sorry and I am apologize. 
 
Good bye and have a nice day to you all :)

**Comment by lotus-minh** [comment]
If there is someone in the future that have a problem to play Quest for Glory II VGA on his or her Android device, then he or she should create a new thread concerning an issue to his or her problem regarding unable to play Quest for Glory II VGA on his or her Android device, or he or she should create a request to fix a problem on the link below : 
 
https://github.com/adventuregamestudio/ags/issues/new 
 
Thanks for viewing this thread :)
