### ISSUE TITLE
give us the colorpicker every where it is needed please

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#638]
The colorsystem in AGS is a mess, but the least annoying thing would be to have the colorpicker, that converst RGB to AGS colors, everywhere, where you pick a color.
It is probably just locating the colorpicker and copying a function everywhere where colors are picked. Mostly GUI related inputs and speech color come to my list. Did I forget something?
You use it not that often, and when needed you go through the colorpicking of AGS by chosing a color in a completely different tab and copying a converted value over... palette editing is good for 8bit games and what else it is good for, but just picking a color for a game element is way too complicated

And because I am a lazy but clever bastard I'd put the colorpicker not even in the dropdown menu, but it is so important, I'd put it on click of the current selected color. AND in the dropdown, with a or noone will notice it... No idea if it possible to add another clickable item with the current selected color with the editor system, but either way in the dropdown menu for colorpicking it is severely missing. I'd put it first there!
cheers!

**Comment by selmiak** [comment]
https://i.imgur.com/cCGxZV1.jpg
something like this

**Comment by ivan-mogilko** [comment]
I added one in #1024, but it acts like a modal dialog (appears in the center of the screen).

**Comment by ivan-mogilko** [comment]
Colour picker was added to ags4 branch, in theory we could backport this to ags3 too, as changes are only in Editor UI.
Maybe should make a test version and ask for feedback on forums.

**Comment by selmiak** [comment]
cool. this are good news! :)

**Comment by ivan-mogilko** [comment]
Added to 3.5.1 beta, please tell if it's working for you.

**Comment by ivan-mogilko** [comment]
Standard colorpicker dialog was implemented in 3.5.1.
