### ISSUE TITLE
Wrong error message when assigning int array to int

### ISSUE THREAD

**Issue by alkhimey** [adventuregamestudio/ags#639]
It seems that the `[]` are missing in the error message.

![image](https://user-images.githubusercontent.com/652603/53045779-252e2d00-3497-11e9-8dcc-1f772f1a70b4.png)

It seems that the line printing the error message is located here: 
https://github.com/adventuregamestudio/ags/blob/bd86e80343ec94934d9a501bd877744591e45ab4/Compiler/script/cs_parser.cpp#L1260

**Comment by fernewelten** [comment]
The refactored compiler (master and currently in review) returns: `Type mismatch: cannot convert 'int[]' to 'int'`.

**Comment by alkhimey** [comment]
I got this on 3.4.1.15, probably should have mentioned this.

**Comment by ivan-mogilko** [comment]
Wait, this should not be closed until the fix is in official release.

**Comment by rofl0r** [comment]
aren't bugfixes routinely applied to all active branches ?

**Comment by ivan-mogilko** [comment]
Yes, I can confirm this bug exists in ags3 branch (i.e. AGS 3.5.0).

> aren't bugfixes routinely applied to all active branches ?

I was trying to making sure that critical fixes are applied to all active branches, but non gamebreaking bugs like this may be not applied if they require extra effort to fix in the old branch. For example, if code was refactored for the new version it may be easy to fix something there, but not in the previous stable release.
If this is what you were asking about?

**Comment by rofl0r** [comment]
> If this is what you were asking about?

yes, thanks for info

**Comment by ivan-mogilko** [comment]
This is fixed in 3.5.0, now reports:
`GlobalScript.asc(8): Error (line 8): Type mismatch: cannot convert 'int[]' to 'int'`
