### ISSUE TITLE
WaitMouse(), allow indefinite Wait, more info about Wait-interrupt

### ISSUE THREAD

**Issue by messengerbag** [adventuregamestudio/ags#647]
AGS currently has `Wait()`, `WaitKey()` and `WaitMouseKey()` functions to block for a fixed time (or rather, number of game loops), with option to interrupt either with a keypress, or with a mouseclick _or_ keypress.

There is no way to set a block that can only be interrupted by a mouseclick. I propose a function `WaitMouse()` that blocks until there's a mouseclick.

There is also no way to block _indefinitely_ until there's a mouseclick or keypress. I propose that `WaitKey()`, `WaitMouseKey()` and the new `WaitMouse()` (but not plain `Wait()`) should be modified to accept negative `time` arguments, which would be interpreted as "block forever (until interrupted)".

Finally, it would be useful in some circumstance to know exactly how a block was interrupted. I propose that instead of returning just 0 if timed out and 1 if interrupted, `WaitKey()` and `WaitMouse()` would return the `keycode` or `MouseButton` that were pressed, and 0 if timed out. `WaitMouseKey()` could return the `keycode` value if interrupted by a keypress, `-MouseButton` (the negative of the `MouseButton`) value if interrupted by a mouseclick, and 0 if timed out.

**Comment by ivan-mogilko** [comment]
This may work as an ammendment to existing API for the time being, but I have to frankly say that I don't like these functions in general. Firstly they may encourage bad UI design where players have no means to decide whether they like to skip things with mouse or keyboard, and secondly they restrict to predefined device (what if I use joystick plugin and want to skip with gamepad buttons?).

Hopefully we could come to something more flexible in the future.

**Comment by messengerbag** [comment]
I mainly want these functions in order to emulate dialog blocking, which has options for skipping lines based on keyboard press or mouse click, or both, or neither. In fact, to be truly on par with the speech system, there needs to be a `WaitKey(eKeyCode skipKey)` and `WaitMouseKey(eKeyCode skipKey)` variation that only interrupts on a particular key (cf. `Speech.SkipStyle` and `Speech.SkipKey`).

For example, in [this thread](https://www.adventuregamestudio.co.uk/forums/index.php?topic=56962.0) asking about a way to allow you to rewind conversations, I was about to suggest a solution with a custom speech function based on showing a GUI, blocking until the user clicks, and then checking whether it was over any buttons to determine how to proceed. However, this cannot be done without a lot of other work since `WaitMouse(forever)` doesn't exist.

**Comment by ivan-mogilko** [comment]
> I was about to suggest a solution with a custom speech function based on showing a GUI, blocking until the user clicks, and then checking whether it was over any buttons to determine how to proceed. However, this cannot be done without a lot of other work since `WaitMouse(forever)` doesn't exist.

Sorry for offtopic, but I am getting anxious this may be an overcomplication. If they are doing something like VN style game where you can go back and forward along the story, then there may be no need for blocking at all, you could check for the state of the speech and input events. I did this in the past with the typewriter style speech, which was working in async way.
But maybe I should comment in the forum thread instead, when I have more time to think this over.

**Comment by messengerbag** [comment]
> If they are doing something like VN style game where the speech is displayed in a box you can go back and forward along the story, then there may be no need for blocking at all, you could check for the state of the speech and input events.

You _can_, but then you can't keep each line as a "standalone" call, you have to break up the logic between starting the line and completing it. So rather than an "overcomplication" I think it's a matter of trying to enable the most straightforward solution.

> Frankly I've grown a natural repulsion against blocking game during anything except cutscenes. Because players may want to e.g. quit the game by clicking on menu button anytime (not that ags were good for that).

I get what you're saying, but the benefit of `Wait()` and blocking calls in general is that it's simple for people without a lot of programming know-how to grasp. And frankly, without delegates or something like that, coding asynchronous logic in AGS is a nightmare. Even the "semi-blocking" cancellable actions in the Tumbleweed Verbs template are implemented using `Wait()` (and `Mouse.IsButtonDown()` to get around the disabling of normal input events).

**Comment by ivan-mogilko** [comment]
I have a crazy question, after working on #656 I thought, may something like SkipWait be useful? Not sure if it's possible, but supposedly it could let you programmatically break out of Wait from rep_exec_always (still need to experiment to prove that it works).

**Comment by ericoporto** [comment]
SkipWait would be great to advance something using a non-engine supported input method, like Joystick, or a key combination. It would be a great addition!

**Comment by ivan-mogilko** [comment]
@messengerbag 
> There is also no way to block indefinitely until there's a mouseclick or keypress. I propose that WaitKey(), WaitMouseKey() and the new WaitMouse() (but not plain Wait()) should be modified to accept negative time arguments, which would be interpreted as "block forever (until interrupted)".

Could you tell, why do you suggest _negative_ argument as forever, and not 0 for simplicity?

If I understand correctly, 0 is a useless value in Wait functions currently.

**Comment by messengerbag** [comment]
Partly for backwards compatibility, partly it feels a little bit safer by making it harder to accidentally call the function to block forever (for example if you're setting a `Wait` based on some calculation, e.g. the distance between point A and point B, which might be, or round to, 0).

And you could perhaps argue that it's more readable (clearer that the number has some special meaning) with `WaitKey(-1)` than with `WaitKey(0)`. Perhaps.

Anyway, it felt right to me. It's not a huge deal to me in either case.

**Comment by morganwillcock** [comment]
Couldn't the parameter just be made optional? That doesn't break anything and if you don't want a timeout you just don't specify one.

**Comment by ivan-mogilko** [comment]
@morganwillcock 
> Couldn't the parameter just be made optional? That doesn't break anything and if you don't want a timeout you just don't specify one.

It definitely could be, except optional timeout would have to have some value anyway, meaning "no value".

**Comment by ivan-mogilko** [comment]
Opened pull request: #1084
