### ISSUE TITLE
Direct3D renderer in fullscreen is showing non-black masking bars

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#653]
Here is a game built with the alpha 10 release:
https://www.adventuregamestudio.co.uk/site/games/game/2332/

When using the Direct3D renderer fullscreen, and scaling which requires black bars to maintain the aspect ratio, some parts of the bars are appearing as a dark brown colour instead of black.

Example of issue (top of the border is brown for the width of the game) from someone else's computer:
[https://www.youtube.com/watch?v=2kFiFOphnCs](https://www.youtube.com/watch?v=2kFiFOphnCs)

When I try the game, I actually get the entire left side (height of the screen) and the entire top side (width of the screen) showing as brown.

![brown_resized](https://user-images.githubusercontent.com/14958747/53673450-7e5c4480-3c7f-11e9-829c-4ae27ace406a.PNG)

I've tried with the engine from alpha 11 and it has the same issue.

**Comment by morganwillcock** [comment]
@ivan-mogilko I think the issue is probably introduced here, which was a change for new camera/viewport system:
https://github.com/adventuregamestudio/ags/blob/e4eaca2b33048bb0c013066bd67a8d7ea016247d/Engine/platform/windows/gfx/ali3dd3d.cpp#L1014-L1029
Ignoring the Rect and clearing the whole screen will display the border correctly on all 4 sides.
<pre>direct3ddevice->Clear(0, NULL, D3DCLEAR_TARGET, colorDword, 0.5f, 0);</pre>
...or is there something I've missed for an earlier blanking of the entire screen?

**Comment by ivan-mogilko** [comment]
Fixed: 1ae9070dd93a0d3dd7e70c59cc6bb893e6f39059

Direct3D has incorrectly used this function for internal purposes, passing real display coordinates while function expects native game coords.
