### ISSUE TITLE
Don't delete binaries after running from IDE

### ISSUE THREAD

**Issue by messengerbag** [adventuregamestudio/ags#658]
So here's something that happens to me a lot: I make some changes to my project. I try to compile, eventually I fix all my typos and it works. I press F5 to see how it looks. It's fine. I go to grab the build. The EXE is deleted!

**In the name of God, why?!**

Proposal: Don't do this.

**Comment by ivan-mogilko** [comment]
The reason it gets deleted is that the test build reads data from compiled folder too and can catch up old data from previous exe.

**Comment by morganwillcock** [comment]
Would it be preferable to split build and distribution into separate functions? So the building (and optionally running) is the first stage, with creating files for distribution (create archives or installers) being a second stage that depends on the first stage. This way there is no confusion over what is where or about what data may be stale.

**Comment by morganwillcock** [comment]
I've tested writing a tar archive with SharpZipLib and it doesn't seem too complex:
<pre>TarEntry tarEntry = TarEntry.CreateEntryFromFile(GetCompiledPath(LINUX_DATA_DIR, Path.GetFileName(fileName)));
tarEntry.Name = fileName;
tarEntry.SetIds(1000, 1000);
tarEntry.TarHeader.Mode = 33277; // octal 100775 as decimal
tarArchive.WriteEntry(tarEntry, true);</pre>
...so I'll probably try switching the Linux build process to use this, and maybe try it with a macOS .App directory in an archive too. But this is very much distribution only and I'm still not sure why there is such an overlap between the test build and the compiled folder. Is it because some other external files may only exist in the complied folder?

**Comment by ivan-mogilko** [comment]
> I'm still not sure why there is such an overlap between the test build and the compiled folder. Is it because some other external files may only exist in the complied folder?

Yes, I mentioned this in my reply above.

**Comment by morganwillcock** [comment]
How do these files get in there though? Do people put them in there with the expectation that the debug build also uses them? I wasn't sure whether 'catch up' means that the compilation process it taking a shortcut or whether you mean that someone has manually changed something.

**Comment by ivan-mogilko** [comment]
It's both. Compiled translation files are being put there, and I guess users put them there by habit.

**Comment by ericoporto** [comment]
I had a thought on it building for debug, if the build is good, it runs a separate thread where it builds the actual exe to be put on the compiled folder. This way after the game developer has debug tested his game and it worked, once he looks into the compiled folder, there will be the compiled game, updated, and ready to be pack for release.

**Comment by ivan-mogilko** [comment]
> The reason it gets deleted is that the test build reads data from compiled folder too and can catch up old data from previous exe.

I just had a random idea that this may be worked around by passing a list of file packs to ignore for the engine.
Or pass an option to ignore packages completely, since test game is supposed to run over the non-packaged assets.

**Comment by ivan-mogilko** [comment]
Fixed this by b35e3b97e127c94e85c267f7030255657433d83e

Some things have changed in the past in regards to how engine is instructed to find game data.
Made engine to print all the known asset locations to the log 801f21a12bfc8cc534f6cf3062097fa42f8db98c to let us know where it gets data from. Used this to double check that it does not try to read from non-deleted *.exe and *.ags packages in Compiled/Windows when running from IDE.

But just in case, added explicit instruction to find game data in _Debug/game.exe, as a command line arg.

**Comment by messengerbag** [comment]
Hallelujah! 🥳
Thank you!
