### ISSUE TITLE
AGS3: weird relative path issue.

### ISSUE THREAD

**Issue by sonneveld** [adventuregamestudio/ags#665]
(context, within Linux)

While testing games from the Engine directory, I typically run games by using a relative path:

e.g

```
/mnt/hgfs/nick.sonneveld/tmp/ags-mergin/Engine$ ./ags ../game_files/
....
Initializing game data
Located game data file: /mnt/hgfs/nick.sonneveld/tmp/ags-mergin/game_files/ac2game.dat
```

But in certain path combinations, the directory seems to be doubled up somehow:

```
/mnt/hgfs/nick.sonneveld/tmp/ags-mergin/Engine$ ./ags ../game_files_16bit/game_files_ntgtfoi_16bit/
....
Initializing game data
Game data file could not be found. Search path used: '/mnt/hgfs/nick.sonneveld/tmp/ags-mergin/game_files_16bit/game_files_16bit/game_files_ntgtfoi_16bit/'
```

Note the `game_files_16bit/game_files_16bit` appearing doubled.

Or running `ags` from project root:

```
/mnt/hgfs/nick.sonneveld/tmp/ags-mergin$ Engine/ags ./game_files
...
Initializing game data
Game data file could not be found. Search path used: '/mnt/hgfs/nick.sonneveld/tmp/ags-mergin/game_files/game_files'
```

**Comment by morganwillcock** [comment]
It seems this also doesn't work properly on Windows, although maybe for different reasons:
<pre>C:\Users\mwillcock\Downloads\AGS-3.5.0-alpha12>dir /b ..\hydrate-v1\Windows
acsetup.cfg
audio.vox
Hydrate.exe
winsetup.exe
</pre>

All of these fail with the same error:
<pre>C:\Users\mwillcock\Downloads\AGS-3.5.0-alpha12>acwin.exe ..\hydrate-v1\Windows\Hydrate.exe
C:\Users\mwillcock\Downloads\AGS-3.5.0-alpha12>acwin.exe ..\hydrate-v1\Windows\
C:\Users\mwillcock\Downloads\AGS-3.5.0-alpha12>acwin.exe ..\hydrate-v1\Windows</pre>

![find](https://user-images.githubusercontent.com/14958747/55104918-37693f80-50c3-11e9-934b-76826633fd7a.PNG)

**Comment by ivan-mogilko** [comment]
This may be simply a logic fault somewhere in string manipulations where it e.g. expects to contatenate absolute path and filename and ends up adding two absolute paths.

@morganwillcock --log may provide more info on why this is failing (at least display where it is looking at)

**Comment by ivan-mogilko** [comment]
@morganwillcock I found there's a faulty logic in the engine which triggers if you are using relative paths, at least when these include "../". In such case it may duplicate step up.

**Comment by ivan-mogilko** [comment]
Yes, this is because AGS sets new current working dir at startup to the path contained in command argument and then again uses same argument when searching for game data. If path is relative it becomes incorrect.

I am doing small adjustments around that place in code right now, will try fixing this too.

**Comment by ivan-mogilko** [comment]
I made a pr, please test:  #699

**Comment by morganwillcock** [comment]
I've tried to test it, but the branch is missing the recent build fixes for Linux.

**Comment by ivan-mogilko** [comment]
Rebased after fixes.

**Comment by morganwillcock** [comment]
Still testing it, but it seems to have issues when the path is /.

<pre>$ export ENGINE=~/build/ags-refactoring/Engine/ags

# this will launch a game from /
$ cd /tmp && $ENGINE ..

# these are incorrectly deemed to be invalid and don't launch
$ cd /tmp && $ENGINE ../
$ cd / && $ENGINE .
$ $ENGINE /</pre>

Also, when the path is printed it is missing a newline, so the "Usage" message is on the same line.

<pre>$ cd /tmp && $ENGINE ../ | grep -B1 Usage:
Defined game location is not a valid path.
Path: /Usage: ags [OPTIONS] [GAMEFILE or DIRECTORY]</pre>

**Comment by morganwillcock** [comment]
I've re-tested (following the changes) and all 4 of these example now launch the game.

**Comment by ivan-mogilko** [comment]
> I've re-tested (following the changes) and all 4 of these example now launch the game.

Thank you.
There's another problem found by rofl0r here: #662 
I wanted to take a look too before merging this one to at least find out if it may require different approach to code.

**Comment by ivan-mogilko** [comment]
> I've re-tested (following the changes) and all 4 of these example now launch the game.

So I guess this particular issue is fixed then.
