### ISSUE TITLE
AGSEditor /compile should turn alert into log messages

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#666]
So I am looking into building an AGS Game using a CI system.

Once you can get AGS installed in the system, it's as simple as running the following:
```
%AGSINSTALLDIR%\AGSEditor.exe /compile %AGSGAMEPROJECT%\Game.agf
```

If the game builds ok, everything is good. If when building, the game misses a plugin, even if harmless (eg: SpeechCenter), an alert window with an OK is popped up. Also if the game was made with a previous version of AGS, the ok alert window will pop up. And finally, in case of error, another window will pop up.

Ideally, when using a flag like `/compile` I would expect missing a plugin, or other warns to be simple log messages on console, and the build to proceed. Then if the build is ok, it should finish with 0, and if the build hit an error, finish with 1, and log the errors to console.

**Comment by ivan-mogilko** [comment]
This is honestly the first time I learnt about this flag in all those years. No wonder there was no attempt to prevent anything modal from appearing.

Hmm, this may require some good thought and maybe redesign of some processes.
For example, a warning/error reporting interface could be passed in building functions, and let external user decide what to do with alert.

**Comment by morganwillcock** [comment]
+1 for stand-alone game compiler

**Comment by ericoporto** [comment]
Just to illustrate the use, here is Dungeon Hands:
- [Dungeon Hands GH Repo](https://github.com/ericoporto/dungeonhands)
- [Script to install AGS in clean env and build the game](https://github.com/ericoporto/DungeonHands/tree/master/Script)
- [Appveyor Log](https://ci.appveyor.com/project/ericoporto/dungeonhands)
- [Actual game built in CI](https://ci.appveyor.com/project/ericoporto/dungeonhands/build/artifacts)

**Comment by ivan-mogilko** [comment]
Only FYI, as a hotfix we could try checking "compileAndExit" flag in GUIController.ShowMessage() methods. Maybe it's possible to dump the message to stdout instead if .NET can do that (but IIRC when running windowed app on Windows it does not write back to same terminal it was launched from).
Of course that won't cover other possible blocking events we may not know about yet.

**Comment by ericoporto** [comment]
That hotfix works for me :]

**Comment by ericoporto** [comment]
![image](https://user-images.githubusercontent.com/2244442/59315832-d698de80-8c91-11e9-9222-a1fa17944491.png)

I think the hotfix proposed may be easier to implement, since there is already an option to not show popups on compile. This way, if a build fails, it will not generate the game .exe file in the compile folder and fail a possible next task of packaging in the game CI pipeline.

**Comment by ericoporto** [comment]
Made a PR by using the hotfix as an approach. This became an issue to me because I wanted to test a 3.6.1 game in the command line and the Beta warning pop-up was hanging my pipeline.
