### ISSUE TITLE
Steps for adding and removing function to script api

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#668]
I read the wiki https://github.com/adventuregamestudio/ags/wiki but couldn't find it described there, so I decided to ask a question, where I believe the answer should probably just go there and then this issue should be closed.

What are the minimal places needed to modify in the Engine code so that one can add a method to an existing namespace? I know on each version of ags some script functions are added and some are gone.

As an example, imagine adding a DisplayHelloWorld() method that just call Display("Hello World") or whatever is as simple as possible.

**Comment by ivan-mogilko** [comment]
I will write a topic today.

**Comment by ivan-mogilko** [comment]
I will write a topic in wiki today.

**Comment by rofl0r** [comment]
should be quite easy to find out with git. use git blame on the file containing script interpreter accessors, then read the commit log of a commit that added one.

> I will write a topic in wiki today.

thinking about, making this easy might invite game creators to hack their own accessor funcs into their own custom engine mod, which will then in turn make their games incompatible with the official engine.

**Comment by ericoporto** [comment]
@rofl0r I just wanted to do a PR with some Math functions I think are missing from the AGS Standard Script API, but I am not sure how it was the right way to approach this . This seems to be really trivial for @ivan-mogilko but it isn't for me, I have lived for now with my script modules. Couple of things I wanted to do but couldn't for lack of knowledge on proper script api evolution:

- Move display functions to a display namespace.
- Move global functions to Game (`Game.isPaused` instead of `IsGamePaused`)
- Add Maths.Max and Maths.Min 

This all seem non priority issues that I could contribute as PR because sounds easy enough, but I couldn't figure out basic stuff, like, how I do that and have the person using the 3.4.1 script api have the older methods working?

**Comment by ivan-mogilko** [comment]
It's an important part of engine knowledge that must be documented. While it's possible to follow examples from git history, not everything there is trivial or obvious from the code.

> thinking about, making this easy might invite game creators to hack their own accessor funcs into their own custom engine mod

This problem is too ... can't find a good word. Abstract?
I don't think we should be responsible for supporting any hacks people do for themselves, that's too much to ask. And definitely I would not deny documenting my own work because of this.

**Comment by ivan-mogilko** [comment]
Sorry, this takes more time than I thought because did not realize all the nuances I have to mention (and I am sometimes being awkward with words).
If this is urgent or you want to try something out for a test I may post a crude version and improve later.

**Comment by ericoporto** [comment]
A crude would be enough, I just want to add some things to Maths! :)

**Comment by rofl0r** [comment]
meanwhile here are some related commits for starters
d7667f3f1fc7c15d2f58b1a8f10412551c49d3bd
c5faba58d6ef5a6ee795a57a5df353ad596bd374

**Comment by ivan-mogilko** [comment]
I wrote this: https://github.com/adventuregamestudio/ags/wiki/A-quick-guide-to-Script-API

Please tell if something is missing, hard to understand etc.

**Comment by ericoporto** [comment]
@ivan-mogilko thank you, the text is informative, I will give it a try later to see if I understood :)
