### ISSUE TITLE
Editor room loading code requires debugging and testing

### ISSUE THREAD

**Issue by monkey0506** [adventuregamestudio/ags#67]
I've identified a couple of issues with my porting of the room (CRM file) loading code from the native assembly to the editor assembly (multi_room_edit branch only). The latest commit has the following identified issues:
- Broken C# implementation of String::Read is causing massive overflow while reading. (Fixed, not committed)
- C#'s Encoding.ASCII.GetString is not null-truncating strings, leading to very strange and broken results. (Fixed, not committed)
- C# implementation of LoadLZW is throwing invalid argument. Requires further investigation.

If any one else has a chance to look at the code, please let me know what else I may be doing totally wrong. Thanks! -monkey

**Comment by ivan-mogilko** [comment]
IIRC this was related to the "multi_room_edit" branch. The branch is based on development version found in the "experimental" branch, which was cancelled few years ago.

If the "multi_room_edit" work is to be restored, it needs to be recreated on top of current master.
