### ISSUE TITLE
Issue with "\[[" in script (again?)

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#671]
**Script 1:**
<pre>
player.Say("TEST\[[TEST");
</pre>

Expected to display:
<pre>
TEST[
TEST
</pre>
(1 linebreak)

Instead displays:
<pre>TEST[[TEST</pre>

**Script 2:**
<pre>
player.Say("TEST\[[[[TEST");
</pre>

Expected to display:
<pre>
TEST[

TEST
</pre>
(3 linebreaks)

Instead displays:
<pre>TEST[[

TEST</pre>
(2 linebreaks)

It looks like engine appends second "[" to the escaped sequence and prints both of '[' instead of only one.

**Comment by ivan-mogilko** [comment]
On a side note, why does AGS support '[' char as linebreak when '\n' works? ...

**Comment by fernewelten** [comment]
When the compiler sees a `\` inside of a string, it doesn't do any special logic with the next letter at all, it takes the next letter just as it is. `\[` and `[` mean exactly the same thing to the compiler, namely, put a `[` into the string. `\n` means put a `n` into the string etc.

No matter how you code the `[` on the program side, they mean exactly the same. It's the Bytecode interpreter that reads the `[` and takes this to mean a linebreak. 

For the interpreter to see a `\[`, you need to code `\\[` in the program The first `\\` translate into a single `\`, the following `[` gives a `[`. Another way of coding it would be `\\\[`. The first  `\\` translate into a single `\` again, the following `\[` gives a `[`.

I haven't tested what the interpreter makes of `\\[`, but I **think** I've read somewhere that this would give you a non-linebreak [.

**Comment by fernewelten** [comment]
[Escaping characters (AGS Wiki)](https://www.adventuregamestudio.co.uk/wiki/Escaping_characters)

**Comment by fernewelten** [comment]
So, why don't we change this to the C style way at least for AGS4?
* The compiler would translate `\`combinations at compile time the C way, e.g., `\n` means linefeed.
* All the string processing functions would treat an in-memory `\` as a perfectly normal character. For instance, when a concatenation function gets strings as input that contain a `\`, then they just concatenate the strings as they are.
* Display functions also treat an in-memory `\` as a perfectly normal character and output it as given. Also, they treat an in-memory 0x0A (10, `\n`) as the linefeed.
* Editor fields accept, store and show strings exactly as entered. 
    * When the contents of such fields are passed to the compiler in some way, they are surrounded by `"` and copied verbatim into the code. So the compiler will turn any `\n` into 0x0A. 
    * If the field contents  are passed anywhere else but to the compiler (e.g. they are taken as a label inscription, a listbox entry), then the editor will do C-style translation first.

**Comment by ivan-mogilko** [comment]
@fernewelten this is a bug in the engine, not the compiler. Compiler does everything right. Engine interprets the sequence of '[' symbols incorrectly somewhere.

**Comment by gurok** [comment]
For extra fun, try `\\[[`

**Comment by ivan-mogilko** [comment]
Apparently this got fixed by my recent changes to split_lines() function, while I also corrected unescape_script_string() a little: 2eaf54637ff22320c4c3f72011ab1729dba7af6d

@gurok 
> For extra fun, try `\\[[`

This sequence gets converted into `\[[` real text (according to C rules),
which AGS interprets as literal '[' followed by linebreak (according to its own line splitting rules).

**Comment by ivan-mogilko** [comment]
@fernewelten I've agreed with what you've said about compiler earlier
> When the compiler sees a \ inside of a string, it doesn't do any special logic with the next letter at all

but that was too hasty it seems, because I was mistaken about whole thing as well. The situation is actually different.

Here's the function in compiler that parses string literals:
https://github.com/adventuregamestudio/ags/blob/release-3.5.0/Compiler/script/cc_compiledscript.cpp#L61

As you can see that it actually replaces certain combinations having backslash in them:
* "\\" got merged into '\' (single slash)
* "\n" replaced with '\n' (linefeed) (so this is how \n actually work in ags)
* "\r" replaced with '\r' (caret return) (pretty useless as it is ignored by Display functions!)
* the "\[" sequence is *protected*, and in kept as-is.

One thing you noted right is that 
> The way we do it now means that symbols are interpreted at several times

The worst thing in above is that it's not always easy to predict escaping rules.
For example, consider the example @gurok posted above:

`player.Say("TEST\\[[TEST");`

One could imagine that "\\" is merged into single slash, and "[[" is left as two linebreaks. That would happen if there were only 1 pass, but because there are 2 passes for interpreter that actually looks like an escaped '[' followed by a linebreak. That's because compiler parses backslashes one by one without paying attention to what's next.

So, yeah, the whole thing is pretty messed up and should be definitely revisited. Removing special rules for "[" would be very beneficial. In the interpreter it could still check for them for old game formats (if we consider backwards compatibility).
