### ISSUE TITLE
modern 3d-devices run unthrottled during faded-out screen

### ISSUE THREAD

**Issue by mgambrell** [adventuregamestudio/ags#674]
due to `if (play.screen_is_faded_out)` in `render_to_screen` the vsyncing won't happen and the game will run unthrottled until something is rendered again. If other scripting is going on still, it will run at warp speed.

This is needed after `gfxDriver->ClearDrawLists();`:
`if(gfxDriver->RequiresFullRedrawEachFrame()) gfxDriver->Render();`

**Comment by ivan-mogilko** [comment]
Right, this looks like a bug.
Also this means that plugin callbacks for AGSE_FINALSCREENDRAW won't get called for what is worth.

**Comment by ivan-mogilko** [comment]
RIght, and it seems to me that skipping render is wrong in general, because there could be debugging information displayed over the game which still has to be on screen regardless of in-game effects.

**Comment by ivan-mogilko** [comment]
I ended up removing this skip: 09c26bec949fdb133585ad49d1b1ccec3b9ea0fa

At first I wanted to use same condition and skip adding certain sprites to render list instead when constructing a scene, but apparently at the moment drawing hooks are the only way plugins can track the game ticks, so discretion is necessary there. I'd leave it for the future.

**Comment by mgambrell** [comment]
When I made that change, I discovered that my engine was rendering the previously-drawn contents of the screen (or the previously-drawn framebuffer, at least) when the screen was fully faded-out. I don't know why for sure, but I thought it was because the graphics driver doesnt know how to darken due to a fade unless it's in the scope of its own fade. Actually I guess the bigger question is why the fix I posted works when yours doesnt (for me, in my engine). I know youve changed the video drivers since I forked my "console" video driver from the d3d one so maybe the difference is in there.

**Comment by ivan-mogilko** [comment]
Hm, I made an oversight then, will look further.

I guess your fix would work because you are running Render after clearing the list of drawn things.

**Comment by mgambrell** [comment]
Yes, that matches my analysis. What I don't understand is why your change doesn't do the same thing.

**Comment by ivan-mogilko** [comment]
Since I removed this skip it continues to do full render instead, and as you say 3d renderer does not handle full fade-out correctly for some reason.

**Comment by ivan-mogilko** [comment]
Alright, this is bigger than I thought, it affects software renderer too, which means, I think, that engine was not supposed to draw anything at all in the "fade-out" state, it simply does not consider this as a separate state, and my change broke that "logic".

**Comment by ivan-mogilko** [comment]
I pushed another commit, which explicitly tells which groups of sprites to not render if the game is faded out: fb7d8abe8c55cbf0a89bf9aba0c170731aded6f4

My only concern currently is plugin hooks, since this means they will be skipped too, which older plugins may not be aware of, but time will show I guess (and we have open source versions of most of them).

**Comment by ivan-mogilko** [comment]
I think this was fixed. Also, quite a few things changed in the render function since, so this ticket would be not relevant anymore.
