### ISSUE TITLE
Room.HotspotCount setter silently adding items to Room.Hotspots.

### ISSUE THREAD

**Issue by monkey0506** [adventuregamestudio/ags#69]
I'm changing some code from using local variables to using the Room properties directly, and I started getting OutOfMemory exceptions, which I tracked back to a loop which apparently should only have run 16 times. There isn't a clear indication (from the interface level) that setting Room.HotspotCount, Room.WalkableAreaCount, etc. automatically populate the associated list. I don't believe that the setter method for an int property should be doing that anyway.

IMO, if you change HotspotCount then it's your responsibility to ensure that the list is updated also (by calling the method that does this, or adding them manually). If this is intended as a "feature", then I believe the interface should be changed. Having a public int property setter do this is very confusing, and in my case, led to crashing the editor.

Please consider changing this behavior. Thanks.

**Comment by ivan-mogilko** [comment]
This is no longer relevant to the current development.
