### ISSUE TITLE
Automatically create all nested subdirectories when user opens file for writing in script

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#697]
Strangely, but for some reason AGS does not cover this case when user wants to have subdirectories in $APPDATADIR$ and $SAVEGAMEDIR$. I don't see any reasons not to.
This should not be hard to fix too (need to write an utility function that creates all missing subdirectories along the path, starting from base dir).

**Comment by morganwillcock** [comment]
Would this just be for `File.Open` with the mode set to `eFileWrite`, or something more generic?

**Comment by ivan-mogilko** [comment]
> Would this just be for File.Open with the mode set to eFileWrite, or something more generic?

Yes, it should be done when File.Open is called with eFileWrite to ensure it can create a file.

**Comment by ivan-mogilko** [comment]
Done by #764
