### ISSUE TITLE
Game.DoOnceOnly reset state

### ISSUE THREAD

**Issue by Dualnames1** [adventuregamestudio/ags#701]
It would be useful to be able to do a reset on all the Game.DoOnceOnly's used
But also being able to get their state like so

bool HasGetGameDoOnceOnlyBeenUsed(String token)  (possibly a far better name).
But definitely the reset probably. Though to be fair for this custom save game system I'm working on, a replacement function is quite more likely.

**Comment by ivan-mogilko** [comment]
Something to consider maybe, I was wondering other day how easy that would be to implement and expose a key/value map (ordered or not) into ags script.

We already have String, which is a basic container of chars.

What if we make Map or Dictionary in a same way?

Then you could script your own "do once only" and even have multiple instances of these for different purposes.

**Comment by ericoporto** [comment]
I have no idea on how to implement this, but I am interested in using it. So just some random thoughts, that can be wrong, maybe it will be easier to develop it in shipable states, so people can test it:

1. map
2. Game DoOnceOnly using map as a module
3. CustomProperties as a map
4. Plugin interfaces for map

Far future things that should be only thought about in the future: sorted map, custom sorting, allowing("this").or.something.similar() //to ease deep working with deep dictionaries

Being able to test maybe requires landing in 3.5.0, or 3.6.0 (or is ags4 actually working?)

**Comment by ivan-mogilko** [comment]
> I have no idea on how to implement this, but I am interested in using it.

Set or Map script class may actually be relatively easy to do. There is a bunch of small script classes declared in API that may be used for the reference. For example, you may find Camera or Viewport classes added recently. Internally, it should work more like DynamicArray (having a std::unordered_map<String,String> as a storage).

I'd say that on its own could be done in 1-2 days, assuming you know how to add new script API.
Reimplementing DoOnceOnly and custom props as a new map class will take more (and may have some compatibility issues to resolve), but if we will add at least an unordered string set and/or map that may be created in script that alone would cover most of use cases.

I will open a ticket for this soon.

**Comment by ivan-mogilko** [comment]
Set and Dictionary were merged (#714, included with alpha build 3.5.0.9). So on one hand now one could use custom Set instead of Game.DoOnceOnly, on another hand it should be possible to reimplement that function with a Set.

E.g. something like `readonly attribute Set* Game.DoOnce;` (readonly means container object itself cannot be replaced).

Perhaps we could aim full replacement internally (so that old scripts and original script command ran through the same container). Then it's important to keep in mind that managed object should have 1 extra reference held by GameState to prevent automatic deletion of the unused set.

**Comment by ivan-mogilko** [comment]
I decided to add Game.ResetDoOnceOnly() into the ags3 branch. The reasoning is that DoOnceOnly is one of the few things in game data that could not be reset (or maybe the only remaining one). This will at least allow to reset game state when going back to main menu, or something.

For other situations it's best to use available Set and Dictionary types.
Whether replace DoOnceOnly and custom properties with these types in script in ags4 is a separate question, I guess this may be addressed separately if there's a wish for this.
