### ISSUE TITLE
Engine crash when exceeding GUI label text length limit

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#706]
Setting label text to a string that is too long to be supported (because of configured limit) causes the engine to crash (exits with no error message).

<pre>lbl.Text = "";

for (int i = 0; i < 2047; i ++)
{
  lbl.Text = lbl.Text.Append("a");
}

// crash here
lbl.Text = lbl.Text.Append("a");</pre>

In contrast, adding too many items to a Listbox silently drops new items once the limit is reached (200 items) without crashing.

**Comment by ivan-mogilko** [comment]
This seem to not be a case in latest ags3 branch, after GUI refactoring (and there's no arbitrary label length limit anymore).

**Comment by morganwillcock** [comment]
OK, closing as already fixed.
