### ISSUE TITLE
Rewrite text wrapping function and remove wraps limit

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#707]
There's a universal text wrapping function `void split_lines(const char *todis, int wii, int fonnt)` that is used anywhere where engine needs to wrap text. It uses a fixed array of 50x200 (lines x chars), which may be enough in common case, but may be easily exceeded if there is a label used for displaying a big blob of text (with scrolling for instance).

The task is to remove this arbitrary limit and otherwise improve this function if necessary (the code is pretty old).

**Comment by sonneveld** [comment]
I can look at this if you like.

**Comment by ivan-mogilko** [comment]
Done by #911
