### ISSUE TITLE
Scripting: forward declaration of types seem to be ignored for function arguments

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#708]
Script compiler allows to do forward-declaration of types and seem to be fine with using forward-declared ones in function return values or attribute types, which may be observed in the built-in header:

<pre>
// forward-declare these so that they can be returned by GUIControl class
builtin managed struct GUI;
...
builtin managed struct GUIControl {
  ...
  /// Gets the GUI that this control is placed onto.
  readonly import attribute GUI* OwningGUI;
  ...
}
</pre>

But for some reason same does not work for function arguments, e.g. if you write:
<pre>
  import void SomeFunc(GUI* gui); // reports "Parse error at 'GUI'"
</pre>

**Comment by ivan-mogilko** [comment]
This is fixed by a new compiler in ags4 branch.
