### ISSUE TITLE
Script API: add ID property to AudioClips

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#709]
### Explanation

Almost every object in game has an ID which is by current implementation equals to their index in a array where they're stored. AudioClips are ones that don't have it for some reason.

This is a problem, because sometimes user would like to have something to look a clip up in array rather than address it by script name.

Additionally, as far as I know, because there's no fixed ID the clips do not have fixed position in their array when game is compiled, and dragging them around in project (e.g. from type to type) breaks their order, unlike Characters and other entities.

To clarify why this may be important for some users: sometimes they would like to choose an object from some range using a formula of some kind (like, randomly choose between 10 clips). Of course there's a workaround to write and initialize custom arrays in script, but the general consensus was it would be better if game's global clip array would be already suitable for this. This is especially important in the abscence of other ways to look objects up, for example, when saving and reading data from custom files.

IIRC that was a reason some users still prefer to use old audio API, which orders clips based on their filenames.

### To summarize

1) Add ID property to AudioClip type in the Editor. This property is equal to their index in the list (new elements get ID equal to previous list length). _When object is removed in the middle all IDs are shifted._
(Although this seem counter-rational and not convenient, this is for consistency with other objects in the game, because all of them are stored in arrays without empty spaces.
Changing this behavior may be a task on its own, but if done it's preferrably be applied to *all* game objects at once).

2) Make sure when game is compiled AudioClips are written into game data in the order of their IDs.

3) Add new ID script property (attribute) to AudioClip type which may be readable at runtime.

**References**

For 1) and 2) use other dynamic lists for example, such as Characters or Inventory Items.

For 3) see similar property in any game object, from Character to AudioChannels.
A quick guide on adding script API: https://github.com/adventuregamestudio/ags/wiki/A-quick-guide-to-Script-API

**Comment by messengerbag** [comment]
Just to add another use-case to this: debugging. Currently there's no way to identify a clip that's playing in-game (short of manually comparing it one-by-one to every clip you've imported until you get a match). With an ID, you could output this value for debugging and find it in the IDE.

**Comment by ivan-mogilko** [comment]
@messengerbag 
> Just to add another use-case to this: debugging. Currently there's no way to identify a clip that's playing in-game (short of manually comparing it one-by-one to every clip you've imported until you get a match). With an ID, you could output this value for debugging and find it in the IDE.

I feel like much better way would be to just export "script name" in AudioClip API.

**Comment by ivan-mogilko** [comment]
Done.
