### ISSUE TITLE
building a debian package doesn't seem to work

### ISSUE THREAD

**Issue by LogicalDash** [adventuregamestudio/ags#71]
I've followed the instructions in debian/README.md . I have used them to install a functional AGS in the "normal" way, make --directiory=Engine install . That part works fine. But when I follow the instructions for building a Debian package, I get a package with the README in it and basically nothing else--no binaries. At least it installs.

In case it matters...
OS: Kubuntu 13.04 64bit
CPU: AMD Athlon X2

**Comment by ivan-mogilko** [comment]
This is an old report and was never mentioned since. I'd like to close this now. If similar problem appears again please open a new issue.
