### ISSUE TITLE
INFO: a variant of utf8 support for translations

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#711]
A while ago @mgambrell has pointed me his work on hacking in utf-8 string support for translations. It's based on modifying alfont source to use parts of the **musl** library to convert strings.

Here's the commit (and maybe there are more commits around): https://github.com/RatalaikaGames/ags/commit/a00e7d933458d8360c17cf84c8cfbf5125111c3b

I am leaving this here only for the reference if someone would like to look into this at some point, because afaik the solution was not applied universally to whole engine, and it's hard to tell which nuances may be met when fully moving to utf8 support in both editor and engine (especially if you care about loading old games into new interpreter).

**Comment by mgambrell** [comment]
We haven't made an asian localized game yet. We'll be doing it eventually, though. Certainly don't use my commits until we've run it through the entire process to smoke out other bugs.

**Comment by ivan-mogilko** [comment]
Closing this, as we have implemented it in somewhat different way in the engine (#1321).
