### ISSUE TITLE
Build alfont and freetype embedded on Windows too

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#712]
After #690 we have compaible freetype sources in the repository for Linux (and OSX?). Now we need to make them build for Windows version too.

I'm afraid we'd have to **move** these library sources (alfont **and** freetype) to Common lib, because Editor's AGS.Native.dll also uses alfont (otherwise it would still depend on alfont being built as a separate static lib). Common lib is linked/embedded in both Engine and AGS.Native.

I guess we may use available alfont-2.0.9 on Windows too (even though we were using 1.9.1 until now). I made a quick test and don't see any difference in how they draw fonts, so guess main difference was freetype version. alfont-2.0.9 also has multiple fixes.

**UPD** Don't forget to adjust README.md for all related ports.

**Comment by rofl0r** [comment]
> I'm afraid we'd have to move these library sources (alfont and freetype) to Common lib

should be a non-issue, no ? `git mv` will do it, the binary blob should stay identical so this should not result in a more bloated repo.

apparently it builds on mac now too with 48c3697dc5168884caef0919f4a4892f30bf1ba6 ( btw the config.mk generated on linux looked like this: https://0x0.st/zZdb.mk  )  but it seems embedding the sources in the current build system is lacking, it would need to be done like in commit 6723e59237567ecf6a56e6d62cb9fb41e18871de:

```diff
+++ b/Engine/Makefile-defs.osx
@@ -1,8 +1,7 @@
 USE_MIDI_PATCH = 1
 
-FT_CFLAGS := $(shell pkg-config --cflags freetype2)
-FT_LDFLAGS := $(shell pkg-config --libs freetype2)
+include Makefile-defs.freetype
 
 INCDIR = ../Engine ../Common ../Common/libinclude ../Plugins ../Engine/libsrc/glad/include
```
it's possible that for OSX build one or more files need to be added to the source list in Engine/Makefile-defs.freetype

**Comment by rofl0r** [comment]
also, let's not forget to remove this hack here when the freetype sources are used everywhere 

https://github.com/adventuregamestudio/ags/blob/master/Common/font/ttffontrenderer.cpp#L102

**Comment by sonneveld** [comment]
Check out my CMakeLists.txt file for Freetype, there's only a few minor differences between systems. https://github.com/adventuregamestudio/ags/blob/e2cdfdf8c7435676242d778c66aef9814076be5c/Engine/libsrc/freetype-2.1.3/CMakeLists.txt

**Comment by ivan-mogilko** [comment]
Oh, and all related READMEs should be updated.

**Comment by rofl0r** [comment]
as CMake is not merged yet (and it will hopefully stay that way), the task would be to adapt the current build system.

**Comment by sonneveld** [comment]
> the task would be to adapt the current build system.

> it's possible that for OSX build one or more files need to be added to the source list in Engine/Makefile-defs.freetype

yep, check out the cmakefile for the list of files needed for each system.

**Comment by ivan-mogilko** [comment]
This is done now.
