### ISSUE TITLE
Reimplement script managed objects (de)serialization with memory stream

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#713]
Right now script managed objects (descendants of ICCDynamicObject) are deserialized using temp buffer, which is error prone and also they must precalculate their content size before writing and report back if buffer is not large enough.

Need to implement an automatically extending memory stream (as a subtype of Stream class) and use that instead (maybe pass as a base Stream pointer).

NOTE: this should erase following members of AGSCCDynamicObject -
<pre>
    int bytesSoFar;
    int totalBytes;
    char *serbuffer;

    void StartSerialize(char *sbuffer);
    void SerializeInt(int val);
    void SerializeFloat(float val);
    int  EndSerialize();
    void StartUnserialize(const char *sbuffer, int pTotalBytes);
    int  UnserializeInt();
    float UnserializeFloat();
</pre>

**Comment by ivan-mogilko** [comment]
Resolved in 3.6.0, commits ccee37e303af2d9e6ca23b115ff33631ca1244af and c9007679f21e8347d34312b0dd078bbbd29f0de5
