### ISSUE TITLE
AGS3: Investigate CPU load

### ISSUE THREAD

**Issue by sonneveld** [adventuregamestudio/ags#715]
See below discussion for details:

![image](https://user-images.githubusercontent.com/335451/56006594-bcd22e00-5d18-11e9-8553-f3543129aae9.png)

**Comment by rofl0r** [comment]
maybe use `git bisect` to find the commit where the cpu load started to go up

**Comment by ivan-mogilko** [comment]
I admit this is not a very accurate problem description. Like I was saying before, script interpreter became slower in general after some of my changes, but I am no longer certain if it's the only reason. Other day I was testing very script-heavy game, but recently I noticed same effect if I run almost any game, both ancient and (relatively) newer ones, using 3.5.0 interpreter. So I begin to wonder if it's relevant to some recent changes.

Note, I tested only windows build.

**Comment by sonneveld** [comment]
I suspect it's my changes for the frame rate limiting. Whatever fix is in place needs to test with  `--fps` and max frame rate to ensure we're not actually slowing things down.

**Comment by sonneveld** [comment]
Please test this PR https://github.com/adventuregamestudio/ags/pull/777 It introduces a delay after rendering a frame if we still have time after updating and rendering. I was thinking of adding this as a config option because it can affect frame rate negatively.

**Comment by sonneveld** [comment]
This should be fixed in `ags3` now if you'd like to test it.  Still waiting on PR to update the 3.5.0 release branch.

**Comment by rofl0r** [comment]
seems this is still relevant. "operation forklift" still uses 100% cpu with ags3 branch. (pretty good game, btw)
link https://gamejolt.com/games/operation-forklift/3811/download/build/211987
(and yeah, latest commit, linux, the usual)

**Comment by sonneveld** [comment]
> seems this is still relevant. "operation forklift" still uses 100% cpu with ags3 branch. (pretty good game, btw)

I'm not sure this is the same issue. With all optimisations, I'm getting 60% cpu. What framerate are you seeing with `--fps` enabled? It might just be that the ags script is cpu heavy.

**Comment by rofl0r** [comment]
> What framerate are you seeing with --fps enabled

about 80 in avg (with turbo activated @4ghz). when i throttle the CPU to 800 Mhz (using "userspace" governor), it runs at a well playable ~35 fps average.

**Comment by sonneveld** [comment]
> it runs at a well playable ~35 fps average

Ah ok, if the game is running at 35 fps, that suggests the bottleneck is an ags script that can't keep a consistent 40 fps. That should account for the 100% cpu usage in that case I think.
