### ISSUE TITLE
Resolve the steam/gog client plugin issue on Android and others

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#723]
There's a problem that games that come with the Steam/GOG plugin support cannot be run on Android using our launcher APK, because it does not include stubs for these plugins.

There are two ways to deal with this issue.

1. First is to add these stubs to the compilation lists for Android and bundle their *.so into APK.

2. Second is to add plugin stubs to the engine... again.

I don't like this second way, but when I say "don't like" - I mean precisely that. If it's the only/most optimal solution, then we'd have to do that. There may be other situations when supplying dynamically linked library is not an option or is inconvenient. To think of it, partially the problem may be that we don't have any centralized cross-platform plugins distribution.

In the past @monkey0506 already suggested to add these stubs into the engine: #455. Back then I did not remember whole deal so was not sure why this is needed when there's already a stub plugin around. Unfortunately he seem to not like my reply, so closed the pr, and deleted the working branch. But the code is still available in github cache: https://github.com/adventuregamestudio/ags/pull/455/commits/8e0d7fda85539db53d268b2387ac14f7a9f34c0c (I also copied it just in case)

**Comment by i30817** [comment]
Some games still have problems with this even on pc linux. Heroine's quest for instance.

**Comment by ivan-mogilko** [comment]
There were a stub plugin that may be compiled on Linux. Can't find the link atm.

**Comment by i30817** [comment]
How do you use these stubs? I compiled the 64 bits version (i'm on 64 bits and compiled the 64 bits ags) and used `LD_PRELOAD=libags2clientstub.so ags`  and HQ still didn't start with the same error.

**Comment by ivan-mogilko** [comment]
Yes it should be named just like the one requested by the game, otherwise engine won't know what to load. But more important question is if it has all necessary stub functions inside, because there were several variants in the past.

**Comment by i30817** [comment]
Renaming to `agsteam.dll` didn't seem to work for any of the main games (Kathy Rain, Heroine's Quest and Unavowed).

**Comment by ivan-mogilko** [comment]
Are you running on Linux or Windows?

**Comment by i30817** [comment]
linux

**Comment by ivan-mogilko** [comment]
It should be agsteam.so then.

**Comment by i30817** [comment]
Didn't help, both the 32 and 64 builds of https://github.com/monkey0506/ags2clientstub/commits/master

named agsteam.so and dropped on Heroine's Quest don't affect the crash:
```
No placeholder functions for the plugin 'agsteam' found. The game might fail to load.
Loading game failed with error:
Script link failed.
Runtime error: unresolved import 'AGSteam::SetAchievementAchieved^1'.
```

Kathy Rain has:
```

No placeholder functions for the plugin 'agsgalaxy' found. The game might fail to load.
No placeholder functions for the plugin 'agsspritefont' found. The game might fail to load.
No placeholder functions for the plugin 'agsteam' found. The game might fail to load.
Loading game failed with error:
Script link failed.
Runtime error: unresolved import 'AGS2Client::SetAchievementAchieved^1'.

```
Which is probably 3 plugins. Only Galaxy.dll is actually visible or a actual file in the dir 

Unavowed has
```
No placeholder functions for the plugin 'agsteam-unified' found. The game might fail to load.
Loading game failed with error:
Script link failed.
Runtime error: unresolved import 'AGS2Client::SetAchievementAchieved^1'.

```

**Comment by ivan-mogilko** [comment]
Alright, I guess I'll just merge these steam and gog stubs into the engine, since not everyone can build plugins on their own and we don't have any centralized way to distribute them now. Not that I love this solution but it seem to may be the simpliest at the moment.

Regarding others:
* agsspritefont and agspalrender plugins are in our repository, in Plugins. They may also be built-in the engine if you compile using BUILTIN_PLUGINS option.
* ags_nickenstien_gfx - I hear first time about this plugin.

**Comment by i30817** [comment]
I think the plugins dir isn't being built by the makefiles generated by cmake.

**Comment by i30817** [comment]
BTW stdio_compat.c is not being built by the standard makefile for some reason, and then stops the build. I had to add a target to it in Makefile-objs and then call that target in the Main Makefile OBJS_C_CPP_MM (though maybe there is a better way).

**Comment by ivan-mogilko** [comment]
I know nothing about cmake script, it's very new and I haven't had a chance to try it myself. We used make files all the time previously.

I made a mistake about AGSSpritefont, it is not built-in, and instead has its own makefile in its directory.

**Comment by ivan-mogilko** [comment]
Regarding cmake, there's an option "AGS_BUILTIN_PLUGINS" which tells it to include all plugins. Perhaps it's what needed, but like I said, I haven't tried that myself yet.

**Comment by i30817** [comment]
First thing i tried to turn on. Doesn't really build them (all?). Anyway built from the Engine dir with the old makefile and a system installed self-built libdumb goes further in at least "Terror of the Vampire" which means "agspalrender" is not being built on cmake.

**Comment by sonneveld** [comment]
> First thing i tried to turn on. Doesn't really build them (all?). Anyway built from the Engine dir with the old makefile and a system installed self-built libdumb goes further in at least "Terror of the Vampire" which means "agspalrender" is not being built/linked on cmake.

That is definitely included in the list of built in plugins.

When you run `cmake` on your build directory, did you include the option `-DAGS_BUILTIN_PLUGINS=ON` ?  Simply editing the cmake file won't affect it if the cache variable is already set to off.

cmake also comes with `ccmake` which is a console variable editor (you'll need to press 'c' to configure, edit options, then 'g' to generate)

**Comment by i30817** [comment]
> When you run `cmake` on your build directory, did you include the option `-DAGS_BUILTIN_PLUGINS=ON` ? Simply editing the cmake file won't affect it if the cache variable is already set to off.

Makes sense, with that that 'Terror of the Vampire' game works.

**Comment by ivan-mogilko** [comment]
@i30817 I pushed the old commit with steam/gog stubs, could you test that engine runs these games without sub plugin now?

**Comment by i30817** [comment]
Isn't that commit kind of small, compared to the https://github.com/monkey0506/ags2clientstub repo?

 I think at least the steam functions might have changed meanwhile. For instance this file:
https://github.com/monkey0506/ags2clientstub/blob/master/LeaderboardsStub.cpp
 has stubs not on that commit like `GetLeaderName`

But anyway, i'm building. I don't have steam thou, so my games don't have that dll on their builds to test.

**Comment by ivan-mogilko** [comment]
> I think at least the steam functions might have changed meanwhile. For instance this file:
https://github.com/monkey0506/ags2clientstub/blob/master/LeaderboardsStub.cpp
has stubs not on that commit like GetLeaderName

What matters are calls to `engine->RegisterScriptFunction` and the script names functions are being registered with. If something is missing we may compare lists of `RegisterScriptFunction` calls to find differences.

**Comment by i30817** [comment]
Ok Heroine's quest starts (this one uses agsteam.dll), both whispers of a machine and kathy rain don't start, but this is for unrelated reasons, not because of galaxy.dll (because of the missing engine functions they added) and they both say `Placeholder functions for the plugin 'agsgalaxy' found.`. So it appears to work, but you probably want more tests.

**Comment by ivan-mogilko** [comment]
> I'd honestly prefer a more fully featured achievement system that could actually display them ingame for the games that have a inbuild 'achievement gallery'. I'm pretty sure this could be stubbed as a simple ini file placed on the save dir. Maybe even a switch on the cfg file for them 'on' or not.

TBH I don't understand your suggestion, is this related to steam achievements? Don't know if engine should be allowed to display something overriding game rules. Anyway I think it's better to open a new issue for this.
The point of the plugin stubs were simply to let the game run at least, disregarding missing functionality.

**Comment by i30817** [comment]
I may actually be confusing the AGS plugins with other games. I've seen games that have in-built achievements menus that just mirror those on steam. I had the idea that some ags games did that but from a cursory look at my collection i can't see one, so i must have been imagining it.

**Comment by ericoporto** [comment]
I think the problem is #456, if that issue is solved the developer could provide this disconnection, IF he wanted.

**Comment by ivan-mogilko** [comment]
@ericoporto even if they do, this won't fix existing games.

**Comment by ivan-mogilko** [comment]
I'd like to close this issue if it's confirmed that games depending on steam client can now be run on Android with our launcher APK. For now that is simpliest (if not only) way to run them at all there for most users.

**Comment by i30817** [comment]
I don't have a smartphone/android so i'll bow out of that.

**Comment by ivan-mogilko** [comment]
This was fixed apparently.
