### ISSUE TITLE
Redesign runtime debug overlay

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#724]
Engine is capable to display some debug overlay for game, such as showing walkable area masks and character walking paths. Unfortunately this is all done in a hard way, by overriding game update and render. During display game is unconditionally paused and debug information is drawn on black screen, which makes it inconvenient to compare with actual room background (not certain if this is not a bug though).

Anyway, my suggestion is to
1) redesign the debug overlay in a non-blocking way, with debug info layers being inserted at wanted order in the render stack as half-translucent sprites.
2) redesign debugging API to avoid using "Debug(a,b)" command.

after that it would be easier to add more debugging options.

**UPDATE**
p 1) may be done in either ags3 or ags4.
p 2) is changing script api, so meant for ags4.

**Comment by selmiak** [comment]
sounds like a great addition.

also people tend to forget to turn off debug mode when releasing games. Maybe some subtle message when you start or quit the game to remind the dev that debug mode is still on would be helpful. But could also turn out to be annoying as there is one more click when testing over and over again...
