### ISSUE TITLE
OpenGL window gets displaced on some Windows systems

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#736]
First reported and discussed here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=56699.0

The latest guess is that Windows treats ags game as "non-DPI-aware" application and tries to adjust its position on screen. This breaks OpenGL fullscreen mode.

Possible problem and solution reference:
https://docs.microsoft.com/en-gb/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows
https://stackoverflow.com/a/31979996/965638
https://stackoverflow.com/questions/13228185/how-to-configure-an-app-to-run-correctly-on-a-machine-with-a-high-dpi-setting-e
https://stackoverflow.com/questions/47049651/opengl-and-windows-10-per-monitor-aware-dpi-scaling

**Comment by ericoporto** [comment]
Hey, a bit unrelated, I noticed the *AGS Editor* had similar settings but it's disabled -> 

https://github.com/adventuregamestudio/ags/blame/ags3/Editor/AGS.Editor/app.manifest

**Comment by morganwillcock** [comment]
Does anyone have a screen that has a high enough resolution to recreate this problem?

**Comment by ivan-mogilko** [comment]
> Does anyone have a screen that has a high enough resolution to recreate this problem?

I believe you could try using virtual machine for this purpose, for example VMware player allows to setup number of monitors and their max resolution.

**Comment by morganwillcock** [comment]
The same (or at least a similar) issue is also present with the software renderer, although the choice to use OpenGL is also changing the screen resolution of the desktop.

**Comment by morganwillcock** [comment]
I've re-checked this again (and had reinstalled Windows in-between), and the commited change defintely flags the application as self-scaling, which fixes the geometry calculations.
