### ISSUE TITLE
Sprite does not clear when moving viewport

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#741]
A repainting bug on Donna Avenger of blood.

Load the first save here:
[Donna Avenger of Blood Saves.zip](https://github.com/adventuregamestudio/ags/files/3134572/Donna.Avenger.of.Blood.Saves.zip)

Then move right along the corridor. The 'camera' will move horizontally but the pc sprite will 'ghost'.

edit: near the end of the corridor.

Not sure if this is supposed to be a game or engine bug, but here it is. It's cosmetic fortunately.

**Comment by i30817** [comment]
There is a crash when finishing the chapter too. To finish the chapter from this save, just 'combine' the key in the inventory with door 5 and wait until the sequence finishes.

backtrace from gdb:
```

Thread 1 "ags" received signal SIGFPE, Arithmetic exception.
0x00005555556df7e3 in room_to_mask_coord(int) ()
(gdb) bt
#0  0x00005555556df7e3 in room_to_mask_coord(int) ()
#1  0x00005555556ee3e5 in get_hotspot_at(int, int) ()
#2  0x00005555556b9faa in __GetLocationType(int, int, int) ()
#3  0x00005555556b59dc in GetLocationName(int, int, char*) ()
#4  0x000055555574171f in ?? ()
#5  0x0000555555742e98 in ?? ()
#6  0x00005555557430c5 in RunGameUntilAborted() ()
#7  0x0000555555743377 in initialize_start_and_play_game(int, char const*) ()
#8  0x000055555573d162 in initialize_engine(int, char**) ()
#9  0x0000555555625a93 in main ()
(gdb) 

```

**Comment by i30817** [comment]
I just avoided the division by zero above by changing this method to add the last if. 

Integer division rounds to 0 so...
```
// Setups coordinate conversions between room and masks
void init_room_coordinate_conv()
{
    // Make a multiplier from mask to data resolution for faster conversions.
    // Normally a coordinate would be converted first from mask to game res,
    // and then from game to data res (and in opposite direction).
    room_mask_to_data_mul = thisroom.MaskResolution / game.GetDataUpscaleMult();
    if (room_mask_to_data_mul == 0)
       room_mask_to_data_mul = 1;
}
```

**Comment by ivan-mogilko** [comment]
It should not be 0, this means MaskResolution does not get initialized correctly at some conditions.

**Comment by i30817** [comment]
Integer division with the divisor > the dividend floors to 0 right?

**Comment by ivan-mogilko** [comment]
Maybe that too, although it seemed at first that should never happen here, but maybe I missed some case. I will check again.

**Comment by i30817** [comment]
I think the original repainting bug here does not exist when using opengl instead of software like i was before.

But i saw a bug with Z, where a object was in the foreground to the pc character when it shouldn't logically. Not sure if it exists on the original too.

[Donna Avenger of Blood 2.zip](https://github.com/adventuregamestudio/ags/files/3137180/Donna.Avenger.of.Blood.2.zip)

first save. You should be already be in front of the object (a post on a pillar).

**Comment by ivan-mogilko** [comment]
I did another attempt on the previous fix: 81f8f51a07ed2d573b2dc4bfee0465cb0f99fc4b

Repaint bug will occur only with software renderer, because its related to "dirty rects" system this renderer uses. It also seem to affect only scrolling rooms when camera has moved away from 0,0.

**Comment by i30817** [comment]
> There cannot be repainting bugs in other renderers, because they work differently.

I just found one in the zip save above? Or maybe it's rather a z-fighting bug, but same difference IMO.

**Comment by ivan-mogilko** [comment]
@i30817 , yes, this Z-order bug is the IgnoreWalkBehind problem.
In short, the regular z-order may be A -> B -> C, but this property can additionally require object C be above A at the same time.

In the past we decided to consider this very low priority and recommend developers to not use this property, because it breaks the normal "sprite stack" logic. Maybe it can be fixed by some kind of additional hack, but it's so rare that no one was arsed to do this yet.

**Comment by ivan-mogilko** [comment]
Anyway, regarding repaint bug, apparently it was there for a long time, but I did not notice because my test game had a transparent gui covering whole screen, in which case ags just repaints whole screen all time.

**Comment by ivan-mogilko** [comment]
Pushed a fix: 0b2c762fa32dd219519343b93c7c7eb43357e1dc

**Comment by i30817** [comment]
Good job, it's fixed. Now only the z-order bug remains. It occurs a lot on this game.

**Comment by ivan-mogilko** [comment]
Alright, closing this now.
Split Z-order problem into separate ticket: #745.
