### ISSUE TITLE
Setup installed engine subsystems in editor and config

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#753]
This was asked few times before by users: a way to set up which subsystems engine should install when running particular game. Initially this refered to audio ones, since not every game uses MIDI or MOD/XM clips for instance, but maybe there are other examples.

The reasoning behind this is to prevent engine from trying to initialize something that it's not supposed to use anyway during the course of the game, and which may fail resulting in error messages, confusing players or causing other side-effects.

Supposedly there should be a way to set this up in game design-time settings, as well as disable them in runtime config.

**Comment by ivan-mogilko** [comment]
To narrow the task, having at least switches disabling MIDI and MOD/XM audio in General Settings would be enough for starters.

**Comment by ivan-mogilko** [comment]
Closed, as the task is unclear, and the #962 which was the primary reason is closed as probably not necessary.
