### ISSUE TITLE
Feature: allow using character's speechColor with Sierra Style

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#754]
I wanted to have the possibility of using the character own speech color as the text color on the text written for speech when Sierra Style speech is used.

Right now Sierra Speech passes a negative textcolor taken from the actual character speech color:
https://github.com/adventuregamestudio/ags/blob/ags3/Engine/ac/character.cpp#L2732

Later on in the code, this color information has a multiple hidden meanings in the negative sign.

Here is when it finally decides to grab the TextGUI color and use it instead of the original text color passed in the variable asspch:
https://github.com/adventuregamestudio/ags/blob/ags3/Engine/ac/display.cpp#L207

If the TextGUI had a property like useSpeechColor, allowing `guis[usingGui].UseSpeechColor` to be checked or  `guis[usingGui].FgColor` also had a hidden meaning to be ignored if it's value is negative (without breaking the Editor) then it would be possible to use Character Speech Color when using the Sierra Style speech.

This was previously in the forum:
https://www.adventuregamestudio.co.uk/forums/index.php?topic=55025.0

```
function MySay(this Character*, const string message,  ...) {
  gTextGui.TextColor = this.SpeechColor
  this.Say(message,  ...)
}
```

The solution of the workaround code snippet above can work once #748 goes through

**Comment by ericoporto** [comment]
Because now it's possible to change TextGUI color in script and Dialog scripts support using a custom function, I don't feel this is needed anymore, and think this can be closed.

**Comment by ivan-mogilko** [comment]
I think the actual problem is that color selection of Sierra speech is an obscure algorithm, and its not obvious which properties do you have to set to have an impact.
