### ISSUE TITLE
Kathy Rain camera bug

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#758]
Ok found what's likely the first bug that isn't plugin related or new function related (i think).

In the first cemetery scene in Kathy Rain (just after you have the intro conversation and check the beeper and exit the room) is supposed to follow the ego right to left. This doesn't happen in the open source AGS but does in wine. Here are saves for both versions just before entering the scene (it's the autosave). Just click the icon on the top.

[kathyrain_camera_bug.zip](https://github.com/adventuregamestudio/ags/files/3160132/kathyrain_camera_bug.zip)

To get the game to run, compile the AGS and AGSSpriteFont from this branch here (place the so in the game dir) and run it as opengl. Also you need a galaxy or steam stub from https://github.com/monkey0506/ags2clientstub since this fork doesn't have the recent fallback for that yet.

https://github.com/i30817/ags/tree/compat/whispers-of-a-machine

I *tried* to compile the AGS from the author for this game at https://github.com/josthas/KrusAGS and it progresses until the linking stage if you disable the builtin plugins (this is before cmake), but fails with lots of multiple definitions, so i didn't try more.

**Comment by ericoporto** [comment]
Probably using SmoothScroll module which literally has an if system Linux then not work.

**Comment by ivan-mogilko** [comment]
> Probably using SmoothScroll module which literally has an if system Linux then not work.

Interesting idea. This happened in couple of games already.

Try adding following to acsetup.cfg:
<pre>
[override]
os=win
</pre>

**Comment by i30817** [comment]
Well that makes this happen:

```
An error has occurred. Please contact the game author for support, as this is likely to be a scripting error and not a bug in AGS.
(ACI version 3.5.0.10)

in "ConfigHelper.asc", line 61
from "ConfigHelper.asc", line 145
from "GlobalScript.asc", line 2117

Error: Error running function 'game_start':
Error: Null pointer referenced

```

**Comment by ericoporto** [comment]
If it uses a custom config it uses folders from the OS and crashes because of that no?

I feel in this case you should take the problem with the game developer.

**Comment by i30817** [comment]
There are no actual subfolders in the game dir.

**Comment by i30817** [comment]
Uh, that was actually caused by trying to use a cfg, not the new entry. The hunt continues.

**Comment by i30817** [comment]
Oh god it worked (with the original, which now i have to binary search to minimize and find the setting it absolutely needs).

**Comment by i30817** [comment]
I see the author is the Nelly Cootalot author too, so i need to test that game too. In fact i should just use `strings Game.exe | grep SmoothScroll` ugh.

**Comment by ivan-mogilko** [comment]
> I see the author is the Nelly Cootalot author too, so i need to test that game too. In fact i should just use strings Game.exe | grep SmoothScroll ugh.

Actually, I introduced this "override os" setting after someone mentioned that "Nelly Cootalot" does not work on Linux.

**Comment by i30817** [comment]
I think the latest versions don't do this now, at least if i donwload the source of 1.7.1 and search for Linux i found this:

```
    //if (System.OperatingSystem != eOSLinux){

    if (SmoothScroll_ScrollStatus){
```

But how am i going to figure out which script version needs this? I guess i'll be putting in cfg files for every exec that has the SmoothScrolling string just in case...

**Comment by ivan-mogilko** [comment]
So, in the end, this was SmoothScroll module's problem, and it is fixed by "override os" setting?
I will close this then.

**Comment by i30817** [comment]
Just FYI, downfall redux is another game i noticed needs this.
