### ISSUE TITLE
Enhanced rooms panel

### ISSUE THREAD

**Issue by AleWin32** [adventuregamestudio/ags#763]
First of all, thanks to @tzachshabtay for the work made to the Rooms panel interface.
My suggestion is an enhancement of it. The advantage is that you can work faster:

- You need less clicks (3 mouse clicks compared to 1) to expand the room layer (edges, characters, objects, hotspots, etc). See the first animated GIF below to understand this, you will see 3 red circles (these are the mouse cilcks done).

- You can see the visibility and locking status of each layer at once without doing any mouse click.

**PLEASE, CLICK ON THE ANIMATED GIFS TO SEE THEM BETTER IN FULLSCREEN**

Current Rooms panel (at least on AGS v3.5.0):
<img src="https://i.ibb.co/4dWT81n/old-Rooms-panel-UI-Selecting-Edges-3-clicks.gif" alt="old Rooms panel">

New Rooms panel i propose (notice you will only see one circle = mouse click and you can see the visibility and locking status of every layer at once):
<img src="https://i.ibb.co/0KhQWLn/new-Rooms-panel-UI-Selecting-Edges-1-click.gif" alt="new Rooms panel">

Also, you must notice i removed the "Room" word (see the image below in a red rectangle) because actually it doesn't make sense, the first word will always be "Room" because we are in the Room panel, and also at the left in a label it is said "Edit this room's:".
<img src="https://i.ibb.co/sKQZKVb/useless-Room-word.png" alt="new Rooms panel">

**Comment by ivan-mogilko** [comment]
I'm sorry, but I'd prefer to close this suggestion. In short, we don't plan any significant editor changes for 3.* now. For more please see the discussion and last comments to #958.
