### ISSUE TITLE
The smallest points has malformed sizes for save and load and quit boxes

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#766]
This is a minor backwards compatibility issue of a very small MAGS game, so if it's too troublesome, no big deal.

https://www.adventuregamestudio.co.uk/site/games/game/2141/

![Screenshot from 2019-05-13 08-21-59](https://user-images.githubusercontent.com/757900/57602929-48c5b880-7558-11e9-997a-edf17f6b3911.png)

The game uses no plugins and this is how it should look:

https://www.youtube.com/watch?v=vFyA9uNsngw

**Comment by ivan-mogilko** [comment]
Wow that's a weird one. Probably some coordinate conversion went wrong.

**Comment by ivan-mogilko** [comment]
Fixed: 405054c1ceb6c0bdc1f797b41f866d8ad9bd05a0

**Comment by i30817** [comment]
fixed
