### ISSUE TITLE
New game 'Guard Duty' might expose a  memory leak

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#773]
So this game has the habit of crashing with things simillar to:

`Error: SpriteCache::removeOldest: Attempted to remove sprite 879 that was either remapped or added externally`

After either some complex graphical effects or some anims.

I've seen 877, 878 too. Anyway the fun thing is that if you restart and reload a game save from later than you started the last time you're probably going to get further. I could just keep increasing the memory with 
```
[misc]
cachemax=...
```
until it works from start to end but I'm unsure that this is how it's supposed to work? I'm up to 300mb right now (307200).

[Steam says it's supposed to use 64mb of memory](https://store.steampowered.com/app/872750/Guard_Duty/) and the default on opensource ags is 128mb. Anyway, i found it suspicious, because it looks like a leak.

**Comment by ivan-mogilko** [comment]
That's not necessarily a memory leak, the error indicates a flaw in internal logic. Which may be also result of some recent changes.

The game was made in 3.4.1, will same thing happen if you use 3.4.1 interpreter?

Could you tell what's the easiest way to reproduce this (like, size of cache, the scene in game)?


PS. Oh, actually there's a rather old ticket related to same error: #201

**Comment by 256colour** [comment]
FWIW, Guard Duty uses the 3.4.15 interpreter.

**Comment by sonneveld** [comment]
How long till you see an issue?

**Comment by i30817** [comment]
I left it to default (that is uninitialized, 128mb) at first, but it crashed during the transition from act 1 to 2. It's difficult to give a savegame or anything because you have to play until the error and if you try to reload the cache is empty so the error delays to another animation.

I'll try to compile a old version and reply later.

**Comment by i30817** [comment]
Ok here is a easy way to reproduce with a save; soon i'll build the actual version of the game ags engine and see if it's a regression:

[Guard Duty Bug [click on knight, enter forest].zip](https://github.com/adventuregamestudio/ags/files/3195416/Guard.Duty.Bug.click.on.knight.enter.forest.zip)

As the filename says, to crash, click on the knight (the save already has the item needed in the 'use' position; lose the 'click game' (you can't win anyway) and when the next act starts click on the forest on the lower right. When the bird takes off, it'll crash here.

**Comment by i30817** [comment]
Turn out that the savegame format is not backwards compatible so i'll just play again until that place to get a new save and test it then. If it doesn't crash it's time to bisect/see if it does later.

**Comment by i30817** [comment]
Here is a old version of the fileformat for the saves with the same idea:

[Guard Duty Bug 2 [click guard, enter forest].zip](https://github.com/adventuregamestudio/ags/files/3195546/Guard.Duty.Bug.2.click.guard.enter.forest.zip)

I'm performing a bisect with it now (it's still a bit tiresome because software mode makes it slow) and we'll see what's what.

**Comment by ivan-mogilko** [comment]
> but with some later versions (but before the savegame became incompatible) it does.
Which versions do you mean?

Personally I had a suspicion there's something broken by this commit:
238a983bf9700a3d5a30368c87558d021a35b87a

**Comment by i30817** [comment]
> Which versions do you mean?
^_^ 
I don't know exactly because i didn't bother tracking down which revision changed the savegame format, i just did `git bisect bad HEAD`, `git bisect good v.3.4.1.14` (after compiling this version saving the game and verifying the sequence worked) and then the midpoint crashed (not had a invalid save), so i know there is a regression.

**Comment by ivan-mogilko** [comment]
I was trying to understand, if you mean before the *new savegame* format become incompatible, or *old savegame* format become incompatible.

**Comment by i30817** [comment]
The first zip up there is the new savegame format, and when i tried to test the regression with it on bisect, the load game screen told me it was incompatible, so i compiled the version of AGS the game was compiled on and created a new save (zip 2) to use on the regression testing.

So it's the first, but i didn't test the second. Is this explanation ok?

**Comment by ivan-mogilko** [comment]
Ok, so the regression is likely in 3.5.0.

**Comment by i30817** [comment]
Actually i just tried to load the old save game in current compile and the menu didn't tell me it was incompatible, it just crashed, if you want to prevent that.

**Comment by ivan-mogilko** [comment]
> Actually i just tried to load the old save game in current compile and the menu didn't tell me it was incompatible, it just crashed on pressing load, if you want to prevent that.

Hmm, actually yes, it is supposed to load older saves. Not sure if I intended to keep this for long, but its still supported.

**Comment by i30817** [comment]
Sorry about not using a debug build but fwiw, here is a backtrace (i'm chasing down the original regression so i'm not on a position to build a current debug build right now):
```

Thread 1 "ags" received signal SIGSEGV, Segmentation fault.
0x0000555555761197 in GameState::ScreenToRoomImpl(int, int, int, bool, bool) [clone .constprop.778] ()
(gdb) bt
#0  0x0000555555761197 in GameState::ScreenToRoomImpl(int, int, int, bool, bool) [clone .constprop.778] ()
#1  0x00005555555d8519 in __GetLocationType(int, int, int) ()
#2  0x00005555555e99cc in GetLocationName(int, int, char*) ()
#3  0x00005555556268c1 in UpdateMouseOverLocation() [clone .lto_priv.1287] ()
#4  0x00005555555835f1 in initialize_start_and_play_game(int, char const*) [clone .constprop.432] ()
#5  0x0000555555633f82 in initialize_engine(std::map<AGS::Common::String, std::map<AGS::Common::String, AGS::Common::String, std::less<AGS::Common::String>, std::allocator<std::pair<AGS::Common::String const, AGS::Common::String> > >, std::less<AGS::Common::String>, std::allocator<std::pair<AGS::Common::String const, std::map<AGS::Common::String, AGS::Common::String, std::less<AGS::Common::String>, std::allocator<std::pair<AGS::Common::String const, AGS::Common::String> > > > > > const&) ()
#6  0x0000555555589b9e in main ()
```

**Comment by i30817** [comment]
Confirmed it was that commit:
```
238a983bf9700a3d5a30368c87558d021a35b87a is the first bad commit
commit 238a983bf9700a3d5a30368c87558d021a35b87a
Author: Ivan Mogilko <ikm_spb@yahoo.com>
Date:   Mon Apr 1 20:50:54 2019 +0300

    Common: SpriteCache should not use sprite offset value unless reading

:040000 040000 a9d0c12e22f0ed7ee6ca8c5a7365a84e56b9e205 083bd309a0154bd7b57dd72548d56256b8057ad9 M	Common
:040000 040000 f33f10fd556095e198e9f9639167b04470f7347a 38969237f1a4e1a2eff443b655ce7643ba488466 M	Engine
```

**Comment by ivan-mogilko** [comment]
I fixed the old save loading, now on to the sprite cache bug.
There's also another issue I noticed, although not a game breaking one: #775.

**Comment by ivan-mogilko** [comment]
Opened pull request: #776
