### ISSUE TITLE
Some old games have their inventory 'empty' after picking up a item.

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#774]
I found this in two free games:

Heartland Deluxe: manipulate the trash bag twice to get a pill bottle, open inventory, nothing.
https://www.adventuregamestudio.co.uk/site/games/game/813/

This city at night: talk to boss then pick up the folder on the IT guy desk, open inventory, nothing
https://www.adventuregamestudio.co.uk/site/games/game/2313/

**Comment by ivan-mogilko** [comment]
Hm, "City at night" is not that old, was made with AGS 3.3.4.

**Comment by ivan-mogilko** [comment]
Pushed a fix: 31ddf0a58e03f1a331cbcef02344af0c1e1115a8

**Comment by i30817** [comment]
Fixed in both games
