### ISSUE TITLE
Translation files not working

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#789]
This may be my imagination or user error, but i suspect translation files are not working. I've seen the behavior in some french games which supposedly have english .tra files and nothing changes, and yes, i've been deleting the copies of acsetup.cfg on the ~/.local/share/ags/GAMENAME dir before testing edits.

For instance, https://github.com/adventuregamestudio/ags/blob/master/OPTIONS.md says i only have to have a section in acsetup.cfg

```
[language]
translation=english2
```

for this game:
https://drive.google.com/uc?id=1m4d89_ogny14T2HBTYn3_lqVFBf5yRjV&export=download

which has a 'english2.tra' file on the game dir and nothing happens and it stays french.

I actually suspect this is another manifestation of the 'linux ags can be installed in a different place than the game data and some code is looking for files on the executable location instead of the dir passed as game data location', just like patches.dat for the MIDI DIGI driver sounds.

**Comment by i30817** [comment]
False alarm, it was just the intro menu on this game.

**Comment by i30817** [comment]
Ok this is a false alarm... i think. The fact that a copy of acsetup.cfg with priority gets written to ~/.local/share/ags/Game/ with that language setting is confusing because it sabotages the main game cfg without user intervention after a single run, but i think that's it.

**Comment by ivan-mogilko** [comment]
> The fact that a copy of acsetup.cfg with priority gets written to ~/.local/share/ags/Game/ with that language setting is confusing because it sabotages the main game cfg without user intervention after a single run, but i think that's it.

If it's confusing, maybe it's wrong? I'd rather investigate this.

**Comment by i30817** [comment]
I suspect that there is assumption people will use winsetup.exe (or similar) always.

Why does it do that ccpy? I can't think of a reason to copy part of the cfg file (only some settings are transferred there). I understand the override possibility on the system save dir is a good idea (on case of read only filesystems it gives a good fallback), but i don't understand why make it happen by 'default'.

Ok, wait, i can think of a reason:
some games have in-game options changes that could use persistence, including language - however i think this is actually not working - anyway, there is the possibility that modifications like those, if they were to be made persistent, are better on the 'override' folder to account for the possibility of read-only game fillesystem.

**Comment by ivan-mogilko** [comment]
The user config is saved because the game location could be read-only.

Initially only winsetup saved into user config, but then I also made engine itself save some of the last settings there, for the reason that -

> some games have in-game options changes that could use persistence, including language

> - however i think this is actually not working, or never did - anyway

Why do you think so? This may be the issue here.

Of course usability issue is also present and may be discussed further.

**Comment by ivan-mogilko** [comment]
Note that the user config path is platform dependent and may even be merged with default config if wanted, as it is done on mobile systems IIRC. In theory it may be possible to do same on Linux (right now it points to XDG_HOME), but idk if that's universally correct.

**Comment by i30817** [comment]
I'm fine with read only being catered for (i plan to place a ags game collection on a read only compressed filesystem), i just find it weird a copy happens when it's not necessary (ie: the original file is writable and the game scripts didn't request a cfg write - if that is even possible).

**Comment by i30817** [comment]
Time to close this? It's user error imo. It's _confusing_ but i don't see a alternative if you want to cater for runtime changes and read only filesystem, and it's only confusing if people don't use winsetup, which most will. I'm willing to accept my own 'leetness' screwed me up here.

**Comment by ivan-mogilko** [comment]
I'd leave this open for now, just don't have spare time at the moment, but I'd like to give this some more thought.

**Comment by ivan-mogilko** [comment]
Opened #975 for future consideration, will close this one.
