### ISSUE TITLE
Crash reporting and statistic submission has stopped working

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#792]
As mentioned in #781.

Once the SSL issue is fixed the response is 500 (Internal Server Error) for crash reporting and statistic submission.

**Comment by ivan-mogilko** [comment]
Do we need to do something with this? Don't remember, if this is editor's fault or server's fault?

**Comment by ericoporto** [comment]
Reports used to go to somewhere on adventuregamestudio.co.uk , this somewhere died. Morgan looked into a ton of other crash report systems, but they all require a person as responsible and he is afraid that if this person ceases to participate the effort to go to the reporting tool will be wasted. The alternative is fixing the website. Regardless, the user will experience the error when sending a report.

**Comment by morganwillcock** [comment]
Yes, this is the story. I'm pretty certain the issue is on the server side, and forwarded the info to AGA and didn't ever hear back. There are various places we could run a replace service (ranging from using something like Azure App Service or AWS Lambda functions, or getting an entire VM to setup as a webserver at GCE), but to get in on a free tier it seems someone needs to sign up to comply with the usage agreements (and in some instances give credit card details).

The most obvious solution is just to disable the crash reporting entirely, unless a clearer replacement is available. I'm not particularly inclined to chase to fix the original server when no-one here actually has access to it and the processing isn't transparent.

**Comment by ivan-mogilko** [comment]
The terrible truth is that these crash reports were majorly ignored for the several years, and we did not have access to them (maybe not everyone know what they are). So, in the open source period of AGS these are rather useless in general.

People post bugs and crashes on forums anyway too.

I guess disabling this feature is okay until better option is present.

**Comment by ivan-mogilko** [comment]
The feature was temporarily disabled until better solution is found.
