### ISSUE TITLE
libpng12.so.0 is missing when compiling to Linux

### ISSUE THREAD

**Issue by alkhimey** [adventuregamestudio/ags#801]
AGS 4.3.4

libpng12.so.0 could be shipped in the lib32/lib64 directories but it is not there.

> 
> $ ./MyGame
> /home/artium/Desktop/Linux-57b42a/Linux/data/ags64: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
> $ ls data/lib32/
> alleg-alsadigi.so  liballeg.so.4.4   libogg.so.0         libvorbis.so.0
> alleg-alsamidi.so  libdumb.so.1      libtheora.so.0      modules.lst
> libaldmb.so.1      libfreetype.so.6  libvorbisfile.so.3
> $ ls data/lib64/
> alleg-alsadigi.so  liballeg.so.4.4   libogg.so.0         libvorbis.so.0
> alleg-alsamidi.so  libdumb.so.1      libtheora.so.0      modules.lst
> libaldmb.so.1      libfreetype.so.6  libvorbisfile.so.3

If this is intentional (ie - assumption that every Linux system must have this lib, please close this issue)

**Comment by ivan-mogilko** [comment]
Probably duplicate: #693
