### ISSUE TITLE
ags3.5: "Unable to find game data file"

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#808]
I'm building AGS ags3, newest version (commit e832a4fc).
I call up the Editor for the program referenced below. 
Compiling it (f7) and clicking on Compiled/Windows/Test01.exe (or …/winsetup.exe) calls up a popup window with the message: “ERROR: Unable to find game data files.”
Same effect when test-running it (f5) from the Editor.

(This program compiles and runs in AGS 3.4.1 without errors.)
[Test01.zip](https://github.com/adventuregamestudio/ags/files/3245522/Test01.zip)

**Comment by ivan-mogilko** [comment]
There's something very strange here. I compile same commit, and do same steps, yet the game runs well (I can see "Hello World" label with input field on screen).

I also noticed that compiled game is larger the the one in your archive, which maybe means that in your case some data was not appended.

**Comment by ivan-mogilko** [comment]
Checking the information on executables found in your archive, the version of the engine is 3.4.2.1, which is a very old dev version of 3.5.0. Have you rebuilt the newest engine also?

**Comment by fernewelten** [comment]
I'll carefully retry and rebuild the steps and report back. But generally, I went in the other direction: from top downwards:

I'm trying to secure a reliable release to base my live tests on. 
- Starting on master, I tried to construct a Hello World adventure and had the editor repeatably crash on me. 
- So I headed over to the ags3 branch, latest version and ran into different problems. 
- So I went back in time and tried a previous release to compile and run. and failed.
- So as a last resort, I looked up the exact version that was claimed to be “stable” on the AGS download page, and tried to get that to compile and run.


After this “adventure” of a different kind, I reconstructed my steps to write up the error reports; I might have left out a recompiling step at that point in time.

**Comment by ivan-mogilko** [comment]
> Starting on master, I tried to construct a Hello World adventure and had the editor repeatably crash on me.

I have to warn that this bug #809 will happen to you regardless of which version you build. It's been in AGS since the beginning of 3.* generation.

> So as a last resort, I looked up the exact version that was claimed to be “stable” on the AGS download page, and tried to get that to compile and run.

3.4.* branch was originally developed with MSVS 2008. We had to do number of steps upgrading it and making sure it compiles on MSVS 2015 and 17, but I guess these steps are not in the release-3.4.3 branch itself, but in next one.

**Comment by fernewelten** [comment]
Okay, carefully recompiling everything makes the problem go away. I seem to be all set. Thanks!
