### ISSUE TITLE
why do savegames save scripts ?

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#811]
i was trying to fix a bug in a game using agsutils' assembler, and recognized that my changes to scriptfiles only take effect if i start a new game. why is that, and isn't it horribly ineffective and space-consuming to save all gamescripts in every savegame file ?

**Comment by ivan-mogilko** [comment]
As far as I know only script variables (values) are saved.

Could you give an example of your changes?

**Comment by rofl0r** [comment]
quest for infamy 1.0.1 (GOG) has the following bug which i fixed:
```diff
--- gamescript14.s
+++ gamescript14.s_fixed_clean
@@ -7061,7 +7061,7 @@
 label000000016443: ; referenced by 1 spots
        sourceline 679
        push op
-       li mar, iKnife
+       li mar, iSwordBastard
        mr ax, mar
        farpush ax
        li mar, cEgo
@@ -7073,7 +7073,8 @@
        farsubsp 1
        pop op
        push ax
-       li ax, 1
+; patch: if have_bastard_sword != 0: jump to good
+       li ax, 0
        pop bx
        cmpeq bx, ax
        mr ax, bx
```
basically they check for whether you have a first generation sword (iKnife) in your inventory, and if so, refuse to upgrade your second generation sword (iSwordBastard) to a 3rd generation sword. this can happen when one (as a sorcerer) finds a bastardsword in the forest, so one carries both an iKnife as well as an iSwordBastard around, which prevents from ever getting the best sword (by buying the upgrade spell from the sorcerer in town.)

if (after my patch) i start a new game with the following cheat to have enough money, and go straight to the sorcerer to buy the updates (use moneybag on mr magic), it will work correctly, but if i use a savegame from before the patch was applied, the old unpatched code is used (presumably stored in the savegame).
the same happened when i added some debug code which was supposed to print stuff using `RawPrint`...

here's the patch for sufficient money:
```diff
--- gamescript0.s.org
+++ gamescript0.s
@@ -270,7 +270,7 @@
 ; unref'd, assuming array member with last known size
 export int drinkLosses = 0
 ; unref'd, assuming array member with last known size
-export int coinBlythos = 3140
+export int coinBlythos = 314
 ; unref'd, assuming array member with last known size
 export int itemcost = 0
 ; unref'd, assuming array member with last known size
```

**Comment by ivan-mogilko** [comment]
Why I doubt that whole scripts may be saved: people often update their games to patch mistakes, and unless they add more data/game objects the old savegames actually work and patches are enabled when player restores old saves.

Here's how script data is saved in new format: https://github.com/adventuregamestudio/ags/blob/master/Engine/game/savegame_components.cpp#L829
"globaldata" is an array where all script's variables are stored. Code itself is in "code" array.
Old format did similar thing.

But the problem is curious... don't have any ideas right now.

**Comment by rofl0r** [comment]
```asm
        li ax, Character::HasInventory^1
; 2100000003000000
        farcall ax
; 2300000001000000
        farsubsp 1
; 1e00000006000000
        pop op
; 1d00000003000000
        push ax
; 060000000300000001000000
        li ax, 1
; 1e00000004000000
        pop bx
; 0f0000000400000003000000
        cmpeq bx, ax
; 030000000400000003000000
        mr ax, bx
; 1c00000010000000
        jzi label000000016505
; 06000000030000008c330000
        li ax, "&3354 You need to upgrade to the bastard sword first."
```
in my savegame file, i can for example find this string of hexadecimal chars:
```
0600000003000000010000001e000000040000000f0000000400000003000000
```
it seems to come directly from gamescript14

**Comment by rofl0r** [comment]
> Here's how script data is saved in new format: https://github.com/adventuregamestudio/ags/blob/master/Engine/game/savegame_components.cpp#L829

https://github.com/adventuregamestudio/ags/blob/master/Engine/game/savegame_components.cpp#L857
so globalscript's data is saved/restored: it probably contains the entire script too

**Comment by sonneveld** [comment]
> so globalscript's data is saved/restored: it probably contains the entire script too

data is different from code though.

**Comment by ivan-mogilko** [comment]
> so globalscript's data is saved/restored: it probably contains the entire script too

IIRC globaldata contains script variable values. I can double check later though.

But I just remembered one reason this may be happening: if you have both old and new game data in same directory. Saved game remembers the name of the data file that was used, and if it's found in the directory then engine switches to it.

**Comment by sonneveld** [comment]
It looks like game.cpp:restore_game_scripts has the same behaviour, it only stores the Data, not code or strings.

So I guess make sure your patching tool isn't modifying the global data section. It looks like you're changing a global variable so it's likely.

**Comment by ivan-mogilko** [comment]
> So I guess make sure your patching tool isn't modifying the global data section. It looks like you're changing a global variable so it's likely.

Only in second case when he was changing starting money value, not in first case when the code itself was changed.

**Comment by sonneveld** [comment]
> Only in second case when he was changing starting money value, not in first case when the code itself was changed. He also mentioned he added "print" commands which did not work.

True. But I suppose there could be other behaviour affected by global variables that is affecting his patch. Hard to say. I suggest maybe @rofl0r could modify the engine to dump scripts to a file and compare.

**Comment by rofl0r** [comment]
> But I just remembered one reason this may be happening: if you have both original and patched game data under different names in same directory. Saves have the name of the data file that was used, and if it's found in the directory then engine switches to it.

hmm, i repacked the changed stuff into a file called test.ags and ran that, but i see in strace that ags accesses `./QFI.exe`. and indeed, the savefile was initially created with that exe. so ags overrides which "pack" it uses, depending on information stored in savefiles ? that's most unexpected.

**Comment by rofl0r** [comment]
> so ags overrides which "pack" it uses, depending on information stored in savefiles

indeed, this is what happens. after removing QFI.exe, my savegame works with the patched code.

i'd argue this is a misfeature, would you agree ?

**Comment by sonneveld** [comment]
> But I just remembered one reason this may be happening: if you have both original and patched game data under different names in same directory. Saves have the name of the data file that was used, and if it's found in the directory then engine switches to it.

Ah, this is to allow RunAGSGame to work when there are multiple exes I suppose?

**Comment by sonneveld** [comment]
> i'd argue this is a misfeature, would you agree ?

This seems to be very specific circumstances. Does the patch work if you only have one game library in the directory?

**Comment by ivan-mogilko** [comment]
> indeed, this is what happens. after removing QFI.exe, my savegame works with the patched code.

> i'd argue this is a misfeature, would you agree ?

Well, yes, this is an awkward legacy feature, and as sonneveld said it was introduced because game may consist of several "minigames" or chapters distributed together (the Yahtzee's 1213 SE could be an example). In such case the save correctly jumps to proper game file even if you commanded to load it from another one.

But I agree it's not always convenient, and maybe we could invent something better.

**Comment by sonneveld** [comment]
> In such case the save correctly jumps to proper game file even if you commanded to load it from another one.

Specifically here: https://github.com/adventuregamestudio/ags/blob/ags3/Engine/ac/game.cpp#L1700

**Comment by sonneveld** [comment]
Do we still allow for registering save game extensions in windows? So users can double click to jump straight into the game? I imagine it would be useful there too, since you would only have one executable registered per extension name.

**Comment by rofl0r** [comment]
> Well, yes, this is an awkward legacy feature

could we make this obsolete ? the old games come with an .exe launcher anyway, and there's probably only a handful using this.

**Comment by ivan-mogilko** [comment]
I think there might be better ways to do same thing, like preload game's header and check for GUID.

And I'd rather consult with game developers who use this multigame technique first before deprecating anything, because they might want to use same behavior on Linux or other platforms.

**Comment by sonneveld** [comment]
> could we deprecate this behavior ? the old games come with an .exe launcher anyway, and there's probably only a handful using this.

Even if deprecated, it will still be default behaviour if you're modifying and running old games.

**Comment by sonneveld** [comment]
Just a comment about the original issue text, 

> isn't it horribly ineffective and space-consuming to save all gamescripts in every savegame file ?

Please don't make rude judgements about the code. Your assumption turned out to be incorrect but there might be reasons for doing something that, to you, seemed "horribly ineffective". 

We're all volunteer contributors here, trying to work on legacy code. There's weird edge cases and stuff that made sense for DOS. We're doing this for fun, there's no need for negativity.

**Comment by rofl0r** [comment]
> Please don't make rude judgements about the code

there's nothing rude about stating a fact: it is indeed ineffective to save the scripts in each savegame, if this would be the case.
"lol your stupid code sucks" would've been rude or negative, but we're having a technical discussion here.

**Comment by sonneveld** [comment]
Ok fine. But this is not a bug. Could you please open another ticket to track mapping save games to the appropriate game file?
