### ISSUE TITLE
Room background of different size causes confusing error with OpenGL or Direct3D renderers

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#817]
Having room frames of different sizes is a mistake, but engine seem to not detect this normally and don't report as a user mistake. Instead it fails in **UpdateDDBFromBitmap** with error:

`"UpdateDDBFromBitmap: mismatched bitmap size"`

which ofcourse is not very useful.
Error itself happens because DDB was created with 1st room frame, but then updated with next one (seek for `gfxDriver->UpdateDDBFromBitmap(roomBackgroundBmp, thisroom.ebscene[play.bg_frame], false);`)

Steps to reproduce:
* Create a new game with 1 room;
* Add more background frames of different sizes.
* Run the game.

---

**MUCH LATER EDIT:**

Some thoughts on how to fix this. Regardless of how the background management is solved, the immediate problem is that the next background frame is updated over to the same texture created for the first background frame. That is a wrong thing to do on its own. Firstly a texture is meant for the particular sprite of certain parameters, and secondly if room background textures are cached at some point we'd have to stop redrawing onto the same texture. So the short-term fix would be to just recreate texture every time background frame changes, and in long-term we'd need a sort of "frame set" cache (and for the regular animations too).

**Comment by ivan-mogilko** [comment]
Fixed by 660857d193b9bcac3a7bb1bba70be8149b1e2d7e

Although, I'm no longer certain how do you make room backgrounds of different sizes, because when you try importing different sized backgrounds in the editor, editor displays an error.
