### ISSUE TITLE
macOS: game colors are incorrect

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#818]
I used the CMake build with the 3.5.0 release branch, game colors are incorrectly represented on the screen.

As an example:

- on the left is a previous macOS build based on the [osx-nick](https://github.com/JanetGilbert/ags/tree/osx-nick) branch
- on the right is the same game running on the release-3.5.0 branch

![mac-3 5 0](https://user-images.githubusercontent.com/14958747/59064177-94daf300-88a1-11e9-8588-17c453f72caf.png)

**Comment by morganwillcock** [comment]
Interestingly, not all elements are affected.

![mac-3 5 0-2](https://user-images.githubusercontent.com/14958747/59065940-cbb30800-88a5-11e9-9045-6c22fd07f999.png)

**Comment by jdiperla** [comment]
Seems it is screwing up more of a maroonish tint and turning it blue.
However on the last image on the right, that general seems to still have
his maroon. Maybe it's a different tint.

**Comment by ericoporto** [comment]
I have flashes, I already saw this bug on Android at some point in the past.

**Comment by ivan-mogilko** [comment]
This may be related to color component offsets:
https://github.com/adventuregamestudio/ags/blob/release-3.5.0/Engine/main/engine_setup.cpp#L216

Perhaps @sonneveld knows which should be correct for mac, he tinkered with them before.

**Comment by morganwillcock** [comment]
> I have flashes, I already saw this bug on Android at some point in the past.

Yes, the byte order was reversed so green remained correct. This does look similar.

**Comment by sonneveld** [comment]
Sorry, currently away from machine but I believe this is an issue with the texture format byte ordering in the allegro patch. It was on my list to look into it.

**Comment by sonneveld** [comment]
Ok, I pushed a first pass at fixing this.

> This may be related to color component offsets:
https://github.com/adventuregamestudio/ags/blob/release-3.5.0/Engine/main/engine_setup.cpp#L216

I find all those colour offsets so confusing. I need to figure out exactly where and when they're all used.

**Comment by sonneveld** [comment]
Could someone please `ags3` now and let me know if it works okay?  I used Contrapasso as the test game (it seems to have a mix of 32bit and 16bit gfx) https://blondbraid.itch.io/commissars-contrapasso

**Comment by ivan-mogilko** [comment]
release-3.5.0 branch may also be tested now after #825 was merged.

**Comment by morganwillcock** [comment]
I've tried the release branch and the problem shifts from the background to the characters.

![mac-3 5 0-3](https://user-images.githubusercontent.com/14958747/59157691-f0c29900-8aa6-11e9-9962-abc4b150733e.png)

**Comment by morganwillcock** [comment]
Second time around the problem was on my end, so this appears to be fixed. Thanks!
