### ISSUE TITLE
Primordia: Deadlock (sound/thread-related?) while walking around

### ISSUE THREAD

**Issue by eriktorbjorn** [adventuregamestudio/ags#82]
This is going to be one of those annoying bug reports, I'm afraid. I'm playing Primordia, using the current git master on Linux.

While walking around, the game sometimes locks up or even crashes for me. I don't know if this only happens inside the UNNIIC, or if it's just that this is where I've done the most to try and reproduce it.

It seems to have something to do with waiting for a mutex to become unlocked, but I can't figure out why. If I interrupt the process when it's hung, gdb points to it waiting for the mutex in update_polled_audio_and_crossfade(). I added a bunch of debug printf()s to the MYSTATICOGG class, and this is the last few messages I got on the last run where it hung:

<pre>
0x86a6fe8: =&gt; MYSTATICOGG::poll()
0x86a6fe8: MYSTATICOGG::poll - Got lock
0x86a6fe8: MYSTATICOGG::poll - Released lock
0x86a6fe8: &lt;= MYSTATICOGG::poll()
0x9cee498: =&gt; MYSTATICOGG::poll()
0x9cee498: MYSTATICOGG::poll - Got lock
0x9cee498: MYSTATICOGG::poll - Released lock
0x9cee498: &lt;= MYSTATICOGG::poll()
0x9cf2338: =&gt; MYSTATICOGG::destroy()
0x9cf2338: MYSTATICOGG::destroy - Got lock (#1)
0x9cf2338: MYSTATICOGG::internal_destroy
0x8835d68: =&gt; MYSTATICOGG::poll()
0x8835d68: MYSTATICOGG::poll - Got lock
0x8835d68: MYSTATICOGG::poll - Released lock
0x8835d68: &lt;= MYSTATICOGG::poll()
0x8395f08: =&gt; MYSTATICOGG::poll()
0x8395f08: MYSTATICOGG::poll - Got lock
0x8395f08: MYSTATICOGG::poll - Released lock
0x8395f08: &lt;= MYSTATICOGG::poll()
0x9cf2338: =&gt; MYSTATICOGG::poll()
0x9cf2338: MYSTATICOGG::internal_destroy: tune is now NULL
0x9cf2338: MYSTATICOGG::destroy - Released lock (#1)
0x9cf2338: MYSTATICOGG::destroy - Got lock (#2)
0x9cf2338: MYSTATICOGG::destroy - Released lock (#2)
0x9cf2338: &lt;= MYSTATICOGG::destroy()
</pre>

The hexadeximal prefix is the value of 'this' and the arrows mark entering/leaving the function. So it seems that in 0x9cf2338, destroy() was called and locked the mutex. Before destroy() had finished, poll() was called. But even though destroy() finished, unlocking the mutex, poll() was still waiting for the lock, and I can't figure out why. Maybe I'm barking up the wrong tree...

On the few times I got a crash instead, this also seemed to happen in connection with destroy(). In one case, gdb claimed that 'tune' had some obviously bogus non-NULL value. Again, I can't figure out why.

**Comment by ivan-mogilko** [comment]
Needs to be retested with 3.5.0 after threaded audio was rewritten.

**Comment by ivan-mogilko** [comment]
I'd like to close this ticket: it's too old and alot of code has changed since. Sound clip struct was fixed few times, audio thread was rewritten for 3.5.0, and there is another complete remake in SDL2 port. So this particular problem may not be aplicable anymore.
At the same time looks like no one is interested in retesting this again.

If there are similar issues found with the contemporary version then a new ticket should be opened.
