### ISSUE TITLE
New game Tales of Jayvin crashes at start

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#822]
Maybe it's better for someone with a account to report here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=57223.0

Anyway in this game::
```

Audio is processed on the main thread
Engine initialization complete
Starting game
An error has occurred. Please contact the game author for support, as this is likely to be a scripting error and not a bug in AGS.
(ACI version 3.5.0.12)

in "Tween module.asc", line 1305
from "Tween module.asc", line 1321
from "Tween module.asc", line 1501
from "Input.asc", line 864
from "GlobalScript.asc", line 3567

Error: A blocking function was called before the first room has been loaded

***** ENGINE HAS SHUTDOWN
```

It can be avoided by setting both of these on acsetup.cfg:

```
[override]
os=win
[graphics]
driver=software
```
Which then starts the game, which i can't control the main menu because i don't have a joypad or functional arrow keys in my broken keyboard.

As i said, maybe the solution here is to do nothing because this is a very early version of the game.

**Comment by ivan-mogilko** [comment]
Have you tried reporting this to game author and see if this is a game bug?

**Comment by i30817** [comment]
that's fine
