### ISSUE TITLE
CI: ags-ci-user unconditionally creates a release out of a new tag

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#826]
Never noticed this before, but I found that ags-ci-user now unconditionally publishes a release when I push a tag to repository.

I think this is not convenient because:
- the tag could've been a mistake and later moved to another commit
- the tag may correspond to a "pre-release".

What are the options to configure this behavior?

E: Or do you think it's okay, and should be edited by hand if necessary?

**Comment by morganwillcock** [comment]
It could be switched to create a draft release, but if the builds come from multiple CI services then perhaps this would be problematic.

https://docs.travis-ci.com/user/deployment/releases/#draft-releases-with-draft-true

Maybe it is easier to configure them to build only when the tag matches a certain format, I think the tag name would be available to all CI services (although configuration may vary between them).

https://docs.travis-ci.com/user/deployment#conditional-releases-with-on

**Comment by ivan-mogilko** [comment]
I think this was solved meanwhile.
