### ISSUE TITLE
Script API: provide access to game config (read & write)

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#827]
Since we have Dictionary class in script API now I thought it could be relatively easier to expose game config into script and allow to read and write it, including add custom user options.

There's a number of things to consider here, like do we support reading/writing arbitrary custom config files also using same API (don't see why not). But config API itself could look something like (rough draft):

<pre>
managed struct Config
{
    readonly attribute int SectionCount;
    readonly attribute Dictionary *Sections[];

    static Config *Load(String filename);
    static Config *LoadUserConfig();

    void Save(String filename);
    void SaveUserConfig();
};
</pre>

**UPDATE:**
Since 3.5.1 File.Open command supports `$CONFIGFILE$` tag and lets open user config, which lets for easier accessing the file without hardcoding where it's located.

So, I think this issue is about reading and writing config format into a struct, for convenience.

**Comment by ivan-mogilko** [comment]
Not sure about this anymore, maybe I'll close as not planned, until someone will bring this up with a better and clear feature proposal.
