### ISSUE TITLE
Is it possible to restore old linker compatibility?

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#838]
At the moment the Linux build doesn't work on the oldest Ubuntu that is available on CI platforms because of the use of `--push-state` and `--pop-state` which aren't supported by older versions of ld:

https://github.com/adventuregamestudio/ags/blob/fac12cf58549a03911523e0b7b0b156f67dc3a7d/Engine/Makefile-defs.linux#L38-L41

Is there an easy alternative that doesn't use these features? I'm not sure this is critical, as building on the next newest Ubuntu release doesn't seem to change the GLIBC requirements (but I don't know enough to know that this is all I should be checking to establish that backwards compatibility for the built binary is the same).

**Comment by rofl0r** [comment]
shouldn't USE_BUILT_IN_LIBSRC be set anyway?

**Comment by morganwillcock** [comment]
That is a good question. Perhaps this was for having a default that works for Debian packaging?

**Comment by rofl0r** [comment]
ah, this is only for dumb and aldumb, i confused it with the libsrc code for alfont and freetype, which now gets used everywhere afaik. yeah, libdumb should not be built by default but shipped with the distro.

**Comment by morganwillcock** [comment]
Current plan is to build on Debian 8 (either chroot or container), so I'll close this.
