### ISSUE TITLE
global config and save-path settings

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#841]
newer engine saves all savegames into $HOME/.local/share.
i personally prefer savegames to go into their respective game-directory, so once you're done with a game you can delete the directory and be done.
especially as directories starting with `.` are by default hidden on UNIX, and gigabytes of data can accumulate.
i think it would be nice if this behaviour could be configured from a global config file.
i looked through the ags manual/help website but couldn't find a reference to this topic.

**Comment by ivan-mogilko** [comment]
There's a way to configure save dir and shared data dir in config, by setting user_data_dir and shared_data_dir options respectively: https://github.com/adventuregamestudio/ags/blob/master/OPTIONS.md#configuration-file-options

Although tbh I don't know how convenient this is, as people usually set these per game.

**Comment by rofl0r** [comment]
thanks, works!
