### ISSUE TITLE
Game.SimulateKeyPress: Map eKeycode to allegro4 keycodes.

### ISSUE THREAD

**Issue by sonneveld** [adventuregamestudio/ags#848]
edit: filling in details. I posted a quick issue to remind me.

Currently Game.SimulateKeyPress does not take into account the difference between the AGS keycodes (which were based on the original Allegro3 codes) and Allegro4 codes (which are different, we convert one way in sys_events).

**Comment by ivan-mogilko** [comment]
To clarify, this is about Game.SimulateKeyPress implementation.

**Comment by sonneveld** [comment]
This is the test game I was using to test the simulate key function.
[kbtest.zip](https://github.com/adventuregamestudio/ags/files/3317971/kbtest.zip)
