### ISSUE TITLE
saving in games that don't offer savegames

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#854]
i started playing a game which is medium-length (takes probably about 6 hrs to play through) which doesn't have a save function. (searching for a way to save i mistakenly quit the game hitting F9). is there a way to save anyway via an engine keyboard shortcut or similar ?

**Comment by ivan-mogilko** [comment]
Not at the moment, but I wanted to add something enabled by "override" config section, because certain games also may have broken save system (this game for instance: https://www.adventuregamestudio.co.uk/site/games/game/1812/) which was never fixed.
