### ISSUE TITLE
Video decoding in linux, available codecs?

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#856]
How does ags decode video files in linux? There is a one room game, [the heist](https://www.adventuregamestudio.co.uk/site/games/game/728/), that uses encoded videos.

```
 1. I don't see the videos
 
    Make sure you have installed the newest DivX codec on your system
    (www.divx.com), it's free. The videos are actually compressed with XviD but
    DivX will decode them by default. If you don't want to download DivX, you can
    download XviD (www.koepi.org) but make sure that in the decoder configuration
    "DIVX" FourCC is checked. FFDShow is another possibility which supports
    multiple codecs.
```

Now granted, i find this absolutely bad, and i don't really want support in ags for random codecs that game makers had the bad idea of using. This is just a question of what framework ags uses to play in linux, so i can see if i can find the right package to make the videos play or if i should just give up on this (very short) game. It's **not** a request to statically link ffmpeg and dodgy codecs.

**Comment by rofl0r** [comment]
one possibility is to extract the game with agstract and then play the embedded videos with mpv

**Comment by i30817** [comment]
They're not embeded, i can play them fine outside. It's more a question of pride you know?

Actually, i decided not to store this game, it's too simple to bother, so i might as well close this.

**Comment by ivan-mogilko** [comment]
AGS historically supported two ways to play video: based on external codecs and played through Windows API and second was based on theora which do not need external codecs.

We had some discussion in the past and I think we mostly agree to deprecate platform-dependent video playback.

I also thought about trying ffmpeg as an option but it may have some licensing and other issues, and I haven't really researched it yet, so do not have an opinion.

**Comment by i30817** [comment]
I gotcha, it's unsupported.

**Comment by ivan-mogilko** [comment]
But I think it is a valid question: how to run old games with non-portable video formats. Maybe worth considering at some point too.

**Comment by i30817** [comment]
BTW, speaking of videos, there is a game that has a extremely slow video in linux even on the hardware renderer. https://www.adventuregamestudio.co.uk/site/games/game/2174/
