### ISSUE TITLE
Android: mouse sensitivity

### ISSUE THREAD

**Issue by Jinx1337** [adventuregamestudio/ags#862]
Would it be possible to add a RELATIVE MOUSE sensitivity setting? I only play games with relative mouse, to the point of actually choosing running games through AGS rather than their native android ports (I hate point and click on a the phone). That's one thing that is severely missing from an otherwise great port.

**Comment by ericoporto** [comment]
I need to check but it should probably be possible to leverage the SDL hint `"SDL_MOUSE_RELATIVE_SPEED_SCALE"`. But I don't know if we can reuse the current speed property or we need a second one. Anyway it needs to be added in the preferences GUI and for that it either has to be added to `android.cfg` or those preferences need to be reworked to work with `acsetup.cfg`.

**Comment by ivan-mogilko** [comment]
What is actually required for completing this? Frankly I'm somewhat confused by the request itself, is it about mouse cursor speed, or else? If speed, then how is it used on Android (touch screen), where afaik you don't move the mouse around, but touch the screen to point at something, and cursor moves instantly (or do I miss something)?

> I need to check but it should probably be possible to leverage the SDL hint "SDL_MOUSE_RELATIVE_SPEED_SCALE"

We have this hint utilized already, so if it's the case, we will only need to add an extra option to Android preferences:
https://github.com/adventuregamestudio/ags/blob/d036374e628aa49ca80e41a343290179adffa6ee/Engine/device/mousew32.cpp#L202-L209

**Comment by ivan-mogilko** [comment]
Now when I learned a bit about how touch-to-mouse emulation works, it looks like this is a matter of applying a factor to the dx,dy for the relative touch movement. Since 3.6.0 we no longer apply mouse Speed ourselves, but only use it to configure SDL2. From the perspective of the mouse emulation, it might be that this change was not a smart move.

There are two possible solutions:
- revert setting SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE and apply it ourselves. This will simultaneously affect Android's touch-to-mouse emulation.
- create a separate speed setting and apply it only for touch-to-mouse logic.

**Comment by ericoporto** [comment]
> We have this hint utilized already, so if it's the case, we will only need to add an extra option to Android preferences

Any reason why that would not just work?

**Comment by ivan-mogilko** [comment]
> > We have this hint utilized already, so if it's the case, we will only need to add an extra option to Android preferences

> Any reason why that would not just work?

That old comment was made at the time when we were using SDL2's own touch-to-mouse function. But the touch-to-mouse emulation that is implemented in the engine now goes around the SDL2's internal options, like the mouse speed. This hint simply will not affect anything.

The approximate scheme looks like this:

<pre>
SDL2: system events ---> apply hints here --->  SDL_Events ---> Engine: touch events handle ---> touch-to-mouse |
                                                     ^                                                          |
                                                     |----------------------------------------------------------|
</pre>

**Comment by ericoporto** [comment]
thanks, I see now. But I think we still need to keep that preference - in the desktop, that is used for the infinite mouse, isn't?

I gave a shot [at creating a preferences entry here](https://github.com/adventuregamestudio/ags/compare/master...ericoporto:ags:android-mouse-speed-preference). But the widget for SeekBarPreference is a bit terrible, not sure if there is a better one for this.

**Comment by ivan-mogilko** [comment]
Actually, somehow I missed the third option: keep the settings as they are and just use existing mouse speed when sending touch-to-mouse events.
This is the simpliest way, and may be enough for mobiles, but I wonder if we may need separate options in case user's device or PC has both touchscreen and mouse present, which may be both used. This is just a theoretical possibility though.
