### ISSUE TITLE
Android: Hardware mode does not work

### ISSUE THREAD

**Issue by Jinx1337** [adventuregamestudio/ags#864]
Newer versions of AGS for ANDROID do not have the HARDWARE mode working properly.

Only software mode generates any graphics, switching to HW only gives black screen with audio playing.

**Comment by ivan-mogilko** [comment]
This is a strange problem, because HW mode works on emulator and on the device I bought for testing purposes. My only guess is that this is all because we are using old fixed OpenGL pipeline there (this is also why shaders don't work correctly even where HW renderer works).

**Comment by Jinx1337** [comment]
I am using a newer snapdragon 855 device, so that might be the case.

**Comment by sonneveld** [comment]
I'm working on an experimental android branch which will hopefully land in 3.5.1. If you'd like to try it out, it is available at https://github.com/sonneveld/ags/tree/android-64bit in the `Android2` directory.

The complete build is done through Android Studio and cmake, but it is pretty straightfoward. The document `Android2/README.md` should help.

**Comment by Jinx1337** [comment]
I would LOVE to test it and report back with my findings; I am, however, too inept to build the release.

Would asking you to compile it for me be too much?
I would really appreciate it (and pay back with some serious testing).

**Comment by ericoporto** [comment]
@Jinx1337 I built  @sonneveld 's branch on my computer, if you want to test, download the .apk below

[app-debug.zip](https://github.com/adventuregamestudio/ags/files/3765203/app-debug.zip)

**Comment by sonneveld** [comment]
Attached is a slightly newer version with the correct icons: [Uploading launcher-debug.apk.zip…]()

**Comment by sonneveld** [comment]
Attached is a slightly newer version with the correct icons: 
[launcher-debug.apk.zip](https://github.com/adventuregamestudio/ags/files/3772422/launcher-debug.apk.zip)

**Comment by Jinx1337** [comment]
I have tested both builds for a couple of hours; my findings so far:

1) Hardware mode is back (Samsung S10+, latest android revison) 
2) Games still randomly crashing, as per my other thread on GitHub :(

Will play around with logcat logs later on and post some info.

**Comment by ivan-mogilko** [comment]
This was resolved by #1190
