### ISSUE TITLE
Installer build issues

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags#875]
**Build issues**
(Mainly for #800)

- [x] Wrapper script doesn't work with all Python versions

Since this also required the win32 API module and calls a Windows binary, there doesn't seem much point in requiring Python here. I've already made a replacement script in Powershell that does the same thing.

- [x] Wildcarded source paths means that the installer will successfully build with some ciritical files missing

I've restructured source directories to there is a clearer separation between what is copied in vs what is already there. The only wildcard paths are now for URL links, Templates, and sub-directories of Linux build components (these are not optional though).

- [x] Requires vcredist_x86-9.0.30729.6161.exe to be present, which is now the wrong version and I'm not sure 100% sure whether these are allowed to be distributed

I've re-implemented this as a registry check and also added a checksum verification to the build script to be 100% sure that the version being included is the correct one.

- [x] .NET 4.5 version check and installation

I've updated the registry check and updated the download URL to go to the current  .NET Framework downloads page

- [x] Filename collision for different versions

Filename now uses the longer version (sp text was already included)

**Compiler warnings**
(tested with Inno Setup 6.0.2)

- [x] Warning: Constant "pf" has been renamed. Use "commonpf" instead or consider using its "auto" form.

Renamed to use the 32 bit equivalent (in-case the registry checks ever need the installer to run in 32 bit mode)

- [x] Warning: The [Setup] section directive "PrivilegesRequired" is set to "admin" but per-user areas (userappdata) are used by the script. Regardless of the version of Windows, if the installation is running in administrative install mode then you should be careful about making any per-user area changes: such changes may not achieve what you are intending. See the "UsedUserAreasWarning" topic in help file for more information.

I've removed all the quick launch stuff.

- [x] Warning: Line 145, Column 37: [Hint] Support function "IsComponentSelected" has been renamed. Use "WizardIsComponentSelected" instead.

Renamed.

**Comment by sonneveld** [comment]
Powerscript is probably the better option here. I just have zero experience with it so I stuck with what I knew!

Unless something has changed you should still be able to bundle the redist package. I think Microsoft only explicitly forbids bundling the debug version.

**Comment by ivan-mogilko** [comment]
I may look into InnoSetup warnings; existing script was written for InnoSetup 5 though.

**Comment by morganwillcock** [comment]
I'll probaby go through it today. I was most worried about the user appdata warning, as this implies the logic is broken. I think it is actually just this:
```
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\AGS {#AgsFriendlyVersion}"; Filename: "{app}\AGSEditor.exe"; Tasks: quicklaunchicon
```
...which will break if the uninstalling user is the installing user, but I think it can just be removed because past Windows XP there is no built-in quick launch launcher.

**Comment by morganwillcock** [comment]
Can I also suggest that we change the installer filename to reference the full version number?

`AGS-3.5.0.exe` makes it tricky to tell which version it is and means the installers for later versions cannot be stored in the same directory.

**Comment by ivan-mogilko** [comment]
> Can I also suggest that we change the installer filename to reference the full version number?

IIRC at some point in the past the installer was named as x.x.x-NN.exe, where NN was something like Beta1, RC (release candidate), P1 (patch 1) etc. Or maybe I was naming it by hand.

Guess full version will work too.

**Comment by morganwillcock** [comment]
> IIRC at some point in the past the installer was named as x.x.x-NN.exe, where NN was something like Beta1, RC (release candidate), P1 (patch 1) etc. Or maybe I was naming it by hand.

All the version strings are passed in, so it is probably not too hard to also include the special name in the filename where it is set.

This Visual C++ runtime issue is quite tricky, I don't beleive the previous detection method will give the correct result: Since all runtime is now backwards compatible to 2015, when you install the runtime for 2019 or 2017 you effectively also get 2015, but the MSI package ID will be different. It looks like you can query the 2015 build level in the registry, but I'll have to investigate a little more.

**Comment by morganwillcock** [comment]
.NET looks a little more straight-forward and is documented:

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#find-newer-net-framework-versions-45-and-later

> Check for a DWORD entry named Release. If it exists, then you have .NET Framework 4.5 or later versions installed. Its value is a release key that corresponds to a particular version of the .NET Framework. In the following figure, for example, the value of the Release entry is 378389, which is the release key for .NET Framework 4.5.

**Comment by ericoporto** [comment]
@morganwillcock this is finished, right?

**Comment by morganwillcock** [comment]
If PR is accepted.
