### ISSUE TITLE
harry potter rpg crash bug

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#880]
on the current 3.5.0 branch

game is here:
https://drive.google.com/file/d/18_8Y7zs-cg47Wn10NX641vCjV-Rv3y2A/view

crash occurs when you go to gringots (after chargen, which also has a focus bug on the last name and first name text entries being written/selected at the same time, which can be avoided with enter but is not necessary in the original), talking to the goblin teller and asking for the number of galleons in the bank crashes the game with:
```
An error has occurred. Please contact the game author for support, as this is likely to be a scripting error and not a bug in AGS.
(ACI version 3.5.0.14)

in "Dialog 1", line 30

Error: Error running function '_run_dialog1':
Error: ScriptSprintf: formatting argument 1 is expected to be a string, but it is a null pointer


***** ENGINE HAS SHUTDOWN
```

So it appears that the new version of the engine might be somewhat stricter about null strings, though you're supposed to start with 50g so maybe the problem is it being null at all instead.

Also the mouse cursor behaves weird compared to the original imo. Clicks are often not recognized as interaction until you right click into the 'magnifying glass' alt cursor mode and back, while the original exe didn't have this problem.

**Comment by ivan-mogilko** [comment]
There supposed to be a compatibility mode for older games that prints `(null)` for pointers, but maybe the condition is incorrect.
Also, I've been thinking, maybe it would be better to just apply the old unrestrictive behavior to every game.

**Comment by i30817** [comment]
The mouse behavior i complained about is a false alarm I think. I didn't notice that there are 3 mouse pointer types in the game, not two (two types of wand, one for interaction and another just for walking).

**Comment by ivan-mogilko** [comment]
Sorry for delay. I tried but could not reproduce the bug, it correctly sais "you have 50 galleons".
(BTW the game is made in AGS 3.4.0 where using null pointer in formatting will cause the crash originally)

Do you have a save game before this happens?

**Comment by i30817** [comment]
Interesting, i also couldn't reproduce with the default character, but restarting the game and changing the character characteristics on chargen a bit got a even more amusing result that also crashes there (check the size of the pc avatar when not moving).

[Harry Potter RPG.zip](https://github.com/adventuregamestudio/ags/files/3490970/Harry.Potter.RPG.zip)


I believe this may be caused by the player name overflowing because of bad, no good code in the original game. The game is supposed to allow you to change your name and surname as mentioned, but in the recent engine, those two boxes are both 'focused' and the keyboard fills both. The chargen screen mentions that the enter key serves to change and you can change the surname that way, but i suspect something goes very wrong then.

**Comment by i30817** [comment]
edit: i edited out the save because i mistankely posted the wine version save that is different from what i wanted to post.

**Comment by ivan-mogilko** [comment]
The texbox focus seems to be a problem with current version, because it did not happen in original game. I will look into this.

Regarding the crash itself, it crashes because the first formatting argument is null, which is character's name (number of money is second arg).

**Comment by ivan-mogilko** [comment]
I think I found the commit that broken text boxes: 9ef053af6f9101fafb912dca10e405bddee29347

**Comment by ivan-mogilko** [comment]
Fixed the textbox focus problem: a3e3d1106904e5c2d90de9c98a656acf629d3bc8

**Comment by i30817** [comment]
Ok i tested it, the textbox is solved, but the crash isn't. In short, i think it's a bug in the game when you select a girl pc instead of male and go to the bank. Maybe close?

**Comment by ivan-mogilko** [comment]
Oh okay.
Here's the game forum thread btw, it's relatively recent:
https://www.adventuregamestudio.co.uk/forums/index.php?topic=57326.0
