### ISSUE TITLE
Compiler fails on Debian 10

### ISSUE THREAD

**Issue by VanStam** [adventuregamestudio/ags#887]
Fresh Debian 10 install 64bit.
Followed REAMDE.MD. installed depedencies, git cloned repository, however building the package fails complaining about invalid use of incomplete type structs.

`dh binary --parallel --buildsystem makefile
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/van/Downloads/ags'
make --directory=Engine
make[2]: Entering directory '/home/van/Downloads/ags/Engine'
CFLAGS = -O2 -g -fsigned-char -fno-strict-aliasing -fwrapv -Wunused-result -Wno-unused-value -Werror=write-strings -Werror=format -Werror=format-security -Werror=implicit-function-declaration -DNDEBUG -DALLEGRO_STATICLINK -DALLEGRO_NO_COMPATIBILITY -DALLEGRO_NO_FIX_ALIASES -DALLEGRO_NO_FIX_CLASS -DLINUX_VERSION -DBUILTIN_PLUGINS -DHAVE_FSEEKO -DDISABLE_MPEG_AUDIO -DAGS_CASE_SENSITIVE_FILESYSTEM -DAGS_HAS_CD_AUDIO -DAGS_RUNTIME_PATCH_ALLEGRO -D_FILE_OFFSET_BITS=64 -DRTLD_NEXT -I ../Engine/libsrc/freetype-2.1.3/include -g -O2 -fdebug-prefix-map=/home/van/Downloads/ags=. -fstack-protector-strong -Wformat -Werror=format-security -I../Engine -I../Common -I../Common/libinclude -I../Plugins -I../Engine/libsrc/glad/include 

CXXFLAGS = -std=c++11 -Werror=delete-non-virtual-dtor -g -O2 -fdebug-prefix-map=/home/van/Downloads/ags=. -fstack-protector-strong -Wformat -Werror=format-security -O2 -g -fsigned-char -fno-strict-aliasing -fwrapv -Wunused-result -Wno-unused-value -Werror=write-strings -Werror=format -Werror=format-security -Werror=implicit-function-declaration -DNDEBUG -DALLEGRO_STATICLINK -DALLEGRO_NO_COMPATIBILITY -DALLEGRO_NO_FIX_ALIASES -DALLEGRO_NO_FIX_CLASS -DLINUX_VERSION -DBUILTIN_PLUGINS -DHAVE_FSEEKO -DDISABLE_MPEG_AUDIO -DAGS_CASE_SENSITIVE_FILESYSTEM -DAGS_HAS_CD_AUDIO -DAGS_RUNTIME_PATCH_ALLEGRO -D_FILE_OFFSET_BITS=64 -DRTLD_NEXT -I ../Engine/libsrc/freetype-2.1.3/include -g -O2 -fdebug-prefix-map=/home/van/Downloads/ags=. -fstack-protector-strong -Wformat -Werror=format-security -I../Engine -I../Common -I../Common/libinclude -I../Plugins -I../Engine/libsrc/glad/include 

MMFLAGS = 

LDFLAGS = -Wl,-z,relro -rdynamic -Wl,--as-needed 

LIBS = -Wl,-Bdynamic -lalleg -lX11 -logg -ltheora -logg -lvorbis -lvorbisfile -ldl -lpthread -lc -lm -lstdc++ -Wl,--push-state,-Bstatic -laldmb -ldumb -Wl,--pop-state 

../Plugins/agspalrender/ags_palrender.o
../Plugins/agspalrender/ags_palrender.cpp: In function ‘int agspalrender::DrawReflections(int, int)’:
../Plugins/agspalrender/ags_palrender.cpp:1624:65: error: invalid use of incomplete type ‘struct AGSCharacter’
  if (Reflection.Characters[id].replaceview == 0) view = currchar->view+1;
                                                                 ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1626:51: error: invalid use of incomplete type ‘struct AGSCharacter’
  AGSViewFrame *vf = engine->GetViewFrame (currchar->view+1,currchar->loop,currchar->frame);
                                                   ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1626:68: error: invalid use of incomplete type ‘struct AGSCharacter’
  AGSViewFrame *vf = engine->GetViewFrame (currchar->view+1,currchar->loop,currchar->frame);
                                                                    ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1626:83: error: invalid use of incomplete type ‘struct AGSCharacter’
  *vf = engine->GetViewFrame (currchar->view+1,currchar->loop,currchar->frame);
                                                                      ^~

In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1627:43: error: invalid use of incomplete type ‘struct AGSViewFrame’
  charsprite = engine->GetSpriteGraphic (vf->pic);
                                           ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:89:8: note: forward declaration of ‘struct AGSViewFrame’
 struct AGSViewFrame;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1628:25: error: invalid use of incomplete type ‘struct AGSCharacter’
  long scaling = currchar->flags & CHF_NOSCALING;
                         ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1628:35: error: ‘CHF_NOSCALING’ was not declared in this scope
  long scaling = currchar->flags & CHF_NOSCALING;
                                   ^~~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1629:55: error: invalid use of incomplete type ‘struct AGSCharacter’
  if (!scaling)scale = engine->GetAreaScaling (currchar->x,currchar->y);
                                                       ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1629:67: error: invalid use of incomplete type ‘struct AGSCharacter’
  if (!scaling)scale = engine->GetAreaScaling (currchar->x,currchar->y);
                                                                   ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1631:16: error: invalid use of incomplete type ‘struct AGSCharacter’
  cox = currchar->x;
                ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1632:16: error: invalid use of incomplete type ‘struct AGSCharacter’
  coy = currchar->y;
                ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1633:16: error: invalid use of incomplete type ‘struct AGSCharacter’
  coz = currchar->z;
                ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1639:49: error: invalid use of incomplete type ‘struct AGSObject’
   charsprite = engine->GetSpriteGraphic (currobj->num);
                                                 ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1641:47: error: invalid use of incomplete type ‘struct AGSObject’
   else scale = engine->GetAreaScaling (currobj->x,currobj->y);
                                               ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1641:58: error: invalid use of incomplete type ‘struct AGSObject’
   else scale = engine->GetAreaScaling (currobj->x,currobj->y);
                                                          ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1642:16: error: invalid use of incomplete type ‘struct AGSObject’
   cox = currobj->x;
                ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1643:14: error: invalid use of incomplete type ‘struct AGSObject’
   if (currobj->baseline < 0) coy = currobj->y;
              ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1643:43: error: invalid use of incomplete type ‘struct AGSObject’
   if (currobj->baseline < 0) coy = currobj->y;
                                           ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1644:21: error: invalid use of incomplete type ‘struct AGSObject’
   else coy = currobj->baseline;
                     ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1706:42: error: invalid use of incomplete type ‘struct AGSCharacter’
  flipped = sfGetGameParameter(13,currchar->view+1,currchar->loop,currchar->frame);
                                          ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1706:59: error: invalid use of incomplete type ‘struct AGSCharacter’
  flipped = sfGetGameParameter(13,currchar->view+1,currchar->loop,currchar->frame);
                                                           ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:1706:74: error: invalid use of incomplete type ‘struct AGSCharacter’
 pped = sfGetGameParameter(13,currchar->view+1,currchar->loop,currchar->frame);
                                                                      ^~

In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp: In function ‘int agspalrender::AGS_EngineOnEvent(int, int)’:
../Plugins/agspalrender/ags_palrender.cpp:2124:17: error: invalid use of incomplete type ‘struct AGSCharacter’
     if (tempchar->room != engine->GetCurrentRoom ()) continue; //if character isn't even in the room, go to next iteration.
                 ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2125:24: error: invalid use of incomplete type ‘struct AGSCharacter’
     int32 vx = tempchar->x;
                        ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2126:24: error: invalid use of incomplete type ‘struct AGSCharacter’
     int32 vy = tempchar->y;
                        ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2128:54: error: invalid use of incomplete type ‘struct AGSCharacter’
     AGSViewFrame *vf = engine->GetViewFrame (tempchar->view+1,tempchar->loop,tempchar->frame);
                                                      ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2128:71: error: invalid use of incomplete type ‘struct AGSCharacter’
   AGSViewFrame *vf = engine->GetViewFrame (tempchar->view+1,tempchar->loop,tempchar->frame);
                                                                     ^~

In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2128:86: error: invalid use of incomplete type ‘struct AGSCharacter’
  *vf = engine->GetViewFrame (tempchar->view+1,tempchar->loop,tempchar->frame);
                                                                      ^~

In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:87:8: note: forward declaration of ‘struct AGSCharacter’
 struct AGSCharacter;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2129:39: error: invalid use of incomplete type ‘struct AGSViewFrame’
     int w = engine->GetSpriteWidth (vf->pic);
                                       ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:89:8: note: forward declaration of ‘struct AGSViewFrame’
 struct AGSViewFrame;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2130:40: error: invalid use of incomplete type ‘struct AGSViewFrame’
     int h = engine->GetSpriteHeight (vf->pic);
                                        ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:89:8: note: forward declaration of ‘struct AGSViewFrame’
 struct AGSViewFrame;
        ^~~~~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2141:17: error: invalid use of incomplete type ‘struct AGSObject’
     if (!tempobj->on) continue;
                 ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2142:23: error: invalid use of incomplete type ‘struct AGSObject’
     int32 vx = tempobj->x;
                       ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2143:23: error: invalid use of incomplete type ‘struct AGSObject’
     int32 vy = tempobj->baseline - tempobj->y;
                       ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2143:43: error: invalid use of incomplete type ‘struct AGSObject’
     int32 vy = tempobj->baseline - tempobj->y;
                                           ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2145:46: error: invalid use of incomplete type ‘struct AGSObject’
     int32 w = engine->GetSpriteWidth (tempobj->num);
                                              ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
../Plugins/agspalrender/ags_palrender.cpp:2146:47: error: invalid use of incomplete type ‘struct AGSObject’
     int32 h = engine->GetSpriteHeight (tempobj->num);
                                               ^~
In file included from ../Plugins/agspalrender/ags_palrender.cpp:31:
../Engine/plugin/agsplugin.h:88:8: note: forward declaration of ‘struct AGSObject’
 struct AGSObject;
        ^~~~~~~~~
make[2]: *** [Makefile:64: ../Plugins/agspalrender/ags_palrender.o] Error 1
make[2]: Leaving directory '/home/van/Downloads/ags/Engine'
make[1]: *** [debian/rules:22: override_dh_auto_build] Error 2
make[1]: Leaving directory '/home/van/Downloads/ags'
make: *** [debian/rules:16: binary] Error 2
`

**Comment by ivan-mogilko** [comment]
agspalrender is still not compilable on master branch.

**Comment by VanStam** [comment]
You are right, release-3.5.0 compiles succesfully. Thanks
