### ISSUE TITLE
MIDI patch files for the DIGI driver (software synth) are not picked up in the game dir 

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#896]
This can easily be tested on a linux with a recent ags with this zip:
[Murder In A Wheel.zip](https://github.com/adventuregamestudio/ags/files/3538171/Murder.In.A.Wheel.zip)

This game has a 'jingle' that is not using midi on the studio logo, wait for the 'new game menu' with a mansion to appear. If you wait a few seconds and it has no music, midi is not working.

The game is configured with midiid=DIGI (to force it) and has the unzipped patches.dat from some site i forget in the game root. However, the music will only appear if the patches.dat file is copied or moved to the $HOME.

Presumably it would also work to set the ALLEGRO env variable to a absolute path before starting the ags executable, or to place the file on the default ALLEGRO dir, but i didn't try it.

I think this is not intended and placing the file in the game dir is supposed to work, for game devs to distribute stuff without weird cmd line batch files (that would have to figure out the current absolute dir) or asking the user to mess with the filesystem.

Since allegro was going to be updated i was thinking of asking for a setting for this that turns a relative path to the game dir to absolute one and feeds it to allegro for this, but on second thought the game dir working for this is always fine because its also 'runtime portable' and hardlinks and deduplication in squashfs exist to share the patches file and has the further advantage of not changing the cfg format.

**Comment by rofl0r** [comment]
confirmed. it puzzled me since quite some time why midi music wasn't working in any game, but it didn't occur to me that it was due to a missing soundfont file in $HOME.

**Comment by ivan-mogilko** [comment]
Maybe related older issue: #760 (although frankly I failed to understand what was required in #760 last time, maybe need to re-read everything again)

**Comment by rofl0r** [comment]
in case this can be influenced with an env var as mentioned by OP, it could be sufficient to set that var with setenv() to the path containing the game executable.

**Comment by i30817** [comment]
I'd forgotten about that issue. Frankly i think this is the same, just better explain without the fumbling to try to find what the issue was.

**Comment by necros2k7** [comment]
does DIGI give some kind of "better" music, tried both modes - with patches.dat sounds more toonish

**Comment by i30817** [comment]
Some sound cards don't have midi synthesizers so the users have to use the software synth to get music on those games.

**Comment by necros2k7** [comment]
Can you give an example of what modern sound cards have no midi synthesizer?

**Comment by i30817** [comment]
I don't know about modern, but my portable motherboard from 2009 can't run midi without a synth server on which i don't turn on, because i abhor having a daemon wasting cpu running waiting for midi.

Thus the DIGI driver is the only one that works, or will ever work for MIDI here. Similarly i doubt devices like the raspberry pi come with timidity or fluidsynth on, and if they did, that would be one of the first things i'd uninstall.

**Comment by necros2k7** [comment]
As a Win desktop user I assume I should delete patches.dat and forget this issue?)

**Comment by i30817** [comment]
Only if you want a bad surprise when you move the game to a device without driver midi support and the fallback falls when this issue is fixed.

**Comment by legluondunet** [comment]
Could Wildfire be a better choice for AGSto play midi music on all platform?
https://www.mindwerks.net/projects/wildmidi/
https://github.com/Mindwerks/wildmidi

**Comment by ericoporto** [comment]
Reading this I still don't understand where midi directory is picked from: https://github.com/liballeg/allegrowww2/blob/master/en/digmid/digmid

> # MIDI patch sets
> 
> The DIGMID wavetable music driver needs a set of instrument samples, which can
> either be in the GUS patch or SoundFont 2.0 formats. GUS patches can be read
> directly from disk or converted into a single patches.dat file with the pat2dat
> utility. SoundFont banks must be converted prior to use.
> 
> A GUS patch set consists of around 180 .pat instrument files, plus a
> default.cfg index file listing which patch goes with each MIDI program number.
> To use these files directly, point the "patches=" line in your allegro.cfg at
> the default.cfg file. To convert them into the patches.dat format, run "pat2dat
> -o patches.dat samplepath\default.cfg -8", and then copy the resulting
> patches.dat into either the same directory as your program, the location
> pointed to by the ALLEGRO environment variable, or the location specified by
> the "patches=" line in your allegro.cfg.

Not sure if these docs are for our version of allegro: https://liballeg.org/stabledocs/en/alleg027.html#load_midi_patches

 Apparently Allegro has a config file on etc: https://stackoverflow.com/questions/45665743/mid-not-playing-with-allegro-4-on-ubuntu-14-04?r=SearchResults

**Comment by i30817** [comment]
That file does not exist here. Probably because AGS bundles allegro, it doesn't link it from the system iirc.

**Comment by i30817** [comment]
Ok before AGS 3.5 is completely abandoned by the compatibility breaking AGS 4.0, could this bug be fixed? It's pretty much the largest annoyance that is not a incompatible library or a game using another kind of fork in its code.

**Comment by ivan-mogilko** [comment]
I set this for 3.5.1 milestone for now.

Anyway, 3.5 is not going to be thrown out, fixes that don't require large rewrite are still allowed here.

**Comment by ericoporto** [comment]
This needs allegro label too.

**Comment by ivan-mogilko** [comment]
After investigating Allegro's algorithm that searches for patches.dat (and resources in general), it's apparent that it may search at the executable's directory, but it obviously does not know how to check in the game's directory if it differs (and if it's run with ags engine installed somewhere in system it's most definitely a case).

There's a hope though, Allegro 4 provides a system driver's callback `find_resource`, which we may utilize and search in our custom location. I'll look into this direction.

**Comment by ivan-mogilko** [comment]
Opened pr #1114 
@i30817 , could you try that and see if it fixes your problem?

**Comment by i30817** [comment]
It solves the problem. And in conjunction with hardlinks i don't even need to waste space or risk a game losing the soundfont when i copy it elsewhere like a symlink. I'm satisfied.

**Comment by ivan-mogilko** [comment]
> Just to be clear (since it doesn't matter since i'm going to delete the home dir soundfont), the order of checking the game dir for these soundfont resources is after or before the HOME dir?

Our custom location is checked the last:
https://github.com/adventuregamestudio/lib-allegro/blob/allegro-4.4.3.1-agspatch/src/file.c#L1246
