### ISSUE TITLE
Kathy Rain crashes attempting to read [sound] tags from the save dir acsetup.cfg

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#898]
It's as i said, so i'm requesting that the 3 volume properties, or maybe just the `[sound]` tag is written to the copy of `acsetup.cfg` that the ags engine does to the savedir.

Context: https://github.com/rofl0r/agsutils/issues/3#issuecomment-524700636

I found this while testing my replacement for the fallback `else` on the script file read/write for the read only filesystem. I noticed Kathy Rain was crashing after the first start, verified it started after the first start if I copied the whole game dir `acsetup.cfg` to the save dir that it was now attempting to read from\*, and minimized the number of settings until i found what was crashing if missing.

It's not completely surprising since the game has a option menu with all of the properties on the save dir copy of the .cfg, except it also had volumes. It's probably bad error handling.

\*(before that in linux it read `./acsetup.cfg` because '.' was the default dir give as the shared system dir in linux)

**Comment by ericoporto** [comment]
I don't think ags should bend to nonstandard usage of config files, specially if such crash is because the developer didn't check if the file existed before reading.

**Comment by i30817** [comment]
It's not the file existing that is the problem, it's the [sound] section inside the file.

**Comment by ivan-mogilko** [comment]
> It's not the file existing that is the problem, it's the [sound] section inside the file.

Sounds like this is a scripting mistake. I think it should be reported to the game developer, because the file or section could be missing for various reasons too.

> A easy way to fix this particular case that is probably easier (but will make these files marginally larger) is to copy the speechvol, musicvol, mastervol in the [sound] section of the original file if they exist to the savedir acsetup.cfg, just like it already copies some properties.

These settings that you list are not even standard in ags config. They are custom settings, and engine is not aware of these. Engine only writes those settings to user config that it's aware of and aware that they are changing at runtime and restored on game launch.

**Comment by ivan-mogilko** [comment]
I think an alternate solution to consider is to actually have script API to write and read user config. That would cover everything.

We have a Dictionary class in script since recently, perhaps that could be reused for this purpose too.

**Comment by i30817** [comment]
> These settings that you list are not even standard in ags config. They are custom settings, and engine is not aware of these. Engine only writes those settings to user config that it's aware of and aware that they are changing at runtime and assigned from config on game launch.

Huh. I had the idea they were because of the 'standard sounding name'. But sort of good news, i found a workaround.

Just set `midiid=NONE` in the original game acsetup.cfg. That one *is* a standard option and it *does* get copied the first time, creating the `[sound]` section and thus letting the game itself write the volume stuff it wants (though it probably is ignored).

**Comment by i30817** [comment]
My guess is this can be closed, unless you want it kept open for people searching for it to find the workaround?

**Comment by ivan-mogilko** [comment]
Alright. But I'd also suggest discussing all this with original authors, because if they are using custom engine and/or custom plugins they are also kind of responsible to cover player problems.
