### ISSUE TITLE
Script API: get resolved script path

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#899]
https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/file.cpp#L277

This function enables the file open and write to have access to really useful tokens. Unfortunately, the resolved path is not available for a script be able to print the resulting path string from the game itself.

It would be useful to preprocess through script a file path and pass the resulting path to a plug-in API that implements their own file write and open operations.

**Comment by ivan-mogilko** [comment]
What about passing token path to plugin and add plugin API function that asks engine to convert to real path?

But I guess, there will always be ways to expose actual paths to script, so it will be unsafe anyway.

**Comment by ivan-mogilko** [comment]
Yes that will be easy to make.

**Comment by ericoporto** [comment]
The PR in #2056 closes this
