### ISSUE TITLE
Implement old path finding for legacy (< v3.5) games

### ISSUE THREAD

**Issue by sonneveld** [adventuregamestudio/ags#903]
(creating for tracking, will add details)

**Comment by i30817** [comment]
I'm sure you known but the sumatra path of yandi game has a example of a bug caused by this change about midway through, and there is a savegame there to test it if you want.

**Comment by ivan-mogilko** [comment]
#784

**Comment by ivan-mogilko** [comment]
Also, not necessarily but could be: #663

**Comment by morganwillcock** [comment]
Reimplemented in #904
