### ISSUE TITLE
Script API: add coordinate offset to Character.FollowCharacter

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#920]
This is a suggestion from user.

> I think a great thing would be to add an optional x- and y- offset for the FollowCharact(_EXACTLY) function, because this way you could very easily add shadow below the character without messing up baselines

**Comment by ericoporto** [comment]
A reminder that this offset needs to also be serialized.

**Comment by ivan-mogilko** [comment]
Hmm, this is stupid, why I did not think before posting this, but the same effect could be easily achieved by just assigning character's coordinates in rep_exec_always, is not it.
