### ISSUE TITLE
make button animation accept flipped frames

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#931]
While editing the manual I found this:

https://github.com/adventuregamestudio/ags-manual/wiki/Button#animate
NOTE: This command does not support flipped view frames. Any frames marked as "Flipped" will in fact be drawn normally when on a button.

Is there any reason to not accept flipped frames from a view for an animation based on the loop in a view like it would be the expected behavior of the engine? No? Please add this.

**Comment by ivan-mogilko** [comment]
Fixed by #1944 in ags4 branch.
