### ISSUE TITLE
Room MaskResolution impacts character WalkSpeed

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#936]
If Room MaskResolution is a different value from 1:1, like 1:2, it will change a character observed WalkSpeed, because he was set with room pixels in mind but he will consume the path in mask coordinates. Ideally, MaskResolution should influence the Pathfinder/Walk so that the WalkSpeed used is transparent (2 meaning 2 in room coordinates and 1 in mask coordinates for the 1:2 example).

**Comment by ivan-mogilko** [comment]
If fixed in ags3 branch, this would need a switch in "Backward Compatibility" section of General Settings which alternates between uniform speed and speed dependent on room mask.

**Comment by ivan-mogilko** [comment]
This should be solved with addition of a new setting (#943)
