### ISSUE TITLE
On Room Editor, Mouse middle click doesn't trigger sometimes or wrongly triggers

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#938]
When the Editor is loaded, it's expected to be able to use mouse middle click anywhere to copy coordinates. This doesn't work all the time. Additionally, mouse middle click sometimes fires unexpected events: if you are editing a room mask and has rectangle selected, if you use middle click, instead of copying the coordinates it will draw a rectangle, with the initial point of the rectangle being from somewhere, accounting the middle click as a release like if you were previously holding and just released the left button.

**Comment by ivan-mogilko** [comment]
I did a small change: fed0cc018b98970b1bda6a12ce0bd90223f02c70

**Comment by ericoporto** [comment]
Ok, I downloaded [the build here](https://cirrus-ci.com/task/5387046016778240) which includes your change, and it fixed for me! Thank you so much! :D I also don't have it randomly not working like before for me (but I don't know why). This can be closed now.
