### ISSUE TITLE
Script API: consider change meaning of undefined Object.SetView's parameters

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#940]
Apparently, **Object.SetView** function has a pretty counter-intuitive behavior if you skip optional arguments:

From the manual:
> Object.SetView(int view, optional int loop, optional int frame)

> Sets the object's view to VIEW, and changes the object's graphic to FRAME of LOOP in VIEW. If you do not supply the loop or frame, **they will be left unchanged**.

TBH I think this was a very bad decision to make this a default behavior. Maybe it was made by mistake and then left for compatibility reasons?
Something tells me user would rather expect loop and frame reset to 0 if they are not specified (and looking at existing scripts that is the case).

This may lead to weird issues, for example if the last frame in the previous view matches a frame with linked sound in a new view. Then a sound may be played unexpectedly, and users will have hard time realizing what is going on. (This happened just today, and made me write this ticket)

My suggestion is following:
* By default (if optional arguments are not specified) set loop and frame to 0.
* Old behavior may be kept for backwards compatibility, under a condition checking game format index, or maybe script API (OPT_BASESCRIPTAPI) (?).

User may still ask to keep previous loop & frame by passing Object.Loop and Object.Frame respectively, e.g.:
`oObject.SetView(10, oObject.Loop, oObject.Frame);`

**UPDATE**: 
I'd like to elaborate more on my opinion about this.

Characters are quite different from objects, because they are complex systems which have a concept of "direction"/"facing", which in turn requires having animation frames in particular loops; but object does not have that explicitly. IMHO Room Object is supposed to be a very simple struct that does not have any special built-in behavior, but allows to program itself in script.
This is why I tend to disagree with the argument about consistency between characters and objects in this regard.

My reasoning behind the change is that it works better for "default" case when you do not expect any special behavior. At the same time function still may be used to sustain or update running animation in any way you prefer (passing corresponding values).

**Comment by messengerbag** [comment]
It's probably done this way for consistency with `Character`, right? Where you don't want changing the view to affect the loop (direction) of the character.

**Comment by ivan-mogilko** [comment]
But Object does not support loops for direction, unlike character loops are not changed when you move object around.

**Comment by ivan-mogilko** [comment]
Hmm, I made a small research regarding original (legacy) functions. Earlier there were two functions later merged into Object.SetView:
* SetObjectView
* SetObjectFrame

Quoting their manual entries from AGS 2.55:

> SetObjectView
SetObjectView (int object, int view)

> Sets object number OBJECT's view to VIEW. **The graphic is set to the first frame of loop 0 of the view.**

and

> SetObjectFrame (int object, int view, int loop, int frame)

> Sets object number OBJECT's graphic to frame FRAME of loop LOOP of view number VIEW. This is useful if you want the object to use the second loop in a view for an animation, **because using the SetObjectView function in room startup code will cause loop 0 to breifly flash on the screen first.**

(Notice that SetObjectFrame did not have optional arguments, all were required)

So, apparently, this is not only a convenience issue, but also the new Object.SetView seem to contradict to the original SetObjectView's behavior.
*Which means that there's also a backwards-compatibility bug in the engine* (running old games may produce different results).

**Comment by ivan-mogilko** [comment]
Another small update to the above comment, looking into the code of the legacy SetObjectView function, it actually *did* keep the loop, on contrary to what manual sais, but frame was reset to 0 anyway.

**Comment by ivan-mogilko** [comment]
Done: #942
