### ISSUE TITLE
SaveLoadEnabled room property is no longer accessible but remains in room data

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#946]
SaveLoadEnabled was a room property that affected SaveDialog() and RestoreDialog() script functions, preventing them from actually showing these dialogs when player is in particular room, and displaying a standard message.

This property was deprecated and hidden in the property list, but it is not automatically removed from the room data during recompilation. This means that if you import a room made with older version of AGS which had SaveLoadEnabled set to false, then you are going to be stuck with that setting, and it affects the game (if you are using above script functions).

The two most obvious options here are:
* make this option visible again, marking it as deprecated;
* forcefully reset this option when importing an older room.
the latter would alter the game behavior but at least this is something user can fix in script.
EDIT: also might add a warning (comment) in the room script, briefly explaining this situation.

**Comment by ivan-mogilko** [comment]
Fixed by 5ec52bab21bb1e1dfb8e519d39e8bac5a906bb3f

Maybe i spent too much time on this...
