### ISSUE TITLE
CI: linux binary package name

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#947]
Please, rename `ags_x.x.x.x_linux.tar.gz` into something like `ags_x.x.x.x_linux_bin.tar.gz` to clarify that these are binaries (and also in case we will be uploading something else for linux later).

**Comment by morganwillcock** [comment]
> AGS-3.5.0.18-RC2.exe
AGS-3.5.0.18-debug.apk
AGS-3.5.0.18-pdb.zip
AGS-3.5.0.18.zip
ags_3.5.0.18_amd64.deb
ags_3.5.0.18_i386.deb
ags_3.5.0.18_linux.tar.gz
ags_3.5.0.18_source.tar.bz2
ags_3.5.0.18_source.tar.gz
ags_3.5.0.18_source.tar.xz
ags_3.5.0.18_source.zip

They are all binary packages, except for the ones labelled as source. It isn't too hard to change, but labelling one binary archive as 'bin' and then not doing the same for other platforms would seem to make it less consistent.
