### ISSUE TITLE
CI: windows zip name

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#948]
I do not know if this is trivial, but wonder if it's possible to name built windows ZIP archive similarily to the installer exe, with special tag attached, like AGS-3.5.0.18-RC2.zip.

**Comment by morganwillcock** [comment]
It is a little tricky to parse this value without adding more dependencies or scripts, but it happens that the installer is already on disk whilst the archive is being written, so just taking the filename from that wasn't much of a change. So updated in https://github.com/adventuregamestudio/ags/commit/dcfd5358a0abf127adf48d74baf93440cbe7e33c.

https://api.cirrus-ci.com/v1/task/5589059753213952/logs/create_checksums.log
