### ISSUE TITLE
libcda contains non-free code

### ISSUE THREAD

**Issue by rathann** [adventuregamestudio/ags#949]
While preparing a package for Fedora Linux distribution, we found that [djgpp.c](https://github.com/adventuregamestudio/ags/blob/master/Engine/libsrc/libcda-0.5/djgpp.c) and [bcd.doc](https://github.com/adventuregamestudio/ags/blob/master/Engine/libsrc/libcda-0.5/bcd.doc) from the original BCD code are licensed under _swap-ware_ license, which is [non-free](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/message/BSJAUOYSUXZS4LAEGBW73E5JPA5MOUOT/). Please remove `djgpp.c` and `bcd.doc` from the source tree. They don't seem to be referenced anywhere in the code.

**Comment by ivan-mogilko** [comment]
It's for DOS, which is no longer supported, so should be safe to remove.

@rathann could you clarify just in case which branch/release are you using for distribution?
I think we should remove from all active ones (3.4.*, 3.5.0, master).

**Comment by sonneveld** [comment]
Created pull requests https://github.com/adventuregamestudio/ags/pull/951 , https://github.com/adventuregamestudio/ags/pull/952 , https://github.com/adventuregamestudio/ags/pull/953

**Comment by rathann** [comment]
Thank you for such quick response!

@ivan-mogilko I am packaging 3.4.4.1 and will update to 3.5 when it's released, unless you have some other suggestions.

**Comment by rathann** [comment]
Fedora is RPM-based. What do you mean by "debian packaging pipeline"?

**Comment by ivan-mogilko** [comment]
@rathann sorry for delay! the files are now removed.
Do you also need me to create new release tag?

**Comment by rathann** [comment]
@ivan-mogilko no problem, thank you very much. It would be nice to have an official release I can point to directly, yes.

**Comment by ivan-mogilko** [comment]
Done: https://github.com/adventuregamestudio/ags/releases/tag/v.3.4.4.2
