### ISSUE TITLE
Object.Scaling available from Script

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#954]
Currently it's not possible to manually scale an object from Script. I would like it was possible similar to how it's possible for Characters, through Object.Scaling. This may require and additional property to enable disable manual scaling, like Character.ManualScaling, but instead Object.ManualScaling.

**Comment by ericoporto** [comment]
I don't know if there's a reason why scaling is limited to 5 to 200 (is stored as a short for instance), but if there isn't, I would really like it to be able to go bigger than 200. A 5 to 1000 limit would be good enough for my usage.

**Comment by ericoporto** [comment]
Just for register, the probable reason for the 5 to 200 limit for character scaling is due to the walkspeed linked to scaling on : https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/character.cpp#L2038

**Comment by ivan-mogilko** [comment]
Done #1033
