### ISSUE TITLE
Theora video playback may be rendered incorrectly

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#956]
This is a very old issue. Several users in the past have encountered a problem where AGS renders Theora video playback with a little vertical offset, cutting of several pixels from the top.

Investigation showed that there are actually two issues with AGS code and apeg library it uses.

1) For some reason, apeg library's function `apeg_get_video_size` does not return values received from Theora decoder, but instead tries to calculate them based on "aspect ratio" value, producing strange results (this may be have some meaning in theory, but in practice these don't work). E.g. for a 320x200 video it may return 426x200 resolution.
https://github.com/adventuregamestudio/ags/blob/release-3.5.0/Engine/libsrc/apeg-1.2.1/mpeg1dec.c#L616

2) In the playback callback AGS relies on the size of `theoraBuffer` bitmap, which is returned by apeg, to position video on screen.
https://github.com/adventuregamestudio/ags/blob/release-3.5.0/Engine/media/video/video.cpp#L233
But this bitmap _is not necessarily matches original video resolution_. Instead its size depends on Theora's internal mechanism. According the Theora docs:
<pre> * Encoded theora frames must be a multiple of 16 in width and height.
 * To handle other frame sizes, a crop rectangle is specified in
 * frame_height and frame_width, offset_x and * offset_y. The offset
 * and size should still be a multiple of 2 to avoid chroma sampling
 * shifts. Offset values in this structure are measured from the
 * upper left of the image.</pre>
However, neither apeg nor AGS acknowledge this. When apeg gets theora's video header it discards this important information and therefore cannot report it to the external user (AGS in this case).

**Example**

Following 320x200 video may be used to reproduce the issue:
[VideoSync_Test_320x200.zip](https://github.com/adventuregamestudio/ags/files/8056769/VideoSync_Test_320x200.zip)

* Original video is 320x200;
* apeg_get_video_size reports 355x200;
* the actual frame buffer returned by apeg is 320x208.

**What has to be done:** we need to get full information on the video frame from Theora and use it to correctly position that frame on screen. This may be done either by amending apeg library source, or writing our wrap over theora functions, whichever convenient.

**Backward compatibility:** it is not clear whether anything is necessary. Existing games may have accomodated for this mistake by resizing the video, but unlikely they had any workarounds done in game itself. For now I think we may not do anything in this regard. Later if something comes up it will be possible to switch behavior based on game data format or anything else that would be suitable to test (like script API version), and position video in an "old way".

**Workaround:** the solution currently is to increase the size of video, to make its resolutions multiples of 16, and place actual image in the center.

**Comment by ivan-mogilko** [comment]
Possibly fixed by fee0b22a91e47165a5513bf6bb9dadc4e5932e14.

More tests may be needed. The good way to test is to make a video where width/height sizes are NOT multiplies of 16. Example: 320x200, but also may be anything else.

**Comment by rofl0r** [comment]
```
~/games/ags $ find -iname '*.ogv'
./agdi_qfg2/F/AGDI.OGV
```
seems quest for glory 2 by agdi has such a video.

**Comment by ivan-mogilko** [comment]
Pushed a "backward compatible" fix: 757335c55c2908c4a9a0c179415b834ca5cfce0c.

Frankly, this accounts only for non-stretched "wrong" video behavior. In the stretched mode the "wrong" videos were repositioned in a quite weird way, which is technically possible to simulate, but that will make code more complicated. So i'd rather don't do that until some old game is found where this is really necessary.
