### ISSUE TITLE
Edit this room's room? (layout weirdness)

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#957]
![ags](https://user-images.githubusercontent.com/22618469/67144454-ad5b1100-f276-11e9-96e1-fe7fc8a128a2.png)
why is the word room twice in there?
Clicking on the second word Room does nothing, only the small arrow button opens the dropdown.
I suggest removing the word room the second time and only have a dropdown button. And the arrow pointing down is really small, I suggest making this button bigger so it easier to click on.
This should be doable for 3.5.0 final?

**Comment by ivan-mogilko** [comment]
The "Room" is there to select room's properties for editing.

**Comment by morganwillcock** [comment]
The selection is done by clicking the node separators, clicking the nodes does nothing in the majority of cases and when it does do something I'm not sure it is intended. The first node does seem entirely redundant.

So the reality is you end up with three very wide items (the nodes) that are easy to click but do nothing, and two very small items to click (the seperators) that are hard to click and contain all functionaility.

I've already looked at redoing it, but I don't think these controls support the changes to have the functionality entirely on nodes, and the way it is implemented means that the constructor parameter to remove the first node gets ignored. So basically, I think this needs re-doing from scratch.

**Comment by ivan-mogilko** [comment]
> The selection is done by clicking the node separators, clicking the nodes does nothing in the majority of cases

Clicking on "Room" node selects the "Room" in the property grid.

**Comment by morganwillcock** [comment]
> Clicking on "Room" node selects the "Room" in the property grid.

It does this for every node except the final one, it doesn't seem specific to the first node.
e.g. you can click on 'Hotspots' and it also selects the room in the property grid
