### ISSUE TITLE
New room editor only icons, no dropdown

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#958]
![ags2](https://user-images.githubusercontent.com/22618469/67144586-31fa5f00-f278-11e9-948c-aa4f7e06a706.png)

the new room editor is an improvement, but it is still not as easy to handle as it could be. So my suggestion is to have no more dropdowns for the 7 different options but 7 icons (with mouseover text in case someone doesn't know what the icons mean). Since no more additional options came in here since ags 2.72 or even earlier the 7 options while editing rooms are more or less fixed and finite.
Edit: There are no mouseovertexts in ags, this is sad, so we'd need really good icons or written text...

To toggle the visibility of these edit layers 2 buttons under the icons representing the lock and the eye should make this a joy to work with, you see everything at once and it is one click less to change some thing.

The icons in my mockup are crudely drawn, but I'd make some better ones if this is implemented in a way.

Probably not for final 3.5.0 but maybe a thing for 3.5.1...

**Comment by ivan-mogilko** [comment]
Note that there was another suggestion regarding the navigation bar: #763

> So my suggestion is to have no more dropdowns for the 7 different options but 7 icons
> To toggle the visibility of these edit layers 2 buttons under the icons representing the lock and the eye should make this a joy to work with, you see everything at once and it is one click less to change some thing.

Please also note that sometimes a user may want to lock/hide very particular object, not all objects at once. For example if the object is very big and covers most of the room for some reason.

**Comment by selmiak** [comment]
this is also interesting, of course with my suggested layout we'd need some dropdown for the individual elements of that group no matter what. maybe like this 
![ags3](https://user-images.githubusercontent.com/22618469/67567349-079e1b00-f72a-11e9-9385-3b5be0d504ae.png)
here every icon would also be clickable and only one icon can be selected so you know which option you are browsing in the element picker. When you click on the selected icon everything is deselected and the room properties are accessible. Or an extra button for the room properties, maybe that button even does the same as deselecting a selected icon/option.

...   
  
another idea, close to what #763 suggests would be an individual element selector button for every room option, something like this maybe
![ags4](https://user-images.githubusercontent.com/22618469/67567591-70859300-f72a-11e9-8451-623e57fb059e.png)

**Comment by selmiak** [comment]
so do you even consider this?

I can make some icons, but need to know min and max resolution of that image that needs to look good. bigger than project explorer might be good as idk yet how make some icons get the meaning across and maybe with more pixel it is easier...

also is PNG good or rather .svg for maybe bigger icons? most icons in the project explorer seem to be pixelart in a small size, is that the default or can it be 2x the size? also is it default style or can antialiasing from rendering out svg curves happen?

**Comment by ericoporto** [comment]
I see two problems here

- current editor can only focus on one thing, this is clearly conveyed by the current bar, this change doesn't tells right away what is on focus
- if things are added to the room editor (as in new layers, like say we have points or a way to draw polygonal areas), it is not programatically obvious how to deal with this

**Comment by AlanDrake** [comment]
Sometimes I wish this stuff was handled like a photoshop layers pane, or maybe a tree. 
But in such case, where to dump this new pane? How many years before we find the strength to make it?

**Comment by ericoporto** [comment]
With the new xml room format, if we have a command line tool that reads the xml and writes the crm in theory it should be reasonably easy to make an off-editor room editor, by just focusing on manipulation of the xml and forgetting a bit of the rest. This would allow to advance things faster separate of the editor and figuring out a better design.

Until 3.6.0 is properly stable and released I don't think much is going to happen here, since after the room editor change I expect no changes at all on it to hit ags3, only ags4.

**Comment by ivan-mogilko** [comment]
> so do you even consider this?

No, we do not. The current bar is functional, and there were other problems to address in the meanwhile. It's not about icons at all of course, this change will bring additional issues in both code and ui design.

I too think we should not hack the existing navigation bar; instead, in my opinion, we need someone who is good at UI design to rethink the room editor awhole. Perhaps it could go into the direction of "photoshop layers pane, or maybe a tree", as @AlanDrake  suggested. This is also something that I was proposing many years ago on ags forums, but tzachs decided to go other way.

Also, I suggest that these things should be discussed on forums, there's a greater chance to bring more people into this conversation, perhaps even someone who can make a functional prototype, either as a alternate editor, or a standalone program.

**Comment by selmiak** [comment]
the bar is functional indeed but not fun to work with, thus this suggestion. Especially hitting these small arrows for the dropdowns is annoying me thus the idea of huge buttons (that might be icons or just text) that are easy to click and one click less overall in the workflow. Of course is not only about the icons, I am a designer and not a coder, so I want to do my part and motivate the people handling the codebase. 
I like Alan's ideas of a photoshop like pane, that would eliminate another dropdown and give you a nice overview that is always visible and easy to browse but would require an additional pane indeed.
I'd love to discuss this in a thread on the forums, let's go.
