### ISSUE TITLE
new room editor hotkeys

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#959]
coming from #958 I also want to suggest implementing hotkeys for the different room editor states. When they are all visible as suggested in #958 this could be even more fun to work with. I think just having the keys 1,2,3,4,5,6,7 when the room editor is open toggle the different room editor version would ease up working with the room editor. Ctrl+1; ctrl+2; etc could toggle the lock icon on the editor part.

**Comment by ivan-mogilko** [comment]
Close as won't fix, because this is derived from #958 which was also rejected.
