### ISSUE TITLE
Engine mode to have everything saved and read in the game dir

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#961]
In the past multiple users have expressed a wish to be able to make engine save everything in the game directory similarily to how AGS worked originally; this means: user config, game saves, any dynamic data game writes.

As of 3.5.0 there are two separate options for saves path (user_data_dir) and "shared data" path (shared_data_dir), these may be used to remap file saving into game dir, but even with these set engine will still write user config elsewhere (currently - into the common savegame dir).

The suggestion is to introduce a simple boolean config option that would switch engine defaults from using common writeable locations to the game directory for literally everything that engine saves and reads for this game.

**Comment by AlanDrake** [comment]
Or maybe not the game directory but a subfolder/s

**Comment by morganwillcock** [comment]
On Windows this could be pretty confusing, because unprivileged writes to a privileged location will be silently redirected to a per user location (within the user profile). If this feature is added, to work as intended it would need to explicitly bypass the redirection, in-case the game has been copied to a location where the user cannot write, and also gracefully handle being denied access.

**Comment by ivan-mogilko** [comment]
Posted by @legluondunet in #1163

> I'm writing a game script on Lutris (games platform for Linux) which will use AGS.
I need support about an issue.
I put a config file in main game folder, acsetup.cfg.
But when AGS launch it copies this config file in /home/your-username/.local/share/ags/your_game/.
Then AGS only take care of the cfg file located in /home/your-username/.local/share/ags/your_game/.
Modifications done on acsetup.cfg in main game folder are no more taken into account.
Is there a way to tell AGS to not copy config file in user profile and just take in account the config file in main game folder?
Our installs are locale, we don't want to use user profile folder, Lutris should manage AGS option in game folder (or other place we could choose).

**Comment by ivan-mogilko** [comment]
Not exactly how I envisioned this originally, but there is now the option to keep user config in game dir, and save/appdata paths were already customizable. (#1252, 109a9d985f498ed31308e2e97e1b97fa306c87c0)
