### ISSUE TITLE
Game settings enabling/disabling certain audio types

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#962]
This was asked by a user several times in past, to have an option which explicitly turns off initialization of MIDI and XM/MOD audio systems in the engine. The reason is that these may not be necessary for a game, but are still initialized taking internal resources. Also, they may fail initialization, displaying error messages to players, or causing other side effects.

The suggestion is to add at least two options for MIDI and XM/MOD in General Settings (other audio types could be also added if wanted).

It's also necessary to decide what there default value would be. Personally I propose to make them Off by default, because majority of games today don't use these, and turning them on would be a simpler matter for a game developer than dealing with strange warnings for a player.

**Comment by rofl0r** [comment]
> Personally I propose to make them Off by default, because majority of games today don't use these

generally you're right, though my leaning is when adding new switches to default whatever was the behaviour before the addition. this saves from a lot of surprises.

**Comment by ivan-mogilko** [comment]
Things have changed since transition to SDL2, or SDL_Sound to be precise. SDL_Sound does not seem to let enable/disable particular decoders from initialization.

Also, I'm no longer certain if this is necessary, as any initialization errors may be handled (they were handled in pre-3.6.0 version after all).
