### ISSUE TITLE
AssetManager should not rely on current working directory

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#965]
Because games may be run from other directories (like `./mygame/agsgame`) the current working directory may end up in a different location. This is a general engine issue currently. But regardless of how this is solved for the rest of the program, AssetManager should not rely on cwd, and instead require an explicit path to the data directory (would that be relative or absolute) passed same way as a path to the data package. This seems logical, because AssetManager is allowed to search in the directory along with the package (in the order according to the priority option).

If such path is stored in the AssetManager, then all the search is going to be done relative to that path instead of blindly using cwd.

If #963 is implemented, then it may be beneficial to allow registering multiple directories as well (this could be done as a part of #963). From the top of my head, that would be useful when running a game from IDE (where project may have unpacked resources in multiple folders).

**Comment by ivan-mogilko** [comment]
Resolved by 3b22ee9f37ba4e052bc96bba4ad03c50cb67d2c5.
