### ISSUE TITLE
Use matrix functions instead of PlaneScaling struct

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#968]
There's a naive PlaneScaling struct I wrote when needed a uniform way to deal with some 2D coordinate conversions. Consider replacing it with transform matrix and matrix functions, because it will allow to work with camera and game objects rotations would they be implemented.

NOTE: it may make sense to use matrix form and functions compatible with OpenGL everywhere (either implement in the engine yourself (not too hard) or use a third party lib that does that. OpenGL matrices are "column-major" while DirectX expected them as "row-major", but this probably may be accomodated by transposing (mirroring) an input matrix whenever it's passed to the DirectX renderer interface (e.g. withing spritebatch/scene node setup).

**Comment by ericoporto** [comment]
If it's the struct here [Engine/util/scaling.h](https://github.com/adventuregamestudio/ags/blob/6fda61b3536533bab6572cebf1afec90bd69dc66/Engine/util/scaling.h#L110), maybe it could keep some functions as interface but have the data stored in a matrix so it could be retrieved and used directly when needed.

**Comment by ivan-mogilko** [comment]
> If it's the struct here Engine/util/scaling.h, maybe it could keep some functions as interface but have the data stored in a matrix so it could be retrieved and used directly when needed.

Well, yes, it could be a class wrapping around the matrix which provides useful functions, or functions to work with matrix, similar to how it's done e.g. in Direct3D implementation right now. Whatever seem convenient.

**Comment by ericoporto** [comment]
Can this be done in three steps: first, rewrite the storage to be a matrix and keep the api; then redo the renderers to access the matrixes directly; later, rework the "input" part of the API if needed ?

Is it a correct understanding that this would ease #967 implementation?

**Comment by ivan-mogilko** [comment]
> Can this be done in three steps: first, rewrite the storage to be a matrix and keep the api; then redo the renderers to access the matrixes directly; later, rework the "input" part of the API if needed ?

This may be done in any number of steps as seem convenient, but the struct is so simple and its uses are limited to literally 2 or 3 places at the moment, so I doubt that will be necessary.

> Is it a correct understanding that this would ease #967 implementation?

I don't know, this is mostly unrelated.

**Comment by ivan-mogilko** [comment]
I'm in changed mind regarding this, the struct is optimized for simple translations within relatively small integer coordinates, which is what it's used for now. I checked the speed just in case, and it's few times faster than the fp matrix functions; may not be a critical difference as it's not used extensively, but still it might be a better option to simplify its code and get it to some consistency with glm matrix methods, then use where there's a need of simple integer coordinate translations.
