### ISSUE TITLE
D3D driver should clear whole screen before rendering 

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#971]
At the moment the black borders aren't redrawn so if there's a steam overlay or an external shader it will leave a smear over the undrawn regions.
Replicable at fullscreen using the pixelperfect rendering, max round multiplier/keep aspect ratio and reshade with a crt filter that leaks outside the game area.

**Comment by ivan-mogilko** [comment]
Fixed by #974.
