### ISSUE TITLE
Replace Sprites from Source doesn't work correctly for Sprite 1 of a Tiled Sprite

### ISSUE THREAD

**Issue by rdurfee** [adventuregamestudio/ags#973]
If you import a sprite with the Tiled Sprite Import option, if you later use the Replace Sprites from Source context menu on the first sprite (offset 0, 0), it is replaced by the whole image instead of the first tile.

**Comment by ericoporto** [comment]
I tested on the latest 3.5.0.17 build and it does happens for me, but only for the first sprite in a tile import.

Here's a video: https://streamable.com/cs1i9

**Comment by ivan-mogilko** [comment]
Could you tell which version of AGS you were using?

**Comment by ivan-mogilko** [comment]
Should be fixed by #977.
