### ISSUE TITLE
RFC: update sprite cache file to allow 8bit bitmaps with own palette

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#983]
current sprite cache formats (acsprset.spr) either allow specification of a single 256 RGB values palette for all 8 bit images in a pack, or none at all (in which case the palette is assigned by room or script).
it would be nice to have a way to store also 8 bit bitmaps with own palette.
my tests with agsprite have shown that a lot of sprites, even though they are saved as 32bit images, use less than 257 colors so they could be saved in this format internally, saving a lot of space. in the case of quest for infamy, packsize would be reduced from 330MB to 280MB while requiring minimal changes to the existing codebase.

**please don't derail this discussion with talk about a completely new sprite cache format, or just saving compressed pngs etc instead.**

what i'm proposing here is simply adding a new sprite cache version number, in which BPP 5 would mean "1 BPP + palette", and when a sprite with such value is encountered, an additional word containing the length of the palette is read, and the data decoded on the fly into a 32bit image.

**Comment by sonneveld** [comment]
I think we should leave palette techniques for 8bit games, leaving the sprite cache format simple. As you say, there are already other techniques we can introduce for reducing the size.

**Comment by ivan-mogilko** [comment]
> I think we should leave palette techniques for 8bit games, leaving the sprite cache format simple

Well, it's about compression, not about "palette techniques".

On another hand, I don't see how comparing this with other compression kinds (like mentioned PNGs) is derailing, unless you want strictly particular compression type for personal reasons.

Speaking hypothetically, the main question here is of its use to the majority of users. It may not require alot of code to support, but it may not be wanted to support custom formats/hacks if they end up used only by few people (and once introduced, the engine will have to keep supporting them). (And especially if this format can only be achieved by the use of a separate repack tool.)

Also, others pointed me out that atm the biggest problem gamedevs and players are experiencing with sprites **in compiled game** is not their size (this was a direct problem before large file support was introduced), but rather the speed of loading them up.

**Comment by rofl0r** [comment]
> custom formats/hacks if they end up used only by few people

as demonstrated in agsprite, the 8bit+palette version can be automatically generated with almost no cost

> And especially if this format can only be achieved by the use of a separate package/compression tool

well, not this format, no. a compression tool works with the bit depth its given. if you pass 32bit RGB data to png, you'll get a 32bit LZW compressed png. if, otoh, you first find that only 200 colors are used, and turn the picture into 8bit+palette, even the uncompressed version probably already beats the 32bit png in size, but even moreso if you png-compress *that* version.

> would we have to add this compression option into the editor as well?

that would make sense, yeah. in agsprite it's done in about 10-15 lines of code. but it should not be done as an option, but as something that's automatically done if a sprite uses less than 256 distinct colores. so the game author doesn't notice any difference apart from a smaller product.

> I believe the main question here is of its use to the majority of users.

i strongly believe the majority of users will be delighted to see packfile size reduced by say 20% indeed.

> biggest problem gamedevs and players are experiencing with sprites in compiled game is not their size (this was a direct problem before large file support was introduced), but rather the speed of loading them up

if you have 20% less disk IO, you automatically have higher speed. i've so far not come across any acsprset.spr that uses 24 bit either, but a lot of them use 32 bit. that's also quite inefficient (bloats any image saved so by 25% for identical content).

> BTW, since this is proposed not a as a global compression type but as a single image type, does this mean that in case of compressed sprite file there will now be two decompressions of same image?

no, this can easily be done in the same pass, it should even be possible to reuse the existing 8 bit rle decompression routine, since it already deals with a separate palette.

**Comment by morganwillcock** [comment]
> as demonstrated in agsprite

What is agsprite?

**Comment by rofl0r** [comment]
> What is agsprite?

https://github.com/rofl0r/agsutils/blob/master/agsprite.c

**Comment by ivan-mogilko** [comment]
So, I'm looking into this now, as a part of an experiment to introduce better compression types to the ags sprites by a user's request; as RLE naturally does not work too well sometimes (and even when it does it still may be noteably worse than the sprite source size).

We've already found a user's project where saving indexed bitmaps alone reduces sprite file by 4 times (maximum possible with this method), as they use oldschool gfx style.

**Comment by rofl0r** [comment]
> as RLE naturally does not work too well in certain cases (and even when it does it still may be noteably worse than the sprites' source size)

rle works well for images where adjacent pixels use the same color, but not well for those that have different color for almost every pixel. what engine could do is automatically generate rle version, and if it's found to be bigger than original (original size can easily be calculated) store uncompressed version, else rle compressed one. with palettized images rle usually works quite well.

**Comment by ivan-mogilko** [comment]
> what engine could do is automatically generate rle version, and if it's found to be bigger than original

Sorry, I was not clear, by "sprite's source" I was refering to PNGs that people use most of the time now. They are smaller than anything that ags saves currently, compressed or uncompressed.

I was considering to support LZW compression in the sprite file, mostly because engine already has LZW code used for room backgrounds. Initial tests show LZW is much worse than RLE with simple pixel graphics, but may be noteably better with more complicated hires graphics.

**Comment by ivan-mogilko** [comment]
Sorry, I got distracted for a few days, now opened a pr: #1461.
