### ISSUE TITLE
Make GUI drawing compatible with hardware-accelerated sprite stack

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#988]
GUI rendering is currently a slow part in AGS, because it is all done using software operations (controls drawing) and only final result (whole GUI's surface) is converted into texture. Thus there are textures per each GUI, but controls are drawn outside of the renderer (see `guibg` and `guibgbmp` arrays).
Naturally, a slightlest change to GUI or any control on that GUI will result in whole GUI getting redrawn (actually, the situation is even worse, see note below).

Suggestion is to instead create and maintain a DDB (texture) per each GUI Control similarily to how it's done for characters and objects. These textures should then be passed into renderer according to gui/control z-order.

~**NOTE:** This may be viewed as an issue on its own, but currently there's a global flag `guis_need_update`, which is set whenever *anything* on *any GUI or control* changes. When this happens *all of the GUI* gets redrawn.~ This had been fixed.
**NOTE:** This ticket is essential before supporting any kind of GUI transformation (like scaling).

**Comment by ivan-mogilko** [comment]
Forgot to make note, there's a draft pr opened, with couple of issues left unsolved at the time of writing, see more information here: #1393.
