### ISSUE TITLE
Rotating character and object graphics

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#995]
Sometimes, I find myself in need of rotating sprites in AGS. 

In AGS though, the ags object graphics is defined by either their graphic property or the current view applied (along with frame and loop), and a character has a view set, that also decides which sprite to use for that character (again, depending on that character frame and loop). Thus, for me, rotating sprites in an AGS script api level, belongs either to the view or the viewframe - I would argue the view itself is better. 

For the backend implementation of this, it appears it's best to have #968 and #967 solved so that the code is simpler to deal with. 

I also found an alternative algorithm for CPU based rendering that could work IF rotated sprites were to be supported by software renderer at all (or if it still existed). https://www.ocf.berkeley.edu/~fricke/projects/israel/paeth/rotation_by_shearing.html

**Comment by ivan-mogilko** [comment]
> I also found an alternative algorithm for CPU based rendering
Just to make sure, do you know there's DynamicSprite.Rotate?
CPU based rotation of a sprite is already in AGS.

The point is probably in assigning a "Rotation" property to engine objects and make that hardware accelerated. Ideally all of them, from Character to GUI, should have full transform set (position, scaling and rotation).

**Comment by ericoporto** [comment]
> Just to make sure, do you know there's DynamicSprite.Rotate? CPU based rotation of a sprite is already in AGS.

I did not knew that, thanks :)

**Comment by ivan-mogilko** [comment]
Ah, right, there is already a ticket; so for the reference there's a wip PR opened: #1229

**Comment by ivan-mogilko** [comment]
Should be resolved by #1229.
