### ISSUE TITLE
This city at night crashes on the second scene with a animation error

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#997]
**Describe the bug**
"Error: The character 'Tracey' could not be displayed because there were no frames in loop 2 of view 110."

**AGS Version**
 3.5.0.15

**Game**
https://www.adventuregamestudio.co.uk/site/games/game/2313/

**To Reproduce**
1. wait for the intro and dialog to finish
2. Click on the folders on the desk
3. Click on the folder in inventory in the photocopier on the background
4. open inventory and click the copy on the folder
5. look at the folder with magnification glass to get the name
6. place folder in one of the blue file archives
7. repeat until pc asks for a break.
8. talk to female co-worker
9. exhaust dialog after getting the tea
9. repeat 2-6 once and use the new 'secret' folder on the photocopier
10. replace the secret folder on the file archive you got it from
11. talk to female co-worker, mention you feel sick.
12. pc will exit automatically to the second scene, and game will crash once the auto-dialog gets far enough.

**Expected behavior**
People completed this game before, so not a crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux AIVAS 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - ubuntu 19.04

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel Something]
 - OS: [e.g. Android Q]

**Additional context**

**Comment by ivan-mogilko** [comment]
Hmm, I tested with recent version (3.5.0.21) and it did not crash. I played until character is in her appartment and changed clothes.

Does this error reproduce stably for you? and if so, do you maybe have a save made just before the crash?

**Comment by i30817** [comment]
Ahh... I'll pull and build again and write back. Now that i think about it the build is a bit old (2 months).

**Comment by i30817** [comment]
You're right, release-3.5.0 current doesn't crash, my bad.

**Comment by ivan-mogilko** [comment]
Do, I found this was fixed by getting legacy pathfinder back: d12c571f51bbe930884f96bd2fbcea1ea4f18243

Perhaps this view was not proper complete walking view, and new pathfinder had it switch to a missing direction.

**Comment by i30817** [comment]
So it could be a real bug on the new pathfinder?

**Comment by ivan-mogilko** [comment]
> So it could be a real bug on the new pathfinder?

Missing loop is not pathfinder's fault, but that game creators did not supply frames for that direction.

At some point it may be worth investigating what's the difference between paths character takes with new and old pathfinder, and whether the new pathfinder choice is illogical in that scene.
